### ISSUE TITLE
OSX --> cmd + ctrl + space --> no emoji 😩

### ISSUE THREAD

**Issue by mattdell** [telegramdesktop/tdesktop#2886] opened 2017-01-19 20:44 UTC
### Steps to reproduce
1. Use OSX
2. Click in message box where it says "Write a message..."
3. On the keyboard, press cmd + ctrl + space

### Expected behaviour
The user should see the following popup showing emoji characters.
<img width="285" alt="screen shot 2017-01-19 at 20 42 38" src="https://cloud.githubusercontent.com/assets/2536442/22124467/da9c3c8a-de87-11e6-9d75-083c0aa4c146.png">

### Actual behaviour
Nothing happens. User is sad.
<img width="516" alt="screen shot 2017-01-19 at 20 43 23" src="https://cloud.githubusercontent.com/assets/2536442/22124497/f37066b4-de87-11e6-81e7-d8f361c383f0.png">

### Configuration
**Operating system:**
OSX Sierra

**Version of Telegram Desktop:**
1.0.2

### Logs
None

**Comment by mattdell** [comment] 2017-01-19 20:46
To add, this worked in versions prior to 1.0

**Comment by john-preston** [comment] 2017-01-19 21:17
@mattdell I'm afraid it worked in some older version of OS X :( or maybe older version of Qt.

**Comment by mattdell** [comment] 2017-02-14 20:35
@john-preston just to update, is this considered a bug or improvement?

**Comment by stek29** [comment] 2017-02-15 00:21
@mattdell what version of OS X (sic!) have you had before the update? And what was the version of TDesktop?

**Comment by john-preston** [comment] 2017-02-15 07:37
@mattdell I'd consider it a bug, but I have no idea, why it worked before and why stopped now, this isn't something I was ever controlling. So for now it'll stay that way :( until I (or someone else here) will find a way to fix that.

**Comment by mattdell** [comment] 2017-02-15 09:53
@stek29 I'm on MacOS 10.12.3 with Telegram v 1.0.5

This works really well on Telegram for MacOS, so I think I'll switch back until this can be fixed. 😕

**Comment by ben-xo** [comment] 2017-02-17 10:49
I'm fairly sure this changed in a recent version of Telegram (maybe around the 1.0.x mark). It is not an OSX change, as it stopped happening in Telegram on OS's prior to Sierra as well.

**Comment by ben-xo** [comment] 2017-02-17 10:55
Is there a way to download older versions, in order to check when this regression appeared?

**Comment by john-preston** [comment] 2017-02-17 10:57
@ben-xo Here is 0.10: https://updates.tdesktop.com/tmac/tsetup.0.10.0.dmg

**Comment by john-preston** [comment] 2017-02-19 13:01
I've narrowed down, it stopped working when moved from Qt 5.6.0. to Qt 5.6.2 :(

**Comment by stek29** [comment] 2017-03-01 04:57
Have emacs style shortcuts stopped working because of the same problem?

**Comment by ben-xo** [comment] 2017-03-07 16:15
Is this bug closed because the problem is upstream? The related bug link in the previous comment seems relevant, although nobody there has mentioned the Emoji input shortcut, and the implication is that it was "Fixed" in 5.6.1, yet on 5.6.2 it's broken.

**Comment by mattdell** [comment] 2017-03-07 16:20
I would think a bug shouldn't be closed until the fix for that bug is shipped. If the problem is upstream the bug is still occurring and needs to be tracked.

**Comment by john-preston** [comment] 2017-03-07 16:25
@ben-xo this bug is not closed.

**Comment by Aokromes** [comment] 2017-03-08 09:45
#729 ?

**Comment by stek29** [comment] 2017-04-02 19:43
@Aokromes and also #1939, and maybe even other issues related to native macOS text input areas I can't remember.
@auchri What do you think about some kind meta-issue for them all?

**Comment by thomasbiddle** [comment] 2017-04-03 22:30
Verified, seeing the same issue - and confirming that it worked in prior versions.

**Comment by spiritualcoach** [comment] 2017-04-20 20:27
Could you give us any estimated time when it might be fixed? It's very 😰😰😰

**Comment by spiritualcoach** [comment] 2017-04-20 20:54
I just checked alpha 1.0.33 and I like the idea of having a separate emoji/stickers/gifs panel, however, the biggest part is still missing: searching bar for emoji (and stickers).
#627 or #1060 (shortcut for emoji panel) might be a good alternative for Mac OS users.

**Comment by Streppel** [comment] 2017-04-24 02:01
Even though this will (might?) get fixed sometime in the near future, could we see this as an improvement on the emoji panel? Searching emojis by typing related words is insanely faster than picking them up by hand. Don't know how much work this mapping would take, though...

**Comment by alvare** [comment] 2017-11-19 22:11
So is this a QT thing? I couldn't find a bug report over there.

**Comment by stek29** [comment] 2017-11-20 01:39
@alvare [9 comments above](https://github.com/telegramdesktop/tdesktop/issues/2886#issuecomment-283245054)

> Related Qt Bug:  https://bugreports.qt.io/browse/QTBUG-53085

**Comment by ben-xo** [comment] 2017-11-24 15:25
It's tricky to find the bug report on QT because the symptom reported isn't identical to the symptom here. Looks like you'd need to upgrade to QT 5.7 to get the fix?

**Comment by stek29** [comment] 2017-11-26 23:50
@ben-xo It might be not that issue, but even if it's not, TDesktop has patched Qt and maybe the issue is caused by patch.

**Comment by harunene** [comment] 2018-01-16 19:05
How do you think of this Qt issue?
https://bugreports.qt.io/browse/QTBUG-61359
https://codereview.qt-project.org/197138
When it comes to my default example, the bug was resolved.
For your convenience, attach my example project.
[TestQtApp_001.zip](https://github.com/telegramdesktop/tdesktop/files/1636419/TestQtApp_001.zip)

**Comment by kaiserkiwi** [comment] 2018-07-20 12:03
When will the bug be fixed? Switched to macOS recently and it's pretty annoying that I can't use CTRL+CMD+Space in Telegram. Both, macOS and Telegram, are the newest version.

**Comment by erictheswift** [comment] 2019-01-25 04:49
Still relevant. Could not easily find this issue.

Just compare telegram selector:
![image](https://user-images.githubusercontent.com/2434839/51725775-38ef9a80-2075-11e9-9e4e-f1478a9020e3.png)

with short version of native selector:
![image](https://user-images.githubusercontent.com/2434839/51725783-43119900-2075-11e9-93d7-734812f6ef7c.png)

or expanded version:
![image](https://user-images.githubusercontent.com/2434839/51725789-473db680-2075-11e9-9c1d-8c8b5aedf572.png)
 
I would really like to pay (e.g. patreon) in order to get this issue addressed and fixed.

**Comment by erictheswift** [comment] 2019-01-25 04:51
I would really appreciate to donate (e.g. via patreon) in order to get this issue addressed and fixed.

**Comment by riconeitzel** [comment] 2019-06-05 13:37
we tried it here … mine works :D @tobsen's doesn't :D strange!

**Comment by Streppel** [comment] 2019-06-05 13:55
> we tried it here … mine works :D @tobsen's doesn't :D strange!

Could you post a screenshot of your behavior, and also inform your macOS and telegram versions? That would be useful.

**Comment by tobsen** [comment] 2019-06-05 18:47
Mine is "5.3 (171638) AppStore" on "macOS 10.14.5 (18F132)" running in German.

**Comment by riconeitzel** [comment] 2019-06-05 18:49
Telegram: 5.3 (171638) AppStore
macOS: 10.14.5 (18F132) (running in english)

Screencast: http://r.b71a.de/p5oR1b69TS.mov

**Comment by riconeitzel** [comment] 2019-06-05 18:57
I first thought of a collision issue: cmd +space = spotlight
On my computer I changed it to be ctrl + alt + cmd + space … but it wasn't the cause. @tobsen tried my configuration but it didn't work on his machine.

**Comment by Streppel** [comment] 2019-06-05 19:01
This is super weird. Could be useful for further investigations. However I feel this issue has been abandoned, unfortunately, as it is almost completing it's third anniversary.

**Comment by revolutionair** [comment] 2019-08-29 13:30
Why are issues like "Can't type ê ë or other similar characters using the standard mac method #3377" linked to this one?

**Comment by 23rd** [comment] 2020-01-05 23:36
Well, that has to be fixed now. Unfortunately, sometimes appears bug with a menu placement (it's a Qt5 bug), but still it works.

**Closed by 23rd** 2020-01-05 23:36 UTC
Labels: macOS

**Comment by robert-cody** [comment] 2020-01-17 14:03
> Well, that has to be fixed now. Unfortunately, sometimes appears bug with a menu placement (it's a Qt5 bug), but still it works.

This bug is still there, not fixed for latest macOS 10.15.2 (19C57) and Telegram Desktop 1.8.15.

**Comment by 23rd** [comment] 2020-01-17 19:02
> This bug is still there, not fixed for latest macOS 10.15.2 (19C57) and Telegram Desktop 1.8.15.

Yes, that's because 1.8.15 version was released in October, and the version with the version with the fix was on December 31.
