### ISSUE TITLE
Case Invariant Emoji Suggestions

### ISSUE THREAD

**Issue by TheYarin** [telegramdesktop/tdesktop#3985] opened 2017-10-13 20:42 UTC
As a user that chats in telegram in a language other than English, it is quite frustrating to switch to English every time I want to see the emoji suggestions.
It would be lovely if these suggestions will appear even if I type :HEART: instead of :_heart: (without the underscore), so I could just hold the SHIFT key down while typing an emoji search while the input language remains <insert non-english language here>.

Cheers!

**Comment by stek29** [comment] 2017-10-14 11:48
So even GitHub doesn't do this 😅

**Comment by Dyedan** [comment] 2017-10-14 12:47
It seems GitHub gives suggestions even when I write :HEART:, it just doesn't automatically replace :HEART: with ❤️ . I can live with that 😅

**Comment by pentix** [comment] 2018-02-18 15:13
@Dyedan Did you expect something like this?

![telegram_patch](https://user-images.githubusercontent.com/3193006/36353429-adf99508-14c6-11e8-94f0-2966ca8b8f46.gif)

**Comment by Dyedan** [comment] 2018-02-18 16:19
Yes, exactly that!

**Comment by pentix** [comment] 2018-02-18 16:22
@Dyedan I wrote a patch for this and just submitted it as pull request #4429. Let's just hope it gets accepted 😄

**Comment by Dyedan** [comment] 2018-02-18 16:50
Thank you! I hope they'll merge it!

**Comment by MasterGroosha** [comment] 2018-03-12 22:46
@Dyedan since your PR is merged, now we cannot easily type `:D`, `:P` and other short text emoji. Looks like a regression rather than a "feature".

**Comment by john-preston** [comment] 2018-03-13 10:55
@MasterGroosha yeah, I see that effect as well :/ I guess I didn't think this through and perhaps it should be reverted. Not sure yet.

**Comment by pentix** [comment] 2018-03-13 11:10
@john-preston @MasterGroosha I didn't see this either. What about increasing the number of letters needed for suggestion to two? I think nobody really relies on the only-one-char-suggestion since it's a purely speculative thing anyway. This would provide a fix for the cases mentioned above.

**Comment by john-preston** [comment] 2018-03-13 11:26
@pentix I can make the string lowercase (case insensitive autocompletion) in case of two letters and case sensitive in case of one letter  (for :o for example).

**Comment by pentix** [comment] 2018-03-13 11:39
@john-preston This sounds like a good idea. :relaxed:

**Comment by Dyedan** [comment] 2018-03-13 22:06
@MasterGroosha Sorry 😅 
@pentix Excellent idea, I think this will work well!
@john-preston I think it would be better to use case insensitivity when there are *atleast* 2 letters instead of only when there are *exactly* 2 letters, don't you?

**Comment by timocov** [comment] 2018-03-14 16:00
Another case where other emoji is selected is just type `:-D` and then press enter (with enabled `Replace emoji` in the settings).

For now workaround is type space after typing emoji and then press enter, but it is annoying.

**Comment by pentix** [comment] 2018-03-17 09:32
@john-preston I saw your suggested changes in b6e7625, thanks a lot!

**Comment by stek29** [comment] 2018-05-17 05:45
Regression

**Comment by Aokromes** [comment] 2020-01-27 18:01
this issue is still valid on 1.9.8?

**Comment by pentix** [comment] 2020-01-27 18:54
@Aokromes With above's changes all being merged in, I haven't had a similar issue for a while; Seems this can be closed.

**Closed** 2020-01-27 18:55 UTC
Labels: waiting for answer
