### ISSUE TITLE
Older photo is shown as primary profile picture

### ISSUE THREAD

**Issue by yashpalgoyal1304** [telegramdesktop/tdesktop#8558] opened 2020-09-06 18:42 UTC
### Steps to reproduce
Exact steps to reproduce from ground zero yet to be investigated. Meanwhile, think these steps are based off an "attachment" for example when dealing with files related issues.

1.  open [SpeedyQWERTY](https://tx.me/SpeedyQWERTY) profile or the person's profile [this message 🡭](https://tx.me/tgbetachat/390812) was sent in reply to.
2. Check their profile pic in small view
3. Expand the profile picture's view.

### Expected behaviour
The primary profile picture (shown in small view or in chat's view) is the latest one.

### Actual behaviour
Older photo is shown as primary profile picture. (also note the number of current photo and total photos)

| Tdesk | TgAnd | TGX (not replicated) |
| -- | -- | -- |
| ![photo_2020-08-16_02-39-19.jpg] | ![photo_2020-09-06_22-36-27.jpg] <br/> <hr/> <br/> [recording][doc_2020-09-06_23-49-17.zip]  | ![photo_2020-09-06_22-40-10.jpg] |

[photo_2020-08-16_02-39-19.jpg]: https://user-images.githubusercontent.com/19423063/92332755-c262ad80-f09d-11ea-8f5d-6b93f7c7bc4a.jpg
[photo_2020-09-06_22-36-27.jpg]: https://user-images.githubusercontent.com/19423063/92332501-fa68f100-f09b-11ea-95e2-6a81e5bf492c.png
[doc_2020-09-06_23-49-17.zip]: https://github.com/telegramdesktop/tdesktop/files/5180080/doc_2020-09-06_23-49-17.zip
[photo_2020-09-06_22-40-10.jpg]: https://user-images.githubusercontent.com/19423063/92332529-2c7a5300-f09c-11ea-8156-2f0780c0b55b.jpg

### Configuration
- Tdesk 2.2 on W10 1903
- TGand 5.13.0 (1818) on AOSP 7.0N
- TGand -- on --
- **NOT** replicated on TGX -- on --
- **Improperly** NOT replicated on Unigram 4.0 (5098) on W10 1903

### Additional Comments
Discussion from : tx.me/tgbetachat/ [390812](https://tx.me/tgbetachat/390812) to [390848](https://tx.me/tgbetachat/390848)

**Comment by ilya-fedin** [comment] 2020-09-06 19:03
User can set any picture in the list as a primary AFAIK

**Comment by yashpalgoyal1304** [comment] 2020-09-06 20:40
> User can set any picture in the list as a primary AFAIK

how and in which version?? have u tried doing it?? i thought there was no such feature, but i very much wanted it :)

**Comment by ilya-fedin** [comment] 2020-09-06 21:40
> how and in which version??

Only mobile clients have that feature AFAIK

**Comment by yashpalgoyal1304** [comment] 2020-09-07 13:02
i dont have access to a suitable mobile client at the moment, so cant say from my side. if u found some new results, be sure to document them here as well :)

**Comment by ilya-fedin** [comment] 2020-09-07 13:05
Well, this is not a bug
@Aokromes i think you can close this

**Comment by Aokromes** [comment] 2020-09-07 15:54
> i dont have access to a suitable mobile client at the moment, so cant say from my side. if u found some new results, be sure to document them here as well :)

memu can do the job :)

**Closed** 2020-09-07 15:55 UTC
