### ISSUE TITLE
[Feature Request] - Some features on the mobile apps that TDesktop is missing

### ISSUE THREAD

**Issue by hartkotet** [telegramdesktop/tdesktop#7852] opened 2020-05-09 12:51 UTC
Please add the following features that exist on the mobile app(s): 

- Ability to edit scheduled messages + a reschedule option
- Muted chat indicator (crossed out loudspeaker) display in the chat list + actual chat
- Ability to adjust the quality of videos when sending 

Thanks in advance.

**Comment by RememberTheAir** [comment] 2020-05-11 06:41
You should open one issue for every one of your request, since it's a mess to mix all the discussion related to your re

**Comment by RememberTheAir** [comment] 2020-05-11 06:50
You should open one issue for every one of your request, because:

- it would be a mess to mix all the discussion related to your three request under one issue
- it's hard for people looking for information about these things to find this issue using the issues search, given this generic title
- it's easier to redirect to an atomic issue when people post duplicates
- people administrating this repo can close some of these three request as duplicate, and right now it's impossible since all of these are all here in the same issue 

Anyway:

> Ability to adjust the quality of videos when sending

Duplicate of #6161

> Muted chat indicator (crossed out loudspeaker) display in the chat list + actual chat

Duplicate of #5981

> Ability to edit scheduled messages

Duplicate of  #6496

> + a reschedule option

Duplicate of #6694

**Closed** 2020-05-11 06:51 UTC
