### ISSUE TITLE
version 1.1 ruins UX with forced sticker window

### ISSUE THREAD

**Issue by Silur** [telegramdesktop/tdesktop#3402] opened 2017-05-15 09:38 UTC
I have JUST enough space on my screen for the app to trigger the always-visible sticker and emoji sidebar, but this completely ruins my user experience since now 40% of the space goes to the contact list, another 40 for the sticker sidebar and only 20% remains for me to actually type.

Would be nice If I had an option to make this sidebar disappear

**Comment by omggga** [comment] 2017-05-15 10:08
>this sidebar disappear

+++

**Comment by skobkin** [comment] 2017-05-15 10:11
Seems like duplicate of #3399

**Closed** 2017-05-15 10:42 UTC
