### ISSUE TITLE
You can't disable notifications for pinned messages in groups

### ISSUE THREAD

**Issue by Squirrel2020** [telegramdesktop/tdesktop#3890] opened 2017-09-13 13:36 UTC
### Steps to reproduce
1. Subscribe to any group
2. Disable notifications 
3. And admins will annoy you with pinned messages with the only option of deleting group to disable pinned notifications 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment] 2017-09-13 13:37
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/1864.

**Comment by Squirrel2020** [comment] 2017-09-13 13:38
So much years left, and pinned message piss me off!

Why you're so lame at user experience

**Closed by auchri** 2017-09-13 13:37 UTC

**Comment by Squirrel2020** [comment] 2017-09-13 13:39
@auchri if it's exist why bug isn't still unsolved and why it's closed!?

**Comment by auchri** [comment] 2017-09-13 13:40
It's not a bug, it's consistent with other official apps.

If you don't like this behavior, contact [Telegram at Twitter](https://twitter.com/telegram).

**Comment by stek29** [comment] 2017-09-13 21:16
@auchri not consistent with Android which has option to disable it :)

**Comment by rvaleyev** [comment] 2017-11-09 13:04
Hi, how can i Turn on back notifications by pin? Its very important to me

**Comment by Su4oNoK** [comment] 2017-11-09 21:07
"Hi, how can i Turn on back notifications by pin if notification is disabled on group chat? Its very important to me"
I have same problem

**Comment by auchri** [comment] 2017-11-09 21:12
You can turn them back on at the same place where you turned them off.

**Comment by vlvrmn** [comment] 2017-11-09 21:15
We mean that pinned messages are not showing up, when notifications are turned off in group. That all what we need back, or a new switcher. Pinned messages are not showing 2 days already. Who we need to write a letter, tell us please)

**Comment by vlvrmn** [comment] 2017-11-09 21:23
> Pinned messages
> You can pin any message to be displayed at the top of the chat screen. All members will get a notification — even if they muted ordinary messages from your group.
[https://telegram.org/faq](url)

That how exactly it used to work, and what we need. If you need 100+ bumps or more, let us know, we will cooperate. Thnx

**Comment by auchri** [comment] 2017-11-09 21:27
Ok, but how is this related to Telegram Desktop?
You can contact Telegram on Twitter: https://twitter.com/telegram

**Comment by vlvrmn** [comment] 2017-11-09 21:35
Thaks man
