### ISSUE TITLE
[Feature Request] Dinamically link qt5

### ISSUE THREAD

**Issue by paoletto** [telegramdesktop/tdesktop#24798] opened 2022-07-17 09:51 UTC
### Is your feature request related to a problem?

I'd like to open youtube links in app like on mobile.  But statically linking webengine would make the binary size explode.

### Describe the solution you'd like

Allow to use dinamically linked Qt5

### Describe alternatives you've considered

Statically link everything. But already now the binary size is 125MB. With webengine it would be at least twice the size.
It would be however an acceptable workaround to provide a version with statically linked webengine

**Comment by john-preston** [comment] 2022-07-17 09:51
@paoletto Qt webengine doesn't allow static linking anyway.

**Comment by ilya-fedin** [comment] 2022-07-17 22:27
@paoletto Qt Web Engine is not used and there's no plan to use it. I'd say the issue is wontfix given that.

**Closed** 2022-07-17 22:31 UTC
Labels: enhancement
