### ISSUE TITLE
current telegram from flatpak is crashing

### ISSUE THREAD

**Issue by marcosps** [telegramdesktop/tdesktop#8564] opened 2020-09-08 03:22 UTC
### Steps to reproduce
1. flatpak run org.telegram.desktop
2. crash
3. 

### Expected behaviour
Telegram opening

### Actual behaviour
Telegram crashes

### Configuration
Linux - openSUSE Tumbleweed (20200906)

Telegram 2.3.2

Flatpak 1.8.2

**Used theme**: default

flatpak run org.telegram.desktop

(process:2): Telegram-WARNING **: 00:21:44.259: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 00:21:44.260: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 00:21:44.260: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported
Gtk-Message: 00:21:44.505: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:21:44.505: Failed to load module "canberra-gtk-module"
Telegram-Message: 00:21:44.515: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
The X11 connection broke (error 2). Did the X11 server die?

**Comment by ilya-fedin** [comment] 2020-09-08 09:44
Duplicate of #8506

**Closed** 2020-09-08 12:52 UTC
