### ISSUE TITLE
Overfeature: fetching link content

### ISSUE THREAD

**Issue by WrongBit** [telegramdesktop/tdesktop#10472] opened 2021-03-05 08:26 UTC
When I send URL, **I already saw it**. WHY T again fetches URL content and shows to me?? Stop doing unnecessary work, just let us exchange normal text of URLs. Fetching content IS NOT YOUR JOB - it must be done by browser on addressee side.

**Comment by RememberTheAir** [comment] 2021-03-05 08:54
Fetching links previews is a pretty established behavior across literally every messaging app (whatsapp, signal, matrix/element, skype, discord, slack, mattermost... I really can't think about an IM that doesn't have this feature). The popup that appears allows you to know whether a link preview is available or not, and eventually to dismiss it and send the message without it

**Comment by WrongBit** [comment] 2021-03-05 09:02
Using finger to inspect nose even MORE widely used feature - why to repeat??
It seems my words are skipped w/o understanding, but I'm ready to repeat important part:

> When I send URL, I already saw it

What the purpose to WASTE MY TRAFFIC and SHOW ME AGAIN the content I already seen? Answer THIS question please.

**Comment by WrongBit** [comment] 2021-03-05 09:06
Using analogy: you DO NOT play music AGAIN if you send somebody MP3. You DO NOT open PDF if you send somebody your doc. So why the hell you need to load URL?? Especially when it was ALREADY LOADED in browser???

**Comment by RememberTheAir** [comment] 2021-03-05 09:30
Telegram doesn't open the webpage on your face when you paste an url in the input field, it shows you an extremely minimal sneak peek of its content. It's like showing a thumbnail of a PDF document you're sending, rather than showing you the full document again as you said. Also, the link preview is fetched by the server (so your machine doesn't directly send the request to the url to fetch the whole page), that then sends back to Telegram Desktop an object containing just the relevant information stripped of all the useless stuff. The bandwidth usage is really minimal

**Comment by john-preston** [comment] 2021-03-05 09:35
@WrongBit This is done for the receiver of your message, not for the sender. But it is shown to the sender as well, because the sender should see the message the same way the receiver will, so that he understands what he sends. Preview is fetched by the server.

**Comment by WrongBit** [comment] 2021-03-05 10:07
@RememberTheAir : good point about "server fetches"! I didn't know that and to me process looks like _I_ waste traffic (surprise, I pay for every byte!). But anyway now I look at sent URL and I see at least 200 bytes of content (+ picture!!) was loaded **by me** from your server. This "preview" occupies HALF OF SCREEN in a message stripe. Sorry, what the hell I should see it again and again?? I don't ask too much - I ask OPTION to let **me** decide, do I want to see all those previews or not. ESPECIALLY when preview doesn't look like small box (as in picture case), but it's a whole readable page! It's too much unnecessary work and wasted space.

**Comment by WrongBit** [comment] 2021-03-05 10:11
@john-preston : again the case "taking too much decisions for user". Why you think I care how URL will look at addressee side?? It's HIS problem - maybe he uses `lynx` to browse! But instead just showing me my URL (just text) you load content and I have to waste HALF of my vertical space just to... SEE AGAIN what I saw before?? Man, don't be Microsoft! More you think instead of user - more MISTAKES you do. Preview is not a "must have feature", but optional thing. I recommend to make OPTION and **user** will decide on what he wanna waste space.

**Comment by WrongBit** [comment] 2021-03-05 10:16
For your sure I prepared a screen how it looks:
http://www.lonehearts.org/pvt/WastedSpace.PNG
I sent URL, which must take 40 pixels. Instead I see A WHOLE PAGE WITH PICTURE of content. And this content waste MY traffic and space. Serious?? Every time I see history, I must watch this huge Карныярык?? Sorry, but not. Usability again wrong.

**Comment by catSIXe** [comment] 2021-03-06 12:08
Paste your link, Ctrl-A, Ctrl-Shift-M , done you formatted your link in Monospace-Markdown

**Comment by WrongBit** [comment] 2021-03-07 15:24
@catSIXe : cool, thanks for hint! But it's "woraround" around unnecessary functionality. I don't think chatting must be so complicated. Much easier to make checkbox and do NOT do downloading, than thousands users will "ctrl-shift-m".
Telegram is nothing, but one of messengers, staying behing much more popular Whatsapp and Facebook. So to be popular, it must overtake 'em by 1) functionality 2) usability. And while implementing functions can be costly, usability requires just paying more attention to feedback.

**Comment by AndydeCleyre** [comment] 2021-03-08 17:27
For the sake of completeness, I'm going to add here two answers to @WrongBit's question:

> What the purpose to WASTE MY TRAFFIC and SHOW ME AGAIN the content I already seen? Answer THIS question please.

- Sometimes I create a share-able URL from some otherwise or possibly private space, such as Google Photos, and I like to get the confirmation that the content is (or isn't) accessible to anyone with the shared URL. Watching the behavior of the link preview gives me that assurance.
- Knowing that the other chat members will see the preview, I like to review its appearance before deciding whether the chat is best served by including or omitting that preview.

---

I *like* the feature, but I also understand the desire to disable it, for a yet unmentioned reason: links that, when visited, *do* something, such as making the content no longer accessible (share-once downloads). 

But for that case, disabling previews only for yourself will not affect the other user's clients previews/link-fetching. You'd want to attach the setting to the message itself, not the client. You can already do this *after* the link gets fetched by closing the preview, which is something, but still a problem for this case. It would indeed be useful to prevent the fetch altogether.

---

But @WrongBit's case isn't about that. Some of the expressed frustrations aside, it seems the primary issue is bandwidth budgeting, which is certainly a valid and important use case. Maybe a broadly-applying low-bandwidth mode is in order? 

---

@WrongBit

That said, given the nature of this Telegram client, the dev reluctance to add new settings, and your bandwidth needs, you might be better off using a different client, such as [tg](https://github.com/paul-nameless/tg). I don't know if any others are as good and low bandwidth.

I share your frustration with the tendency of this project to insist it knows what's best for users, against their will, then locking bug reports to silence dissent. I hope that we will see more client competition in the future, but a feature-complete Telegram client is an enormous undertaking, and I'm grateful to have this very good client actively developed.

**Comment by Aokromes** [comment] 2021-03-08 17:56
not a bug, consistent with other telegram applications.

**Closed by Aokromes** 2021-03-08 17:56 UTC

**Comment by catSIXe** [comment] 2021-03-08 17:58
> I share your frustration with the tendency of this project to insist it knows what's best for users, against their will, then locking bug reports to silence dissent. I hope that we will see more client competition in the future, but a feature-complete Telegram client is an enormous undertaking, and I'm grateful to have this very good client actively developed.


well then use tg-cli... there you go, "bandwith efficient"

**Comment by AndydeCleyre** [comment] 2021-03-08 18:31
> well then use tg-cli... there you go, "bandwith efficient"

I don't know if you mean to reply to me, but in case there is a misunderstanding:

- I'm not looking for a minimal bandwidth client right now
- I don't know anything called `tg-cli` that's been maintained at all in the last few years
- I don't know anything called `tg-cli` that's feature complete

**Comment by WrongBit** [comment] 2021-03-09 12:10
@AndydeCleyre : you miss one more important part I mention - SPACE. So shortly my complain is:
1. Telegram does unnecessary work - I do NOT want to see AGAIN what I already saw.
2. Telegram waste my traffic (I pay for bytes)
3. Telegram waste space in a chat window - preview of the link took HALF OF MY SCREEN! (vertically)

I don't ask to do smth extraordinary or expensive in development - just ONE CHECKBOX, which will increase usability of the messenger.

**Comment by WrongBit** [comment] 2021-03-09 12:13
@Aokromes : sorry, where "click the X" I should make and why? Do you mean "close Telegram" button?
I send links and EVERY link content is fetched. I offer option [x] Do not download link preview - direct analogy when you do not play video when you send it. How link differs from that??

**Comment by Aokromes** [comment] 2021-03-09 15:05
the X when you paste one link on top right side of preview. and you look to report for telegram android, not desktop.

**Comment by WrongBit** [comment] 2021-03-10 14:29
@Aokromes : I see no any X in the corner. "and you look to report for telegram android, not desktop." - sorry, are you speaking on English??
Just in case, I use desktop client and NEVER EVER said word "Android". Anyway, feature I request is useful on ALL clients.

**Comment by Aokromes** [comment] 2021-03-10 15:37
https://i.imgur.com/EsrmrTk.png that x
if for all clients such feature request belongs to https://bugs.telegram.org/
