### ISSUE TITLE
Impossibility of sending images and files

### ISSUE THREAD

**Issue by leandrocunha526** [telegramdesktop/tdesktop#16550] opened 2021-07-02 18:12 UTC
### Steps to reproduce
After selecting an image or file to send in a group or private chat, the problem only occurs in 2.8.4.

### Expected behaviour
Previously had a demo of the image to be sent to insert a message.
Problem also occurs with files.

### Actual behaviour
It is not possible to upload the image or file.

### Configuration
**Operating system:**
Arch Linux

CPU: Dual Core Intel Core i5 M 480 (-MT MCP-) 
speed/min/max: 1463/1199/2667 MHz Kernel: 5.12.14-arch1-1 x86_64 Up: 55m 
Mem: 1312.9/3791.6 MiB (34.6%) Storage: 465.76 GiB (5.2% used) Procs: 209 
Gnome Shell version 40.2 

**Version of Telegram Desktop:**
2.8.4

https://github.com/archlinux/svntogit-community/blob/cb08704c93d8ede52b48d80dcfd8c3cb1ee81d24/telegram-desktop/repos/community-x86_64/PKGBUILD

By @svenstaro

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
distribution package

**Used theme**:
Default (dark mode)

<b>Logs</b>:

(telegram-desktop:4530): lib_base-WARNING **: 15:05:11.148: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
lib_base-Message: 15:05:11.149: This can be ignored by setting DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
lib_base-Message: 15:05:11.149: GTK integration can be disabled by setting DESKTOP_APP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to some features being unavailable.

(telegram-desktop:4530): Telegram-WARNING **: 15:05:11.149: Application was built without embedded fonts, this may lead to font issues.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.gl: Choosing xcb gl-integration based on following priority
 ("xcb_glx", "xcb_egl")
qt.qpa.gl: Xcb GLX gl-integration created
qt.qpa.gl: Xcb GLX gl-integration successfully initialized
qt.qpa.gl: Requested format before FBConfig/Visual selection: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.qpa.gl: Available GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_video_sync 
qt.qpa.gl: Got format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
error: : cannot open
error: : cannot open
error: : cannot open
qt.qpa.gl: Requested format before FBConfig/Visual selection: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.qpa.gl: Available GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_video_sync 
qt.qpa.gl: Got format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 0, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.qpa.gl: Requested format before FBConfig/Visual selection: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.qpa.gl: Available GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_video_sync 
qt.qpa.gl: Got format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
  OpenType support missing for "Open Sans", script 18
  OpenType support missing for "Open Sans", script 12
  OpenType support missing for "Open Sans", script 11
  OpenType support missing for "Open Sans", script 20
  OpenType support missing for "Open Sans", script 16
  OpenType support missing for "Open Sans", script 14
  OpenType support missing for "Open Sans", script 15
  OpenType support missing for "Open Sans", script 9
  OpenType support missing for "Open Sans", script 13
  OpenType support missing for "Open Sans", script 16
  OpenType support missing for "Open Sans", script 18
  OpenType support missing for "Open Sans", script 11
qt.qpa.gl: Requested format before FBConfig/Visual selection: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.qpa.gl: Available GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_video_sync 
qt.qpa.gl: Got format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 0, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)

**Comment by ilya-fedin** [comment] 2021-07-02 18:16
2.8.4 release is Windows-only and wasn't tested for anything except Windows :(

**Comment by leandrocunha526** [comment] 2021-07-02 18:18
> 2.8.4 release is Windows-only and wasn't tested for anything except of Windows :(

It's being tested now @lya-fedin. :)

**Comment by ilya-fedin** [comment] 2021-07-02 18:18
> It's being tested now @lya-fedin. :)

I mean it's not meant to be built on any other OSes, so there won't be a new release with a fix

**Comment by leandrocunha526** [comment] 2021-07-02 18:21
> > It's being tested now @lya-fedin. :)
> 
> I mean it's not meant to be built on any other OSes, so there won't be a new release with a fix any time soon most likely

I'm doing some debugging here to see what's going on.

**Comment by ilya-fedin** [comment] 2021-07-02 18:21
There's no need to debug, this is already fixed on dev branch

**Comment by leandrocunha526** [comment] 2021-07-02 18:22
> There's no need to debug, this is already fixed on dev branch

Good to know, I can test to see if it fixes the problem here.

**Comment by svenstaro** [comment] 2021-07-02 18:37
Would appreciate a new release with this then. Alternatively I can cherry pick the commit if the next release is too far away. :)

**Comment by levon-isajanyan** [comment] 2021-07-02 19:04
Same problem when user try send file instead of image .
In Ubuntu software just freeze and stuck .

**Comment by leandrocunha526** [comment] 2021-07-02 19:06
> Same problem when user try send file instead of image .
> In Ubuntu, software just freeze and stuck .

I will update the report. Thanks.

**Comment by ilya-fedin** [comment] 2021-07-02 20:04
> Would appreciate a new release with this then.

dev branch is already in beta state and tdesktop doesn't have parallel stable/beta chanells, it's unlikely that there will be stable release any time soon

**Comment by mlacunza** [comment] 2021-07-02 20:47
I can confirm the bug in Ubuntu 20.04 using Telegram 2.8.4

**Comment by ADPD777** [comment] 2021-07-03 02:16
Hello there.
I'm reportiing that I'm having the same issue in Linux Ubuntu 20.04 LTS and Telegram version 2.8.4 after the recent update.

**Comment by ilya-fedin** [comment] 2021-07-03 02:20
There's no need to write messages like "I have the same issue"

**Comment by leandrocunha526** [comment] 2021-07-03 02:41
@ilya-fedin Do you think it's better to close it or leave it open? Since the issue has been resolved, even with release pending.

**Comment by ilya-fedin** [comment] 2021-07-03 06:27
Usually issues are being closed as soon as there's a fix on dev branch, but I have a feel if that issue will be closed there will be just a lot of new duplicates

**Comment by Aokromes** [comment] 2021-07-03 09:19
> Usually issues are being closed as soon as there's a fix on dev branch, but I have a feel if that issue will be closed there will be just a lot of new duplicates

even with this ticket opened we already have 2 new tickets.
since it's already fixed i will close.
if anyone have this issue compile latest version.

**Closed by Aokromes** 2021-07-03 09:19 UTC

**Comment by leandrocunha526** [comment] 2021-07-03 19:27
Confirmed, problem solved with patch commit 01b4a24 fix freeze after creating file dialog.
patch: https://github.com/telegramdesktop/tdesktop/commit/1261c775d4ca6fb78277ec213794da7c15e304e2.patch
https://github.com/archlinux/svntogit-community/blob/packages/telegram-desktop/trunk/PKGBUILD

**Comment by ilya-fedin** [comment] 2021-07-03 19:48
The next commit is also important, it fixes popping event loop context in case portal doesn't work and it fallbacks to other dialog implementation
