### ISSUE TITLE
French language during the installation process

### ISSUE THREAD

**Issue by mdan312** [telegramdesktop/tdesktop#4697] opened 2018-05-16 10:08 UTC
Installation program should propose French as a supported language.  
The application works in French! 
Many people do not understand English and do not install Telegram when seeing the lack of French in the list of the install program

**Comment by stek29** [comment] 2018-05-17 05:42
The problem is that languages are requested from Telegram server, so having an up-to-date language list in installer would require making custom installer with complete MTProto client in it, which imo isn't really worth it. Installer can just specify that there are way more languages in the app itself I guess.

Also, I can't really imagine those "many" people tbh

**Comment by mdan312** [comment] 2018-05-17 07:59
Well for example my parents / grand parents were reluctant to install Telegram because of that... 
I had to do it for them.
Yes indicate that many other languages are available once installed would be a good thing.

**Comment by stek29** [comment] 2018-05-18 19:29
Fixed in c43dcf056797cb08069c7707abdf3ca99780a0d8

**Closed** 2018-06-01 06:44 UTC
