### ISSUE TITLE
Broken chat balloons after update v 0.10

### ISSUE THREAD

**Issue by daniloalsilva** [telegramdesktop/tdesktop#2306] opened 2016-08-04 22:04 UTC
After update v 0.10, every message with less than 2 lines broke the chat layout:
![image](https://cloud.githubusercontent.com/assets/1165282/17419711/155a80c6-5a75-11e6-8b5f-b3c7ed2bddcd.png)

I'm not sure if this happens because of my video configuration, but it work properly before this update.

**Operating system:**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10586 N/A Build 10586
System Model:              OptiPlex 390
System Type:               x64-based PC
System Locale:             pt-br;Portuguese (Brazil)

**Version of Telegram Desktop:**
v 0.10

**Comment by john-preston** [comment] 2016-08-04 22:14
@daniloalsilva I can't reproduce that :( but I'll try to fix that by some strict rules on minimal message height, I'll be glad if you'll be able to test a version before I roll it out.

**Comment by slav** [comment] 2016-08-04 23:24
@john-preston I also experience this. Tried clean reinstall of Telegram, didn't help. Will be happy to help as right now Telegram is hard to use (read).

**Comment by john-preston** [comment] 2016-08-05 09:28
@daniloalsilva @slav please check out this build:

https://updates.tdesktop.com/other/Telegram.zip

Does it work fine for you? Thanks.

**Comment by slav** [comment] 2016-08-05 13:37
No, still doesn't work the same.

**Comment by john-preston** [comment] 2016-08-05 14:13
@slav I can't understand that :( Can you contact me at https://telegram.me/preston so I could deploy you test versions directly? I'll enable some logging for the painting and see what the problem is, because blindly (without reproducing at my system) I was unable to guess where the problem can be.

**Comment by john-preston** [comment] 2016-08-05 21:09
@john-preston This should be fixed in 0.10.1 version.

**Closed** 2016-08-06 18:20 UTC

**Comment by daniloalsilva** [comment] 2016-08-08 22:37
Hey @john-preston, I've tested 0.10.1 and now it's working just fine :+1:

**Comment by stek29** [comment] 2016-08-16 17:35
@daniloalsilva that's why he closed the issue :)
