### ISSUE TITLE
Add "Pin to Bottom" Option

### ISSUE THREAD

**Issue by wthreex** [telegramdesktop/tdesktop#5443] opened 2018-12-05 10:57 UTC
Hello there, I think it would be nice you guys add "Pin to Botton" or "Disable Bumping Up" option for Groups/Channel, Due to the fact that some channels sent a lot of messages in one day and i think this is really annoying.

**Comment by RememberTheAir** [comment] 2018-12-05 13:20
Duplicate of #4796

**Closed** 2018-12-05 17:44 UTC
