### ISSUE TITLE
Unable to open file picker

### ISSUE THREAD

**Issue by remcohaszing** [telegramdesktop/tdesktop#7254] opened 2020-02-21 19:42 UTC
### Steps to reproduce
1. Open Telegram on Pop_OS 19.10 
2. Try to open a file, for example by:
  - Selecting a group icon
  - Sending a file to a contact
  - Import or export a theme 

### Expected behaviour
A file picker appears

### Actual behaviour
Nothing, except in some cases a ripple effect.

### Configuration
**Operating system:** Pop_OS! 19.10

**Version of Telegram Desktop:** 1.9.14

**Used theme**: Slightly customized dark theme

<details><summary><b>Logs</b>:</summary>
[2020.02.21 20:29:30] Launched version: 1009014, install beta: [FALSE], alpha: 0, debug mode: [TRUE], test dc: [FALSE]
[2020.02.21 20:29:30] Executable dir: /home/remco/.local/share/Telegram/, name: Telegram
[2020.02.21 20:29:30] Initial working dir: /home/remco/
[2020.02.21 20:29:30] Working dir: /home/remco/.local/share/TelegramDesktop/
[2020.02.21 20:29:30] Command line: /home/remco/.local/share/Telegram/Telegram --
[2020.02.21 20:29:30] Executable path before check: /home/remco/.local/share/Telegram/Telegram
[2020.02.21 20:29:30] Logs started
[2020.02.21 20:29:30] Checking for XDG Desktop Portal...
[2020.02.21 20:29:30] XDG Desktop Portal is present!
[2020.02.21 20:29:30] Connecting local socket to /run/user/1000/3b3067ea5f4006e4a1e8387a51e75884-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.02.21 20:29:30] Socket connect error 0, starting server and app...
[2020.02.21 20:29:30] Moved logging from '/home/remco/.local/share/TelegramDesktop/log_start0.txt' to '/home/remco/.local/share/TelegramDesktop/log.txt'!
[2020.02.21 20:29:30] Opened '/home/remco/.local/share/TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0
[2020.02.21 20:29:30] Primary screen DPI: 96
[2020.02.21 20:29:30] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2020.02.21 20:29:30] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2020.02.21 20:29:30] Font: from ':/gui/fonts/DAOpenSansBold.ttf' loaded 'DAOpenSansBold'
[2020.02.21 20:29:30] Font: from ':/gui/fonts/DAOpenSansBoldItalic.ttf' loaded 'DAOpenSansBoldItalic'
[2020.02.21 20:29:30] Font: from ':/gui/fonts/DAOpenSansSemibold.ttf' loaded 'DAOpenSansSemibold'
[2020.02.21 20:29:30] Font: from ':/gui/fonts/DAOpenSansSemiboldItalic.ttf' loaded 'DAOpenSansSemiboldItalic'
[2020.02.21 20:29:30] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
[2020.02.21 20:29:30] Getting DE, XDG_CURRENT_DESKTOP: 'pop:GNOME'
[2020.02.21 20:29:30] Getting DE, DESKTOP_SESSION: 'pop'
[2020.02.21 20:29:30] Getting DE, KDE_SESSION_VERSION: ''
[2020.02.21 20:29:30] DE: Gnome
[2020.02.21 20:29:30] App Info: reading settings...
[2020.02.21 20:29:30] App Info: reading encrypted settings...
[2020.02.21 20:29:30] Lang Info: Loaded cached, keys: 2581
[2020.02.21 20:29:30] OpenAL Logging Level: (not set)
[2020.02.21 20:29:30] Audio Playback Devices: OpenAL Soft
[2020.02.21 20:29:30] Audio Playback Default Device: OpenAL Soft
[2020.02.21 20:29:31] Audio Capture Devices: Built-in Audio Analog Stereo;Monitor of Built-in Audio Analog Stereo
[2020.02.21 20:29:31] Audio Capture Default Device: Built-in Audio Analog Stereo
[2020.02.21 20:29:31] App Info: reading map...
[2020.02.21 20:29:31] App Info: reading encrypted map...
[2020.02.21 20:29:31] App Info: reading encrypted user settings...
[2020.02.21 20:29:31] App Info: encrypted user settings read.
[2020.02.21 20:29:31] App Info: reading encrypted mtp data...
[2020.02.21 20:29:31] MTP Info: read keys, current: 3, to destroy: 0
[2020.02.21 20:29:31] Map read time: 2
[2020.02.21 20:29:31] Notification daemon specification version: 1.2
[2020.02.21 20:29:31] Notification daemon capabilities: actions, body, body-markup, icon-static, persistence, sound
[2020.02.21 20:29:31] Export Info: Destroy top bar by controller removal.
[2020.02.21 20:29:31] System tray available: [TRUE]
[2020.02.21 20:29:31] Found Unity Launcher entry telegramdesktop.desktop!
[2020.02.21 20:29:31] Using SNI tray icon.
</details>

**Comment by Aokromes** [comment] 2020-02-21 20:37
try updating to 1.9.15 beta.

**Comment by ilya-fedin** [comment] 2020-02-22 12:35
Duplicate of #7230

**Closed** 2020-02-22 16:46 UTC
