### ISSUE TITLE
2.5.1 "<person> typing" not displaying in chat list for the chat

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#8952] opened 2020-10-31 15:27 UTC
when someone is writing a message for you in a personal chat, there is no "...typing" displayed for this chat in the chat list, you can only see "... typing" it if you open the chat with this currently typing person.

**Comment by john-preston** [comment] 2020-10-31 16:17
@imashxtyz This happens in case his "last seen" status was hidden from you.

**Comment by imashxtyz** [comment] 2020-10-31 18:46
@john-preston "last seen" was hidden from me for a long time, but the issue i described was not in earlier version, before 2.4.5

**Comment by pmarrapese** [comment] 2020-11-06 00:42
+1. This used to appear in the chat list regardless of "last seen" settings; it now only appears within the active chat panel. It's useful to see when typing is occurring in other windows.

**Comment by matteocontrini** [comment] 2020-11-12 10:57
Could this be fixed? It works correctly with other clients, and it worked in previous versions of tdesktop as well.

It doesn't really make sense to hide the typing status in the chats list. It makes even less sense if you consider that you can see that the user online even if the last seen status is hidden, when he's typing...

I think this should be considered as an (annoying) bug and not as the intended behaviour.

**Comment by imashxtyz** [comment] 2020-11-24 17:06
2.4.7 still

**Comment by imashxtyz** [comment] 2020-12-05 21:15
Next update won't be "epic" if this isn't fixed.

**Comment by Aokromes** [comment] 2020-12-05 22:16
oh, it will be, even this isn't fixed.

**Comment by imashxtyz** [comment] 2020-12-28 11:34
not fixed, not epic

**Comment by Thoufak** [comment] 2021-05-23 16:32
Can we have an update on this? Reproduces in 2.7.4. Totally agree with https://github.com/telegramdesktop/tdesktop/issues/8952#issuecomment-726004587

**Comment by matteocontrini** [comment] 2021-11-19 21:44
Still an issue.

**Comment by RememberTheAir** [comment] 2022-05-31 12:09
Is it really intended? As far as I remember, that comment was made during a period of changes from Telegram. If https://github.com/telegramdesktop/tdesktop/issues/8952#issuecomment-726004587 is correct in saying that in other clients, the "typing..." status(es) is correctly shown in the chat list (which I personally remember to be the case, even if I'm not entirely sure), then this is an issue that should be fixed in this client

**Comment by john-preston** [comment] 2022-10-11 04:27
@RememberTheAir I tested now - official Android works exactly like desktop (it doesn't show typing in chats list but it sets local fake online status which it shouldn't, and tdesktop shouldn't), official iOS works correctly (doesn't show typing in chats list, doesn't show local online fake online status). So, this is intended, although local fake online should be fixed in Android / tdesktop.

**Comment by Thoufak** [comment] 2022-10-11 09:37
> @RememberTheAir I tested now - official Android works exactly like desktop (it doesn't show typing in chats list but it sets local fake online status which it shouldn't, and tdesktop shouldn't), official iOS works correctly (doesn't show typing in chats list, doesn't show local online fake online status). So, this is intended, although local fake online should be fixed in Android / tdesktop.

I'm sorry for reopening this. I understand that this makes a lot of sense from a technical point of view. However, it does make no sense at all from the user standpoint and it makes their experience much worse. Why is using a fake local online/typing status bad?

**Comment by john-preston** [comment] 2022-10-14 04:21
I think this is done to keep the "last seen hidden" a bit closer to reality in most cases.

**Closed by john-preston** 2022-10-14 04:21 UTC
