### ISSUE TITLE
Autostart not working on Linux Mint

### ISSUE THREAD

**Issue by gunchleoc** [telegramdesktop/tdesktop#24000] opened 2022-02-01 13:31 UTC
### Steps to reproduce

1. Install the Flatpack version of Telegram Dektop, or get & install the latest version from the Telegram homepage
2. Search for "telegram" in the main menu, right-click and add to autostart
3. Open Telegram and set it to autostart in the Advanced Settings
4. Reboot. Telegram will not autostart
5. Try any combination of 2 & 3 and reboot.  Telegram will not autostart
6. I tried defining the menu shortcut as `/home/<user>/Downloads/Telegram/Telegram -workdir /home/<user>/.local/share/TelegramDesktop/ -- %u -startintray` but that didn't help either

### Expected behaviour

Telegram will autostart on system start after being told to autostart

### Actual behaviour

Telegram will not autostart on system start after being told to autostart - possible regression of https://github.com/telegramdesktop/tdesktop/issues/422

### Operating system

Release Linux Mint 20.2 Uma 64-bit, MATE 1.24.0

### Version of Telegram Desktop

3.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2022-02-01 13:52
`flatpak permission-show org.telegram.desktop`

**Comment by gunchleoc** [comment] 2022-02-01 18:14
| Table        | Object           | App  | Permissions | Data |
| ------------- | ------------- | ----- | ---- | ---- |
| background | background | org.telegram.desktop | yes | 0x00 |

**Comment by ilya-fedin** [comment] 2022-02-01 18:54
Maybe your xdg-desktop-portal backend (or version) doesn't support autostart?

**Comment by ilya-fedin** [comment] 2022-02-01 18:55
Linux Mint 20 is based on Ubuntu 20.04 what means all software installed from the repos is two years old and may not support all the APIS

**Comment by gunchleoc** [comment] 2022-02-02 10:41
I have Signal and Skype on autostart, so it should be possible in theory - of course I don't know which APIs they are using.

The problem with Telegram started when I had to move from the outdated package in the official Repo to the Flatpack - so, a recent change in how Telegram autostarts would certainly explain the problem.

Screenshot for packages versions on my system:

![xdg-versions](https://user-images.githubusercontent.com/4095570/152138520-16cccfe3-37dc-499a-aa7c-650e76eff495.png)

**Comment by ilya-fedin** [comment] 2022-02-02 23:03
> I have Signal and Skype on autostart, so it should be possible in theory - of course I don't know which APIs they are using.

Are they installed through flatpak? Flatpak is sandboxed, so adding to autostart works in a completely another way.

> The problem with Telegram started when I had to move from the outdated package in the official Repo to the Flatpack - so, a recent change in how Telegram autostarts would certainly explain the problem.

Well, there were no change in how Telegram autostarts since autostart was added IIRC

**Comment by ilya-fedin** [comment] 2022-02-02 23:44
> Screenshot for packages versions on my system:

It seems autostart support was added in portals 1.4.0, so versions seem to be ok... Hmm... Which files present in ~/.config/autostart?

**Comment by gunchleoc** [comment] 2022-02-03 18:35
Done, but still not working. I'm wondering if the blank space in the localized "Downloads" directory name might be a problem?

Switching it on and off created the following autostart file:

appimagekit_ddea7328d578c0a94855eb4e72f69bb5-Telegram_Desktop.desktop
```

[Desktop Entry]
Version=1.5
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/<user>/Luchdaidhean a-nuas/Telegram/Telegram
Exec=/home/<user>/Luchdaidhean\\ a-nuas/Telegram/Telegram -workdir /home/<user>/.local/share/TelegramDesktop/ -autostart
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=Quit;
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

[Desktop Action Quit]
Exec=/home/<user>/Luchdaidhean\\ a-nuas/Telegram/Telegram -workdir /home/<user>/.local/share/TelegramDesktop/ -quit
Name=Quit Telegram
Icon=application-exit
```

**Comment by ilya-fedin** [comment] 2022-02-04 01:29
What is not working? I see the desktop file is correct now

**Comment by gunchleoc** [comment] 2022-02-06 10:08
Telegram is not starting after system start. If I right-click on the entry in the start menu, the tick mark is there, so everything looks correct, but it's still not working.

I just double-checked the rights of the executable, it's on `-rwxrwxr-x`, so that looks OK too.

BTW I'm on MATE, not Cinnamon, in case this makes a difference.

**Comment by ilya-fedin** [comment] 2022-02-06 13:35
Are you sure it's not starting? Maybe you've activated the start minimized option and it's starting, just tray icon doesn't work?

**Comment by zaemiel** [comment] 2022-02-08 08:52
I have the same problem. Telegram Desktop won't autostart anymore.
I'm on Linux Mint 20.1 Cinnamon.

**Comment by ilya-fedin** [comment] 2022-02-08 10:23
@zaemiel check what is present in ~/.config/autostart

**Comment by gunchleoc** [comment] 2022-02-08 10:43
> Maybe you've activated the start minimized option and it's starting, just tray icon doesn't work?

Good guess, but removing the tick from "Launch minimized" didn't fix it.

**Comment by ilya-fedin** [comment] 2022-02-08 10:45
:(
Maybe it's something Mint-specific? E.g. there was an update that broke the update mechanism. Because I can't reproduce this nor I have enough space on my SSD to create a VM with Mint.

**Comment by gunchleoc** [comment] 2022-02-08 10:54
Maybe. I just double-checked with `ps aux` and there are no processes with "telegram" in heir name.

**Comment by zaemiel** [comment] 2022-02-08 12:03
> @zaemiel check what is present in ~/.config/autostart

It's the same like gunchleoc has.
I have a solution.
I've made manually a startup command for System Settings > Startup Applications

![image](https://user-images.githubusercontent.com/8142952/152983271-f69ca1a4-ac4d-4805-86d9-c82ae57e7921.png)

And used this command:
`~/Telegram/Telegram -startintray`

It's solved the problem. "Official way" no longer works.

**Comment by mknv** [comment] 2022-02-16 20:53
> It's solved the problem. "Official way" no longer works for me.

Thank you. This works for me.

**Comment by KrazyIvan-** [comment] 2022-02-19 15:36
Problem is Version in .config/autostart/ 
Telegram_Desktop.desktop 
[Desktop Entry]
Version=1.5
Name=Telegram Desktop
....
--- Change to Version=1.5  to Version=1.0 --- and it works
[Desktop Entry]
Version=1.0
Name=Telegram Desktop

**Comment by ilya-fedin** [comment] 2022-02-19 15:37
The version couldn't be change, the file uses features from the version 1.5 of the XDG spec

**Comment by ilya-fedin** [comment] 2022-02-19 15:38
Looks like you should request support for version 1.5 in Cinnamon

**Comment by KrazyIvan-** [comment] 2022-02-19 15:46
run this:
desktop-file-validate .config/autostart/Telegram_Desktop.desktop  ( tname of your file)
Telegram_Desktop.desktop: error: value "1.5" for key "Version" in group "Desktop Entry" is not a known version

just Mint left behind ;-)

**Comment by ilya-fedin** [comment] 2022-02-19 15:50
Yeah, looks like your Mint is too old for this feature now, you should ask Mint developers to add support if you want to use this feature

**Comment by KrazyIvan-** [comment] 2022-02-19 15:57
Linux Mint 20.3 Cinnamon/Ubuntu 20.04.3 LTS same latest LTS. 
better keep Version=1.0 until next LTS release. 
or skip/remove  'Version=..' line in .desktop file also can work.

**Comment by ilya-fedin** [comment] 2022-02-19 16:02
I don't think the progress should be stopped because of LTS

**Comment by KrazyIvan-** [comment] 2022-02-19 16:06
Then if users complain just find this thread fix himself.
Can close the issue now. Not a bug, Ubuntu/Mint LTS not support/left behind in progress :)

**Comment by ilya-fedin** [comment] 2022-02-19 16:20
Yeah, there's no sign that would be supported in 22.04 and waiting another 2 years is not something really wanted here given that tdesktop is bleeding edge by its nature

**Comment by ilya-fedin** [comment] 2022-02-19 16:35
Also, if changing the Version key value or removing it helps, this means desktop-file-validate is unrelated here as it would fail with those changes anyway (either because version 1.0 doesn't support the used keys or because the file lacks the version), so it's most likely a bug in Cinnamon that you need to report if you want to see it fixed

**Comment by KrazyIvan-** [comment] 2022-02-19 16:42
remove just Version=... working fine. Even valide still say error.
---
Telegram_Desktop.desktop: error: file contains key "SingleMainWindow" in group "Desktop Entry", but keys extending the format should start with "X-"
----
Ubuntu/Mint LTS all same. Just remove Version=... and all users will be happy

**Comment by ilya-fedin** [comment] 2022-02-19 16:44
> all users will be happy

Users of Linux Mint will be happy obviously. Not all users though. In other words, changing that would fix for you, but break for users of others DE that conform the spec more strictly. So this needs a fix on Cinnamon side.

**Closed** 2022-02-19 17:16 UTC
Labels: bug, 3rd party issue

**Comment by gunchleoc** [comment] 2022-03-03 17:58
My system still doesn't like it, so I'll just have to start it manually for now.

Thank you all very much for the time spent trying to help me! I fully understand why you don't want to spend more time programming for this.

**Comment by ilya-fedin** [comment] 2022-03-03 17:59
The thing is change needs to be done on Cinnamon side
