### ISSUE TITLE
Set native windows frame

### ISSUE THREAD

**Issue by kamuz** [telegramdesktop/tdesktop#2958] opened 2017-02-01 20:42 UTC
Like into VK Messager

![2017-02-01_22-33-40](https://cloud.githubusercontent.com/assets/587267/22525380/9c181bee-e8cf-11e6-888d-a753b73fde69.png)

That is will be nice for Windows 7, 8, 10

It is better

![2017-02-01_22-35-37](https://cloud.githubusercontent.com/assets/587267/22525313/5e7367ee-e8cf-11e6-90cd-49e1da5f64ad.png)

then this

![2017-02-01_22-36-14](https://cloud.githubusercontent.com/assets/587267/22525324/67151938-e8cf-11e6-87e9-1538579ea293.png)

**Comment by Twilightssuperb** [comment] 2017-02-02 15:28
Only as option. To my mind, Telegram window looks OK with present frame. However the user should have a choice. 🤔

**Comment by liquidplace** [comment] 2017-02-03 06:13
It's necessary because the title bar is now shorter than before and quite difficult to _catch_ minimize button in the first try. In addition, there's no shortcut key for minimizing/closing the window to the tray icon like ESC or double ESC (esc key works only once), except ALT+F4 which is also confusing.

**Comment by john-preston** [comment] 2017-02-03 08:59
@liquidplace You can press Ctrl+W, it closes the window with minimizing to tray. Ctrl+M will minimize the window (leaving the icon in taskbar) and Ctrl+Q will quit the app.

**Comment by Aokromes** [comment] 2017-02-03 17:03
you can allways right click over bar and http://i.imgur.com/VkvKVEu.png

**Comment by ralesk** [comment] 2017-02-08 12:58
A much bigger issue than the bar being small is that it doesn't show difference between focused and unfocused window.

**Comment by MasterGroosha** [comment] 2017-02-12 12:34
@ralesk this is more theming issue since title bar colors are now separated (focused/unfocused states)

**Comment by ralesk** [comment] 2017-02-12 21:22
@MasterGroosha Ah, back in the day when window managers did that for you... :)

**Comment by Aokromes** [comment] 2017-04-01 08:20
this is needed for small sized windows tables, click on the buttons is hard on a sub 10" tablet.

**Comment by maxoku** [comment] 2017-06-02 22:02
I agree, there should be that option. I really hate when apps force their themes into UI elements like title bar.

**Comment by pedrogarcia** [comment] 2017-07-09 19:17
The Close, minimize and maximize buttons are too small on my computer, I can barely click them. If I increase the interface scale, then text and all other things become too big!

**Comment by stek29** [comment] 2017-07-09 20:13
@pedrogarcia That's #2818 :)

**Comment by BoffinbraiN** [comment] 2017-07-19 21:40
I would like to see this too. I'm not a fan of ugly borderless Win8 themes and when tdesktop sits alongside other native Windows 7 applications, it looks out of place and ugly. Applications should always respect the OS' native look-and-feel unless there's a very good reason not to. Please don't copy what Microsoft does.

**Comment by Aerz** [comment] 2017-09-18 12:20
I agree, it would be an option like use custom notifications or use native notifications.

**Comment by ImagoPL** [comment] 2017-12-10 19:51
I agree! I don't like apps, that implements their own window title bars. Why on Linux and MacOS there is no problem with that?

**Comment by john-preston** [comment] 2017-12-10 19:55
@ImagoPL I have custom colored title bar on macOS as well.

**Comment by ImagoPL** [comment] 2017-12-10 19:56
@john-preston oh, so - why on Linux there is no problem? 😄

**Comment by navossoc** [comment] 2017-12-10 19:58
The problem is not the color. That window bar is too thin, the buttons are really small.

**Comment by ImagoPL** [comment] 2017-12-10 20:00
@navossoc Yeah, this is truly the main problem. But I think there should be an option - display native title bar or themed by app.

**Comment by john-preston** [comment] 2017-12-10 20:22
@navossoc It has similar size to the one on macOS.

**Comment by auchri** [comment] 2017-12-10 21:24
@john-preston But it's smaller than the Windows' one.

**Comment by stek29** [comment] 2017-12-10 21:39
btw discord seems to use same frame :)

**Comment by readonly24** [comment] 2018-02-20 14:36
Any updates on this? I'd really like to see native (Windows-)UI look and behaviour.

**Comment by ajyotirmay** [comment] 2018-03-09 07:39
@readonly24 I don't think this issue is being considered important. Native frame is being asked for over an year, but still there's no sign of it being implemented, and that's sad :(

**Comment by readonly24** [comment] 2018-03-12 14:45
@ajyotirmay I still hope someone takes care of this soon.

**Comment by readonly24** [comment] 2018-03-26 09:51
I was hoping, that the new version includes a solution, but we still have this ugly, themed frame. 

Devs, is it **so hard** to implement this?

**Comment by ajyotirmay** [comment] 2018-03-27 15:20
@readonly24 the only thing that comes to my mind is, "they don't want to implement this feature request" :(

**Comment by stek29** [comment] 2018-03-27 18:18
Please keep discussion on topic.

**Comment by readonly24** [comment] 2018-07-02 08:01
How much would it cost to pay a developer to implement native Windows controls? We could crowdfound  it...

**Comment by stek29** [comment] 2018-07-03 10:00
@readonly24 I highly doubt that developer needs money and/or has enough free time to work on this.

**Comment by vrubleg** [comment] 2018-07-13 14:57
Must have feature. Non-standard frame is really buggy, especially its shadow. Sometimes the shadow is visible when the window is not visible. Sometimes the window is visible, but the shadow is invisible. Also it doesn't respect system setting which disables window shadows.

**Comment by eiarhabi** [comment] 2018-10-07 02:58
issue #2818 states that windows can't set a customized color for title bar is a reason preventing native design, but Chrome achieved this but drawing the title bar that accords w/ windows 10 design by itself.

**Comment by vrubleg** [comment] 2018-10-07 06:13
It's OK if Telegram doesn't change color of native title bar. Themes are for children anyway.

**Comment by tdchien** [comment] 2019-06-17 02:11
In the recent version, my computer application sometimes has problems like this
![image](https://user-images.githubusercontent.com/1614393/59574035-d8263480-90df-11e9-88c0-515ad704cdf0.png)

**Comment by vm-scher** [comment] 2019-10-09 06:37
Non-native window frame with taskbar autohiding enabled makes it impossible to activate the taskbar 
with telegram maximized.
I consider it a bug.

**Comment by beppe9000** [comment] 2020-03-28 13:36
This is important to have since there are many desktop customization utilities that rely on the standar windows frame to do trigger macros when left,right,middle-clicking titlebar and buttons, or add new items to system menu.

**Comment by widersky** [comment] 2020-03-30 06:25
> Must have feature. Non-standard frame is really buggy, especially its shadow. Sometimes the shadow is visible when the window is not visible. Sometimes the window is visible, but the shadow is invisible. Also it doesn't respect system setting which disables window shadows.

I have the same issues, really annoying. I really don't like this small window titlebar. If Telegram devs really don't like to implement Windows native titlebars, maybe only implement window controls like it's in Messenger desktop app?

![image](https://user-images.githubusercontent.com/45122321/77881772-eead0f00-725f-11ea-9e2c-076661f38190.png)

**Comment by beppe9000** [comment] 2020-03-30 13:04
actually I think they "unimplemented" the default window frame.

**Comment by lbcake** [comment] 2020-03-31 19:44
> @liquidplace可以按Ctrl + W，它将关闭窗口并最小化到托盘。Ctrl + M将最小化窗口（将图标保留在任务栏中），而Ctrl + Q将退出应用程序。

这些快捷键 从哪里可以看到详细的？

**Comment by liquidplace** [comment] 2020-03-31 23:32
@lbcake oh come on, you really think i can read chinese? On what grounds? And on top of that, you really think i care even a tiny bit supporting a comment i made THREE YEARS ago, just because you are necro'ing a long dead issue? 

Bye bye.. 👋

**Comment by beppe9000** [comment] 2020-04-01 00:31
@lbcake see the [wiki](https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts)

**Comment by liquidplace** [comment] 2020-04-01 01:57
Yes i did, sorry. I only stated that this tiny button is hard to click. 

I guess lbcake was not replying to me, he misquoted another reply:
https://github.com/telegramdesktop/tdesktop/issues/2958#issuecomment-277196937

**Comment by efeciftci** [comment] 2020-07-01 13:52
Starting with the 2.1.14 beta, Telegram window started implementing CSD and display its own titlebar on my KDE Plasma based Linux distro. Now instead of displaying the titlebar drawn by KWin, it is displaying a narrower imitation of ugly Windows 10-ish titlebar.

![image](https://user-images.githubusercontent.com/3438150/86250050-c31c2680-bbb8-11ea-94cd-1b6c2a073c5f.png)

The current implementation has the following problems:
- It does not follow KWin theme; it stands out from all the other windows with an inferior titlebar theme.
- Active or not, it is impossible distinguish. The titlebar is always painted gray.
- Window title is not displayed.
- Since Telegram is no longer using KWin's decorations, it is impossible to move/reorder the window control buttons or add additional buttons as "Keep above".
- It provides no customization options as provided by the native window manager. It is impossible to imitate KWin theme in Telegram CSD.

In many senses, the current CSD implementation is inferior than what window managers can offer. Please add an option to turn on and off CSD in Telegram and let window managers to handle things out of Telegram's scope if and when desired.

**Comment by ajyotirmay** [comment] 2020-07-01 14:18
Okay, this is very upsetting now. I don't even think maintainers or devs are even being considerate or polite at this point. There have been no official acknowledgement of this issue, it's been 3 years since this issue was opened, and now they've even started to bring the same awful and widely rejected design to Linux, throwing logic right out the freaking window!

**Comment by ilya-fedin** [comment] 2020-07-01 22:07
> Telegram's borders and titlebar do not follow KWin theme

It's ok since they follow Telegram theme. It's strange if you have titlebar in one style and content in another. KWin decorations are good for applications that are using system widgets, but for custom widgets, custom titlebar fit better.

> Window title is not displayed.

Telegram has not so much helpful information in the window title...

> it is impossible to move/reorder the window control buttons or add additional buttons as "Keep above".

Is there any API that Telegram can use to get the cofigure controls from KWin?

> It is impossible to imitate KWin theme in Telegram CSD.

:\

**Comment by beppe9000** [comment] 2020-07-01 23:37
these days everybody wants to render their own window frame rendering, but telegram does it for no purpose other than changing the color... at least browsers do so to put the tabs in the title bar.

this is a problem for both windows and linux. this thing kills interoperability with various utility software and even standard funcitons like right click the title bar for the context menu of the window on windows.

a toggle for native window frame in the settings would've been an easy fix 😐

**Comment by ilya-fedin** [comment] 2020-07-01 23:49
> a toggle for native window frame in the settings would've been an easy fix

As far as I know, core devs really hate adding new options... For example, for people from #897 it's took 5 years to get an option to disable bouncing icon. People from #2060 were asking an option to make bubbles adaptive for 4 years, someone made a PR #7822 and... they got bubble extending on code blocks and the PR was closed because it adds option.

Asking an option is the best way to make your issue ignorable here :see_no_evil: 

Moreover, as far as I know, any UI things can be changed only by some designers from the telegram team. I.e. making issues that are asking to change something in the UI is an another way to make it just ignored, since devs doesn't have any right to change that...

**Comment by guzszisvww** [comment] 2020-07-02 08:36
> Asking an option is **the best way** to make your issue ignorable here

**The best way** for the user is not to use an inconvenient program with many problems, with non-standard appearance and behavior, with the developers ignoring the requests and requirements of users.
When the number of users is reduced to 10 people, low-professional and ignoring constructive criticism programmers will be fired.
This is not the only bug that has been ignored for several years. And this is not the only bug that would not even have appeared if the programmers had a high professional level.

**Comment by beppe9000** [comment] 2020-07-02 13:17
best way is to fork, actually

**Comment by frozenspider** [comment] 2020-07-02 13:31
And then maintain the fork? Ain't nobody got time for that.

**Comment by ilya-fedin** [comment] 2020-07-02 14:35
(there are already forks, including with native frame option, but not sure if it is a good idea talking about that here)

**Comment by beppe9000** [comment] 2020-07-03 16:47
it is a good idea. it's not like they will censor you: any such reaction would result in a terrible p.r. lol
beside o.s. software is meant to be forked

**Comment by ilya-fedin** [comment] 2020-07-03 17:32
Here's actual open source forks that I can remember now (unsorted):
https://github.com/TDesktop-x64/tdesktop
https://github.com/Sea-n/tdesktop
https://github.com/kotatogram/kotatogram-desktop (that one I contributing to, too)

**Comment by ajyotirmay** [comment] 2020-07-04 08:29
@ilya-fedin I agree with your points, and certainly no one can help with the core beliefs of the team, but doesn't it make no sense at all to have one more maintainable section of code (custom titlebar) that actually serves no purpose and ruins the UX big time.

It's not just about not integrating with the OS well, but Linux concern has only been raised recently. The actual issue with this whole design choice was that the buttons are tiny, compared to what action buttons Windows offers. So tiny that you actually need to pay attention as to where your cursor is going.

Not a clue why this decision was even taken in the first place, because everything has only improved with every release of the app, except for the title bar.

And thanks for taking out your time for this discussion. It's actually nice to hear from someone who's actually participating in the development of the app.

**Comment by ilya-fedin** [comment] 2020-07-04 13:24
> The actual issue with this whole design choice was that the buttons are tiny, compared to what action buttons Windows offers.

There are #5434 opened for two years, but it is a no-go [because it is not pixel perfect](https://github.com/telegramdesktop/tdesktop/pull/5434#issuecomment-444141843) :(

**Comment by ilya-fedin** [comment] 2020-07-04 13:27
Some googling gave me that there are [some API to customize native titlebar on Windows](https://docs.microsoft.com/ru-ru/windows/win32/controls/subclassing-overview?redirectedfrom=MSDN), but I don't have enough skills with WinAPI to colour native titlebar with that API :(

**Comment by guzszisvww** [comment] 2020-07-04 14:11
> [some API to customize native titlebar on Windows]

No WinAPI is needed at all to make the window look standard and normal. The operating system itself should normally draw a window. This is the responsibility of the operating system.

In my opinion, an application should not apply any window styles at all. If the user wants to change the appearance of the window elements, he will do this through the settings of the operating system. And then the windows of all applications will change. All windows of all applications will look uniform and standard.

**Comment by ilya-fedin** [comment] 2020-07-04 14:22
> No WinAPI is needed at all to make the window look standard and normal.

WinAPI is needed to colour the native titlebar, so that core devs may accept a change

**Comment by beppe9000** [comment] 2020-07-04 22:36
> 
> 
> > No WinAPI is needed at all to make the window look standard and normal.
> 
> WinAPI is needed to colour the native titlebar, so that core devs may accept a change

which is bad ux and should have its own toggle 🤦

**Comment by ajyotirmay** [comment] 2020-07-07 04:03
Does anyone have experience working with Qt and QML? I'm considering diving into the code and see if it's something that I can fix by myself. At this point, I don't think core devs/maintainers are actually considering this a serious UX issue. I'm not even sure if they're using this on particular systems that's affected by these choices.

**Closed** 2020-07-08 05:34 UTC
Labels: windows

**Comment by ajyotirmay** [comment] 2020-07-08 07:05
@john-preston thanks for fixing this!

Q: Is their any way to make a donation for this project?

**Comment by vrubleg** [comment] 2020-07-08 08:35
I'm glad to know that this option was added. Thank you!

**Comment by michael-fadely** [comment] 2020-07-08 17:34
Thank you!

**Comment by tooomm** [comment] 2020-07-26 12:29
Hmm. On Windows 10, it looks like once you switch to full screen, the native bar is suddenly narrower and the OS default is altered in some way again?!

**Comment by vrubleg** [comment] 2020-07-26 12:32
@tooomm it's standard Windows 10 behavior for non-UWP windows.

**Comment by tooomm** [comment] 2020-07-26 12:39
Ok, that's interesting. Firefox, Chromium, Word etc. all keep the size of the bar. But Windows File Explorer shows the same pattern.

**Comment by vrubleg** [comment] 2020-07-26 12:41
@tooomm becuase Firefox, Chromium and Word render own (non-standard) frame.

**Comment by beppe9000** [comment] 2020-07-26 15:01
I'm glad this was finally fixed.
