### ISSUE TITLE
Mentions in image captions don't work

### ISSUE THREAD

**Issue by Qwerty-Space** [telegramdesktop/tdesktop#4215] opened 2017-12-20 18:09 UTC
### Steps to reproduce
1. Attach image
2. Add caption with a username in of someone in the group
3. Send

### Expected behaviour
User should receive a notification

### Actual behaviour
No notification.  Doesn't even show up when searching for `#m` or `@`

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.2.1

**Comment by RememberTheAir** [comment] 2017-12-20 18:15
Duplicate of #2158

**Comment by Qwerty-Space** [comment] 2017-12-20 18:18
@RememberTheAir I don't think it is.

**Comment by stek29** [comment] 2017-12-21 00:59
API Issue

**Closed by stek29** 2017-12-21 00:59 UTC
