### ISSUE TITLE
Official binary not showing window icon in Cinnamon bottom panel

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#4253] opened 2017-12-29 14:09 UTC
Related to #4231.

I removed the PPA version in favour of the official binary provided on https://telegram.org/dl/desktop/linux.

1. I launched `Telegram` from the extracted folder on Linux Mint 18.3 Cinnamon
2. Now I see a proper icon in the sound applications menu (great!)
3. But I no longer see an icon for the window in the bottom panel

Can someone please try to reproduce it?

Thank you!

![image](https://user-images.githubusercontent.com/170947/34438848-e92a6d90-eca9-11e7-97a0-7a31c681d8dd.png)

**Comment by orschiro** [comment] 2017-12-29 14:28
Hm, interesting, the icon appears if I manually create the following `.desktop` file:

```
orschiro@x230 ~/.local/share/applications $ cat telegramdesktop.desktop 
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
Exec=/home/orschiro/software/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
```

**Comment by orschiro** [comment] 2017-12-30 10:50
I don't know why the `.desktop` worked initially but now it doesn't any longer.

**Comment by hsafe** [comment] 2018-01-09 07:56
Hi there,
Have the same issue after recent updates, I am on Archlinux Mate desktop and the telegramdesktop.desktop does exist in my profile path...
The bug is super annoying since the system bar icon easily notifies you on unread messages you have in a cluttered desktop where the app window can be backgrounded...also weirdly enough the widow might  completely disappear after the inactive period and if you go to meu/apps/telegram and relaunch it again you will see that the app indeed was active...also you can confirm this if you look for the process in bash

**Comment by akkk33** [comment] 2018-12-07 14:47
I fixed this problem by editing `~/.local/share/applications/telegramdesktop.desktop` file and adding this line:
```
TryExec=/usr/bin/telegram-desktop
```
You can replace the above path with the telegram's binary.

**Comment by Aokromes** [comment] 2020-01-27 18:00
this issue is still valid on 1.9.8?

**Comment by xepozz** [comment] 2020-02-12 07:47
@Aokromes yes :C, it's valid on 1.9.11 beta too (and on 1.9.10)

**Comment by ilya-fedin** [comment] 2020-03-05 00:33
> yes :C, it's valid on 1.9.11 beta too (and on 1.9.10)

Can you send .desktop file that app is created for you?

**Comment by xepozz** [comment] 2020-03-05 05:51
Where is it placed?

**Comment by ilya-fedin** [comment] 2020-03-05 13:12
~/.local/share/applications/telegramdesktop.desktop

**Comment by xepozz** [comment] 2020-03-05 13:59
```
xepozz@xepozz-notebook:~$ cat ~/.local/share/applications/telegramdesktop.desktop
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/xepozz/Документы/Telegram/Telegram
Exec=/home/xepozz/Документы/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
X-GNOME-UsesNotifications=true
```

**Comment by ilya-fedin** [comment] 2020-03-07 09:39
@xepozz so what?

**Comment by xepozz** [comment] 2020-03-09 16:24
Nothing happened

**Comment by ilya-fedin** [comment] 2020-03-09 16:34
`ls -l ~/.local/share/icons/hicolor/48x48/apps`

**Comment by xepozz** [comment] 2020-03-09 16:35
```
xepozz@xepozz-notebook:~$ ls -l ~/.local/share/icons/hicolor/48x48/apps
total 24
-rwx------ 1 xepozz xepozz 6393 Apr 10  2019 appimagekit-staruml.png
-rw-rw-r-- 1 xepozz xepozz 1142 Feb 13  2019 application-x-msdownload.png
-rw-rw-r-- 1 xepozz xepozz 1142 Feb 13  2019 application-x-wine-extension-its.png
-rw-r--r-- 1 xepozz xepozz 3065 Mar  6 09:00 telegram.png
-rw-rw-r-- 1 xepozz xepozz 1142 Feb 13  2019 text-x-component.png
```

**Comment by ilya-fedin** [comment] 2020-03-09 16:38
Do you still on mint 18.3? Can't reproduce on 19.3 :thinking:

**Comment by xepozz** [comment] 2020-03-09 17:00
<details>
<summary>cat /etc/os-release</summary>

```
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.3"
VERSION_ID="19.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic
```
</details>

**Comment by ilya-fedin** [comment] 2020-03-09 17:02
Whгср icon theme are you using?

**Comment by xepozz** [comment] 2020-03-09 17:08
![image](https://user-images.githubusercontent.com/6815714/76238953-be1a1c80-6241-11ea-9dde-f1d5ba8c80bf.png)

**Comment by ilya-fedin** [comment] 2020-03-09 19:42
Maybe I'm doing something wrong?
![image](https://user-images.githubusercontent.com/17829319/76250882-fb7cab00-623d-11ea-8bfa-d66733592ab7.png)

**Comment by xepozz** [comment] 2020-03-10 06:00
Was you tried to reboot the system multiple times?

**Comment by ilya-fedin** [comment] 2020-03-10 07:28
> Was you tried to reboot the system multiple times?

Just tries, works as expected

**Comment by xepozz** [comment] 2020-03-10 14:15
How can I erase all related data(configs, caches, etc.)?

**Comment by ilya-fedin** [comment] 2020-03-10 14:21
~/.local/share/TelegramDesktop
~/.local/share/applications/telegramdesktop.desktop
~/.local/share/icons/telegram.png
~/.config/autostart/telegramdesktop.desktop
And that icons which i sent you above

**Comment by xepozz** [comment] 2020-03-10 16:24
![image](https://user-images.githubusercontent.com/6815714/76334646-62fd2e00-6304-11ea-99be-345f95aa9179.png)
It didn't work

**Comment by ilya-fedin** [comment] 2020-03-10 16:31
What didn't work? There are no window for window icon.

**Comment by xepozz** [comment] 2020-03-10 16:37
I deleted everything that you wrote above and installed again. Telegram starts in the background, but there is still no icon

**Comment by ilya-fedin** [comment] 2020-03-10 16:38
This issue is about _window_ icon. If you saying about _tray_ icon, this is not your issue.

**Comment by Aokromes** [comment] 2020-05-03 16:15
no answer for over a month, closing.if this bug is still valid open a new ticket using updated version.

**Closed by Aokromes** 2020-05-03 16:15 UTC
Labels: bug, linux, waiting for answer
