### ISSUE TITLE
Tray icon in kubuntu 20.04

### ISSUE THREAD

**Issue by zorn-v** [telegramdesktop/tdesktop#7572] opened 2020-04-04 07:35 UTC
Tray icon become black some time ago in KDE. 
With dark theme it almost invisible
![изображение](https://user-images.githubusercontent.com/12619075/78421408-b6ac2e80-769a-11ea-8b46-8aae12b0f5eb.png)

**Comment by Madh93** [comment] 2020-04-04 10:29
I think this issue is a duplicate of https://github.com/telegramdesktop/tdesktop/issues/7399

The bug is already reported and resolved: https://bugs.kde.org/show_bug.cgi?id=418996

It's fixed in breeze-icons 5.69 :+1:

**Closed** 2020-04-04 11:01 UTC

**Comment by danito8905** [comment] 2020-04-27 06:13
the fix commit was remove the breeze-icons for telegram. 
So if you dont want wait the update then remove/rename this files and the original telegram icon will back.
![image](https://user-images.githubusercontent.com/29113406/80339439-0367cd00-8835-11ea-9e58-e8721ce3ec44.png)

/usr/share/icons/breeze/status/22/telegram-panel.svg
/usr/share/icons/breeze/status/22/telegram-attention-panel.svg
/usr/share/icons/breeze/status/22/telegram-mute-panel.svg

/usr/share/icons/breeze/status/24/telegram-panel.svg
/usr/share/icons/breeze/status/24/telegram-attention-panel.svg
/usr/share/icons/breeze/status/24/telegram-mute-panel.svg

https://github.com/KDE/breeze-icons/commit/309ea93012f3fe990625419bcca9c11915ebc8ad
