### ISSUE TITLE
Telegram player won't play music through USB Headset.

### ISSUE THREAD

**Issue by ViRGiL175** [telegramdesktop/tdesktop#2426] opened 2016-09-14 07:22 UTC
### Steps to reproduce
1. Plug USB headset to laptop;
2. Play some music from Telegram;

or

1. Play some music from Telegram;
2. Plug USB headset to laptop;

there are no difference.

### Expected behaviour
Sound in my plugged in USB headset.

### Actual behaviour
Loud sound from my laptop.

### Configuration
**Operating system:**
Windows 10, last stable updates.
Headset: DEXP Omegon.

**Version of Telegram Desktop:**
Telegram 0.10.5.

**Comment by z3ntu** [comment] 2016-09-14 08:46
Probably duplicate of #776

**Closed** 2016-09-14 08:50 UTC
