### ISSUE TITLE
TG desktop doen't open links

### ISSUE THREAD

**Issue by Doc73** [telegramdesktop/tdesktop#26357] opened 2023-06-02 09:53 UTC
### Steps to reproduce

1. click a link in a message
2. nothing happens
3. close telegram desktop
4. the webbroser (in my case Firefox) opens at the link

### Expected behaviour

Webbrowser opens the link

### Actual behaviour

Nothing!

### Operating system

Debian 11 Bullseye AMD64

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2023-06-02 10:28
I can't reproduce, please provide a screen record of the issue + logs as requested by the issue template

**Comment by Doc73** [comment] 2023-06-02 10:47
@ilya-fedin 
I can't understand why, but screen record isn't working in my system. Maybe a Wayland issue?
Btw, I attach the log file.
[log.txt](https://github.com/telegramdesktop/tdesktop/files/11634517/log.txt)

**Comment by ilya-fedin** [comment] 2023-06-02 10:48
Maybe. But I don't understand what the issue is from your text description and therefore it couldn't be moved forward

**Comment by Doc73** [comment] 2023-06-02 10:54
I restarted my session under Xorg and here there is NO issue.
Have you tried in a Wayland session?
I use Gnome 38

**Comment by ilya-fedin** [comment] 2023-06-02 10:55
Yes, I use a Wayland session, although I have no Debian and no GNOME (and I don't plan to install them, sorry).

**Comment by iusmac** [comment] 2023-06-02 11:04
Same for me on Ubuntu 21.10 (Gnome 40.4.0). It also refuses to open File Manager when clicking _Show in Folder_. Tried running as `ALSOFT_LOGLEVEL=4 telegram`, but nothing is logged when clicking links, it only shows `Opening in existing browser session` when fully quitting telegram. TG also freezes for a bit when clicking links.

**Comment by ilya-fedin** [comment] 2023-06-02 11:05
I need screen records, folks. I don't see anything like that and your text descriptions sounds like something impossible, nothing could start AFTER closing tdesktop. Looks like you folks either don't write reproductions steps right or misinterpret what you see.

**Comment by ilya-fedin** [comment] 2023-06-02 11:07
If you won't provide a screen record in two weeks, the issue will be auto-closed as there's nothing actionable without requested info.

@Aokromes please add "waiting for answer" label to start the timer.

**Comment by Doc73** [comment] 2023-06-02 11:09
@ilya-fedin 
As I told you before, in Wayland screen records doesn't work. In X11 session, there is no issue.
Do I really have to take a video with my phone? :smile:

**Comment by ilya-fedin** [comment] 2023-06-02 11:09
@Doc73 well, I'm OK with a video record using a phone. That's better than nothing.

**Comment by Doc73** [comment] 2023-06-02 11:15
It's a big file. Try downloading from Mega
[Video](https://mega.nz/file/4kZSzYIQ#3omqAc3I79eI5tzikiA23RenH_iPHzo0hB7uqyFJ6_4)

**Comment by ilya-fedin** [comment] 2023-06-02 11:16
Thanks.

**Comment by VetaLioSTV** [comment] 2023-06-02 15:04
@ilya-fedin how deep links are implemented here? I have two clients (one desktop non portable and second portable), when i want to open TG through link in browser, for some reason it always opens in portable version. (OS Win 8 x64)

Does it possible somehow to configure it? Like suppress portable version and open only in non portable client? I assume it has something with Windows Registry,right? 

The only one solution as far as i remember its to remove portable client completely, then any deep link will be opened at regular desktop client. 

Your thoughts? Should i raise standalone issue?

**Comment by aimakhotka** [comment] 2023-06-02 16:12
I have the same problem. Application version 4.8.3. Ubuntu 22.10.
Usually the application crashes when opening a link that you open for the first time. After re-opening the app, the link opens normally afterwards.
[Video](https://drive.google.com/file/d/1I1qnCo5JmhiYVMrfI5TJwlHTc8rEpod0/view?usp=sharing)

**Comment by rossnomann** [comment] 2023-06-02 16:24
The app crashed right after click on an external link

Ubuntu 22.04.2 LTS, GNOME 42.5, Wayland

ApiId: 2040
Binary: Telegram
Launched: 02.06.2023 17:58:24
OpenGL: Enabled
OpenGL Renderer: [not-initialized]
Platform: Linux
UserTag: e8b0b5129f4d55d6
Version: 4008003


Caught signal 11 (SIGSEGV) in thread 139944254037504
Google Breakpad caught a crash, minidump written in thread 139944254037504

Minidump: [6278aa6b-4f34-4066-2202a9ab-025fbf56.zip](https://github.com/telegramdesktop/tdesktop/files/11637160/6278aa6b-4f34-4066-2202a9ab-025fbf56.zip)

**Comment by ilya-fedin** [comment] 2023-06-02 17:54
> for some reason it always opens in portable version.

Latest updated client has the priority

> Should i raise standalone issue?

It's unlikely something will be done but you can try as a feature request (the behavior is intended)

**Comment by ilya-fedin** [comment] 2023-06-02 18:04
Looks like this is https://bugreports.qt.io/browse/QTBUG-113995

**Closed** 2023-06-03 03:29 UTC
Labels: bug, cant reproduce

**Comment by harshil21** [comment] 2023-06-03 10:48
> The app crashed right after click on an external link
> 
> Ubuntu 22.04.2 LTS, GNOME 42.5, Wayland
> 
> ApiId: 2040 Binary: Telegram Launched: 02.06.2023 17:58:24 OpenGL: Enabled OpenGL Renderer: [not-initialized] Platform: Linux UserTag: e8b0b5129f4d55d6 Version: 4008003
> 
> Caught signal 11 (SIGSEGV) in thread 139944254037504 Google Breakpad caught a crash, minidump written in thread 139944254037504
> 
> Minidump: [6278aa6b-4f34-4066-2202a9ab-025fbf56.zip](https://github.com/telegramdesktop/tdesktop/files/11637160/6278aa6b-4f34-4066-2202a9ab-025fbf56.zip)

yep have the same exact issue. Hopefully a hotfix can be released asap

**Comment by VetaLioSTV** [comment] 2023-06-05 18:35
> Latest updated client has the priority

Can it be setup in custom way or it will be always the same scenario how you have described "latest updated client have priority" ?

**Comment by ilya-fedin** [comment] 2023-06-06 01:40
It couldn't be customized, tdesktop is designed to be the only client with the only instance.

**Comment by VetaLioSTV** [comment] 2023-06-06 22:31
@ilya-fedin i mean, does it possible to customzie DeepLink to be opened only on main desktop client(or at least ignored all portable clients? That approach with latest updated client isn't user friendly)

**Comment by ilya-fedin** [comment] 2023-06-07 04:26
I'm not sure how you would implement that, it means some interaction between the instances probably, currently tdesktop thinks it's the only instance and it just sets itself as the current handler in the code executing after update.
