### ISSUE TITLE
telegram-desktop randomly crashes with SIGABRT and stack smashing

### ISSUE THREAD

**Issue by ohhai** [telegramdesktop/tdesktop#17938] opened 2022-01-08 13:09 UTC
### Steps to reproduce

None. Just launch telegram-desktop and use it.

I did not try binary from desktop.telegram.org since the problem reproduction time varies significantly. Sometimes it's possible to have 2-3 weeks without a single crash. Sometimes I can't do anything in telegram-desktop since it crashes immediately after start.
Besides that, the failing thing is fortification check and there might be no crashes with different checks built in different binary.

My version is rebuilt with `-fsanitize=address -ggdb`. 
Please tell if it's better to try the same with sources from this repo. However, should firstly figure out how to ensure that all fortification checks are enabled, and sync other build options with my current binary.

I see several similar issues in this repo, but all of them are closed after the bug suddenly disappear.
https://github.com/telegramdesktop/tdesktop/issues/16776 is closest because it has trace with same QArrayData::allocate() -> [jemalloc] -> __fortify_fail()

### Expected behaviour

No crashes.

### Actual behaviour

Random crashes with SIGABRT

### Operating system

Fedora 35 x64

### Version of Telegram Desktop

3.3

### Installation source

Other (unofficial) source

### Logs

```shell
$ gdb telegram-desktop
GNU gdb (GDB) Fedora 11.1-5.fc35
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from telegram-desktop...
Reading symbols from .gnu_debugdata for /usr/bin/telegram-desktop...
(No debugging symbols found in .gnu_debugdata for /usr/bin/telegram-desktop)
Missing separate debuginfos, use: dnf debuginfo-install telegram-desktop-3.3.0-1.fc35.x86_64
(gdb) r
Starting program: /usr/bin/telegram-desktop
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffea7ff640 (LWP 9952)]

(telegram-desktop:9770): Telegram-WARNING **: 14:11:14.127: Application was built without embedded fonts, this may lead to font issues.
[New Thread 0x7fffdcace640 (LWP 9953)]
[New Thread 0x7fffdbdff640 (LWP 9954)]
[New Thread 0x7fffdb5fe640 (LWP 9955)]
[New Thread 0x7fffda7ff640 (LWP 9956)]
[New Thread 0x7fffd9ffe640 (LWP 9960)]
[New Thread 0x7fffd91ff640 (LWP 9961)]
[New Thread 0x7fffd7051640 (LWP 10117)]
[New Thread 0x7fffd63ff640 (LWP 10118)]
[New Thread 0x7fffd4bef640 (LWP 10119)]
[New Thread 0x7fffd2553640 (LWP 10138)]
[New Thread 0x7fffcd17f640 (LWP 10139)]
[New Thread 0x7fffcc97e640 (LWP 10140)]
[New Thread 0x7fffcbbff640 (LWP 10141)]
[Thread 0x7fffd2553640 (LWP 10138) exited]
[Thread 0x7fffd4bef640 (LWP 10119) exited]
[New Thread 0x7fffd2553640 (LWP 10866)]
[New Thread 0x7fffd4bef640 (LWP 10867)]
[New Thread 0x7fffbfa1f640 (LWP 10868)]
[New Thread 0x7fffbf21e640 (LWP 10869)]
[New Thread 0x7fffbea1d640 (LWP 10870)]
[New Thread 0x7fffbe21c640 (LWP 10871)]
[Detaching after fork from child process 10872]
[New Thread 0x7fffbcbff640 (LWP 10873)]
[New Thread 0x7fffbbdff640 (LWP 10874)]
error: : cannot open
error: : cannot open
error: : cannot open
[New Thread 0x7fffb8fff640 (LWP 10875)]
[New Thread 0x7fffb87fe640 (LWP 10876)]
[New Thread 0x7fffb79ff640 (LWP 10877)]
[Thread 0x7fffb79ff640 (LWP 10877) exited]
[New Thread 0x7fffb79ff640 (LWP 10879)]
[New Thread 0x7fffb657f640 (LWP 10880)]
[Thread 0x7fffb87fe640 (LWP 10876) exited]
[Thread 0x7fffb8fff640 (LWP 10875) exited]
[New Thread 0x7fffb87fe640 (LWP 10889)]
[New Thread 0x7fffb8fff640 (LWP 10890)]
[New Thread 0x7fffb3373640 (LWP 10891)]
Corrupt JPEG data: premature end of data segment
[New Thread 0x7fffaf3ae640 (LWP 10892)]
[New Thread 0x7fffae5ff640 (LWP 10893)]
[New Thread 0x7fffad7ff640 (LWP 10894)]
[Thread 0x7fffad7ff640 (LWP 10894) exited]
[New Thread 0x7fffad7ff640 (LWP 10895)]
[New Thread 0x7fffac27f640 (LWP 10896)]
[New Thread 0x7fffab67f640 (LWP 10897)]
[New Thread 0x7fffaac7e640 (LWP 10898)]
[Thread 0x7fffaac7e640 (LWP 10898) exited]
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
[Thread 0x7fffae5ff640 (LWP 10893) exited]
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
[Thread 0x7fffab67f640 (LWP 10897) exited]
[Thread 0x7fffac27f640 (LWP 10896) exited]
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
*** stack smashing detected ***: terminated

Thread 1 "telegram-deskto" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading 0.00 MB source file /usr/src/debug/glibc-2.34-12.fc35.x86_64/nptl/pthread_kill.c
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff3a038b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff39b66a6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff39a07d3 in __GI_abort () at abort.c:79
#4  0x00007ffff39f79f7 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff3b34446 "*** %s ***: terminated\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff3a9518a in __GI___fortify_fail (msg=msg@entry=0x7ffff3b3442e "stack smashing detected") at fortify_fail.c:26
#6  0x00007ffff3a95156 in __stack_chk_fail () at stack_chk_fail.c:24
#7  0x00007ffff55ec6b4 in je_large_palloc (tsdn=0x7fffeb06e430, arena=0x7fffeae00980, usize=<optimized out>, alignment=<optimized out>, zero=<optimized out>) at src/large.c:72
#8  0x00007ffff55acc0e in arena_malloc (slow_path=false, tcache=0x7fffeb06e620, zero=false, ind=56, size=524288, arena=0x0, tsdn=0x7fffeb06e430) at include/jemalloc/internal/arena_inlines_b.h:176
#9  iallocztm (slow_path=false, arena=0x0, is_internal=false, tcache=0x7fffeb06e620, zero=false, ind=56, size=524288, tsdn=0x7fffeb06e430) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#10 imalloc_no_sample (ind=56, usize=524288, size=524288, tsd=0x7fffeb06e430, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:1949
#11 imalloc_body (tsd=0x7fffeb06e430, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2149
#12 imalloc (dopts=<optimized out>, sopts=<optimized out>) at src/jemalloc.c:2258
#13 je_malloc_default (size=524288) at src/jemalloc.c:2289
#14 0x00007ffff48af6d1 in QArrayData::allocate(unsigned long, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>)
    (objectSize=objectSize@entry=4, alignment=alignment@entry=8, capacity=131066, options=...) at tools/qarraydata.cpp:218
#15 0x00007fffdacf0246 in QTypedArrayData<unsigned int>::allocate(unsigned long, QFlags<QArrayData::AllocationOption>) (options=..., capacity=<optimized out>)
    at ../../../../include/QtCore/../../src/corelib/tools/qarraydata.h:220
#16 QVector<unsigned int>::realloc(int, QFlags<QArrayData::AllocationOption>) (this=this@entry=0x7fffffffc428, aalloc=<optimized out>, options=...)
    at ../../../../include/QtCore/../../src/corelib/tools/qvector.h:699
#17 0x00007fffdacfabc1 in QVector<unsigned int>::resize(int) (this=this@entry=0x7fffffffc428, asize=90098) at ../../../../include/QtCore/../../src/corelib/tools/qvector.h:431
#18 0x00007fffdad0bae3 in QXcbWindow::setWindowIcon(QIcon const&) (this=0x7fffd37db080, icon=...) at qxcbwindow.cpp:1307
#19 0x00007ffff4ebdef7 in QWindow::setIcon(QIcon const&) (this=this@entry=0x7fffd3aa1480, icon=...) at kernel/qwindow.cpp:1010
#20 0x00007ffff4105c6a in QWidgetPrivate::setWindowIcon_sys() (this=this@entry=0x7fffeace9f40) at kernel/qwidget.cpp:6020
#21 0x00007ffff4111799 in QWidget::setWindowIcon(QIcon const&) (this=0x7fffeacfd810, icon=...) at kernel/qwidget.cpp:6010
#22 0x0000555556dc70fd in Platform::MainWindow::updateIconCounters() ()
#23 0x0000555556f75b27 in rpl::details::consumer_handlers<rpl::empty_value, rpl::no_error, Window::MainWindow::MainWindow(gsl::not_null<Window::Controller*>)::{lambda()#3}, rpl::details::operator|<rpl::empty_value, rpl::no_error, rpl::details::type_erased_generator<rpl::empty_value, rpl::no_error>, Window::MainWindow::MainWindow(gsl::not_null<Window::Controller*>)::{lambda()#3}, void>(rpl::producer<rpl::empty_value, rpl::no_error, rpl::details::type_erased_generator<rpl::empty_value, rpl::no_error> >&&, rpl::details::lifetime_with_next<Window::MainWindow::MainWindow(gsl::not_null<Window::Controller*>)::{lambda()#3}>&&)::{lambda()#1}, rpl::details::operator|<rpl::empty_value, rpl::no_error, rpl::details::type_erased_generator<rpl::empty_value, rpl::no_error>, Window::MainWindow::MainWindow(gsl::not_null<Window::Controller*>)::{lambda()#3}, void>(rpl::producer<rpl::empty_value, rpl::no_error, rpl::details::type_erased_generator<rpl::empty_value, rpl::no_error> >&&, rpl::details::lifetime_with_next<Window::MainWindow::MainWindow(gsl::not_null<Window::Controller*>)::{lambda()#3}>&&)::{lambda()#2}>::put_next(rpl::empty_value&&) ()
#24 0x0000555555c2ac6c in bool __gnu_cxx::__ops::_Iter_pred<rpl::event_stream<rpl::empty_value, rpl::no_error>::fire_forward<rpl::empty_value>(rpl::empty_value&&) const::{lambda(auto:1 const&)#1}>::operator()<base::index_based_iterator<std::vector<rpl::consumer<rpl::empty_value, rpl::no_error, rpl::details::type_erased_handlers<rpl::empty_value, rpl::no_error> >, std::allocator<rpl::consumer<rpl::empty_value, rpl::no_error, rpl::details::type_erased_handlers<rpl::empty_value, rpl::no_error> > > > > >(base::index_based_iterator<std::vector<rpl::consumer<rpl::empty_value, rpl::no_error, rpl::details::type_erased_handlers<rpl::empty_value, rpl::no_error> >, std::allocator<rpl::consumer<rpl::empty_value, rpl::no_error, rpl::details::type_erased_handlers<rpl::empty_value, rpl::no_error> > > > >) ()
#25 0x0000555555c2b208 in void rpl::event_stream<rpl::empty_value, rpl::no_error>::fire_forward<rpl::empty_value>(rpl::empty_value&&) const ()
#26 0x0000555556bbcbe8 in std::_Function_handler<void (), crl::guarded_wrap<Core::Application*, Main::Domain::scheduleUpdateUnreadBadge()::{lambda()#1}> >::_M_invoke(std::_Any_data const&) ()
#27 0x000055555659d1d3 in Core::Sandbox::decrementEventNestingLevel() ()
#28 0x00005555565a299f in Core::Sandbox::notify(QObject*, QEvent*) ()
#29 0x00007ffff4a617d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x7fffd3781660, event=0x7fffbb059b40) at kernel/qcoreapplication.cpp:1064
#30 0x00007ffff4a64d46 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x7fffeac53280) at kernel/qcoreapplication.cpp:1821
#31 0x00007ffff4ab3117 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x7fffeac7cc60) at kernel/qeventdispatcher_glib.cpp:277
#32 0x00007ffff58dc130 in g_main_dispatch (context=0x7fffeac76840) at ../glib/gmain.c:3381
#33 g_main_context_dispatch (context=0x7fffeac76840) at ../glib/gmain.c:4099
#34 0x00007ffff5931208 in g_main_context_iterate.constprop.0 (context=context@entry=0x7fffeac76840, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4175
#35 0x00007ffff58d9933 in g_main_context_iteration (context=0x7fffeac76840, may_block=1) at ../glib/gmain.c:4240
#36 0x00007ffff4ab2bb8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffeac9f4b0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#37 0x00007ffff4a601e2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffccf0, flags=..., flags@entry=...)
    at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#38 0x00007ffff4a68724 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#39 0x00005555565adaee in Core::Launcher::executeApplication() ()
--Type <RET> for more, q to quit, c to continue without paging--
#40 0x00005555565ae41b in Core::Launcher::exec() ()
#41 0x0000555555b5f24b in main ()
(gdb)
```

**Comment by vimpostor** [comment] 2022-01-08 23:20
Probably duplicate of #16673. Has this problem ever been reported to jemalloc?

**Comment by ilya-fedin** [comment] 2022-01-09 06:26
@ohhai this is not a problem on official binary, you can switch to it

> Has this problem ever been reported to jemalloc though?

No, it's not clear how to report something like this, personally I have no idea why this happens at all

**Comment by ohhai** [comment] 2022-01-09 14:03
@ilya-fedin   does the official binary have all stack fortification checks enabled? I see this in docker build env, not sure if effective and sufficient:
```
tdesktop-3.4.3/Telegram/build/docker/centos_env/Dockerfile:ENV HFLAGS "$HFLAGS_DEBUG -D_FORTIFY_SOURCE=2"
tdesktop-3.4.3/Telegram/build/docker/centos_env/Dockerfile:ENV HFLAGS_DEBUG "-fstack-protector-all -fstack-clash-protection -fPIC"
```

I'm ok to play with it more since it's a clear bug somewhere.
Is there something more to use for catching the actual place of stack corruption? Like -fstack-check or Valgrind or some another instrumentation

**Comment by ilya-fedin** [comment] 2022-01-09 14:05
> I see this in docker build env, not sure if effective and sufficient:

I don't know, too

**Closed** 2022-01-22 19:26 UTC
Labels: bug, 3rd party issue
