### ISSUE TITLE
UI is not fitted correctly within the app window

### ISSUE THREAD

**Issue by lbronsdijk** [telegramdesktop/tdesktop#4162] opened 2017-12-12 10:42 UTC
### Steps to reproduce
1. Download Telegram version 1.2.
2. Open Telegram.

### Expected behaviour
A UI that is fitted correctly within the window.

### Actual behaviour
![image](https://user-images.githubusercontent.com/2235259/33879878-092b1b4e-df30-11e7-9461-e8de91f9a360.png)

### Configuration
**Operating system:** Mac OS Sierra 10.12.6 (16G1036)

**Version of Telegram Desktop:** 1.2

**Used theme**: Default

**Comment by john-preston** [comment] 2017-12-12 10:43
@lbronsdijk I hope to fix this in today's update.

**Comment by auchri** [comment] 2017-12-12 10:45
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/4150

**Comment by lbronsdijk** [comment] 2017-12-12 10:46
@auchri Awesome!

**Closed by auchri** 2017-12-12 10:45 UTC

**Comment by john-preston** [comment] 2017-12-12 16:18
@lbronsdijk Please check the latest 1.2.1 version, I hope this is fixed.

**Comment by lbronsdijk** [comment] 2017-12-12 16:33
@john-preston Works like a charm! Thanks!
