### ISSUE TITLE
Incorrect character

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#728] opened 2015-05-18 05:09 UTC
Desktop client doesn't show [ARABIC TATWEEL](http://www.unicodemap.org/details/0x0640/index.html) character correctly while other Telegram clients shows it correctly (see the attachments below).

Telegram Windows desktop client 0.8.13 (incorrect)
![incorrect](http://i.imgur.com/8ilOH8J.png)

Telegram Android client 2.8.1 (correct)
![correct](http://i.imgur.com/rnIwx8M.jpg)

**Comment by SafaAlfulaij** [comment] 2015-11-06 06:08
Unfortunately, it's a bug in Qt5 :(
https://bugreports.qt.io/browse/QTBUG-35836

**Comment by Aokromes** [comment] 2016-11-08 11:31
Bug Fixed on QT and telegram desktop.

**Comment by mbnoimi** [comment] 2016-11-08 14:44
@Aokromes Which Tg you talk about?!

In Tg 0.10.19 alpha this bug still exists!

**Comment by Aokromes** [comment] 2016-11-08 14:46
it's not the same as https://github.com/telegramdesktop/tdesktop/issues/1875 ? because it showed the same for me, plz write the char here to allow copy&paste

**Comment by mbnoimi** [comment] 2016-11-08 14:55
From Tg 0.10.19 alpha

![screenshot_2016-11-08_17-29-28](https://cloud.githubusercontent.com/assets/284547/20103815/2837822a-a5d4-11e6-83c5-1a483aa259de.png)

**Comment by mbnoimi** [comment] 2016-11-08 14:56
![screenshot_2016-11-08_17-56-42](https://cloud.githubusercontent.com/assets/284547/20103871/5bff8ca6-a5d4-11e6-889c-4976fb6e996b.png)

**Comment by Aokromes** [comment] 2016-11-08 14:58
i was asking text not pic :)

**Comment by mbnoimi** [comment] 2016-11-08 14:58
بـسم
بسـم
ـ

**Comment by Aokromes** [comment] 2016-11-08 15:01
Strange, this is how it looks for me:

http://i.imgur.com/uClnzGk.png

**Comment by mbnoimi** [comment] 2016-11-08 15:18
Fine @Aokromes your screenshot shows the bug exactly similar to [my screenshot](https://github.com/telegramdesktop/tdesktop/issues/728#issuecomment-259158193)

**Comment by Aokromes** [comment] 2016-11-08 15:35
Oh, i noticed the small difference how the _ between the most extreme sides :)

**Comment by Aokromes** [comment] 2016-11-08 15:46
btw  #521 ?

**Comment by mbnoimi** [comment] 2016-11-08 15:47
BTW, This bug doesn't occur in Qt 5.7.0 (Linux)

**Comment by mbnoimi** [comment] 2017-12-09 13:49
This bug has been fixed since months ago in Qt while still occurs in Tg!!!

**Comment by john-preston** [comment] 2017-12-09 14:00
@mbnoimi I use a specific Qt version for backward compatibility. Can you give me a link to Qt bugtracker where I can see the patch and perhaps backport it?

**Comment by mbnoimi** [comment] 2017-12-09 14:16
I believe you don't need to make a backward compatibility because Qt 5 is stable enough (I still didn't understand why you don't use standard Qt distro!). Any way [this link points ](https://bugreports.qt.io/browse/QTBUG-35836)to the fix.

**Comment by john-preston** [comment] 2017-12-09 14:45
@mbnoimi I can't always use latest Qt, because it is not backward compatible enough. For example I'm stuck on Qt 5.6.2 on Windows and macOS, because it drops Windows XP support starting with Qt 5.7 as well as OS X 10.8. I have to be source-compatible with Qt 5.3.2 because it is the last version that supports OS X 10.6 and OS X 10.7.

**Comment by Aokromes** [comment] 2020-01-27 15:07
this is valid on 1.9.8?

**Comment by Aokromes** [comment] 2020-02-24 23:47
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Closed by Aokromes** 2020-02-24 23:47 UTC
Labels: bug, waiting for answer

**Comment by mbnoimi** [comment] 2020-02-25 14:31
This bug doesn't exist any more.

**Comment by AliDjango** [comment] 2020-03-02 19:09
I can confirm this is fixed(shows correctly) in 1.9.14.i don't know in which version it was fixed though
os:windows 10
