### ISSUE TITLE
segmentation fault when playing video 

### ISSUE THREAD

**Issue by oleks12345** [telegramdesktop/tdesktop#7839] opened 2020-05-08 16:02 UTC
### Steps to reproduce
1. Open app
2. Play video
3. Click outside video to stop it

### Expected behaviour
should not crash 

### Actual behaviour
segmentation fault 
![image](https://user-images.githubusercontent.com/19672992/81423417-b0571980-9154-11ea-9290-be137607f2aa.png)

- when not started from terminal, it still crashes 

(other messages are before seg fault) 

### Configuration
**Operating system:**

**Version of Telegram Desktop:**
2.1.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap

**Used theme**:
sweet and breeze (kde) 

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment] 2020-06-01 07:52
Cab you get a backtrace?

**Comment by Aokromes** [comment] 2020-06-01 10:23
to start i recommend you to update to 2.1.7 before reporting bugs.

**Comment by oleks12345** [comment] 2020-06-09 11:13
I still have this bug, it only happens when you have 2x speed, just go to any video, set speed to 2x and play video, click outside to close, repeat few times if it won't crash on first 
I always have newest version from snap 2.1.11 now

**Comment by Aokromes** [comment] 2020-06-09 12:28
tried to reproduce it on windows with one random video and i am unable

**Comment by ilya-fedin** [comment] 2020-06-09 12:32
> Operating system:

Why didn't you specify your operating system?

**Comment by oleks12345** [comment] 2020-06-09 15:35
> Installation source (Linux Only)  
> snap
> Used theme:
> sweet and breeze (kde)



I thought that it says enough about system, it is Linux, using KDE as desktop environment, 
More precisely 
Linux (kernel 5.4.0-33-generic)
Kubuntu 20.04

**Comment by Spurlos** [comment] 2020-06-23 20:15
> Cab you get a backtrace?

I have the same issue with the same console output even for video played on regular speed. It crashes just after closing the fullscreen video popup. How can I create a backtrace for the bug to help to move this issue forward?

**Comment by Aokromes** [comment] 2020-06-23 20:44
> > Cab you get a backtrace?
> 
> I have the same issue with the same console output even for video played on regular speed. It crashes just after closing the fullscreen video popup. How can I create a backtrace for the bug to help to move this issue forward?

gdb ./Telegram inside telegrm directory
run
crash it

run the commands in
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/contrib/debugger/crashreport.gdb

(you may need to remove set style enabled off)

**Comment by ilya-fedin** [comment] 2020-06-23 22:22
> gdb ./Telegram inside telegram directory

That won't work with snap
`snap run --gdb telegram-desktop` is for snap

**Comment by Spurlos** [comment] 2020-06-24 00:36
Can't get my head over the gdb commands to launch tgd snap successfully and do the crash. Can you please test it out and provide any directions in gdb steps?

```
Spurlos@spurlos-ThinkPad-E580:/snap/bin$ telegram-desktop 
Qt: Session management error: None of the authentication protocols specified are supported
Gtk-Message: 00:27:17.291: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:27:17.291: Failed to load module "canberra-gtk-module"
error: : cannot open
error: : cannot open
error: : cannot open
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
Segmentation fault (core dumped)
spurlos@spurlos-ThinkPad-E580:/snap/bin$ snap run --gdb telegram-desktop
[sudo] password for spurlos: 
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /snap/core/9289/usr/lib/snapd/snap-confine...
(No debugging symbols found in /snap/core/9289/usr/lib/snapd/snap-confine)
Starting program: /snap/core/9289/usr/lib/snapd/snap-confine --base core20 snap.telegram-desktop.telegram-desktop /usr/lib/snapd/snap-exec --command=gdb telegram-desktop
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 2645904]
[Detaching after fork from child process 2645905]
[Detaching after fork from child process 2645906]
[Detaching after fork from child process 2645907]
[Detaching after fork from child process 2645908]
[Detaching after fork from child process 2645909]
[Detaching after fork from child process 2645910]
[Detaching after fork from child process 2645911]
[Detaching after fork from child process 2645912]
[Detaching after fork from child process 2645913]
[Detaching after fork from child process 2645914]
[Detaching after fork from child process 2645915]
[Detaching after fork from child process 2645916]
[Detaching after fork from child process 2645917]
[Detaching after fork from child process 2645918]
[Detaching after fork from child process 2645919]
[Detaching after fork from child process 2645920]
[Detaching after fork from child process 2645921]
[Detaching after fork from child process 2645922]
[Detaching after fork from child process 2645923]
[Detaching after fork from child process 2645924]
[Detaching after fork from child process 2645925]
[Detaching after fork from child process 2645926]
[Detaching after fork from child process 2645927]
[Detaching after fork from child process 2645928]
[Detaching after fork from child process 2645929]
[Detaching after fork from child process 2645930]
[Detaching after fork from child process 2645931]
[Detaching after fork from child process 2645932]
[Detaching after fork from child process 2645933]
[Detaching after fork from child process 2645934]
[Detaching after fork from child process 2645935]
[Detaching after fork from child process 2645936]
[Detaching after fork from child process 2645937]
[Detaching after fork from child process 2645938]
[Detaching after fork from child process 2645939]
[Detaching after fork from child process 2645940]
[Detaching after fork from child process 2645941]
[Detaching after fork from child process 2645942]
process 2645900 is executing new program: /usr/lib/snapd/snap-exec
[New LWP 2645953]
[New LWP 2645954]
[New LWP 2645955]
[New LWP 2645956]
[LWP 2645956 exited]
[LWP 2645955 exited]
[LWP 2645954 exited]
[LWP 2645953 exited]
process 2645900 is executing new program: /usr/bin/dash
process 2645900 is executing new program: /usr/lib/snapd/snap-gdb-shim


Welcome to `snap run --gdb`.
You are right before your application is execed():
- set any options you may need
- use 'cont' to start


--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "snap-gdb-shim" received signal SIGTRAP, Trace/breakpoint trap.
0x00007f1217c2918b in raise () from target:/snap/telegram-desktop/1708/lib/x86_64-linux-gnu/libc.so.6
Catchpoint 1 (exec)
Continuing.
process 2645900 is executing new program: /usr/bin/bash

Thread 1 "desktop-launch" hit Catchpoint 1 (exec'd /usr/bin/bash), 0x00007f152d62f100 in ?? () from target:/lib64/ld-linux-x86-64.so.2
(gdb) set logging overwrite on
(gdb) set logging file backtrace.log.temp
(gdb) set style enabled off
(gdb) set height unlimited
(gdb) set width unlimited
(gdb) set disassembly-flavor intel
(gdb) handle SIG33 pass nostop noprint
Signal        Stop	Print	Pass to program	Description
SIG33         No	No	Yes		Real-time event 33
(gdb) set pagination 0
(gdb) set logging on
Copying output to backtrace.log.temp.
Copying debug output to backtrace.log.temp.
(gdb) echo \n--- DEBUG: --- START\n\n

--- DEBUG: --- START

(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
`target:/usr/bin/bash' has disappeared; keeping its symbols.
Starting program: target:/usr/bin/bash --base core20 snap.telegram-desktop.telegram-desktop /usr/lib/snapd/snap-exec --command=gdb telegram-desktop
/bin/bash: /snap/bin/target:/usr/bin/bash: No such file or directory
During startup program exited with code 127.
(gdb) if $_isvoid($_exitcode)
 >  echo \n--- DEBUG: BACKTRACE FULL\n
 >  # print assertion message if this is ASSERT crash
 >  if TrinityAssertionFailedMessage != 0
  >    printf "%s\n", TrinityAssertionFailedMessage
  >  end
 >  echo \n
 >  backtrace full
 >  echo \n--- DEBUG: INFO REGISTERS\n\n
 >  info registers
 >  echo \n--- DEBUG: CALLS (x/16i $pc)\n\n
 >  x/16i $pc
 >  echo \n--- DEBUG: THREAD APPLY ALL BACKTRACE\n
 >  thread apply all backtrace
 >  echo \n--- DEBUG: --- STOP\n\n
 >  echo Generated by crashreport.gdb script version 1.4\n
 >  set logging off
 >
 >  # rename log file to avoid it getting overwritten by restart scripts
 >  shell mv backtrace.log.temp backtrace_$(date +%Y-%m-%d-%T).log
 >else
 >  # normal exit, cleanup temp file
 >  set logging off
 >  shell rm backtrace.log.temp
 >end

--- DEBUG: BACKTRACE FULL
No symbol table is loaded.  Use the "file" command.
(gdb) quit
spurlos@spurlos-ThinkPad-E580:/snap/bin$  >  # normal exit, cleanup temp file
bash: syntax error near unexpected token `newline'
spurlos@spurlos-ThinkPad-E580:/snap/bin$  >  set logging off
bash: set: Permission denied
spurlos@spurlos-ThinkPad-E580:/snap/bin$  >  shell rm backtrace.log.temp
bash: shell: Permission denied
spurlos@spurlos-ThinkPad-E580:/snap/bin$  >end
bash: end: Permission denied
spurlos@spurlos-ThinkPad-E580:/snap/bin$ 
spurlos@spurlos-ThinkPad-E580:/snap/bin$ --- DEBUG: BACKTRACE FULL
---: command not found
spurlos@spurlos-ThinkPad-E580:/snap/bin$ No symbol table is loaded.  Use the "file" command.
No: command not found
spurlos@spurlos-ThinkPad-E580:/snap/bin$ (gdb) quit
bash: syntax error near unexpected token `quit'
spurlos@spurlos-ThinkPad-E580:/snap/bin$ spurlos@spurlos-ThinkPad-E580:/snap/bin$ 
bash: spurlos@spurlos-ThinkPad-E580:/snap/bin$: No such file or directory
spurlos@spurlos-ThinkPad-E580:/snap/bin$  >  # normal exit, cleanup temp file
bash: syntax error near unexpected token `newline'
spurlos@spurlos-ThinkPad-E580:/snap/bin$  >  set logging off
bash: set: Permission denied
spurlos@spurlos-ThinkPad-E580:/snap/bin$  >  shell rm backtrace.log.temp
bash: shell: Permission denied
spurlos@spurlos-ThinkPad-E580:/snap/bin$  >end
bash: end: Permission denied
spurlos@spurlos-ThinkPad-E580:/snap/bin$ 
spurlos@spurlos-ThinkPad-E580:/snap/bin$ --- DEBUG: BACKTRACE FULL
---: command not found
spurlos@spurlos-ThinkPad-E580:/snap/bin$ No symbol table is loaded.  Use the "file" command.
No: command not found
spurlos@spurlos-ThinkPad-E580:/snap/bin$ (gdb) quit
bash: syntax error near unexpected token `quit'
spurlos@spurlos-ThinkPad-E580:/snap/bin$ spurlos@spurlos-ThinkPad-E580:/snap/bin$ 
bash: spurlos@spurlos-ThinkPad-E580:/snap/bin$: No such file or directory
spurlos@spurlos-ThinkPad-E580:/snap/bin$ 

```

**Comment by ilya-fedin** [comment] 2020-06-24 00:44
> Can you please test it out and provide any directions in gdb steps?

```
run
bt full
```

**Comment by gospodima** [comment] 2020-07-26 10:42
I have the same issue with version 2.1.18 installed from manjaro community repository. The app crashes by me when speed is set not to 'normal'.
My configuration:
- Manjaro 20.0.3
- KDE Plasma 5.19.3
- Linux kernel 5.7.9

**Comment by Aokromes** [comment] 2020-07-26 11:04
try on 2.2.0 from github releases / desktop.telegram.org

**Comment by gospodima** [comment] 2020-07-26 11:16
I took [binary](https://github.com/telegramdesktop/tdesktop/releases/download/v2.2.0/tsetup.2.2.0.tar.xz) for linux 64 bit.  
it seems to be working without problems, thank you!

**Closed** 2020-07-30 18:12 UTC
Labels: waiting for answer
