### ISSUE TITLE
[Behavior] Turn off phone notifications when Desktop Telegram is active

### ISSUE THREAD

**Issue by LonnyX** [telegramdesktop/tdesktop#8901] opened 2020-10-26 14:26 UTC
### Steps to reproduce
1. Open Telegram desktop and mobile
2. Ask a friend send you a message
3. Receive the notifications on both platforms at the same time, which is not cool!

### Expected behaviour
If desktop app is active, mobile should not receive notifications (A lot of apps are already using this priority)

### Actual behaviour
Receive notifications on all platforms

### Configuration
MacOS & iOS

**Version of Telegram Desktop:**
All versions are affected

**Comment by MarcAnt01** [comment] 2020-10-26 15:41
Telegram Desktop uses in-app notifications, iOS uses push notifications. Telegram Desktop can do nothing about that

**Comment by RememberTheAir** [comment] 2020-10-26 19:40
Duplicate of #277

**Closed** 2020-10-26 19:47 UTC
