### ISSUE TITLE
Option to switch System Window Frame on Linux has disappeared

### ISSUE THREAD

**Issue by bacon1664** [telegramdesktop/tdesktop#8791] opened 2020-10-09 09:32 UTC
### Steps to reproduce
1. Install Telegram Desktop 2.4.1
2. Go to Settings, Advanced, notice the presence of the "use system window frame" in the "System integration" options
3. Upgrade to 2.4.3
4. Note the absence of the option in the settings

### Expected behaviour
The option to use the system window frame should be there so I can use my DE's window decoration and have a consistent user experience with Telegram.

Right-clicking on the window frame should give me the standard window options in the DE.

The window behaviour should follow my DE's settings. e.g. middle-clicking on the window frame should minimize the window.

### Actual behaviour
Since the option is gone, I have to contend with the default, which is ugly and behaves inconsistently with the rest of the desktop environment.

Right-clicking on the frame does not display any windowing options

The frame doesn't follow my DE's settings (e.g. middle-clicking doesn't minimise it).

### Workaround

Remain on Telegram desktop 2.4.1 and disable upgrades.

### Configuration
Fedora 32 (x86_64)

Telegram Desktop version 2.4.3

Installed from flathub

**Used theme**: Classic

![telegram-ugly](https://user-images.githubusercontent.com/71259573/95567017-4819a600-0a1a-11eb-86cf-c40c0e79e4a8.png)

**Comment by ilya-fedin** [comment] 2020-10-09 09:59
Duplicate of #8734

**Closed** 2020-10-09 10:21 UTC
