### ISSUE TITLE
 Option to display emojis instead of stickers

### ISSUE THREAD

**Issue by umazalakain** [telegramdesktop/tdesktop#763] opened 2015-05-28 18:25 UTC
People in group chats tend to overuse the newly added custom sticker feature. I noticed that all stickers have a related emoji which is displayed in the chat summary. An option to change the stickers for emojis would be grate.

**Comment by 4DA** [comment] 2016-01-12 09:24
So you have just closed #1483 as the duplicate of #763.
But here in #763 i don't see any commentary why the feature request is closed.
Could you please elaborate on this?

**Comment by Nashev** [comment] 2017-04-07 06:22
It's great, but some times sticker provide some special meaning that is not translated by linked emoji.
If stickers will have some short additional text to clarify they meaning, it will be very useful feature.

**Comment by Nashev** [comment] 2017-04-07 06:32
from #1203:

* I would recommend as separate options: disable all stickers / disable new stickers, so if you already have them it will display. When disabled, to show the original emoji instead.
* > Enable / Disable / Load-on-Click
 
I would prefer option like 

> Stickers: Enable / Do not load new until click / Do not display until click


Or may be

> Display emojis with caption instead of stickers in chat: Never / When sticker not loaded yet / Always 
>   Note: You can tap on this emoji to load and display posted sticker

**Comment by AntonioMichaelAlvarez** [comment] 2019-04-29 08:22
+1 on that.    
Some people tend to spam huge amounts of meaningless stickers. Admins of groups don't know about media preferences or are just lazy to disable stickers. We need client-side option to resize or hide stickers globally or per-group basis.

**Comment by maxoku** [comment] 2020-01-01 16:34
I agree with those suggested options, but I would add another one like showing emoji for a displayed sticker (e.g. on hover), even if it doesn't quite fit to the topic. Displaying stickers (and animated emoji) on smaller size (along with their emoji) would be a good addition too. So many possibilities to make users' life more comfortable. :stuck_out_tongue:

**Comment by maxoku** [comment] 2020-10-24 10:23
I don't think it's solved.

**Closed** 2021-02-11 13:55 UTC
Labels: enhancement

**Comment by RememberTheAir** [comment] 2021-02-11 13:57
Plot twist

**Comment by umazalakain** [comment] 2021-02-11 14:02
Cleaning up day ;)
