### ISSUE TITLE
Actual interface scale is twice smaller after 4.6.0 update on Windows 11

### ISSUE THREAD

**Issue by salnkv** [telegramdesktop/tdesktop#25856] opened 2023-02-07 19:40 UTC
### Steps to reproduce

1. Open Telegram.
2. Go to Settings.
3. Set interface scale to 300%.

On my 4K monitor I set 150% display scale in Windows display settings.
When I check "Default interface scale" toggle in telegram settings it sets 300% in telegram.

I tried to run telegram with `-scale` parameter.
For example `"C:\Users\username\AppData\Roaming\Telegram Desktop\Telegram.exe" -scale 90`
When I open Telegram, in Settings it shows 180%, so I found out that actual value is doubled. And I can't set more than 150 to get more than 300% in settings.
According this manual https://www.journeybytes.com/telegram-desktop-custom-interface-scale/
-scale value was equal to ui value before update 4.6.0.

### Expected behaviour

Actual interface scale is 300% when set 300% in settings.

### Actual behaviour

Actual interface scale is 150% when set 300% in settings.

### Operating system

Windows 11 Pro 22H2 22621.1105

### Version of Telegram Desktop

4.6.1

### Installation source

Static binary from official website

### Logs

[log.txt](https://github.com/telegramdesktop/tdesktop/files/10679041/log.txt)

**Comment by ilya-fedin** [comment] 2023-02-07 20:01
`-scale` argument accepts the number for Telegram's scaling engine, the number in the UI is the overall scaling (Telegram one * Qt's one).

**Comment by salnkv** [comment] 2023-02-07 20:08
Anyway, scaling after 4.6.0 is twice smaller than before. And current max value is to small.
Here is 100% value on 4K monitor. It is ridiculously non-usable.
![image](https://user-images.githubusercontent.com/4014298/217353758-522ac55b-2895-44d9-a060-9a21c6f19764.png)

**Comment by ilya-fedin** [comment] 2023-02-07 20:10
Provide the logs

**Comment by salnkv** [comment] 2023-02-07 20:13
[log.txt](https://github.com/telegramdesktop/tdesktop/files/10679041/log.txt)

**Comment by ilya-fedin** [comment] 2023-02-07 20:14
The logs say your effective scale is 300%. Would be nice to see a log and screenshot from the old version.

**Comment by ilya-fedin** [comment] 2023-02-07 20:16
> Here is 100% value on 4K monitor. It is ridiculously non-usable.

So it's not the 300%? Can you provide a screenshot using 300%?

**Comment by salnkv** [comment] 2023-02-07 20:51
Okay. I checked every version between 4.5.3 and 4.6.0 and found out that scale is broken starting from 4.5.6.

Here is screenshot of 4.5.5 and 4.5.6 side by side with set toggle Default interface scale.
![image](https://user-images.githubusercontent.com/4014298/217358856-6151547d-596e-4150-bc5a-d9fbea429245.png)

4.5.5 with 300% scale log:
[log.txt](https://github.com/telegramdesktop/tdesktop/files/10679195/log.txt)
4.5.5 with 300% scale screen:
![image](https://user-images.githubusercontent.com/4014298/217359397-6829e25f-9924-45da-8daa-c209956321c5.png)

4.5.6 with 300% scale log:
[log.txt](https://github.com/telegramdesktop/tdesktop/files/10679239/log.txt)
4.5.6 with 300% scale screen:
![image](https://user-images.githubusercontent.com/4014298/217359552-56398e60-a830-4b73-a565-98000f2a3b93.png)

As I noticed, DevicePixelRatio is different.

I have 3 monitors (the screenshots above is from 2nd monitor):
![image](https://user-images.githubusercontent.com/4014298/217362209-3bfe0ab3-cfd5-4031-9e75-79680ed1123c.png)
1. ![image](https://user-images.githubusercontent.com/4014298/217361880-65850d99-56a0-4819-ac61-b0625bad61cf.png)
2. ![image](https://user-images.githubusercontent.com/4014298/217361997-c566b331-b809-4f13-adf3-03fb81ac48af.png)
3. ![image](https://user-images.githubusercontent.com/4014298/217362061-75c66787-2462-4c5c-8e8d-12b5e7387aa2.png)

**Comment by ilya-fedin** [comment] 2023-02-07 20:56
So what happens is the maximum scaling is limited by the biggest device pixel ratio in the system that comes from the first monitor (200%). Telegram's scaling engine is sadly not multi-monitor-aware and is not capable for more than 300% scaling, so it limits itself to the safest value that may come in runtime (150% given that there's a monitor with 200% scaling). So Telegram's scaling seem to not to play nice with Qt's multi-monitor-aware scaling what is probably a valid bug, but without obvious solution.

**Comment by ilya-fedin** [comment] 2023-02-07 20:58
Maybe it's also better to get window's device pixel ratio when showing in the UI for less confusion...

**Comment by salnkv** [comment] 2023-02-07 21:10
I changed my main screen from 2nd to first and got this in log.
[2023.02.07 23:09:28] Global devicePixelRatio: 2
[2023.02.07 23:09:28] Primary screen DPI: 96, Base: 96.
[2023.02.07 23:09:28] Computed screen scale: 100
[2023.02.07 23:09:28] DevicePixelRatio: 2
[2023.02.07 23:09:28] ScreenScale: 100

[log.txt](https://github.com/telegramdesktop/tdesktop/files/10679420/log.txt)

**Comment by ilya-fedin** [comment] 2023-02-07 21:11
You probably misunderstood, the point is not in which monitor is first one, but what is the biggest scale value in the system used by any monitor

**Comment by salnkv** [comment] 2023-02-07 21:13
I mean not the first, but main screen. When I changed main screen, the scaling log values changed.

**Comment by ilya-fedin** [comment] 2023-02-07 21:15
Yeah, default scale value depends on main screen, but the maximum possible scale depends on the maximum scale used by any screen in the system

**Comment by salnkv** [comment] 2023-02-07 21:21
Oh, yeah. Look like my laptop's screen has DevicePixelRatio: 2.
I have just disconected it's screen and used my 4K monitor. It has DevicePixelRatio: 1.

[2023.02.07 23:18:48] Global devicePixelRatio: 1
[2023.02.07 23:18:48] Primary screen DPI: 144, Base: 96.
[2023.02.07 23:18:48] Computed screen scale: 150
[2023.02.07 23:18:48] DevicePixelRatio: 1
[2023.02.07 23:18:48] ScreenScale: 150

**Comment by salnkv** [comment] 2023-02-07 21:25
I hope you will fix this issue! 🙏
Thanks!

**Comment by john-preston** [comment] 2023-02-08 04:42
@salnkv Unfortunately, this is a side effect of supporting auto dpi scaling when you drag the window between screens :(

**Comment by john-preston** [comment] 2023-02-08 05:03
@salnkv But even with this 300%-that-is-really-150% it should look similar to all other apps on your desktop (with such interface scale in the system settings) -- like Chrome, File Explorer, etc. They all use 150% like you chose in system settings, right?

**Comment by john-preston** [comment] 2023-02-08 05:05
Because "4.5.5 with 300% scale screen" doesn't really look right (I know it might be nice to be able to scale the things so much up, but the Telegram UI there looks very large compared to the taskbar and all other apps which use 150%). Why not set at least 200% on the 4K screen? It should allow much larger Telegram Desktop scale.

**Comment by ilya-fedin** [comment] 2023-02-09 05:25
4.6.2 should report actual interface scale properly

**Comment by 7Vlad** [comment] 2023-02-09 15:53
OK, I thought it was fonts issue, but @ilya-fedin told me, I have interface scale issue and I am here.
So, what's going on? On 4.5.3 was possibility to scale up to 300% and default interface scale was(at my computer) 125% (first screenshot). On 4.6-4.6.1 maximum interface scale was 300%, and this is was default scale, but real size was smaller - 100%.
On 4.6.2 issue was "fixed" with replacing tag "300%" with tag "100%", and now this is a maximum(second image). 
And, as user who need "Easy of Access", I just want my interface back with 125%, like it was on 4.5.3.
![Screenshot_47](https://user-images.githubusercontent.com/111490433/217865013-2d0b5d6e-9e84-4945-8755-3afcb9b76423.jpg)
![Screenshot_46](https://user-images.githubusercontent.com/111490433/217865035-fd846a9b-a9c2-4dd5-a33d-c5ba01d7bf99.jpg)

**Comment by ilya-fedin** [comment] 2023-02-09 15:59
@7Vlad please provide the details like here
https://github.com/telegramdesktop/tdesktop/issues/25856#issuecomment-1421455521

**Comment by 7Vlad** [comment] 2023-02-09 16:05
@ilya-fedin 
[2023.02.09 17:24:57] Global devicePixelRatio: 3
[2023.02.09 17:24:57] Primary screen DPI: 120, Base: 96.
[2023.02.09 17:24:57] Computed screen scale: 125
[2023.02.09 17:24:57] DevicePixelRatio: 3
[2023.02.09 17:24:57] ScreenScale: 100

**Comment by ilya-fedin** [comment] 2023-02-09 16:06
@7Vlad including monitor arrangement

**Comment by 7Vlad** [comment] 2023-02-09 16:08
@ilya-fedin 
![Screenshot_49](https://user-images.githubusercontent.com/111490433/217868965-e26f93a6-66f2-475c-959a-899595591f9e.jpg)
![Screenshot_50](https://user-images.githubusercontent.com/111490433/217868982-135759bb-0824-49c8-88f4-59c8be2b1dd4.jpg)

**Comment by ilya-fedin** [comment] 2023-02-09 16:09
@7Vlad the point is to see interface scale of all the displays

**Comment by 7Vlad** [comment] 2023-02-09 16:13
@ilya-fedin 
2 more
![Screenshot_51](https://user-images.githubusercontent.com/111490433/217870241-fd0a84fa-0726-41ed-a00d-83ac7e257763.jpg)
![Screenshot_52](https://user-images.githubusercontent.com/111490433/217870263-e1aa96a3-76f3-4868-b37d-3321b1c05bc5.jpg)

**Comment by ilya-fedin** [comment] 2023-02-09 16:17
@7Vlad thanks

**Comment by ilya-fedin** [comment] 2023-02-09 16:25
The problem is:
1. Telegram's scaling engine can't scale to more than 300%
2. Telegram's scaling engine is not multi-monitor capable
3. Qt's scaling engine is multi-monitor capable

Due to (3), Qt will scale the UI 3x once you move Telegram window to the 300%-scaled monitor. Due to (2), Telegram's scaling engine can't handle that and so preemptively limits itself to 100% or bad things will happen once you move the window due to (1) as actual scaling becomes 900%.

**Comment by 7Vlad** [comment] 2023-02-09 16:41
@ilya-fedin 
As I said, on 4.5.3 and before, it was perfect. The problem first appear in 4.6 and it is still here. I don't want to change my monitor configuration in anyway. Bugs must be fixed not on my side, because its works perfect till 4.6 ;)

**Comment by 7Vlad** [comment] 2023-02-09 17:17
@ilya-fedin 
As you can see on my screenshots - all resolutions on my monitors are recommended by Windows 10. I checked, and you are right, when I decrease my scale from 300% to 250% on 4K monitor, the scale in the Telegram jump to 125%, but in this situation, I prefer to stay with 4.5.3 and wait when bug, and this is definitely bug, will be fixed.

**Comment by 7Vlad** [comment] 2023-02-09 17:50
@ilya-fedin 
> Due to (2), Telegram's scaling engine can't handle that and so preemptively limits itself to 100% or bad things will happen once you move the window due to (1) as actual scaling becomes 900%.

By the way, possible solution, if you don't want 900% - fix the maximum scale on Telegram, not on 300%, but on 200-250% in this case. But definitely not on 100%.

**Comment by ilya-fedin** [comment] 2023-02-09 17:53
@7Vlad it would still be 600-750% while the maximum supported scaling is 300%

**Comment by 7Vlad** [comment] 2023-02-09 18:41
@ilya-fedin 


> @7Vlad it would still be 600-750% while the maximum supported scaling by the engine is 300%

Not exactly. As you can see on my screenshot, the maximum not 300%, but 375%. So, its possible to do scale 125% and stay with 300% monitor. And I will be happy :)
![Screenshot_54](https://user-images.githubusercontent.com/111490433/217907238-c8b6158d-4ba6-43e1-84c9-faff841a089a.jpg)

**Comment by ilya-fedin** [comment] 2023-02-10 03:25
@7vlad Qt works in integer-only scaling mode, so you have 300%. You can switch it to fractional scaling mode in experimental settings with the precise scaling option, but you will see it's experimental for a reason.

**Comment by john-preston** [comment] 2023-02-10 04:03
On your screenshots I see 300% recommended and 125% not recommended in system settings. I guess systems recommended setting is 100% there.

Anyway, there is a possibility to make the app a bit larger, around 125%, in case you have scaling more than 100% on some screen, but it needs some more coding.

**Comment by john-preston** [comment] 2023-02-10 04:04
The way 4.5.3 worked is not an option because it had much more serious bug when you move the window between monitors with different scaling, it didn't adapt at all.

**Comment by ilya-fedin** [comment] 2023-02-10 06:12
This will likely be solved by providing more values for the Qt rounding policy in the UI, so people can choose the most appropriate one for their use-case. There's no ETA though and in the meantime it's possible to use the following environment variables as a workaround:
* `QT_ENABLE_HIGHDPI_SCALING=0` - forces Qt to disable its scaling engine, returns pre-4.6 behavior
* the combination of `QT_SCALE_FACTOR_ROUNDING_POLICY=Ceil` and `QT_DPI_ADJUSTMENT_POLICY=AdjustDpi`  will force Qt to provide a bigger devicePixelRatio to smaller screens, so it should preserve auto-rescaling between monitors, but allowing bigger values for Telegram's scaling, with the downside of that auto-rescaling won't work in use-case like between 125% and 200% monitor (but will still work between e.g. 125% and 300%) as Qt will use devicePixelRatio=2 for both.

**Comment by 7Vlad** [comment] 2023-02-10 08:23
@ilya-fedin 
The screenshot above, is from 4.6.2, and as you see, 150% in Telegram and 250% in Windows works together fine.
So, maybe, 125% in Telegram and 300% in Windows will work too?
Now I am restricted on 100% in Telegram, maybe its possible to move restriction to 125% and I will test it?

**Comment by ilya-fedin** [comment] 2023-02-10 08:37
@7Vlad it works ok because 250% gets devicePixelRatio=2 (200%), 150*2=300

**Comment by 7Vlad** [comment] 2023-02-10 08:49
@ilya-fedin 
I see. Any way to switch to 125% and still have 300% on 4K monitor? It is Windows 10 standard recommendation, not my custom scale. So Telegram need to do something with this fact...

**Comment by ilya-fedin** [comment] 2023-02-10 08:57
@7Vlad well, tdesktop has bad HiDPI support for ages (#1121), the reason is it was developed before Qt got HiDPI scaling support and Telegram's own HiDPI engine doesn't support features like multi-monitor support modern applications needs. So tdesktop requires a complete UI rewrite to get the proper support, this hasn't happen in 7 years and unlikely to happen any time soon. So you have to wait and I really recommend to apply some workaround.

**Comment by brettcp** [comment] 2023-02-10 20:01
Same issue here, I have (3) 2560x1440 displays at 125% scale on Windows 11.  The scaling is way too small even at Telegram's max setting of 300%.  I had to roll back to Telegram 4.5.3 until this is resolved.

**Comment by 7Vlad** [comment] 2023-02-12 12:02
@ilya-fedin 
Ok, here a proof, that 4.6.2 can work with 125% and even with 150% with one of display's has 300% and nothing happened wrong.
So the limitation only in the code and there any problem to allow to users, choose proper scale. 
![Screenshot_55](https://user-images.githubusercontent.com/111490433/218309820-8777c6f4-0def-4b57-993d-96af722c2624.jpg)
![Screenshot_56](https://user-images.githubusercontent.com/111490433/218309828-fa126596-f43c-44fa-84a1-1ca7100047f7.jpg)

**Comment by ilya-fedin** [comment] 2023-02-12 12:07
@7Vlad the bad thing will happen when you move the window to 300% screen

**Comment by ilya-fedin** [comment] 2023-02-12 12:11
> Same issue here, I have (3) 2560x1440 displays at 125% scale on Windows 11.

You mean all the screens use 125% scale, no screens with 200% scale or 300% scale? If yes then it sound like a different issue, would be nice to see your log.tzt.

**Comment by 7Vlad** [comment] 2023-02-12 12:20
@ilya-fedin 
Of course, I checked this options. Nothing "bad" happens. Even when I move TG with 150% scale (it is really huge :) ).
You can check it by yourself

**Comment by ilya-fedin** [comment] 2023-02-12 12:26
> Even when I move TG with 150% scale (it is really huge :) ).

Hmm, in the best scenario the graphics should become blurry. In the worst scenario it may crash.

> You can check it by yourself

Well, I don't have a display with such large resolution

**Comment by 7Vlad** [comment] 2023-02-12 12:28
@ilya-fedin 
I can provide actual screenshots on my 4k display. Will it help?

**Comment by ilya-fedin** [comment] 2023-02-12 12:28
Would be nice to see them, although only @john-preston can decide whether larger scale could be allowed.

**Comment by 7Vlad** [comment] 2023-02-12 12:57
@ilya-fedin 
ok, here we go. By the way, when I move TG windows to 4K display, the scale grow on fly :)
![Screenshot_58](https://user-images.githubusercontent.com/111490433/218312371-c8bda7d1-efd4-47a3-9ab5-58adb8edf49b.jpg)
![Screenshot_57](https://user-images.githubusercontent.com/111490433/218312374-d00bf7c5-4ce6-4bf7-8284-a16e43a6839e.jpg)

**Comment by ilya-fedin** [comment] 2023-02-12 12:59
> By the way, when I move TG windows to 4K display, the scale grow on fly :)

And that's why the scale is limited even when not on that on monitor (Qt scales up, but Telegram code can't scale down on the fly)

**Comment by 7Vlad** [comment] 2023-02-12 13:12
@ilya-fedin 
When I move TG from 4K display, actually - the scale down on fly too, from 375% to 125%. So I don't see any problem to allow this to users...

**Comment by ilya-fedin** [comment] 2023-02-12 13:15
@7Vlad I don't see any raster graphics on your screenshot, it's not really representative, a good example would be the icons in the message input field or icons in the drawer

> When I move TG from 4K display, actually - the scale down on fly too

It's Qt, again. Scaling done by Telegram code remains constantly at 150% during your current run.

**Comment by 7Vlad** [comment] 2023-02-12 13:33
@ilya-fedin 
If you need any screenshot, I can provide it. But I need to know exactly what to show.
As for now, it work good on any display, even with 300% and can be TG scale with 125% or 150%.
If you don't want to implement 125% in the code, maybe you can provide some registry hack, for people who really need those 125% TG scale, but don't want to play with settings any time when the computer need to be restarted...

**Comment by ilya-fedin** [comment] 2023-02-12 13:35
> If you need any screenshot, I can provide it. But I need to know exactly what to show.

> a good example would be the icons in the message input field or icons in the drawer

> If you don't want to implement 125% in the code, maybe you can provide some registry hack, for people who really need those 125% TG scale, but don't want to play with settings any time when the computer need to be restarted...

There's already plan to solve this (https://github.com/telegramdesktop/tdesktop/issues/25856#issuecomment-1425244582), but this needs time

**Comment by 7Vlad** [comment] 2023-02-12 13:56
@ilya-fedin 
So, how I can implement those settings, because now, my changes work only till restart?
Some .ini/cfg file editing, or registry hack?

**Comment by ilya-fedin** [comment] 2023-02-12 14:04
@7Vlad you want to work on that? It's better to ask @john-preston for details as there was a plan to also choose the default rounding policy based on whether any of monitors have 300% scale using Windows platform API.

**Comment by ilya-fedin** [comment] 2023-02-12 14:06
Note that the comment I linked to provides the description of how you can change the rounding policy right now.

**Comment by ilya-fedin** [comment] 2023-02-12 14:12
Or if you meant "how I can set the environment variables", Google should answer perfectly fine this question, personally I recommend to create a batch script with the following content:
```
@echo off
set QT_SCALE_FACTOR_ROUNDING_POLICY=Ceil
set QT_DPI_ADJUSTMENT_POLICY=AdjustDpi
C:\Path\To\Telegram.exe
```
Note that `QT_DPI_ADJUSTMENT_POLICY=AdjustDpi` is already applied in the code on dev branch and becomes irrelevant in the next release.

**Comment by 7Vlad** [comment] 2023-02-12 15:26
@ilya-fedin 
Thanks, works perfect, even there are no possibility to scale to 125%, but with step 10 till 200%, so I choose 120%
Also, instead of your last line, I recommend to use this one - it will also close cmd
cmd /c start C:\Path\To\Telegram.exe
Also, I pay attention, that on forwarded messages, the fonts looks worse, than in my method.
So, how I force 125% or even 150% scale with 300% on 4K display? Very simple - I decrease from 300 to 250 on 4K display, run TG, change it to 125% and after that, get back 250% to 300% on 4K. And TG still stay on 125%. 
Maybe you can use this hack to make some improvement, because its works better than .bat file?

**Comment by ilya-fedin** [comment] 2023-02-12 15:31
> Also, instead of your last line, I recommend to use this one - it will also close cmd
> cmd /c start C:\Path\To\Telegram.exe

Shouldn't there be no difference given that Telegram is a GUI application and releases the console window?

> So, how I force 125% or even 150% scale with 300% on 4K display?

Well, you have to ask @john-preston to allow scale values less than 50% (50 * 3 = 250)

**Comment by 7Vlad** [comment] 2023-02-12 15:36
> Shouldn't there be no difference given that Telegram is a GUI application and releases the console window?

Not exactly. Most of time it didn't releases the console window...
@john-preston 
Could you help us here, please?

**Comment by ilya-fedin** [comment] 2023-02-12 16:17
> Could you help us here, please?

Shouldn't you have the possibility to use 150% right now? I believe it's only 125% that is missing as 50 * 3 = 150

**Comment by ilya-fedin** [comment] 2023-02-12 16:18
> Not exactly. Most of time it didn't releases the console window...

Even without `cmd /c`, just with `start`?

**Comment by EvinceMoi** [comment] 2023-02-14 09:06
> Or if you meant "how I can set the environment variables", Google should answer perfectly fine this question, personally I recommend to create a batch script with the following content:
> 
> ```
> @echo off
> set QT_SCALE_FACTOR_ROUNDING_POLICY=Ceil
> set QT_DPI_ADJUSTMENT_POLICY=AdjustDpi
> C:\Path\To\Telegram.exe
> ```
> 
> Note that `QT_DPI_ADJUSTMENT_POLICY=AdjustDpi` is already applied in the code on dev branch and becomes irrelevant in the next release.

In my case, the `QT_SCALE_FACTOR_ROUNDING_POLICY=Ceil` env made the UI much larger on my secondary 4K monitor, eventually I found the `QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough` more suitable for me, with the price of a little bit non-smooth font looks

**Comment by ilya-fedin** [comment] 2023-02-14 09:08
> In my case, the `QT_SCALE_FACTOR_ROUNDING_POLICY=Ceil` env made the UI much larger on my secondary 4K monitor

Along with `QT_DPI_ADJUSTMENT_POLICY=AdjustDpi`? It's important to set it before the next release.

**Comment by ilya-fedin** [comment] 2023-02-14 09:10
> I found the `QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough` more suitable for me

It's possible to set it from the UI, in the experimental settings

**Comment by 7Vlad** [comment] 2023-02-14 10:07
> Shouldn't you have the possibility to use 150% right now? I believe it's only 125% that is missing as 50 * 3 = 150

With my hack, I can use 150% and 300% scale on 4k display. But I need only 125%, 150% too big :)
![Screenshot_62](https://user-images.githubusercontent.com/111490433/218704276-afe60bc8-6465-4635-b4c8-2583544bdf2e.jpg)

**Comment by ilya-fedin** [comment] 2023-02-14 10:16
But what's the point to use 125% if your system scale is 300%? Shouldn't it be too small?

**Comment by EvinceMoi** [comment] 2023-02-14 12:20
> Along with `QT_DPI_ADJUSTMENT_POLICY=AdjustDpi`? It's important to set it before the next release.

Just tested on my machine, with or without this env won't make any difference

> It's possible to set it from the UI, in the experimental settings

This works just like setting the env, but much simpler, thank you for the tips ;-)

**Comment by john-preston** [comment] 2023-02-14 12:27
@EvinceMoi I suggest you use Ceil + bring the scale down in Settings. That way the rendering would be still pixel-perfect and you should be able to achieve relatively same elements size by scaling down in Settings.

**Comment by ilya-fedin** [comment] 2023-02-14 13:05
I'm totally confused. If you need 125% scale on non-300% monitor then it should work just fine, well, it won't be exactly 125%, but 120%-130%, should be acceptable I believe.

**Comment by 7Vlad** [comment] 2023-02-14 17:26
> I'm totally confused. If you need 125% scale on non-300% monitor then it should work just fine, well, it won't be exactly 125%, but 120%-130%, should be acceptable I believe.

OK, lets make its clear:
1. I have 3 monitors. Main monitor 2560x1080 and I use TG on it, also 3hd monitor is 4k with 300% -Windows default
2. With your hack (bat file), I can set TG scale to 120% or 130%, but fonts looks worse than in my hack.
3. With my hack - decrease scale of 3hd monitor to 250%, and then set TG scale to 125%-150% and set scale of 3hd monitor back to 300% everything works perfect, but only till restart.

So my question is - if with my hack everything works perfect, and I prove it even when I moved TG window to 3hd monitor with 300% scale, why it cannot be implementing in code?

**Comment by john-preston** [comment] 2023-02-14 17:31
@7Vlad Because Qt assignes devicePixelRatio to monitors, it allows to specify rounding algorithm, but none of them can assign value 2 for the 300% scale. But it can assign 2 for 250% scale and keep it while the app is running.

**Comment by 7Vlad** [comment] 2023-02-14 17:35
@john-preston 
As I said, and prove it with screenshot above, 150% works too, while the app is running...

**Comment by ilya-fedin** [comment] 2023-02-14 18:11
> and I prove it even when I moved TG window to 3hd monitor with 300% scale

I've asked you to provide a screenshot with raster icons [here](https://github.com/telegramdesktop/tdesktop/issues/25856#issuecomment-1427030649), with an example of where you can find ones.

**Comment by 7Vlad** [comment] 2023-02-14 18:24
@ilya-fedin 
Sorry, can you post screenshot of example of what are you need?

**Comment by ilya-fedin** [comment] 2023-02-14 19:33
![изображение](https://user-images.githubusercontent.com/17829319/218838738-0a9ce706-2270-406f-8ef3-186d1ea89ea5.png)

**Comment by 7Vlad** [comment] 2023-02-14 20:51
@ilya-fedin 
![Screenshot_63](https://user-images.githubusercontent.com/111490433/218860258-11d26350-6afa-449e-a978-83db866c38c1.jpg)

**Comment by 7Vlad** [comment] 2023-02-15 10:48
@ilya-fedin 
 This is from 375%
![Screenshot_64](https://user-images.githubusercontent.com/111490433/219006675-b8edbeab-507d-4bb1-82a9-bc27ba6794ca.jpg)

**Comment by ilya-fedin** [comment] 2023-02-15 10:49
@7Vlad here's the problem
![изображение](https://user-images.githubusercontent.com/17829319/219006951-c8273d53-4a9b-4210-9ef3-5b81200b0269.png)

**Comment by 7Vlad** [comment] 2023-02-15 10:52
@ilya-fedin 
Not a big one, like with small TG scale 100% , when you cannot use TG at all.
So you icons looks better, when you zoom it, but you cannot use TG, because you not see it well :)
Fix very small problem, but instead receive a big one.
And, as I said, I didn't use TG on display with Windows default 300% scale.

**Comment by ilya-fedin** [comment] 2023-02-15 10:54
@7Vlad I believe that's the reason @john-preston doesn't allow more than 300%

**Comment by 7Vlad** [comment] 2023-02-15 11:02
@ilya-fedin 
But normal usage of TG is more important than such icons (and I didn't see any problem, before you zoom it :) ), so maybe possible to adjust it to 375%, so we can use 125% zoom, or 360% - 120% zoom?

**Comment by ilya-fedin** [comment] 2023-02-15 11:05
@7Vlad are slightly worse fonts really a deal? That's how they were if tdesktop was fully supporting Qt scaling, even with fractional scales (as Qt's scaling engine doesn't support hinted fonts).

**Comment by ilya-fedin** [comment] 2023-02-15 13:01
> They not "worse", they smaller in 25% and unreadable for some people.

smaller fonts while the rest of the UI is the same? can you provide comparison screenshots?

**Comment by 7Vlad** [comment] 2023-02-15 13:05
> smaller fonts while the rest of the UI is the same? can you provide comparison screenshots?

Everything smaller, because maximum scale 100%, including fonts

**Comment by ilya-fedin** [comment] 2023-02-15 13:14
@7Vlad use the ceil workaround

**Comment by 7Vlad** [comment] 2023-02-15 14:10
@ilya-fedin 
I use my own workaround, as I said above, because it's not have problems with fonts and icons on my mail display, like in "ceil" workaround. But if I restart computer, need to do it again.

**Comment by ilya-fedin** [comment] 2023-02-15 14:11
@7Vlad I asked you which problems with fonts the ceil workaround has, but you started talking about small fonts and being unable to scale more thwwn 100%

**Comment by ilya-fedin** [comment] 2023-02-16 09:06
4.6.3 is out with `QT_DPI_ADJUSTMENT_POLICY=AdjustDpi` being by default and rounding the default scale to the near 5% instead of the near 25%.

**Comment by 7Vlad** [comment] 2023-02-16 13:25
@ilya-fedin 


> I asked you which problems with fonts the ceil workaround has, but you started talking about small fonts and being unable to scale more than 100%

here we go, with your "ceil" hack
![Screenshot_68](https://user-images.githubusercontent.com/111490433/219377018-0397a806-88f9-410b-898f-f7273ec6948c.jpg)

**Comment by ilya-fedin** [comment] 2023-02-16 13:28
Oh hell, that's not what I observer with it.... Maybe because you have a 300% screen...

**Comment by 7Vlad** [comment] 2023-02-16 13:32
> Oh hell, that's not what I observe with it.... Maybe because you have a 300% screen...

But this is happened on my main screen 2560x1080 125%

**Comment by 7Vlad** [comment] 2023-02-16 20:07
@ilya-fedin 
Ok, if you need more screenshots, please provide detailed instructions: on which monitor and with which scale, scale of TG, which hack :)

**Comment by ilya-fedin** [comment] 2023-02-16 20:14
@7Vlad run with the ceil hack and set 200% interface scale in Telegram, will the icons still be bad?

**Comment by 7Vlad** [comment] 2023-02-17 07:10
@ilya-fedin 
With 200% ceil hack its looks better, but on my main display its too big, impossible to use, worse than 375% on my 300% scale 4k display
![Screenshot_70](https://user-images.githubusercontent.com/111490433/219574275-dc35485b-0ce1-4b6a-bad6-88c8aaee0ce7.jpg)

**Comment by Cristy94** [comment] 2023-02-17 12:50
I also have scaling issues after a recent update (~1 month). Opening telegram on a 4K screen with 150% scale, sometimes makes the application zoomed in like 4x (it's not consistent, sometimes it opens fine after a restart, but most of the time it opens zoomed-in).

**Comment by 5ta1da** [comment] 2023-02-25 18:10
Simple solution for Windows users:

Right click on _Shortcut_ - _Properties_ - _Compatibility_ - _Change high DPI setting_ button - on bottom tick on _Override_ option and select _System (Enhanced)_

After this default size is bigger and you can go over 100% with the slider in UI size settings.

**Comment by ilya-fedin** [comment] 2023-02-25 18:50
@5ta1da and it still looks crisp when moved to the 300% monitor with that option enabled?

**Comment by 5ta1da** [comment] 2023-02-25 19:24
Im running Windows in non-english language, so I cannot tell exactly.

Its in compatibility section in properties of Telegram shortcut used for launching app via right-click menu.

**Comment by ilya-fedin** [comment] 2023-02-25 19:27
Excuse me, but how my question is related to system language?

**Comment by Cristy94** [comment] 2023-02-26 01:42
> Simple solution for Windows users:
> 
> Right click on _Shortcut_ - _Properties_ - _Compatibility_ - _Change high DPI setting_ button - on bottom tick on _Override_ option and select _System (Enhanced)_
> 
> After this default size is bigger and you can go over 100% with the slider in UI size settings.

This fixed the scale, but made the entire application blurry. If I change the scale to 150% inside the app now, it makes it too big again and also blurry.

**Comment by Cristy94** [comment] 2023-03-07 15:17
Ok, so I found a weird way to reproduce this.

If I open the app directly from the shortcut, it opens at the right scale.
If I open the app through my keyboard binding (handled by Roccat Swarm, and pointing to the same shorcut .ink file), then the scaling is always wrong (app is zoomed in like 4x).

This hasn't happened since a few weeks ago and nothing has changed with the key binding, so I assume it is a Telegram update. I am not sure what's different when opening the app through the keyboard shortcut or by clicking on the shorcut (maybe some timing differences where some concurrency makes the retrieved windows scale/size to be wrong (?)).

**Comment by ilya-fedin** [comment] 2023-03-07 15:22
@Cristy94 check how Telegram reports scaling value in its settings

**Comment by ilya-fedin** [comment] 2023-03-16 04:10
This should be fixed in 4.6.11, the 300% limit is removed

**Comment by ykoala** [comment] 2023-03-17 11:30
I have another scaling related issue sometime since the introduction of "precise High DPI scaling".
The setup is one 4k display with 150% and one smaller display with 100% scaling. Before the latest changes I used tdesktop on the secondary display exclusively because I didn't know of the way to make it look OK when moving the window between the displays. Now auto-scaling works fine, but the issue is: when the application is started with the remembered position on the secondary display, it always resizes its window to make it 1.5 times smaller than it was on shutdown. At some point it stops resizing (when the lower size limit is reached I guess).
Thought it's not a big deal, it's kinda weird to resize the window manually each time on startup. And in my opinion secondary display is really fit for the things like mail, messengers, etc leaving the primary for the main stuff, so I'd like to keep the app there.
[log.txt](https://github.com/telegramdesktop/tdesktop/files/11000828/log.txt)
![изображение](https://user-images.githubusercontent.com/8509249/225892421-5d24bab6-71d7-4be6-8cd9-1403b900d851.png)
![изображение](https://user-images.githubusercontent.com/8509249/225892462-4221adc0-6cfc-4e68-9731-9b33199e0943.png)

**Comment by ilya-fedin** [comment] 2023-03-17 11:35
> it always resizes its window to make it 1.5 times smaller than it was on shutdown

Just resizes or runs with wrong scale?

**Comment by ykoala** [comment] 2023-03-17 11:47
Just resizes.

**Comment by ilya-fedin** [comment] 2023-03-17 11:50
I don't think there were any checks whether all the functionality works ok in that mode as it screws all the graphics to the point that feels unusable. Due to this I'm also highly doubt there would be any investments in fixing issues in that mode.

**Comment by ykoala** [comment] 2023-03-17 12:06
Not sure I got you right.
Almost everything is working fine for me in "that mode". When moving the window from secondary to primary it gets 1.5x times (bigger pixel wise) and vice versa. Scaling in the app auto-changes 150<->100. Fonts look OK (but slightly differ from screen to screen).
No problems there. Only the one that resizes the window on the startup on the display that uses different scaling value. I guess the position and size are saved. And while the former is unaffected, the latter is recalculated for some non-obvious reason.

**Comment by ilya-fedin** [comment] 2023-03-17 12:24
@ykoala the graphics in that mode looks like #17173 from our testing

**Comment by john-preston** [comment] 2023-03-17 12:38
@ykoala Do you test with "Enable precise High DPI scaling" experimental setting enabled? Just to make it clear.

**Comment by ykoala** [comment] 2023-03-17 12:55
@john-preston, yes, I do. But it does not matter in the startup resizing issue.
Though it affects the scaling behavior. In-app scaling is set to whatever value and keeps unchanged when moving the window between displays. The window size changes 1.5x times.
Also tried using the "default scaling" = "on", still the same.

**Comment by ilya-fedin** [comment] 2023-03-17 12:57
> But it does not matter in the startup resizing issue.

You say it's also happening without the option enabled?

**Comment by ykoala** [comment] 2023-03-17 12:57
Yes.

**Comment by 7Vlad** [comment] 2023-03-20 15:23
@ilya-fedin 
New version is cool and now I have any scale I want without tricks.
But I found some bug - when I right-click near message to choose emoji to react, sometimes TG fail and shutdown.

**Comment by john-preston** [comment] 2023-03-21 05:59
@7Vlad Are you using 32 bit build of the application? Because if so it may crash due to OOM with very large interface scale values (the scaled is multiplied by maximum device pixel ratio and the memory requirement is square of that usually).

**Comment by 7Vlad** [comment] 2023-03-29 14:06
@john-preston 
No, 4.7.1 x64

**Closed** 2023-03-31 00:18 UTC
Labels: bug, waiting for answer
