### ISSUE TITLE
Message with updates can not be seen, leaving one notification until restart

### ISSUE THREAD

**Issue by facundobatista** [telegramdesktop/tdesktop#5678] opened 2019-02-11 11:15 UTC
### Steps to reproduce
1. Wait until a button appears that says "Update Telegram" below all the conversations
2. Click to update
3. Wait until restart

### Expected behaviour
It should restart, and the first conversation that should appear, with one message to read, should be the one telling what the update was about.

### Actual behaviour
That message appears for ~200ms, and then disappear. Can not be find. It's not marked as "read", so the icon in the systray says "1" as the message is unread. To remove that "1" in the systray icon I need to quit Telegram and start it again.

### Configuration
**Operating system:** KDE Neon on Ubuntu Bionic

**Version of Telegram Desktop:** 1.5.12 (but happened at least the last 4 times it updated, too)

**Used theme**: Classic

(I'd love to provide logs, where can I find them?)

Thanks!!

**Comment by RememberTheAir** [comment] 2019-02-11 11:40
Duplicate of #5674 (yeah its title could have been a bit more descriptive, but it's the same issue)

**Closed** 2019-02-11 12:53 UTC

**Comment by KnorpelSenf** [comment] 2019-02-11 16:27
> Duplicate of #5674 (yeah its title could have been a bit more descriptive, but it's the same issue)

You're right, it should've. Sorry about that. Great that it's fixed now.
