### ISSUE TITLE
Crash when cancel image choosing for new group/channel (Linux)

### ISSUE THREAD

**Issue by nsauk** [telegramdesktop/tdesktop#2604] opened 2016-11-06 11:58 UTC
### Steps to reproduce
1. With pencil button open window for create new group or new channel
2. Select any, click Next
3. Click on image chooser (square with camera icon)
4. Press Esc on keyboard or Cancel in window
5. Telegram crashed

### Expected behaviour
Just closed image chooser window

### Actual behaviour
Crashed with `ASSERT: "!isEmpty()" in file /usr/local/tdesktop/Qt-5.6.2/include/QtCore/qlist.h, line 337`

### Configuration
**Operating system:** Ubuntu 14.04.3 LTS

**Version of Telegram Desktop:** 0.10.19

### Logs

`ASSERT: "!isEmpty()" in file /usr/local/tdesktop/Qt-5.6.2/include/QtCore/qlist.h, line 337`

With debugmode no additional logs with crash.

**Comment by auchri** [comment] 2016-11-06 12:44
Duplicate of #2595

**Closed by auchri** 2016-11-06 12:44 UTC
