### ISSUE TITLE
[gnome] [wayland] Built-in calls window.

### ISSUE THREAD

**Issue by reagentoo** [telegramdesktop/tdesktop#8715] opened 2020-10-02 21:09 UTC
### Steps to reproduce
1. Startup gnome on wayland
2. Load tdesktop wayland native (`QT_QPA_PLATFORM=wayland telegram-desktop`)
3. Make a call.

### Expected behaviour
Standalone call window

### Actual behaviour
No-movable calling window inside a main telegram-desktop window.
It is not possible to see the call window until the main window is maximized to full screen.

### Configuration
Gentoo Linux

**Version of Telegram Desktop:**

∞ - 2.4.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

Package.

**Used theme**:

gnome adwaita (default)
telegram default

**Comment by ilya-fedin** [comment] 2020-10-02 21:24
Screenshot?

**Comment by reagentoo** [comment] 2020-10-03 11:18
@ilya-fedin Hi,

<a>![url](https://i.imgur.com/X4Ni0Ol.png)</a>

**Comment by Tids** [comment] 2020-10-03 13:39
I can confirm that the call "area" is not visible in portrait window mode. I need to resize the window pretty much to have access to the controls.

**Comment by ilya-fedin** [comment] 2020-10-03 15:44
@reagentoo can you reproduce this with binary from desktop.telegram.org?

**Comment by reagentoo** [comment] 2020-10-03 16:25
@ilya-fedin same result with binary:
<a>![url](https://i.imgur.com/ie96hQp.png)</a>

**Comment by achimfrase** [comment] 2020-10-04 09:37
I get the following error when I start telegram from a terminal.
And I also don't have system window decorations available. The setting isn't available like in the previews version of telegram.

`$ flatpak run org.telegram.desktop 

(process:2): Telegram-WARNING **: 11:32:45.296: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 11:32:45.297: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 11:32:45.297: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
QSocketNotifier: Can only be used with threads started with QThread
Telegram-Message: 11:32:45.424: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
QCoreApplication::postEvent: Unexpected null receiver
`

Regards, Achim

**Comment by ilya-fedin** [comment] 2020-10-04 09:39
> The setting isn't available like in the previews version of telegram.

Yeah, it was removed for GNOME Wayland users since GNOME doesn't support xdg-decoration protocol and Qt's dummy decorations are used when enabling this option.

**Comment by nitroin** [comment] 2020-10-04 15:13
> > The setting isn't available like in the previews version of telegram.
> 
> Yeah, it was removed for GNOME Wayland users since GNOME doesn't support xdg-decoration protocol and Qt's dummy decorations are used when enabling this option.

Any chanches to have Qt's dummy decorations re-introduced?

**Comment by ilya-fedin** [comment] 2020-10-04 18:57
> Any chanches to have Qt's dummy decorations re-introduced?

No chances, they are definitely worse:
![](https://user-images.githubusercontent.com/8373027/75949184-6fd2e980-5ee0-11ea-92ef-cae37a56a81f.png)

**Comment by nitroin** [comment] 2020-10-05 07:59
Ok, thank you. I see that a workaround is provided here #8734.

This looks like a controversial topic in the GNOME community.

**Comment by ilya-fedin** [comment] 2020-10-05 08:17
> This looks like a controversial topic in the GNOME community.

They removed the possibility to have server-side decorations and they got exactly what they wanted: each app on each toolkit has its own decoration style.

**Comment by Tids** [comment] 2020-10-05 08:37
@nitroin position of upstream is clear for years: https://wiki.gnome.org/Initiatives/CSD, in short: _draw your app yourself and respect gsettings_

**Comment by ilya-fedin** [comment] 2020-10-05 08:39
> position of upstream is clear for years: https://wiki.gnome.org/Initiatives/CSD, in short: _draw your app yourself and respect gsettings_

They are forgetting that there are not only gnome and third-party apps on other toolkits won't do that they saying

**Comment by ilya-fedin** [comment] 2020-10-05 09:05
@reagentoo can you give result of `env | grep QT`?

**Comment by reagentoo** [comment] 2020-10-05 09:07
@ilya-fedin 
```
$ env | grep QT
QT_IM_MODULE=ibus
```

**Comment by ilya-fedin** [comment] 2020-10-05 09:11
Are you sure that `QT_WAYLAND_DISABLE_WINDOWDECORATION` is not set somewhere?

**Comment by Tids** [comment] 2020-10-05 09:13
> 
> They are forgetting that there are not only gnome and third-party apps on other toolkits won't do what they saying

I'm sad that you get it this way. It's meant to give the app full control on how to display everything. That this needs restructuring is obvious, but nothing that comes out of place. Nowadays you have this everywhere, from Windows, to macOS, to things like Deepin or elementaryOS. Even XFCE takes on that path.
Hm, this is getting a bit to OT. So I shut up now about that topic now. :s

**Comment by reagentoo** [comment] 2020-10-05 09:16
> Are you sure that `QT_WAYLAND_DISABLE_WINDOWDECORATION` is not set somewhere?
Yes, I'm sure. As I said I'm running `QT_QPA_PLATFORM=wayland telegram-desktop` from terminal.

**Comment by ilya-fedin** [comment] 2020-10-05 09:18
> Nowadays you have this everywhere,

Well, you still can use platform decorations on Windows and macOS, you can't use them with what GNOME offers. They are saying that this due to the fact that Windows and macOS have a platform toolkit, but they should return to the reality and understand that there won't be such toolkit on Linux, Linux is constructor and that's why server-side decorations are mandatory, there are just no other reliable way to give platform decorations.

**Comment by ilya-fedin** [comment] 2020-10-05 09:19
> Yes, I'm sure. As I said I'm running `QT_QPA_PLATFORM=wayland telegram-desktop` from terminal.

Please recheck. That window doesn't have FramelessWindowHint, so it can't be without decorations.

**Comment by ilya-fedin** [comment] 2020-10-05 09:32
But it may be a child widget instead of a window, yes...

**Comment by reagentoo** [comment] 2020-10-05 09:36
> Please recheck. That window doesn't have FramelessWindowHint, so it can't be without decorations.

Now without firejail. There are definitely no other env.
<a>![url](https://i.imgur.com/dwZMgez.png)</a>

**Comment by ilya-fedin** [comment] 2020-10-05 09:37
@reagentoo fix is in progress

**Closed** 2020-10-05 15:30 UTC
Labels: wayland
