### ISSUE TITLE
Update fails on Fedora Linux

### ISSUE THREAD

**Issue by alex-voodoo** [telegramdesktop/tdesktop#16884] opened 2021-09-02 04:17 UTC
### Steps to reproduce
1. Click the blue "Update Telegram" button in the main app window.

### Expected behaviour

The application restarts using the binary executable of the new version.

### Actual behaviour

The application closes but cannot start because the Telegram binary executable file is corrupted.  I once compared the corrupted file that I had locally with the solid one that I downloaded from the website, and it turned out that the updater failed to write the whole file: the contents in the bad and in the good file were identical up to the EOF that was too early in the bad file

### Configuration
**Operating system:** Fedora Linux, version 34 at the moment, but I had this issue on earlier versions.

**Version of Telegram Desktop:** I experience this issue for quite a long time, perhaps a few months.  It worked before, but stopped working a few releases ago.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: The official website.

**Used theme**: The standard one (I use the dark mode sometimes).

**Comment by Aokromes** [comment] 2021-09-02 04:37
what version you are using and to what version is trying to be updated?
a but with 3.0.0 binaries was fixed on windows, maybe it's same issue.

**Comment by alex-voodoo** [comment] 2021-09-02 04:43
The most recent time I got the issue was today, when upgrading from 3.0.0 to 3.0.1.  The previous time was I think yesterday, upgrading from 2.x.x to 3.0.0.  I don't remember when it started to happen, but since then, it never upgraded automatically.  Every time I had to download the actual version from the website, unpack it manually, and replace the corrupted binary.

**Comment by john-preston** [comment] 2021-09-02 07:59
That is really strange. Can you provide the file size of the unpacked binary (corrupted) and the normal, downloaded from site? Because I autoupdate on Ubuntu 20.04 each time and everything is fine. How can it write not a full file? 🤔

**Comment by alex-voodoo** [comment] 2021-09-02 11:38
I have kept the corrupted binary for version 3.0.0, the file size is 46,055,424 bytes.  The valid file is around 100 MB, I cannot tell the exact size for the version 3.0.0, but 3.0.1 has 106,780,368 bytes.  I have no idea how it can write an incomplete file, but at my system that happens every time.

**Comment by alex-voodoo** [comment] 2021-09-20 03:35
Today this happened again, with the upgrade to version 3.1.0 from the previous one (likely 3.0.1).  I hit the blue button, the application exited and failed to start again.
The new binary that the updater has downloaded is 64,061,440 bytes long.  The valid file is 102,167,240 bytes long.  The contents of both files are identical up to premature EOF in the corrupted one.

**Comment by ilya-fedin** [comment] 2021-09-20 13:34
Maybe that machine has a bugged kernel or dying HDD/SSD?

**Comment by alex-voodoo** [comment] 2021-09-20 14:19
My kernel and FS are standard ones, nothing unusual or experimental.  A dying SSD could be a reason, but why do I always get an issue with upgrading Telegram and never—with anything else?

**Comment by Aokromes** [comment] 2021-09-20 14:27
> My kernel and FS are standard ones, nothing unusual or experimental. A dying SSD could be a reason, but why do I always get an issue with upgrading Telegram and never—with anything else?

can you try downloading the binary from desktop.telegram.org to see if it cuts? if yes test multiple times.

**Comment by ilya-fedin** [comment] 2021-09-20 14:41
> My kernel and FS are standard ones, nothing unusual or experimental.

Nevertheless, are they exactly the same? The fact they're standard ones doesn't mean Telegram can't encounter a bug in them.

> A dying SSD could be a reason, but why do I always get an issue with upgrading Telegram and never—with anything else?

I have no idea. No one else seem to exhibit from that issue.

**Comment by alex-voodoo** [comment] 2021-09-20 17:08
> can you try downloading the binary from desktop.telegram.org to see if it cuts? if yes test multiple times.

After the auto update fails, I go to the website and get a tar.xz from there.  I did that many times, and every time it was valid.

**Comment by alex-voodoo** [comment] 2021-09-20 17:10
> Nevertheless, are they exactly the same? The fact they're standard ones doesn't mean Telegram can't encounter a bug in them.

I use ext4 on both machines.  The kernel may be slightly different, in fact I have different CPUs (AMD vs. Intel), but the version should be more or less in sync because I try to update the system frequently on both hosts.

**Comment by a5r0n** [comment] 2021-09-25 17:03
i have the same problem. 
just update to 3.1.1, telegram didn't start again.
when trying to run the binary from terminal, i got `permission denied` and after `chmod +x` it - trying again and got `segmentation fault`

**Comment by ilya-fedin** [comment] 2021-09-26 02:44
Maybe updater crashes while extracting the files? :thinking: 
Can someone look in coredumpctl and check that theory?

**Comment by alex-voodoo** [comment] 2021-09-26 13:44
> Maybe updater crashes while extracting the files? thinking
> Can someone look in coredumpctl and check that theory?

I will try to do that on the next upgrade.
Is there anything I should do or check now to be better prepared?

**Comment by ilya-fedin** [comment] 2021-09-26 15:56
> I will try to do that on the next upgrade.

coredumpctl seem to store dumps from Jule on my machine, so you should be able to check that theory right now

**Comment by alex-voodoo** [comment] 2021-09-26 16:50
You are correct, coredumpctl keeps a long history of dumps.  Unfortunately, I do not see anything about the Updater there.  Yesterday I upgraded Telegram to version 3.1.1 and faced this issue again, but the only dump I see from yesterday is for python3.9.

**Comment by ilya-fedin** [comment] 2021-09-26 16:51
I have no idea then :(

**Comment by Aokromes** [comment] 2021-09-26 18:26
maybe download 3.1, click update, attach gdb to updater and check?

**Comment by john-preston** [comment] 2021-09-26 19:49
@alex-voodoo Can you please try the following:

- download the [3.1.0 release](https://github.com/telegramdesktop/tdesktop/releases/download/v3.1.0/tsetup.3.1.0.tar.xz) from the github releases page
- unpack it to some clean folder
- create "TelegramForcePortable" folder in that clean folder, near the unpacked "Telegram" binary
- launch this binary from Terminal with "./Telegram -debug" command line
- autoupdate it in Settings (no need even to authorize, just press "Start Messaging" and go to Settings)
- try to apply the downloaded update by clicking the "Update Telegram" button in Settings
- if the issue is reproduced can you share the "XXXXXXXX_YYYYYY_upd.txt" log file from "TelegramForcePortable/DebugLogs/" from that clean folder

?

**Comment by a5r0n** [comment] 2021-09-26 22:45
@john-preston 
Just trying to do that, 
1. update works fine..
2. BUT! there no files like `DebugLogs` or so
3. and worst then, it just logged me out from my account!

**Comment by alex-voodoo** [comment] 2021-09-27 01:52
@john-preston, I did what you suggested, and Telegram upgraded successfully.  Tried that two times, both times it went fine.
The only log file I can see is `TelegramForcePortable/log.txt`, nothing interesting in it.

**Comment by john-preston** [comment] 2021-09-27 03:28
@alex-voodoo Are you sure you've ran it with -debug argument?

**Comment by alex-voodoo** [comment] 2021-09-27 03:29
@john-preston, yes.

**Comment by john-preston** [comment] 2021-09-27 03:29
@a5r0n My steps are putting all the data in the created TelegramForcePortable folder, so you were not logged out from anywhere, it was an independent app instance that could be authorized or not. Your regular app authorization was not touched by that run.

**Comment by ilya-fedin** [comment] 2021-09-27 03:33
>  yes.

maybe you entered `--debug` instead of `-debug`?

**Comment by alex-voodoo** [comment] 2021-09-27 03:48
@ilya-fedin, I actually tried both versions.  The outcome was the same.

**Comment by ilya-fedin** [comment] 2021-09-27 03:50
Does log.txt have `debug mode: [TRUE]`?

**Comment by alex-voodoo** [comment] 2021-09-27 04:01
@ilya-fedin, with `-debug` it does, yes.  I have just re-tried this once again, with the same result: it updated seamlessly.  The debug mode stays on even after the application upgrades and restarts.

**Comment by ilya-fedin** [comment] 2021-09-27 04:02
> with `-debug` it does, yes.

it must have DebugLogs folder, then

**Comment by alex-voodoo** [comment] 2021-09-27 04:05
Right, it has that folder.  However, as the "portable" instance upgrades normally with no issues, I guess nothing interesting is there?
Probably I should run my regular Telegram with `-debug` next time it suggests updating, and see what happens, or maybe downgrade it now and try updating with `-debug` but on my actual user profile.

**Comment by ilya-fedin** [comment] 2021-09-27 04:13
you can enter `debugmode` cheat code in setting to enable debug logs permanently

**Comment by alex-voodoo** [comment] 2021-09-27 04:35
Wow!  Thank you.  I will report what happens on the next upgrade.

**Comment by a5r0n** [comment] 2021-10-09 16:57
it's seems the updater works fine in the latest kernel  5.14.9
i have this issues before in previous kernels, 5.13.16 and 5.13.19 .

**Comment by alex-voodoo** [comment] 2021-11-04 03:40
I have just got this issue again on kernel 5.14-14.

The symptoms are exactly the same as I explained in [above](https://github.com/telegramdesktop/tdesktop/issues/16884#issuecomment-939306931).  The file is 112,184,376 bytes long, the updater copied 97,517,568 bytes.

I did not try to debug this time, sorry.  Maybe next time.

**Comment by ilya-fedin** [comment] 2021-11-04 03:42
According to the previous findings, the issue is somewhere in glibc or kernel, so I can't help with further debugging anyway

**Comment by alex-voodoo** [comment] 2021-11-04 03:59
Are there other ways to copy the file?  Maybe it would be possible to add some error handling in the updater?

A bug in glibc or in kernel is possible, but apparently it cannot be common, otherwise I'd imagine the system would be really unstable.  However, this issue happens at my workstation that I use every day, in a very intense manner, and it happens only when I update Telegram.  I do not experience any problems in other applications.

**Comment by ilya-fedin** [comment] 2021-11-04 04:09
> Are there other ways to copy the file?

Sure

> Maybe it would be possible to add some error handling in the updater?

It already has one. The problem is that the binary is killed while it's in the syscall. It doesn't go further, it doesn't even get the result of the syscall.

>  I do not experience any problems in other applications.

Whenever I hear that it usually means that people don't use the applications that use the same APIs even though a lot of such applications do exist. E.g. it's a frequent thing that people create issues related to toolkit behavior and they say "no other application on my computer behave in this way". At that point, it's clear that the user has no other Qt application on the computer while a lot of Qt applications do exist in the world.

**Comment by alex-voodoo** [comment] 2021-11-04 04:33
> > I do not experience any problems in other applications.
> 
> Whenever I hear that, it usually means that people don't use the applications that use the same APIs even though a lot of such applications do exist. E.g. it's a frequent thing that people create issues related to the toolkit behavior and they say "no other application on my computer behave this way". At that point, it's clear that the user has no other Qt application on the computer even though a lot of Qt applications do exist in the world.

I see the point, but you said [above](https://github.com/telegramdesktop/tdesktop/issues/16884#issuecomment-939309737) that the issue happens in the system call, which seems to be quite low-level.  A flawed system call should affect at least some things in the system, should not it?  Copying files is a function that is basic and is of high demand, and if it fails, many things will break imminently.  So either this particular calls fails only in the Telegram updater (or some other applications that I do not use), or, which seems more likely to me, there is some alternative API that works better, and probably it would be worth using it instead.

Anyway, we can only make guesses at this time.  Next time I will try to debug.

**Comment by ilya-fedin** [comment] 2021-11-04 04:39
>  A flawed system call should affect at least some things in the system, should not it?

That depends on whether you're using software that uses such a call or not. Since it's not always reproducible, that also depends on how much you use such software. tdesktop may be the only application on your computer that both uses such a call and used so much.

>  Copying files is a function that is basic and is of high demand, and if it fails, many things will break imminently.

There's multiple APIs to copy a file.

>  which seems more likely to me, there is some alternative API that works better, and probably it would be worth using it instead

I don't think updater should stop using kernel-accelerated API just because it fails on Fedora. Without an answer from kernel maintainers that it's not solvable, at least.

**Comment by alex-voodoo** [comment] 2021-11-04 04:50
@a5r0n, earlier you wrote that you had this issue as well.  Do you still experience it?

Could you please share some details of your setup?  Maybe this is somehow connected to the CPU?  The machine where I see the issue has AMD Ryzen Threadripper 2990WX.  The other computer where I never had the issue has Intel Core i7-8750H.

**Comment by a5r0n** [comment] 2021-11-04 22:25
@alex-voodoo 
in the previous update (maybe 3.1.12) i had the same problem. 
i saw when i try to run the executable from terminal, some lines about AppImageLauncher printed out, so i removed it just in case, 
but in the latest update, (3.2.1) the issue still exists.
my cpu is Intel i7-1165G7.
[20211105_000735_upd.txt](https://github.com/telegramdesktop/tdesktop/files/7479234/20211105_000735_upd.txt)

**Comment by ilya-fedin** [comment] 2021-11-04 23:54
> For the record, I asked [a question about this](https://ask.fedoraproject.org/t/issues-with-sendfile/17767) in Ask Fedora.

I have a feel no one there will help you, try here: https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&product=Fedora&product=Fedora%20EPEL&component=kernel

**Comment by Marzal** [comment] 2021-11-30 16:43
Just for the record 
Arch Linux with Plasma
kernel 5.14.21 (but happens also with others)
Intel(R) Core(TM) i5-8400

Same problem since a few months, I've been manually downloading the bins since then.

**Comment by gbcox** [comment] 2021-12-01 20:21
I'm having the exact same issue.  It has been occuring for many months now, but I thought it would be fixed eventually - that hasn't been the case.  When I use the update function within the app, a new version is automatically downloaded, but that version is corrupted.  I have to delete the current Telegram directory, go download a new tsetup archive, extract it and then manually run Telegram.  My kernel is 5.15.4

**Closed** 2021-12-02 05:15 UTC

**Comment by gbcox** [comment] 2022-01-15 02:48
With the latest update (Jan 14 2022) appears that #17324 has regressed.  Problem was fixed but is now reoccurring with todays update.
