### ISSUE TITLE
Add super group blocklist

### ISSUE THREAD

**Issue by madnessmike** [telegramdesktop/tdesktop#1618] opened 2016-02-16 17:16 UTC
When I upgrade a group into a supergroup, the list that contains all blacklisted members is not available.

Can you add this feature?

**Comment by Kondra007** [comment] 2016-04-01 12:47
Definetely needed feature! Android & iOS apps have this for a long time.

**Comment by tdesktop-closer** [comment] 2017-03-28 19:07
Hey there!

We're automatically closing this issue since there was no activity in this issue since 361 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

<sub>(Please note that this is an [automated](https://github.com/auchri/github_auto_closer) comment.)</sub>

**Comment by MasterGroosha** [comment] 2017-03-28 19:09
This issue need to be open

**Comment by auchri** [comment] 2017-03-28 19:11
It's a duplicate of #3134

**Comment by MasterGroosha** [comment] 2017-03-28 19:12
#1618 was opened obviously **before** #3134, because...numbers :)

But anyway

**Comment by Mistero5050** [comment] 2017-03-28 19:51
Please add the "Next version" milestone as you did in my duplicate
https://github.com/telegramdesktop/tdesktop/issues/3134

**Comment by john-preston** [comment] 2017-03-28 20:04
@Mistero5050 It is not in the next version yet.

**Comment by Mistero5050** [comment] 2017-03-28 20:21
Ok, I simply thought that it was because my duplicate was marked so

**Comment by Mistero5050** [comment] 2017-04-15 06:44
You should close this. It has been done

**Closed** 2017-04-15 06:58 UTC
Labels: enhancement
