### ISSUE TITLE
Backspace key doesn't work if caps lock is active

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#3238] opened 2017-04-08 11:27 UTC
### Steps to reproduce
1. enter a chat
2. hit caps lock
3. start typing
4. hit backspace

### Expected behaviour
Tell us what should happen

It should delete the previous character, it doesn't

### Actual behaviour
Tell us what happens instead

nothing

### Configuration
**Operating system:**
Ubuntu 16.04
**Version of Telegram Desktop:**
1.0.29
**Used theme**:
default
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

----
I don't know if this is related but I use caps lock as my keyboard layout switch key, so in order to activate caps lock I have to press Shift+CapsLock

**Comment by budkin** [comment] 2017-04-08 11:44
it happens regardless of the current language

**Comment by stek29** [comment] 2017-04-08 16:59
I remember having this issue on Arch.
Also had xkbmap option to switch layout with Caps Lock, and when it was activated a lot of keys haven't worked, including Backspace.

**Comment by noavarice** [comment] 2017-12-17 19:40
Reproduced on Fedora 26 64-bit, Telegram Desktop 1.2.1

**Comment by perk11** [comment] 2018-06-05 09:38
This is a duplicate of #2199

**Closed** 2018-06-06 10:00 UTC
Labels: bug, linux
