### ISSUE TITLE
Application always on top

### ISSUE THREAD

**Issue by viruslab1** [telegramdesktop/tdesktop#4056] opened 2017-11-10 13:10 UTC
### Steps to reproduce
1. Install application on windows 10 pro
2. set autorun check box in settings
3. reboot pc

### Actual behaviour
application will be on top of other application

### Configuration
win10 1709 build 16299.19

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
Default

**Comment by auchri** [comment] 2017-11-10 13:59
Duplicate of #3253 and I'm still unable to reproduce this.

**Closed by auchri** 2017-11-10 13:59 UTC

**Comment by wwevo** [comment] 2017-11-11 21:01
Pretty much this. If I start Telegram manually, everything is as it should, in autostart, it gets the always on top plague. I have disabled autostart and just run it manually for the time being.

**Comment by edi** [comment] 2019-11-17 17:16
This issue made a comeback lol. I'm experiencing this for two weeks now. If it's on autostart, I have to quit the app, then re-open it, otherwise it's always on top when not minimized.

**Comment by sansankudo** [comment] 2020-12-16 13:13
> This issue made a comeback lol. I'm experiencing this for two weeks now. If it's on autostart, I have to quit the app, then re-open it, otherwise it's always on top when not minimized.

apparently it made another comeback - v2.4.7
you're workaround still works haha thank you!
