### ISSUE TITLE
[Feature Request] Delete for other user as default

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6186] opened 2019-06-27 09:44 UTC
![](https://user-images.githubusercontent.com/7231077/39856778-c6b5e606-544e-11e8-8ed7-081852ee79e0.png)

Settings to tick `Also delete for ..` as default .

**Comment by RememberTheAir** [comment] 2019-06-27 10:51
Duplicate of #3334, also you should use the issue template. You've never used it once

**Comment by SmartManoj** [comment] 2019-06-27 11:00
https://github.com/telegramdesktop/tdesktop/pull/6159#issuecomment-504382057 
I thought its only for bugs

**Closed** 2019-06-27 15:18 UTC
Labels: duplicate
