### ISSUE TITLE
Telegram does not recognize links to localhost

### ISSUE THREAD

**Issue by KES777** [telegramdesktop/tdesktop#10440] opened 2021-02-26 12:26 UTC
### Steps to reproduce
1.  send MarkdownV2 text:
```
[wwuuu](http://kes:8081/issues/56)
```

### Expected behaviour
the message must be displayed as next:
![image](https://user-images.githubusercontent.com/799021/109299769-4c662480-783e-11eb-98b8-7a17628e19b5.png)

### Actual behaviour
But is displayed as simple text:
![image](https://user-images.githubusercontent.com/799021/109299814-5c7e0400-783e-11eb-8012-da616fa152ca.png)

### Configuration
**Operating system:**
Linux mint 19.3

**Version of Telegram Desktop:**
2.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
.tar.gz

**Used theme**:
default

**Comment by Aokromes** [comment] 2021-02-26 13:08
duplicate of https://github.com/telegramdesktop/tdesktop/issues/7827

**Closed by Aokromes** 2021-02-26 13:08 UTC
