### ISSUE TITLE
In Fedora Linux on Wayland impossible to display gtk themes and consequently related window management buttons

### ISSUE THREAD

**Issue by xzj8b3** [telegramdesktop/tdesktop#6775] opened 2019-11-10 15:11 UTC
telegram-desktop-1.8.15-1.fc31.src.rpm

In Fedora 31 Linux on Wayland impossible to display gtk themes and consequently related window management buttons, rather annoying problem and limiting usability .... Can you please fix?

**Comment by Newbytee** [comment] 2019-11-21 12:03
Duplicate of #6730?

**Closed** 2020-01-26 19:06 UTC
