### ISSUE TITLE
[Feature Request] Support editing shortcuts

### ISSUE THREAD

**Issue by lxiange** [telegramdesktop/tdesktop#7391] opened 2020-03-16 06:45 UTC
### Is your feature request related to a problem?
The input box doesn't support common shortcuts.
For HHKB users, it's inconvenient to move the cursor or backspace.

### Describe the solution you'd like
Support common shortcuts, for example:

`CTRL+A / CTRL+E`: Go to the start/end of the command line
`CTRL+F / CTRL+B`: Move forward/backward one character
`CTRL+D / CTRL+H`: Delete character after/before under cursor
...

These shortcuts are supported in almost all software by default. 
I don't know why it doesn't work in telegram :(

### Additional context
Same as #729 , it's still not working now.

**Comment by Aokromes** [comment] 2020-03-16 10:28
it's duplicate of another issue i cannot find, but
https://github.com/telegramdesktop/tdesktop/issues/1060#issuecomment-578392744

**Closed by Aokromes** 2020-03-16 10:28 UTC
