### ISSUE TITLE
Feature Request /me actions like irc or skype

### ISSUE THREAD

**Issue by ZornTaov** [telegramdesktop/tdesktop#2080] opened 2016-05-25 05:43 UTC
For many chat programs, the ability to use the command /me causes the client to display the post differently, to act like what was posted is an action.  Most chat clients display the post "/me waves" as "Username waves" to everyone that can see the message.  Unfortunately Telegram currently lacks this functionality.  As such I've seen a few people who transition from other chat clients to telegram still try to use /me for actions and it not displaying properly.

### Steps to reproduce
1. make a post like "/me waves to you"

### Expected behaviour
should result in "Username waves to you"

### Actual behaviour
results in "/me waves to you"

### Configuration
**Operating system:**
Windows 10 and Android
**Version of Telegram Desktop:**
0.9.26

**Comment by stek29** [comment] 2016-05-25 11:24
Have you heard about bots?

**Comment by ZornTaov** [comment] 2016-05-25 11:56
A bit vague of a reply, but yes I have. Is there a bot that does this?

**Comment by stek29** [comment] 2016-05-27 13:14
Well, you can write it if it's not.

**Comment by auchri** [comment] 2016-05-27 15:45
Duplicate of #1165

**Closed by auchri** 2016-05-27 15:45 UTC
