### ISSUE TITLE
function  to bookmark the message

### ISSUE THREAD

**Issue by lemniscat** [telegramdesktop/tdesktop#2346] opened 2016-08-11 05:47 UTC
Hello! Make a function to mark the message after which the others do not read. There are group chats, where every day is added for 1000-2000 messages. If I do not have time to read to the end of all of the remaining posts, I have to look for a message in which I stopped.
Now I'm doing "reply" in the current-to-read message, and leave without sending in the chat.
So it is marked in my text entry box. This approach is not convenient if I need someone to answer immediately to this chat. Please add a function or implement a different the opportunity to return to the unread messages, even after the answer in this chat

**Version of Telegram Desktop:0.10.1**

**Comment by auchri** [comment] 2016-08-11 17:58
Duplicate of #1312

**Closed by auchri** 2016-08-11 17:58 UTC
