### ISSUE TITLE
manual switch off autoscroll and bookmark messages

### ISSUE THREAD

**Issue by zaz600** [telegramdesktop/tdesktop#711] opened 2015-05-12 06:25 UTC
when you read 5000 messages in a chat, for example, in the morning, there is a wish to answer immediately some messages without switching on the latest message after sending the answer, and then you want to continue reading further, and then again to respond to any message without interrupting reading process.

It is necessary to make opportunity to switch off autoscroll before reading a large number of messages. Or it shouldn't work if we read not the last lower message.
It is also useful to have possibility of a bookmark on any message in the history  to go back to reading later.

**Comment by auchri** [comment] 2016-08-11 17:58
Duplicate of other issues.

**Closed by auchri** 2016-08-11 17:58 UTC
