### ISSUE TITLE
[Feature Request] Message reaction like we have in Skype and Facebook Messenger

### ISSUE THREAD

**Issue by nayeemahmed84** [telegramdesktop/tdesktop#7638] opened 2020-04-14 06:24 UTC
![image](https://user-images.githubusercontent.com/24442191/79192587-d1c13000-7e4a-11ea-96fb-e0c736765635.png)

Can we have something like this?

**Comment by RememberTheAir** [comment] 2020-04-14 06:33
Duplicate of #6277

**Closed** 2020-04-14 06:34 UTC
