### ISSUE TITLE
Message width computed wrong way

### ISSUE THREAD

**Issue by LexaGV** [telegramdesktop/tdesktop#25010] opened 2022-08-31 17:10 UTC
### Steps to reproduce

When I receive message with video, full message width is adjusted to be the same as video! As a result, long text become narrow, high rectangle.

### Expected behaviour

Message width must be as wide as possible! (as it counted without video)

### Actual behaviour

Message text is shown with the same width as video.

### Operating system

Windows 7 x64

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2022-09-01 04:21
I believe this is intended from design perspective

**Comment by LexaGV** [comment] 2022-09-01 09:01
@ilya-fedin Emm... sorry, what is correspondence between mentioned "design" and inconvenience during reading? Obviously message width MUST be comfortable and take as much as possible space (like message w/o video).

**Comment by ilya-fedin** [comment] 2022-09-01 09:04
I don't quite understand your question. What I said is this works as intended most likely. You may not like it, but this is not a bug.

**Comment by LexaGV** [comment] 2022-09-01 09:25
@ilya-fedin : sorry, if you don't understand the problem, use service of more advanced developers. Problem is quite clear - message text takes same width as video, what leads to VERY NARROW COLUMN to read text. What you don't understand there??
I have wide LCD, but read text like it's written on toilet roll. This is image how message looks in narrow edges: https://i.ibb.co/hBpLChs/telega-Suxx.webp

I prefer to see message in full width (as you count width when message doesn't have video).

**Comment by LexaGV** [comment] 2022-09-01 09:27
@john-preston You don't catch a problem. Video doesn't correspond to problem at all. Problem is message underneath - it takes TOO NARROW SPACE. Look at pic I refer above.

**Comment by ilya-fedin** [comment] 2022-09-01 09:28
> What you don't understand there??

I don't understand this question:

> what is correspondence between mentioned "design" and inconvenience during reading?

**Comment by ilya-fedin** [comment] 2022-09-01 09:28
> This is image how message looks in narrow edges: https://i.ibb.co/hBpLChs/telega-Suxx.webp

That's not a bug

**Comment by ilya-fedin** [comment] 2022-09-01 09:29
> I prefer to see message in full width

Feel free to submit a feature request (don't forget to search for existing ones first).

**Comment by LexaGV** [comment] 2022-09-01 09:29
@ilya-fedin : then be more precise when you ask. This question is "half-answer" on idea that your "design" has no correspondence to idea that message reading should be EASY. If you know this term, there is "usability" word - in this case usability is BAD.

**Comment by ilya-fedin** [comment] 2022-09-01 09:31
Maybe. But this still works as intended and therefore not a bug.

**Comment by LexaGV** [comment] 2022-09-01 09:31
I have no time and knowledge to dig in code. I request to fix bug (in usability) when message width CALCULATED WRONG WAY. It's literally one line of code. For people who develop messenger it's 1 minute job.

**Comment by LexaGV** [comment] 2022-09-01 09:32
Repetition "it's not a bug" just confirms that usability is not your skill, please invite more professional developers. IT IS A BUG. Bug in usability.

**Comment by ilya-fedin** [comment] 2022-09-01 09:33
As @john-preston said, it's more complex: wider bubbles mean wider black border what is no-go from design perspective. Someone has to implement blur background instead of black borders first. So this is a new feature rather than a bug fix.

**Comment by LexaGV** [comment] 2022-09-01 09:36
Sorry, what "black borders" are you talking about?? Nobody asks to touch video - it takes own width and it's OK. But TEXT BELOW THE VIDEO - there you have a problem, it is shown in too narrow space equal to video width. Video width must NOT be used when text width is computed. Quite simple!

**Comment by ilya-fedin** [comment] 2022-09-01 09:38
If you want more space for text, you need to make the bubble wider. When you make the bubble wider, you need to fill the space between video size and the bubble size.

**Comment by john-preston** [comment] 2022-09-01 09:42
@LexaGV The video is the upper part of the message bubble, the text is the lower part. So the media on top and the text at the bottom take the same width. To increase it the same approach as mobile apps use should be used. It could be done, but it's not a quick task.

**Comment by LexaGV** [comment] 2022-09-01 09:43
So what? Is it so hard problem for developer???? Look how it should be: https://i.ibb.co/52f89Kv/Telega-proper-view.webp

**Comment by ilya-fedin** [comment] 2022-09-01 09:43
> Look how it should be

LOL. No, it's definitely not how it should be.

**Comment by LexaGV** [comment] 2022-09-01 09:44
@ilya-fedin I don't need your incompetent LOL - I need comfortable reading zone + video.

**Comment by ilya-fedin** [comment] 2022-09-01 09:45
I propose to show your competence everyone and implement that on your own. The community will thank you.

**Comment by john-preston** [comment] 2022-09-01 09:49
@LexaGV Well, such implementation won't be accepted, sorry. The one with narrow video and wide bubble parts above and below (or only below) the video.

**Comment by john-preston** [comment] 2022-09-03 04:45
I'd say this may be considered a feature request to support the same solution that iOS app provides.

**Comment by ilya-fedin** [comment] 2022-09-03 04:57
Isn't this a duplicate of https://github.com/telegramdesktop/tdesktop/issues/16838 then?

**Comment by john-preston** [comment] 2022-09-03 05:02
@ilya-fedin Hmm, I've looked now, and iOS app only applies blurred-parts workaround to photos, while for videos it just cust top and bottom parts in-chat when caption is present. Interesting, maybe this could be done on TDesktop too.

**Closed** 2022-10-11 04:31 UTC
Labels: enhancement

**Comment by LexaGV** [comment] 2022-10-11 07:30
Issue is NOT resolved, why you close it??
Main issue is not how you move video across text, but MAKE TEXT WIDER. It's totally annoying when narrow video followed a huge column with narrow text. Text MUST be as wide as possible. Is it so hard to guess?

**Comment by john-preston** [comment] 2022-10-14 04:18
@LexaGV because in the latest versions text under the video takes as much width as a regular text message, without a video. So the issue is fixed.
