### ISSUE TITLE
Photo Caption doesn't allow to create an accented character (de-CH keyboard)

### ISSUE THREAD

**Issue by denysvitali** [telegramdesktop/tdesktop#2076] opened 2016-05-24 20:45 UTC
When using a Swiss German keyboard there are two ways of making accents:
the first one is to use the yellow keys, and the second one is by pressing SHIFT + [Red Key] and then pressing a vowel.

![keyboard](https://cloud.githubusercontent.com/assets/4939519/15519200/a1248212-2200-11e6-9813-3adf20cdac2a.png)
Image edited: [source](https://www.goodtyping.com/teclatSWIok.png)

When an accented character is inserted via the first method (yellow keys) everything is fine, unfortunately when the accented letter is inserted via the red key only the selected vowel is printed, unaccented

For example
Expected result: è
Actual result: e

### Steps to reproduce
1. Send an image
2. Add in the description (caption) an accented character using the de-CH keyboard with the "red key" method

### Expected behaviour
The accented character should be added to the caption

### Actual behaviour
The character is added to the caption without the accent

### Configuration
Arch Linux,  Linux 4.5.4-1
Telegram Desktop 0.9.49

**Comment by auchri** [comment] 2016-05-24 20:54
Duplicate of #1418

**Comment by auchri** [comment] 2016-05-24 20:55
@denysvitali Do you use the binary from https://desktop.telegram.org/ ?

**Closed by auchri** 2016-05-24 20:54 UTC

**Comment by denysvitali** [comment] 2016-05-24 21:23
Yes I do
md5sum e02eac36793219e8c18b27f9b3c558a2
