### ISSUE TITLE
log out telegram with a "key"?

### ISSUE THREAD

**Issue by Axe-Usa** [telegramdesktop/tdesktop#4251] opened 2017-12-28 16:01 UTC
It's possible to log out from telegram just pressing a "key"?

**Comment by john-preston** [comment] 2017-12-28 17:19
@Axe-Usa Ctrl+Q (Cmd+Q on macOS)

**Comment by Axe-Usa** [comment] 2017-12-28 17:42
this is for clossing telegram but the process is still running.
Is not possible to log out just pressing a key?
the only way is killing the process by name at the moment i think.
The case is just because i was trying to logout without do it manually. just for that purpose.

**Comment by stek29** [comment] 2017-12-28 18:17
Can you please provide more info (or &#$% use the template)? Cmd+Q works for me on macOS.

**Comment by ferferga** [comment] 2017-12-28 18:51
After closing, (sometimes) the app will be still running a while, terminating all the tasks and encrypting/saving the info. It will close eventually.

**Comment by john-preston** [comment] 2017-12-28 19:05
@Axe-Usa There is no hotkey for log out, I thought you need a hotkey to quit Telegram. Ctrl+Q / Cmd+Q should quit it completely, if the process is still running for a long time after that this is some sort of bug :( But I can't reproduce that.

**Comment by stek29** [comment] 2017-12-28 19:25
@Axe-Usa Do you want to Log Out or to terminate the app?

**Comment by Axe-Usa** [comment] 2017-12-28 21:58
i want to logout without doing manually
i was trying to use differente instance to avoid it.
Telegram.exe -many -workdir "C:\Users\User\Desktop\%RANDOM%\data"
but still open me the same session for this i was just log out or restart the session each time i open telegram,

**Comment by stek29** [comment] 2017-12-29 06:54
What's the reason you want to do it? Servers won't like often login/logout. Won't password lock do?

**Comment by Axe-Usa** [comment] 2017-12-29 13:52
the purpose is because i just want to log out from my account without doing it manually. then like i didn't find any solution i thought that the only way was opening a new instance but still open the same. For example if you have two telegram one for entertainment and other for job inquiries like example it's very annoying to log out manually to use the other. if i have more than one account i can log in in my account without doing it manually.

**Comment by Aokromes** [comment] 2017-12-29 21:08
#2109 ?

**Comment by stek29** [comment] 2017-12-31 10:16
@Aokromes not that, but #1060.

**Closed by stek29** 2017-12-31 10:16 UTC
Labels: enhancement

**Comment by stek29** [comment] 2017-12-31 10:18
@Axe-Usa I'd suggest swapping workdirs
