### ISSUE TITLE
System window frame does not apply to call windows.

### ISSUE THREAD

**Issue by Nikita-Presnov** [telegramdesktop/tdesktop#24083] opened 2022-02-16 06:50 UTC
### Steps to reproduce

Start tg
Go to settings -> advanced settings -> enable system window frame.
Make a call/video call.
Watch the custom frame in the call window, which can lead to the bugs already described here. 

### Expected behaviour

I want to see system frame everywhere or hotel setting for calls. 

### Actual behaviour

The frame in the calls remains custom. 

### Operating system

KDE neon

### Version of Telegram Desktop

3.5.2

### Installation source

Static binary from official website

**Comment by 23rd** [comment] 2022-02-16 08:07
I guess this is a duplicate of #10002.

**Comment by Nikita-Presnov** [comment] 2022-02-16 08:25
Yes...

**Closed** 2022-02-16 08:49 UTC
Labels: duplicate
