### ISSUE TITLE
Consistent Disk crash bug in Linux 64

### ISSUE THREAD

**Issue by scotty264** [telegramdesktop/tdesktop#17415] opened 2021-12-17 21:37 UTC
I have been running the Linux DESKTOP version for about 3 months now. I have had at least 7 auto-updates and none of the updates have remedied the crash I keep seeing. 

The crash happens after "saving" a video. It isn't always right away. It may happen randomly a few minutes later or it may crash when trying to save another video. Sometimes, the "save as" dialog is not invoked and TELEGRAM hangs. Using "htop", it can be seen that TELEGRAM is waiting for disk access. All TELEGRAM processes show "D" (waiting for disk access) as their status.  In those cases, I must select all TELEGRAM processes and KILL (SIGINT 9) then restart TELEGRAM.

My system specifics:
Kernel: Linux toshl755d 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 GNU/Linux
LSB_Release:Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia, Release:	18.3, Codename:	sylvia
Current TELEGRAM desktop release: V3.3

**Comment by ilya-fedin** [comment] 2021-12-18 02:19
So, it this a crash or a hang?

**Comment by scotty264** [comment] 2021-12-18 08:15
Sorry, I should have been a bit more clear; Sometimes its a crash and on occasion, its a hang and I have to kill all the TELEGRAM processes. The pattern seems to be; run TELEGRAM, save a video, save another and it crashes (terminates). And sometimes; run TELEGRAM, save a video, the "save file" dialog doesn't open and it just hangs until I kill all TELEGRAM processes.

**Comment by ilya-fedin** [comment] 2021-12-18 11:49
If you have installed Telegram from official static binary, you should have crash reporter after the crash, please copy the crash report tag, paste it here and send the crash report. If you're using not the static binary, please switch to it.

**Comment by scotty264** [comment] 2021-12-18 12:10
Sorry, that's a little cryptic. I did not compile this code from the repository, so as far as I know, I installed the Linux 64 binary of v3.1. There have been about 7 auto-updates since then. How do I tell if the TELEGRAM I am using is a static build?

**Comment by ilya-fedin** [comment] 2021-12-18 12:14
With the path to the binary in htop, apparently. Official binary should be placed somewhere in your $HOME and the binary should have name 'Telegram'. If its installed from distro repositores, it should be something like /usr/bin/telegram-desktop, if it's installed from snap, something like /snap/telegram-desktop/current/usr/bin/telegram-desktop, if it's installed from flatpak then something like /app/bin/telegram-desktop

**Comment by scotty264** [comment] 2021-12-18 12:22
Does this tell you what you need to know?

/opt/Telegram/Telegram: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9e711f726daa44ae0bbe408b26baff96979361f5, for GNU/Linux 2.6.32, stripped

I says "dynamically linked", not static? I'll install the v3.3 from GITHUB and get back to you after my sleep cycle.

Thank you.

**Comment by ilya-fedin** [comment] 2021-12-18 12:26
> I says "dynamically linked", not static?

Well, the static binary is not fully static, some libraries like libc, libxcb, libX11 are stil linked dynamically

> Does this tell you what you need to know?

Does it have in-app autoupdate?

**Comment by scotty264** [comment] 2021-12-18 12:30
I figured it had to be static build because it came directly from GITHUB and not via the distro.

As I stated, Telegram has been auto-updating at least 7 times now.

**Comment by ilya-fedin** [comment] 2021-12-18 12:57
> you should have crash reporter after the crash, please copy the crash report tag, paste it here and send the crash report

**Comment by scotty264** [comment] 2021-12-18 21:04
Where do I find the crash report? TELEGRAM is not run from the command line, so no text debugging info. Is there a log file? If so where might it be located?

**Comment by scotty264** [comment] 2021-12-18 21:24
I ran TELEGRAM from Linux command line shell. I was able to save videos a few times (usually crashes on 2nd download). Eventually, TELEGRAM crashed. Below is the session info from TELEGRAM:

me@toshl755d /media/truecrypt1/Projects/Active $ /opt/Telegram/Telegram & 
[1] 8588
me@toshl755d /media/truecrypt1/Projects/Active $ 

QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: Windows, Fusion
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[swscaler @ 0x7f3a91e32cc0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7f3a91e32e40] deprecated pixel format used, make sure you did set range correctly
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a41b20400] Packet corrupt (stream = 0, dts = 7869060).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a64dafa00] Packet corrupt (stream = 0, dts = 11534040).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a7d032800] Packet corrupt (stream = 0, dts = 13621950).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a655d1a00] Packet corrupt (stream = 1, dts = 7586921).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a7d032200] Packet corrupt (stream = 0, dts = 16698870).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a7d031000] Packet corrupt (stream = 0, dts = 20343060).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a7d032200] Packet corrupt (stream = 1, dts = 11612273).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a7d031000] Packet corrupt (stream = 0, dts = 25611840).
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a7d031600] Packet corrupt (stream = 0, dts = 27230490).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a7d033400] Packet corrupt (stream = 0, dts = 29989620).
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f3a7d031600] Packet corrupt (stream = 0, dts = 32291370).
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length

[1]+  Aborted                 (core dumped) /opt/Telegram/Telegram

**Comment by ilya-fedin** [comment] 2021-12-19 01:57
> Where do I find the crash report?

You shouldn't find it, you should get a crash report window where you should send the crash report, copy the crash report tag and paste here.

**Comment by scotty264** [comment] 2021-12-19 05:59
Nope! No crash report window. :(

**Comment by ilya-fedin** [comment] 2021-12-19 06:12
Do you have installation of beta versions enabled?

**Comment by ilya-fedin** [comment] 2021-12-19 06:12
It should be enabled for crash reporter to appear

**Comment by scotty264** [comment] 2021-12-19 06:16
I'm just running the Linux static installer from the GITHUB, so whatever is the default is what's being installed. What should and shouldn't be I can't say.

**Comment by scotty264** [comment] 2021-12-19 06:18
No command line options for /opt/Telegram/Telegram available using "--help". Maybe the option wasn't enabled for the static Linux build?

**Comment by ilya-fedin** [comment] 2021-12-19 06:30
> I'm just running the Linux static installer from the GITHUB, so whatever is the default is what's being installed. What should and shouldn't be I can't say.

I mean, you should enable installation of beta versions for crash reporter to appear

> No command line options for /opt/Telegram/Telegram available using "--help". Maybe the option wasn't enabled for the static Linux build?

tdesktop has no command line options for end users

**Comment by john-preston** [comment] 2021-12-19 06:43
@scotty264 Try enabling Settings -> Advanced -> Install beta versions

Also you can check ~/.local/share/TelegramDesktop/tdata/dumps for the crash dumps files. You can send several latest by date with non zero size to me at t.me/preston, assuming there are any.

**Comment by scotty264** [comment] 2021-12-19 07:31
Ilya-fedin: telling me "I mean, you should enable installation of beta versions for crash reporter to appear" is great but means nothing if you don't tell me how to do it.

"tdesktop has no command line options for end users, so no help" I was speaking about the Telegram executable itself, not the installer. BTW: I just installed the v3.3 from the static build. Its only the Telegram and Updater executables.

john-preston: Thank you for telling me where to do that. I did enable beta versions but there are no updates for beta at this time.

So now what? How do I get the crash report if there are no beta versions to install??

**Comment by ilya-fedin** [comment] 2021-12-19 07:38
> "tdesktop has no command line options for end users, so no help" I was speaking about the Telegram executable itself, not the installer.

What do you mean by 'the installer'? Installer exists only for Windows, Linux has only portable executable. So I was speaking about the executable, too.

> How do I get the crash report if there are no beta versions to install??

Yes

**Comment by scotty264** [comment] 2021-12-19 08:21
I agree on the "installer". Its the executable.

Okay, now with "beta" option set, I just got Telegram to crash and there was no crash report. So I don't know how to give you what you need. Sigh...

**Comment by Aokromes** [comment] 2021-12-19 08:29
> I agree on the "installer". Its the executable.
> 
> Okay, now with "beta" option set, I just got Telegram to crash and there was no crash report. So I don't know how to give you what you need. Sigh...

try running it under gdb.

**Comment by ilya-fedin** [comment] 2021-12-19 08:41
This wouldn't be really helpful since he doesn't have debug symbols for the executable. According to

> terminate called after throwing an instance of 'std::bad_array_new_length'
> what(): std::bad_array_new_length

The cause is an exception in a container, but it's unknown where the exception happened without a crash report. Apparently, crash reporter is unable to catch exceptions and without that, it's nearly impossible to fix the issue...

**Comment by scotty264** [comment] 2021-12-19 09:14
Aokromes: THANK YOU! :) That was the solution to getting the crash report! I got the executable running under Linux GDB and as soon as it started, it gave me a window with the crash report. 

ilya-fedin: I think this is what you've been asking for but never gave me clear instructions on how to retrieve it for you.

![image](https://user-images.githubusercontent.com/5011423/146669517-50ff682d-2abc-4061-9a90-2e868b1f1bc5.png)

Also, folks, please don't assume that I am an accomplished programmer for the Linux platform because I don't do much Linux programming in anything beyond BASH.

**Comment by ilya-fedin** [comment] 2021-12-19 09:24
Crash reporter should work without gdb...

**Comment by ilya-fedin** [comment] 2021-12-19 09:24
Maybe you thought it should appear right after crash? It appears only on next launch.

**Comment by scotty264** [comment] 2021-12-19 09:30
"Maybe you thought it should appear right after crash?"  How would I know that? I'm not a developer on this project, so I know nothing of the internal code's behavior. I presume you folks do, yes?

" It appears only on next launch." Well, it NEVER has. It only appeared when ran it under GDB. 

I also have to confess; I can't read minds either! :)

**Comment by scotty264** [comment] 2021-12-20 07:53
Okay... so was the screen-capture of the crash report I posted what was needed?

https://github.com/telegramdesktop/tdesktop/issues/17415#issuecomment-997355268

**Comment by scotty264** [comment] 2021-12-20 10:29
Okay, so can you check with John to see that he got what was needed? I did send the crash report.

Peace and blessings.

**Comment by scotty264** [comment] 2021-12-20 10:36
Here's another one just in case. :)

![image](https://user-images.githubusercontent.com/5011423/146753897-2ef1b40c-bb2c-4ae6-b442-d2c984cc158b.png)

**Comment by scotty264** [comment] 2021-12-20 10:37
Ah, now I see the location of the dump file in the report.

Its attached as well.
[Uploading 88f8a6b3-acfb-45da-634bbc96-30d5ce97.dmp…]()

**Comment by scotty264** [comment] 2021-12-20 10:43
Now that I know where the crash dumps are at, to date there are 33.

I ZIP'd them all up and they are attached. 

[Telegram-crashdumps.zip](https://github.com/telegramdesktop/tdesktop/files/7744677/Telegram-crashdumps.zip)

**Comment by john-preston** [comment] 2021-12-22 11:00
This is either a bug in Qt or in the standard library implementation in the GCC version that is used :( The stack trace looks like this:

```
...
 5  libc.so.6 + 0x7a82b
 6  Telegram!__cxa_end_catch + 0x9
 7  Telegram!__gnu_cxx::__verbose_terminate_handler() [clone .cold] + 0x59
 8  Telegram!__cxxabiv1::__terminate(void (*)()) + 0x6
 9  Telegram!std::terminate() + 0x11
10  Telegram!__cxa_rethrow + 0x46
11  Telegram!std::_Hashtable<QString, QString, std::pmr::polymorphic_allocator<QString>, std::__detail::_Identity, std::equal_to<QString>, QDuplicateTracker<QString, 32ul>::QHasher<QString>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_rehash(unsigned long, unsigned long const&) [hashtable.h : 2077 + 0x5]
12  Telegram!QtPrivate::QStringList_removeDuplicates(QList<QString>*) + 0x7c5
13  Telegram!xdgDataDirs() + 0x178
14  Telegram!QStandardPaths::standardLocations(QStandardPaths::StandardLocation) + 0x80d
15  Telegram!QStandardPaths::locateAll(QStandardPaths::StandardLocation, QString const&, QFlags<QStandardPaths::LocateOption>) + 0x2d
16  Telegram!QMimeDatabasePrivate::loadProviders() + 0xea
17  Telegram!QMimeDatabasePrivate::resolveAlias(QString const&) [qmimedatabase.cpp : 174 + 0x8]
18  Telegram!QMimeDatabasePrivate::mimeTypeForName(QString const&) + 0x1f
19  Telegram!QMimeDatabase::mimeTypeForName(QString const&) const + 0x2b
20  Telegram!Core::MimeTypeForName(QString const&) + 0x246
21  Telegram!DocumentFileNameForSave(gsl::not_null<DocumentData const*>, bool, QString const&, QDir const&) + 0x19d
22  Telegram!DocumentSaveClickHandler::Save(Data::FileOrigin, gsl::not_null<DocumentData*>, DocumentSaveClickHandler::Mode) + 0x1ae
...
```

I can't reproduce that and right now I have no idea what to do with that. Perhaps on the next compiler version (or migrating to another compiler) it will fix itself

**Comment by ilya-fedin** [comment] 2021-12-22 11:02
See, xdgDataDirs calls removeDuplicates only when XDG_DATA_DIRS is set to a non-standard value
![изображение](https://user-images.githubusercontent.com/17829319/147082807-b4787135-fa9b-4c76-9260-8168daefcf0c.png)
The source of the crash is @scotty264's custom environment, so you can't reproduce that without his environment

**Comment by john-preston** [comment] 2021-12-22 11:05
@scotty264 Can you please share the value of your XDG_DATA_DIRS env variable?

**Comment by scotty264** [comment] 2021-12-22 20:07
XDG_DATA_DIRS=/usr/share/mate:/home/scotty264/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

**Comment by scotty264** [comment] 2022-06-23 00:50
It seems to have been fixed in the more recent Linux versions. I've saved a few videos and did not experience crash, so your software development team must not have reported the issue as corrected.








































---- On Wed, 22 Jun 2022 19:27:57 -0500 stale[bot] ***@***.***> wrote ---





Hey there!

This issue was inactive for a long time and will be automatically closed in 30 days if there isn't any further activity. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

**Comment by ilya-fedin** [comment] 2022-06-23 00:52
There were nothing done for this, if it's fixed, it fixed on it's own

**Comment by ilya-fedin** [comment] 2022-06-23 00:55
Please close the issue if it's fixed

**Comment by scotty264** [comment] 2022-06-23 01:05
Hmm. Not sure how it would get fixed on its own. Software doesn't do that unless a library that was used had been fixed/updated. I have not updated the libraries on my distro in about a year, so not likely fixed on my end. 



Admittedly, I have not spent time testing it but I did "save" (download) a few video files and it did not crash, whereas before, it would crash most every time I tried to "save" a video.



I think the ticket should stay open for now.



Peace and blessings.
 

































---- On Wed, 22 Jun 2022 19:52:41 -0500 ilya-fedin ***@***.***> wrote ---





There were nothing done for this, if it's fixed, it fixed on it's own

**Comment by ilya-fedin** [comment] 2022-06-23 01:08
> Software doesn't do that unless a library that was used had been fixed/updated.

It also may get fixed if the code was touched for some other purpose.

> I have not updated the libraries on my distro in about a year

Well, there's a thing called static linking

> I think the ticket should stay open for now.

How long?

**Comment by scotty264** [comment] 2022-06-23 01:28
Hi:

Static linking; yes, as you stated, another piece of code may have gotten updated and that fixed the problem.



How long; I'm closing on a home in the next two weeks and have lots of repairs to get lined up for it. How about leave the ticket open for another 30 days and then remind me with the "bot"? Is that acceptable?



Peace and blessings,

Scott




































---- On Wed, 22 Jun 2022 20:08:30 -0500 ilya-fedin ***@***.***> wrote ---





Software doesn't do that unless a library that was used had been fixed/updated.


It also may get fixed if the code was touched for some other purpose.

I have not updated the libraries on my distro in about a year


Well, there's a thing called static linking

I think the ticket should stay open for now.


How long?

**Comment by ilya-fedin** [comment] 2022-06-23 01:31
Well, adding an exception for one issue would be a problem as the configuration is in repository, so there only two options:
no-response bot - two weeks
stale bot - half of a year

**Comment by scotty264** [comment] 2022-06-23 01:36
Then use the stale bot, which is how I was informed less than a few hours ago?



Thanks.
































---- On Wed, 22 Jun 2022 20:31:12 -0500 ilya-fedin ***@***.***> wrote ---





Well, adding an exception for one issue would be a problem as the configuration is in repository, so there only two options:
 no-response bot - two weeks
 stale bot - half of a year

**Comment by ilya-fedin** [comment] 2022-08-09 04:00
@scotty264 could the ticket be closed?

**Comment by scotty264** [comment] 2022-08-09 14:26
Yes. Saving files doesn't seem to crash the app any longer. Thank you.
































---- On Mon, 08 Aug 2022 23:00:58 -0500 ilya-fedin ***@***.***> wrote ---





https://github.com/scotty264 could the ticket be closed?

**Closed** 2022-08-09 15:38 UTC
