### ISSUE TITLE
[Question] To separate contacts and channels

### ISSUE THREAD

**Issue by Git9243031** [telegramdesktop/tdesktop#6684] opened 2019-10-16 08:36 UTC
Is it possible to separate into different tabs channels / groups / contacts.
Currently I have a lot of groups and they are mixed with my contacts in the list. For this reason, it is not convinient to use tg

**Comment by RememberTheAir** [comment] 2019-10-16 08:37
Duplicate of #1107 and many other

**Closed** 2019-10-16 08:47 UTC
Labels: question
