### ISSUE TITLE
Raise Pinned Chat Limit or Offer option to set max pinned chats

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#4037] opened 2017-11-02 14:11 UTC
### Steps to reproduce
1. Try to Pin more than 5 Chats

### Expected behaviour
Able to pin more than 5 chats

### Actual behaviour
There is a hard limit of 5 max pinned chats 

### Configuration
**Operating system:**
Ubuntu 17.10

**Version of Telegram Desktop:**
11.1.23

In my particular case and for quick finding, I have:

1. My Wife
2. My Family
3. My Sons Group
4. Job Group 1
5. Job Group 2

And I need about 3 more pinned chats. Basically I am replacing the whole Slack platform for Telegram since it is easier to manage from Telegram, by using more pinned chats, it is easier for me to handle this chat channels efficiently, including my family chats. So raising the limit to 10 for example or offering the option would help.

**Comment by RememberTheAir** [comment] 2017-11-02 17:24
Pinned chats are synced across devices, that means the max number of pinned chats one can have depends on Telegram and raising it client-side would lead to inconsistencies across clients. This is a limit that is defined by the API, and thus is out of the scope of TDesktop's development

You can try to suggest that [on Twitter](https://twitter.com/telegram) or via the in-app support

(also duplicate of #3406)

**Closed** 2017-11-02 20:21 UTC
Labels: api issue

**Comment by luisalvarado** [comment] 2017-11-03 14:46
Thank you Air. Think positive.

**Comment by vsvasya** [comment] 2018-03-20 14:11
OMG. It will be totally fine to pin them on desktop without any sync.
It SO unconvenient to have only 5 chats on top.

Which options remains for the user? Start unsubscribing from channels and people? Scroll and search everytime? What's a punishment? For what?

**Comment by vsvasya** [comment] 2018-03-20 14:12
Even skype allows to pin more

**Comment by x011** [comment] 2018-04-04 09:14
Nonsense to have a pin chat limit of 5, specially if you're dealing with several projects.

**Comment by ryanwdavies** [comment] 2018-05-24 19:14
Option to pin any number, and define a static order of the list.

**Comment by prototype99** [comment] 2018-05-25 07:06
it could be an idea, to if the user tries to add a 6th (or whatever) pin, to add it to a local file rather than a synced one? that way the desktop user can get more pins without affecting their syncing or breaking api. although maybe have it display a message when they do a sixth pin telling them that it won't be synced and if they want it to be they should message the relevant page/user. in theory that could eventually produce a passive motivation to increase the number of synced pins, but even if it doesn't, desktop users now have that option.

**Comment by via4e** [comment] 2018-10-03 11:08
"Max 5 pinned chat limit" really uncomfortable. Only on my job used five chat, other chat i cant pin by limit. Please hear us

**Comment by devcline** [comment] 2018-10-11 08:41
2017
2018
2019?

**Comment by roceys** [comment] 2018-10-23 17:49
2020？ I need the Feature.

**Comment by jez9999** [comment] 2018-12-14 17:11
I concur with this, limiting pinning to 5 is a very frustrating arbitrary limitation.

**Comment by pradityabagus** [comment] 2019-02-06 04:34
is there any update on this? it is 2019 and I terribly need this feature.

**Comment by devcline** [comment] 2019-02-06 07:08
@durov

**Comment by avalsoff** [comment] 2019-02-07 12:07
@durov help

**Comment by Eugen-Ask** [comment] 2019-02-09 11:54
@durov verni stenu!

**Comment by T7o7heVV** [comment] 2019-02-13 09:41
Unbelievable that this feature still does not exist. On Android I switched to the "Plus" Messenger which uses the Telegram API but lets you define "favorites" (which are not synched but who cares). 

It's incomprehensible that the devs do not add this feature. It's like punishing the user for using Telegram too much with too many people/groups. No idea how how no one from the corporation seems to realize this...

**Comment by SirLouen** [comment] 2019-03-10 15:06
Yep, this is definitely a bad decission by the dev team. I'm not sure, what lead them to this limit. I have like 5 extra groups that I have to keep pulling them up manually because I can't pin them....

Worse enough this issue has been closed

**Comment by devcline** [comment] 2019-03-11 18:52
I have a temps solution that i use. **Have a second number and use TELEGRAM for Contacts and TELEGRAM X for Groups and Bots.**

**Comment by 2014Alexander** [comment] 2019-08-10 15:17
Trust people who use it (not to testers only) - We need the ability to structure chats and arrange as it convenient!

**Comment by Dimensionsofahimsa** [comment] 2019-09-27 19:32
Personally I solved this issue on my phone with PlusMessenger and on my desktop with Bettergram.

I love Telegram, but it's sad I need to use a different program to actually use it how I can be most productive. Bettergram is discontinued now so I'm getting kind of sad Telegram keeps this limit to 5

- More pinned chats
- Distinction between groups and individual chats would be golden too

2 things I would love to see in the original Telegram

**Comment by SirLouen** [comment] 2019-09-27 21:08
Same here, I don't like Bettergram for PC much, Plus Messenger is way better

**Comment by CoolCollin** [comment] 2019-10-09 05:48
they SUCK!

**Comment by egoarka** [comment] 2020-01-30 01:27
2020. It's still 5.

**Comment by RememberTheAir** [comment] 2020-01-30 08:19
@egoarka it's not going to change

**Comment by devcline** [comment] 2020-02-03 09:06
Telegram Beta for MacOS  now have this feature! Congrats folks a small step.
![image](https://user-images.githubusercontent.com/617020/73639537-e0ca7b80-466c-11ea-8f58-4f83c29f9684.png)

**Comment by SirLouen** [comment] 2020-02-07 08:21
With Bettergram discontinued for PC, any alternatives that make this possible for PC?
I cry everytime I see this:
https://i.imgur.com/UEXpfeA.png

**Comment by HenryFBP** [comment] 2020-02-14 04:57
Five! What!

Guys, the technology is advanced enough! In 2020, we can count to 6! SIX! THE TECHNOLOGY!

**Comment by devcline** [comment] 2020-03-27 22:34
![image](https://user-images.githubusercontent.com/617020/77805907-75f15b80-7083-11ea-8022-2a5e09e65273.png)
OMG!
