### ISSUE TITLE
Drafts malfunction on poor connections

### ISSUE THREAD

**Issue by EhsaanF** [telegramdesktop/tdesktop#3981] opened 2017-10-12 19:18 UTC
### Steps to reproduce
1. Connect to a poor Internet connection.
2. Type something, but don't send it. Just keep typing.
3. If connection isn't reliable, the text will just disappear and there's no way to restore it.

### Expected behaviour
The text must not disappear.

### Actual behaviour
The text disappears

### Configuration
**Operating system:** Windows, Linux (Ubuntu)

**Version of Telegram Desktop:** 1.1.23

**Comment by stek29** [comment] 2017-10-13 00:51
Just use undo, see #3567.

Duplicate of #2963, #2315, #2371.

**Closed by stek29** 2017-10-13 00:51 UTC
