### ISSUE TITLE
Prefer IPv6 if its available

### ISSUE THREAD

**Issue by nshopik** [telegramdesktop/tdesktop#2198] opened 2016-06-27 14:18 UTC
### Steps to reproduce
1. Open Telegram on dual-stacked host
2. Telegram tries connect via IPv4 and IPv6
3. Then drops IPv6 connection and stick to IPv4 only
### Expected behaviour

It should stick to IPv6 if its available and not crippled, similar to happy eyeballs **RFC6555**
### Actual behaviour

Always prefers IPv4, only disabling IPv4 make it stick to IPv6.
### Configuration

Xubuntu 16.04
`4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

v 0.9.56 alpha
### Logs

startup log
https://gist.github.com/nshopik/31528efa4cce7dbccdd7d99f5ef9e862

**Comment by XenHat** [comment] 2016-07-03 02:23
I would like to add that Telegram will also stay on IPV4 mode regardless of the user preference when behind an ISP-provided 6to4 tunnel (Videotron Ltee in my case). I have only tested this on Windows x64 so far.

**Comment by nshopik** [comment] 2016-07-03 09:21
@XenHat This is per design on most OSes, 2002::/16 prefix usually have lower precedence
https://tools.ietf.org/html/rfc6724#section-2.1 so it only selected to route within same prefix.

**Comment by nshopik** [comment] 2016-09-21 09:40
@john-preston This also somewhat improve security, as CGNAT become more common, IPv4 address from which somebody logged into your account could be same as yours and you could completely ignore that by mistake.

Thus connecting via IPv6 preferably give you better track your sessions

**Comment by stek29** [comment] 2016-10-06 17:46
Happens on OS X too by the way.

**Comment by vitorgrs** [comment] 2017-05-27 00:00
This still happens on Windows.

**Comment by yangm97** [comment] 2017-05-27 02:37
Still happens on macOS.

**Comment by john-preston** [comment] 2017-05-27 09:01
Yes, currently IPv4 is preferred to IPv6, because IPv4 shows itself better, is more stable from both our side and local provider side.

**Comment by nshopik** [comment] 2017-05-27 09:58
@john-preston Is there any practical reason why checkbox `try connecting through IPv6` unchecked by default then? 

> Yes, currently IPv4 is preferred to IPv6, because IPv4 shows itself better, is more stable from both our side and local provider side.

I would disagree on that, since iOS version and macOS native version prefer IPv6 and work flaweless

**Comment by john-preston** [comment] 2017-05-27 10:00
@nshopik On Windows I had several reports that when trying to connect both with IPv4 and IPv6 the first one was not working at all till the app restart, so this was moved to settings, disabled by default and on Windows it even requires app restart to change. I could not debug this issue back then and it wasn't a big problem anyway.

**Comment by yangm97** [comment] 2017-05-27 19:46
Wouldn’t it be better to have a dropdown in which the user chooses between auto (default, telegram tries to “reliability test” both), force ipv4 and force ipv6? Multiple users from multiple ISPs have mixed results, guess that would close this case once and for all.

**Comment by nshopik** [comment] 2017-05-29 09:45
@john-preston That's why I've suggested RFC6555 style address family selection instead dumb preference, which may cause problem. All current browsers implement it and correctly fallback to IPv4 if IPv6 in broken state.

Current IPv6 support just doesn't make sense, tdesktop support it but not enabled by default and even if you enable it still not even try connect IPv6 if IPv4 available. And as I'm rightly pointed out it make sense from security perspective when CGN comes into play to prefer IPv6 if its available and working.

**Comment by vitorgrs** [comment] 2017-05-30 02:38
The problem is that even if you enable to use ipv6, it doesn't (unless you disable ipv4 stack on windows, which doesn't make any sense)

**Comment by stek29** [comment] 2017-05-30 07:11
Btw, Telegram deals with IPv6 pretty weirdly -- if you log in using it you get a private IP address in "somebody logged in" message

**Comment by nshopik** [comment] 2017-05-30 09:53
@stek29 They had issue with backend previously which report weird private IP ranges including multicast ranges, now it report correctly in `active session` tab at least for me it was fixed for about month

**Comment by Aokromes** [comment] 2017-10-02 18:36
Maybe dropdown to auto (prefered ipv6) auto (prefered ipv4) ipv4 ipv6? :)

**Comment by Lefey** [comment] 2018-04-21 14:01
Please! Add dropdown to auto (prefered ipv6) / auto (prefered ipv4) / ipv4-only / ipv6-only

**Comment by bjo81** [comment] 2019-07-18 13:35
I have several clients which have IPv6 (no 6to4), "use IPv6" is enabled, but the connection is made via IPv4.

**Comment by miyurusankalpa** [comment] 2019-07-18 18:31
Cannot use telegram over IPv6 only connection.

**Try connecting through IPv6** is checked.

Windows 10 1903

Log:
```
[2019.07.18 23:54:50] Launched version: 1007013, install beta: [FALSE], alpha: 0, debug mode: [TRUE], test dc: [FALSE]
...
[2019.07.18 23:54:52] HTTP Error: network error 99 - Network unreachable
[2019.07.18 23:54:52] HTTP Error: network error 99 - Network unreachable
[2019.07.18 23:54:52] HTTP Error: network error 99 - Network unreachable
[2019.07.18 23:54:54] TCP Error: network - Network unreachable
[2019.07.18 23:54:54] TCP Error: network - Network unreachable
[2019.07.18 23:54:54] TCP Error: network - Network unreachable
```

**Comment by kudrevatykh** [comment] 2019-09-28 21:51
Just tested latest client and it successfully connected via IPv6

**Comment by Kirya2k** [comment] 2020-10-24 14:16
It's time to remove this crutch. 
In networks where there is ipv6, it is already more stable than ipv4.

**Comment by ilya-fedin** [comment] 2020-10-31 22:28
> It's time to remove this crutch.

I have a feel that tdesktop won't use IPv6 until someone brave PR a RFC6555 implement, since it seems really complicated and devs might have no time (or just too lazy) to implement.

**Comment by Mikaela** [comment] 2021-04-30 05:44
I think this issue still exists.

**Comment by booth-f** [comment] 2021-07-05 14:08
Looks like this is still affecting networks where native IPv6 has been implemented. I've done everything I can think of in terms of "Best Practice" for deploying with IPv6 (SLAAC/RDNSS/ full /64s to each subnet) and I can see devices pick it up and use it but Telegram is still falling back to IPv4.

**Comment by miyurusankalpa** [comment] 2021-08-30 09:39
In my country, the unlimited packages have telegram limited to 1mbps, but I found out that it is only limited on IPv4. On IPv6 I get full speed.

I have setuped firewall rules to block telegram IPv4 address to force IPv6 in the desktop app. It would be better to other users if IPv6 was preferred when there is native connectivity.

**Comment by michelolvera** [comment] 2022-02-05 07:19
I don't understand why use IPv4 before IPv6, is this a bug or a premeditated decision by telegram team?
If so, please explain why this decision was taken.

**Comment by ilya-fedin** [comment] 2022-02-05 07:22
@michelolvera read the thread, it was explained

**Comment by michelolvera** [comment] 2022-02-05 07:27
@ilya-fedin so this decision will not change? It has been 5 years and it seems to me that the adoption of IPv6 has increased considerably, or if someone sends a PR with this functionality, do you think it would be accepted?

**Comment by ilya-fedin** [comment] 2022-02-05 07:31
@michelolvera I guess if someone sends a PR that implements this in a way that won't add connection problems (the mentioned RFC6555 apparently) then @john-preston won't be against that, but better to ask himself, maybe it's still blocked by server admins or something else...

**Comment by SopaDeMacaco-UmaDelicia** [comment] 2022-10-11 02:56
Any news about the issue? It was first reported in 2016 when IPv6 adoption rate was 16%, now we live in 2022 where adoption world-wide is 42%. It's kinda dumb to use IPv4 when I have an IPv6 connection.

**Comment by ilya-fedin** [comment] 2022-10-11 03:11
No one volunteers for implementing RFC6555 in tdesktop

**Closed** 2024-12-19 11:49 UTC
Labels: enhancement
