### ISSUE TITLE
Cannot display korean text

### ISSUE THREAD

**Issue by perillamint** [telegramdesktop/tdesktop#202] opened 2014-10-15 13:24 UTC
Since this project uses DejaVu Sans font, It cannot render korean text correctly because that font does not include korean glyphs (it renders korean text as square boxes). I think it should have an option to change its font for users who uses non-latin letters for their language.

**Comment by mxa** [comment] 2015-02-18 01:35
Duplicate of #196 ?

**Comment by telegramdesktop** [comment] 2015-08-14 20:33
Should be fine already.

**Closed by telegramdesktop** 2015-08-14 20:33 UTC
