### ISSUE TITLE
Persian font

### ISSUE THREAD

**Issue by hamidna** [telegramdesktop/tdesktop#7840] opened 2020-05-08 16:25 UTC
Hi, I installed version 2.1.3.
The fonts are cluttered and irritate the eyes
https://imgur.com/hf0M8rr
Please return the font to version 2.1. You can't read the text well now

**Comment by ilya-fedin** [comment] 2020-05-08 16:30
Now Vazir font is used which was requested by Persian people for years and years

**Comment by hemagx** [comment] 2020-05-08 16:34
I use it for Arabic and the new font is just horrible, Windows is terrible when it come to rendering fonts using any Arabic traditional fonts just makes it worse on windows because windows will end up blurring all non-rough edges (which is basically the whole thing).

The preferred font for Arabic or Persian or whatever language using the Arabic abjads is Tahoma and it's even the preferred fonts in all academic paper, communications and formal letter writing because of how nice and clean it renders out.

Telegram as it is right now is simply unusable by any users relays on those languages and it's not even possible to easily change this font either.

**Comment by ilya-fedin** [comment] 2020-05-08 16:38
Decide between yourself which font you want. In the [previous discussion](https://github.com/telegramdesktop/tdesktop/issues/7823), Persian people said that Vazir is much better than the old font.

**Comment by hemagx** [comment] 2020-05-08 16:48
Excuse me, by Persian people you mean a total of 7 people participating in issue? a great sample to represent the tens of million users.

Regardless, this is not a topic about Persians and non-Persians, I'm not a Persian nor i talk in behave of them or any other "Ethnicity".

I'm simply stating the facts, Windows is horrible at rendering fonts, any Arabic traditional renders with serious blur and it's a known issue in windows, you can't just enforce bad quality font render on all users and disregard everyone else providing a terrible UX and awful UI for everyone, I've update just minutes ago and my eyes are already tearing here.

Provide some sort of easy font selector for those users to use their font of choice and let everyone else live in peace.

**Comment by ilya-fedin** [comment] 2020-05-08 16:51
> Excuse me, by Persian people you mean a total of 7 people participating in issue?

https://github.com/telegramdesktop/tdesktop/issues?q=is%3Aissue+persian

In almost every issue about the font, there are requests to use Vazir

**Comment by ilya-fedin** [comment] 2020-05-08 16:52
> you can't just enforce bad quality font render on all users and disregard everyone else providing a terrible UX and awful UI for everyone

They said that Tahoma is bad UX, you said that Vazir. Who are right? ;)
I don't know

**Comment by neesti** [comment] 2020-05-08 18:04
I say that Vazir font is very readable than Tahoma font in Persian scripts. 

Note: "Sahel" font is more compatible with Persian text than Vazir. 
https://github.com/rastikerdar/sahel-font

**Comment by Aokromes** [comment] 2020-05-08 18:15
> Excuse me, by Persian people you mean a total of 7 people participating in issue? a great sample to represent the tens of million users.
> 
> Regardless, this is not a topic about Persians and non-Persians, I'm not a Persian nor i talk in behave of them or any other "Ethnicity".
> 
> I'm simply stating the facts, Windows is horrible at rendering fonts, any Arabic traditional renders with serious blur and it's a known issue in windows, you can't just enforce bad quality font render on all users and disregard everyone else providing a terrible UX and awful UI for everyone, I've updated telegram just minutes ago and my eyes are already tearing here.
> 
> Provide some sort of easy font selector for those users to use their font of choice and let everyone else live in peace.

we asked feedback on semiofficial channel, that was all we got.

**Comment by hamidna** [comment] 2020-05-08 18:16
> Now Vazir font is used which was requested by Persian people for years and years

This font is very ugly and tiny.
Please create a feature that allows you to select fonts.
You impose this font on us

**Comment by ilya-fedin** [comment] 2020-05-08 18:18
> Please create a feature that allows you to select fonts.

#90

**Comment by ilya-fedin** [comment] 2020-05-08 18:21
![image](https://user-images.githubusercontent.com/17829319/81436240-a9caa100-9158-11ea-8eb2-7a7c6410a396.png)

**Comment by Sepehrtooz** [comment] 2020-05-08 18:27
:/

**Comment by hamidna** [comment] 2020-05-08 18:31
> > Please create a feature that allows you to select fonts.
> 
> #90

It is very small. Make the font bigger, maybe the problem will be solved

**Comment by majidnikpour** [comment] 2020-05-08 18:40
i think its best persian font ever

**Comment by neesti** [comment] 2020-05-08 18:43
I have a question:
Which version of Vazir is used for Telegram 2.3.1? 

Latest version of Vazir is: 25.0.0
https://github.com/rastikerdar/vazir-font/releases

**Comment by ilya-fedin** [comment] 2020-05-08 18:44
> Which version of Vazir is used for Telegram 2.3.1?

I took it from the dist folder from master, from the Without-Latin subfolder

**Comment by Aphotice** [comment] 2020-05-08 19:03
well as a Farsi & Arabic writer, i think this argument will go on forever
and each language should be able to use its own best language
and as many none middle eastern might think 

Farsi & Arabic are not the same language/font
even though they have similarities

what do you mean?
Do you mean the bold part?
making Farsi/Arabic bold is tricky in general
cus for a very long time bolding these was not possible, so no one's eyes are used to it
so they just call something "new" to the eyes, "ugly"
hmmm

**Comment by Aokromes** [comment] 2020-05-08 19:23
https://github.com/telegramdesktop/tdesktop/commit/5d3b8f02fc140cbef15e538fc20679d9c24004eb#commitcomment-39045176

**Comment by ilya-fedin** [comment] 2020-05-08 19:30
Does this font engine look better?
https://github.com/ilya-fedin/tdesktop/actions/runs/99402698

**Comment by sina-rst** [comment] 2020-05-08 19:34
This new Font is really good, Tnx

**Comment by AliDjango** [comment] 2020-05-08 19:38
@ilya-fedin Tdesktop 2.1.3 Stable on windows 10 pro 1909
I love the font and it is really readable and easy on eyes.
The size is a little small though but thats the problem with the font itself.but can you increase the font for farsi language a little?

**Comment by ilya-fedin** [comment] 2020-05-08 19:40
> This new Font is really good, Tnx

Are you saying about font in the release or in the test artifact? :thinking:

**Comment by sina-rst** [comment] 2020-05-08 19:41
@ilya-fedin in the release!
in fact I said about the linux version
the update received several minutes ago!

**Comment by ilya-fedin** [comment] 2020-05-08 19:47
ok

**Comment by AliDjango** [comment] 2020-05-08 19:47
> Does this font engine look better?
> https://github.com/ilya-fedin/tdesktop/actions/runs/99402698

what is this test build about?

**Comment by ilya-fedin** [comment] 2020-05-08 19:49
> what is this test build about?

for these disgruntled people

**Comment by AliDjango** [comment] 2020-05-08 19:50
> @ilya-fedin Tdesktop 2.1.3 Stable on windows 10 pro 1909
> I love the font and it is really readable and easy on eyes.
> The size is a little small though ,thats the problem with the font itself.but can you increase the font for farsi language a little?

ok.don't worry about the font.im sure people WILL love this new font.
anyway can you answer my question about the font size please?

**Comment by ilya-fedin** [comment] 2020-05-08 19:54
> anyway can you answer my question about the font size please?

I don't know any way to increase size only for specified writing system
And I think preston won't increase font size for all writing systems

**Comment by AliDjango** [comment] 2020-05-08 19:57
@ilya-fedin can you please check it out later or ask preston about changing font for specified writing system?

btw its not much of a big deal.i just increased the scaling and its perfect now

**Comment by ilya-fedin** [comment] 2020-05-08 20:01
> can you please check it out later or ask preston about changing font for specified writing system?

As I already said - looks like there are no API for that

**Comment by mehdiirh** [comment] 2020-05-08 20:10
Ofc Vazir is better than Tahoma, but, there is a big need to add a font selector for tdesktop
I use arch linux, idk why when I install "Iran Nastaliq" font, tg font will switch to that, so I have to delete that font to get back to Vazir.
So adding a font selector to tdesktop is a good option that keeps everyone happy.

**Comment by ilya-fedin** [comment] 2020-05-08 20:12
> so I have to delete that font to get back to Vazir.

Why not just to make it preffered font via fontconfig?

**Comment by ilya-fedin** [comment] 2020-05-08 20:14
> https://github.com/ilya-fedin/tdesktop/actions/runs/99402698

I got one feedback. Can try this build anyone else?
This is a build with different font engine - freetype
It displays font with different hinting/antialiasing

**Comment by AliDjango** [comment] 2020-05-08 20:19
1.i don't  know how to increase  size in fontconfig. I tried something but
it didnt work
2.i use windows 10 and there is no fontconfig in it ofcourse

**Comment by ilya-fedin** [comment] 2020-05-08 20:20
> .i don't know how to increase size in fontconfig. I tried something but it didnt work

I answered to @mehdiirh

**Comment by Aokromes** [comment] 2020-05-08 20:21
> 1.i don't know how to increase size in fontconfig. I tried something but it didnt work 2.i use windows 10 and there is no fontconfig in it ofcourse

you can use https://github.com/ysc3839/FontMod/ to test witch font fits better you.

**Comment by Sepehrtooz** [comment] 2020-05-08 20:43
in the test artifact:

![image_2020-05-09_00-54-18 (2)](https://user-images.githubusercontent.com/55192376/81446927-f29e4c00-9190-11ea-88a7-fcf5e06290ab.png)

in the release:

![image_2020-05-09_00-54-46](https://user-images.githubusercontent.com/55192376/81447014-182b5580-9191-11ea-8c14-79141934fb40.png)

I think the top is better
What do the others think?

**Comment by AmirHosseinKarimi** [comment] 2020-05-08 20:49
So finally after many years, this feature was implemented to Telegram Desktop.
Thank you @john-preston and other contributors and participants.

**Comment by mehdiirh** [comment] 2020-05-08 20:58
> > so I have to delete that font to get back to Vazir.
> 
> Why not just to make it the preferred font via fontconfig?

Doesn't really help. Tried before

**Comment by ilya-fedin** [comment] 2020-05-08 21:30
> Doesn't really help. Tried before

There are tags for different writing systems. You can find them in files in /etc/fonts/conf.d that named like `65-fonts-persian.conf`, maybe they can help you to fix the fallback?

**Comment by ilya-fedin** [comment] 2020-05-08 21:31
![image](https://user-images.githubusercontent.com/17829319/81451062-2ff3e100-9173-11ea-8091-46ce0d449bbc.png)
I can see this in my `65-fonts-persian.conf`

**Comment by ilya-fedin** [comment] 2020-05-08 21:48
btw, maybe I should notice: Vazir fallback was added only in official builds (static binary, flatpak, snap)
Distro maintainers always remove these things to use system fonts.

**Comment by ilya-fedin** [comment] 2020-05-08 22:15
Maybe Vazir should be used only start from 125% scaling?

**Comment by yar72** [comment] 2020-05-09 06:22
The fonts are cluttered and irritate the eyes.
Please return the font to version 2.

**Comment by AliDjango** [comment] 2020-05-09 07:02
> > 1.i don't know how to increase size in fontconfig. I tried something but it didnt work 2.i use windows 10 and there is no fontconfig in it ofcourse
> 
> you can use https://github.com/ysc3839/FontMod/ to test witch font fits better you.

thanks,But I don't need to test."Vazir" is waaaaaay better than before.

**Comment by AliDjango** [comment] 2020-05-09 07:04
> The fonts are cluttered and irritate the eyes.
> Please return the font to version 2.

i'm pretty sure you are not used to it yet,it is not "irritating" its just "new"
can you try to use Tdesktop for few days and then decide on this?

**Comment by AliDjango** [comment] 2020-05-09 07:05
> Maybe Vazir should be used only start from 125% scaling?

im sure lots of iranian users don't even know/use scaling so i guess not

**Comment by Sepehrtooz** [comment] 2020-05-09 07:06
> The fonts are cluttered and irritate the eyes.

@yar72 please test it :
> https://github.com/ilya-fedin/tdesktop/actions/runs/99402698

In this, the font are not irritate your eyes.

**Comment by Aokromes** [comment] 2020-05-09 07:24
follow here plz
https://github.com/telegramdesktop/tdesktop/issues/7851

**Comment by AliDjango** [comment] 2020-05-09 07:39
> > https://github.com/ilya-fedin/tdesktop/actions/runs/99402698
> 
> I got one feedback. Can try this build anyone else?
> This is a build with different font engine - freetype
> It displays font with different hinting/antialiasing

This one looks a little thicker and I think it looks good.

**Comment by yar72** [comment] 2020-05-09 07:51
The fonts are cluttered and irritate the eyes.
Please return the font to version 2.

> 
> 
> > The fonts are cluttered and irritate the eyes.
> > Please return the font to version 2.
> 
> i'm pretty sure you are not used to it yet,it is not "irritating" its just "new"
> can you try to use Tdesktop for few days and then decide on this?

I wrote here because I used it!!!! 
I am comfortable with my font.

**Comment by Sepehrtooz** [comment] 2020-05-09 08:14
> > > https://github.com/ilya-fedin/tdesktop/actions/runs/99402698
> > 
> > 
> > I got one feedback. Can try this build anyone else?
> > This is a build with different font engine - freetype
> > It displays font with different hinting/antialiasing
> 
> This one looks a little thicker and I think it looks good but it feels like everything is bold so i like the release version

In my opinion, in the test version, the difference between bold font and regular font in a sentence is displayed better than the release.

👇 in the test
![Untitled](https://user-images.githubusercontent.com/55192376/81467944-607a6000-91f1-11ea-8db8-bc93885acbe8.png)
👆 in the release

In the release, you can hardly understand the difference between bold font and regular font

**Comment by ilya-fedin** [comment] 2020-05-09 08:16
> In my opinion, in the test version, the difference between bold font and regular font in a sentence is displayed better than the release.

This is because artifact is based on 2.1.3 and you're comparing with 2.1.4. Compare with 2.1.3 release ;)

**Comment by Sepehrtooz** [comment] 2020-05-09 08:21
:·)))))

**Comment by Sepehrtooz** [comment] 2020-05-09 08:56
> This is because the artifact is based on 2.1.3 and you're comparing with 2.1.4. Compare with 2.1.3 release ;)

The 2.1.3 release font looks sharp
and artifact font looks blurry and bold as you and others said
Can you make it something between these two?

**Comment by ilya-fedin** [comment] 2020-05-09 08:59
> Can you make it something between these two?

:thinking: maybe QFont::NoSubpixelAntialias + QFont::PreferVerticalHinting (which should be the same as subpixel=none + hinting=hintslight on linux)

**Comment by ilya-fedin** [comment] 2020-05-09 12:47
This is artifact with grayscale antialiasing and light hinting
https://github.com/ilya-fedin/tdesktop/actions/runs/99942874
By default GDI is used, FreeType can be activated by typing `freetype` in the settings (look at https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes)

**Comment by ilya-fedin** [comment] 2020-05-09 13:15
> https://github.com/ilya-fedin/tdesktop/actions/runs/99942874

I think rendering should become much better for low-DPI devices

**Comment by ilya-fedin** [comment] 2020-05-09 13:27
This is the same artifact as previous, but based on 2.1.4
https://github.com/ilya-fedin/tdesktop/actions/runs/99956516

**Comment by Sepehrtooz** [comment] 2020-05-09 13:35
> This is an artifact with grayscale antialiasing and light hinting
> https://github.com/ilya-fedin/tdesktop/actions/runs/99942874
> By default GDI is used, FreeType can be activated by typing `freetype` in the settings (look at https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes)

Very well, now everyone can choose their favorite rendering
as well Both renderings are better than before 👌
thank you very much 💙

**Comment by osamz** [comment] 2020-05-09 14:37
Is there a way to choose use different font for Arabic language?
Because what is good For Farisi is may be not good for Arabic, these are different languages totally.
So, please change the Arbic font If it possible, without changing the Farisi font.

**Comment by ilya-fedin** [comment] 2020-05-09 14:42
> Is there a way to choose use different font for Arabic language?

Did Arabic font changed as well?

**Comment by Abasalt-yar** [comment] 2020-05-10 03:19
Can't we just uses any fonts that we like ? (I did it before - Regedit)

**Comment by osamz** [comment] 2020-05-10 07:36
> Has the Arabic font changed as well?
In last ver. 2.1.4 the Arabic font changed to The Farisi font.

**Comment by ilya-fedin** [comment] 2020-05-10 08:01
Can you screenshot how it looks like now and how it should look like?

**Comment by osamz** [comment] 2020-05-10 08:17
> 
> 
> Can you screenshot how it looks like now and how it should look like?

Previously I was edited it from registry, and I think It was a default font. but now It changed to:

![image](https://user-images.githubusercontent.com/13044444/81494090-9e898980-92ae-11ea-9c0e-65b60d2238ae.png)

the default font was someting near this:

![image](https://user-images.githubusercontent.com/13044444/81494203-ab5aad00-92af-11ea-9b8d-fa5c2a4b36f8.png)


and I was edited my font to:  `Arabic UI Text Bold`
![image](https://user-images.githubusercontent.com/13044444/81494109-c4169300-92ae-11ea-97aa-caa4c7f2f286.png)

this edting was in:
```
Computer\
HKEY_LOCAL_MACHINE\
SOFTWARE\
Microsoft\
Windows NT\
CurrentVersion\
FontSubstitutes

MS Shell Dlg 2
```

**Comment by osamz** [comment] 2020-05-10 08:20
I suggest to use **Noto Naskh** for Arabic language
https://noto-website-2.storage.googleapis.com/pkgs/NotoNaskhArabic-hinted.zip 

If Windows will render it perfectly.

**Comment by ilya-fedin** [comment] 2020-05-10 08:21
Try to make font substitute for DAOpenSansRegular, DAOpenSansRegularItalic, DAOpenSansSemibold and DAOpenSansSemiboldItalic instead of MS Shell Dlg 2

**Comment by ilya-fedin** [comment] 2020-05-10 08:29
> Previously I was edited it from registry, and I think It was a default font. but now It changed to:

If this is Segoe UI, then your issue will be fixed in the new version

**Comment by meshalharbi** [comment] 2020-05-10 23:07
> Has the Arabic font changed as well?

Yes, I don't think this was intended, no?

![2 1 2](https://user-images.githubusercontent.com/48245335/81512665-f1a12200-932a-11ea-85b6-fe975021194b.png)
![2 1 3](https://user-images.githubusercontent.com/48245335/81512667-f534a900-932a-11ea-9b8d-44ef5e03c3a6.PNG)

2.1.4 looks exactly like 2.1.3.

I will not open a new issue as this seems to be caused by the change of the Persian font. Please look into options that fix this by at least reverting the Arabic font to the one used in 2.1.2. You can see how the new font is not even rendering correctly and looks jagged compared to version 2.1.2.

**Comment by ilya-fedin** [comment] 2020-05-10 23:11
> Yes, I don't think this was intended, no?

This was not intended
I hope this will be fixed with Thai/Khmer/Armenian fix

**Comment by jbjumbojb** [comment] 2020-05-11 03:55
> This is the same artifact as previous, but based on 2.1.4
> https://github.com/ilya-fedin/tdesktop/actions/runs/99956516

Thai language was fixed in this artifact.

**Comment by danialbehzadi** [comment] 2020-05-11 08:38
Seems you are using windows. Just stop using that shit, since windows has font rendering issues for centuries!

**Comment by neesti** [comment] 2020-05-13 15:49
New version of Vazir font (Version 26.0) is released. Please use it in next version of TDesktop. 
Thank you.

**Comment by DJafari** [comment] 2020-05-13 23:54
@ilya-fedin why selecting font is not customizable ?
i think every people love a font and reverese don't like some font

**Comment by ilya-fedin** [comment] 2020-05-13 23:58
> @ilya-fedin why selecting font is not customizable ?

This is not a question for me, I want a font chooser too :(

**Comment by DJafari** [comment] 2020-05-14 00:02
> > @ilya-fedin why selecting font is not customizable ?
> 
> This is not a question for me, I want a font chooser too :(

it's mean it is impossible ?
or i must waiting for next releases ?

**Comment by ilya-fedin** [comment] 2020-05-14 00:05
> it's mean it is impossible ?

It's mean you should ask one of official devs. I'm just a contributor.

**Comment by DJafari** [comment] 2020-05-14 00:09
> > it's mean it is impossible ?
> 
> It's mean you should ask one of the official devs. I'm just a contributor.

ok please mention one of them to this issue, maybe he accepted our request!

**Comment by ilya-fedin** [comment] 2020-05-14 00:12
> ok please mention one of them to this issue, maybe he accepted our request!

@john-preston

**Comment by osamz** [comment] 2020-05-14 08:39
@john-preston
Why there are no font chooser?

**Comment by aminvakil** [comment] 2020-05-14 19:33
Of course this vazir font is better than previous one, but I should at least have the opportunity to use my own system-wide font for persian which was IRANSans and I like it more.

It's licensed and cannot be used in telegram-desktop client of course, I'm not suggesting that.

I'm just suggesting an option to choose system-wide font instead of Vazir or whatever font telegram-desktop ships with its package.

**Comment by danialbehzadi** [comment] 2020-05-14 20:07
Actually telegram-desktop needs to integrate more with users desktop. Currently it is the only "foreign looking" app in my desktop which doesn't respect my choice of theme, font, etc and has no integration with standard freedesktop e.g. MPRIS2 for music playback.

**Comment by ilya-fedin** [comment] 2020-05-14 20:09
> Currently it is the only "foreign looking" app in my desktop

Probably you doesn't have electron apps or QML/proprietary Qt apps ;)

**Comment by danialbehzadi** [comment] 2020-05-15 04:18
> Probably you doesn't have electron apps or QML/proprietary Qt apps ;)

Yes, all my other apps are pure GTK3 but Firefox, which supports GTK and respects my choices such as themes and fonts.

**Comment by IbneZia** [comment] 2020-05-19 10:10
![image](https://user-images.githubusercontent.com/4980318/82313912-77376880-99e2-11ea-86fe-0d68783fc2d6.png)
Font issue, faced by Urdu-language users is greater than Persian/Arabic users. After updating telegram desktop to 2.1.6, all non-Arabic characters are breaking up. I have tried installing different fonts in PC like Open Sans and Vezir, but din't work. It is very difficult and almost impossible to read messages for many users.

**Comment by techvanity** [comment] 2020-05-20 06:07
+1 for the above post mentioning problem in Urdu.
It was a poor decision to switch to a font used only by Persians. Arabic users are not liking the font for cosmetic reasons. But for Urdu readers, the problem is worse — the new font is broken and non functional. It lacks support for Urdu-specific characters.
The best solution would be to implement a font selector for user customization. But meanwhile please revert to previous font.

**Comment by danialbehzadi** [comment] 2020-05-20 07:58
> The best solution would be to implement a font selector for user customization. But meanwhile please revert to previous font.

The best solution would be respecting user's selected font for desktop.

**Comment by M86xKC** [comment] 2020-05-20 21:59
@Aokromes @ilya-fedin IMO this must have been tested more thoroughly as there are multiple languages affected by this change, that the "Vazir" font might not support.

Not to mention the rendering/shaping/hinting/anti-aliasing issues with some operating systems.

I suggest revering these changes and falling back to operating system fonts as they can support more languages, be changed system wide and will help a more consistent experience across with the whole desktop, until a better solution is found.

Also according to the [commit message](https://github.com/telegramdesktop/tdesktop/commit/5d3b8f02fc140cbef15e538fc20679d9c24004eb) this must be a fallback font which it is not! It is used and even overrides the system fonts for farsi/arabic/urdu ...etc

**Comment by Aokromes** [comment] 2020-05-21 01:06
> @Aokromes @ilya-fedin IMO this must have been tested more thoroughly as there are multiple languages affected by this change, that the "Vazir" font might not support.
> 
> Not to mention the rendering/shaping/hinting/anti-aliasing issues with some operating systems.
> 
> I suggest reverting these changes and falling back to operating system fonts as they can support more languages, be changed system wide and will help a more consistent experience across with the whole desktop, until a better solution is found.
> 
> Also according to the [commit message](https://github.com/telegramdesktop/tdesktop/commit/5d3b8f02fc140cbef15e538fc20679d9c24004eb) this must be a fallback font which it is not! It is used and even overrides the system fonts for Farsi/Arabic/Urdu ...etc

we asked feedback multiple times the amount of answers was very low, ofc changing non-farsi languages is unwanted.

**Comment by ebraminio** [comment] 2020-05-21 07:40
* I think the main issue here is hinting of the new font. Tahoma is of course optimized very well for low sizes, both by having hinting and having a better design for small text. Segoe UI is also provided by Microsoft as somehow a replacement for Tahoma and is very nice.
* Newer versions of Vazir has supported Urdu and Pashto letters, https://github.com/rastikerdar/vazir-font/releases so it resolved some of the mentioned issues that were in the shipped font. Lots of people including me like the font specially at higher DPI screens.
* `Noto Naskh Arabic` is referred in this thread which is good as being default on Android, I like to suggest `Noto Sans Arabic` also if you see shipping a font is a necessity. It is preinstalled on Linux distributions also and see that somehow having a style both useful for Arabic and Persian people.

Let's compare suggestions here and may vote to them here (or maybe eventually in Telegram itself?), feel free to use GitHub reaction using Emojis I've put for each font,

Noto Sans Arabic :+1: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-hinted.zip 
![image](https://user-images.githubusercontent.com/833473/82533233-1d58af00-9b58-11ea-809a-5ec63dc5f772.png)

Vazir :tada: 
![image](https://user-images.githubusercontent.com/833473/82533396-6b6db280-9b58-11ea-81f2-1b1fa743520f.png)

Noto Naskh Arabic :rocket: 
![image](https://user-images.githubusercontent.com/833473/82533488-9952f700-9b58-11ea-9676-081317483e28.png)

Segoe UI (so not shipping the font along Telegram and using the new system default on Windows) :rocket: 
![image](https://user-images.githubusercontent.com/833473/82534425-57c34b80-9b5a-11ea-9576-08290b3e4a71.png)

Tahoma (previous font) :eyes: 
![image](https://user-images.githubusercontent.com/833473/82534458-690c5800-9b5a-11ea-85ba-b030b05cb90e.png)

:-1: if none of them :)

**Comment by ilya-fedin** [comment] 2020-05-21 16:19
Why are Noto Naskh Arabic and Tahoma both marked with a rocket?

**Comment by ebraminio** [comment] 2020-05-21 16:51
Oops, fixed :)

**Comment by Aokromes** [comment] 2020-06-04 11:03
this issue is still valid?

**Comment by M86xKC** [comment] 2020-06-04 12:18
As I said before, IMO it is not a good practice to hardcode using a specific font for an entire writing script, there are a dozen or so of languages affected by this changes. Operating systems have a more complete set of fonts that support almost all languages for the Arabic script.

Maybe change only Persian font to Vazir as it turns out that people like it. I don't know if this is possible though.

**Comment by ilya-fedin** [comment] 2020-06-04 12:26
> I don't know if this is possible though.

No, Qt doesn't have such APIs.

**Comment by aminvakil** [comment] 2020-06-04 14:31
@ilya-fedin Can't it be an option for user to choose between shipped font (currently Vazir) and system-wide font?

**Comment by aminvakil** [comment] 2020-06-04 17:08
Compiling with `-DDESKTOP_APP_USE_PACKAGED_FONTS=ON` uses system-wide font.

**Comment by Aokromes** [comment] 2020-06-26 04:31
this ticket can be closed?

**Comment by Aokromes** [comment] 2020-07-30 18:11
1 month without answer, if this bug is still valid open a new ticket with updated version.

**Closed by Aokromes** 2020-07-30 18:11 UTC
Labels: waiting for answer
