### ISSUE TITLE
Inconsistence in the use of up-arrow is misleading for users

### ISSUE THREAD

**Issue by doktormerlin** [telegramdesktop/tdesktop#4480] opened 2018-03-09 11:07 UTC
### Steps to reproduce
1. Send a message
2. Press the up arrow
-
1. Send a message from another client
2. Press the up arrow
-
1. Send a message
2. Scroll a bit upwards and then down to the bottom of the chat again
3. Press the up arrow
-
1. Send a message
2. Change chats
3. Change chats back again
4. Press the up arrow

### Expected behaviour
The up arrow should always have the same output if you are at the bottom of the chat, no matter what the user did before or after. It's misleading. If at the bottom of the chat, the last message you sent should be editable by pressing the up arrow key.

### Actual behaviour
The message is not always editable. Sometimes it works, sometimes not.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2.10 alpha

**Comment by auchri** [comment] 2018-03-09 11:58
@doktormerlin You should really search for existing issues, almost every one of your issues is a duplicate of some already existing one.

**Comment by doktormerlin** [comment] 2018-03-09 12:11
@auchri There are 835 open issues. If there are duplicates of my issues, I could not find them. I searched for every single one of them, using some buzzwords from my issues. I just want to help improve the software.

**Comment by Aokromes** [comment] 2018-03-09 15:15
https://github.com/telegramdesktop/tdesktop/issues/2454 or https://github.com/telegramdesktop/tdesktop/issues/2455 ?

**Closed** 2018-03-09 15:19 UTC
