### ISSUE TITLE
Photo fullscreen mode opens on wrong monitor

### ISSUE THREAD

**Issue by DASPRiD** [telegramdesktop/tdesktop#10260] opened 2021-01-29 13:39 UTC
### Steps to reproduce
1. Click on a photo to view it in fullscreen mode

### Expected behaviour
Fullscreen mode should open on the same monitor on which the Telegram window is located.

### Actual behaviour
Fullscreen mode opens on the primary monitor.

### Configuration
**Operating system:** Pop_OS! 20.04

**Version of Telegram Desktop:** 2.5.7

**Installation source (Linux Only)** - the official website

**Used theme**: Night mode

**Comment by RememberTheAir** [comment] 2021-01-29 14:31
Duplicate of #5126

**Closed** 2021-01-29 14:39 UTC
