### ISSUE TITLE
[Feature request] Group tab for Private, groups and bots chat

### ISSUE THREAD

**Issue by Ansem93** [telegramdesktop/tdesktop#5303] opened 2018-10-25 09:03 UTC
Hi everyone,
It would be possibile to have an option to enable group tabs for Private chats, groups chats an bots chat?

**Comment by RememberTheAir** [comment] 2018-10-25 09:06
Duplicate of #1107 (the main one) and many many many other

**Closed** 2018-10-25 18:22 UTC

**Comment by stek29** [comment] 2018-12-05 21:43
no, the other issue isn't about searching. also, it's kinda a meta issue for "tabs pls"

**Comment by kenorb** [comment] 2019-02-14 22:38
Related: GH-5560
