### ISSUE TITLE
App closes unexpectedly and never opens chat again

### ISSUE THREAD

**Issue by theerfan** [telegramdesktop/tdesktop#6994] opened 2020-01-14 17:44 UTC
### Steps to reproduce
1.  Enter a chat, doesn't matter if it's group chat, a channel or even saved messages.
2.  Type "به فناییم " (Must include the space at the end of it) and send the message.

### Expected behaviour
It should send the message and work as usual, right?

### Actual behaviour
App crashes for no apparent reason, even crashes when you open the app and try to enter the said chat again.

### Configuration
**Operating system:**
Windows 10 64bit
**Version of Telegram Desktop:**
1.9.3
**Used theme**:
The default night mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

P.S: And yes, @yasharJahanshahloo discovered it first, I forgot to mention his name initially. xD

**Comment by yasharJahanshahloo** [comment] 2020-01-14 17:53
I discovered that first.

**Comment by mmkhmmkh** [comment] 2020-01-14 17:54
> I discovered that first.

That's a FACT.

**Comment by Aokromes** [comment] 2020-01-14 18:01
plz next time it crashes for you click send crash and post id here.

**Comment by theerfan** [comment] 2020-01-14 18:06
> 
> 
> plz next time it crashes for you click send crash and post id here.

It doesn't show the 'send crash' button and the next time I try to open it I only get this. 
![Screenshot (177)](https://user-images.githubusercontent.com/11455681/72369673-d83def80-3715-11ea-8203-c2828172b924.png)

**Comment by pyhp2017** [comment] 2020-01-15 16:39
Holy shit !
absolutely this is on purpose :)))

**Comment by john-preston** [comment] 2020-01-16 08:03
Can you please open Settings > Advanced, enable Install beta versions and then reproduce again? It should offer to send a crash report after that.

**Comment by john-preston** [comment] 2020-01-16 08:15
I can't reproduce that :( Maybe you can add me to such group that crashes tdesktop on Windows 10? t.me/preston

**Comment by ATofighi** [comment] 2020-01-17 19:47
It seems fixed in 1.9.4

**Comment by mmkhmmkh** [comment] 2020-01-18 12:00
@Aokromes @ATofighi 
This is NOT fixed in 1.9.4.
Reopen this issue.

**Comment by ATofighi** [comment] 2020-01-18 15:52
@mmkhmmkh But i can't reproduce it after I update telegram to 1.9.4

## Configuration
Operating system:
Windows 10 64bit
Version of Telegram Desktop:
1.9.4
Used theme:
The default night mode

**Comment by ATofighi** [comment] 2020-01-18 16:01
@mmkhmmkh You're right, I've disabled "Use system spell checker" after I update telegram.
If "Use system spell checker" is on, this issue will happen.

**Comment by john-preston** [comment] 2020-01-18 16:22
@ATofighi wow.. are you sure? that it happens with and doesn't happen without the spellchecker?

**Comment by ATofighi** [comment] 2020-01-18 16:28
@john-preston Yes, I'm sure.

**Comment by mmkhmmkh** [comment] 2020-01-18 20:52
> @mmkhmmkh You're right, I've disabled "Use system spell checker" after I update telegram.
> If "Use system spell checker" is on, this issue will happen.

> @ATofighi wow.. are you sure? that it happens with and doesn't happen without the spellchecker?

Thanks! Yes that's true, It only happens when spellchecker is enabled.

**Comment by john-preston** [comment] 2020-01-19 07:37
@mmkhmmkh Thanks for the info. I hope we'll be able to fix that now.

**Closed** 2020-01-20 10:04 UTC
