### ISSUE TITLE
Option to ignore 'Contact joined Telegram' notification

### ISSUE THREAD

**Issue by CtrInt** [telegramdesktop/tdesktop#964] opened 2015-08-05 16:46 UTC
Should be great to have the same option you got on the Android client to ignore the message '... just joined Telegram' when someone in your contact list creates a Telegram account.

In the Android client is located into:
Settings | Notifications and Sounds | (Events) Contact joined Telegram

Please: Use the new reactions of GitHub on the first entry of this issue instead of creating unnecessary +1 comments.

**Comment by pjc-is** [comment] 2015-08-16 21:01
+1

I agree.. would be great!

**Comment by wtayyeb** [comment] 2015-09-26 07:01
+1
I agree too. it is annoying and disturbing notification.

**Comment by cmbail** [comment] 2015-10-01 11:23
Seriously! Sometimes I make the effort of interrupting a meeting and unlocking my phone only to find that the notification from Telegram wasn't actually a message.

**Comment by auchri** [comment] 2015-10-01 11:54
You can turn off the notification in the android app

**Comment by CtrInt** [comment] 2015-10-02 00:30
This is a thread into telegramdesktop/tdesktop so it's about an improvement on the desktop client.

This improvement, is yet into the android app as I explain in the first post.

**Comment by zippl** [comment] 2015-10-05 11:22
+1

**Comment by andre-low** [comment] 2015-10-17 13:58
+1

**Comment by alizbazar** [comment] 2015-12-02 09:03
+1

**Comment by alizbazar** [comment] 2015-12-02 09:07
How can these be disabled on iOS? Super annoying!

**Comment by Ildarik** [comment] 2015-12-07 08:41
+1

**Comment by wsoyka** [comment] 2015-12-09 16:48
+1

**Comment by natanrolnik** [comment] 2015-12-17 09:52
+1

**Comment by stuntguy3000** [comment] 2015-12-17 13:03
+1

**Comment by carlosfilho88** [comment] 2015-12-17 13:05
+1

**Comment by bofm** [comment] 2016-01-07 17:39
+2

**Comment by mkalininait** [comment] 2016-01-26 07:46
+1

**Comment by irvinhomem** [comment] 2016-01-27 08:53
+1

**Comment by stavv** [comment] 2016-01-31 10:06
+1

**Comment by jonnywilliamson** [comment] 2016-02-24 10:06
Yes please!

**Comment by felizchachacha** [comment] 2016-03-02 11:14
Please please please

**Comment by nocodelab** [comment] 2016-03-14 15:40
+1 PLEASE!

**Comment by auchri** [comment] 2016-03-14 15:53
Use the new [reactions of GitHub](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) on **the first entry of this issue** instead of creating unnecessary `+1` comments.

**Comment by Aigerimm** [comment] 2016-04-07 09:20
+1

**Comment by marcosdiez** [comment] 2016-05-02 23:14
This is even more important in Brazil, where every 5 months some judge blocks whatsapp and than your whole contact list joins Teleram in the same day.

**Comment by theonedemon** [comment] 2016-07-26 21:51
bump

**Comment by thekrotek** [comment] 2017-06-26 06:27
Wow! Two years passed and we still don't have such a simple option. Nice job!

**Comment by Soxo2** [comment] 2017-10-26 17:32
I have the same problem

Amazing, why this feature has not been implemented yet? It's so annoying!! 
I even removed Telegram from iOS and used other Clients, like Teleplus. But the problem is that they doesn't show notifications at all, even messages from real users. So I had to come back to Telegram. But these notifications "User joined Telegram" kill me. I have 2500 contacts. Every day somebody "Joins" (((
I have to delete that massages. HELP PLEASE! ADD THIS SIMPLE FEATURE! PLEEEEES!

PS. re 
"Use the new reactions of GitHub on the first entry of this issue instead of creating unnecessary  +1  comments." - there is no "+1" or "I have the same problem" reaction...

**Comment by auchri** [comment] 2017-10-26 17:41
I think your Github is broken ... 
![20171026_194023](https://user-images.githubusercontent.com/5092164/32068133-ab6edc12-ba85-11e7-8c4b-0c97c149af81.jpg)

**Comment by Soxo2** [comment] 2017-10-26 18:31
I understood your hint from the very beginning ), yet, "thumb up", IMHO, means smth different, e.g. "I like it".

It's different to what I wanted to express - "I have the same question". I might dislike the post, yet having the same problem. "Thumb up" doesn't fit.

I like how Microsoft did it. See any thread there, e.g. -

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_win10-mso_o365b/microsoft-word-attempts-to-open-vtirpc-upon/9b6cbfb6-e4d7-459a-b702-158b727d07f9

**Comment by auchri** [comment] 2017-10-26 20:07
You should suggest that to GitHub 😉

**Comment by coto** [comment] 2017-12-03 02:51
It isn’t a +1. It’s a question about how the hell someone could believe that “a person you maybe don’t remember that know JOINED TELEGRAM” it was one of the reason I stop using telegram years ago, now that I try it again I see that that very annoying notification still is there. 

I will continue using whatsapp and uninstall telegram again, and hope someday someone in telegram wake up and realize how annoying is that “Joined telegram” notification.

**Comment by mvollebregt** [comment] 2018-01-01 21:00
+1

**Comment by chmac** [comment] 2018-02-10 10:41
I guess this “feature” is not specific to any individual platform. I use telegram across iOS, Android and MacOS and I get notifications on all of them. Worse, every new “conversation” must be deleted individually on each platform. :-(

**Comment by thekrotek** [comment] 2018-02-10 10:58
@chmac on Android you can turn it off in Settings -> Notifications and Sounds, Contact joined Telegram option. Most likely you can do the same for iOS.

**Comment by stek29** [comment] 2018-02-10 23:23
@thekrotek nah, you can't on iOS afaik.

**Comment by sciurius** [comment] 2018-06-01 15:43
Neither you can in the linux desktop client.

**Comment by spenat28** [comment] 2018-09-19 21:00
I don't like event the fact, that i cannot disable this option, to notify others, that i am using it ...
Sorry, but shouldn't this thing be about security?
This is not secure ...

**Comment by sciurius** [comment] 2018-09-20 06:14
Notifications are only sent to people that have your mobile number in their contact lists. Since I do not want people to know my (secret) mobile number, I bought a cheap SIM and used that number, that noone knows, to activate Telegram. Augmented privacy for a couple of bucks per year.

**Comment by dharamsk** [comment] 2018-12-14 21:15
I use telegram to message a single friend, but telegram constantly spams me with soandso joined, who's someone in my contacts I went to school with a decade ago and haven't spoken to since... sigh..

**Comment by sabbour** [comment] 2019-03-19 17:21
Why is this still an issue?

**Comment by dharamsk** [comment] 2019-04-06 05:45
Lol I literally forgot that I searched for a solution to this on iOS. I'm now on Android and unchecked the setting and wondering again WTF I still get push notifications for it? Is this some kind of annoy the user growth strategy?

I would delete the damn app but it's the only one a close friend uses..

**Comment by dharamsk** [comment] 2019-04-06 05:52
I just unchecked "sync contacts" and deleted all my contacts from telegram servers (option in settings). This might help prevent these, we'll see...

**Comment by Soxo2** [comment] 2019-04-07 20:10
iOS Telegram now has option in Settings -> Notifications and Sounds -> "New Contacts".
- Receive push notifications when one of your contacts becomes available on Telegram.
Alleluia!!!!

Will see if it works. Finally!

**Comment by thekrotek** [comment] 2019-04-08 09:19
@Soxo2 This option exists in Windows for quite a while already, but it doesn't work. I keep getting these stupid notifications. Also it stopped working in Android recently. I really hate this option and can't imagine anybody actually using it.

**Comment by thekrotek** [comment] 2019-04-08 09:21
@dharamsk This option should work regardless of syncing settings. It just doesn't work anymore, notifications pop every time.

**Comment by yurikoles** [comment] 2019-04-12 09:13
Doesn't work for me on macOS. I see contact join notifications regardless of this option.

**Comment by john-preston** [comment] 2019-04-12 09:32
@yurikoles The message about joined contact is always there, but in case the option is disabled you shouldn't see toast /notifications / hear sound notifications.

**Comment by thekrotek** [comment] 2019-04-12 09:37
@john-preston Nobody wants this stupid notification in any form.

**Comment by yurikoles** [comment] 2019-04-12 09:42
@john-preston

But I see a badge next to telegram icon in dock. That forces me to check for unread messages.

**Comment by chmac** [comment] 2019-04-12 09:54
There are a lot of people subscribed to this issue, if you do not have something substantiative to add to the issue, please refrain from posting a comment. This is an open issue, might or might never be resolved, please +1 on the top if you want to add support, but there's no need to write more text.

**Comment by Pash237** [comment] 2019-04-17 09:50
You can turn notifications both in iOS and Android, see screenshots.

iOS:
![IMG_0F0A6767212E-1](https://user-images.githubusercontent.com/277626/56278451-ef13cf00-610e-11e9-8499-3c8c5ea02868.jpeg)

Android:
![Screenshot_20190417-124215](https://user-images.githubusercontent.com/277626/56278454-ef13cf00-610e-11e9-9dd4-7b3025a21390.png)

What we need now is to disable this stupid new chat creation for every contact joined Telegram.
All the contacts we want to talk to are already there, I'm not going to talk to a person I added to my contact list 10 years ago and never talked since then.

**Comment by wrkc** [comment] 2019-06-24 17:08
It should be fixed since if you have thousand of contacts synced from you company address book it will flood your chat history with useless notifications.

**Comment by kaplandani** [comment] 2019-09-09 19:26
I've turned it off - but notification keeps coming. this setting doesn't work !!!

**Comment by RememberTheAir** [comment] 2019-09-10 06:19
> but notification keeps coming. this setting doesn't work !!!

I think that setting is only about the notification. If you uncheck the checkbox, tdesktop won't who any notification but you'll still find a new item in your chats list

**Comment by k1r4v** [comment] 2019-10-09 12:11
For me, problem is that Telegram keeps creating a new conversation for each new contact that joins telegram and there's no option to delete all conversations in a row. I don't believe in such lack of a basic feature in telegram!

**Comment by mrf1do** [comment] 2019-11-19 22:34
So, as i see, there's no decision. It's fail.

**Comment by rm3l** [comment] 2019-11-22 23:15
Hi Guys! Any progress on this? Thanks!

**Comment by dahacouk** [comment] 2019-12-30 09:08
Dearest @john-preston, @23rd, @auchri, sorry if you get this unwanted notification of a message on GitHub. As you can see it comes at the bottom of a long thread about unwanted notifications. We can't switch off the 'Contact joined Telegram' notification. I know you have your own priorities and your own lives to lead. I know it can be tough making decisions about what to do next. But you would sure make a lot of people happy if you could fix this. What would it take? Money? Gold? Chocolate? Love? How can we say thanks? Let us know. Hugs Daniel

**Comment by midenok** [comment] 2020-02-28 11:05
There must be an option to **block** such messages. No matter notified or not, these messages clutter my list with lots of garbage, forcing me to make some pointless job or just fuck my chat list up. I choose second and probably don't use Telegram much by this moronic cause.

**Comment by ivlukyanov** [comment] 2020-04-08 13:19
Is there already some solution to block the "Contact joined Telegram" events? Even with the notification option turned off, these events are still generated and clutter up chats.

**Comment by yurikoles** [comment] 2020-04-08 13:21
Please stop writing useless posts, a lot of people get email notifications for this issue. If you have nothing to add, then just subscribe and wait for a solution.

**Comment by dahacouk** [comment] 2020-04-08 15:29
Hey @yurikoles go easy on @ivlukyanov , eh? He was only asking a question. No need to jump down his throat. If you don't want to get GitHub emails direct to your inbox you can create a rule that sends them into their own folder which you can review at your own leisure. I would love to be able to control everyone and get them to do what I want them to do too. I'm with you bro. But sometimes you just have to breathe and let the frustration subside. I'm doing that a lot these days. It's OK. These are anxious times and we can all do with being kind to each other. Lots of love bro. 🤗

**Comment by ikhwanuddin** [comment] 2020-04-21 13:25
hey it is almost 5 years and no update regarding this issue? I already put +1 there.

**Comment by cairocoder** [comment] 2020-05-08 02:54
5 years without any improvements, why?!
It's very important addition.

**Comment by thekrotek** [comment] 2020-05-08 08:01
> 
> 
> 5 years without any improvements, why?!
> It's very important addition.

They don't give a crap, that's why.

**Comment by crunchy-brains** [comment] 2020-05-17 12:23
Telegram app desktop version 2.1.6 on Windows 10 - issue still present. 😞

**Comment by dahacouk** [comment] 2020-05-17 13:27
Is there a way we can exert some pressure? Maybe in a nice way? Do the top developers have tip jars? Do they have personal profiles we can message them on? Seems like @john-preston @23rd @auchri @ilya-fedin @RadRussianRus @mymedia2  are the latest contributors. How do we get into their good books?

**Comment by RadRussianRus** [comment] 2020-05-17 14:36
This checkbox is in Settings > Notifications is already here. 
![](https://user-images.githubusercontent.com/2903496/82151586-ca83ac80-9864-11ea-978b-1af1945adf96.png)

What's the point of issue? 🤔

**Comment by vitorbertolucci** [comment] 2020-05-17 14:54
> The checkbox for this option is in Settings > Notifications.
> ![](https://user-images.githubusercontent.com/2903496/82151586-ca83ac80-9864-11ea-978b-1af1945adf96.png)
> 
> What's the point of issue? 🤔

The point is that people don't want a new chat opening everytime a contact joins telegram, regardless of receiving a notification.

**Comment by ilya-fedin** [comment] 2020-05-17 17:26
> How do we get into their good books?

All the people you listed except the first two are just third-party contributors that do something out of enthusiasm and they cannot influence such things due to CONTRIBUTORS.md. Personally, I'm just improving Linux support.

**Comment by dahacouk** [comment] 2020-05-18 06:35
> > The checkbox for this option is in Settings > Notifications.
> > ![](https://user-images.githubusercontent.com/2903496/82151586-ca83ac80-9864-11ea-978b-1af1945adf96.png)
> > What's the point of issue? 🤔
> 
> The point is that people don't want a new chat opening everytime a contact joins telegram, regardless of receiving a notification.

And @RadRussianRus "a new chat opening" creates a notification! 😭

**Comment by RadRussianRus** [comment] 2020-05-18 07:52
Does it work like this in other official Telegram apps?

**Comment by RememberTheAir** [comment] 2020-05-18 07:53
@RadRussianRus yes

**Comment by RadRussianRus** [comment] 2020-05-18 07:55
Then it's consistent with other official apps, and should not be changed.

We're talking about official app here, after all.

**Comment by dahacouk** [comment] 2020-05-18 09:01
> Then it's consistent with other official apps, and should not be changed.

Sorry, @RadRussianRus I'm missing some logic here. This **is a request** to change the behaviour of the Telegram app**s**. If this is not the place to post such a request then where is please?

And really thank you for your time in engaging here. It's good to have someone who knows the process that engage with this issue. 🙏 🙇‍♂️

**Comment by Aokromes** [comment] 2020-05-18 09:04
> > Then it's consistent with other official apps, and should not be changed.
> 
> Sorry, @RadRussianRus I'm missing some logic here. This **is a request** to change the behaviour of the Telegram app**s**. If this is not the place to post such a request then where is please?
> 
> And really thank you for your time in engaging here. It's good to have someone who knows the process that engage with this issue. 🙏 🙇‍♂️

twitter.

**Comment by kaplandani** [comment] 2020-05-18 09:25
this is been going for ages.
There is a setting in telegram that doesn't work.
every new contact in my address book that installs telegram gives me a
notification and a line in the chats.
I don't want to chat with these people and I don't care to know that they
installed telegram.
This is bull*** behavior. people complain about this for years and nothing
is being done to fix this simple feature (BUG)
Dani

**Comment by dahacouk** [comment] 2020-05-18 09:49
So, seems like https://twitter.com/telegram may be out best bet. If anyone posts to https://twitter.com/telegram with a link to this issue please copy the link here so we can like and RT. I suggest a polite approach at first would be to our advantage. ;-)

**Comment by RememberTheAir** [comment] 2020-05-18 09:50
> There is a setting in telegram that doesn't work.

No, the settings works. As has been explained in this thread already, the settings is supposed to suppress the sound notification and _not_ to hide the chat telegram creates when one of your contacts joins Telegram

As long as the mobile clients will continue to behave like that, I'm afraid tdesktop will not be able to change this behavior just because people complain here. If we want this to change, we should bug Telegram [on Twitter](https://twitter.com/telegram) or the in-app support

**Comment by vieiramanoel** [comment] 2020-08-09 02:55
> So, seems like https://twitter.com/telegram may be out best bet. If anyone posts to https://twitter.com/telegram with a link to this issue please copy the link here so we can like and RT. I suggest a polite approach at first would be to our advantage. ;-)

https://twitter.com/warqueer/status/1292282078457933826?s=19

**Comment by hypnotoad** [comment] 2020-10-23 10:58
Hi stale bot. The user has not lost interest but has resigned on the topic that filing bug reports might eventually produce a solution after 5 years.

**Comment by kaplandani** [comment] 2020-10-23 11:18
Well. How about fixing this stupid bug already ?

**Comment by Aokromes** [comment] 2020-12-24 06:04
https://bugs.telegram.org/c/65

**Closed by Aokromes** 2020-12-24 06:04 UTC
Labels: enhancement

**Comment by kaplandani** [comment] 2020-12-24 06:09
is it fixed ?

**Comment by Aokromes** [comment] 2020-12-24 06:12
nope, it's platform wide "bug".

**Comment by dahacouk** [comment] 2020-12-24 07:15
Thanks! I have made a back-link to this issue.

**Comment by ChuVienTran** [comment] 2020-12-26 15:58
G

**Comment by RememberTheAir** [comment] 2020-12-26 23:12
Just dropping the related discussion in the new "bugs and suggestions" site: https://bugs.telegram.org/c/65

**Comment by Aokromes** [comment] 2020-12-26 23:46
> Just dropping the related discussion in the new "bugs and suggestions" site: [bugs.telegram.org/c/65](https://bugs.telegram.org/c/65)

i did when i closed

**Comment by ChuVienTran** [comment] 2020-12-27 00:10
G

**Comment by john-preston** [comment] 2021-09-23 13:41
The toasts should not appear starting with the next version.
