### ISSUE TITLE
Runtime Default Playback Device Switch

### ISSUE THREAD

**Issue by nimatrueway** [telegramdesktop/tdesktop#1741] opened 2016-03-07 09:51 UTC
I have two playback devices (my monitor speaker and my headphone) and switch between them very often, almost all other programs respond to change in default playback device. However, telegram desktop still uses **the default-playback device it recognized at load time** of the app and **does not follow the change** until I restart the program.

**Comment by diazbastian** [comment] 2016-03-07 18:56
@nimatrueway I can not duplicate your problem. Could you provide more information?
Telegram version, operating system you use, what steps must follow to replicate the bug, etc.

Cheers

**Comment by auchri** [comment] 2016-03-07 18:58
Duplicate of #418 :wink:

**Closed by auchri** 2016-03-07 18:58 UTC
