### ISSUE TITLE
Most people show as "Online" status when I return from sleep

### ISSUE THREAD

**Issue by Royal2000H** [telegramdesktop/tdesktop#1902] opened 2016-04-15 00:37 UTC
### Steps to reproduce
1. Put Windows computer to sleep mode.
2. Return from sleep many hours later.
3. Telegram desktop shows many/most friends as online.
4. Telegram then shows them as "Last seen just recently"
5. Exit Telegram Desktop completely.
6. Reopen it.
7. Online status times are what they should be.

### Expected behaviour
I except to see whether my friend is actually online or not and if not, the proper time for how recent.

### Actual behaviour
Instead it shows the friend is online when not and then shows that they were "just recently" online, which may not be true. Clicking on their profile does not update it. Restarting Telegram does fix it.

### Configuration
**Operating system:** Windows 7.

**Version of Telegram Desktop:** 0.9.42.

**Comment by matteocontrini** [comment] 2016-07-19 11:36
Duplicate of #1211, that was fixed, but introuced #2258

**Closed** 2016-07-19 15:40 UTC
