### ISSUE TITLE
Load libnotify without X too

### ISSUE THREAD

**Issue by ivyl** [telegramdesktop/tdesktop#6485] opened 2019-09-04 05:51 UTC
### Steps to reproduce
1. Run tdesktop on a Wayland (setup `QT_QPA_PLATFORM=wayland` or `wayland-egl`) on Linux
2. unset DISPLAY; telegram-desktop
3. try enabling native notifications

### Expected behaviour
This should work as libnotify does not depend on X.

### Actual behaviour
There is no "enable native notification option". 

### Configuration
**Operating system:** Fedora 30 + RPM Fusion

**Version of Telegram Desktop:** 1.8.2

**Used theme**:

<details><summary><b>Logs</b>:</summary>

```
[2019.09.04 08:39:55] Launched version: 1008002, install beta: [FALSE], alpha: 0, debug mode: [TRUE], test dc: [FALSE]
[2019.09.04 08:39:55] Executable dir: /usr/bin/, name: telegram-desktop
[2019.09.04 08:39:55] Initial working dir: /home/ivyl/
[2019.09.04 08:39:55] Working dir: /home/ivyl/.local/share/TelegramDesktop/
[2019.09.04 08:39:55] Command line: telegram-desktop
[2019.09.04 08:39:55] Executable path before check: /usr/bin/telegram-desktop
[2019.09.04 08:39:55] Logs started
[2019.09.04 08:39:55] Connecting local socket to /tmp/fb950045bca9157cf2f39f17367429a1-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2019.09.04 08:39:55] This is the only instance of Telegram, starting server and app...
[2019.09.04 08:39:55] Moved logging from '/home/ivyl/.local/share/TelegramDesktop/log_start0.txt' to '/home/ivyl/.local/share/TelegramDesktop/log.txt'!
[2019.09.04 08:39:55] Primary screen DPI: 96
[2019.09.04 08:39:55] Could not load 'ayatana-appindicator3' with version 1 :(
[2019.09.04 08:39:55] Could not load 'ayatana-appindicator' with version 1 :(
[2019.09.04 08:39:55] Could not load 'appindicator' with version 1 :(
[2019.09.04 08:39:55] Could not load gtk-x11-2.0!
[2019.09.04 08:39:55] Getting DE, XDG_CURRENT_DESKTOP: ''
[2019.09.04 08:39:55] Getting DE, DESKTOP_SESSION: ''
[2019.09.04 08:39:55] Getting DE, KDE_SESSION_VERSION: ''
[2019.09.04 08:39:55] Getting DE, GNOME_DESKTOP_SESSION_ID: ''
[2019.09.04 08:39:55] Getting DE, KDE_FULL_SESSION: ''
[2019.09.04 08:39:55] DE: Other
[2019.09.04 08:39:55] Tray Icon: Try Qt = [TRUE], Prefer appindicator = [FALSE]
[2019.09.04 08:39:55] App Info: reading settings...
[2019.09.04 08:39:55] App Info: reading encrypted settings...
[2019.09.04 08:39:55] Lang Info: Loaded cached, keys: 2486
[2019.09.04 08:39:55] Lang Error: Unexpected tag (key 'lng_call_box_status_group:count')
[2019.09.04 08:39:55] Lang Error: Unknown tag (key 'lng_manage_discussion_group_warning:visible')
[2019.09.04 08:39:55] OpenAL Logging Level: (not set)
[2019.09.04 08:39:55] Audio Playback Devices: OpenAL Soft
[2019.09.04 08:39:55] Audio Playback Default Device: OpenAL Soft
[2019.09.04 08:39:55] Audio Capture Devices: Monitor of Built-in Audio Digital Stereo (HDMI 2)
[2019.09.04 08:39:55] Audio Capture Default Device: Monitor of Built-in Audio Digital Stereo (HDMI 2)
[2019.09.04 08:39:55] App Info: reading map...
[2019.09.04 08:39:55] App Info: reading encrypted map...
[2019.09.04 08:39:55] App Info: reading encrypted user settings...
[2019.09.04 08:39:55] App Info: encrypted user settings read.
[2019.09.04 08:39:55] App Info: reading encrypted mtp data...
[2019.09.04 08:39:55] MTP Info: read keys, current: 5, to destroy: 0
[2019.09.04 08:39:55] Map read time: 5
[2019.09.04 08:39:55] TCP Error: network - Network unreachable
[2019.09.04 08:39:55] HTTP Error: network error 99 - Network unreachable
[2019.09.04 08:39:55] Export Info: Destroy top bar by controller removal.
[2019.09.04 08:39:55] Tray Icon: Using Qt tray icon, available: [TRUE]
[2019.09.04 08:39:55] Not using Unity Launcher count.
```

</details>

**Comment by ivyl** [comment] 2019-09-04 06:10
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/linux_libs.cpp#L286

```cpp
if (gtkLoaded) {
	startLibNotify();
}
```

Seems to be the culprit.

```
[2019.09.04 08:39:55] Could not load 'ayatana-appindicator3' with version 1 :(
[2019.09.04 08:39:55] Could not load 'ayatana-appindicator' with version 1 :(
[2019.09.04 08:39:55] Could not load 'appindicator' with version 1 :(
[2019.09.04 08:39:55] Could not load gtk-x11-2.0!
```

For notifications tdesktop seems to use GTK just to get [GDK-PixBuf](https://developer.gnome.org/gdk-pixbuf/) which is pixel manipulation library and should not depend on any graphical system. Even then GDK has Wayland support for a long time.

**Comment by emersion** [comment] 2019-09-04 06:20
It does *not* print "Could not load gtk-3", so I think this succeeds:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/linux_libs.cpp#L250

However it doesn't print "Library gtk functions loaded!"… And also:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/linux_libs.cpp#L110

**Comment by ivyl** [comment] 2019-09-04 06:40
Oh yeah allowing only the x11 backend explains why `gtkLoaded` is false in the end:

```cpp
	if (load(lib_gtk, "gdk_set_allowed_backends", gdk_set_allowed_backends)) {
		// We work only with X11 GDK backend.
		// Otherwise we get segfault in Ubuntu 17.04 in gtk_init_check() call.
		// See https://github.com/telegramdesktop/tdesktop/issues/3176
		// See https://github.com/telegramdesktop/tdesktop/issues/3162
		DEBUG_LOG(("Limit allowed GDK backends to x11"));
		gdk_set_allowed_backends("x11");
	}

	DEBUG_LOG(("Library gtk functions loaded!"));
	if (!gtk_init_check(0, 0)) {
		gtk_init_check = nullptr;
		DEBUG_LOG(("Failed to gtk_init_check(0, 0)!"));
		return false;
	}
```

**Comment by xvitaly** [comment] 2019-09-04 09:15
All this code should be removed and rewrited using modern DBus notifications.

**Comment by Johnnynator** [comment] 2019-09-04 10:43
Duplicate of #6199

**Closed** 2019-09-04 11:15 UTC
