### ISSUE TITLE
Image viewer breaks after resolution change

### ISSUE THREAD

**Issue by mirh** [telegramdesktop/tdesktop#1400] opened 2015-12-15 19:43 UTC
As title. 
Launch Telegram. 
Change resolution (in my case: 1920x1080 --> 1440x1080)
Open some photo. 

*Possibly* something to do with #373

**Comment by ofalvai** [comment] 2016-02-21 14:03
I think this is a duplicate of #1542

**Comment by mirh** [comment] 2016-02-21 14:25
If any, I see #1604 duplicate of this. 
But it has nothing to do with *higher* resolution. 

And I just now notice the cant reproduce tag @auchri (which seems silly tbh)
I'm on windows 7 if it can help. 
Perhaps it's something with changing resolutions with **different** aspect ratios?

**Comment by Aokromes** [comment] 2016-05-13 16:16
I have a similar/related issue, if i open one image on portrait mode and close it, i rotate tablet and open the same image it will have problems to show properly and won't fit the screen.

**Closed** 2016-06-26 17:16 UTC
Labels: bug
