### ISSUE TITLE
Linux native notifications don't set focus

### ISSUE THREAD

**Issue by GordeevArt** [telegramdesktop/tdesktop#2593] opened 2016-11-02 09:42 UTC
I use telegram desktop 0.10.19 on fedora 22 64x linux with gnome 3.16.12. I use native notifications. 

When I click on notification popup telegram window shown with chat but not focused. I cannot write before I click on chat window (I am writing on .previous window)

**Comment by auchri** [comment] 2016-11-02 09:43
Please use the template next time.

**Comment by Aokromes** [comment] 2016-11-15 18:04
https://github.com/telegramdesktop/tdesktop/issues/91#issuecomment-254016489 ? @auchri

**Comment by auchri** [comment] 2016-11-15 19:04
@Aokromes what has the comment to do with this issue?

**Comment by Aokromes** [comment] 2016-11-15 19:29
bad copy and paste XD you closed another ticket like this xD

**Comment by GordeevArt** [comment] 2016-11-17 11:56
No, it's hard to explain, but the problem is:

1. Click on popup message http://pasteboard.co/siEyaTkbT.png
2. Start typing, but nothings shown http://pasteboard.co/siGCwTgrc.png
3. It's on the previous window (text that I've written in chat) http://pasteboard.co/siHcV5fT5.png 

Sorry for side-host images

**Comment by stek29** [comment] 2016-11-17 20:00
It would be really nice to change title to something like "Linux native notifications don't set focus" or something, because it's really confusing.

**Comment by AndydeCleyre** [comment] 2016-11-22 21:00
This is a duplicate of #481, which will be 2 years old in 3 months.

**Comment by john-preston** [comment] 2016-11-22 21:03
@AndydeCleyre I would really appreciate a pull request here.

**Closed** 2016-11-22 21:04 UTC
Labels: linux

**Comment by AndydeCleyre** [comment] 2016-11-23 01:13
@john-preston I would really appreciate suddenly being able to write C++ here, as well as a sane build process using upstream Qt. I will take a look anyway. Do you happen to know where the raise/focus behavior is defined in the source?

**Comment by AndydeCleyre** [comment] 2016-11-23 06:01
@GordeevArt please make sure to check out the original bug's discussion.
