### ISSUE TITLE
Chat search functionality on Ubuntu 14.04

### ISSUE THREAD

**Issue by heihachi88** [telegramdesktop/tdesktop#316] opened 2014-12-11 18:36 UTC
Do you plan to add "search" functionality within the chat? Just like skype (ctrl+f and you can make a full text search)

**Comment by tushar-suresh** [comment] 2015-02-10 16:28
>just write your search term in the search field and let the magic happen ;)

This works.

Can we close this issue?

**Comment by joshery420** [comment] 2015-02-20 23:30
To be fair, @heihachi88 technically asked for Ctrl+F support too, which the desktop apps don't currently have.
Maybe worth marking this as a duplicate of Issue #364, just because that's received more attention.

**Comment by auchri** [comment] 2015-02-20 23:33
duplicate of #97 too

**Comment by auchri** [comment] 2015-08-14 21:46
Added

**Closed by auchri** 2015-08-14 21:46 UTC
