### ISSUE TITLE
Feature request: Disable sending link previews altogether

### ISSUE THREAD

**Issue by kenniki** [telegramdesktop/tdesktop#839] opened 2015-06-18 16:19 UTC
I don't like the link previews and would like to disable sending them altogether, not requiring me to click the X on every post anymore. Could you make that work?
I'd also like a way to disable showing the link previews for other users, but I'd prefer that to be a seperate setting.

**Comment by yuergen** [comment] 2015-06-27 13:19
This bug is a duplicate of #687.

**Closed** 2015-08-14 22:48 UTC
