### ISSUE TITLE
Interactive Emoji Crashes Telegram

### ISSUE THREAD

**Issue by Shad0w-Walk3r** [telegramdesktop/tdesktop#16994] opened 2021-09-22 17:40 UTC
### Steps to reproduce

1. Send an interactive emoji to a private chat (e.g ❤️)
2. Click on the animation
3. Switch to another chat

### Expected behaviour

Animation should stop playing and telegram shouldn't crash

### Actual behaviour

Telegram will crash immediately when you play an interactive emoji in a private chat and switch to another chat while animation is playing

### Operating system

Windows 11 Pro

### Version of Telegram Desktop

3.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment] 2021-09-22 18:02
cannot reproduce. what graphics card and drivers version?

**Comment by john-preston** [comment] 2021-09-22 20:57
@Shad0w-Walk3r Thanks for your report! This will be fixed in the next version.

**Comment by Shad0w-Walk3r** [comment] 2021-09-23 00:50
> 
> 
> cannot reproduce. what graphics card and drivers version?

After restarting telegram and flushing log file, seems like the problem has been resolved.

I'm not sure if it was because of graphic cards or anything

**Comment by john-preston** [comment] 2021-09-23 05:45
@Shad0w-Walk3r No, it just crashes only if the interaction animation is still not in the cache.

**Comment by Aokromes** [comment] 2021-09-24 13:46
https://github.com/telegramdesktop/tdesktop/commit/ec064a904db57a4b5f1efd436a90078013540019

**Closed by Aokromes** 2021-09-24 13:46 UTC
Labels: bug
