### ISSUE TITLE
2 visual bugs

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6975] opened 2020-01-07 18:44 UTC
### Steps to reproduce
First:
1. open chat with someone wait until he will come online
2. wait until he will leave telegram and get "last seen recently" status
3. see to the dialog box - online icon don't disappear until you mouse over it
![image](https://user-images.githubusercontent.com/39812401/71919448-c13b5280-3195-11ea-9c79-d2bb5acce950.png)
![image](https://user-images.githubusercontent.com/39812401/71919452-c3051600-3195-11ea-9051-2dcb193b0f63.png)

Second:
1. disable animation, enable auto download for photos
2. open some chats/channels where uploaded some new photos
3. when you open the channel and photos start download — some of them can become bugged and loading round animation doesn't finish until you mouse over it
![image](https://user-images.githubusercontent.com/39812401/71919864-b03f1100-3196-11ea-8455-dc19055e48c6.png)
This happens not all time but sometimes and it's annoying.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.3

**Used theme**: tinted default

**Comment by akorb** [comment] 2020-01-20 18:01
The first point is really annoying.
A fix would be appreciated

**Comment by Jeronimo17** [comment] 2020-01-22 10:55
https://github.com/telegramdesktop/tdesktop/issues/6410

**Comment by Jeronimo17** [comment] 2020-01-22 10:55
#https://github.com/telegramdesktop/tdesktop/issues/6410

**Comment by Jeronimo17** [comment] 2020-01-22 10:56
Duplicate of #https://github.com/telegramdesktop/tdesktop/issues/6410

**Closed** 2020-01-22 11:08 UTC

**Comment by Laiteux** [comment] 2020-03-21 03:48
What about the first issue, the one about the online status bubble not disappearing until mouse hover? It's been a while I'm waiting and I frequently see users creating new issues about this bug.
