### ISSUE TITLE
Videos are uploaded as gifs

### ISSUE THREAD

**Issue by fires3as0n** [telegramdesktop/tdesktop#24247] opened 2022-03-24 12:41 UTC
### Steps to reproduce

Upload short video

### Expected behaviour

When I upload video, I want video to be uploaded with fullscreen, play, pause buttons.

### Actual behaviour

Video is converted to small gif - like cycled animation. If I want to upload gif - I will upload gif myself, why doing unnecessary things? - This is unexpected.

### Operating system

any

### Version of Telegram Desktop

latest

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment] 2022-03-24 13:47
Duplicate of #23934/#2053 - unfortunately this is the intended behavior. Such issue should be brought to httsp://bugs.telegram.org

**Closed** 2022-03-24 21:02 UTC
Labels: bug
