### ISSUE TITLE
flatpak not starting - Linux Ubuntu 18.04.6 LTS - NVidia driver ver 390.157

### ISSUE THREAD

**Issue by JazzTp** [telegramdesktop/tdesktop#27197] opened 2023-12-06 22:31 UTC
### Steps to reproduce

1. installed [as recommended](https://flathub.org/apps/org.telegram.desktop) (I didn't install as sudoer, should I have?)  
    ```
    flatpak install flathub org.telegram.desktop
    ```
2. launched as recommnded in the above linked page
    ```
    flatpak run org.telegram.desktop
    ```
    

### Expected behaviour

I'd expect it to start just fine.

I have non-flatpak Telegram desktop ver 4.4.1 running fine (but the latest requires GLIBC-2.28 which is unavailable on this pretty old Ubuntu system).

I have **other flatpak programs running fine** (which wouldn't run as normal binaries because they also require GLIBC-2.28).

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/8016573/0999f8a1-a0ba-4c3e-96f0-fad03ae3fa3c)

If I click on "Keep Disabled" nothing happens, "action" only starts again by clicking "Enable".

Console output:

```
$ flatpak run org.telegram.desktop
Gtk-Message: 19:01:46.690: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:01:46.690: Failed to load module "canberra-gtk-module"
Fontconfig error: Cannot load config file "/run/host/font-dirs.xml": No such file: /run/host/font-dirs.xml
Qt: Session management error: Could not open network socket
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
Gtk-Message: 19:02:08.522: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:02:08.524: Failed to load module "canberra-gtk-module"
Fontconfig error: Cannot load config file "/run/host/font-dirs.xml": No such file: /run/host/font-dirs.xml
Qt: Session management error: Could not open network socket
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
*** stack smashing detected ***: terminated
$
```

+ As for **"Could not open network socket":** I am online, I opened for output to any destination IP (I opened the firewall to the most permissive settings, everything else is working fine; non-flatpak Telegram desktop also works fine with my _usual_ firewall settings).

+ As for OpenGL (see screenshot above): no other program is complaining about that here, including the ones I have installed as flatpak.

### Operating system

Linux Ubuntu 18.04.6 LTS - NVidia driver ver 390.157

### Version of Telegram Desktop

4.12.2 ("Changes in version 4.12.2" I'm reading here https://flathub.org/apps/org.telegram.desktop)

### Installation source

Flatpak

### Crash ID

I don't see how to enter Settings to enable beta versions and issue a cheat code, since I can't launch the GUI at all.

Also, I don't find anything related with Telegram under ~/.config/

**Could anybody please point me to a **settings file**, specifically the one the flatpak version would use, where I could enable beta versions**, and to an alternative command line interface, if any, through which I might issue the necessary cheat codes, ***if*** necessary?

### Logs
Please see the above section "Crash ID".

```shell
no logs provided for now, sorry
```

**Comment by larouxn** [comment] 2023-12-08 01:01
> latest requires GLIBC-2.28 which is unavailable on this pretty old Ubuntu system

Was about to say, it appears Ubuntu 18.04 reached end of life in May of this year (2023), approximately 8 months ago. Pretty unlikely to have apps support an unsupported OS re: libraries and whatnot, as you mentioned.

EOL source: https://ubuntu.com/about/release-cycle

**Comment by JazzTp** [comment] 2023-12-08 02:36
> > latest requires GLIBC-2.28 which is unavailable on this pretty old Ubuntu system
> 
> Was about to say, it appears Ubuntu 18.04 reached end of life in May of this year (2023), approximately 8 months ago. Pretty unlikely to have apps support an unsupported OS re: libraries and whatnot, as you mentioned.
> 
> EOL source: https://ubuntu.com/about/release-cycle

Yes long due upgrade, plenty of things to do and plenty of stuff I'm still using on this PC as it is.

But that's what flatpak normally overcomes, as I said I have other programs requiring GLIBC-2.28 and their flatpak distribution works just fine.

Anyways, you certainly have priorities, I reported just in case it serves (no problems for me, I've already connected another disk to put a new OS on it, a few others I know might not sort it out as quickly but as I said you certainly have priorities).

**Comment by lifehackerhansol** [comment] 2023-12-09 04:12
Snap package also appears to be broken with the same behaviour, on Ubuntu 23.10, with Nvidia 525/535.

Note that, after a few tries, it'll eventually hang for 30 seconds and then appear, and proceed to do absolutely nothing (no QR shows up, phone number input does nothing, etc). Launching the Snap or flatpak package from command line shows the same behaviour.

The not-containerized version of Telegram works perfectly, but also I'm a bit too lazy to set up a `.desktop` for it.

**Comment by ilya-fedin** [comment] 2023-12-10 00:03
Folks, please stop mixing various issues here. The first post of the issue is about non-working 'keep disabled' button. If your problem is not with the button, you don't have _this_ issue.

**Comment by ilya-fedin** [comment] 2023-12-10 00:03
> The not-containerized version of Telegram works perfectly, but also I'm a bit too lazy to set up a `.desktop` for it.

This is done automatically, you don't have to do that.

**Comment by ilya-fedin** [comment] 2023-12-23 18:39
Should be fixed by https://github.com/telegramdesktop/tdesktop/commit/4337f0b509af00839aa21c4ac5aaa3b88e271c90

**Closed** 2023-12-23 18:43 UTC
Labels: bug

**Comment by Samirako3d** [comment] 2023-12-30 05:23
From Flatseal Enable D-Bass System Bus and it will work

**Comment by ilya-fedin** [comment] 2023-12-30 05:27
I don't think this really can help cause tdesktop doesn't use the system bus
