### ISSUE TITLE
Support formatting text (bold, italic...) without bots thru user interface

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#2847] opened 2017-01-13 21:50 UTC
Now both Ios and Android version support formatting without bots and thru user interface!
Exotic android versions (like MIUI), that have own selection menu, doesn't support this with interface, but at least we can use ** and __ (and in webogram too).
Tdesktop where it most needed, and where it can (and **must**!) be most user friendly, doesn't have this functionality!!! Please, finally, integrate text formatting thru user interface and without bots :)

**Comment by stek29** [comment] 2017-01-16 17:33
yay, duplicates :)

**Comment by auchri** [comment] 2017-01-16 17:34
@stek29 of?

**Comment by stek29** [comment] 2017-01-16 21:46
@auchri the closed #330?
It's intended, just because old one was closed.

**Comment by MasterGroosha** [comment] 2017-01-17 12:08
@stek29 This shouldn't be considered as duplicate IMO since #330 was opened in late 2014 when no official clients had Markdown support without bots.  
Now Android, iOS and Webogram support it.

**Comment by Turby3Pots** [comment] 2017-01-19 21:18
how to strike thru that's what iwanna know

**Comment by MasterGroosha** [comment] 2017-01-19 21:53
@Turby3Pots Not possible

**Comment by Flam1ngDem0n** [comment] 2017-02-07 19:55
Has this been resolved/fixed? Or is the desktop version still without text formatting without the requirement of using a bot?

**Comment by kirsan31** [comment] 2017-02-07 20:00
@Flam1ngDem0n still not implemented :(

**Comment by Flam1ngDem0n** [comment] 2017-02-11 11:46
@kirsan31 
That's a bummer. Hopefully it will be added some time soon.

**Comment by TheBestPessimist** [comment] 2017-03-22 09:03
+1 for this fieature

**Comment by KAMiKAZOW** [comment] 2017-03-23 14:42
Unicode supports strikethrough text and pasting that into Telegram works just fine. Try it out using http://adamvarga.com/strike/

Unicode features should, IMO, exposed via the desktop environment (like they support Asian characters), so that all applications can benefit equally.
![screenshot from 2017-03-23 15-40-23](https://cloud.githubusercontent.com/assets/3259076/24253004/5d164858-0fdf-11e7-889d-e357712d6203.png)

**Comment by sedovalx** [comment] 2017-05-03 15:01
Actually it would be nice to extend the support for code blocks on the desktop client stretching the code blocks on the whole available screen width.

**Comment by dangranos** [comment] 2017-05-09 09:16
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/ui/text/text_entity.cpp#L34
That seems to store a huge regular expression dealing with `` `code` `` blocks (actually called `pre`). If you `CTRL+F` if further down, you can find the logic that seems to control the actual formatting in the message or something like that... And it seems that the code is very repetitive even with only code blocks 
Point is, adding the rest of markdown (`*italics*, **bold** and [links](google.com)` at least) is going to be be either tons of almost-same-code or rewriting this part.

**Comment by iansowinski** [comment] 2017-05-09 13:32
Aren't there any markdown libs for cpp? Rewriting this part with it should be much easier.

**Comment by dangranos** [comment] 2017-05-09 13:35
How exactly that would make it easier? It will add another library and will
require a way to translate its data into TG data. The only way i see it is
rewriting parser to be more generic. Maybe look at what the web telegram is
doing?

**Comment by igorsantos07** [comment] 2017-05-30 22:59
So the issue is fear of writing long regexp to discover whether a message has **bold** or _italics_ formatting, because the `code fence` was complicated enough? Is it "just" this? (not joking, but trying to summarize the current problem).

This is expected for ages in Telegram Desktop, the best client but that still doesn't support that, for no reason from the user's pov.

**Comment by dangranos** [comment] 2017-05-31 01:11
Regular expression is the easiest part here, so no, it's not the problem.
The problem is the parsing code that uses those expressions, it's a bit
further down in the same file. Even with just the code blocks there's a
very high amount of duplicating code. And adding anything more either means
adding /more/ of the duplicating code, or redoing the parser to be more
generic.

**Comment by stek29** [comment] 2017-05-31 01:57
@dangranos It parses links while typing to show previews, but it doesn't work so well and looks like a hack.

**Comment by dangranos** [comment] 2017-05-31 02:06
@stek29 Yeah, that seems to be a bunch of hacks made at different time, with some ducttape over this. The main parsing loop itself [here](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/ui/text/text_entity.cpp#L1448) seems to do the parsing by constantly pushing the start of substring to match forward and then matching ALL of the regexps.

This can be replaced by a finite-state machine. Would get rid of regexps and maybe make it a bit faster (I mean, the regexp matching isn't the cheapest operation, no?). Though that means analyzing the current code and noting down all the possible ways it should go *and* add markdown to this.

**Comment by dangranos** [comment] 2017-05-31 02:36
@john-preston Supposing in the future I, or someone else, will redo the parsing code in *any* (sane) way, and then make a Pull Request, will such PR be accepted? Or are there some specific rules or requirements for PRs? (Other than standard "it must compile" and "don't break everything")

**Comment by stek29** [comment] 2017-05-31 03:13
@dangranos I'm pretty sure it would.
Also, in case someone does this, please parse them as links (while user is typing) -- it would help a lot with #3232. So don't do it in text_entity, do it in flattextarea. Or make flattextarea store text_entity internally.

Btw, speaking of hacks. `~` symbols use different font than other symbols. That's intended and fixes #27, which is OpenSans' issue imo.

**Comment by john-preston** [comment] 2017-05-31 08:28
@dangranos The problem with markdown will be not only the initial parsing, but also applying it back and forth when you edit such message.

**Comment by ksmirenko** [comment] 2017-05-31 09:46
@john-preston What about the Android Telegram app? Both editing and bold/italic formatting work there very well. How is Telegram Desktop different?

I agree that supporting Markdown fully would be challenging, but the initial issue was about bold/italic formatting, which is already supported in the mobile apps.

**Comment by dangranos** [comment] 2017-06-01 12:02
@john-preston Isn't that fixable by adding the formatting symbols around the parts of text that should be bold/italics/etc, and then passing that down to whatever is responsible for displaying and editing the text?

**Comment by stek29** [comment] 2017-06-01 13:27
@dangranos or just passing text along with it's formatting information.

**Comment by dangranos** [comment] 2017-06-01 13:32
Or just use plaintext to transmit message and parse/format it on client
side without the weird message structures that you must convert from and
to. But alas, that's not something that can be done.

**Comment by stek29** [comment] 2017-06-02 05:16
@dangranos I meant passing between different classes in app, not passing to server.

**Comment by Rostgnom** [comment] 2017-06-11 01:30
I'd just like to add my voice to this, +1. I am so distraughtly missing my markdown on the most appropriate device, and end up opening the web client, editing and reposting my messages every time... I'm not proficient in C++, but I would assume that finding another library for this job, even if it blows up the project, couldn't hurt and shouldnt be too hard :disappointed:

**Comment by nyuszika7h** [comment] 2017-06-30 17:09
@iansowinski 

> Aren't there any markdown libs for cpp? Rewriting this part with it should be much easier.

That wouldn't work, because Telegram uses its own incompatibl version of Markdown. Standard Markdown uses `**bold**` / `__bold__` and `*italic*` / `_italic_`.

**Comment by stek29** [comment] 2017-06-30 20:21
@nyuszika7h using external library won't work indeed, but for different reasons.

**Comment by Rostgnom** [comment] 2017-07-02 17:36
@nyuszika7h That doesn't strike me as much of an issue, you can always adjust the tree parser to use Telegram's markdown instead of the official version...

@stek29 Could you elaborate on the different reasons?

**Comment by stek29** [comment] 2017-07-02 19:56
@Rostgnom because the issue is not about not being able to parse markdown -- writing simple regex based parser would take less than 10 minutes.
The issue is about how telegram (and tdesktop) handle parsing -- it's done through entities of different types, with offset+length.
But TDesktop's code in this part needs to be rewritten -- parsing is done multiple times, code is duplicated in field, message sending and maybe somewhere else. And parsing links while typing made it even worse.
You can easily allow formatting with bold/italic in the same way as monospace, but that would make everything even worse. The code needs to be rewritten, and it won't be easy -- no matter if you use some third party parser or not.

Btw, issue with adding ```` ``` ```` on each line is also related -- if I understand correctly, that's done to workaround splitting into text blocks.
Also, you should keep possibility of message editing in mind, as Preston said.
This should also integrate with link parsing, spellchecking, drafts and many other things.

So this issue report is much deeper than "monkey code more regexes", it's about complete rewrite of everything related to entities and formatting. And there are too many edge cases and stuff only Preston (or even nobody) knows.

**Comment by kirsan31** [comment] 2017-07-06 18:58
First step:

> Alpha 1.1.11.
> - Send **bold** and __italic__ text in your messages (in addition
> to already supported `monospace` and ```multiline monospace```).

**Comment by Rostgnom** [comment] 2017-07-06 22:17
@stek29 Thank you for providing this insight! I noticed there has been done something https://github.com/telegramdesktop/tdesktop/commit/f6eccf85dcb7e26681369659baa0eece0afb2b50

**Comment by auchri** [comment] 2017-07-07 06:25
Fixed in latest alpha version.

**Closed by auchri** 2017-07-07 06:25 UTC
Labels: enhancement

**Comment by jez9999** [comment] 2018-12-30 11:04
This doesn't seem fixed to me.  I can't use any Markdown in the Telegram desktop client.

**Comment by TheBestPessimist** [comment] 2018-12-30 11:43
As per the spec https://commonmark.org/help/ it should be
```
_italic_ and NOT __italic__
```
(please observe the single underscore).

This is how every markdown-powered platform i know works (check right here on github!)

**Comment by nyuszika7h** [comment] 2018-12-30 11:46
I don't know why Telegram chose to use double characters, but there seems to be no way to escape Markdown in the official clients so that may be part of the problem. The API uses the normal Markdown syntax internally and escaping works too. Also note that Telegram doesn't support nested formatting (this includes links).

**Comment by stek29** [comment] 2019-01-04 09:07
> The API uses the normal Markdown syntax internally and escaping works too. 

Nope, it doesn't. BotAPI isn't the API used by everything else (actually, BotAPI is just a "proxy" for normal mtproto API). And BotAPI markdown isn't a popular flavor, tbh.

Initially when one character markdown was introduced, a lot of people who had no idea about what markdown or escaping is started complaining that their * highlights turn into bold text. That's why double characters are used.
