### ISSUE TITLE
Reconnect after laptop sleep

### ISSUE THREAD

**Issue by robertfoss** [telegramdesktop/tdesktop#607] opened 2015-03-27 23:00 UTC
After my laptop resumes, the telegram client will no longer receive any new messages.

To receive new messages the client has to be killed and restarted.

I'm on Ubuntu 14.04

**Comment by kireledan** [comment] 2015-03-27 23:25
This happens to me as well. Im running Arch.

**Comment by skyjack** [comment] 2015-03-30 16:22
The same for Win8.1: status "connecting...".
W/a: restart Tg.

**Comment by basheersubei** [comment] 2015-03-30 17:09
+1

Have to restart application on Ubuntu 14.04 as well

**Comment by basheersubei** [comment] 2015-03-30 17:10
I believe this is a duplicate of #536

**Comment by Foodfast** [comment] 2015-04-03 19:53
+1 Very annoying issue. Linux Mint 17.1, Arch.

**Closed** 2015-08-14 23:11 UTC
