### ISSUE TITLE
Windows 10: Interface scaling should adjust to current monitor's setting in 'Auto' mode

### ISSUE THREAD

**Issue by xfeldman** [telegramdesktop/tdesktop#1694] opened 2016-02-26 17:06 UTC
Multi-Monitor setup.

 When Telegram's Interface Scaling is set to 'Auto' mode, scaling does not get auto-adjusted when Telegram window is moved between monitors with different scaling settings.

**Comment by telegramdesktop** [comment] 2016-02-26 17:07
@xfeldman Yes, currently this is a per-launch setting, it can't be changed in runtime :(

**Comment by xfeldman** [comment] 2016-02-26 17:10
Is there a chance to add a manual 175% setting then? Otherwise telegram window looks awkward on one or the another monitor in Surface Pro + 4K external monitor setup.

**Comment by PrzemekBurczyk** [comment] 2016-02-27 09:59
The same for me, it makes it unusable on multi-monitor configuration with different per-monitor scaling like 4k (200%) + Full HD (125%). It's either microscopic on 4k or enormous on Full HD.

**Comment by karlobencic** [comment] 2016-04-02 12:44
Still not solved, can't use telegram on multiple monitors with different scale set in Windows 10 screen settings.

**Comment by lpatiny** [comment] 2016-04-24 05:25
I would also really like that the interface scale can go to 300% like in windows 10. Those new high resolution screen yield really to small text in telegram.

**Comment by auchri** [comment] 2016-04-25 08:18
This will be possible with the new version of qt: http://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by john-preston** [comment] 2016-04-25 08:48
@auchri It won't be out of box, though. Currently tdesktop is designed to have only one scale per launch (all the style dimensions, sprites, emoji pixmaps are prepared once and never change).

**Comment by hdd1013** [comment] 2016-05-11 00:55
+1 for this issue. It will be much better with per-monitor DPI support

A reference document:
https://www.google.co.kr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjb7Oan59DMAhVCEpQKHbUWAiIQFggbMAA&url=https%3A%2F%2Fmsdn.microsoft.com%2Fen-us%2Flibrary%2Fwindows%2Fdesktop%2Fee308410(v%3Dvs.85).aspx&usg=AFQjCNEUNzWk3lKbD9vLXKFZQg5KaduP_g&sig2=q0I0xept_WUH_pQOm5P8kQ&bvm=bv.121421273,d.dGo&cad=rjt

**Comment by thepting** [comment] 2016-05-13 02:23
Yeah, this is really killing the usability for me at work.  I have to relaunch every time I dock or undock.  Hopefully something can be done to help.

**Comment by auchri** [comment] 2016-06-24 14:35
Duplicate of #1121

**Closed by auchri** 2016-06-24 14:35 UTC
