### ISSUE TITLE
Tray icon on non unity linux window managers doesn't have transparent background anymore

### ISSUE THREAD

**Issue by alferpal** [telegramdesktop/tdesktop#492] opened 2015-02-18 08:12 UTC
Hello and thanks for developing telegram desktop.

I just updated from 0.7.13 to 0.7.16 and found that the tray icon used to have a transparent background or seemed to have and in 0.7.16 it doesn't. 

It just displays a white box around the telegram icon which looks rather strange in the trayer on my window manager.

I'm using Arch Linux, DWM with the systray patch ( among others, but I guess only the systray is relevant in this issue) as window manager

**Comment by Lachmoewe** [comment] 2015-02-18 10:57
Same problem here with Ubuntu 14.10 and awesomeWM v3.4.15

**Comment by tushar-suresh** [comment] 2015-02-18 16:24
+1 . Using Ubuntu 14.04 with xfce.

**Comment by telegramdesktop** [comment] 2015-02-19 07:05
Many messages about better working icon through QSystemTrayIcon instead of libappindicator, so I've left libappindicator only for Unity. After some more reports I saw I should return libappindicator in p
Pantheon and perhaps some others. Can you please tell what does "echo $XDG_CURRENT_DESKTOP" tell you in Terminal so I could switch back from QSystemTrayIcon to libappindicator in your case?

**Comment by alferpal** [comment] 2015-02-19 07:18
It reports nothing in my case because I'm only using a window manager, not a desktop environment:

0 akai@Arch-Akai: ~ 8:16 ---> echo $XDG_CURRENT_DESKTOP

0 akai@Arch-Akai: ~ 8:16 --->

**Comment by telegramdesktop** [comment] 2015-02-19 07:49
And how can I separate your case from all the others? Maybe some other env-var that will name your window manager? Because I can't use libappindicator everywhere (many issues about menu-only tray icon that does not activate the app by click etc), and I can't use Qt tray icon everywhere too.

**Comment by alferpal** [comment] 2015-02-19 08:16
I'm trying to find if there's any env variable set by DWM, awesome and such, but for now no luck

**Comment by telegramdesktop** [comment] 2015-02-19 09:50
The problem is current issue: I use Qt tray icon class right now for all not Unity environments - and this issue comes up.

**Comment by tushar-suresh** [comment] 2015-02-19 15:23
XDG_CURRENT_DESKTOP should be used. In cases where it fails, you could grep the output of XDG_DATA_DIRS for presence of 'unity'.

Source: http://unix.stackexchange.com/a/116694

**Comment by nicklan** [comment] 2015-03-05 19:33
I also have a non-transparent background now.  And for non-standard desktops all the current suggestions are broken.  Not sure what the right way forward is, but for example, here's my situation:
```
XDG_CURRENT_DESKTOP=i3-agent
XDG_DATA_DIRS is empty
DESKTOP_SESSION=i3-with-ssh-agent
```

Also, starting with:

```
DG_CURRENT_DESKTOP=GNOME  DESKTOP_SESSION=gnome
```

causes telegram to segfault now:

```
DG_CURRENT_DESKTOP=GNOME  DESKTOP_SESSION=gnome telegram
libs init..
/usr/bin/telegram: line 2:  4370 Segmentation fault      (core dumped) ./Telegram
```

Let me know if I should open that as a separate issue.

**Comment by dkadashev** [comment] 2015-04-08 09:53
I have this problem as well. AwesomeWM 3.5.5.

But WM is probably irrelevant, seems it's a QT problem: https://bugreports.qt.io/browse/QTBUG-35832?attachmentOrder=desc

**Comment by hobarrera** [comment] 2015-07-05 03:16
Detecting the desktop/wm explicitly is probably a bad idea because you'll never be able to list every single existing one (you'll just get into more trouble down the road).

Detecting appindicator support might be a better choice, and I believe this can be done independently of DE/WM.

I tried to follow the code around to find the source of the issue myself, but my C++/Qt skills are insufficient for this, regrettably. :(

**Comment by hobarrera** [comment] 2015-07-06 17:34
#874 (a duplicate of this issue), has a few more details regarding this issue. For example, it's not reproducible when using compositing window managers.

**Comment by ewnd9** [comment] 2015-07-12 09:08
+1 (Ubuntu 14.04, Awesome 3.4.15)

**Comment by dkadashev** [comment] 2015-07-16 06:37
Seems to be fixed in v0.8.39 dev (probably because qt 5.5 is used now)

**Comment by hobarrera** [comment] 2015-07-16 08:56
@dkadashev 

I could not confirm this, since building failed for me with the latest from master:


```
In file included from ../../Telegram/SourceFiles/gui/text.h:55:0,
                 from ../../Telegram/SourceFiles/stdafx.h:64:
../../../Libraries/QtStatic/qtbase/include/../../../QtStatic/qtbase/src/gui/text/qfontengine_p.h:52:35: fatal error: private/qtextengine_p.h: No such file or directory
compilation terminated.
Makefile:2781: recipe for target '../DebugIntermediate/Telegram.gch/c++' failed
make: *** [../DebugIntermediate/Telegram.gch/c++] Error 1
```

Are you building that? Did you encounter that issue as well? I'm not seeing any tags for specific versions though. :-(

**Comment by dkadashev** [comment] 2015-07-16 09:12
@hobarrera, I didn't build it from source. Used the latest dev build from here: https://desktop.telegram.org/

**Comment by hobarrera** [comment] 2015-07-18 10:26
@dkadashev 
Seems to be down at the moment, regrettably. I'll retry later, though master is still failing to build for me. :-(

**Comment by alferpal** [comment] 2015-08-03 08:17
Building from source using the latest available stable version in Arch Linux's aur ( https://aur4.archlinux.org/packages/telegram-desktop/ ) this appears to be solved.

Should I close?

**Comment by kittee** [comment] 2015-08-03 08:47
Yes, seems like it is completely solved

**Closed** 2015-08-03 09:15 UTC
