### ISSUE TITLE
CTRL+Shift+M doesn't work

### ISSUE THREAD

**Issue by kvrvgv** [telegramdesktop/tdesktop#27461] opened 2024-02-08 13:29 UTC
### Steps to reproduce

1. Write text
![image](https://github.com/telegramdesktop/tdesktop/assets/50778263/6cac807d-9464-4c38-af6f-1edb66761abf)
2. Press CTRL+A to select *
![image](https://github.com/telegramdesktop/tdesktop/assets/50778263/507daaa7-d195-4179-8b2e-aa5a6aa0baf2)
3. Press CTRL+Shift+M
![image](https://github.com/telegramdesktop/tdesktop/assets/50778263/cd19a1c8-94e5-42dc-9af9-2f0ab34c332f)
4. Nothing happened

### Expected behaviour

The text should become monospacedThe text should become monospaced

### Actual behaviour

Nothing... but CTRL+B or CTRL+I or any other combos works correctly

### Operating system

Windows 10 Enterprise LTSC Release Version 21H2 Installation date 28.01.2024 OS build 19044.3570

### Version of Telegram Desktop

4.14.13 x64

### Installation source

Static binary from official website

### Crash ID

-

### Logs

```shell
-
```

**Comment by Aokromes** [comment] 2024-02-08 15:37
works for me (TM)

**Comment by ilya-fedin** [comment] 2024-02-08 16:03
#4977?

**Comment by singlanitin661** [comment] 2024-02-09 17:00
Please assign this to me. I will look into it.

**Comment by ilya-fedin** [comment] 2024-02-09 17:05
@singlanitin661 why can't you look without assigning?

**Comment by john-preston** [comment] 2024-02-16 13:19
I can't reproduce too. Maybe the combination doesn't reach Telegram process 🤔

**Comment by ilya-fedin** [comment] 2024-02-16 13:23
@john-preston it might be a duplicate of #4977 (where it's known that only exact advanced layouts trigger such behavior, read the comments) although the reporter has never acknowledged that

**Closed** 2024-02-24 00:16 UTC
Labels: bug, cant reproduce
