### ISSUE TITLE
Spellchecker dictionary is not case-insensitive

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#6776] opened 2019-11-11 08:05 UTC
I'm not sure whether I should post this issue here or in [lib_spellcheck](https://github.com/desktop-app/lib_spellcheck) repo.

### Steps to reproduce
1. Write a word which is not currently in dictionary
2. Add it to dictionary
3. Write the same word with some letters in another case (for example, in the beginning of sentence)

### Expected behaviour
Spellchecker should be case-insensitive (not 100% sure, though) and both "Word" and "word" should be treated the same when doing a spell check.

### Actual behaviour
![изображение](https://user-images.githubusercontent.com/2780044/68570841-9ae98700-0472-11ea-8120-fcb6eb208e93.png)
![изображение](https://user-images.githubusercontent.com/2780044/68571073-2cf18f80-0473-11ea-8c68-79482e54af28.png)

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.9.1

**Comment by 23rd** [comment] 2019-11-11 08:52
That is how Windows API works.
Firefox and Chrome work the same way.

**Comment by MasterGroosha** [comment] 2019-11-11 09:14
Oh, okay then. So, should I close the issue as wontfix?

**Comment by 23rd** [comment] 2019-11-11 23:15
This is not "wontfix", this is the intended behavior for the system spellchecker in Windows.
Perhaps this will be different with a custom spellchecker.

**Closed** 2019-11-25 14:41 UTC
