### ISSUE TITLE
Image preview is not working for images hosted on my server

### ISSUE THREAD

**Issue by efahmad** [telegramdesktop/tdesktop#3844] opened 2017-08-29 10:51 UTC
### Steps to reproduce
1. When I paste an image URL to input field of telegram Desktop, I can see a preview for it immediately. (e.g http://media.farsnews.com/media/Uploaded/Files/Images/1396/06/07/13960607001150_PhotoB.jpg)
2. But when I paste an image URL hosted on my server, telegram doesn't show any preview. (e.g http://84.241.52.6:8092/inojoom-pics/file_3.jpg) While i can see this image in browser.
3. Should I do any specific  configuration in my Nginx server in order to see telegram preview for my images ?

### Expected behaviour
An image preview should appear in the Telegram message.

### Actual behaviour
Only the URL to the image is being shown, no preview will ever show up.

### Configuration
**Operating system: Windows 8**

**Version of Telegram Desktop: 1.1.19**

**Comment by stek29** [comment] 2017-08-29 12:25
Do you see any requests from Telegram servers in logs?
Probably it's a bug related either to lack of domain, or to port number being not 80/443.

**Comment by stek29** [comment] 2017-08-29 12:26
This is most likely not related to TDesktop, but I'll close it once you find the problem and report to server side devs.

**Comment by 733amir** [comment] 2018-08-23 10:52
I am having the same problem here.

There is no preview for my image when posting the link on telegram.
The image is hosted on:
http://188.166.165.184/cloud/store/AgADBAADiq0xG5vA8VOaRuuF1o9DK3RQNBoABKMBI2a4dg-Xy5MFAAEC.jpg

@stek29 I checked what you asked and there was no request from telegram servers.

**Comment by stek29** [comment] 2018-08-27 21:27
@733amir try to get a hostname

**Closed** 2018-08-27 21:28 UTC
Labels: api issue

**Comment by lobit0** [comment] 2018-12-28 15:49
I can reproduce on Telegram Web using an URL with a hostname:

https://suchat.org:5443/eea8337bf704834779249f08b25ab7ea69f6fbdd/slsIkO6FL2egF2T8d4sj6zm0WeL5wA6IgLegnR4J/l_NoSGeUQF-Ju4mkTkypag.jpg

It seems that ports other than 80 or 443 aren't previewed either.

Should I open a different issue on Telegram Web's repo?

I thought I'd put it all together here, since it's tagged as an API issue.

Also: Is this the desired behaviour for previews?

If you ask me, I'd prefer it wasn't. So that Telegram groups that are connected to XMPP MUCs via bots have better UX, as uploaded files on XMPP are likely served on a port different than standard HTTP/S (at least that's the case for suchat.org, [xabber.de](https://xabber.de:5443/upload/0a439dd36287c9c7ecc99824dcdf9896d39e74ee/ivN5SOl1wwduRGHrA0rnQPJZ4wIDRbaIBSJRbZRl/2018-12-24-060742_1366x768_scrot.png) and [diaspora.com.ar](https://diaspora.com.ar:5281/upload/0ab6ecb4-cf2e-45d8-b900-9a2e591086cd/nDPkNLb3Rt6mcuXmOkODpw.jpg), the 3 chat providers I use).

**Comment by stek29** [comment] 2019-01-04 09:33
That's known server side limitation, sadly
