### ISSUE TITLE
Copied webp images from Firefox send as stickers

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#6276] opened 2019-07-11 17:34 UTC
### Steps to reproduce
1. Go to this link: https://oldschool.runescape.wiki/w/Rain_bow
2. Right click the image of the character holding the Rain bow and select "Copy Image"
3. Paste this image inside of a telegram chat and attempt to send it.

### Expected behaviour
When sending an image, it should simply be sent as an image, not a sticker.

### Actual behaviour
Sometimes when sending images, particularly if right clicking the image from a website and selecting "Copy Image" from the context menu, Telegram will send that image as a sticker. 
I believe this is unintentional because Telegram will prompt the user for a caption, even though it's sending the image as a sticker. 

The reason I know this is a bug is because when this happens, the caption you provide is discarded and if you view your stickers on mobile, you can sometimes see the image you sent in your recently sent stickers interface.

Also when attempting to click the image to view a larger version of it, it won't show an enlarged version as expected.

This doesn't happen for every single image sent via this method, but only some of them.

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 1.7.14

**Used theme**: Midnight

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by SmartManoj** [comment] 2019-07-13 11:27
Cant reproduce

**Comment by Talon876** [comment] 2019-12-05 02:45
I have this issue as well.

Operating system: Win 10

Version of Telegram Desktop: 1.8.15

Used theme: Midnight

I think it may be related to the browser also. I am able to reproduce using the same image that @classicmari mentioned when I use Firefox (version 70.0.1) but it is not reproducible using Chrome.

**Comment by ShaneIsrael** [comment] 2019-12-05 04:27
Can confirm. @Talon876 keeps sending me stickers and I have to tell him to resend them to me as a file or else I can't zoom in and actually view the content.

**Comment by hematogender** [comment] 2019-12-10 00:15
This is probably caused by your browser, Firefox, .webp images settings/behaviour. Wepb an image format optimized for web use, which is also used by Telegram for stickers. Tweak your browser settings accordingly, by disabling wepb support, for example.

**Comment by classicmari** [comment] 2020-01-21 00:05
Yeah, it's probably caused by the format being webp in Firefox. I'm unable to reproduce on Chrome or Edge with default settings. Thanks @Talon876 for creating a video that reproduces the behavior with the example I provided in the OP.

Would it be feasible to fix this on Telegram's side without the user having to tinker with their Firefox settings? That seems too much to ask for of standard users.

Interestingly, I do not have this issue with Firefox on Ubuntu/PopOS, they must use different settings for installations?

**Comment by Brawl345** [comment] 2020-03-30 09:43
Adding to this: Copying WebP images in Firefox and sending them in Webogram sends them correctly as image, not as sticker, so it's definitely something that needs to be fixed in TDesktop.

**Comment by RememberTheAir** [comment] 2020-03-30 09:46
> so it's definitely something that needs to be fixed in TDesktop

I wonder if they consider this a bug or it's designed to work like that and webogram is just outdated. It sure is annoying as hell. Tdesktop should give the option to select how to send the image, as it already happens with all the other types of pictures (send as picture/send as file)

**Comment by Akhlys** [comment] 2020-04-24 22:00
Can confirm, Firefox 75.0/Windows 10 and current TDesktop, updated just now (v. 2.1).
This is especially annoying as it happens for all reddit images (hosting server is not important, as long as they're embedded on reddit). Seeing as reddit is not particularly unknown and you might very well send images from it to your friends..

Copy Pasting to other targets like MS Paint/Gimp/etc works as expected.

@hematogender copy/pasting images being sent as stickers is obviously a bug in TG, as nothing but stickers should be sent as stickers.

**Comment by hematogender** [comment] 2020-04-27 17:51
> @hematogender copy/pasting images being sent as stickers is obviously a bug in TG, as nothing but stickers should be sent as stickers.

I absolutely agree with you, I just haven't thought about it in that way back then. The downvotes are justified 😃 I use Firefox, too, and it drives me nuts when this happens. I just take a screenshot as a workaround, but the quality worsens for sure.

Also, I tried to save such image as file, and it showed as jpg. But uploading to TG yields the sticker nevertheless. It is something to do with metadata, I guess. So I wonder if it may be a bug in Firefox... Well, an answer from the developer would be nice to clear this up.

**Comment by rarog** [comment] 2020-05-08 13:36
I can confirm the behaviour with Firefox 75 and Telegram 2.x But this was present even on older posts.

**Comment by Amunak** [comment] 2020-05-22 14:00
It's not an issue with Firefox, FFS. My theory is that Telegram overall (like, not just the desktop client, but also mobile) has very poor support for webp *as images*. It doesn't know what to do with them; desktop makes them into stickers, mobile just uploades them as a file.

### Steps to reproduce
1. Download a webp image, like [this one from WikiMedia](https://upload.wikimedia.org/wikipedia/commons/a/a1/Johnrogershousemay2020.webp).
2. Drag&Drop or "attach" the image into a Telegram chat.
3. Telegram correctly asks for a comments, as if it was a picture being uploaded.
4. Click Send.
5. The picture appears in the chat, but its styling is as if it was a sticker (the size is limited and there is no click-behavior).

### Expected behaviour
The picture, once sent, should behave like any other picture, not like a sticker.

### Actual behaviour
The webp picture behaves like a sticker.

### Configuration
Probably not relevant, but for completeness:

**Operating system:** Windows 10 18363

**Version of Telegram Desktop:** 2.1.6

**Comment by RememberTheAir** [comment] 2020-05-23 14:18
> My theory is that Telegram overall [...] it doesn't know what to do with them

It perfectly knows what to do with them: consider _every_ webp file as a stciker. The assumption Telegram does is that when an user uploads a webp file, he wants to upload it as a sticker, which is not necessarily true, and also particularly annoying when it is not. The android app initially sends `webp`s as file, but then the server probably validates is as sticker and the next time you open the chat, the app will show it as a sticker.

Unfortunately, I think this is out of the scope of possibilities of the developer of tdesktop, because of platforms consistency, although I think this kind of issue is much more common for desktop users so adding some kind of choice box would be a good thing. We should bug Telegram on [Twitter](https://twitter.com/telegram)

**Comment by Amunak** [comment] 2020-05-23 14:24
That's also a reasonable explanation; though it's something Telegram must change. Webp images are becoming more and more common on the web, and this is slowly becoming a major issue.

**Comment by Akhlys** [comment] 2020-05-23 21:58
> It perfectly knows what to do with them: consider _every_ webp file as a stciker. The assumption Telegram does is that when an user uploads a webp file, he wants to upload it as a sticker, which is not necessarily true, and also particularly annoying when it is not.

This makes no sense tho. Yes it treats webp as stickers, but you can't tell me that was ever intended/wanted. A feature, not a big, so to speak. When you actually create a sticker, you do not upload a webp file, you upload a PNG. Telegram may then convert that PNG to webp, but that is after all user interaction.

Why would you assume that sending a random file as sticker was the intended result in any situation?

My hypothesis (and this is a complete guess) because the problem seems to happen on other platforms as well:
The the sticker browser and sticker sending mechanism aren't connected, there is no dedicated command for sticker sending on the Telegram server. Instead, they thought since webp is so rare and their sticker are webp internally, they just send it as an image, and server side they probably just went quick'n'dirty "if (webp) { sticker } else {image }".
Not because that was ever intended to be used for anything but stickers but because someone was lazy.

Whatever the reason may be, I simply don't believe there is a situation where it was intended that a directly user supplied image will be sent as sticker.
And if I'm right, a quick workaround would be to just check the resolution of the webp.. "if (webp && image.h <= 512 && image.w <= 512) { sticker  } else {image }". That wouldn't be a real solution but honestly, the ticket is open since a year. Better an imperfect fix than none at all

**Comment by Aokromes** [comment] 2020-05-23 23:21
maybe a 3rd "setting" must be show when droping webp files.
Send as file.
Send as image.
Send as sticker.

**Comment by RememberTheAir** [comment] 2020-07-10 08:45
Just noticed that animated webp files like [this one](https://files.catbox.moe/m1jt2l.webp) are sent as static stickers and cannot be sent as files, making it impossible to share them through tdesktop. Beyond annoying

**Comment by skacurt** [comment] 2020-07-18 15:21
When you copy an image, Firefox creates and advanced clipboard content.

In addition to the bitmap and other stuff, a list of files object containing the image's local cache path also stored in the clipboard and I think that's what's causing the problem.

I would expect Telegram use the bitmap primarily.

The job of handling webp files as stickers must take its place only when there's no bitmap in the clipboard but a local webp file path.

**Comment by Aokromes** [comment] 2020-11-20 14:15
https://github.com/telegramdesktop/tdesktop/commit/8aafe6ba0e5d98f75236869231819a22760ec0eb

**Closed by Aokromes** 2020-11-20 14:15 UTC

**Comment by Akhlys** [comment] 2021-02-19 14:57
The bug is back on TG desktop

**Comment by flaep** [comment] 2021-02-27 18:12
@Aokromes 
The Issue is back. At least Win10 Telegram Desktop 2.6.1. Did no try another platform

**Comment by Ansem93** [comment] 2021-03-02 16:30
Can confirm, copying images from 9gag will send a sticker :(

**Comment by Brawl345** [comment] 2021-03-02 16:35
Seems like it's intentional: https://github.com/telegramdesktop/tdesktop/commit/8ec60e03214b869d5ab770daea68e5f8db5940bb
>Show all .webp as stickers.
>Allow opening stickers not from stickerpacks in media viewer.

>	// Show all .webp (except very large ones) as stickers,
	// allow to open them in media viewer to see details.

**Comment by Ansem93** [comment] 2021-03-02 16:41
wtf, not even 3 months bug free :(

**Comment by Xeddius** [comment] 2021-03-04 22:43
I'm getting so sick of this annoying and completely useless "feature", I NEVER want to send an image, webp or otherwise, as a sticker. Sticker packs and the sticker bot exist for a reason. It is single handedly the most useless and annoying feature and I can't fathom why they keep shoehorning it back in. 
### GIVE US THE ABILITY TO DISABLE THIS GARBAGE BEHAVIOR!

**Comment by ilya-fedin** [comment] 2021-03-04 23:05
> wtf, not even 3 months bug free :(

A lot of people complained on the non-sticker behavior as well: https://github.com/telegramdesktop/tdesktop/issues/8284

**Comment by Ansem93** [comment] 2021-03-04 23:07
Just put this as an option :/ As the other user said, it's incredibly annoying to send an image from 9gag or other sites just to see a useless stickers in the chat.

**Comment by ilya-fedin** [comment] 2021-03-04 23:10
> Just put this as an option

@john-preston follows "less options is better" principle, so I'm afraid this won't happen

**Comment by Ansem93** [comment] 2021-03-04 23:12
They already have both the possibility coded. They just need to revert the preview version and add a toggle in the advanced settings.
Everyones happy since advanced it's not meant for the average user.

**Comment by ilya-fedin** [comment] 2021-03-04 23:14
> They already have both the possibility coded.

I guess this is not an argument for preston...

**Comment by Akhlys** [comment] 2021-03-04 23:26
> > wtf, not even 3 months bug free :(
> 
> A lot of people complained on the non-sticker behavior as well: #8284

It seems those that complained were all bot makers. Couldn't that API-call that was mentioned, sendSticker, just resize them to the correct proportions for stickers and leave the Couldn't they just make the stickers they want to send in the correct proportions with transparent space and then handle it as when it was fixed for 3 short months?
Another option would be to add something like "hey lad this is a sticker" to the WEBP metadata (cursory look: can be XMP or EXIF, EXIF UserComment could be utilized for example) which would be set by sendSticker. Something like that.

In the end, I can't think there are more bot makers than normal users just wanting to copy paste images from some of the largest sources of images to send around that exist..

**Comment by ilya-fedin** [comment] 2021-03-04 23:28
> Couldn't that API-call that was mentioned, sendSticker, just resize them to the correct proportions for stickers and leave the fix?

> Another option would be to add something like "hey lad this is a sticker" to the WEBP metadata (cursory look: can be XMP or EXIF, EXIF UserComment could be utilized for example) which would be set by sendSticker. Something like that.

All this is could be implemented only server-side and no one transfers issues to server side developers from this repo

**Comment by Talon876** [comment] 2021-03-04 23:30
I've also noticed this behavior came back and thought I was going crazy because I thought it was fixed. Ever since its return I've sent at least a dozen "stickers" by accident, then had to notice that and go copy the full image and send that instead, and then delete the sticker message.

"Less options is better" certainly makes sense in a lot of cases, but there is already quite a bit of advanced configuration in the settings as is. For instance there's already an option about whether or not stickers should continuously animate, why not have an option right next to that for toggling this behavior? Like others in this thread, I **never** want to send a sticker that's not already in a pack, but if there are enough other users out there that like that behavior, enough that this bug was purposely reintroduced, why not make an option?

**Comment by Xeddius** [comment] 2021-03-05 02:50
Seriously, less is not more in this case. This is clearly a situation where providing a choice is significantly better. This is annoying enough for me to stop recommending telegram at all. I absolutely DESPISE this "feature". I will never send stickers outside of a pack. If people like the setting, good for them, but many like me DO NOT.

**Comment by john-preston** [comment] 2021-03-05 03:24
@Ansem93 What is the problem with posting from 9gag? It is just a bit smaller than a photo would be shown, but still could be opened by click and seen in full. It is sent without recompressing to jpeg, so even the large images with small letters would be fine when opened by click. It is better than sending as file anyway, which is the same except showing only a tiny preview in chat.

**Comment by Xeddius** [comment] 2021-03-05 03:28
@john-preston on mobile clicking to view in full-size isn't an option, so anything sent to almost everyone I chat with isn't going to be visible besides the tiny little icon. Not really practical.

**Comment by john-preston** [comment] 2021-03-05 03:29
@Talon876 Also this is consistent with mobile apps, the sent .webp images were shown as files for some time in tdesktop, but all that time mobile apps still were showing the same messages as stickers. Which confuses users more.

Like here, many guys who report it, think that SENDING changed somehow, but really only DISPLAYING of messages changed for some .webp to files and back to stickers, but that you can click to see in full size.

**Comment by john-preston** [comment] 2021-03-05 03:46
@Xeddius You see, someone here thought that for past month they were sending a file, but really a sticker for mobiles, just tdesktop was not showing them as mobile apps do.

So now the behavior at least consistent with mobile apps + you can view large files in the viewer by click.

I think I'll enable the "send compressed" option for webp, so it works like png, by sending as photo. That should be fine for everyone.

**Comment by Akhlys** [comment] 2021-03-05 07:51
> All this is could be implemented only server-side and no one transfers issues to server side developers from this repo

How about.. Couldn't webp on copy-paste, possibly before even showing the dialog, be converted to PNG? cleint side change, display the same on all platforms, problem fixed, bot makers not affected

This would be a workaround, not a fix (I still think one popular image file format being handled entirely differently than all others is wrong) but besides possibly a slight delay before the dialog opening there wouldn't be downsides I can think of right now.

**Comment by Mithgol** [comment] 2021-03-07 22:31
Sending WebP files as stickers is an old feature of Telegram [announced in January 2015.](https://telegram.org/blog/stickers#sharing-your-own-stickers)

Telegram Desktop has already become designed to display WebP files in TD's fullscreen media viewer (when the WebP file is clicked) and can also download stickers (right click → Save File As…). That already provides WebP images, were they not intended to become stickers, with much better recognition than in other Telegram clients; for example, Telegram for Android does not seem to have a fullscreen media viewer for WebP files and also does not seem to have an option for saving WebP files when they're displayed as stickers.

🯁🯂🯃 **Note:** Telegram for Android decides against displaying WebP “as a sticker” and starts showing WebP “as a file” (downloadable) if that file is large enough (over 2 MB, if I may guess? — that limit does not seem to be documented), and Telegram Desktop does the same, but that is another story.

I believe that currently (under the constraints of the previously announced feature) the client cannot be designed better than that. And also it's not just the client that should be redesigned; the whole mindset behind the feature should change (causing server-side changes as well). Telegram has to understand that the Web in 2021 (where [WebP support is almost ubiquitous,](https://caniuse.com/webp) unlike the Web in 2015) is brimming with WebP images that have never been intended to become stickers in Telegram: that images are saved in WebP just because WebP files are significantly smaller that PNG (because of WebP's better lossless compression), or because WebP files are prettier than JPEG (because of WebP's less visible artifacts of lossy compression), etc. Therefore Telegram should let its users decide how they intend to send their WebP files, allowing the following three options:

① as a sticker,

② as an image,

③ as a file.

And the GitHub page of a client does not seem like a place where the new mindset is determined.

Please visit Telegram's platform of bugs and suggestions [(announced in December 2020)](https://telegram.org/blog/voice-chats#feature-suggestion-platform) and vote for my [suggestion of wider support for WebP.](https://bugs.telegram.org/c/1021)

**Comment by Mithgol** [comment] 2021-03-07 22:37
> I think I'll enable the "send compressed" option for webp, so it works like png, by sending as photo. That should be fine for everyone.

Would that push the image into [the vicious circle of JPEG-to-JPEG recompression?](https://bugs.telegram.org/c/1058)

**Comment by drguildo** [comment] 2021-04-14 08:35
I think treating all pasted WebP images as stickers is a poor design choice, but even if that's behaviour certain people want, can you at least give us the option of sending it as a normal image? Ideally this would be the default, with the **_option_** of sending it as a sticker.
