### ISSUE TITLE
Cannot login without mobile phone.

### ISSUE THREAD

**Issue by SkybuckFlying** [telegramdesktop/tdesktop#24342] opened 2022-04-15 08:04 UTC
### Steps to reproduce

Download and install.

Can't get passed these two screens:

Screen 1:
![TelegramScreen1](https://user-images.githubusercontent.com/34254801/163543567-0453b2d3-d7b5-47dd-a3d9-7cf4d19b0baa.png)

Screen 2:
![TelegramScreen2](https://user-images.githubusercontent.com/34254801/163543590-7c820925-9feb-4f7c-ad43-3e053effef80.png)

### Expected behaviour

PC-Only.

### Actual behaviour

Tracker/Radiation device needed.

### Operating system

Windows 7

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment] 2022-04-15 08:20
duplicate of #16153

**Closed** 2022-04-15 08:39 UTC
Labels: bug
