### ISSUE TITLE
Telegram crashes on accent characters like ` ^ ´

### ISSUE THREAD

**Issue by Lesik** [telegramdesktop/tdesktop#1318] opened 2015-11-22 21:23 UTC
Since a few weeks I'm observing that after Telegram was open for a while, it crashes when I try to type accent characters. Since the update that allows to `include code blocks` using the \` character, I started using these much more frequently, making this bug a little annoying.

Unfortunately, running Telegram in terminal didn't produce much useful output:
```
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
AL lib: (EE) LoadHrtf: Could not open default-44100.mhr
AL lib: (EE) GetHrtf: Incompatible format: Stereo 44100hz
Speicherzugriffsfehler
```

(The last message means "segmentation fault" in German.)

`~/.TelegramDesktop/log.txt`:
```
[2015.11.22 22:14:58] Message Info: bad message notification received (error_code 16) for msg_id = 6220085940386275280, seq_no = 304
[2015.11.22 22:20:02] Message Info: bad message notification received (error_code 16) for msg_id = 6220087277786353204, seq_no = 350
[2015.11.22 22:20:04] Message Info: bad message notification received (error_code 16) for msg_id = 6220087277786353208, seq_no = 350
[2015.11.22 22:20:08] Message Info: bad message notification received (error_code 16) for msg_id = 6220087277786353212, seq_no = 351
```

Pay attention to the "after Telegram was open for a while" – these characters function just fine for about 10 minutes after Telegram was started. I can't tell at what point exactly, but at some point they don't work anymore.

I do not have a `nodeadkeys` keyboard layout.

**Comment by telegramdesktop** [comment] 2015-11-22 21:42
@Lesik Can you try and run "catchsegv ./Telegram" from terminal next time? It will produce backtrace of the segmentation fault in the terminal.

**Comment by Lesik** [comment] 2015-11-22 23:32
It finally happened again, and there's a lot of output. I presume there is also personal information in it.

What part of it is important for solving this issue?

**Comment by Lesik** [comment] 2015-11-23 09:46
Telegram installation directory has been replaced with `/run/Telegram`, user directory has been replaced with `/home/user`:

http://hastebin.com/buquzizape.avrasm

**Comment by Lesik** [comment] 2015-11-27 07:17
I did a complete reinstall to see if I can reproduce the error, and I definitely can.

**Comment by Lesik** [comment] 2015-12-24 16:16
I can replicate this bug on a completely different computer on a different operating system (Arch Linux).

**Comment by roobre** [comment] 2015-12-29 13:46
Maybe this is a duplicate of #1074?

**Closed** 2015-12-29 13:48 UTC
