### ISSUE TITLE
Sometimes Telegram doesn't exit properly

### ISSUE THREAD

**Issue by hogsmead** [telegramdesktop/tdesktop#27027] opened 2023-11-01 11:10 UTC
### Steps to reproduce

1. Launch the app on GNOME with appindicators extension
2. Close the app by clicking the exit button in the tray menu

### Expected behaviour

Telegram exits normally.

### Actual behaviour

Sometimes you can still observe Telegram in the background apps UI. When you try to close it there, it's crashing.

### Operating system

Fedora Linux 38, GNOME 44.5

### Version of Telegram Desktop

4.11.1

### Installation source

Flatpak

### Logs

[log.txt](https://github.com/telegramdesktop/tdesktop/files/13226473/log.txt)

**Comment by ilya-fedin** [comment] 2023-11-01 14:26
> This shouldn't happen on GNOME as far as I know.

It should as long as you have close button and don't have minimize button

**Comment by pearsche** [comment] 2023-11-05 05:09
I don't use extensions, but yeah closing telegram with the titlebar X doesn't close it completely, it remains in the process list and still gives notifications and such.  Closing it with ctrl+q does close it completely though

**Comment by ilya-fedin** [comment] 2023-11-05 11:09
@pearsche this is intended. And please don't mix this unrelated thing into the issue which is about closing from tray as you can read from steps to reproduce. If people will start mass-pollute this issue with complains about intended behavior then it's likely to be closed as its actual meaning will change and no one will remember about the initial issue.

**Comment by mike-zueff** [comment] 2023-11-24 10:31
I can reproduce it. When I close Telegram in a conventional way (in awesome WM), it just destroys UI but never close the process in background. But when I close it using Ctrl + q, it closes without leaving the background process.

I use Gentoo Linux, Qt 6, X server, systemd, awesome WM.
Telegram: 4.11.6.
USE flags in Gentoo for Telegram: X dbus fonts jemalloc qt6 qt6-imageformats screencast webkit -enchant -wayland.

**Closed** 2023-11-24 12:14 UTC
Labels: bug, cant reproduce
