### ISSUE TITLE
Not possible to enter «angle quotes» in messages

### ISSUE THREAD

**Issue by gentoo-root** [telegramdesktop/tdesktop#26976] opened 2023-10-27 20:18 UTC
### Steps to reproduce

1. Setup right alt for the third layer modifier, and the ru+ruu keyboard layout that has special symbols on the third layer, such as: `«»„“…`
2. Try to type those symbols into the chat.

### Expected behaviour

All of those symbols should be typeable.

### Actual behaviour

While I can type `„“…`, there is no reaction to angle quotes `«»`.

### Operating system

Arch Linux, GNOME 45.0

### Version of Telegram Desktop

4.10.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment] 2023-10-28 07:47
Can you do that in other Qt 6 applications?

**Comment by ilya-fedin** [comment] 2023-10-29 13:41
There's no need to say that, as you can see the issue is open so it will be reproducible for sure.

**Comment by ilya-fedin** [comment] 2023-10-29 13:43
Actually I don't understand how to reproduce that. I don't understand what 'third level' is and how to set it up. I'm also unable to find such layout.
![](https://github.com/telegramdesktop/tdesktop/assets/17829319/a362da66-dfb6-469f-b97a-bb67ba18cb1d)

**Comment by ilya-fedin** [comment] 2023-10-29 13:54
My guess is still that Qt is at fault most likely as all the input is managed by Qt. Maybe that's unreproducible in other applications due to minor difference in version (like 6.6.0 vs 6.5.3) or because all those applications are using QLineEdit widget (no markup support) while Telegram is using QTextEdit. I remember reports about backspace not working with caps lock layout switch that was reproducible in message input field (which is using QTextEdit) but not in search field (that was using QLineEdit at the time but is using QTextEdit now as well). Although the backspace bug is still not fixed by Qt so the hope for such reports is low... Sadly I don't know any other Qt application that is using QTextEdit (but there should be examples using it in Qt source code).

**Comment by ilya-fedin** [comment] 2023-11-08 20:35
> Has there been any Qt updates in the Telegram flatpak image recently?

Yeah, they are regular. The last one was at https://github.com/flathub/org.telegram.desktop/commit/68598851cc3f709e5c0aae14c4013de35c1a05cc.

**Comment by ilya-fedin** [comment] 2023-11-08 20:38
We're talking about X11, yeah? As setxkbmap doesn't work on Wayland obviously.

**Comment by ilya-fedin** [comment] 2023-11-08 20:42
I'm unable to reproduce in my KDE X11 VM with `setxkbmap -option misc:typo,lv3:ralt_switch,grp:caps_toggle`. right alt + <</>> works just fine.

**Comment by ilya-fedin** [comment] 2023-11-08 22:15
I can't reproduce on KDE Wayland either and I have no GNOME system to test. Perhaps that's yet another incompatibility between Qt and GNOME.

**Comment by ilya-fedin** [comment] 2023-11-08 22:30
If it used to work fine then mentioning the first bad vesrion when creating the issue would save a lot of time

**Comment by ilya-fedin** [comment] 2023-11-08 22:37
Apparently it changed how GNOME works cause flatpak package couldn't have access to host libraries

**Comment by ilya-fedin** [comment] 2023-11-08 22:43
> but not a single other application.

Maybe they aren't flatpaks or use Xwayland? I can assume it could be incompatibility between server/client with different libxkbcommon versions as keyboard layouts on Wayland work via generating, sending, receiving & parsing payload generated by libxkbcommon. And gtk tends to have custom implementations for xkbcommon-related things rather than relying on libxkbcommon like Qt does.

**Comment by ilya-fedin** [comment] 2023-11-08 22:56
Apparently, yes.

**Closed** 2023-11-08 22:56 UTC
Labels: bug, cant reproduce
