### ISSUE TITLE
problem when receiving notify in window10 desktop

### ISSUE THREAD

**Issue by bndghn** [telegramdesktop/tdesktop#2446] opened 2016-09-20 20:37 UTC
### Steps to reproduce
1. when receiving notify in windows 10 desktop ,
2. 
3. 

### Expected behaviour
Tell us what should happen
 telegram Freezed and dont work.

### Actual behaviour
Tell us what happens instead
 telegram Freezed and dont work when receiving notify in window10 desktop
### Configuration
**Operating system:**
windows 10 Desktop 

**Version of Telegram Desktop:**
v 0.10.7
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment] 2016-09-21 11:32
This looks like Window toasts problem, I've received reports that Slack desktop app has the same issues. I couldn't reproduce that myself or find a workaround remotely, so currently the only solution is to disable Windows notifications in Settings (leaving custom TDesktop notifications enabled).

**Comment by bndghn** [comment] 2016-09-21 12:15
I have not this problem in older version of telegram

**Comment by john-preston** [comment] 2016-09-21 12:35
@bndghn You try the older version right now? Or you tried it before windows 10 anniversary update?

**Comment by Aokromes** [comment] 2016-10-06 12:44
duplicate of #2296 no?

**Closed** 2016-10-06 12:45 UTC
