### ISSUE TITLE
desktop client version 2.6.1 stopped displaying icons after negotiating keys in voice calls

### ISSUE THREAD

**Issue by sergstesh** [telegramdesktop/tdesktop#10456] opened 2021-03-03 13:58 UTC
I am on 64 bits Kubuntu 18.04 and downloaded Telegram from https://telegram.org/dl/desktop/linux . Though the problem can be seen in version 2.6.1, I first saw it in some 2.5.8 version.

When I call my friend, he tells me that when he uses Telegram on his smartphone he sees the four icons after secret key negotiation. I do not see the icons using my desktop client. I did see the four icons in the past when I was using some Telegram version from flathub.
...
I have performed more tests, and results are the following:

1) when I use version 2.5.8 from flathub I do see the four icons, and the pop-up window appearing during the call at the top of which the four icons are displayed does have window frame;
2) when I use version 2.5.8 or 2.6.1 downloaded from https://telegram.org/dl/desktop/linux , I do not see the four icons and the pop-up window appearing during the call at the top of which the four icons are supposed to be displayed, but in this case are not displayed does not have window frame - even though the main Telegram window does have window frame.

**Comment by ilya-fedin** [comment] 2021-03-03 14:02
Which four icons are you talking about?

**Comment by sergstesh** [comment] 2021-03-03 14:18
> Which four icons are you talking about?

I am talking about the four icons which are supposed to be compared by both parties of the call. If the four icons are the same, probability of man in the middle attack is very low.

**Comment by john-preston** [comment] 2021-03-03 15:00
@sergstesh Can you provide me with a screenshot of the call window without the emoji? I see this in Ubuntu 20.04, tdesktop 2.6.1.

![image](https://user-images.githubusercontent.com/17900494/109824924-bcb3e200-7c52-11eb-9bd7-eac7eeb299ee.png)

**Comment by sergstesh** [comment] 2021-03-03 15:15
![telegram_no_icons](https://user-images.githubusercontent.com/49365706/109826770-cc77fa00-7c43-11eb-880f-8e709ac5399c.png)
My friend allowed me to take the whole window screenshot, I took the screenshot using the stock KDE 'spectacle' application and I chose to take screenshot of "Window under cursor".

**Comment by ilya-fedin** [comment] 2021-03-03 15:25
looks it's because you close at the left side...

**Comment by sergstesh** [comment] 2021-03-03 15:34
> looks it's because you have close button at the left side...

I don't think so. This same friend of mine has the same issue with his desktop client, and, as I wrote, if I use flatpak version I do see the four icons.

Anyway, in more general terms the buttons are normally located on window border. This window doesn't have border, but the flatpak version window does have border.

**Comment by ilya-fedin** [comment] 2021-03-03 15:36
> This same friend of mine has the same issue with his desktop client, and, as I wrote, if I use flatpak version I do see the four icons.

Ask if your friend have close button on the left side :)

**Comment by ilya-fedin** [comment] 2021-03-03 15:38
You also can change your settings and you will see that the icons will appear if you set all the buttons to right side

**Comment by sergstesh** [comment] 2021-03-03 15:50
> You also can change your settings and you will see that the icons will appear if you set all the buttons to the right side

As I wrote, I do see icons in the flatpak version. The settings affect all windows, don't they ?

Anyway, an application should not display data between the buttons - except for window title.

**Comment by ilya-fedin** [comment] 2021-03-03 15:54
> As I wrote, I do see icons in the flatpak version.

Because you're using old flatpak version...

> Anyway, an application should not display data between the buttons - except for window title.

It's just your opinion.

**Comment by john-preston** [comment] 2021-03-03 16:17
@sergstesh This is by design. It will be fixed in the next version, but right now indeed the top element in both calls and voice chats disappear if at least one control button is on the left side of the window. Thank you for your report.

**Comment by sergstesh** [comment] 2021-03-03 17:11
@john-preston , of course you know what's in the code while I don't, but an important fact is that the flatpak version uses its own KDE environment, and I do not know about the version downloaded from https://telegram.org/dl/desktop/linux . I again remind that the pop-up window is borderless in case of https://telegram.org/dl/desktop/linux version and does have border in case of flatpak version.

So to me it looks like first of all differences between KDE versions.

**Comment by sergstesh** [comment] 2021-03-03 17:26
I have just downloaded version 2.6.1 via flatpak and conducted a test call.

Main telegram window still has the close window ('x') button on the left side of the window - as proscribed by my desktop settings, but the pop-up window appearing as a result of voice call has the close window button on the right side, and as before I do see the four icons.

So yes, the problem is related to the close window button position, but, as I stated above , we have difference of behavior which is quite possibly due to difference in KDE environments.

**Comment by sergstesh** [comment] 2021-03-03 17:53
> Because you're using old flatpak version

No, I don't - see https://github.com/telegramdesktop/tdesktop/issues/10456#issuecomment-789908236 .

**Comment by ilya-fedin** [comment] 2021-03-03 18:37
KDE needs xsettingsd in order to provide settings for sandboxed applications IIRC. Not sure if xsettingsd integration is present in such old KDE as in Kubuntu 18.04 though.

**Comment by sergstesh** [comment] 2021-03-03 20:34
> KDE needs xsettingsd in order to provide settings for sandboxed applications IIRC

I am not familiar with these mechanism/settings.

Anyway, does your statement explain the fact that the main Telegram window has the 'x' (close) window button on the left side, as it is supposed to be according to my desktop setting, but the pop-up window has the same button on the right side ?

I did write a number of GUI applications (not in Qt/KDE), and child windows simply inherit settings from the parent window. Is the pop-up window not a child window ? It also dosen't have window border while the main window has it. If it is not a child window, should it be this way ?

**Comment by ilya-fedin** [comment] 2021-03-03 20:39
"Use system window frame" setting is only about the main window, that's why you see the difference.

**Comment by sergstesh** [comment] 2021-03-03 20:51
> "Use system window frame" setting is only about the main window, that's why you see the difference

How about the 'x' (close) button ? Shouldn't its position be inherited from the main window ?

**Comment by ilya-fedin** [comment] 2021-03-03 20:57
> Shouldn't its position be inherited from the main window ?

No

**Comment by sergstesh** [comment] 2021-03-03 21:29
> > Shouldn't its position be inherited from the main window ?
> 
> No

Then how come whenever I open new window in a web browser, Email client, etc button positions are inherited ?

If button positions shouldn't be inherited, then they should be read from global desktop settings, shouldn't they ? Again, why is it so that when I write an application button positions are inherited ?

**Comment by ilya-fedin** [comment] 2021-03-03 21:33
> Then how come whenever I open new window in a web browser, Email client, etc button positions are inherited ?

I don't know why do you think there's any inheritance...

> If button positions shouldn't be inherited, then they should be read from global desktop settings, shouldn't they ?

Exactly. tdesktop reads them from gtk (Qt doesn't offer a way to do that).

> Again, why is it so that when I write an application button positions are inherited ?

What do you mean by "I write an application button"?

**Comment by sergstesh** [comment] 2021-03-03 21:44
> What do you mean by "I write an application button"?

I didn't clearly enough formulated my statement. I meant the following: when I write an application, and the application allows to create child windows, button positions in child windows are inherited automagically. I.e. I do not have to write any special code to achieve the same button positions.

I also have nheko installed ( https://github.com/Nheko-Reborn/nheko ) - yet another KDE application. When a child window is created (e.g. the one through which new users are invited) window button positions are inherited from the main window. I run nheko via flathub.

**Comment by ilya-fedin** [comment] 2021-03-03 21:47
Probably you don't understand that tdesktop has client-side window decorations and "Use system window frame" enables server-side decorations (only) on main window?

**Comment by Aokromes** [comment] 2021-03-26 23:00
fixed on 2.7.1

**Closed** 2021-03-26 23:00 UTC
