### ISSUE TITLE
High-DPI/4K - 250% interface scale

### ISSUE THREAD

**Issue by fadavi** [telegramdesktop/tdesktop#2144] opened 2016-06-14 17:12 UTC
Telegram Desktop UI is too small in High-DPI ([4K](https://en.wikipedia.org/wiki/4K_resolution)) display (Screenshot attached),  and I need 250% interface scale to reach best readability.

Could you add 250% (or even more!) interface scale support to Telegram Desktop to next release?
### Configuration

**Operating system:** Ubuntu 16.04 LTS

**Version of Telegram Desktop:**  0.9.49

**System:** [ASUS N552VW - A](https://www.asus.com/Notebooks/VivoBook-Pro-N552VW/)
![telegram-desktop-4k-display](https://cloud.githubusercontent.com/assets/9992849/16052185/51c6f334-3278-11e6-953c-8757751eb724.png)

**Comment by zhulik** [comment] 2016-06-17 09:40
I have the same issue on Lenovo Y5070, env QT_DEVICE_PIXEL_RATIO=3 is a workaround for me. It will be great, if telegram will do it automatically!.

Also, with QT_DEVICE_PIXEL_RATIO=3 wome graphics in application is broken, see attachment
![2016-06-17 12-45-01](https://cloud.githubusercontent.com/assets/287062/16146795/96a8cbbe-3488-11e6-927a-34f83ef06887.png)

**Comment by scutdk** [comment] 2016-07-10 14:29
Same for windows. Can you please add 250% scale. Thank you.

**Comment by HankAviator** [comment] 2016-08-01 07:06
Tried the workaround of OP on Windows 10, the scaling did change but the windows was frozen. 3K display here.

**Comment by artemrizhov** [comment] 2017-01-24 17:20
Also please add 300% for 4k 17'' displays.

**Comment by stek29** [comment] 2017-01-25 22:50
Or make it dynamically scalable.

**Comment by nachoparker** [comment] 2017-01-25 22:51
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  pkbrister@zoho.com
    Domain ownyourbits.com has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:49367)
	by skywalker.onesite.co with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7866-nacho=ownyourbits.com@sgmail.github.com>)
	id 1cWWOz-002JvR-7j
	for nacho@ownyourbits.com; Wed, 25 Jan 2017 17:50:53 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=GTQ4xAMPo8/fVLrd2LpHu/HukDk=; b=SnuMDyZx6NAoQEcZ
	FReIN487hCLCE/E2/pnY3FJzMnN4ZkB4L0I9i1zLQ+D3RKXI5M60MoCsTT2L9FyX
	xRGveEIDEKBErrYLb6zauQlDON6uX6aVn+8u82xYKM38cdFZO/UllK7v1sIy7TXt
	lXalo1nscMQwc1LZO+66jOAs6iM=
Received: by filter0253p1las1.sendgrid.net with SMTP id filter0253p1las1-6569-58892BA3-34
        2017-01-25 22:50:11.757424738 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id 7gzZr0BRQG2FOYyHVOH1OA
	for <nacho@ownyourbits.com>; Wed, 25 Jan 2017 22:50:11.537 +0000 (UTC)
Date: Wed, 25 Jan 2017 14:50:11 -0800

**Comment by auchri** [comment] 2017-01-25 22:52
@nachoparker FIX YOUR MAIL!

**Comment by auchri** [comment] 2017-02-01 11:58
Closing for #1121

**Closed by auchri** 2017-02-01 11:58 UTC

**Comment by omid-1985** [comment] 2018-06-25 05:13
How is this issue closed when it was opened in 2016 and not yet resolved after two years????
May I know why @auchri closing all other open duplicated issue from other users when maximum scaling in telegram is still 200% and this issue is already closed? No one from developers team cares about a closed issue.
Neither 250% nor 300% was added to Telegram yet and app is literally unusable in 13" 4K laptop.

**Comment by artemrizhov** [comment] 2018-06-25 11:57
This issue will not bother developers unless they get 4k 13'' laptops))) But developers uses 17" laptops usually. So we have to wait many years for 16k displays to get this problem solved.

**Comment by ch3ckmat3** [comment] 2018-06-25 12:35
How difficult is it to enable zooming the UI, when the app already has the functionality of zooming to 200%?

**Comment by john-preston** [comment] 2018-06-25 13:09
@ch3ckmat3 There is some work to be done, all graphics currently are drawn and prepared only for the four existing scale factors.

**Comment by kvaster** [comment] 2018-06-25 13:28
Just switched from my old macbook pro retina to xps 9575 4k and now I have same problem - Telegram is too small :(

**Comment by artemrizhov** [comment] 2018-06-25 20:37
@john-preston if so, why is the issue closed?

**Comment by john-preston** [comment] 2018-06-25 20:54
@artemrizhov I guess because no one does the mentioned work right now =(

**Comment by artemrizhov** [comment] 2018-06-25 21:50
I thought "closed" means it is fixed already or never will be fixed.

**Comment by john-preston** [comment] 2018-06-25 22:05
@artemrizhov I can't tell about never, but currently I'm unable to do that :(

**Comment by ch3ckmat3** [comment] 2018-06-25 22:22
AFAIK, if the zooming functionality is present int he app, then extending the functionality in the same lines is mostly repetitive work, with adjustments to new requirements of course... so if the dev team takes the task up, I believe they can achieve it in time, where more and more 4K displays are coming out, this feature is in high demand.

**Comment by john-preston** [comment] 2018-06-25 22:38
@ch3ckmat3 The problem is graphics. If you just use the existing with a large resolution it will be looking extremely bad :( emoji as well, and they're huge, like HUGE huge.

**Comment by artemrizhov** [comment] 2018-06-26 00:37
What number of images are we talking about? Can you tell the approximate cost of this work?

**Comment by kvaster** [comment] 2018-06-26 09:32
It will be much to have possibility to scale up to 250-300 even with badly upscaled graphics. My eyes are struggling from such small fonts....

**Comment by kvaster** [comment] 2018-06-26 09:37
Also may be it will be good to have svg's instead of pngs (or additional to pngs).

**Comment by john-preston** [comment] 2018-06-26 09:46
@kvaster Yes, this will be a real solution. But it is hard, not only to redraw all graphics, but to enable fast usage of svgs instead of pngs.

**Comment by kvaster** [comment] 2018-06-26 10:22
@john-preston I think we can use existing pngs and prerender svg (maybe even during build). Main problem is to redraw svg graphics :( Anyway I think that users with hidpi screens like my will appreciate having hidden option (maybe launch option) which will allow scale more then 200% even with ugly emojis.

**Comment by ch3ckmat3** [comment] 2018-06-26 12:17
@kvaster I'll use the hidden option. +1

**Comment by lucidyan** [comment] 2018-09-10 11:48
Same issue here. On DELL XPS 13 with 4K app looks very small with 200% scaling
So reopen this issue, please

**Comment by the-eric-kwok** [comment] 2018-09-19 03:44
On Deepin LInux 15.7, When the system scale is 125%...

![photo_2018-09-19_11-10-16](https://user-images.githubusercontent.com/16463312/45729354-ba827800-bbfe-11e8-866c-0e95960762e5.jpg)

Disable system scale for Telegram, and manually scale in Telegram's setting should fix this.

**Comment by ng0177** [comment] 2019-09-30 17:50
Glad to see you guys working on it; a terrible situation...

**Comment by RasAlhag** [comment] 2021-01-16 12:41
I am writing since January 2021, the problem persists!

**Comment by ilya-fedin** [comment] 2021-01-17 03:09
@RasAlhag can't confirm
![image](https://user-images.githubusercontent.com/17829319/104829969-6856cd80-5871-11eb-9a01-e8411b576eca.png)

**Comment by RasAlhag** [comment] 2021-01-17 09:30
@ilya-fedin I have 2 monitors 2.5k and 4k, when the application is on 2.5k, everything is fine, but when I transfer it to a 4k monitor, everything becomes very small, on a 4k monitor, there is 175% scaling, in other applications, for example discord, chrome there is such a problem no!
OS: windows 10 pro x64

**Comment by ilya-fedin** [comment] 2021-01-17 09:35
Anyway, there's no point to commenting on an issue that was closed as a duplicate

**Comment by Ondra1230** [comment] 2021-01-17 09:40
how do i know it's a duplicate?On 1/17/21 at 11:36 PM, ilya-fedin wrote:
                
            
            
                
                    From: "ilya-fedin" <notifications@github.com>Date: January 17, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: Re: [telegramdesktop/tdesktop] High-DPI/4K - 250% interface scale (#2144)
                
                
Anyway, there's no point to commenting on an issue that was closed as a duplicate

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/2144#issuecomment-761761529",
"url": "https://github.com/telegramdesktop/tdesktop/issues/2144#issuecomment-761761529",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RasAlhag** [comment] 2021-01-17 09:41
@ilya-fedin and the duplicate referenced by this issue is also closed!

**Comment by Ondra1230** [comment] 2021-01-17 09:43
I believe that, some things are too good ..On 1/17/21 at 11:31 PM, RasAlhag wrote:
                
            
            
                
                    From: "RasAlhag" <notifications@github.com>Date: January 17, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: Re: [telegramdesktop/tdesktop] High-DPI/4K - 250% interface scale (#2144)
                
                
@ilya-fedin I have 2 monitors 2.5k and 4k, when the application is on 2.5k, everything is fine, but when I transfer it to a 4k monitor, everything becomes very small, on a 4k monitor, there is 175% scaling, in other applications, for example discord, chrome there is such a problem no!
OS: windows 10 pro x64

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/2144#issuecomment-761760931",
"url": "https://github.com/telegramdesktop/tdesktop/issues/2144#issuecomment-761760931",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ilya-fedin** [comment] 2021-01-17 09:44
> and the duplicate referenced by this issue is also closed!

I see it's open
![image](https://user-images.githubusercontent.com/17829319/104836811-82f86900-58a8-11eb-80a8-bbc73f6079e9.png)

**Comment by ilya-fedin** [comment] 2021-01-17 09:45
> I believe that, some things are too good ..On 1/17/21 at 11:31 PM, RasAlhag wrote:

Preserve multiple lines until the "On ... wrote" line in order to let github hide that mess :see_no_evil:

**Comment by Ondra1230** [comment] 2021-01-17 09:46
I don't understand it at all now...MAYBYOn 1/17/21 at 11:44 PM, ilya-fedin wrote:
                
            
            
                
                    From: "ilya-fedin" <notifications@github.com>Date: January 17, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Comment" <comment@noreply.github.com>,"Ondra1230" <Ondra123@mail.com>Subject: Re: [telegramdesktop/tdesktop] High-DPI/4K - 250% interface scale (#2144)
                
                

and the duplicate referenced by this issue is also closed!

I see it's open


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/2144#issuecomment-761762514",
"url": "https://github.com/telegramdesktop/tdesktop/issues/2144#issuecomment-761762514",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BitMobix** [comment] 2021-01-25 11:00
Add a scale of 225%.
Not everyone has good eyesight.
You understand that it affects people's health !!!
