### ISSUE TITLE
read message counter went to minus

### ISSUE THREAD

**Issue by islamsav** [telegramdesktop/tdesktop#6446] opened 2019-08-27 09:16 UTC
![image](https://user-images.githubusercontent.com/43797131/63758462-ddb4ad80-c8cc-11e9-81fd-01ddda6b4ba8.png)

**Comment by islamsav** [comment] 2019-08-27 09:17
1.7.13 desktop version on Windows

**Comment by RememberTheAir** [comment] 2019-08-27 09:21
Duplicate of #6100, also there has been a few more stable releases after 1.7.13, I suggest you to update your app

**Comment by MasterGroosha** [comment] 2019-08-27 17:53
@RememberTheAir even more, 1.8.x is also stable

**Closed** 2019-09-06 20:54 UTC
