### ISSUE TITLE
Telegram keeps unnecessary handle on audio driver

### ISSUE THREAD

**Issue by bduffany** [telegramdesktop/tdesktop#1044] opened 2015-08-30 22:23 UTC
Not sure of the correct terminology here, but Telegram keeps the audio driver open for longer than it needs to (in Windows, at least). This is a HUGE pain for people who use programs that require the audio driver to be free (e.g., music producers using FL Studio, Pro Tools, etc.) In order for me to run FL Studio, I have to first go into the system tray to close Telegram, otherwise the ASIO4ALL drivers in FL Studio (and other DAW programs) don't work properly.

Telegram should instead open the audio driver, play a sound, then close it when it's finished.

**Comment by auchri** [comment] 2015-08-30 22:27
Which version do you use?

It should be fixed with 0.8.22.dev (see #457)

**Comment by bduffany** [comment] 2015-08-31 00:24
I have version 0.8.52.

**Comment by mirhl** [comment] 2015-09-02 10:44
It's still permanent. 
Even worse, I played no sound (and the "play sound" setting in notifications is disabled), and telegram desktop can still be seen 24/7 in the windows mixer.

**Comment by ix** [comment] 2015-12-22 19:01
This is a massive problem on Linux. I use ALSA, and ALSA only supports one audio channel at a time. Due to Telegram being constantly open in the background for notifications, I have to run `killall telegram` in my terminal before I can start using audio in another application.

**Comment by telegramdesktop** [comment] 2015-12-22 19:56
@ix That's strange :( I pause OpenAL device between notifications (when sound is not playing), so it should release the handle..

**Comment by ix** [comment] 2015-12-22 20:16
I don't even have notifications enabled.

**Comment by j54n1n** [comment] 2016-01-03 04:57
I can confirm this behaviour in version 0.9.15. On my Win7 laptop I have an integrated Conexant HD Audio soundcard. It has normally an auto power off feature that kicks in when no sound is played back. But it is not doing that as long as I have running Telegram. With the headphones I can hear the typical faint background noise of the soundcard until I quit Telegram by right clicking on the symbol in the notification area.

**Comment by DiThi** [comment] 2016-01-11 11:27
Another big problem with this is that it doesn't switch devices. I connect my bluetooth headset and I hear *everything* but telegram. I missed some important messages because of that.

In other words, every time it plays a sound, it should open the default device, and close it when it's done.

**Comment by Kocane** [comment] 2016-02-01 02:00
I second j54n1n's problem. The audiocard on my laptop is rather awful, when theres open audiostreams like youtube video, music, videofile there's a hiss coming from the speakers. But it usually stops after some seconds when exiting whatever app or webpage that played something with audio. 

However, when telegram is opened this hiss is there at **all times**. I would really like it, if this could be fixed. Telegram should just let go of the audio-stream when it's done playing a sound. Something which I actually rarely use in Telegram

**Comment by cookiengineer** [comment] 2016-04-11 13:12
I can confirm that, for Ubuntu 15.10, Ubuntu 16.04 and ArchLinux.

When using two different audio devices (e.g. Scarlet 2i2 USB with headphones connected and an HDMI-to-audio-jack connector) telegram results in issues with audio. The audio frequency is changed for _all devices_ by telegram.

That means sound playback is double as fast (probably 41kHz as audio sampling via USB is typically 21kHz) for all devices. You have to reboot your computer to get rid of that. Sometimes going back to sound settings in GNOME fixes the problem as they reload pulseaudio configuration, but often it doesn't fix it since the last updates.


Why does Telegram use ALSA and not say, pulseaudio or [libSDL](http://www.libsdl.org/) APIs? libSDL is battle-tested in the whole Steam world and is very common for cross-platform usage, so I'm wondering why all the OpenAL stuff is being reinvented in the [audio.cpp](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/audio.cpp).

**Comment by DiThi** [comment] 2016-04-11 15:51
@cookiengineer Switching APIs may solve it for PulseAudio users, but the problem is still there for ALSA and Windows users. The problem is that Telegram, for most use cases, is completely silent most of the time, so it makes no sense keeping the audio device open at all times, or not switching devices when you connect another device. When someone sends me an audio message I have to use the phone to hear it (even if I disconnect the headphones to go back to the initial device), or to restart Telegram in the PC.

**Comment by cookiengineer** [comment] 2016-04-11 18:24
That's why I was mentioning SDL in the first place. The APIs there are pretty neat as they are cross-platform for all OSes and have simple OpenAudio/CloseAudio methods.

See: https://wiki.libsdl.org/SDL_OpenAudioDevice

**Comment by DiThi** [comment] 2016-04-11 18:29
Does it switch devices automatically? Then it's a good suggestion, although it wouldn't solve all.

My suggestion is just to close the device, and open the default device when it has to play sound. It would fix all problems mentioned in this thread.

**Comment by cookiengineer** [comment] 2016-04-11 18:34
@DiThi [Yes](https://hg.libsdl.org/SDL/file/aa9904a56acf/src/audio/alsa/SDL_alsa_audio.c#l332) and it supports pretty much every sound daemon you can imagine: https://hg.libsdl.org/SDL/file/aa9904a56acf/src/audio

In my case (pulseaudio) it also [correctly uses different audio formats without overriding them](https://hg.libsdl.org/SDL/file/aa9904a56acf/src/audio/pulseaudio/SDL_pulseaudio.c#l449).

**Comment by DiThi** [comment] 2016-04-11 19:59
@cookiengineer that's not my point. I know that it supports many audio APIs, and that PulseAudio allows you to change frequencies and devices seamlessly. But if the application is in Windows (or using ALSA) and it doesn't release the audio device, it won't support switching devices on the fly. That's sort of OK for old games or multimedia applications (annoying, but understandable), but not for an application that is open 24/7. I don't want to restart it every time I connect the bluetooth headset so I can hear notifications and voice messages.

Even worse, after turning the heatset off, it doesn't even play on the original device anymore.

**Comment by Enes81** [comment] 2016-05-22 19:47
So I've seen issues from more then a year ago describing this issue, and it's still not fixed..

It's incredibly annoying on a laptop. When I plug my headset in, the audio still comes from the speakers. Never ever have I seen this behavior on other software!

**Comment by Kocane** [comment] 2016-05-22 22:57
I would also like being able to dock my laptop without having to restart Telegram to get the right sound output... and be able to change record input etc, without having to restart the program... moreover, the constant hook on the audio driver makes my speakers hizz. With all other programs, that only happens when audio is actually being played.. alas, I'm probably alone with that, just saying it would be really nice to have this fixed.

**Comment by zaps166** [comment] 2016-07-26 14:30
I also think that it is important BUG to fix. It blocks the sound card and needs more power from the device especially on laptops/tablets. It is annoying...

**Comment by dreaddymck** [comment] 2016-08-02 14:44
Hi all.
Version 0.9.56 - Windows 10

Have to exit Telegram to free up audio driver for other applications like Fruity loops. 

Any solutions available?

**Comment by skywalkersenior** [comment] 2016-08-10 22:45
I add a problem.
With Telegram open, on my notebook the sound is scratchy (seems a problem with the speakers). I have to completely close TG to have a clear sound

**Comment by TrueBers** [comment] 2016-12-01 21:12
Confirm.

ArchLinux with ALSA here. Output device is NVidia HDMI sound via DisplayPort.
When TG is running, no single application is able to play a sound. It says that device is doing really serious business (busy). Web browsers, media players, games, any of the apps that uses ALSA throw an error. So even to watch Youtube I have to terminate TG.

Even worse when I'm using my Win10 setup which is a KVM guest with GPU and sound passed through PCIe natively. When TG is running and some thing touches the sound device it makes a repeating sound like something hanged while playing. That sound can't be stopped even after TG shutdown, only reboot helps.

**Comment by drdrdr** [comment] 2017-01-30 07:25
Confirm.

Cannot start jackd when telegram is running.

**Comment by john-preston** [comment] 2017-01-30 09:17
@drdrdr Please try the latest alpha version 1.0.3 from the bottom of https://desktop.telegram.org/changelog#alpha-version page. It is not holding any audio device opened while it is not playing audio.

**Comment by drdrdr** [comment] 2017-01-30 09:26
@john-preston Thank you! Now jackd works with telegram

**Closed** 2017-02-27 09:28 UTC
Labels: bug

**Comment by mtaalas** [comment] 2018-07-21 20:12
This also causes completely unnecessary sample rate changes on windows platform still to this date.

I use MOTU 828MKII for music production and I want to run everything in one single and known sample rate that doesn't change on it's own (48/96khz). Telegram always resets this to 44.1khz when starting no matter what I do in any other sound setting available to me. And this makes telegram a very bad choice to be run in my main computer since it can do this on it's own suddenly and to reset the sampling rate i have to close all programs using the audio device first.

telegram should always respect the sampling rate of the system before trying to change it at all. If it can't respect that, there has to be sample rate conversion added to the code such that it can handle running in a system with different sampling rates even if it's using 44.1khz internally.

It's completely inexcusable as it stands. :/
