### ISSUE TITLE
BUG -Telegram won't start (creates many processes)How to fix?

### ISSUE THREAD

**Issue by Mitia514** [telegramdesktop/tdesktop#17530] opened 2022-01-07 12:49 UTC
After a certain time, telegram stops sending files (99% download), sending messages and playing messages.
 Although switching between chats works well.

I close the telegram (in the tray). when you try to start, nothing happens (although the process appeared in the task manager)
At another start, there is nothing again, and another telegram process appears in the dispatcher.

So you can create many telegram processes but never run the program

Completion of all processes in the task manager helps and the program then starts well, but this does not solve the problem and it comes back again after a while. 
How to fix it?

Telegram v 3.4.3 x64, windows 7 64bit, i5 ,16ram. 1050ti

**Comment by Aokromes** [comment] 2022-01-22 19:29
this is duplicate of a ticket i cannot remember id.

**Closed by Aokromes** 2022-01-22 19:29 UTC
Labels: question
