### ISSUE TITLE
[proposal] [usability] "pin to bottom" / "hide chat" / split chats into favourite ones and not / group spaces

### ISSUE THREAD

**Issue by dgronskij** [telegramdesktop/tdesktop#4947] opened 2018-07-06 18:47 UTC
Case: I'm a member of quite a few of private groups with 15+ members. With such an amount of members there is a constant flow of messages that make them bubbling up in the chat's list. My chat list is **bloated** with groups with high amount of members.

1) I can read them from time to time but don't want to do it on regular basis
2) I don't want to leave them due to them being private => will need an invitation next time
3) I **did** disabled notifications for them but that doesn't reposition the muted chat somehow
4) There is one private group that is, on the contrary, quite important for me so it's preferable to see an unread badge in still muted state. 

"Pin to top" functionality doesn't work here because to make specific chats not visible you have to make all the others been pinned to top.

Proposals (discussion appreciated):
1) Make sort of "pin to bottom" function
2) Assign priority to chats -- chats will move within their priority in the chats list
3) Chat spaces with corresponding tabs ("family", "work", "trash DO NOT WANNA SEE"). _This one could prevent the user from writing to the wrong chat by the way._
4) "Hide chat" functionality with access via separate tab / special button
5) Whatever else that is a compromise of implementation complexity and acceptable usability

**Comment by stek29** [comment] 2018-07-08 15:13
You might want to try work mode.

> Open Settings and type “workmode” on the keyboard (if you’re old like me, you remember this iddqd drill). This will give you a button at the top of the chats list that switches between showing all chats and only those for which you have notifications enabled.
> Zero time to set up and very flexible: if the things you’re currently doing require frequent access to a certain muted chat, just enable notifications for it temporarily.

**Comment by RadRussianRus** [comment] 2018-07-08 15:44
Duplicate of #4796?

**Closed** 2018-07-08 19:32 UTC
