### ISSUE TITLE
Custom icon doesn't work in v1.9.12

### ISSUE THREAD

**Issue by slideray** [telegramdesktop/tdesktop#7192] opened 2020-02-12 16:22 UTC
After update custom icons in the system tray are no longer used.  
Icons for the [linux] system tray were located at:

~/.local/share/TelegramDesktop/tdata/ticon  

sand previously, if you delete this directory, it was created again.  Not anymore.

Where can I place icons to display them in the system tray?

[Linux Debian 10 (stable), Telegram Desktop v1.9.12]

**Comment by xvitaly** [comment] 2020-02-12 17:22
> Where can I place icons to display them in the system tray?

Telegram Desktop will now use default icon with name `telegram.{svg,png}` from installed desktop theme.

**Comment by slideray** [comment] 2020-02-12 17:38
> Telegram Desktop will now use icon with name `telegram.{svg,png}` from installed desktop theme.
And where are the icons for displaying the unread message counter?

**Comment by xvitaly** [comment] 2020-02-12 17:47
> And where are the icons for displaying the unread message counter?

Check your installed system theme. If it has no Telegram icon, fallback from hicolor-theme will be used.

**Comment by xvitaly** [comment] 2020-02-12 17:48
You can create override in `~/.local/share/icons`.

**Comment by slideray** [comment] 2020-02-12 21:20
Yes, I did exactly that, but the new icon did not apply.  I tried to make both a png file and an svg file.  I made the size exactly the same as the original file.  Located in:
~/.local/share/icons/telegram.png

But nothing worked.

And yet I still didn't understand where the icons for the message counter come from (when the number of unread chats/messages is displayed in the tray)

**Comment by SmartFinn** [comment] 2020-02-13 00:49
Now Telegram looking for icons in the system themes. It's great, but there are a couple of issues:

- it looking for icons only in hicolor, gnome, Adwaita themes
- the tray icon size hardcoded to 48px when the majority of DE uses 22px icons for tray icons

[telegram_strace_file.txt](https://github.com/telegramdesktop/tdesktop/files/4195926/telegram_strace.txt)

**Comment by IsoaSFlus** [comment] 2020-02-13 03:07
Does telegram-desktop set the color of tray icon explicitly instead of using system's colorscheme?

**Comment by varlesh** [comment] 2020-02-13 06:31
@slideray it's can be disabled:
![image](https://user-images.githubusercontent.com/8083855/74407714-06fdd180-4e4c-11ea-86bf-46e852e3a491.png)

**Comment by andrei-a-papou** [comment] 2020-02-13 08:02
> @slideray it's can be disabled:
> ![image](https://user-images.githubusercontent.com/8083855/74407714-06fdd180-4e4c-11ea-86bf-46e852e3a491.png)
> update: but this not worked

I confirm this doesn't work. I can successfully plug in a custom monochrome tray icon by placing it under ~/.icons/hicolor, but Telegram still places a red unread message counter on top of it, even with this setting enabled.

Is this a bug?

**Comment by varlesh** [comment] 2020-02-13 08:06
reported here https://github.com/telegramdesktop/tdesktop/issues/7196

**Comment by varlesh** [comment] 2020-02-13 08:15
bugs in 1.9.13 release (with libappindicator and qsystemtray):
- Badge counter not disabled
- locked size 48px - it's blurred icons on non-HiDPI screens
Also why 48px? 22px * 2 scale = it's 44px

with libappindicator (Unity, Gnome, Cinnamon and etc):
- application find custom icons only hicolor, gnome & adwaita themes

**Comment by varlesh** [comment] 2020-02-13 09:31
Also strange why on KDE used SNI tray. 
```
[2020.02.13 13:20:42] Using SNI tray icon.
[2020.02.13 13:20:42] Getting DE, XDG_CURRENT_DESKTOP: 'KDE'
[2020.02.13 13:20:42] Getting DE, DESKTOP_SESSION: '/usr/share/xsessions/plasma'
[2020.02.13 13:20:42] Getting DE, KDE_SESSION_VERSION: '5'
[2020.02.13 13:20:42] DE: KDE5
```

**Comment by xvitaly** [comment] 2020-02-13 09:44
> libappindicator

There are no appindicator support anymore.

**Comment by varlesh** [comment] 2020-02-13 09:48
Yes, it's SNI. But why on KDE used SNI?

**Comment by ilya-fedin** [comment] 2020-02-13 11:47
> Where can I place icons to display them in the system tray?

It was a hack for appindicator. No appindicator - no hack. 🙃
It was a completely undocumented feature, so the answer is nohow.
But new tray icon implementation uses system icons: telegram-{,attention-,mute-}panel.{svg,png} as a main icon and telegram.{svg,png} as a fallback.

> ~/.local/share/icons/telegram.png

~/.local/share/icons/hicolor/$YOUR_ICON_SIZE/apps/telegram.png

> And where are the icons for displaying the unread message counter?

Counter is generated by the code, `ticons` folder was just a cache for appindicator, because it supports only icons from files

>     * it looking for icons only in hicolor, gnome, Adwaita themes

No, it looking for your current theme and hicolor as a fallback, as all other applications.

>     * the tray icon size hardcoded to 48px when the majority of DE uses 22px icons for tray icons

Unfortunately, it's a max size that code for counter generating can output :(

> but Telegram still places a red unread message counter on top of it

`TDESKTOP_DISABLE_TRAY_COUNTER=1` to your environment variables.

>     * Badge counter not disabled

It's not a bug, `Count unread messages` setting switches between chat and messages counting, as far as I know.

> Also strange why on KDE used SNI tray.

Because KDE uses the SNI prootocol 🙃

**Comment by IsoaSFlus** [comment] 2020-02-13 11:57
> > Where can I place icons to display them in the system tray?
> 
> It was a hack for appindicator. No appindicator - no hack. 
> It was a completely undocumented feature, so the answer is nohow.
> But new tray icon implementation uses system icons: telegram-{,attention-,mute-}panel.{svg,png} as a main icon and telegram.{svg,png} as a fallback.
> 
> > ~/.local/share/icons/telegram.png
> 
> ~/.local/share/icons/hicolor/$YOUR_ICON_SIZE/apps/telegram.png
> 
> > And where are the icons for displaying the unread message counter?
> 
> Counter is generated by the code, `ticons` folder was just a cache for appindicator, because it supports only icons from files
> 
> > * it looking for icons only in hicolor, gnome, Adwaita themes
> 
> No, it looking for your current theme and hicolor as a fallback, as all other applications.
> 
> > * the tray icon size hardcoded to 48px when the majority of DE uses 22px icons for tray icons
> 
> Unfortunately, it's a max size that code for counter generating can output :(
> 
> > but Telegram still places a red unread message counter on top of it
> 
> Put `TDESKTOP_DISABLE_TRAY_COUNTER=1` into your environment variables.
> 
> > * Badge counter not disabled
> 
> It's not a bug, `Count unread messages` setting switches between chat and messages counting, as far as I know.
> 
> > Also strange why on KDE used SNI tray.
> 
> Because KDE uses the SNI protocol

I noticed that the new telegram-desktop changed icon's color explicitly.
![image](https://user-images.githubusercontent.com/5125031/74433170-ddb86200-4e9a-11ea-9cc5-ebe05bfc3cb5.png)
Is there any way to make telegram-desktop not set color explicitly?

**Comment by ilya-fedin** [comment] 2020-02-13 12:00
> I noticed that the new telegram-desktop changed icon's color explicitly.

What do you mean? It requests a icon from system and shows it.

**Comment by IsoaSFlus** [comment] 2020-02-13 12:02
> > I noticed that the new telegram-desktop changed icon's color explicitly.
> 
> What do you mean? It requests a icon from system and shows it.

![image](https://user-images.githubusercontent.com/5125031/74433605-b1511580-4e9b-11ea-9514-0b3f69455985.png)
It should be black (follow current colorscheme).
But telegram-desktop set it to blue.

**Comment by SmartFinn** [comment] 2020-02-13 12:02
@ilya-fedin 

> No, it looking for your current theme and hicolor as a fallback, as all other applications.

```
$ > gsettings get org.gnome.desktop.interface icon-theme
'Papirus-Dark'
$ >
```

![image](https://user-images.githubusercontent.com/819186/74433641-7930df00-4e69-11ea-9063-8f251ad7f936.png)

As you can see in the strace output Telegram even doesn't try to find icons there.

**Comment by varlesh** [comment] 2020-02-13 12:23
@ilya-fedin with qsystemtray icon not blurred (on left SNI on right QT):

![image](https://user-images.githubusercontent.com/8083855/74434872-c0749b00-4e7c-11ea-9ce4-bc2694ced7ec.png)
tdesktop builded with key: `-D TDESKTOP_DISABLE_DBUS_INTEGRATION=ON`

**Comment by ilya-fedin** [comment] 2020-02-13 12:27
> But telegram-desktop set it to blue.

Oh, it's an [old hack](https://github.com/telegramdesktop/tdesktop/blob/7bf2b607f92de40fabf840e348d986509ef2c00a/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L128-L147), I was afraid to touch it.

> As you can see in the strace output Telegram even doesn't try to find icons there.

If you use tdesktop from official binary, it doesn't know about qt5ct :)


> tdesktop builded with key

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L453

**Comment by varlesh** [comment] 2020-02-13 13:55
@ilya-fedin I'm really not understand why used SNI on KDE if QSystemTray worked correct. It's possible hack for KDE? Use QSystemTray forcibly.
And size 48px - 2@scale 22px it's 44px

**Comment by ilya-fedin** [comment] 2020-02-13 14:22
> I'm really not understand why used SNI on KDE if QSystemTray worked correct. It's possible hack for KDE? Use QSystemTray forcibly.

Oh, there are a check for SNI watcher accessibility. Even if QSystemTrayIcon will be used for KDE, this check is not depend on Telegram's SNI implementation. When you disabled D-Bus integration, you disabled this check and size was decreased to 22 for compatibility with XEmbed (but QSystemTrayIcon, anyway, uses SNI, since you didn't recompile Qt without D-Bus).

There are no reasons to do a check for DE and enforce QSystemTrayIcon for KDE.

**Comment by AndydeCleyre** [comment] 2020-02-13 17:55
I created colored icons so there should be no ambiguity about the colors used, yet it does not appear to use my overriding icons in `~/.local/share/icons`, on Arch with Plasma Desktop.

![image](https://user-images.githubusercontent.com/1787385/74463604-0f600780-4e60-11ea-94ba-b4e1cbd5fdd1.png)

**Comment by varlesh** [comment] 2020-02-13 17:58
we test some versions for linux and here our result:
on Gnome DE used SNI for disable blur and badge use key:
`TDESKTOP_DISABLE_TRAY_COUNTER=1`
But this not worked for KDE - badge not disabled, icon blurred.
If build tdesktop with flag `TDESKTOP_DISABLE_DBUS_INTEGRATION` icon not blurred, BUT badge not disabled & used not native notifications

**Comment by SmartFinn** [comment] 2020-02-13 18:04
Workaround for GNOME Shell:

Pass `TDESKTOP_DISABLE_TRAY_COUNTER=1` environment variable to Telegram to disable converting SVG to 48px PNG.

```
$ > grep '^Exec=' ~/.local/share/applications/telegramdesktop.desktop
Exec=env TDESKTOP_DISABLE_TRAY_COUNTER=1 /home/sergei/.local/bin/Telegram -- %u
$ >
```

![image](https://user-images.githubusercontent.com/819186/74464177-c037c800-4e9b-11ea-88e9-ae2f40609940.png)

**Comment by ilya-fedin** [comment] 2020-02-13 18:32
> I created colored icons so there should be no ambiguity about the colors used

Maybe it uses your icon, but https://github.com/telegramdesktop/tdesktop/issues/7192#issuecomment-585731675?

**Comment by varlesh** [comment] 2020-02-13 19:06
@ilya-fedin `TDESKTOP_DISABLE_TRAY_COUNTER=1` not worked on KDE. badge not disabled.

**Comment by rarjpg** [comment] 2020-02-14 06:38
![image](https://user-images.githubusercontent.com/57395050/74507515-88a93a00-4ef4-11ea-977f-1ebc659f19c9.png)

Confirm the bug too.

**Comment by rarjpg** [comment] 2020-02-14 06:41
`telegram-desktop-bin` command on Arch Linux shows the correct icon for the panel while `telegram-desktop` shows a fallback one. I know I should report this to the maintainer but I drop it here just in case it helps solve the bug.

**Comment by lelik-ku** [comment] 2020-02-14 11:45
It seems that now telegram app is using /usr/share/icons/hicolor/32x32/apps/telegram.png on my host.
But now it changes the size of this icon to ~22x22

**Comment by varlesh** [comment] 2020-02-14 16:18
@ilya-fedin Ilya you see, badge not disabled on kde with `TDESKTOP_DISABLE_TRAY_COUNTER=1`. Maybe you confirm or check this bug?

**Comment by varlesh** [comment] 2020-02-14 16:21
@IsoaSFlus Maybe you use css with Highcolor kde scheme?

**Comment by varlesh** [comment] 2020-02-14 16:36
@ilya-fedin Официальный бинарник от вас 1.9.13, с последней версией. Суть такова, что в кедах значок работает на половину. Видать где-то ошибка.
Изначально доступны размеры в SVG 16/22/24px. Все они прописаны в Index.theme как Fixed - т.е. могут быть отображеным меньше или боле указаннаго размера. В коде прописан хак для HiDPI 48px, тем самым прога берет первый попавшийся значок и растягивает его до 48px. Я сейчас попробовал обхитрить  прогу и подсунул ему 22px растянутый до 48px и залил в тему. Прога нашла статусные значки для 48px и хак сработал.
![image](https://user-images.githubusercontent.com/8083855/74549795-afee1e80-4f69-11ea-80cb-ea676521c74a.png)
НО теперь проблема с бейджем осталась. Неужели его нельзя никак отрубить для кед? Хак какой-нить а? Мы ведь все хотим интеграцию в ОСь... так эта красная хреновина всё портит ((
![image](https://user-images.githubusercontent.com/8083855/74549768-a2389900-4f69-11ea-9054-7fb2019ed947.png)

**Comment by Aokromes** [comment] 2020-02-14 16:41
this is a real bug or simply users needs to update their icons / locations?

**Comment by SmartFinn** [comment] 2020-02-14 16:52
@ilya-fedin please look at these lines https://github.com/telegramdesktop/tdesktop/blob/7bf2b607f92de40fabf840e348d986509ef2c00a/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L295 https://github.com/telegramdesktop/tdesktop/blob/7bf2b607f92de40fabf840e348d986509ef2c00a/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L205, if I understand correctly, this statement explains why the counter cannot be disabled in KDE.

**Comment by AndydeCleyre** [comment] 2020-02-14 17:14
> this is a real bug or simply users needs to update their icons / locations?

I am experiencing a real bug, as I have updated the icons as instructed in #7111 and #1908, and Cuttlefish shows all the sizes resolving to my custom icons.

**Comment by IsoaSFlus** [comment] 2020-02-15 00:28
> @IsoaSFlus Maybe you use css with Highcolor kde scheme?

No, I'm using Breeze Light.
And I found that if people use dark colorscheme, telegram will follow it and not change the color of tray icon. But in light colorscheme, telegram will change it to blue.

**Comment by SmartFinn** [comment] 2020-02-15 04:42
With these changes 
https://github.com/SmartFinn/tdesktop/commit/69c8e66d9e6c2d7d8cd92221b8e790b8c3e923e0 `TDESKTOP_DISABLE_TRAY_COUNTER=1` works on KDE as espected:

![image_2020-02-15_08-13-00](https://user-images.githubusercontent.com/819186/74581917-f40b0e80-4fbd-11ea-9f27-13d31e88e875.png)

**Comment by varlesh** [comment] 2020-02-15 05:32
@IsoaSFlus  @AndydeCleyre here fixed builded binary for test:
Download this file and replace binary (create backup original binary, if needed):
https://github.com/SmartFinn/tdesktop/suites/459341316/artifacts/1875998
RUN:
`env TDESKTOP_DISABLE_TRAY_COUNTER=1 Telegram`

without `TDESKTOP_DISABLE_TRAY_COUNTER` this not be worked

**Comment by varlesh** [comment] 2020-02-15 05:42
result (Breeze theme, changed only colorscheme):
![image](https://user-images.githubusercontent.com/8083855/74582581-69370d80-4fd7-11ea-81c2-0ca1265345be.png)
![image](https://user-images.githubusercontent.com/8083855/74582594-79e78380-4fd7-11ea-824d-d2eb69066e38.png)

**Comment by varlesh** [comment] 2020-02-15 06:13
@ilya-fedin now with [this fixes](https://github.com/SmartFinn/tdesktop/commit/69c8e66d9e6c2d7d8cd92221b8e790b8c3e923e0) and hack `TDESKTOP_DISABLE_TRAY_COUNTER=1` on Gnome and KDE all worked fine:
- icon not blurred
- icon not colored to blue
- disabled badge on KDE
- icon correct applied KDE Color Scheme (it's very cool feature)

And now question: why this hack `TDESKTOP_DISABLE_TRAY_COUNTER=1` not added to button on notifications settings? It's comfortable for usage, because all DE's need this option for show correct system icons.

**Comment by ilya-fedin** [comment] 2020-02-15 15:55
> Maybe you confirm or check this bug?

Yes, I confirm

> this is a real bug or simply users needs to update their icons / locations?

there are two real bugs that are tracked by this issue:
* Icon size should be 22 at all time
* KDE prefers IconPixmap instead of IconName

> if I understand correctly, this statement explains why the counter cannot be disabled in KDE

IconPixmap should be fallback. But not in KDE :(

> And now question: why this hack `TDESKTOP_DISABLE_TRAY_COUNTER=1` not added to button on notifications settings?

As far as I know, tdesktop doesn't accept PRs that adding new settings.

**Comment by andrei-a-papou** [comment] 2020-02-17 13:38
> > > but Telegram still places a red unread message counter on top of it
> > 
> > 
> > Put `TDESKTOP_DISABLE_TRAY_COUNTER=1` into your environment variables.
> > > * Badge counter not disabled
> > 
> > 
> > It's not a bug, `Count unread messages` setting switches between chat and messages counting, as far as I know.

@ilya-fedin Thank you for the suggestion. It doesn't work for me, though.

Running v1.9.13 under Xfce 4.12. 

The line `export TDESKTOP_DISABLE_TRAY_COUNTER="1"` is in my startup script. The env var is exported (double-checked it).

The Telegram log says Qt icon is being used (_Using Qt tray icon_). The badge counter still appears over my custom icon (`~/.icons/hicolor/22x22/status/telegram-attention-panel.svg`):

![image](https://user-images.githubusercontent.com/30468319/74658698-df886b00-51a3-11ea-94f9-a5222422c289.png)

How can I debug this further?

Thanks, Andrei

**Comment by ilya-fedin** [comment] 2020-02-17 14:23
>  under Xfce 4.12

Xfce uses XEmbed tray by default, but this option is only for SNI.

Some SNI implementations for Xfce:
https://aur.archlinux.org/packages/xfce4-statusnotifier-plugin/
https://aur.archlinux.org/packages/xfce4-panel-sntray-git/
https://aur.archlinux.org/packages/xfce4-snw-plugin/
https://aur.archlinux.org/packages/xfce4-indicator-plugin/

**Comment by andrei-a-papou** [comment] 2020-02-17 14:50
@ilya-fedin Does this mean the badge counter cannot be disabled with the classic systray?

**Comment by ilya-fedin** [comment] 2020-02-17 14:55
> Does this mean the badge counter cannot be disabled with the classic systray/notificaiton area?

Yes, this feature is just for possibility to use SNI tricks like that https://github.com/telegramdesktop/tdesktop/issues/7192#issuecomment-586556905

**Comment by ilya-fedin** [comment] 2020-02-17 19:31
I just checked with the icon size of 22px...
![image](https://user-images.githubusercontent.com/17829319/74681567-9e9c5080-51bb-11ea-985e-b8d92f4a1467.png)

According to https://github.com/telegramdesktop/tdesktop/issues/7192#issuecomment-586366555, I think, it is better to leave the size of 48px.

**Comment by varlesh** [comment] 2020-02-18 05:24
my comment hack only blur icon on KDE, but it's not solve problem with colored icon (to blue) and disabling badge. 
Colored icon to blue:
![image](https://user-images.githubusercontent.com/8083855/74705875-c7116280-522e-11ea-899e-4f9a7e3d4548.png)
It's strange, but this happened with only dark icon. I think because source SVG contained CSS style... but why application color icon to highlight color and why only dark version? - it's puzzle

i'm attach archive with light and dark icons, you can test it. [tdesktop_custom_icons.zip](https://github.com/telegramdesktop/tdesktop/files/4217440/tdesktop_custom_icons.zip)

**Comment by varlesh** [comment] 2020-02-18 05:40
it's not CSS bug... i'm now remove CSS from SVG and check this:
```
<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" version="1">
 <path style="fill:#444444" d="M 40.77266,39.935232 C 41.429795,38.647628 45.205752,16.631028 45.745543,10.939689 46.329509,5.3000586 43.284642,6.3487958 40.482877,7.3015068 33.609061,9.6469735 11.87624,18.062399 5.9275456,21.200107 4.4630307,21.813785 3.8300088,22.855019 4.8956132,23.75623 c 0.9174851,0.763885 4.2747491,1.813056 6.9822938,2.345487 2.30806,0.706597 4.100858,0.02978 5.755761,-0.913553 3.977045,-2.382783 15.827739,-8.869187 16.465912,-9.291592 0.638173,-0.422405 1.336643,0.361513 0.979479,0.741012 -0.357166,0.379496 -8.750014,7.98531 -11.505578,11.424148 -1.459857,1.890827 -1.416129,2.900315 0.08356,4.092654 3.36445,2.666036 12.353579,8.743914 13.691129,9.111282 1.70558,0.468447 2.704484,0.08036 3.424493,-1.330436 z"/>
</svg>
```
Anyway dark icon show as blue:
![image](https://user-images.githubusercontent.com/8083855/74707250-b367fb00-5232-11ea-8668-a79fa83245e4.png)

**Comment by ilya-fedin** [comment] 2020-02-18 11:55
@varlesh https://github.com/telegramdesktop/tdesktop/issues/7192#issuecomment-585731675

**Comment by ilya-fedin** [comment] 2020-02-18 18:59
> Colored icon to blue

What's now with it?

**Comment by varlesh** [comment] 2020-02-18 19:06
Now all fine... in KDE. With key `TDESKTOP_DISABLE_TRAY_COUNTER=1` - badge disabled, icon not blured and applied KDE Color scheme.
Big thx)

**Comment by ilya-fedin** [comment] 2020-02-18 19:08
> With key `TDESKTOP_DISABLE_TRAY_COUNTER=1`

Does icon coloring with blue without it?

**Comment by varlesh** [comment] 2020-02-18 19:09
no. Icon not colored, but blured and not applied KDE Color Scheme.

**Comment by AndydeCleyre** [comment] 2020-02-18 19:11
I could give up the badge counter, but for the record I like to have the tray icon only change color, while the item in my dock/tasklist shows a nice big badge. 

So disabling the badge completely is not ideal, but I'll take it over the miscolored tray icon.

**Comment by ilya-fedin** [comment] 2020-02-18 19:17
> no. Icon not colored,

Ok, thank you for testing
@Aokromes the issue can be closed 🥳

> so does it only disable the counter for the tray? That would be great.

Icon in taskbar didn't have counter on linux ever, there are a dbus counter api from Unity which is used by tdesktop (and other DEs, as KDE and a dock extension for GNOME), so there are no problems with the icon size in taskbar :)

**Closed** 2020-02-18 19:59 UTC
Labels: bug

**Comment by ilya-fedin** [comment] 2020-02-22 12:37
@andrei-a-papou this feature should work with XEmbed trays too since 1.9.15

**Comment by SmartFinn** [comment] 2020-02-22 12:51
@ilya-fedin the last changes broken the custom panel icon in GNOME Shell:

![image](https://user-images.githubusercontent.com/819186/75092624-63ff3300-5582-11ea-949d-42c64910bb41.png)

Passing `TDESKTOP_DISABLE_TRAY_COUNTER` variable doesn't help now.

**Comment by ilya-fedin** [comment] 2020-02-22 12:55
> the last changes broken the custom panel icon in GNOME Shell

snap, flatpak, official binary or distribution package?
Which distribution?

**Comment by SmartFinn** [comment] 2020-02-22 13:00
@ilya-fedin official Linux 64 bit: Binary from the last pre-release.

```
$ > gnome-shell --version
GNOME Shell 3.34.4
$ > cat /etc/fedora-release
Fedora release 31 (Thirty One)
$ > env | grep TDESKTOP_DISABLE_TRAY_COUNTER
TDESKTOP_DISABLE_TRAY_COUNTER=1
```

On the previous version (1.19.14) works file when `TDESKTOP_DISABLE_TRAY_COUNTER` env variable passed.

**Comment by varlesh** [comment] 2020-02-22 13:09
For INFO: Pre 1.9.15 on KDE worked fine.

**Comment by ilya-fedin** [comment] 2020-02-22 13:23
Oh, I added a fallback for tray icon to prepare it for possible option in the UI, but Qt can't read icon theme settings from anything but Qt
https://github.com/qt/qtbase/blob/5.12.5/src/platformsupport/themes/genericunix/qgenericunixthemes.cpp#L346
Distribution packages can use platform theme plugins, but static binary not. :(
The best option is switch to distribution package if you want full system integration.
I'll try to grab the qt5ct platform theme plugin from qt5ct and link it with tdesktop statically.

**Comment by andrei-a-papou** [comment] 2020-02-22 14:56
> @andrei-a-papou this feature should work with XEmbed trays too since 1.9.15

Thanks a lot! Can't wait to test!

**Comment by andrei-a-papou** [comment] 2020-02-22 15:03
> @andrei-a-papou this feature should work with XEmbed trays too since 1.9.15

Happy to report that under Xfce 4.12 (xfce4-panel 4.12.1, classic notification area) tdesktop v1.9.15-pre (static binary) works fine with custom icons.

**Comment by ilya-fedin** [comment] 2020-03-12 13:03
> official Linux 64 bit: Binary from the last pre-release.

[I added](https://github.com/telegramdesktop/tdesktop/pull/7370) a new `TDESKTOP_FORCE_PANEL_ICON` variable. It will restore the previous behaivor.
It will work only with SNI, because with SNI icon is rendered by panel and panel can use system theme even if app can't. With XEmbed icon is rendered by app and if app can't find icon, then it won't displayed anyway, i.e. there is no sense for such variable with XEmbed.

If PR will be accepted, you can use this variable to get system icon.
Warning: if your icon theme doesn't have this icon, you will get empty space or a dummy icon (that's why it is a variable).

**Comment by Darkhogg** [comment] 2020-03-18 09:23
As of 1.9.21 I'm seeing the non-themed icon again, with both `TDESKTOP_FORCE_PANEL_ICON=1` and `TDESKTOP_DISABLE_TRAY_COUNTER=1`, has anything else changed that we should be aware of?

**Comment by ilya-fedin** [comment] 2020-03-18 12:34
TDESKTOP_FORCE_PANEL_ICON works only with SNI trays, check if your tray is SNI tray (the icon should have native menu, not telegram one).

**Comment by Darkhogg** [comment] 2020-03-18 12:58
It is, I'm using the XFCE4  "Status Notifier Plugin".
I just tried to downgrade to the previous version and it works, so it's something introduced between 1.9.14 and 1.9.21 that's causing this for me.

**Comment by ilya-fedin** [comment] 2020-03-18 13:02
Oh, looks like the option is broken.
#7414

**Comment by ilya-fedin** [comment] 2020-05-05 13:07
I'm just want to say that v2.1.2 will finally get qt5ct support :partying_face: 
I also tried to add lxqt plugin, but got a conflict with Qt5Gui symbols (they copied class from it).
And I wanted to add Kvantum support, but encountered into license troubles (Kvantum is licensed under GPL3 which is incompatible wth OpenSSL, tdesktop has OpenSSL exception in the license)

**Comment by ilya-fedin** [comment] 2020-06-03 15:04
Starting with v2.1.8 static binary supports system icon even on gtk-based environments without qt5ct

**Comment by KebabLord** [comment] 2020-10-05 17:27
reminder of that adding the disabletray option to bashrc or profile doesn't work when setting env variable. 
first check if it works for disabling badge counter by
```env TDESKTOP_DISABLE_TRAY_COUNTER=1 `which telegram` ```
if it works, make it persistent by adding it to the 
```sudo echo TDESKTOP_DISABLE_TRAY_COUNTER=1 >> /etc/environment```
