### ISSUE TITLE
Sending transparent image with @bing bot

### ISSUE THREAD

**Issue by hectorlinarestascon** [telegramdesktop/tdesktop#3032] opened 2017-02-19 17:19 UTC
### Steps to reproduce
1. Write: "@bing why not" and select the image that have transparent background.
2.  Send image.
3.  See that the image does not arrive, the clock is on the message.

### Expected behaviour
Image sent.

### Actual behaviour
Image not sent.
Telegram desktop becomes slower.
If you delete the message with image, telegram desktop becomes faster again.

### Configuration
**Operating system:**
Windows 10.
**Version of Telegram Desktop:**
1.0.6
![captura de pantalla 2017-02-19 18 15 53](https://cloud.githubusercontent.com/assets/22228648/23104524/e2b63938-f6cf-11e6-8cf7-4a399bd742bd.png)

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment] 2017-02-19 17:24
Also reproducible on 1.0.12

**Comment by angelskieglazki** [comment] 2017-08-05 21:44
Operating system:
Ubuntu 16.04
Linux den 4.4.0-83-generic
Version of Telegram Desktop:
1.1.19

Also reproducible.

**Comment by 23rd** [comment] 2019-07-18 16:44
Hm, I think it was fixed on the server side. At least now I can't reproduce this bug.

**Comment by 23rd** [comment] 2019-07-18 17:07
Please reopen if it still occurs.

**Closed by 23rd** 2019-07-18 17:07 UTC
Labels: bug
