### ISSUE TITLE
I don't want the "Allow notification dots" to appear in the computer toolbar.

### ISSUE THREAD

**Issue by timmy61109** [telegramdesktop/tdesktop#9001] opened 2020-11-06 04:14 UTC
### Is your feature request related to a problem?
Yes

### Describe the solution you'd like
I don't want the "Allow notification dots" to appear in the computer toolbar.

![2020-11-06 12-06-10 的螢幕擷圖](https://user-images.githubusercontent.com/38396747/98325104-fb30eb80-2028-11eb-8681-7bcd9dfb39b5.png)

![2020-11-06 12-10-13 的螢幕擷圖](https://user-images.githubusercontent.com/38396747/98325190-2b788a00-2029-11eb-865d-e5a1d9dd3606.png)

### Describe alternatives you've considered
I hope to cancel the displayed notification from the "settings".

![2020-11-06 12-12-24 的螢幕擷圖](https://user-images.githubusercontent.com/38396747/98325345-90cc7b00-2029-11eb-9165-e5e2d030f98a.png)

**Comment by ilya-fedin** [comment] 2020-11-06 04:18
There should be a switch in your system (addon?) settings

**Comment by ilya-fedin** [comment] 2020-11-06 04:19
Anyway, duplicate of #6721

**Comment by timmy61109** [comment] 2020-11-06 09:54
@ilya-fedin It is the toolbar, not the notification bar. The toolbar cannot be set, but the notification bar can

**Comment by ilya-fedin** [comment] 2020-11-06 09:56
@timmy61109 there are no option for any of them and if it would be implemented, it will disable the counter on both of them I guess

**Comment by timmy61109** [comment] 2020-11-06 10:02
> @ timmy61109它們中的任何一個都沒有選項，並且如果將其實現，它將在兩個對像上禁用計數器

Ok, got it

**Comment by Aokromes** [comment] 2020-11-09 12:20
so, cannot be implemented?

**Comment by timmy61109** [comment] 2020-11-09 14:34
Shouldn't it should be

**Comment by ilya-fedin** [comment] 2020-11-09 18:31
> so, cannot be implemented?

It could be, but this is a duplicate of #6721

**Closed** 2020-11-09 19:07 UTC
