### ISSUE TITLE
Thai font broke after upgrade to v4.6.0

### ISSUE THREAD

**Issue by icez** [telegramdesktop/tdesktop#25825] opened 2023-02-04 06:15 UTC
### Steps to reproduce

With reference to issue https://github.com/telegramdesktop/tdesktop/issues/7845 . The situation is about the same. The previous stable version on Windows OS seems to use Tahoma for displaying Thai language but on v4.6.0 it seems to change to another font which cause Thai word to be too small compare to other.

v4.6.0
https://imgur.com/rvIdiAF

v4.5.3
https://imgur.com/o27t0T9

### Expected behaviour

v4.5.3
https://imgur.com/o27t0T9

### Actual behaviour

v4.6.0
https://imgur.com/rvIdiAF

### Operating system

Windows 11

### Version of Telegram Desktop

v4.6.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2023-02-04 06:44
The v6.4.0 link is unavailable, it's better to load images on github. But there indeed was a change in retrieving default system font for better UX on High-DPI, the used API is upgraded from Windows XP one to the Windows 7 one. So I don't think it's really broken, just a more modern font is used.

**Comment by icez** [comment] 2023-02-04 06:50
Re-uploaded here:

v4.6.0
![rvIdiAF](https://user-images.githubusercontent.com/568485/216753367-84735649-9bb2-4115-a528-dfc72b825bde.png)

v4.5.3
![o27t0T9](https://user-images.githubusercontent.com/568485/216753385-43cf2e51-4e5d-45ec-9c40-584461944711.png)

It looks like the default system font detected is not optimal to use on low DPI screen. Is it possible to force/change font setting in the app?

**Comment by ilya-fedin** [comment] 2023-02-04 06:52
No, it's not possible to change font and adding such an option is non-trivial and is not planned (#99). The API change is backported from Qt 6, can you check any Qt application (e.g. qBittorrent has Qt 6 builds)? If its font is good then maybe the backport is incomplete, if it's the same, it's better to report to Qt and when Qt developers produce a fix, it coulf be backported.

**Comment by icez** [comment] 2023-02-04 07:03
Not sure if the user-generated content will be fine but UI looks fine to me. qTorrent 4.5.0 running on Windows 11 & change app language to Thai.

![c-20230204-140142](https://user-images.githubusercontent.com/568485/216753924-3e31a691-110e-4e94-8df6-9540db053b00.png)

**Comment by ilya-fedin** [comment] 2023-02-04 07:03
Does it use another font or just the text is bigger?

**Comment by ilya-fedin** [comment] 2023-02-04 07:38
Also, are you sure you checked qBittorrent built with Qt 6 exactly? Qt 5 version would use the legacy API tdesktop used prevoiusly.

**Comment by icez** [comment] 2023-02-04 07:43
I just noticed that I downloaded the qt5 version. Here's from Qt 6. So this seems to be Qt6 problem.

![image](https://user-images.githubusercontent.com/568485/216755479-90cc6c77-f65e-4161-b1d1-6ccffed80963.png)

**Comment by ilya-fedin** [comment] 2023-02-04 07:46
btw, I just checked and I can't reproduce your problem, so it might be that some additionally installed fonts (that may happen even automatically by installing software) caused this. So prepare that Qt developers may not reproduce your problem when you will report this to them and you will have to find what installed the breaking font by installing Windows into VM and installing software you use or copying your host fonts into it.

**Comment by ilya-fedin** [comment] 2023-02-04 07:57
You can also try the Linux font render by typing `freetype` [cheat code](https://github.com/telegramdesktop/tdesktop/wiki/Cheat-Codes)

**Comment by tehcneko** [comment] 2023-02-04 10:32
Are you using a multi-display setup?

**Comment by ilya-fedin** [comment] 2023-02-04 10:34
If the question is for me then the answer is no

**Comment by icez** [comment] 2023-02-04 10:40
Tried 'freetype' & back to GDI. No difference. 

I've checked with many friends and they're all having this problem. I'll try changing the default Windows font and see if there's any change to this. I'll report back later

**Comment by ilya-fedin** [comment] 2023-02-04 10:58
Hmm, maybe it's a font that is present only in Thai version of Windows? Changing default font is unlikely to help, what you see is likely to be caused by Qt's fallback logic that just tries all the fonts in the system in alphabetical order and picks up the first one that claims to have a glyph for the character.

**Comment by likecyber** [comment] 2023-02-04 12:12
> Hmm, maybe it's a font that is present only in Thai version of Windows? Changing default font is unlikely to help, what you see is likely to be caused by Qt's fallback logic that just tries all the fonts in the system in alphabetical order and picks up the first one that claims to have a glyph for the character.

This is true, I used the software to copy and rename the font name of "Tahoma" to "_Tahoma" and install it on my Windows.
The Telegram Desktop app does take effect by the copied fonts, now it looks like the previous version!

If anyone wants to copy and rename the font name, you can use the software named "FontForge" or "Typograf".
Make sure to do it both on tahoma.ttf and tahomabd.ttf.
Otherwise, it may look weird on some parts of the Telegram app.

**Comment by iBug** [comment] 2023-02-04 12:14
I'd like to add that a popular workaround for Chinese font issue on English systems is also broken in v4.6.

In English installations of Windows 10, the default font fallback lists all put Microsoft JhengHei (MSJH, Japanese font) above Microsoft YaHei (MSYH, Simp./Trad. Chinese), causing streams of Chinese characters to be rendered in both fonts.

A common solution is editing the registry to manually prioritize MSYH over MSJH ([link](https://qamoe.cyou/2021/11/10/17/30)), which worked until TDesktop v4.6.

I have dug through the registry for hours and could not get the same solution to work anymore.

**Comment by iBug** [comment] 2023-02-04 12:17
> This is true, I used the software to copy and rename the font name of "Tahoma" to "_Tahoma" and install it on my Windows.

@likecyber Can you elaborate a bit more on this? Did you install a copy of the Tahoma font as "\_Tahoma"? Did you remove the original Tahoma font?

**Comment by likecyber** [comment] 2023-02-04 12:25
> > This is true, I used the software to copy and rename the font name of "Tahoma" to "_Tahoma" and install it on my Windows.
> 
> @likecyber Can you elaborate a bit more on this? Did you install a copy of the Tahoma font as "_Tahoma"? Did you remove the original Tahoma font (i.e. the system no longer has a font named "Tahoma")?

Yes, I did install a copy of the Tahoma font family as "_Tahoma". (tahoma.ttf + tahomabd.ttf)
I did not remove the original Tahoma font as it may break some display parts of Windows and apps.

The reason behind putting the underscore before the name is to make it the first font for alphabetical order fallback.

This way I will also have the original Tahoma and a copy of Tahoma on the same computer.
It will fix the Telegram Desktop app and also not break Windows and other apps.

**Comment by itorz7** [comment] 2023-02-04 22:57
+ same problem

**Comment by likecyber** [comment] 2023-02-05 00:32
If anyone really needs a quick fix for this issue, you may install the fonts I renamed from this repository.
This is just a temporary quick fix. The explanation can be read inside the repository.

It should work for any language that uses Tahoma as the display font in the previous version.

https://github.com/likecyber/Tahoma-For-Telegram

**Comment by tiietee** [comment] 2023-02-05 03:57
> If anyone really needs a quick fix for this issue, you may install the fonts I renamed from this repository. This is just a temporary quick fix. The explanation can be read inside the repository.
> 
> It should work for any language that uses Tahoma as the display font in the previous version.
> 
> https://github.com/likecyber/Tahoma-For-Telegram

This works so well. You save my life! Thank you soooooo much. TT

**Comment by Mynameisone** [comment] 2023-02-05 07:25
Thank you soooooo much.you good bro

**Comment by totoguy** [comment] 2023-02-05 20:44
@Aokromes You've merged the Hebrew issue with this one, but none of the suggested workarounds here resolve the Hebrew one. At least for me.

**Comment by ilya-fedin** [comment] 2023-02-06 01:36
It likely means Hebrew is a part of Segoe UI and it's not a bug.  If you don't like the font size, well, you can change scale.

**Comment by charnsak** [comment] 2023-02-06 02:40
Using Thai and also faced the same problem. 
The quick fix with renamed Tahoma work. Thank you for the work around. The small font hurt my eye so much

**Comment by icez** [comment] 2023-02-06 05:15
This issue should now be closed. I'll try submit issue to Qt.

**Comment by veer66** [comment] 2023-02-06 09:06
> This issue should now be closed. I'll try submit issue to Qt.

Please share to us the link to the Qt bug after you submit the issue.

**Comment by Artur2048** [comment] 2023-02-07 01:30
Why is this issue closed without fixing?
Yes. i know there is some workaround that allows to enlarge Thai font, but from users perspective this issue is not resolved.
(Yes I understand the problem is in the Qt library...)

I'm using Telegram long time already. After upgrading to v4.6.0 fonts became TINY for Thai language.
v4.6.1 didn't change anything as well

My solution: **I downgraded Telegram to v4.5.3 and it did resolve my problem.**

I have 2 laptops - one running Windows 11, another running Windows 10.
On both laptops i use Telegram Desktop and the Thai font since v4.6.0 became SO SMALL it was completely unreadable.
As i understand this problem also affects many other languages with "non-latin" characters.

@icez
Why is this issue closed? Please kindly reopen this ticket and fix Telegram.
even if the real "root cause" is in Qt library, it's still "a problem with Telegram" from the users perspective.
I have downloaded app from Telegram official website, it doesn't work as expected... and it used to work well until 4.5.3.
please include some fix/workaround for the "broken library" in Telegram. otherwise it will affect millions of your users.
99%+ of Telegram users don't even use Github, and most certainly don't know what Qt is :)
If they download application from official website, they expect it to work well.
v.4.6.0/4.6.1 is completely useless for people who use languages affected by this problem.
If an application is utilizing a library with broken functionality it should include some kind of workaround in the app code until the functionality in the library is fixed (even if it's "not Telegrams fault").

Please kindly consider making it work the way it used to work in 4.5.3

**Comment by ilya-fedin** [comment] 2023-02-07 05:40
> Please kindly consider making it work the way it used to work in 4.5.3

It it were so easy then that didn't exist at all. The problem is old (pre-Qt6) way of determining font doesn't work properly on Win11 with High-DPI.

**Comment by Artur2048** [comment] 2023-02-07 05:52
It doesn't work properly on Both - Windows 11 and 10.
Sure i believe it's "not Telegram fault" but "Qt fault".
... But in this case either some workaround should be introduced in
Telegram code or there should be maybe some setting that would allow users
to turn off that new feature that broke our fonts.

Believe me, everyone around here would rather look at "old, ugly, low dpi
font" rather than text which is literally 2mm high

It was working OK in 4.5.3 so... It's possible to make it work again I'm
sure

(BTW end users of windows based systems don't usually manually install Qt,
etc. They download official Telegram app from Telegram website,... And it
doesn't work.... And it used to!)

On top of that there is no solution on telegram website and no link to
download 4.5.3

If it doesn't get fixed soon you can loose a lot of users. They will switch
over to web versions, etc... (guys, we cannot read text 2mm big).

I'm IT professional, so I can try to mess up with font settings or
downgrade Telegram (I chose downgrade).
... But for "regular users" that use those "other languages" the app just
became useless

**Comment by ilya-fedin** [comment] 2023-02-07 05:55
It's not that "old ugly low dpi" font, it's that behavior of Windows has changed in new veersions and now the old API returns font size of 3px. So we're in position between bad font fallback for Thai users or unredable font size for everyone.

**Comment by Artur2048** [comment] 2023-02-07 06:04
V4.5.3 was actually readable for everyone 🙂
As I said I was forced to downgrade and now the text looks fine for me in
English and in Thai.

Also, the issue affects not only Windows 11, but also Windows 10.
(my other laptop uses Windows 10 with all the "feature updates" disabled.
Only security updates)

When I upgraded Telegram to 4.6.0 on both laptops I lost the possibility to
read Thai on both of them.

Application like this one (yes. I know... No warranty, use at your own
risk, etc) should work out of the box.
WhatsApp works
Line works
Telegram 4.5.3 works
... Telegram 4.6.x does not

I'm a big fan of telegram. I promote it and I already "converted" many
people and convinced them to create account.
... Now I'm sending GitHub links to Telegram 4.5.3 download :-(

**Comment by ilya-fedin** [comment] 2023-02-07 06:08
> V4.5.3 was actually readable for everyone slightly_smiling_face

I'm grad to hear this wasn't affecting you. This is definitely not 'for everyone' though.

**Comment by Artur2048** [comment] 2023-02-07 06:26
(it probably affects many other languages as well...)
(you could change font? Change library? Or add some settings to allow users
to "switch to the old way" somewhere).

Instead if just defending that the bug "is not in my code so it's OK",
think about millions of users you might lose if it's not fixed soon...
Please think about users, not just "my piece of code".

Looking forward for this issue to be resolved, and I'd be happy to test new
versions and provide feedback if needed.

Again, I'm really big fan of Telegram. It's my main communicator now..

(even though you might consider this issue to be some minor severity, I
assure you there are millions of people for whom it will be a blocker)

All the best,
-Artur

**Comment by ilya-fedin** [comment] 2023-02-07 06:30
> you could change font? Change library? Or add some settings to allow users to "switch to the old way" somewhere

If you ask to change the main inteface font then the answer is sadly no, this is not allowed as it's a part of the design. Adding font choosing is also not allowed as Telegram prefers to have as less options as possible. Switching from Qt library to antoher means rewriting tdesktop entirely, unrealistic. "switch to the old way" sounds like adding an option and the answer is the same as with choosing the font.

> Instead if just defending that the bug "is not in my code so it's OK", think about millions of users you might lose if it's not fixed soon... Please think about users, not just "my piece of code".

Well, no one said that, there was a try to fix this in 4.6.1 and it's mentioned in the changelog, sadly it was not successful and even introduced a regression for CJK users.

**Comment by iBug** [comment] 2023-02-07 06:36
Then why is this issue closed in the first place? From an end user's perspective, this issue is not resolved, yet you keep marking new issues as "duplicate" of this one. This only leaves users confused, and is not constructive towards a proper resolution of the actual problem.

**Comment by ilya-fedin** [comment] 2023-02-07 06:37
The issue was closed by the reporter

**Comment by iBug** [comment] 2023-02-07 06:50
> The issue was closed by the reporter

Maintainers can reopen issues regardless of who closed them.

**Comment by ilya-fedin** [comment] 2023-02-07 06:54
Well, personally I don't have the right to manage issues

**Comment by Artur2048** [comment] 2023-02-07 07:02
Exactly,

Issue should remain open until resolved or rejected (for example, if
Telegram creators decide to officially not support languages other than
English.)

Yes,there were SIMILAR issues open I've seen.. Some for different language,
etc.
... It just means there were multiple incidents caused by the same problem.
... You can just link them together i guess if they have exactly the same
root cause.

It's also important for the maintainers / developers to understand that
it's not just small cosmetic issue.
... It really renders Telegram Desktop unusable for millions of people.

Think about that please...
(and yes. There is plenty you could do in the app code apart from raising a
ticket with the Qt lib and closing this one)

**Comment by Artur2048** [comment] 2023-02-07 07:12
Please think about users first.
This (minor for you) problem makes millions of people unable to use your
app.
How's that?

And again, I'm not writing this just to argue.
I really care about Telegram future and it's ability to spread in Asia
more...
It was working well, it got broken by 4.6.0+
... That's how users will see it.
(and now they see the issue was CLOSED, and the problem declared "invalid"
/ "concerning 3rd party app")

From users perspective - they download official Telegram app from official
website and install it on "supported" OS.
... and it doesn't work (well if I can't read text because it's 2mm high,
it doesn't work).

how come 4.5.3 is still OK?

Please think about millions of users this "upgrade" affected.

**Comment by ilya-fedin** [comment] 2023-02-07 07:15
If you write this not to argue then I don't understand why do you continue to write, you were informed that an attempt to fix was attempted, but was not successful, your posts won't make the next attempt developed faster

**Comment by Artur2048** [comment] 2023-02-07 07:30
Because the status "CLOSED" suggests the issue is either resolved or
rejected... And also suggests that nothing more will be ever done.

If the "unsuccessful attempt" to fix this issue was made in 4.6.1, then the
issue should be reopened. (to assure YOUR USERS that you are still aware of
the problem, and will try to do something about it... Not just explain its
not your fault...)

If I saw the status "open" probably i would not write anything in the first
place. I would assume that issue was already raised and well documented,
and someone is working on it.

That's it.

Have a great day.
-Artur

**Comment by Artur2048** [comment] 2023-02-07 07:34
Thank you very much.

If you need any retest (with pre-release version) I'll be more than happy
to help.

Best regards,
-Artur

**Comment by nonene-n** [comment] 2023-02-07 08:14
An in-app customizable font setting would be an ideal feature to add to telegram.

**Comment by forgotPassword** [comment] 2023-02-07 08:56
+1 for the Hebrew issue. Scaling does not fix the issue. The font itself is much thinner and used to be considerably bolder, scaling does not change that. @ilya-fedin your approach to all the issues about this bug was that it's either the users problem or qt's problem. Please understand that for years the font in Telegram was ok and now it is barely readable. 99% of users don't know about this github thing and where to notify you that something is wrong. Waiting years for some other platform to fix it is not a solution. You should rollback this change.

**Comment by 7Vlad** [comment] 2023-02-07 09:35
+1 with Russian language. Same problem. Back to V4.5.3

**Comment by ilya-fedin** [comment] 2023-02-07 09:59
> You should rollback this change.

Rolling back will lead to the initial issue restored. A way to fix both issues should be found;

> +1 with Russian language.

Russian is a part of the embedded Open Sans font, it couldn't be affected.

**Comment by fordantitrust** [comment] 2023-02-07 10:28
I tested with Artifacts [One more fonts fix and fix paste from clipboard. #4442](https://github.com/telegramdesktop/tdesktop/actions/runs/4111545015). It's fixed this issue. 

I think in the next release build this should be fixed.

**Comment by john-preston** [comment] 2023-02-07 10:31
@fordantitrust Thank you for confirming.

**Comment by 7Vlad** [comment] 2023-02-07 10:37
> > You should rollback this change.
> 
> Rolling back will lead to the initial issue restored. A way to fix both issues should be found;
> 
> > +1 with Russian language.
> 
> Russian is a part of the embedded Open Sans font, it couldn't be affected.

not if you have several languages on computer and russian not display language. I had this problem and when I reinstall 4.5.3 the problem disappear.

**Comment by Artur2048** [comment] 2023-02-07 11:25
Yes. My windows are also not Thai.
Display language is English..
I just use multiple languages in chat.

**Comment by ilya-fedin** [comment] 2023-02-07 11:28
> not if you have several languages on computer and russian is not main display language.

You want to say tdesktop doesn't use Open Sans for Russian on your computer? If yes, can you provide log.txt from `%APPDATA%\Telegram Desktop`?

**Comment by tarkungZZ** [comment] 2023-02-07 14:27
After update this issue happen to me as well.

**Comment by 7Vlad** [comment] 2023-02-07 15:45
> You want to say tdesktop doesn't use Open Sans for Russian on your computer? If it doesn't, can you provide log.txt from `%APPDATA%\Telegram Desktop`?

[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2023.02.07 11:34:22] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'

**Comment by 7Vlad** [comment] 2023-02-07 16:01
> Can you provide the full log?

I don't want to filter my "private" parts, but if you tell exactly what are you need, I can provide it

**Comment by Ai-Himmel** [comment] 2023-02-07 17:15
The same broke for text in Chinese on Simplified Chinese system.
All chinese font became SimSun.

**Comment by ilya-fedin** [comment] 2023-02-07 17:47
@7Vlad the log.txt has no private parts

**Comment by biaocy** [comment] 2023-02-08 05:08
> The same issue for text in Chinese on the Simplified Chinese system. Font for Chinese became SimSun. A workaround provided by community is here Save as `something.reg` file and run. Users in other language can changed the alias font as you like. **IT WOULD WRITE SOMETHING TO YOUR REGITRY, USE AT YOUR OWN RISK**
> 
> ```reg
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
> "DAOpenSans"="Microsoft YaHei UI"
> "DAOpenSansBold"="Microsoft YaHei UI Bold"
> "DAOpenSansBoldItalic"="Microsoft YaHei"
> "DAOpenSansRegular"="Microsoft YaHei"
> "DAOpenSansRegularItalic"="Microsoft YaHei"
> "DAOpenSansSemibold"="Microsoft YaHei"
> "DAOpenSansSemiboldItalic"="Microsoft YaHei"
> "DAVazir"="Microsoft YaHei"
> "DAVazirBold"="Microsoft YaHei Bold"
> "DAVazirMedium"="Microsoft YaHei Light"
> "DAVazirRegular"="Microsoft YaHei"
> ;; Priority font resolving: "Cascadia Mono", "Consolas", "Liberation Mono", "Menlo", "Courier"
> ;; Override monospace font:
> "Cascadia Mono"="Consolas"
> ```

Fix Chinese font issue

**Comment by CurtisWong458** [comment] 2023-02-08 06:38
> 

Has the latest version 4.6.2 fixed this BUG?

**Comment by boypt** [comment] 2023-02-08 08:16
> 



> ```reg
> DAOpenSans
> ```

People ask if this reg file affects the system fonts. yes and no.

Yes, because the patch is applied to the Windows font replacement mechanism. But this patch is meant to replace those fonts that start with "DA", e.g. "DAOpenSans".

So the patch only affects Telegram for those fonts starting with "DA" are ALL of Telegram custom font, no other programs will be affected.

**Comment by 7Vlad** [comment] 2023-02-08 08:28
> @7Vlad the log.txt has no private parts

Of course, it has. Like full path to Telegram directory, full path to taskbar and ALL list of your applications pinned to taskbar, etc.
So, what exactly you need from my log?

**Comment by 7Vlad** [comment] 2023-02-08 08:40
> I believe it should contain more lines about fonts starting with "Fonts Info:" and "Font Error:" if the font failed to load
This is what I assumed and therefore all the lines with the word "font"/fonts, I copied above

**Comment by likecyber** [comment] 2023-02-09 00:14
Version 4.6.2 seems to fix the issue of Thai language for me as well.

Anyone who installs my quick fix can remove the fonts and update the Telegram Desktop app to 4.6.2 now.

**Comment by Artur2048** [comment] 2023-02-09 01:18
Yes.
4.6.2 seems to fix it for me as well (Thai font).

**Comment by BlackMercy** [comment] 2023-02-09 05:45
I have been waiting for the fix so I stayed at 4.5.3 without updating to 4.6.0 when it was released. Now many people are confirming that 4.6.2 fixed the issue so I updated Telegram Desktop on my PC. I can also confirm that Thai font looks exactly the same as in 4.5.3.

Thanks dev team for fixing this quickly!

**Comment by iBug** [comment] 2023-02-09 06:35
I can confirm that the "workaround for Chinese fonts on English systems" is also working again, the same way as it used to in v4.5.3.

**Comment by nolykhemin** [comment] 2023-02-09 07:33
Yes guys v4.6.2 seems to fix Thai font fallback problem for me (win 11)

**Comment by 7Vlad** [comment] 2023-02-09 15:12
I am still have a problem with fonts in 4.6.2. Also in "Settings", Interface Scale now has maximum only 100% and in 4.5.3 it was 300%
![Screenshot_46](https://user-images.githubusercontent.com/111490433/217852282-c2e391f5-00f0-4b02-b56c-5ed907d4cff0.jpg)
![Screenshot_47](https://user-images.githubusercontent.com/111490433/217852311-0ddec17d-09db-4cf5-bd65-345613299a25.jpg)

**Comment by ilya-fedin** [comment] 2023-02-09 15:16
Can you provide the screen of broken font? For scaling issue provide logs in #25856

**Comment by 7Vlad** [comment] 2023-02-09 15:31
> Can you provide the screenshot of broken font?

As you can see on my screenshots (and this is not actual size, because github enlarge the image), first image fonts is smaller than second. The size was the same on 4.6-4.6.1, but scale was "300%", now, in 4.6.2, it was "fixed", so its show 100% instead of 300%. The key for shortcut "-scale 125" didn't work at all.

**Comment by ilya-fedin** [comment] 2023-02-09 15:32
This doesn't seem to be related to fonts and this issue, it's interface scale

**Comment by 7Vlad** [comment] 2023-02-09 15:37
> This doesn't seem to be related to fonts and this issue, it's interface scale

So fonts issue was "fixed" with replacing maximum interface scale from 300% to 100%? 
But, for me, as for user, nothing was changed, because interface/font still smaller than it was on 4.5.3., as you can see on my actual screenshot. It doesn't matter for me, how you called this issue, I am only want my font size/interface scale back.

**Comment by ilya-fedin** [comment] 2023-02-09 15:40
@7Vlad no, you hae a completely another issue

**Comment by 7Vlad** [comment] 2023-02-09 15:43
> @7Vlad no, you have a completely another issue, please discuss it in the respective ticket

here https://github.com/telegramdesktop/tdesktop/issues/25856 ?

**Closed** 2023-02-09 16:49 UTC
Labels: bug, waiting for answer, 3rd party issue
