### ISSUE TITLE
Add option to replace window frame with header bar

### ISSUE THREAD

**Issue by EuriNaiz** [telegramdesktop/tdesktop#17161] opened 2021-10-31 06:07 UTC
### Is your feature request related to a problem?

Actually by default telegram uses a window frame, we can check an option to use the native window frame, and that's good for some DEs, but that's not the optimus...

The appearance is bad in GNOME, XFCE, Pantheon (Elementary OS Desktop Environment) and other DEs who use CSD.

### Describe the solution you'd like

Some solution could be adding an option to use a header bar instead window frame and tick it by default when a XFCE or GNOME installation is detected.

Something like that:

![telegram with header bar instead window frame](https://blogs.gnome.org/tbernard/files/2018/01/telegram-csd.png)

### Describe alternatives you've considered

Other option could be bring [telegrand](https://github.com/melix99/telegrand) as official telegram client as Telegram For GNOME the same way you bring us a special telegram client for MacOS.

Or, why limit us with gnome, it could be Telegram For GNUs.

(a positive and advantageous point is that telegrand is GTK)

### Additional context

[This GNOME blog post](https://blogs.gnome.org/tbernard/2018/01/26/csd-initiative/) could be useful

**Comment by ilya-fedin** [comment] 2021-10-31 06:12
First of, it's a duplicate of #4358
Second of, there's no plan to implement a headerbar AFAIK
Third of, no one here can help you with oficializing a client

**Comment by john-preston** [comment] 2021-10-31 06:35
Such redesign is not planned, sorry.

I don't know anything about telegrand, but I'm sure 99% that it won't be made official for a bunch of reasons.

**Closed by john-preston** 2021-10-31 06:35 UTC
Labels: enhancement
