### ISSUE TITLE
[Bug] Can't see my own title in a supergroup

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#6435] opened 2019-08-22 11:51 UTC
### Steps to reproduce
1. Have a title (new telegram update) in a group
2. Send a message

### Expected behaviour
See your title near your message

### Actual behaviour
No title is seen
![immagine](https://user-images.githubusercontent.com/6240983/63512352-eaf42580-c4e3-11e9-96cd-7f9cec9ed229.png)

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 1.8.2

**Used theme**: Dark

**Comment by MasterGroosha** [comment] 2019-08-22 16:19
Like you also don't see "admin" title as before. Not sure it's a bug. Same thing on Android & iOS

**Comment by Remu-rin** [comment] 2019-08-22 17:38
Bug is that you can't see titles in Manage Group (if you don't have rights to edit) and in member list, when you can on Android. #6392

**Comment by ArmeF97** [comment] 2019-08-23 12:50
> 
> 
> Like you also don't see "admin" title as before. Not sure it's a bug. Same thing on Android & iOS

There was not title then, but now there is. As I read the feature, also my title should be displayed

**Comment by MasterGroosha** [comment] 2020-10-24 09:38
I think it's not a bug, however #6392 is definitely a bug

**Comment by ilya-fedin** [comment] 2020-11-04 15:56
> I think it's not a bug, however #6392 is definitely a bug

I agree that this looks like a duplicate of #6392

**Closed** 2020-11-04 15:59 UTC
Labels: enhancement
