### ISSUE TITLE
Trailing exclamation marks in pasted urls are not recognized as part of url

### ISSUE THREAD

**Issue by Artboomy** [telegramdesktop/tdesktop#5800] opened 2019-03-16 10:35 UTC
### Steps to reproduce
1. Send a message with url [https://en.wikipedia.org/wiki/Surely_You%27re_Joking,_Mr._Feynman!](https://en.wikipedia.org/wiki/Surely_You%27re_Joking,_Mr._Feynman!)
2. Copy an url with right-click - Copy Link
3. Paste in notepad

### Expected behaviour
Url contains trailing "!" symbol
### Actual behaviour
Url does not contain trailing "!" symbol
### Configuration
**Operating system:**
Windows 7 x64
**Version of Telegram Desktop:**
1.5.15
**Used theme**:
Dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by WrongBit** [comment] 2020-01-29 16:40
It seems parsing URLs is a big pain for Telegram developers, because it fails on another symbol too - on double quot ("). Say, if you take link from google map, it fails on nearest double quot:

![Capture](https://user-images.githubusercontent.com/15650524/73376858-c9833b00-42c6-11ea-95f8-b8cee76ffc15.PNG)

**Comment by Remu-rin** [comment] 2020-10-24 14:13
Not resolved.

**Comment by WrongBit** [comment] 2020-10-25 09:52
Hey, anybody work on the problem? Guys, don't play gods of regexp - just allow URL to be anything like "http:// ... and till first space". It's enough and quite simple.

**Comment by Remu-rin** [comment] 2021-04-23 16:14
Still relevant.

**Comment by WrongBit** [comment] 2022-04-19 20:17
We need bug to be fixed! Stop closing bugs like they never exist! FIRST fix and only then - close!

**Comment by Remu-rin** [comment] 2022-10-17 14:49
Not resolved.

**Comment by LexaGV** [comment] 2022-10-17 18:59
Switch off that stupid bot! It MUST NOT touch our bugs! We spent time to file a bug, now is YOUR RESPONSIBILITY to confirm bug and assign responsible developer. Where is all of that??

**Comment by john-preston** [comment] 2022-10-17 20:55
@LexaGV There are no responsible developers :(

**Comment by ilya-fedin** [comment] 2022-10-17 23:19
@LexaGV if it won't touch bugs, there will be a lot of issues no one has interest in (either because the bug disappeared on its own what happens quite often or because the reporter lost interest), so the amount of issues will just grow endlessly

**Comment by LexaGV** [comment] 2022-10-18 10:52
@ilya-fedin : it's a bug, it was actual at the moment people register it. It's not question of "interest"! Responsibility of dev.team is check this bug and put in definite state - "confirmed/not-a-bug/couldn't-reproduce/fixed/etc". ATM I see just negligent work of team who even didn't look at the problem. In any case ONLY HUMAN must remove/close bugs, because it requires HUMAN WORK. It's not a wishlist, but list of bugs where EACH of them should be properly handled.
Did I explain smth new for you??

**Comment by ilya-fedin** [comment] 2022-10-18 11:07
@LexaGV there's unfortunately no enough humans to check every report, so without bots the issue tracker will become a trash

**Comment by ilya-fedin** [comment] 2022-10-18 11:11
I don't see a problem. If a bug bothers anyone, the reporter will respond to the bot's request. If there's no one to respond to the bot, it means the issue just takes place in the list, it's not even clear whether it still happens or not.

**Comment by LexaGV** [comment] 2022-10-18 11:16
@ilya-fedin It looks like you mix roles of people in the project. Nobody owes you to monitor YOUR bugs! It's strictly their GOODWILL (read dictionary what's that) to report about bugs. Literally they do YOUR job on testing software. And once people register bugs, you should RESPECT people's work and take all efforts to fix the bug. Or AT LEAST check the bug and mark it with appropriate status.
I repeat: people do YOUR job for which you get salary. Be respectful to their efforts and do not remove bugs automatically - each bug MUST be processed by your team.

**Comment by ilya-fedin** [comment] 2022-10-18 11:16
@LexaGV I'm a volunteer

**Comment by john-preston** [comment] 2022-10-18 11:18
@LexaGV The URLs in text are parsed (and highlighted) by the server, so this report belongs to https://bugs.telegram.org, nothing to do in Telegram Desktop for it. Sorry.

**Comment by ilya-fedin** [comment] 2022-10-18 11:18
tdesktop project doesn't have enough manpower to handle every bug people report everyday, that's the reality. So bots are a must like you that or not.

**Comment by LexaGV** [comment] 2022-10-18 11:18
@ilya-fedin Sure! Because professional developer will never say "bug is a problem of user". It's a problem of DEVELOPER. I'm shocked Durov has so negligent team who just autoclose bugs(!!!!). It's even worse than MS.

**Closed by john-preston** 2022-10-18 11:18 UTC
Labels: bug

**Comment by ilya-fedin** [comment] 2022-10-18 11:21
Well, GitHub is community-based, if you want your reports to be handled by people on salary, feel free to use the bug platform (mentioned by preston). There's also in-app support that will handle your reports like support if you like that, but people there are vollunteers, too.

**Comment by LexaGV** [comment] 2022-10-18 11:22
@john-preston Please don't explain to USERS which hoops they should jump! Where URL is parsed and any internal algorithms is strictly DEVELOPER's business. If you decide it's server problem, just forward bug to appropriate team! NOT USER must deal with that.

**Comment by ilya-fedin** [comment] 2022-10-18 11:23
@LexaGV it's a normal behavior when GitHub reporters forward bugs on themselves to relevant upstream, that's how open source works. If you want your reports to be handled like business product, there's support.

**Comment by john-preston** [comment] 2022-10-18 11:25
@LexaGV Ok, I won't explain, sorry.

**Comment by LexaGV** [comment] 2022-10-18 11:30
@ilya-fedin Even "open-source" developers should keep in mind: user is "simple guy" who completely unaware of software structure. He has "desktop app" and bug appears in this program. Period. If "community" wants to make s/w better, they should take care of bugs, NOT AUTOCLOSE THEM. Don't be like ostrich who hides from problems - you just postpone problems, not eliminate 'em. That's why I ask to behave professionally - switch OFF stupid bot and handle errors HUMAN way.

Just keep in mind: people's patience is limited. If you "throw away" even those small amount of people who REPORTS about bugs, you'll finish without reports AT ALL. Or even worse - like ICQ.

**Comment by ilya-fedin** [comment] 2022-10-18 11:34
@LexaGV GitHub is a platform to report issue to developers by developers. For "simple guys", there's in-app support and the official bug & suggestion platform. It seems you've just chosen the wrong place, meant not for you.

What about the bot, there's unfortunately no sense in disabling it as long as there's no enough manpower, most reports are invalid (e.g. temporary bugs due to server load problems) or are about intended behavior, so without the bots the issue tracker will become a trash very fast.

**Comment by ilya-fedin** [comment] 2022-10-18 11:35
It's better if people will report it again so it comes to the eye than if the issue will just reside with no activity.
