### ISSUE TITLE
Add "Instant View" feature to Telegram Desktop [Feature Request] 

### ISSUE THREAD

**Issue by krunkerista** [telegramdesktop/tdesktop#7946] opened 2020-05-25 19:06 UTC
### Is your feature request related to a problem?
At the moment, when someone sends you a link, it will be opened in the browser when you click on it.

### Describe the solution you'd like
A more convenient way would be to add "Instant View" option so that the webview of the website opens within the app. The mobile version of Telegram has this option.

**Comment by RememberTheAir** [comment] 2020-05-25 19:10
Duplicate of #3492

**Closed** 2020-05-25 19:40 UTC
