### ISSUE TITLE
Can't change recording device under Linux/PulseAudio

### ISSUE THREAD

**Issue by meltylang** [telegramdesktop/tdesktop#2231] opened 2016-07-06 11:55 UTC
### Steps to reproduce
1. Install external sound card or webcam
2. Make this external card default (fallback) recording device using pavucontrol
3. Make old card output-only (e.g. analog stereo output instead of analog stereo duplex)
4. Launch Telegram 
5. Try to record audio message
### Expected behaviour

Message recorded from webcam mic.
### Actual behaviour

Telegram will use old device or show error message "Could not send  an empty file :("  <very sad face though>. Skype on this machine works just fine.
### Configuration

**Operating system:**
Debian 8.5+backports, Linux 4.6.1-1~bpo8+1 x86_64, pulseaudio 7.1, KDE 4.14

**Version of Telegram Desktop:**
0.9.51
### Logs

Console messages:

> Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
> Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
> Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
> Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
> Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
> Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
> AL lib: (EE) LoadHrtf: Could not open default-48000.mhr
> AL lib: (EE) GetHrtf: Incompatible format: Stereo 48000hz
> QXcbWindow: Unhandled client message: "_QTCURVE_ACTIVE_WINDOW_"
> [libopus @ 0x7fd1fc017b10] Warning: not compiled with thread support, using thread emulation
> [opus @ 0x7fd1fc017140] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.

[log_20_45.txt](https://github.com/telegramdesktop/tdesktop/files/349674/log_20_45.txt)

**Comment by z3ntu** [comment] 2016-07-12 10:38
Does changing the **output** device of Telegram work for you?

**Comment by Erusy** [comment] 2016-07-12 12:59
No, I can't change output device for Telegram.

**Comment by z3ntu** [comment] 2016-07-12 13:12
Okay then I also experienced this issue.

**Comment by DrLuke** [comment] 2016-08-08 22:12
A workaround is to set the fallback device and then restart telegram. It will choose the fallback device when it starts.

**Comment by Erusy** [comment] 2016-08-16 05:10
Kind of solution:
Updated to Debian Testing + Pulseaudio 9.0, and then old caches break PA.
Cleaned old caches by next command:
`$ rm -r ~/.pulse ~/.pulse-cookie ~/.config/pulse`
Now when you set fallback device and restart telegram it will respect new settings.

**Comment by Erusy** [comment] 2016-08-16 05:21
After reboot TG again forget about selected device and do not want to user fallback device.

**Comment by z3ntu** [comment] 2016-09-02 15:24
Maybe duplicate of #776

**Comment by Erusy** [comment] 2017-02-02 02:59
Version 1.0.5 seems to respect pulseaudio settings.
PA version 10.0
Debian Testing (aka 9.0 Stretch)

**Comment by Bleuzen** [comment] 2018-03-09 15:13
I also have this problem with Telegram 1.2.8 on Manjaro Linux.
I can't get it to record from my 'real' mic. It always starts recording from my 'Monitor of ...'.
If I go into pavuctl and change it to my mic, it directly resets itself to the 'Monitor of ...' input. So Telegram forces this. I can't change the input device for that recording stream. With other applications, this is possible, but not with Telegram.

Also an option in Telegram to choose a mic would be nice. Because I for example have my webcam and my 'real' mic and there is currently no way to switch between them.

**Comment by stefan-reich** [comment] 2018-08-24 12:56
I also can't use my external mic for Telegram voice messages.

Can't this be fixed?

**Comment by Erusy** [comment] 2018-08-24 13:41
This issue can't be fixed until it's not affecting core developers, as it is for many other projects running on linux desktop.
My workaround is just switching to macOS and forgeting about desktop linux like it was a bad dream.

**Comment by 0xpr03** [comment] 2018-12-10 17:45
Same problem here on Ubuntu 18.04 in Pulse Audio trying to select audio output device.
Works for another person on KDE Neon.. (which also has an ubuntu base)

**Comment by iKoze** [comment] 2019-01-29 08:03
Bug persists on Ubuntu 18.04 with Telegram 1.5.8

**Comment by ShrewdSpirit** [comment] 2019-03-12 11:54
Same issue with pulseaudio 12.2 and telegram 1.5.15 on Manjaro.
Other programs use the fallback device but telegram ignores pavuctrl options

**Comment by logicinu** [comment] 2019-09-25 13:58
Same issue with pulseaudio 13 and telegram 1.8.8 on Archlinux.

**Comment by arlyoneel** [comment] 2019-10-19 21:07
> This seems to be an inherent issue depending on the audio engine you use. I know exactly one other system that has this problem: Minecraft, java edition. Every other system seems to use the pulse audio API, except these two, where you have to disable all other devices except for the one you want them to use. Then these applications will stick with them forever (accidentally unplugged your device ? restart the application ).

I do not agree, I solve the problem that has an issue with some programs. In the case of MC and Telegram issue is simple you need to enable this configuration in your system:

> # Create a config file for openalsoft that allows the source to move
# but still uses the wrong default
# ~/.alsoftrc
[pulse]
allow-moves=yes

After this you can switch on the fly ACTIVE streams, e.g. calls is easy because the stream do not depend of your mouse, different is when you need to change device of a recording audio. In KDE/Plasma you can change it but only is active, when I release the audio record button, stream stops and I cannot change the stream device input, and the funny thing is that stream is not using even the default device, is so weird.

May some of you do not notice but, there is a call specific options that are not in global settings, you need to go to call-> and then setting. This settings are useful to change device streams using test microphone option either with system device switch or the telegram option listed there.

I leave this half solution that may will be useful. I'm still with the issue of recording audios with correct device.

**Comment by sTiKyt** [comment] 2020-03-01 19:14
Now they have settings and ability to change recording device, and you know what? Test works great! But it still records with internal microphone...

**Closed** 2020-03-10 07:49 UTC
Labels: bug

**Comment by IlyaIndigo** [comment] 2020-09-23 09:44
https://github.com/telegramdesktop/tdesktop/issues/5380
My issue 5380 was recognized as a duplicate of this and still does not work for me.
Should I have a new issue?

**Comment by 0xpr03** [comment] 2020-09-23 11:06
> Create a config file for openalsoft (~/.alsoftrc or /etc/openal/alsoft.conf). This will allow to seamsly change your sound output/input on the fly.
> 
> > [pulse]
> > allow-moves=yes
> 
> After this you can switch on the fly ACTIVE streams, but may not really changes default option in some cases, e.g. calls is easy because the stream do not depend of your mouse, different is when you need to change device of a recording audio. In KDE/Plasma you can change it but only if its active, when I release the audio record button, stream stops and I cannot change the stream device input, and the funny thing is that stream is not using even the default device, is so weird.
> 
> May some of you do not notice but, there is a call specific options that are not in global settings, you need to go to call-> and then setting. This settings are useful to change device streams using test microphone option either with system device switch or the telegram option listed there, this may solve call issue, but there is no option for test recording audio, not even here or in general settings.
> 
> I leave this half solution that may will be useful. I'm still with the issue of recording audios with correct device.
> 
> I do not agree with you because Telegram IS NOT using default device, and telegram uses two different configurations for call and record, so I dont think this is an SO or audio engine issue, is the way that telegram handles devices, may they should have a similar test and options for recording audio like they have with call settings.
> 
> PS: I'm using Manjaro Linux & Plasma

@arlyoneel Thanks! I didn't see this reply until now.. (And yes that full quote is on purpose, it's the solution.)
