### ISSUE TITLE
Telegram window doesn't open on left click on tray icon

### ISSUE THREAD

**Issue by stemar94** [telegramdesktop/tdesktop#3181] opened 2017-03-31 07:32 UTC
### Steps to reproduce
1. Close Telegram window.
2. Left click on Telegram tray icon.

### Expected behaviour
Telegram window opens up.

### Actual behaviour
The Menu pops up as if right clicked.

### Configuration
**Operating system:**
Linux xxxxxx-ThinkPad-E460 4.4.0-67-generic #88-Ubuntu SMP Wed Mar 8 16:34:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.0.26

**Used theme**:
-

**Logs**:
[log_09_30.txt](https://github.com/telegramdesktop/tdesktop/files/884815/log_09_30.txt)

**Comment by felfert** [comment] 2017-03-31 08:43
Main issue is the same here, but in addition, no menu pops up here either. When started from within a console window, upon right-click the following is printed on stderr:
````
(Telegram:27915): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
````
Telegram 1.0.26

Linux fritz.fe.think 4.9.12-100.fc24.x86_64 #1 SMP Thu Feb 23 21:29:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
This is a Fedora, but with a KDE5 Desktop.

[log.txt](https://github.com/telegramdesktop/tdesktop/files/884993/log.txt)

**Comment by Aokromes** [comment] 2017-03-31 08:58
#3177 ?

**Comment by RafaelKr** [comment] 2017-03-31 09:41
Same for me.
In the version before the expected behaviour take place.

**Comment by felfert** [comment] 2017-03-31 10:08
#3175 !

**Comment by Murray1991** [comment] 2017-04-01 13:08
Same issue here using archlinux and plasma.

**Comment by artemrizhov** [comment] 2017-04-02 23:54
Same problem, but no menu on left click, and no errors in console. It just does nothing.
I can't be sure, but I feel there was no such problem before last updates to 1.0.26/1.0.27. Also this may be related to the lates Kubuntu updates.

Ubuntu 16.04.2 LTS
KDE Frameworks 5.28.0
Qt 5.6.1

**Comment by thpar** [comment] 2017-04-03 13:00
I'd like to weigh in on this bug, as it's quite an annoying little one. Left-clicking the tray icon indeed stopped bringing up the client, so I have to be careful not to minimize it to tray anymore.
Also right-clicking doesn't show any menu anymore.

I noticed this regression after the update to 1.0.27

Left click doesn't do anything. Right click gives the error as described above by @felfert 

Fedora 24
KDE Frameworks 5.32.0
Qt 5.6.2

**Comment by marcoesposito1988** [comment] 2017-04-03 13:33
I bisected the bug. The window does not appear any more on left click on the tray icon since version 1.0.15.

Kubuntu 16.04

**Comment by felfert** [comment] 2017-04-03 16:17
Can some admin please close this and mark it as duplicate of #3175.

**Closed** 2017-04-03 16:20 UTC

**Comment by stemar94** [comment] 2017-04-03 16:21
Someone else has to mark it as duplicate though.

**Comment by artemrizhov** [comment] 2017-04-03 18:00
@felfert I'm not sure this is really a duplicate because I have not experienced this problem until the last update.

**Comment by stemar94** [comment] 2017-04-06 09:10
Fixed for me by 1.0.29

**Comment by hxss** [comment] 2017-11-09 19:18
1.1.23. Arch linux. Installed from [AUR](https://aur.archlinux.org/packages/telegram-desktop/).
Menu opens on left click.

**Comment by stemar94** [comment] 2017-11-11 00:41
@hxss Then please file a new issue for that.

**Comment by mpeshev** [comment] 2018-08-16 15:48
Fedora 28 with 1.3.10-1 - left click doesn't work. Even if I right click -> open, it's not on focus and I need to dig it across the two screens.

**Comment by hyperbond** [comment] 2019-05-29 07:35
The same problem exist for mx linux 18.2 (xfce edition).

**Comment by focuz** [comment] 2019-09-25 09:56
Same problem on MX Linux 19 with latest XFCE 4.14.

Tellegram v.1.8.8.

**Please fix this, as it's one of the most popular distros at the moment!**

**Comment by ncc-1701-a** [comment] 2019-11-10 15:09
The same problem on Debian sid (unstable) with XFCE 4.14.
Tellegram v.1.8.15.
Other applications (Skype (electron based), Viber (qt5), uget (GTK2) and deluge (GTK3)) are have not this issue.
Additional information: appindicator (libappindicator3-1) has been purged deliberately: it does not help.
Please fix this.
