### ISSUE TITLE
Some UI refreshes (x is typing...) cause many games and applications to stutter on all screens if telegram runs on a lower refresh rate secondary screen

### ISSUE THREAD

**Issue by Ultrawipf** [telegramdesktop/tdesktop#4941] opened 2018-07-04 15:25 UTC
### Steps to reproduce
Reproducable for example with any unity engine game and windows or [Testufo site](https://www.testufo.com/).

0. Setup windows with two screens with different refresh rates
1. Put telegram on secondary screen with a lower refresh rate than the primary
3. Start a fullscreen game or browser on primary screen with a higher refresh rate (happens for example with https://www.testufo.com/ on firefox with a 144hz screen or any unity based game)
4. Receive "x is typing..." message in preview
5. Every Game/application on other screens will be forced to the refresh rate of the screen it is active on like 60/50hz for the time the message is shown and refreshed.

Only reproducable with multiple screens with different refresh rates over 60hz.
Playing gifs or videos or notifications don't cause the issue. 
Only the temporary "typing..." messages or any similiar text changes in the top or side bar.

### Expected behaviour
UI refreshes should not cause interferences with other applicatons.

### Actual behaviour
When running telegram on windows some notifications cause some gpu applications on all screens to run at a slower speed. This might seem like a rare issue caused by windows behaviour, but it is extremely annoying if you are using telegram permanently in the background to see incoming messages and many people run similiar setups.

If the cause is any windows redraw and not fixable at least an option to disable the animation of these messages should be included to reduce the impact significantly. 

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.3.9

**GPU configuration:** AMD Vega56 with newest drivers
Two screens with different refresh rates. Telegram on 60hz screen, primary screen 144hz (where the issues are )

**Comment by Rezulux** [comment] 2018-07-25 00:06
I've had this as well for the longest time, it can be not only irritating but disruptive of my work as QA, leading to perceived instability or performance issues in the games I'm testing, when it turns out to simply be Telegram's UI refreshing.

Original report states that it happens on an AMD card, and I can confirm it happens on NVIDIA as well, on my GeForce 1070.

**Comment by ItsOnlyMeNL** [comment] 2018-12-24 22:18
Same issue here, with a Nvidia TitanXP.  Have telegram open on second screen that has 60Hz and main screen is 144Hz

**Comment by radixwolf** [comment] 2019-01-20 06:19
I still have this issue and have had this issues for years at this point, with my 144hz running telegram, every time the ... animation comes up my games and any other applications running seem to drop down to the monitors, which is having that animation, refresh rate.

**Comment by Rezulux** [comment] 2020-10-25 07:36
Not sure why stalebot would threaten to close the issue when it has already been labeled as a bug, it's not something the end user can resolve and as such if it goes unfixed, will continue to affect users who have a multiple monitor setup containing a high refresh rate monitor and a 60hz monitor, something that is not nearly an uncommon configuration for those with multiple monitors.

As for the issue in question, I assume it persists as the issue has not been closed by a developer, although I cannot test for it myself as I have since upgraded to two 144hz monitors, and therefore I'm no longer within the affected userbase. I'm simply here to do my due diligence to ensure this issue doesn't get swept under the rug.

**Comment by Aokromes** [comment] 2020-10-25 08:45
> Not sure why stalebot would threaten to close the issue when it has already been labeled as a bug,

easy sometimes bugs are fixed but issues continues to be opened.

**Comment by Ultrawipf** [comment] 2020-10-25 13:37
By disabling animations you can reduce the impact and i wouldn't consider it as problematic as when the issue was opened so if a developer considers it fixed it could be closed.

**Closed** 2020-10-30 18:11 UTC
Labels: bug
