### ISSUE TITLE
Difficult to distinguish the tray icon from other icons and the message counter is now unreadable 

### ISSUE THREAD

**Issue by Pathfinder9021** [telegramdesktop/tdesktop#26989] opened 2023-10-29 12:43 UTC
### Is your feature request related to a problem?

With the introduction of a monochrome taskbar icon under [[Feature Request] Monochrome Icon for Windows](https://github.com/telegramdesktop/tdesktop/issues/17438), the message counter is now unreadable and the Telegram icon is difficult to quickly distinguish from other taskbar icons.

### Describe the solution you'd like

Revert the changes

### Describe alternatives you've considered

Add setting to choose which icon (old or monochrome) to use.

### Additional context

![image](https://github.com/telegramdesktop/tdesktop/assets/43930265/f4ee9135-edc3-4d56-9073-c2e097ae50d1)
There is a study on this topic that confirmed that colored icons are better. In addition, Microsoft acknowledged this in the Windows 11 Settings app. 
![image](https://github.com/telegramdesktop/tdesktop/assets/43930265/3840ed47-b543-4bbc-bd20-d17a9c6b81c6)

**Comment by suprunchuk** [comment] 2023-10-29 12:51
+

**Comment by alexchexes** [comment] 2023-10-29 13:45
You're lucky, since you can at least see the Telegram icon itself. On a standard Windows 10 tray, it looks like this:

![image](https://github.com/telegramdesktop/tdesktop/assets/49966773/a0e49b4e-4606-49b2-a26b-077511bb51f0)

I'm going to roll back to the previous version until it's fixed. Telegram is my work tool, but now I have to spend a few seconds every time I want to find the familiar blue icon in the tray.

**Comment by john-preston** [comment] 2023-10-29 15:53
![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/7588a57c-ee50-406b-b1e1-8f6fcc58a5f9)

Perhaps something like the left one can be used (with an indicator instead of the unreadable counter) instead of the one on the right.

**Comment by electrofloat** [comment] 2023-10-29 15:55
> Perhaps something like the left one can be used (with an indicator instead of the unreadable counter) instead of the one on the right.

Leave the counter pls.

**Comment by Pathfinder9021** [comment] 2023-10-29 16:07
I don't want to be picky, but does anyone know if it's legal to change the tray icon, which is essentially the Telegram [logo](https://telegram.org/tour/screenshots#logos)? Isn't this the official client representing Telegram?

**Comment by ilya-fedin** [comment] 2023-10-29 16:10
@Pathfinder9021 this icon is official as well and is used in tray on macOS since a long time

**Comment by alexchexes** [comment] 2023-10-29 16:54
@ilya-fedin
The icon in the Start menu, as well as the window icon, remains the same as before. Why is it so inconsistent then? And why are you referring to macOS when we are discussing Windows, where the design of the badge is different?

![image](https://github.com/telegramdesktop/tdesktop/assets/49966773/fb5b6985-a04a-4b49-9495-1aae2eb923ec)

---

@electrofloat 
> Leave the counter pls

I agree that we need a counter when there's a meaningful number that it can display. However, many people have 100+ messages in muted chats, making the counter useless. It displays something like '..3' when you actually have 5,203 messages. Does anyone find this useful?

**Comment by ilya-fedin** [comment] 2023-10-29 16:57
> And why are you referring to macOS when we are discussing Windows, where the design of the badge is different?

It has the same design decision. Colorful application icon while monochrome tray icon. The only thing stopping the same from being implemented on Windows is the lack of system APIs. Now Windows has `SystemUsesLightTheme` regsitry key that allowed to implement this feature on Windows as well.

**Comment by ilya-fedin** [comment] 2023-10-29 16:57
> However, many people have 100+ messages in muted chats, making the counter useless.

You can disable the counter for muted chats in settings.

**Comment by john-preston** [comment] 2023-10-29 17:06
@alexchexes I've made '..3' counter as the only badge that can have any meaning for 5203 messages - you can see in it if the counter changes, which isn't true for some other badge formats, like "5K", which is the same (in terms of meaning) as just a red dot.

**Comment by john-preston** [comment] 2023-10-29 17:06
It can be made a badge with a single digit, like '1', '2', '3', ... , '8', '9' and after that '+' or smth like that.

**Comment by dogancelik** [comment] 2023-10-29 17:42
I prefer the original icon. Please allow us to use the original icon. Not everything has to be monochrome.

**Comment by baterflyrity** [comment] 2023-10-29 17:53
Monochrome Icon is definitely better than the old one but such red alert is really bad.

**Comment by alexchexes** [comment] 2023-10-29 17:54
@john-preston, @ilya-fedin

The main problem that prompted me to come here and open #26991 issue is not the design of the counter or even the icon itself as an isolated item (I understand that things change sometimes, and we have to give up our old habits and build new ones; that's OK). But still, as I described in #26991, with the new design, a counter with more than one digit overlaps and almost completely hides the Telegram icon, at least on Windows 10:

![image](https://github.com/telegramdesktop/tdesktop/assets/49966773/fc963a80-2cf7-4402-8d0e-8c2ccabe9dfe)

Perhaps I should have opened a separate issue for this, but I didn't, and now the issue that mentions this problem is closed as a duplicate of the current issue, where the focus is on a related but still different problem.

**Comment by OpenSpaghettiSauce** [comment] 2023-10-29 18:33
Please revert to the old icon. This is **really, really** annoying. I can't find the icon, ever. I can't see the new messages now. All the people I managed to convert to Telegram are freaking out. They couldn't even find the icon on their computer.

Who accepted this change? Please don't do things like this.

I like Telegram. Why? Why ruin something great? Please don't?

**Comment by netkot** [comment] 2023-10-29 20:03
Worst icon change I've ever seen.

**Comment by staticpiratex** [comment] 2023-10-29 20:21
The first time I saw that gray icon, I though It was a bug...
Please make a option to customize this icon!
It's too hard to see in systray!
Thanks!

**Comment by ReyVGM** [comment] 2023-10-29 20:24
I like the old icon better too. I think there should be an option to select which tray icon you want. I know on the mobile app you can (or could?) change your app icon a couple of years ago.

![Screenshot 2023-10-29 at 16-23-22 Change App Icon on Telegram](https://github.com/telegramdesktop/tdesktop/assets/7338867/6f1415b1-f308-4e45-aef2-444bde76b754)

**Comment by alexchexes** [comment] 2023-10-29 21:47
> I know on the mobile app you can (or could?) change your app icon a couple of years ago.

You still can, at least on iOS:

![IMG_0549](https://github.com/telegramdesktop/tdesktop/assets/49966773/f89deb54-ba92-4b28-ae54-65cbd9c0a697)

**Comment by sanyvaa** [comment] 2023-10-30 04:51
is this new awful white icon a bug in telegram desktop?
if it is not, why it wasn't mentioned in release notes?
why is it differ to icon in Start menu?
if it was done intentionally, I'd advise firing designer who created it. it is just worst change in telegram ever,

**Closed** 2023-10-30 07:18 UTC
Labels: enhancement

**Comment by Exaybachay** [comment] 2023-10-30 09:08
> @john-preston, @ilya-fedin
> 
> ![image](https://user-images.githubusercontent.com/49966773/278888329-fc963a80-2cf7-4402-8d0e-8c2ccabe9dfe.png)
> 

While you can disable Muted chats like groups/channels to not show up in the badge counter, the issue is no better even for regular one-digit counters in Win10.
![image](https://github.com/telegramdesktop/tdesktop/assets/9845534/1bc6683d-538a-49f3-b8c2-38638a6ec725)

**Comment by OpenSpaghettiSauce** [comment] 2023-10-30 10:39
Thank you @john-preston . I appreciate listening to the users. Seriously I never made a fuss about changes but this was truly awful.

**Comment by torbasow** [comment] 2023-10-31 03:40
Where is this setting to disable monochrome icon? I do not see it in the application settings.

**Comment by Pathfinder9021** [comment] 2023-10-31 06:47
Thank you @john-preston for improving this. 

@torbasow typically the customer receives the changes as part of the next version of the software after the changes have been tested and a release candidate is available and approved.

**Comment by kasumiru** [comment] 2023-10-31 09:26
why discussion is closed? up please, issue not resolved.

**Comment by OpenSpaghettiSauce** [comment] 2023-10-31 10:10
@kasumiru They fixed it, but there was no release since. Once there is a new version, we should see the fix go live.

As far as I understand the commit, "normal" colored icon that we all love will return as default.

**Comment by john-preston** [comment] 2023-10-31 10:12
@OpenSpaghettiSauce As default in old installations, new one is default in new installations.

**Comment by pnrjason** [comment] 2023-10-31 16:12
![image](https://github.com/telegramdesktop/tdesktop/assets/39984351/6024303f-6ae8-41a7-8e1f-9cda1b9b9539)
It's really annoying

**Comment by good-gamedev** [comment] 2023-10-31 19:15
Please return old icon. It was better, and we got used to it. )

**Comment by OpenSpaghettiSauce** [comment] 2023-10-31 20:47
@john-preston Can't you make the monochrome opt-in? If I were to install Telegram to any non-techie user, telling them "look for the blue icon" is 1000% more effective than saying "look for the uh.. white one.. the uh.. looks like a paper plane but in modern design? yes ma, I know the icons are so small but its white like the rest and its a uh white.."

Maybe we could vote? I don't know. I've been with Telegram for so many years now and I'm a huge fan and advocate. This is just I don't know. I mean don't get me wrong I really appreciate you guys listening - at all. Just the regular users might find it easier to have the colored one.

You could put this icon and others like a premium feature maybe. Just set one in settings and then the program would relaunch with the new icon set. Because now, the tray was white but the pinnned taskbar icon is blue. So it's not even matching.

**Comment by good-gamedev** [comment] 2023-10-31 20:51
Issue is closed as completed, thanks to @john-preston, old icon will be optional.

**Comment by ilya-fedin** [comment] 2023-10-31 20:57
> So it's not even matching.

It's not supposed to match. Tray is a place for status icons, status icons aren't meant to look like application icon.
