### ISSUE TITLE
Telegram marks all unread messages from a channel as read on iPhone.

### ISSUE THREAD

**Issue by j4hangir** [telegramdesktop/tdesktop#7002] opened 2020-01-15 16:59 UTC
This is an annoying problem that I face with channels. Whenever I use Telegram on Windows and accidentally open a channel with unread messages, say 450 unread messages, on my iPhone the channel now gets all its messages displayed as read and I can't simply scroll down and read them one by one.
The expected behavior, as it is on iOS, is to only mark a message as read when scrolled down and was literally read, OR, when one presses the Down Arrow to scroll to the bottom and mark all as read.

**Comment by RememberTheAir** [comment] 2020-01-15 17:01
Duplicate of #775, unfortunately this is a feature tdesktop still misses

**Closed** 2020-01-15 17:13 UTC
