### ISSUE TITLE
[Feature Request] Enable the max number of top pinned chats to be a configurable number

### ISSUE THREAD

**Issue by isurugiu** [telegramdesktop/tdesktop#10266] opened 2021-01-29 23:21 UTC
### Is your feature request related to a problem?
Not really, but more an annoyance. I'm running Telegram on a display in portrait mode and I find it annoying that only 5 chats are pin-able on the top

### Describe the solution you'd like
Have a configurable setting in either Settings->Advanced or Settings ->Chat Settings where you can actually specify how many chats you can pin to the top

### Describe alternatives you've considered
None that I could think of except of creating a PR, but my C++ was such a long time ago

**Comment by ilya-fedin** [comment] 2021-01-29 23:22
This is a server-side limit

**Comment by RememberTheAir** [comment] 2021-01-29 23:27
Kind of duplicate of #3026, anyway this now belongs to https://bugs.telegram.org (new bugs and suggestions platform)

**Closed** 2021-01-29 23:28 UTC
