### ISSUE TITLE
There is no option "Use native notifications" in KDE if the Telegram is loaded before the Plasma because of Autostart (Racing condition)

### ISSUE THREAD

**Issue by qg0** [telegramdesktop/tdesktop#7308] opened 2020-02-29 20:32 UTC
There is no option "Use native notifications" in KDE if the Telegram is loaded before the Plasma because of Autostart (Racing condition)

Telegram 1.9.19 beta
Linux OpenSUSE Tumbleweed
KDE 5

Steps to reproduce:
killall plasmashell
run telegram
run plasmashell

Possible solution:
Check the running Plasma when the user opens the Settings/Notifications window.

![image](https://user-images.githubusercontent.com/919099/75614579-c3ee6e80-5b6c-11ea-957c-78a72a3738d6.png)
![image](https://user-images.githubusercontent.com/919099/75614601-0d3ebe00-5b6d-11ea-96d0-3944d77499b6.png)

**Comment by ilya-fedin** [comment] 2020-02-29 23:19
![image](https://user-images.githubusercontent.com/17829319/75616501-c9868d00-5b49-11ea-91e9-9cc4eda120c4.png)
Kubuntu 18.04, official binary v1.9.19 beta

**Comment by ilya-fedin** [comment] 2020-03-02 07:13
So, maybe some additional info? Log, installation method, etc?

**Comment by qg0** [comment] 2020-03-02 09:16
There is a linux binary from the official site.
I have not find logs, only binary and themes.
> find / -iname "*telegram*" | grep "log"

The option "use native notifications " is here now on the bottom, but there is no "screen" now. 🤷‍♂️
![image](https://user-images.githubusercontent.com/919099/75661504-0369a780-5ca0-11ea-8ff2-6c5f1bb5727f.png)

**Comment by ilya-fedin** [comment] 2020-03-02 09:19
> I have not find logs, only binary and themes.

~/.local/share/TelegramDesktop/log.txt


> but there is no "screen" now.

This is non-native-notifications-specific

**Comment by qg0** [comment] 2020-03-02 09:36
[2020.03.02 15:57:35] Launched version: 1009019, install beta: [TRUE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.03.02 15:57:35] Executable dir: /home/user/bin/Telegram/, name: Telegram
[2020.03.02 15:57:35] Initial working dir: /home/user/
[2020.03.02 15:57:35] Working dir: /home/user/.local/share/TelegramDesktop/
[2020.03.02 15:57:35] Command line: /home/user/bin/Telegram/Telegram -autostart
[2020.03.02 15:57:35] Executable path before check: /home/user/bin/Telegram/Telegram
[2020.03.02 15:57:35] Launcher filename is telegramdesktop.desktop
[2020.03.02 15:57:35] Logs started
[2020.03.02 15:57:35] Checking for XDG Desktop Portal...
[2020.03.02 15:57:41] XDG Desktop Portal is present!
[2020.03.02 15:57:41] Usage of XDG Desktop Portal is disabled.
[2020.03.02 15:57:41] Connecting local socket to /run/user/0/c8a98f2fe164925688f81a251c978b91-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.03.02 15:57:41] This is the only instance of Telegram, starting server and app...
[2020.03.02 15:57:41] Moved logging from '/home/user/.local/share/TelegramDesktop/log_start0.txt' to '/home/user/.local/share/TelegramDesktop/log.txt'!
[2020.03.02 15:57:41] Primary screen DPI: 96.1032
[2020.03.02 15:57:41] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2020.03.02 15:57:42] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2020.03.02 15:57:42] Font: from ':/gui/fonts/DAOpenSansBold.ttf' loaded 'DAOpenSansBold'
[2020.03.02 15:57:43] Font: from ':/gui/fonts/DAOpenSansBoldItalic.ttf' loaded 'DAOpenSansBoldItalic'
[2020.03.02 15:57:43] Font: from ':/gui/fonts/DAOpenSansSemibold.ttf' loaded 'DAOpenSansSemibold'
[2020.03.02 15:57:44] Font: from ':/gui/fonts/DAOpenSansSemiboldItalic.ttf' loaded 'DAOpenSansSemiboldItalic'
[2020.03.02 15:57:45] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
[2020.03.02 15:57:45] App Info: reading settings...
[2020.03.02 15:57:45] App Info: reading encrypted settings...
[2020.03.02 15:57:45] Lang Info: Loaded cached, keys: 2581
[2020.03.02 15:57:49] OpenAL Logging Level: (not set)
[2020.03.02 15:57:49] Audio Playback Devices: OpenAL Soft
[2020.03.02 15:57:49] Audio Playback Default Device: OpenAL Soft
[2020.03.02 15:57:49] Audio Capture Devices: Camera Многоканальный;Monitor of Встроенное аудио Аналоговый стерео;Встроенное аудио Аналоговый стерео;Monitor Source of Simultaneous output to Встроенное аудио Аналоговый стерео
[2020.03.02 15:57:49] Audio Capture Default Device: Camera Многоканальный
[2020.03.02 15:57:49] App Info: reading map...
[2020.03.02 15:57:49] App Info: reading encrypted map...
[2020.03.02 15:57:49] App Info: reading encrypted user settings...
[2020.03.02 15:57:49] App Info: encrypted user settings read.
[2020.03.02 15:57:49] App Info: reading encrypted mtp data...
[2020.03.02 15:57:49] MTP Info: read keys, current: 4, to destroy: 0
[2020.03.02 15:57:49] Map read time: 28
[2020.03.02 15:58:01] Notification daemon specification version: 1.2
[2020.03.02 15:58:01] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[2020.03.02 15:58:03] Export Info: Destroy top bar by controller removal.
[2020.03.02 15:58:03] System tray available: [TRUE]
[2020.03.02 15:58:03] Not using Unity launcher counter.
[2020.03.02 15:58:03] Using SNI tray icon.
[2020.03.02 15:58:49] API Warning: not loaded minimal channel applied.
[2020.03.02 16:00:38] API Warning: not loaded minimal channel applied.
[2020.03.02 16:05:51] API Warning: not loaded minimal channel applied.
[2020.03.02 16:06:22] Launcher filename is telegramdesktop.desktop
[2020.03.02 16:06:50] App Info: writing encrypted user settings...
[2020.03.02 16:06:51] App Info: writing encrypted user settings...
[2020.03.02 16:06:51] App Info: writing encrypted user settings...
[2020.03.02 16:06:52] App Info: writing encrypted user settings...
[2020.03.02 16:06:53] App Info: writing encrypted user settings...
[2020.03.02 16:06:54] App Info: writing encrypted user settings...
[2020.03.02 16:08:00] API Warning: not loaded minimal channel applied.
[2020.03.02 16:08:31] Streaming Error: Error in avcodec_find_decoder (code: 32797, text: Error number 32797 occurred).
[2020.03.02 16:08:31] Streaming Error: No codec for video stream 0, mode 2.
[2020.03.02 16:08:31] Streaming Error: Error in avcodec_find_decoder (code: 32797, text: Error number 32797 occurred).
[2020.03.02 16:08:31] Streaming Error: No codec for video stream 0, mode 2.
[2020.03.02 16:09:30] API Warning: not loaded minimal channel applied.
[2020.03.02 16:09:31] API Warning: not loaded minimal channel applied.
[2020.03.02 16:11:25] API Warning: not loaded minimal channel applied.
[2020.03.02 16:14:55] App Info: writing encrypted user settings...
[2020.03.02 16:14:55] App Info: writing encrypted user settings...
[2020.03.02 16:14:55] App Info: writing encrypted user settings...
[2020.03.02 16:14:56] App Info: writing encrypted user settings...
[2020.03.02 16:15:24] Audio Info: recreating audio device and reattaching the tracks
[2020.03.02 16:15:25] Launcher filename is telegramdesktop.desktop
[2020.03.02 16:15:27] Audio Info: Closing audio playback device.
[2020.03.02 16:18:27] API Warning: not loaded minimal channel applied.
[2020.03.02 16:18:57] Audio Info: recreating audio device and reattaching the tracks
[2020.03.02 16:18:57] Launcher filename is telegramdesktop.desktop
[2020.03.02 16:18:59] Audio Info: Closing audio playback device.
[2020.03.02 16:22:18] Launcher filename is telegramdesktop.desktop
[2020.03.02 16:23:42] API Warning: not loaded minimal channel applied.
[2020.03.02 16:24:28] API Warning: not loaded minimal channel applied.
[2020.03.02 16:24:55] API Warning: not loaded minimal channel applied.
[2020.03.02 16:25:40] API Warning: not loaded minimal channel applied.
[2020.03.02 16:27:19] API Warning: not loaded minimal channel applied.
[2020.03.02 16:29:07] API Warning: not loaded minimal channel applied.
[2020.03.02 16:29:57] Launcher filename is telegramdesktop.desktop
[2020.03.02 16:30:20] API Warning: not loaded minimal channel applied.

**Comment by ilya-fedin** [comment] 2020-03-02 09:39
> [2020.03.02 15:58:01] Notification daemon specification version: 1.2

This log is from working launch
PS: please, hide log into `code` tag

**Comment by Aokromes** [comment] 2020-03-02 09:43
even better <details >

**Comment by qg0** [comment] 2020-03-02 10:04
> > [2020.03.02 15:58:01] Notification daemon specification version: 1.2
> 
> This log is from working launch

There are no other logs.
I could not reconstruct the case where there was not an option "Use native notifications".

**Comment by ilya-fedin** [comment] 2020-03-02 10:15
> I could not reconstruct the case where there was not an option "Use native notifications".

Maybe a race condition between telegram and notification daemon launch on system start? :thinking:

**Comment by qg0** [comment] 2020-03-02 11:51
Is there some condition in the code when you show this option and where not?
Like 
```
if (notification_daemon_is_started) {
native_notifications_enabled = true;
}
```

Maybe something [here](https://github.com/telegramdesktop/tdesktop/blob/57b76e3f0021aedda940b18902bf57a5cb92c333/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp)

`#ifndef TDESKTOP_DISABLE_DBUS_INTEGRATION
	if (Global::NativeNotifications() && Supported()) {
		return std::make_unique<Manager>(system);
	}
#endif // !TDESKTOP_DISABLE_DBUS_INTEGRATION
	return nullptr;
}`

**Comment by ilya-fedin** [comment] 2020-03-02 11:54
Yes, look at Supported()

**Comment by Aokromes** [comment] 2020-03-02 12:04
hackaround here xd https://itsfoss.com/manage-startup-applications-ubuntu/

**Comment by ilya-fedin** [comment] 2020-03-02 12:06
I can't reproduce it at all.
@qg0 did you install the whole `plasma` group (or `plasma-meta` package)? Did you disabled some service in plasma settings?

**Comment by qg0** [comment] 2020-03-02 12:37
I just closed the telegram and killed the plasma.
`killall plasmashell`
Then I started the telegram
`~/bin/Telegram/Telegram`
Then I started the plasmashell
`plasmashell`

So, in the result I have not the "Use native notifications" option, but I have the running plasma. Maybe the app should check if the plasma is running when the user opens the settings dialog?

![image](https://user-images.githubusercontent.com/919099/75676658-4afe2c80-5cbc-11ea-9ab6-b6cacb4f0d6d.png)

**Comment by ilya-fedin** [comment] 2020-03-02 13:40
> So, in the result I have not the "Use native notifications" option, but I have the running plasma.

Starting plasma after starting the app is something very, very strange and result is predictable

**Comment by ilya-fedin** [comment] 2020-03-02 13:42
> did you install the whole `plasma` group (or `plasma-meta` package)? Did you disabled some service in plasma settings?

@qg0

**Comment by qg0** [comment] 2020-03-02 14:48
Here is packages. Everything what contains "plasma" in the name are installed.
<details><pre>
# zypper se plasma
Загрузка данных о репозиториях...
Чтение установленных пакетов...

С  | Имя                                         | Заключение                                                                     | Тип                   
---+---------------------------------------------+--------------------------------------------------------------------------------+-----------------------
i  | kde_plasma                                  | KDE Plasma 5 Desktop Base                                                      | шаблон                
i+ | libKF5Plasma5                               | Plasma framework - core libraries                                              | пакет                 
i+ | libKF5Plasma5-32bit                         | Plasma framework - core libraries                                              | пакет                 
i+ | libKF5Plasma5-32bit-debuginfo               | Debug information for package libKF5Plasma5                                    | пакет                 
i+ | libKF5Plasma5-debuginfo                     | Debug information for package libKF5Plasma5                                    | пакет                 
i+ | libplasma2                                  | Development files for plasma                                                   | пакет                 
i+ | libplasma2-32bit                            | Development files for plasma                                                   | пакет                 
i+ | libplasma2-32bit-debuginfo                  | Debug information for package libplasma2                                       | пакет                 
i+ | libplasma2-debuginfo                        | Debug information for package libplasma2                                       | пакет                 
i+ | patterns-kde-kde_plasma                     | KDE Plasma 5 Desktop Base                                                      | пакет                 
   | plasma                                      | Parallel Linear Algebra Software for Multicore Architectures                   | пакет с исходным кодом
   | plasma-applet-weather-widget                | Plasma 5 widget for displaying weather information                             | пакет с исходным кодом
i+ | plasma-applet-weather-widget                | Plasma 5 widget for displaying weather information                             | пакет                 
i+ | plasma-applet-weather-widget-debuginfo      | Debug information for package plasma-applet-weather-widget                     | пакет                 
i+ | plasma-applet-weather-widget-debugsource    | Debug sources for package plasma-applet-weather-widget                         | пакет                 
i+ | plasma-applet-weather-widget-lang           | Translations for package plasma-applet-weather-widget                          | пакет                 
   | plasma-browser-integration                  | Helper for the KDE Plasma Browser Integration                                  | пакет с исходным кодом
i+ | plasma-browser-integration                  | Helper for the KDE Plasma Browser Integration                                  | пакет                 
i+ | plasma-browser-integration-debuginfo        | Debug information for package plasma-browser-integration                       | пакет                 
i+ | plasma-browser-integration-debugsource      | Debug sources for package plasma-browser-integration                           | пакет                 
i+ | plasma-browser-integration-lang             | Translations for package plasma-browser-integration                            | пакет                 
i+ | plasma-debugsource                          | Debug sources for package plasma                                               | пакет                 
i+ | plasma-devel                                | Development files for plasma                                                   | пакет                 
i+ | plasma-devel-32bit                          | Development files for plasma                                                   | пакет                 
   | plasma-framework                            | Plasma library and runtime components based upon KF5 and Qt5                   | пакет с исходным кодом
i+ | plasma-framework                            | Plasma library and runtime components based upon KF5 and Qt5                   | пакет                 
i+ | plasma-framework-32bit                      | Plasma library and runtime components based upon KF5 and Qt5                   | пакет                 
i+ | plasma-framework-32bit-debuginfo            | Debug information for package plasma-framework                                 | пакет                 
i+ | plasma-framework-components                 | Plasma QML components                                                          | пакет                 
i+ | plasma-framework-components-32bit           | Plasma QML components                                                          | пакет                 
i+ | plasma-framework-components-32bit-debuginfo | Debug information for package plasma-framework-components                      | пакет                 
i+ | plasma-framework-components-debuginfo       | Debug information for package plasma-framework-components                      | пакет                 
i+ | plasma-framework-debuginfo                  | Debug information for package plasma-framework                                 | пакет                 
i+ | plasma-framework-debugsource                | Debug sources for package plasma-framework                                     | пакет                 
i+ | plasma-framework-devel                      | Plasma library and runtime components                                          | пакет                 
i+ | plasma-framework-devel-32bit                | Plasma library and runtime components                                          | пакет                 
i+ | plasma-framework-lang                       | Translations for package plasma-framework                                      | пакет                 
   | plasma-mycroft                              | Plasmoid for Mycroft AI                                                        | пакет с исходным кодом
i+ | plasma-mycroft                              | Plasmoid for Mycroft AI                                                        | пакет                 
i+ | plasma-mycroft-debuginfo                    | Debug information for package plasma-mycroft                                   | пакет                 
i+ | plasma-mycroft-debugsource                  | Debug sources for package plasma-mycroft                                       | пакет                 
   | plasma-nm5                                  | Plasma applet written in QML for managing network connections                  | пакет с исходным кодом
i+ | plasma-nm5                                  | Plasma applet written in QML for managing network connections                  | пакет                 
i+ | plasma-nm5-debuginfo                        | Debug information for package plasma-nm5                                       | пакет                 
i+ | plasma-nm5-debugsource                      | Debug sources for package plasma-nm5                                           | пакет                 
i+ | plasma-nm5-fortisslvpn                      | FortiGate SSL VPN support for plasma-nm5                                       | пакет                 
i+ | plasma-nm5-fortisslvpn-debuginfo            | Debug information for package plasma-nm5-fortisslvpn                           | пакет                 
i+ | plasma-nm5-iodine                           | VPN support for plasma-nm5                                                     | пакет                 
i+ | plasma-nm5-iodine-debuginfo                 | Debug information for package plasma-nm5-iodine                                | пакет                 
i+ | plasma-nm5-l2tp                             | L2TP support for plasma-nm5                                                    | пакет                 
i+ | plasma-nm5-l2tp-debuginfo                   | Debug information for package plasma-nm5-l2tp                                  | пакет                 
i+ | plasma-nm5-lang                             | Translations for package plasma-nm5                                            | пакет                 
i+ | plasma-nm5-openconnect                      | OpenConnect support for plasma-nm5                                             | пакет                 
i+ | plasma-nm5-openconnect-debuginfo            | Debug information for package plasma-nm5-openconnect                           | пакет                 
i+ | plasma-nm5-openswan                         | Openswan support for plasma-nm5                                                | пакет                 
i+ | plasma-nm5-openswan-debuginfo               | Debug information for package plasma-nm5-openswan                              | пакет                 
i+ | plasma-nm5-openvpn                          | OpenVPN support for plasma-nm5                                                 | пакет                 
i+ | plasma-nm5-openvpn-debuginfo                | Debug information for package plasma-nm5-openvpn                               | пакет                 
i+ | plasma-nm5-pptp                             | PPTP support for plasma-nm5                                                    | пакет                 
i+ | plasma-nm5-pptp-debuginfo                   | Debug information for package plasma-nm5-pptp                                  | пакет                 
i+ | plasma-nm5-ssh                              | SSH support for plasma-nm5                                                     | пакет                 
i+ | plasma-nm5-ssh-debuginfo                    | Debug information for package plasma-nm5-ssh                                   | пакет                 
i+ | plasma-nm5-sstp                             | SSTP support for plasma-nm5                                                    | пакет                 
i+ | plasma-nm5-sstp-debuginfo                   | Debug information for package plasma-nm5-sstp                                  | пакет                 
i+ | plasma-nm5-strongswan                       | strongSwan support for plasma-nm5                                              | пакет                 
i+ | plasma-nm5-strongswan-debuginfo             | Debug information for package plasma-nm5-strongswan                            | пакет                 
i+ | plasma-nm5-vpnc                             | vpnc support for plasma-nm5                                                    | пакет                 
i+ | plasma-nm5-vpnc-debuginfo                   | Debug information for package plasma-nm5-vpnc                                  | пакет                 
   | plasma-pass                                 | Plasma 5 widget for the pass password manager                                  | пакет с исходным кодом
i+ | plasma-pass                                 | Plasma 5 widget for the pass password manager                                  | пакет                 
i+ | plasma-pass-debuginfo                       | Debug information for package plasma-pass                                      | пакет                 
i+ | plasma-pass-debugsource                     | Debug sources for package plasma-pass                                          | пакет                 
i+ | plasma-pass-lang                            | Translations for package plasma-pass                                           | пакет                 
   | plasma-vault                                | Plasma applet and services for creating encrypted vaults                       | пакет с исходным кодом
i+ | plasma-vault                                | Plasma applet and services for creating encrypted vaults                       | пакет                 
i+ | plasma-vault-backend-cryfs                  | Necessary packages for plasma-vault to support cryfs vaults                    | пакет                 
i+ | plasma-vault-backend-encfs                  | Necessary packages for plasma-vault to support encfs vaults                    | пакет                 
i+ | plasma-vault-debuginfo                      | Debug information for package plasma-vault                                     | пакет                 
i+ | plasma-vault-debugsource                    | Debug sources for package plasma-vault                                         | пакет                 
i+ | plasma-vault-lang                           | Translations for package plasma-vault                                          | пакет                 
   | plasma5-addons                              | Additional Plasma5 Widgets                                                     | пакет с исходным кодом
i+ | plasma5-addons                              | Additional Plasma5 Widgets                                                     | пакет                 
i+ | plasma5-addons-debuginfo                    | Debug information for package plasma5-addons                                   | пакет                 
i+ | plasma5-addons-debugsource                  | Debug sources for package plasma5-addons                                       | пакет                 
i+ | plasma5-addons-devel                        | Additional plasmoid widgets - development files                                | пакет                 
i+ | plasma5-addons-lang                         | Translations for package plasma5-addons                                        | пакет                 
   | plasma5-applet-suse-prime                   | Plasma 5 applet for controlling SUSE Prime                                     | пакет с исходным кодом
i+ | plasma5-applet-suse-prime                   | Plasma 5 applet for controlling SUSE Prime                                     | пакет                 
i+ | plasma5-defaults-openSUSE                   | Default settings for KDE Plasma 5                                              | пакет                 
   | plasma5-desktop                             | The KDE Plasma Workspace Components                                            | пакет с исходным кодом
i+ | plasma5-desktop                             | The KDE Plasma Workspace Components                                            | пакет                 
i+ | plasma5-desktop-debuginfo                   | Debug information for package plasma5-desktop                                  | пакет                 
i+ | plasma5-desktop-debugsource                 | Debug sources for package plasma5-desktop                                      | пакет                 
i  | plasma5-desktop-emojier                     | Selection window for emoji text input                                          | пакет                 
i+ | plasma5-desktop-emojier-debuginfo           | Debug information for package plasma5-desktop-emojier                          | пакет                 
i+ | plasma5-desktop-lang                        | Translations for package plasma5-desktop                                       | пакет                 
   | plasma5-integration                         | Plugins responsible for better integration of Qt applications in KDE Workspace | пакет с исходным кодом
i+ | plasma5-integration-debugsource             | Debug sources for package plasma5-integration                                  | пакет                 
i+ | plasma5-integration-plugin                  | Plugins responsible for better integration of Qt applications in KDE Workspace | пакет                 
i+ | plasma5-integration-plugin-debuginfo        | Debug information for package plasma5-integration-plugin                       | пакет                 
i+ | plasma5-integration-plugin-lang             | Translations for package plasma5-integration                                   | пакет                 
   | plasma5-openSUSE                            | openSUSE KDE Extension                                                         | пакет с исходным кодом
   | plasma5-pa                                  | The Plasma5 Volume Manager                                                     | пакет с исходным кодом
i+ | plasma5-pa                                  | The Plasma5 Volume Manager                                                     | пакет                 
i+ | plasma5-pa-debuginfo                        | Debug information for package plasma5-pa                                       | пакет                 
i+ | plasma5-pa-debugsource                      | Debug sources for package plasma5-pa                                           | пакет                 
i+ | plasma5-pa-lang                             | Translations for package plasma5-pa                                            | пакет                 
   | plasma5-pk-updates                          | Software Update Manager for Plasma                                             | пакет с исходным кодом
i+ | plasma5-pk-updates                          | Software Update Manager for Plasma                                             | пакет                 
i+ | plasma5-pk-updates-debuginfo                | Debug information for package plasma5-pk-updates                               | пакет                 
i+ | plasma5-pk-updates-debugsource              | Debug sources for package plasma5-pk-updates                                   | пакет                 
i+ | plasma5-pk-updates-lang                     | Translations for package plasma5-pk-updates                                    | пакет                 
i+ | plasma5-radiotray                           | Plasmoid to listen to online radio stations                                    | пакет                 
   | plasma5-radiotray                           | Plasmoid to listen to online radio stations                                    | пакет с исходным кодом
i+ | plasma5-radiotray-debuginfo                 | Debug information for package plasma5-radiotray                                | пакет                 
i+ | plasma5-radiotray-debugsource               | Debug sources for package plasma5-radiotray                                    | пакет                 
i+ | plasma5-radiotray-lang                      | Translations for package plasma5-radiotray                                     | пакет                 
   | plasma5-sdk                                 | Plasma SDK                                                                     | пакет с исходным кодом
i+ | plasma5-sdk                                 | Plasma SDK                                                                     | пакет                 
i+ | plasma5-sdk-debuginfo                       | Debug information for package plasma5-sdk                                      | пакет                 
i+ | plasma5-sdk-debugsource                     | Debug sources for package plasma5-sdk                                          | пакет                 
i+ | plasma5-sdk-lang                            | Translations for package plasma5-sdk                                           | пакет                 
i+ | plasma5-session                             | KDE Plasma 5 X11 Session                                                       | пакет                 
i+ | plasma5-session-wayland                     | KDE Plasma 5 Wayland Session                                                   | пакет                 
i+ | plasma5-theme-openSUSE                      | Plasma 5 theme for openSUSE                                                    | пакет                 
   | plasma5-thunderbolt                         | Plasma frontend for Thunderbolt 3 security levels                              | пакет с исходным кодом
i  | plasma5-thunderbolt                         | Plasma frontend for Thunderbolt 3 security levels                              | пакет                 
i+ | plasma5-thunderbolt-debuginfo               | Debug information for package plasma5-thunderbolt                              | пакет                 
i+ | plasma5-thunderbolt-debugsource             | Debug sources for package plasma5-thunderbolt                                  | пакет                 
i+ | plasma5-thunderbolt-lang                    | Translations for package plasma5-thunderbolt                                   | пакет                 
   | plasma5-workspace                           | The KDE Plasma Workspace Components                                            | пакет с исходным кодом
i+ | plasma5-workspace                           | The KDE Plasma Workspace Components                                            | пакет                 
i+ | plasma5-workspace-branding-openSUSE         | openSUSE branded KDE settings                                                  | пакет                 
i+ | plasma5-workspace-debuginfo                 | Debug information for package plasma5-workspace                                | пакет                 
i+ | plasma5-workspace-debugsource               | Debug sources for package plasma5-workspace                                    | пакет                 
i+ | plasma5-workspace-devel                     | The KDE Plasma Workspace Components                                            | пакет                 
i+ | plasma5-workspace-lang                      | Translations for package plasma5-workspace                                     | пакет                 
i+ | plasma5-workspace-libs                      | The KDE Plasma Workspace Components                                            | пакет                 
i+ | plasma5-workspace-libs-32bit                | The KDE Plasma Workspace Components                                            | пакет                 
i+ | plasma5-workspace-libs-32bit-debuginfo      | Debug information for package plasma5-workspace-libs                           | пакет                 
i+ | plasma5-workspace-libs-debuginfo            | Debug information for package plasma5-workspace-libs                           | пакет                 
   | plasma5-workspace-wallpapers                | Aditional Plasma Wallpapers                                                    | пакет с исходным кодом
i+ | plasma5-workspace-wallpapers                | Aditional Plasma Wallpapers                                                    | пакет                 
i+ | plasmaengineexplorer5                       | Provides direct access to plasma data engines                                  | пакет                 
i+ | plasmaengineexplorer5-debuginfo             | Debug information for package plasmaengineexplorer5                            | пакет  
</pre></details>

![image](https://user-images.githubusercontent.com/919099/75686366-b9e48100-5cce-11ea-99f9-90ed063ec74a.png)
![image](https://user-images.githubusercontent.com/919099/75686448-d84a7c80-5cce-11ea-9ffc-7935de84dcab.png)

I have not disabled services in plasma.

![image](https://user-images.githubusercontent.com/919099/75686624-23fd2600-5ccf-11ea-9528-e3f6c73548e8.png)
![image](https://user-images.githubusercontent.com/919099/75686657-324b4200-5ccf-11ea-9d83-ae7e21de0849.png)

**Comment by ilya-fedin** [comment] 2020-03-03 04:05
Can you try https://github.com/ilya-fedin/tdesktop/actions/runs/48554469?

**Comment by qg0** [comment] 2020-03-03 09:27
The same.
I killed the Plasma with working Telegram.
There was an option "Use native notifications", but I couldn't set the flag there.
Then the app became freezed.
Then the OS/KDE prompted that "the app is not responded. Kill the app?".
When I started the Plasma again, the app became unfreezed.
<details><pre>
cat log_16_00.txt| grep -i  "notification"
[16:13:54.394 00-0000454] Lang Warning: Unknown key 'lng_settings_advanced_notifications' (lang_instance.cpp : 209)
[16:14:29.112 00-0001118] Lang Warning: Unknown key 'lng_settings_advanced_notifications' (lang_instance.cpp : 209)
[16:14:49.159 00-0006579] Notification daemon specification version: 1.2
[16:14:49.159 00-0006580] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions


cat log_16_15.txt| grep -i  "notification"
**[16:16:16.787 00-0007238] Native notification error: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[16:16:16.788 00-0007239] Native notification error: server information should have 4 elements
[16:16:41.811 00-0007299] Native notification error: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.**
[16:16:51.226 00-0007423] Notification daemon specification version: 1.2
[16:16:51.226 00-0007424] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[16:16:52.245 00-0007436] Notification daemon specification version: 1.2
[16:16:52.245 00-0007437] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[16:16:52.827 00-0007440] Notification daemon specification version: 1.2
[16:16:52.827 00-0007441] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[16:16:52.863 00-0007444] Notification daemon specification version: 1.2
[16:16:52.863 00-0007445] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[16:16:52.904 00-0007448] Notification daemon specification version: 1.2
[16:16:52.904 00-0007449] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[16:17:11.650 00-0008358] Notification daemon specification version: 1.2
[16:17:11.650 00-0008359] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions

</pre>
</details>

**Comment by ilya-fedin** [comment] 2020-03-03 09:29
Okay, then it detects notification daemon, but needs a timeout since it is not running at the moment. This is progress.

**Comment by ilya-fedin** [comment] 2020-03-03 13:34
@qg0 try this variant pls https://github.com/ilya-fedin/tdesktop/actions/runs/48793447

**Comment by qg0** [comment] 2020-03-03 14:05
The same thing with freezing.
Also I've tried to launch the Telegram when the Plasma is off. The flag of the option was reseted to default (Telegram) notifications.
I propose to check if the Plasma is running before displaying this option when the user is opening the settings window and/or setting a flag to use native notifications.

**Comment by ilya-fedin** [comment] 2020-03-03 14:12
> The same thing with freezing.

Don't try to check with killing of plasma, it is absolutely not a typical situation and I don't try to support it. Just check if bug with autostart is fixed.

**Comment by qg0** [comment] 2020-03-03 14:49
I've logout and relogin a couple of times. It seems good and working, but the bug was not stable, like 1 per 5 logins, so maybe it would be in the future. Maybe it was also depended on KDE saved session when other apps spent the time for launching.

**Comment by ilya-fedin** [comment] 2020-03-05 00:26
Duplicate of #5590

**Closed** 2020-03-05 07:20 UTC
Labels: question

**Comment by Storm-Engineer** [comment] 2020-03-08 10:09
Now this is weird because that bug report is over a years old but for me this only started happening a few months ago.

**Comment by qg0** [comment] 2020-03-08 16:49
Delete the app from your autostart and write the script which starts the app after some delay and put it in the autostart.
Like
```
#!/bin/bash
sleep 20;
~/bin/telegram;
```

**Comment by Aokromes** [comment] 2020-03-08 17:00
i suggested preston to do that on the thing he uses to start.

**Comment by qg0** [comment] 2020-05-19 03:27
The Telegram version 2.1.5 is starting before KDE Plasma, so there are no native notifications. Also there was an error and the report was sent automatically.

Maybe the option `OnlyShowIn=KDE` should be required in the `$HOME/.config/autostart/telegramdesktop.desktop` file ?

**Comment by ilya-fedin** [comment] 2020-05-19 03:37
> The Telegram version 2.1.5 is starting before KDE Plasma, so there are no native notifications

Then there are a bug in KDE autostart code

> Maybe the option `OnlyShowIn=KDE` should be required in the `$HOME/.config/autostart/telegramdesktop.desktop` file ?

Exactly not
