### ISSUE TITLE
often crashing when forwarding messages

### ISSUE THREAD

**Issue by Ryder17z** [telegramdesktop/tdesktop#23928] opened 2022-01-19 08:12 UTC
### Steps to reproduce

1. select one or several messages
2. forward to somewhere
3. maybe the app crashes.
4. if it does not crash, try again.

### Expected behaviour

forwarding without crashing

### Actual behaviour

crash and the forward might be lost.

### Operating system

Manjaro Linux 21.2.1

### Version of Telegram Desktop

3.4

### Installation source

Other source 

### Logs

```shell
if started via the terminal:
$ telegram-desktop
(telegram-desktop:89952): Telegram-WARNING **: 17:48:22.949: Application was built without embedded fonts, this may lead to font issues.
error: : cannot open
error: : cannot open
error: : cannot open
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
  OpenType support missing for "Open Sans", script 11
  OpenType support missing for "Droid Sans", script 11
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
  OpenType support missing for "Open Sans", script 20
  OpenType support missing for "Open Sans", script 19
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment

then when a message is forwarded:
Segmentation fault (core dumped)
```

**Comment by ilya-fedin** [comment] 2022-01-19 08:22
> Static binary from official website

> ```shell
> (telegram-desktop:89952): Telegram-WARNING **: 17:48:22.949: Application was built without embedded fonts, this may lead to font issues.
> ```

Static binary from official website can't print such a warning. Looks like you provided false information.

**Comment by Ryder17z** [comment] 2022-01-19 08:39
> > Static binary from official website
> 
> > ```shell
> > (telegram-desktop:89952): Telegram-WARNING **: 17:48:22.949: Application was built without embedded fonts, this may lead to font issues.
> > ```
> 
> Static binary from official website can't print such a warning. Looks like you provided false information.

Seems the dropdown reset. It was supposed to be other sources

**Comment by ilya-fedin** [comment] 2022-01-19 08:40
Can you try the official build actually?

**Comment by Aokromes** [comment] 2022-01-19 09:24
also, the best is try 3.4.7 beta

**Comment by Ryder17z** [comment] 2022-01-19 09:53
official build does seem more stable but the default font seems a little bit buggy:
![image](https://user-images.githubusercontent.com/2000703/150104367-de23206c-f516-48cd-b508-ad0e286067eb.png)
The V in "even" isn't centered and it was either less visible or not in the old/alt builds. It's not a big issue but it does affect readability on my laptop which is running a 2k resolution and no scaling on 15 inch.

I would try switching to another font but I don't see that option.

**Comment by ilya-fedin** [comment] 2022-01-19 10:00
tdesktop doesn't support changing UI font.
@Aokromes can you close the issue since the crash is no longer reproducible?

**Closed** 2022-01-19 10:01 UTC
Labels: bug
