### ISSUE TITLE
Automatically Syntax-Highlight received Code

### ISSUE THREAD

**Issue by leolabs** [telegramdesktop/tdesktop#250] opened 2014-11-10 23:43 UTC
It would be great if we were able to send code snippets via Telegram in a way that is nicely readable by the receiver. I'm chatting a lot with other developers and often, I feel the need for such a feature.

Related issue on the Telegram bug tracker: https://bugs.telegram.org/c/824

**Comment by HallEffect** [comment] 2015-03-03 09:02
I absolutely agree. Syntax highlighting is very useful thing

**Comment by ezdev128** [comment] 2015-03-03 09:33
I disagree about automatic mode. Should be some markup language like [code]int main()...[/code] instead of automatic to avoid bugs and excessive CPU consumption on parsing messages.

**Comment by AryanShadowhunter** [comment] 2015-03-14 12:09
Nice Feature, Like that ;)

**Comment by mrpatiwi** [comment] 2015-04-08 11:23
+1

**Comment by jeyemwey** [comment] 2015-05-29 11:51
+1 :)

**Comment by rockneurotiko** [comment] 2015-06-07 19:23
:+1: !!

**Comment by Ziul** [comment] 2015-06-13 23:48
I would love that support! A markdown support as in GitHub or on HabitRPG's chat would solve well the problem about a non-dev sending a sample message and te app reading it as source code.

**Comment by rizo** [comment] 2015-07-02 02:26
+1

**Comment by takahser** [comment] 2015-07-09 13:45
+1

**Comment by yurtaev** [comment] 2015-07-13 10:20
:+1:

**Comment by ncravino** [comment] 2015-07-24 15:37
+1

**Comment by hugomrdias** [comment] 2015-07-27 15:57
+1

**Comment by faqie** [comment] 2015-07-28 08:25
+1

**Comment by nwcfang** [comment] 2015-08-05 10:43
+1

**Comment by mi-volodin** [comment] 2015-08-05 10:54
+1

**Comment by Lev91gor** [comment] 2015-08-06 09:25
+3.14

**Comment by ricardobanegas** [comment] 2015-08-12 10:02
+1

**Comment by andrecamposgm** [comment] 2015-08-12 18:04
+1

**Comment by andrecamposgm** [comment] 2015-08-12 18:07
I know telegram is a mobile-first application, but we already have this kind of functionality in other chat tools like slack that use it in both mobile and desktop implementation. 
This kind of markdown language would really help telegram to be adopted by technical teams on internal communication. I am trying to convince my team to replace slack and skype by telegram and this feature would help me a lot on this task! 
Keep doing this great work!

**Comment by stolidity** [comment] 2015-08-15 01:54
+1

**Comment by joeldrapper** [comment] 2015-08-30 11:45
:+1:

**Comment by MaxMommersteeg** [comment] 2015-09-08 16:56
Would love to see this feature!

**Comment by Lookingeast5** [comment] 2015-09-10 11:05
+1

**Comment by aldarionsevero** [comment] 2015-09-10 18:49
+1

**Comment by theetcher** [comment] 2015-09-15 10:51
+1

**Comment by lawrencegs** [comment] 2015-09-18 10:41
+1

**Comment by rizkix** [comment] 2015-09-18 10:42
+1

**Comment by auchri** [comment] 2015-09-18 10:45
I just unsubscribed from this issue because your "+1" comments are just annoying

**Comment by DaFri-Nochiterov** [comment] 2015-09-18 10:50
+1.00001

**Comment by Trigun27** [comment] 2015-09-19 13:46
+1

**Comment by isnifer** [comment] 2015-09-22 08:17
+1

**Comment by m16a1** [comment] 2015-09-24 07:12
+1

**Comment by dimkosru** [comment] 2015-09-25 07:08
+1

**Comment by tolwi** [comment] 2015-10-02 10:00
+1

**Comment by justedd** [comment] 2015-10-06 08:55
+1

**Comment by GreatMedivack** [comment] 2015-10-06 08:57
+2

**Comment by joeldrapper** [comment] 2015-10-06 13:18
@GreatMedivack you just had to be different to everone else :arrow_up:

**Comment by DaFri-Nochiterov** [comment] 2015-10-06 14:36
+1 from me and +1 from my cat <3

**Comment by DamirCiganovic-Jankovic** [comment] 2015-10-12 13:34
+1 from me

**Comment by kmyakotin** [comment] 2015-10-20 09:27
+1 most wanted

**Comment by dobleme** [comment] 2015-10-31 19:28
+1

**Comment by lawrencegs** [comment] 2015-11-01 05:40
What would be the best way to handle this? Slack does code highlighting, but its not markdown style, rather code upload. UX matters too.

**Comment by Kutsan** [comment] 2015-11-06 14:24
+1

**Comment by xtopolis** [comment] 2015-11-06 19:28
+1

**Comment by pascalchevrel** [comment] 2015-11-14 12:49
+1 for the same system as Github, backticks with the language code behind, would be super useful

**Comment by ttldtor** [comment] 2015-11-18 18:51
+1

**Comment by animalillo** [comment] 2015-11-22 00:12
+101

**Comment by pikachuPokemon** [comment] 2015-11-23 15:50
+1

**Comment by ricardobanegas** [comment] 2015-11-25 10:31
+1

**Comment by Marinofull** [comment] 2015-11-26 18:42
:+1:

**Comment by mrpatiwi** [comment] 2015-11-26 18:55
This was implemented, check this out:
![image](https://cloud.githubusercontent.com/assets/7570744/11429338/720679c4-9455-11e5-8eb7-42ef20a2ff8b.png)

```no-highlight
Inline `code` has `back-ticks around` it.
```

<pre lang="no-highlight"><code>```
var s = "Block highlighting";
alert(s);
```
</code></pre>

**Comment by Ziul** [comment] 2015-11-26 20:09
This is just the monospace, not Syntax-Highlight. And if a line have more than 51 characters, it breaks the line (if was even the 80 chars i would understand...but why 51?). And the mobile still not working well.
If the feature is already implemented, it need some improves.

**Comment by citec** [comment] 2015-12-10 16:59
+1

**Comment by bskydive** [comment] 2015-12-10 20:30
+1 highlight syntax like in gitter

**Comment by theus** [comment] 2015-12-12 19:26
+1

On Thu, Dec 10, 2015, 17:31 Valeriy Stepanov <notifications@github.com>
wrote:

> +1 highlight syntax like in gitter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/250#issuecomment-163741003>
> .
>
-- 

Theus Falcão
Sent by Gmail Mobile

**Comment by rmuhamedgaliev** [comment] 2015-12-19 13:48
👍

**Comment by gogl92** [comment] 2015-12-22 01:40
+1

**Comment by Niklan** [comment] 2016-01-08 11:08
+

**Comment by joeldrapper** [comment] 2016-01-10 21:46
It's worth noting that it's now possible to format code blocks by using the `@bold` bot which accepts markdown.

**Comment by Niklan** [comment] 2016-01-11 03:54
@joeldrapper `@bold` didn't support syntax highlighting and use word breaking to separate line. It's makes code more unreadable if you send some example to man for showing some example, it's hard to read and still better sending code with pastebin. It's needs horizontal scroll at minimum, but i don't know, support it's telegram or not.

**Comment by telegramdesktop** [comment] 2016-01-11 04:07
@Niklan Currently TDesktop does not support horizontal scroll in messages layout :(

**Comment by theus** [comment] 2016-01-13 13:21
Has no way to embed Pastebins links? However, a native option will be great.

**Comment by lawrencegs** [comment] 2016-01-13 14:00
If inline-bot is the preferred ways for bold & italic... then we will probably have to resort to inline-bot for this "programmer only" case?

**Comment by theus** [comment] 2016-01-13 14:09
Could be inline-bots a way to do this, but the API don't have a implement
to modify colors in text. It has only a simple markdown.

On 13 January 2016 at 11:00, Lawrence <notifications@github.com> wrote:

> If inline-bot is the preferred ways for bold & italic... then we will
> probably have to resort to inline-bot for this "programmer only" case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/250#issuecomment-171298571>
> .
>



-- 
Matheus Falcão.

**Comment by TiagoDanin** [comment] 2016-02-20 12:05
+1 :+1:

**Comment by zekefast** [comment] 2016-02-21 04:54
+1

**Comment by alessandrohc** [comment] 2016-02-24 13:07
+1

**Comment by mishudark** [comment] 2016-03-01 18:08
+1

**Comment by haimn** [comment] 2016-03-01 23:45
I love the ``` block and I use it a lot, but syntax highlighting will be a new level.

**Comment by Shahor** [comment] 2016-03-08 13:44
Well, I'm upping this since it would be really lovely and useful :+1:

**Comment by 0916174** [comment] 2016-03-08 14:39
+1

**Comment by kirsan31** [comment] 2016-03-10 16:25
@Niklan Indeed, we need resizable chat width at least.  I commented about it here: https://github.com/telegramdesktop/tdesktop/issues/1634#issuecomment-194929183

**Comment by renatorib** [comment] 2016-03-23 19:46
+1

**Comment by auchri** [comment] 2016-03-23 20:22
Use the new [reactions of GitHub](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) on **the first entry of this issue** instead of creating unnecessary `+1` comments.

**Comment by stek29** [comment] 2016-03-23 22:52
Reactions aren't available in mobile site yet.

**Comment by auchri** [comment] 2016-03-23 23:04
@stek29 I know - but you can easily switch to the desktop version.

**Comment by vgonisanz** [comment] 2016-03-30 15:03
With this feature, I will change hipchat for telegram desktop directly!

**Comment by givisok** [comment] 2016-04-06 06:24
Only that feature stops from using telegram on work.

**Comment by vgonisanz** [comment] 2016-04-07 07:09
We want to change skype/hipchat/hangout on work for telegram desktop :8ball:

**Comment by resetko** [comment] 2016-04-07 11:01
+1

**Comment by ekhlusov** [comment] 2016-04-07 11:02
This will be great, +1

**Comment by chibisov** [comment] 2016-04-25 13:22
We're waiting for this feature too! For now we've built a small bot which replies with `rtf` files. Looks convenient for mobile preview:
![image](https://cloud.githubusercontent.com/assets/522462/14785115/b2dcc2dc-0b01-11e6-8606-72418c7f9ceb.png)

https://telegram.me/pastemebot

It works in inline mode too replying with urls for `rtf` files.

**Comment by Mobilizr** [comment] 2016-08-07 12:49
Really hoping to see support for code snippets with syntax highlighting. Even better if Telegram would allow centralised viewing of all code snippets via the "Shared Media" viewer.

**Comment by gosteev** [comment] 2016-09-06 11:05
hmm...'shared code' inside media section - great idea. too great to be implemented 😄

**Comment by Dessix** [comment] 2017-01-04 21:07
LaTeX would be awesome to see available.

**Comment by Niklan** [comment] 2017-01-05 07:30
I think code must be like media files with little preview or just name and some meta info, but on click opens in new modal window with syntax highlighting. Also would be great if we can edit it and resend edited version after that.

**Comment by theus** [comment] 2017-01-06 11:14
At least here in Brazil, many developers uses Telegram so is very useful
this feature 😇

> --

Theus Falcão
Sent by Gmail Mobile

**Comment by Piterden** [comment] 2017-01-21 04:50
+1 support markdown and highlight syntax like in this chat

**Comment by milosjovac** [comment] 2017-02-20 21:14
+1

**Comment by berroteran** [comment] 2017-03-26 22:38
+999

**Comment by berroteran** [comment] 2017-03-26 22:38
Nicaragua, from centroAmerica, we like this

**Comment by Piterden** [comment] 2017-03-27 03:58
This would be nice
` ```php `
```php
class StreamsServiceProvider extends ServiceProvider
{
    use DispatchesJobs;
    protected $schedule = [];
}
```
` ``` `

**Comment by cauebs** [comment] 2017-05-26 23:11
Any progress on this? If not, is there any opposition?

**Comment by Piterden** [comment] 2017-05-26 23:15
I suppose, they just don't want to be the best messenger for programmers :)
![image](https://cloud.githubusercontent.com/assets/5930429/26515307/4dfc152a-4282-11e7-9624-37f0e83a2987.png)

**Comment by arenaq** [comment] 2017-05-26 23:28
Any progress on this? Cmn, it's not that hard to implement? If you are scared it might mess with non-programmer users, just make some obscure rules to enable it, we'll manage ;)

**Comment by Piterden** [comment] 2017-05-26 23:33
But, don't forget guys, there are some more serious problems. For example, Telegram, could be blocked in Russia soon, and so on...

That's interesting, could the community start such project based on inline bot. I had seen few implementations, but they are not enough convenient for everyday use.

**Comment by Piterden** [comment] 2017-05-26 23:42
Thoughts? Community! ))

**Comment by sigod** [comment] 2017-05-26 23:44
> If you are scared it might mess up with non-programmer users, just make some obscure rules to enable it, prefixes, etc., we won't mind :)

What? It's already done through use of code blocks. I'm talking about formatting, not highlighting. And it doesn't mess anything up for non-programmers. Or are talking about _autodetection_? I hope not, as it's very _bad_ idea.

> That's interesting, could the community start such project based on inline bot?

Nah. Inline bots are confusing. Should just have clear rules for formatting/highlighting.

**Comment by Piterden** [comment] 2017-05-26 23:56
Formatting is not so clear, so it could be. I mean, if you would write ` ``` ` multiline block, it would transform your code to many lines limited by ` sign.
It's not fully useful for some cases.

Highlighting that what we talk above.

Inline bots... Unfortunately, you are right. ((( This is weird thing. But, as I think, the problem is deeper, some low level problem, like the shell which not supports coloring? Correct me, please if I'm wrong.

**Comment by arenaq** [comment] 2017-05-27 08:15
> But, don't forget guys, there are some more serious problems. For example, Telegram, could be blocked in Russia soon, and so on...

Not our problem :)

> What? It's already done through use of code blocks. I'm talking about formatting, not highlighting. And it doesn't mess anything up for non-programmers. Or are talking about autodetection? I hope not, as it's very bad idea.

I am trying to come up with some reason why this is not yet implemented. So I hypothesized that maybe they are worried that autodetection could affect regular users, but I agree with you ofc, that such fears are missplaced.

**Comment by Piterden** [comment] 2017-05-27 11:01
> Not our problem :)
Whom do you mean, @arenaq ?
I think, it is general problem. At the first it is the problem of Pavel Durov.
But I agreed, this is offtop for here.

**Comment by arenaq** [comment] 2017-05-27 14:51
@Piterden I meant ppl that won't be affected by Telegram blocked in Russia. Was more like a joke, really.

**Comment by gogl92** [comment] 2017-05-27 15:06
Maybe something like this could be easier to implement instead of trying to do code detection
![slackcode](https://cloud.githubusercontent.com/assets/1505641/26522337/0119517c-42c4-11e7-831d-ff0dd421dc91.png)

**Comment by Piterden** [comment] 2017-05-27 15:49
Slack has the worst implementation of highlighting I ever seen.
The best implementation is here, on GitHub.

**Comment by ygbr** [comment] 2017-05-27 16:02
Still better than nothing, which is what we currently have on Telegram

**Comment by Piterden** [comment] 2017-05-29 07:03
Does Telegram support any type of modal dialog?

**Comment by rockymontana** [comment] 2017-08-24 19:30
Yes. It does. :-)
![image](https://user-images.githubusercontent.com/330839/29684736-530ccf28-8913-11e7-9036-3b6f47c70339.png)

**Comment by Piterden** [comment] 2017-08-30 01:22
Btw, guys. I had avoid that problem with the ST3 and its Export HTML plugin. I even have highlighting with my own colors.
[Gallery.vue.html.zip](https://github.com/telegramdesktop/tdesktop/files/1262169/Gallery.vue.html.zip)
You need to unpack and open it in browser then.

**Comment by rockymontana** [comment] 2017-08-30 05:09
You shouldn’t share files like that.Why don’t you just create a repo and show the source instead? Otherwise noone have a clue what they’re downloading and opening.
		
		

		Get Outlook for iOS
	




On Wed, Aug 30, 2017 at 3:22 AM +0200, "Denis Efremov" <notifications@github.com> wrote:












Btw, guys. I had avoid that problem with the ST3 and its Export HTML plugin. I even have highlighting with my own colors.

Gallery.vue.html.zip

You need to unpack and open it in browser then.

**Comment by Piterden** [comment] 2017-08-30 05:14
@rockymontana 
Bro, you shouldn't leave comments like this ^
:rofl:

**Comment by gogl92** [comment] 2017-09-14 17:41
Maybe...
Preformatted text now displayed in beautiful block.
![photo_2017-09-14_12-30-11](https://user-images.githubusercontent.com/1505641/30444824-d745fd1e-9949-11e7-9c59-baadea1d2063.jpg)
SOURCE: @tentangtelegram

**Comment by stek29** [comment] 2017-09-14 22:30
That's completely unrelated to TDesktop and to syntax highlighting.

**Comment by Piterden** [comment] 2017-09-14 22:37
My tg don't have this ^

**Comment by ygbr** [comment] 2018-01-03 14:12
+1 for 2018!!!

**Comment by Piterden** [comment] 2018-01-03 14:25
https://github.com/Piterden/syntax-highlighter-bot
https://t.me/cris_highlight_bot

**Comment by Piterden** [comment] 2018-01-10 05:25
![image](https://user-images.githubusercontent.com/5930429/34757036-cde2ee42-f5df-11e7-9abb-d8215f9beb7f.png)

**Comment by JulianAtlas** [comment] 2018-01-27 07:07
Code highlighting, and extend the 51 character limit per line please!

**Comment by lolgab** [comment] 2018-01-28 11:46
\```languageName
code
\```
syntax like markdown would be perfect... No need to detect the language (which is not only difficult but error prone)..

for example:
\```java
public class MyClass {
&nbsp;&nbsp;public static void main(String[] args) {
&nbsp;&nbsp;&nbsp;&nbsp;System.out.println("Hello world");
&nbsp;&nbsp;}
}
\```
should give
```java
public class MyClass {
  public static void main(String[] args) {
    System.out.println("Hello world");
  }
}
```

and
\```python
def mysum(x, y):
&nbsp;&nbsp;&nbsp;return x + y
\```
should give
```python
def mysum(x, y):
   return x + y
```

**Comment by ShavidzeT** [comment] 2018-04-17 13:27
Is any news about code highlighting?
Does someone work on this feature?

**Comment by Piterden** [comment] 2018-04-17 13:33
@ShavidzeT, ya it should be rewritten, I had stopped it now.

**Comment by ShavidzeT** [comment] 2018-04-17 14:01
@Piterden I see that it's useful feature for telegram, if you looking for maintainers, I can help.
I'll ping you on your email.

**Comment by AndydeCleyre** [comment] 2018-04-19 03:15
As a workaround, I made https://t.me/colorcodebot . It's susceptible to #522 problems.

**Comment by Piterden** [comment] 2018-04-19 03:25
You know, we could also add there a question about a preferred file format. @AndydeCleyre

**Comment by AndydeCleyre** [comment] 2018-04-19 12:16
@kirsan31 I'm hoping for an in-app solution as well. The benefits of the bot for me: 

- I'm running it, so I can safely share private code
- sender doesn't have to leave Telegram
- quick viewing, especially when associating local html files with a simple renderer

**Comment by gogl92** [comment] 2018-04-19 12:31
I always wanted the idea of having a in-app browser inside tdesktop, I made this concepts

**Comment by kirsan31** [comment] 2018-04-19 12:32
> quick viewing, especially when associating local html files with a simple renderer
Exactly! 

> Guys, we need the instant view of highlighted code!!!
> The bot can share statically the prepared for an instant view HTML files.

If it's possible, I think this is the right direction...

**Comment by AndydeCleyre** [comment] 2018-04-19 20:00
@kirsan31 I invite you to take further colorcodebot discussion to [its own issues page](https://github.com/AndydeCleyre/colorcodebot/issues), and let me know which of these you would appreciate included: [theme previews](https://t.me/ColorCodeBotThemes)

**Comment by Piterden** [comment] 2018-04-23 20:25
@AndydeCleyre did you see this stuff?
https://github.com/revolunet/sublimetext-html-export

**Comment by therecluse26** [comment] 2018-04-26 19:04
Puhleaaase add github-like code highlighting. That would be amazing.

**Comment by kirsan31** [comment] 2018-05-01 21:25
If anyone interested, my [workaround](https://github.com/kirsan31/tdesktop/blob/master/docs/html-code-processing.md) for this problem:
<details><summary><b>Preview</b>:</summary>  

![example](https://github.com/kirsan31/tdesktop/raw/master/docs/assets/html.gif?raw=true)  

</details>

**Comment by ShavidzeT** [comment] 2018-05-02 10:28
@kirsan31 your approach looks better but we still need markdown support 😄

**Comment by olleharstedt** [comment] 2018-08-28 12:14
Bump.

**Comment by Piterden** [comment] 2018-08-28 16:41
@kirsan31 so does your approach need html key for c++ code?

**Comment by kirsan31** [comment] 2018-08-28 16:57
I like your idea with html file creating by bot. So I thinked, if I can create and send such file on the fly in telegram (if I have html markup in clipboard)... 
In my [mod](https://github.com/kirsan31/tdesktop/blob/master/docs/html-code-processing.md) you need to type ` ```html` and then paste your html code.
Yes, it's not so good approach, but we are using it along with sending files from bots.

**Comment by AndydeCleyre** [comment] 2018-08-28 18:50
@olleharstedt can I ask if you've tried my bot? https://t.me/colorcodebot

**Comment by adrianopol** [comment] 2018-09-12 13:58
Totally disagree with this feature. Telegram is for chatting and sharing media, it is not a developer-specific tool. For code sharing use Slack, Mattermost, or whatever.

1. Any unnecessary complexity implies increased RAM consumption, more bugs in code, slower interface rendering.
2. All platform client implementations are not very suitable for sharing code due to a very limited line length (up to only 50 symbols).
2. If the code (regardless of language) needs highlighting to be understood, it's the ugly code and needs to be rewritten. :)

**Comment by arenaq** [comment] 2018-09-12 14:57
@adrianopol disagree with you completely.

How is being a developer relevant for Telegram usage? Developers are users too and they want to chat and share as well as others. When I chat with my friends how happens to be developers as well, I don't want to invite then to different platform just because I want to send them a small code snippet.

By the way, how do you know what is Telegram for? By the same logic you could have argued, before introducing Telegram calls, that it was meant only for texting and for calls and therefore ppl should go to Skype, Discord, or whatever. Are you saying that you won't accept any change at all?

1. Theoretically, yes. In practice, it is insignificant to features like mentioned calls. I would even argue that it would not consumed any more RAM than before. Maybe you meant CPU or HDD, but RAM would not suffer at all (if any, we are talking about few kB for a few seconds).
2. Not sure, where did you took that number. The line on my platform shows 71 chars. But, you argue that the implementation are not suitable. I would argue that since there is a demand it means that people are using it already, they just want syntax highlight (which have nothing to do with line breaks).
3. Are you saying that syntax highlighting is useless and that IDE's are only supporting it cause of ugly code? It is not about "if" it will be understood, but how. I believe that if you would be looking at it for a while, you would figure it out eventually, but wouldn't it be nice to get that right away? As well as if all messages would be mirrored upside down, it would still be understood, but it would not be as pleasant reading, right?

**Comment by gogl92** [comment] 2018-09-12 15:09
@adrianopol I think that we do not need "Automatically Syntax-Highlight" we need a "Syntax-Highlight Snippet" that when you need you can Highlight the code in a message.

**Comment by Piterden** [comment] 2018-09-12 15:11
> 3. If the code (regardless of language) needs highlighting to be understood, it's the ugly code and needs to be rewritten. :)

Why do you highlight your chat then?
![image](https://user-images.githubusercontent.com/5930429/45434469-32a8e500-b6b7-11e8-8811-fc8948e689cb.png)

**Comment by arenaq** [comment] 2018-09-12 15:18
@adrianopol I believe it is just misleading title. If you read what author of this topic wrote, it seems to me that it is very similar to what you are proposing.
> It would be great if we were able to send code snippets via Telegram in a way that is nicely readable by the receiver. I'm chatting a lot with other developers and often, I feel the need for such a feature.

**Comment by adrianopol** [comment] 2018-09-12 16:11
@arenaq,

> How is being a developer relevant for Telegram usage?

Because this feature is useless for everyone except SW developers. I am not about discarding any improvements or features at all. My message was about a niche feature. Suppose photographers asking for a .psd file previewer, mathematicians asking for LaTeX support, and so on.

Support for calls is a marketing feature, and it is meaningful for all users, so this is not a valid comparison.

Any software product is always a compromise between [a number of features expected by users] and [a number of bugs, fast UI reaction, and a good interrelation between existing features].

The key point is that small code snippets are enough readable without highlighting, and the large ones suffer from size limitation, making them absolutely unreadable (regardless of any highlighting).

> it seems to me that it is very similar to what you are proposing

Well, talking about a separate media type (like images, videos) with its own viewer is a more reasonable way, I suppose. But most examples and suggestions are about inline support.

**Comment by Piterden** [comment] 2018-09-12 16:19
Try my bot @adrianopol 
[@cris_highlight_bot](https://t.me/cris_highlight_bot)

Compare this two ways.
```
horizontalWords () {
  const words = []
  let row = 1

  for (row; row <= this.width; row++) {
    const rowBlankCells = this.blanks
      .filter((cell) => Number(cell.split(':')[1]) === row)
      .map((cell) => Number(cell.split(':')[0]))

    if (rowBlankCells.length > 0) {
      let i = 1
      const cols = new Array(this.height).fill(0).map((col) => i++)

      if (cols) {
        `:${cols.join('::')}:`
          .split(new RegExp(`:${rowBlankCells.join(':|:')}:`))
          .filter((word) => {
            const match = word.match(/:\d+:/g)

            return match ? match.length > 1 : false
          })
          .forEach((word) => {
            const match = word.match(/:\d+:/g)
            const length = match ? match.length : 0

            words.push({
              x: Number(word.match(/^:(\d+)/)[1]),
              y: row,
              type: 'horizontal',
              length,
              question: '',
            })
          })
      }
    } else {
      words.push({
        x: 1,
        y: row,
        type: 'horizontal',
        length: this.width,
        question: '',
      })
    }
  }

  return words
},
```

![image](https://user-images.githubusercontent.com/5930429/45438766-a7345180-b6c0-11e8-9138-e56e4ed9a6ae.png)

**Comment by arenaq** [comment] 2018-09-12 17:37
@adrianopol
> Because this feature is useless for everyone except SW developers.

> Support for calls is a marketing feature, and it is meaningful for all users

I do not believe it is (to both).

> Suppose photographers asking for a .psd file previewer, mathematicians asking for LaTeX support, and so on.

I wouldn't mind. If there will be reasonable demand for it and wouldn't affect other users, why not?

Yes, you are right, it is a compromise, but this is a tiny feature that would not impact performance. In regards of bugs, UI reaction time - this really is negligible, since there are many optimized libraries that can do that.

I would understand the argument about too many options in UI for other users, but since this would be sort of hidden feature, not even that would apply.

And I do believe that in case of snippets, size does not matter. Should be highlighted even when it's just one line :)

PS: I am not talking about parsing all the messages that user type and looking for code, but rather introduce a new syntax for formatting (as now with "`" character, as markdown has for example)

**Comment by Piterden** [comment] 2018-09-12 18:50
Just like here on GitHub would be nice. @arenaq 
```
```c++
#include <iostream>
using namespace std;

int main()
{    
    int number;

    cout << "Enter an integer: ";
    cin >> number;

    cout << "You entered " << number;    
    return 0;
}
```


```c++
#include <iostream>
using namespace std;

int main()
{    
    int number;

    cout << "Enter an integer: ";
    cin >> number;

    cout << "You entered " << number;    
    return 0;
}
```

**Comment by arenaq** [comment] 2018-09-12 20:59
@Piterden yep, that's exactly what I had in mind 👍

**Comment by simonneutert** [comment] 2020-01-20 20:55
yes, please 👍

**Comment by danwalmsley** [comment] 2020-04-28 18:24
Im from a group of devs and we have left gitter for telegram... this is the only feature we miss.

Please implement or opensource so we can send you a PR :)

**Comment by s-barannikov** [comment] 2020-06-13 19:19
Any updates?

**Comment by RusseII** [comment] 2020-07-31 16:41
![image](https://user-images.githubusercontent.com/15036618/89057070-a6435200-d322-11ea-9cd6-c39f437ff405.png)

They have an example of this with python, but it does NOTHING different

**Comment by SvenWritesCode** [comment] 2020-07-31 16:41
Could you post a link to that image? Hard to tell if that is the api docs or some other library. @RusseII

**Comment by kirsan31** [comment] 2020-07-31 16:47
> Could you post a link to that image? Hard to tell if that is the api docs or some other library. @RusseII

https://core.telegram.org/bots/api#markdownv2-style

**Comment by SvenWritesCode** [comment] 2020-07-31 16:52
I see. Tested it out, and it does remove the language and display the text, but doesn't highlight. Though the docs don't claim it should highlight anything.  
![image](https://user-images.githubusercontent.com/7458951/89058004-8c0e7180-d32c-11ea-8438-9acc9e44bee2.png)

**Comment by kirsan31** [comment] 2020-07-31 17:00
@SvenWritesCode This is the **bot** api. Must work thru bot, but not from client :(

**Comment by kirsan31** [comment] 2020-10-23 10:24
> This issue will be automatically closed in 7 days if there would be no activity. We therefore assume that the user has lost interest or resolved the problem on their own.
> 
> Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the issue.

This bot will close **all** issues due to _no spam_, but reactions policy :)))))

**Comment by Jadd** [comment] 2020-12-07 04:24
Bump. Considering this issue is from 2014, I have to assume the telegram devs use a different chat client, lol.

**Comment by Piterden** [comment] 2020-12-07 04:30
> Bump. Considering this issue is from 2014, I have to assume the telegram devs use a different chat client, lol.

They use Discord :laughing:

**Comment by Jadd** [comment] 2020-12-07 04:59
> They use Discord 
> 
> UPD: Or maybe Pavel bought to them enterprise Slack?

Literally every other chat client has this feature. Get with the times, telegram. 🙄

**Comment by mikhailpashkov** [comment] 2021-01-14 15:22
I'm waiting this feature for more that 4 years.
```python
Hope this will be implemented()
```

**Comment by Piterden** [comment] 2021-01-14 21:39
> I'm waiting this feature for more than 4 years.
> 
> ```python
> Hope this will be implemented()
> ```

You are able to use my bot until that feature will be done. 
@cris_highlight_bot 
It's ready to work in groups without any admin privileges.

**Comment by RememberTheAir** [comment] 2021-01-15 07:50
Just dropping here Telegram's "bugs & suggestions" platform card for this issue, so everyone can upvote it: https://bugs.telegram.org/c/824

**Comment by Sparpvp** [comment] 2021-03-24 14:11
Any updates?

**Comment by AndydeCleyre** [comment] 2021-06-28 15:43
I know this isn't the *real* improvement everyone's hoping for, but FWIW I spruced up [my syntax-highlighting bot](https://github.com/AndydeCleyre/colorcodebot) a bit, and you can see [a demo video here](https://user-images.githubusercontent.com/1787385/123204250-ae9a0380-d485-11eb-981d-3302220aad58.mp4).

**Comment by iasj** [comment] 2021-08-06 06:29
This feature would greatly save storage for Telegram's servers over time. I often take a screenshot of the code and share it together with the code itself, so people can how to code should appear. The picture would become obsolete if this feature existed.

Also, a copy to clipboard button -on the side of the code - would be an even better addition.

**Comment by ilya-fedin** [comment] 2021-09-17 07:11
> There's a vscode extension for telegram I'd love to use

Am I missing something?
![изображение](https://user-images.githubusercontent.com/17829319/133740144-c63842ae-478f-472d-ad75-95c0dd72fe34.png)

**Comment by amogorkon** [comment] 2021-09-26 16:19
> > There's a vscode extension for telegram I'd love to use
> 
> Am I missing something?
> ![изображение](https://user-images.githubusercontent.com/17829319/133740144-c63842ae-478f-472d-ad75-95c0dd72fe34.png)
![Unbenannt](https://user-images.githubusercontent.com/16521496/134815756-fd74419d-e763-4a00-aa3e-255d35ef5868.PNG)

**Comment by ilya-fedin** [comment] 2021-09-26 16:23
for me it returns nothing :(

**Comment by amogorkon** [comment] 2021-09-26 16:26
What version are you running? I've got 1.60.2

**Comment by ilya-fedin** [comment] 2021-09-26 16:30
VSCodium 1.59.0

**Comment by amogorkon** [comment] 2021-09-26 16:33
Could be related to https://github.com/VSCodium/vscodium/issues/448

**Comment by Miuler** [comment] 2022-09-09 03:58
Please, add Syntax-Highlight

**Comment by adriangalilea** [comment] 2023-04-16 19:02
Just here to also bump the request of Syntax-highlight.

**Comment by vsolontsov-ll** [comment] 2023-05-17 08:31
+1 for this feature!

**Comment by Andrew15-5** [comment] 2023-05-24 17:40
+1 for manual code block:

\```language
\```

**Comment by Andrew15-5** [comment] 2023-05-24 17:48
As was pointed out [here](https://bugs.telegram.org/c/824), [web](https://web.telegram.org/a) version does support manual code block (as I showed in my previous comment), but not for all languages. I tried `python` and `latex` and only the first one works (GitHub supports both).

**Comment by kirsan31** [comment] 2023-10-05 06:43
It's coming? 🤔🙏
https://github.com/telegramdesktop/tdesktop/commit/2414e927bd2e4fa313932d14fa285bb91550b666

**Comment by john-preston** [comment] 2023-10-05 06:46
It's done in some way. In the upcoming version you'll be able to specify language after triple-tick:

\`\`\`cpp
code here
\`\`\`

Then it'll be a usual monospace block but with some syntax highlighting on top. It won't be supported in the message input field (at least for now, maybe ever), but some improvements may come when there is more time for that.

**Comment by john-preston** [comment] 2023-10-05 06:47
Lines will break as before, implementing a horizontal scroll for a part of a message in the middle of the message bubble is something really complex and not planned right now.

**Comment by kirsan31** [comment] 2023-10-06 15:31
@john-preston 
First of all - thank you 🙏

I've tried current build. Bugs:
1. ` ```cs` (default for c#) doesn't work, ` ```dotnet` doesn't work too, only ` ```csharp` is working.
2. For cpp and c# and  I think for all same synaxis - wrong color for last closing bracer: 
![image](https://github.com/telegramdesktop/tdesktop/assets/17767561/a735c2f5-0675-4e4b-bcf6-9f8ada37b31e)

**Comment by john-preston** [comment] 2023-10-09 06:05
@kirsan31 I see, prism.js has aliases for languages, that aren't handled in the libprisma fork. Thanks for pointing that out.

Last bracer is a bug, thanks, fixed in code.

**Comment by Aokromes** [comment] 2023-10-21 19:13
https://github.com/telegramdesktop/tdesktop/commit/b209683c8e98692ef4d18245fd645b1e7aea78d9

**Closed by Aokromes** 2023-10-21 19:13 UTC
Labels: enhancement

**Comment by Piterden** [comment] 2023-10-23 22:26
@john-preston , first of all thank you so much for this feature! Looks really good, but there are a few remarks:
- Unnecessary line wrap. And here is what it looks like:
![image](https://github.com/telegramdesktop/tdesktop/assets/5930429/a8ca538b-461a-4f8c-abc4-f23f751c588c)
- It is impossible to change the highlighting language, moreover, when editing, the text indicating the language disappears completely. I would make a drop-down menu with a list of languages.
- Lack of reaction to the change of app theme. It seems to me that it would be logical if the syntax highlighting colors were set by the theme editor, because there are not so many different highlighting areas to put them there.
- Many people are using monospace font not for code, so the word `code` when no language is specified seems a bit superfluous to me. Monospaced code-blocks have the ability to be copied by a click on them and I had seen many times people are using this feature. But if be honest, it bothers me personally.
- It would be ideal to have internal a code recognizer.

> PS About prismjs: it hasn't code recognizer and this was the main reason I refused it, as I remember. I used highlight.js instead.

**Comment by john-preston** [comment] 2023-10-24 05:07
1. Providing horizontal scrolling inside the message bubble is a very complex task on its own and not planned in this release definitely. Maybe later if there'll be time. Might be in another nine years though 🫣
2. Editing is bad indeed, should be improved somehow.
3. The colors are taken from theme, but from statistics color keys 😂 
4. For quotes there will be a dedicated feature starting with this release. So monospace code blocks are left for code. They can be copied by a click on the block title.
5. It would be.

**Comment by rtfmoz2** [comment] 2023-10-29 00:20
So what languages are supported. There is no doco anywhere and once I find out I can update

**Comment by kirsan31** [comment] 2023-10-29 07:45
> So what languages are supported.

https://prismjs.com/index.html#supported-languages

**Comment by AndydeCleyre** [comment] 2023-10-29 22:00
> > So what languages are supported.
> 
> https://prismjs.com/index.html#supported-languages

This list includes Factor, but I don't get any highlighting for that in the latest Android app.

**Comment by Andrew15-5** [comment] 2023-10-29 22:44
Speaking of Android app, I immediately noticed that syntax colors differ between desktop and mobile app. I even applied my custom "desktop" theme on the smartphone, and it still shows different colors on the same message with a code. I checked and didn't see any color values that are applied to the code. So these code color schemes are platform dependent. This is not what I expected. And I want to say that Android colors are better (at least green color for `"strings"` is more natural IMO than orange).

So, adding a list of color schemes would be a huge feature. Imagine, every dev will see the same code message (in a group chat) in the color scheme that they want. This would be amazing. But it would require a separate menu (section) with a variety of color schemes, including custom ones. But if this is too ambitious, then a set of values in theme's color palette, which are specific for each code token type (string, number, keyword etc.), would do the trick.
