### ISSUE TITLE
Something is wrong (i think)

### ISSUE THREAD

**Issue by eVanilla** [telegramdesktop/tdesktop#4325] opened 2018-01-19 08:30 UTC
something is wrong with telegram in past two days.. every time i open the application, the program closes automatically but some times it works fine, any idea?
* telegram version: **1.2.6**
* default theme and night mode
* os: **windows 7**

**Comment by rezazoom** [comment] 2018-01-19 12:34
Same problem on **Windows 10 Pro** with Telegram Desktop **Version 1.2.6**!

**Comment by john-preston** [comment] 2018-01-19 12:43
@rezazoom Should be fine already. Client side fix will be in the next version, the bug should've been caused by wrong server data.

**Closed** 2018-01-19 14:02 UTC
