### ISSUE TITLE
telegram-desktop for Raspberry Pi

### ISSUE THREAD

**Issue by sallyahaj** [telegramdesktop/tdesktop#16949] opened 2021-09-13 06:05 UTC
### Is your feature request related to a problem?

I am using telegram-desktop on raspberry pi 4 on Fedora 34, I have used flathub to install it, but the app doesn't function as normal, it is very slow + couldn't do video or audio chat through it.

### Describe the solution you'd like

I would like to see an official telegram-desktop for arm64/aarch64, as there is a huge number of arm processors in used.
Thank you.

### Describe alternatives you've considered

There is I think a debian package on its repos for arm64, but not in Fedora.

**Comment by ilya-fedin** [comment] 2021-09-13 15:03
Sorry, there's no plan to produce official builds for ARM processors due to cross-compilation burden and I don't think it will help with the fact it works slowly. Anyway, it's a duplicate of #1924.

**Closed** 2021-09-13 16:06 UTC
Labels: enhancement
