### ISSUE TITLE
Lack of any filters and blocking messages from specific  users in group chats 

### ISSUE THREAD

**Issue by Butcer** [telegramdesktop/tdesktop#4970] opened 2018-07-13 00:05 UTC
### Steps to reproduce
1.  Go to supergroup shopping channels
2.  Alot of stuff posted there i dont like but other stuff i like so iwant to filther and remove those posts from local chache so i dont see them 
3. Even after blocking users i still see there messages in group chat

### Expected behaviour
That Telegram would do something as basic as having the option to not see messages from blocked users 
Tell us what should happen
You add a person on blocklist and autodeletes all his posts from the local chache plus you wont see any new ones from hi
### Actual behaviour
Nothing, You might even think that the progarmers of Telegram are stuck in the 90´s and the idea of a filter and blocking user (as in never see any messages from that person on group chat) is somehow foreign 

### Configuration
Windows 10

**Version of Telegram Desktop:**
1.3.9

**Comment by zeroone2numeral2** [comment] 2018-07-13 09:01
Duplicate of #1281 and #2361

**Closed** 2018-07-13 10:52 UTC
