### ISSUE TITLE
Touchpad scrolling is jittery/laggy on GNOME Wayland

### ISSUE THREAD

**Issue by DualityKyle** [telegramdesktop/tdesktop#16118] opened 2021-04-11 19:56 UTC
### Steps to reproduce
1. Install tdesktop on a system running GNOME Wayland
2. Open a window and scroll the chat list or messages
3. Notice the lag/jitteryness
4. Plug in a mouse and scroll, the scrolling seems fine
5. Log out of the GNOME session, and set the session to Xorg before logging back in. You'll notice touchpad scrolling is fine

### Expected behaviour
The scrolling should be smooth

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Fedora Workstation 34

**Version of Telegram Desktop:**
2.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Distribution package (rpmfusion repo)

**Used theme**:
Stock

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment] 2021-04-11 21:47
Please check the issue on the official binary from https://desktop.telegram.org

**Comment by ilya-fedin** [comment] 2021-04-11 21:55
I can't reproduce the issue on Weston

**Comment by DualityKyle** [comment] 2021-04-12 00:12
@ilya-fedin - Just tried the official flatpak from the URL you posted. I'm still having the same issue.

Perhaps this is specific to Mutter rather than Weston? Whatever other data or testing you need from me I'm happy to do.

**Comment by ilya-fedin** [comment] 2021-04-12 00:14
> Just tried the official flatpak from the URL you posted.

No, I meant official static binary. Please check it.

**Comment by DualityKyle** [comment] 2021-04-12 00:30
Ah, I'm running Fedora so that might explain why the issue remains, they're likely both the same version.

The static binary is working perfectly, scrolling is smooth as butter.

Is this something I would need to report to the Fedora folks?

**Comment by ilya-fedin** [comment] 2021-04-12 00:32
> Is this something I would need to report to the Fedora folks?

Well, one of their Qt patches is forced native Wayland (upstream Qt blacklists GNOME for Wayland since there are still big bugs that are specific only to GNOME, but looks like Fedora folks don't care), so maybe you want to recheck with `QT_QPA_PLATFORM=wayland`

**Comment by DualityKyle** [comment] 2021-04-12 00:54
Thanks for the tip, unfortunately it didn't work.

Since the issue clearly isn't anything on your end I'm fine to close this out. I'll pursue the the issue with them and hope something can be figured out. :)

**Comment by ilya-fedin** [comment] 2021-04-12 01:01
:thinking: i wonder whether this could be an upstream Qt bug actually and fixed by one of tdesktop's patches, e.g. https://github.com/desktop-app/patches/blob/master/qtbase_5_15_2/0015-count-scrollbar-sizehint-only-when-needed.patch

**Comment by DualityKyle** [comment] 2021-04-12 01:12
Out of my are of expertise, but it's definitely possible. I'm happy to leave this issue open and updating/testing once the upstream patch gets implemented?

**Comment by ilya-fedin** [comment] 2021-04-12 01:20
> I'm happy to leave this issue open and updating/testing once the upstream patch gets implemented?

I guess upstream Qt is not even aware of this... But I think you can [build](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md) tdesktop yourself, adding to the [Dockerfile](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/build/docker/centos_env/Dockerfile) a `RUN cd patches && rm qtbase_5_15_2/0015-count-scrollbar-sizehint-only-when-needed.patch` line right after 33th line (with git clone). Or even remove entire patching code: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/build/docker/centos_env/Dockerfile#L527-L531. And check whether issue will appear after this or not.

**Comment by DualityKyle** [comment] 2021-04-12 22:39
@leha-bot - Thanks, this does work but the ability to resize the tdesktop window is lost. Is there any way around that?

**Comment by ilya-fedin** [comment] 2021-04-12 22:44
> so maybe you want to recheck with `QT_QPA_PLATFORM=wayland`

@DualityKyle I wonder whether this is possible that you specified this variable incorrectly to the official binary? Can you try again and check the string with information about OS in `Privacy & Security -> Show all sessions`? It should show whether Wayland or XWayland (X11) is used.

**Comment by DualityKyle** [comment] 2021-04-12 22:49
![image](https://user-images.githubusercontent.com/26319313/114472200-3206c100-9bc8-11eb-9352-5f0d31e961dc.png)

Appears it is indeed using Wayland

**Comment by ilya-fedin** [comment] 2021-04-12 22:53
> Appears it is indeed using Wayland

And doesn't have lags?

**Comment by DualityKyle** [comment] 2021-04-14 05:35
The official binary on the site never had issues. I was trying the various fixes with the Fedora repo package. Launching the repo version with QT_QPA_PLATFORM=xcb has removed the stuttering. I'm satisfied with this solution, so I think we're fine to close out this issue. :)

**Comment by ilya-fedin** [comment] 2021-04-14 05:38
Weird Fedora package

**Closed** 2021-04-14 06:03 UTC

**Comment by skidnik** [comment] 2021-05-19 06:58
## Expected Behavior

Smooth scrolling when using a touchpad.

## Current Behavior

When using a touchpad for srolling the app stutters for random period of time from 0.5 to 3 seconds.

## Steps to Reproduce

1. Have a device with a touchpad.
2. Install Fedora Workstation 34, log in to Gnome wayland session (default).
3. Download and unpack the official Telegram desktop appimage archive.
4. Start the app using `QT_QPA_PLATFORM=wayland ./Telegram/Telegram` commandline.
6. Try to scroll a chat or a settings menu.
7. Observe the app becoming unresponsive for a short period of time.

## Detailed Description

When using the telegram desktop app on Gnome 34 wayland session trying to scroll a chat or a menu inside the app results in the app becoming unresponsive for 0.5 to 3 seconds, after which the the interface refreshes with a result of scrolling visible (the chat is scrolled up/down approximately as expected).

This issue is specific to gnome environment. It does not reproduce in weston or sway.

This issue does reproduce with the rpmfusion package, the [official binary](https://telegram.org/dl/desktop/linux) and the flatpak package from flathub if forced to start as native wayland client.

## Configuration

Device: Dell Inc. Inspiron 11-3168

Touchpad: Synaptics TM3207-001, over libinput driver.

OS: Fedora 34 (Workstation Edition)

Gnome: 40.1.0

mutter: 40.1

wayland: 1.19.0

Telegram binary version: 2.7.4

## Additional notes

My laptop also has a touchscreen that, unlike the touchpad, is handled by the i2c_hid driver, and scrolling using it does not cause the app to stutter.

I see why you don't want to bother trying to fix this yet while the only version that is started as native wayland client by default is the rpmfusion package and the only distribution effected so far is Fedora Workstation. But the issue is not specific to Fedora packaging as it does reproduce with the official binary if it's forced to be a native wayland client.

**Comment by ilya-fedin** [comment] 2021-05-19 07:19
> I see why you don't want to bother trying to fix

Because no idea how to fix that. This issue is so specific: you should have Fedora, you should have GNOME, you should have Wayland, you should have Intel processor with intel_pstate powersave governor, I'm just not able to reproduce that. I asked people from #8347 to bisect through official binaries including beta versions multiple times, but no one wants to, so I gave up and asked to let the bot to close the issue.

**Comment by skidnik** [comment] 2021-05-19 15:01
Attaching the logs.

All I did here was launch on Gnome, choose the chat, scroll up using the touchpad, wait for reaction, scroll down, wait for reaction, close.

One is the output of `WAYLAND_DEBUG=1 QT_QPA_PLATFORM=wayland ./Telegram |& tee t_w_debug.log`, mostly wayland debug there.

The other is the `~/local/share/TelegramDesktop/log.txt`.

[t_w_debug.log](https://github.com/telegramdesktop/tdesktop/files/6509489/t_w_debug.log)
[log.txt](https://github.com/telegramdesktop/tdesktop/files/6509478/log.txt)

In case it helps.

And, btw, Intel CPU is in about 90% of laptops, I don't say that you should install Fedora immediately, but that if this issue doesn't accidentally fix itself, it will eventually spread with the adoption and forcing of wayland by other distributions. I don't think this depends on the powersave governor, rather the powersave one makes things more noticeable, maybe IO scheduling, but then why the CPU at all. To me the issue seems to be somewhere in the libinput-mutter-telegram chain, but then what do I know about these things, I'm just a regular user.

**Comment by ilya-fedin** [comment] 2021-05-19 15:07
> In case it helps.

I'm not a Wayland expert and Wayland log gives nothing to me, sorry.

> but then what do I know about these things, I'm just a regular user.

Telegram uses high level Qt APIs don't expect that anyone here is able to debug such low level bug...

**Comment by ilya-fedin** [comment] 2021-05-19 15:10
> it will eventually spread with the adoption and forcing of wayland by other distributions.

Well, maybe then someone will give something that will help to fix that.

**Comment by LastLightSith** [comment] 2021-06-10 13:26
I can reproduce this issue on KDE Wayland on ArchLinux. Its not specific to GNOME or Fedora
Should I open new issue ?

**Comment by ilya-fedin** [comment] 2021-06-10 15:36
> I can reproduce this issue on KDE Wayland on ArchLinux.

With official binary?

**Comment by LastLightSith** [comment] 2021-06-11 05:48
> With official binary?
Yes I downloaded the tar file from releases page from github.

Both, package from Arch's repo and the one from github releases page shows this issue

Also I tested this on sway and it seems to work fine. So it looks like this is specific to kwin_wayland. I'll report it to them
Anyways thanks for this amazing software :)

**Comment by ilya-fedin** [comment] 2021-06-11 06:03
i have an idea, try to run tdesktop with `DBUS_SESSION_BUS_ADDRESS=fdvfvsdfvsdvfsd` and check whether it will lag or not, that will point it to a non-existent dbus socket and prevent any dbus interaction.

**Comment by LastLightSith** [comment] 2021-06-11 07:21
> i have an idea, try to run tdesktop with `DBUS_SESSION_BUS_ADDRESS=fdvfvsdfvsdvfsd` and check whether it will lag or not, that will point it to a non-existent dbus socket and prevent any dbus interaction.

Wow. Its smooth now. But why any dbus interaction slows it down ?

**Comment by ilya-fedin** [comment] 2021-06-11 07:24
There are a method called LastUserInputTime. It uses X API on X11, D-Bus API on GNOME/Plasma Wayland and is unimplemented on other environments. It's called a lot of times per second when scrolling

**Comment by ilya-fedin** [comment] 2021-06-11 07:25
> But why any dbus interaction slows it down ?

I don't know the reason why it's slow compairing to X API though, it's a question for dbus library creators, dbus server creators and dbus protocol designers.

**Comment by LastLightSith** [comment] 2021-06-11 13:48
> It's called a lot of times per second when scrolling.

This looks bad idea. dbus is not that fast

**Comment by LastLightSith** [comment] 2021-06-11 13:54
Also whats the point of calling GetSessionIdleTime from dbus if we know that last input was in telegram itself ?

**Comment by ilya-fedin** [comment] 2021-06-11 17:38
It returns last input time in all the system
