### ISSUE TITLE
Telegram Desktop (Windows Store version) doesn't start at boot

### ISSUE THREAD

**Issue by jimbolimbo3** [telegramdesktop/tdesktop#3234] opened 2017-04-08 08:22 UTC
### Steps to reproduce
1. Install it
2. It doesn't start at boot 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
V. 1.0.29 (Windows Store Version)
**Used theme**:
Dark Blue (https://t.me/themes/104)
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by octolith** [comment] 2017-06-08 14:59
Here's an explanation from Microsoft on how it should be done.
[https://blogs.msdn.microsoft.com/appconsult/2017/02/23/supporting-launch-at-startup-in-a-desktop-app-converted-with-the-desktop-bridge/](url)

**Comment by SewerNode** [comment] 2017-09-09 10:58
Same from me:

## Steps to reproduce

1. Install it from Windows Store
2. It doesn't start at boot and no settings for auto start.

## Expected behaviour

Settings for turn autostart on/off.

## Actual behaviour

It doesn't start at boot and no settings for auto start.

## Configuration

### Operating system:
Windows 10 (1703)
### Version of Telegram Desktop:
v. 1.1.22 (Windows Store)
### Used theme:
Default and Night Mode.

**Comment by ElvisPresly** [comment] 2017-10-01 17:40
+

**Comment by niks255** [comment] 2017-10-03 13:07
I made the neccesary changes to appx manifest, but couldn't set a build environment to test it. I guess build instruction is either wrong or incomplete. If there's anybody who can help, just contacts me in Telegram @niks255

**Comment by auchri** [comment] 2017-10-03 13:08
@niks255 Where to you need help?

**Comment by niks255** [comment] 2017-10-03 13:10
@auchri You can either help me set up my VS 2017 to build Telegram or build it yourself with my changes.

**Comment by auchri** [comment] 2017-10-03 13:11
> You can either help me set up my VS 2017 to build Telegram

Why do you thing the instructions are wrong?

**Comment by niks255** [comment] 2017-10-03 13:12
@auchri Could you contact me in telegram please?

**Comment by auchri** [comment] 2017-10-03 13:15
@niks255 No why? Others can benefit from our conversation here too.

**Comment by niks255** [comment] 2017-10-03 13:19
I see. Well, I couldn't build LZMA SDK. Turned out, I needed Windows 8.1 SDK for that. So I installed it, but it failed to build because it couldn't find standart C++ libraries. I guess there's something wrong with build configuration?

**Comment by niks255** [comment] 2017-10-03 13:28
@auchri I can give you remote access to my PC so you can help me.

**Comment by ElvisPresly** [comment] 2017-11-01 07:39
1. Open File Explorer
2. In the file address bar type shell:AppsFolder
3. This will show all apps installed on your PC. Right click one of them and select "create Shortcut".
4. It will create a shortcut on the the desktop.
5. Finally copy the shortcut to the startup folder.

startup folder:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by octolith** [comment] 2017-11-01 07:59
@ElvisPresley that is a workaround, not really a fix for this issue. Thanks anyways :)

**Comment by JayBeeDe** [comment] 2017-11-01 11:25
I suggest the following registry changes:
1. Open the registry editor and go to 
**HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run**
2. Create a new REG_SZ Value, set the Name to Telegram (or whatever you like) and set its value to **"C:\Windows\explorer.exe" "shell:appsFolder\TelegramMessengerLLP.TelegramDesktop_t4vj0pshhgkwm!Telegram.TelegramDesktop.Store"**

This is usually what is done by a software that has the option start at boot. Since it **doesn't start minimized** this change will remain a **workaround**.

So we need an argument that will allow us to start it minimized. It seems to be possible since the Windows 10 Fall Creators Update.  Maybe this link could be usefull: [https://blogs.windows.com/buildingapps/2017/07/05/command-line-activation-universal-windows-apps/](https://blogs.windows.com/buildingapps/2017/07/05/command-line-activation-universal-windows-apps/): it seems to be possible to define an alias and some arguments

**Comment by Sjkomy** [comment] 2018-02-04 12:03
Windows apps sucks ass, that is simple.

**Comment by StrikerMan780** [comment] 2018-03-23 00:52
I'd like a true fix for this, not a workaround.

**Comment by niks255** [comment] 2018-03-23 13:40
Telegram is a Win32 app, not UWP app. So it could use autostart since the release of desktop bridge. That is since anniversary update.

**Comment by john-preston** [comment] 2018-03-23 13:44
@niks255 Non-windows store version uses a shortcut to launch itself on boot. If there is an easy way to create such a shortcut for a window store win32 app please let me know, I'll quickly add it as well.

**Comment by john-preston** [comment] 2018-03-23 13:44
@niks255 But I'm not sure that even Win32 windows stora app has rights to write to the required user data folder. So I'm afraid it requires some other approach.

**Comment by niks255** [comment] 2018-03-23 13:52
@john-preston You need to add some code to appx manifest. The tricky part is that you cannot pass any arguments to the executable file. So that means the app will not start minimized.
I suggest we write a small executable, which launches the main one with the background parameters and include it in the package. That is what f.lux did for their store package.
Here's how to do it:
https://blogs.msdn.microsoft.com/appconsult/2017/02/23/supporting-launch-at-startup-in-a-desktop-app-converted-with-the-desktop-bridge/

**Comment by john-preston** [comment] 2018-03-23 13:55
@niks255 Thanks for the info.

**Comment by JRuedas** [comment] 2018-03-24 11:01
I'd really appreciate that feature, it's really annoying. I just discovered this repository so I'll try to learn how this feature must work in order to fix this issue asap.

**Comment by niks255** [comment] 2018-03-24 11:39
I can do this, just need to set up a build environment.
If you already have a build environment, just contact me.

**Comment by EpicLPer** [comment] 2018-04-30 12:16
Was this fixed already? I'd really love to use more Windows Store apps from now on since developers port the most important apps I need over already and Auto-Updates are nice to have, but since almost none of them have Autostart it's annoying :(

**Comment by cad0p** [comment] 2018-07-05 13:00
This issue is still not fixed!

**Comment by mifozski** [comment] 2018-07-19 21:48
I have Slack installed from the Store and it has the settings to launch on startup and it works. So it's definitely possible.

**Comment by pitlochry** [comment] 2018-08-12 11:00
There are still no settings for turning autostart on/off in telegram windows version. The workaround is no real workaround, since the app doesn't start minimized.
Hope it will be fixed soon. Thanks God autostart minimized on Linux works.

**Comment by john-preston** [comment] 2018-08-12 13:37
@pitlochry It works in Windows version from site.

**Comment by revanmj** [comment] 2018-08-12 13:55
As title of this issue says, we are talking about Windows Store version.

**Comment by lmillucci** [comment] 2019-01-06 11:45
This issue is still not fixed :(

**Comment by cryptochrome** [comment] 2019-01-18 19:01
This issue has been opened over 1.5 years ago. How is it possible that something as easy and essential as this is still not implemented?

**Comment by alex94cp** [comment] 2019-03-12 08:37
Is there someone working on this? If not, what can we do to help?

**Comment by Red-Eyed** [comment] 2019-04-04 04:33
> 1. Open File Explorer
> 2. In the file address bar type shell:AppsFolder
> 3. This will show all apps installed on your PC. Right click one of them and select "create Shortcut".
> 4. It will create a shortcut on the the desktop.
> 5. Finally copy the shortcut to the startup folder.
> 
> startup folder:
> C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup

It will only help till first update.
Because path to programm is different each update.

**Comment by Kissaki** [comment] 2019-04-05 18:34
The MS blog article that was linked to twice in this thread no longer exists. ([archived version](https://web.archive.org/web/20190110023900/https://blogs.msdn.microsoft.com/appconsult/2017/02/23/supporting-launch-at-startup-in-a-desktop-app-converted-with-the-desktop-bridge/))

The StartupTask class documentation and specifically [remarks section](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.startuptask#remarks) has more information though that should be helpful for implementation.

Maybe I'll be able to take a look this weekend to get a buildenv going and/or create a PR for this, if nobody else picks this up.

**Comment by hemant17** [comment] 2019-07-25 16:54
fix it please why now you fixing it

**Comment by Aokromes** [comment] 2020-01-26 20:59
this issue is still valid?

**Comment by Mertsch** [comment] 2020-01-27 08:40
Yes it is, there is no auto-start option and if you *hack* around it by starting the app from CMD, it will not start in the background. That option is missing as well.

**Comment by AxeMill** [comment] 2020-01-27 17:07
Yeah, however You may want to try Unigram which doesn't have such problem (not sure if it's native or a workaround) and also has support for secret chats.On Jan 26, 2020 23:59, Aokromes <notifications@github.com> wrote:this issue is still valid?

**Comment by gugglegum** [comment] 2020-02-03 14:44
What a shame, Telegram team. The issue exists almost 3 years without fixing. Delete your Telegram from Windows Store if you don't support it. Save people's time to do not install Telegram twice: once from Windwos Store and then by traditional setup executable.

**Comment by JayBeeDe** [comment] 2020-02-03 14:54
> I suggest the following registry changes:
> 
> 1. Open the registry editor and go to
>    **HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run**
> 2. Create a new REG_SZ Value, set the Name to Telegram (or whatever you like) and set its value to **"C:\Windows\explorer.exe" "shell:appsFolder\TelegramMessengerLLP.TelegramDesktop_t4vj0pshhgkwm!Telegram.TelegramDesktop.Store"**
> 
> This is usually what is done by a software that has the option start at boot. Since it **doesn't start minimized** this change will remain a **workaround**.
> 
> So we need an argument that will allow us to start it minimized. It seems to be possible since the Windows 10 Fall Creators Update. Maybe this link could be usefull: https://blogs.windows.com/buildingapps/2017/07/05/command-line-activation-universal-windows-apps/: it seems to be possible to define an alias and some arguments

Or at least : implement my workaround :
- when "open at windows startup" option is checked : add the registry key,
- when "open at windows startup" option is unchecked : remove the registry key,
- when an update occurs : and if "open at windows startup" option was checked : update the appid if needed (TelegramMessengerLLP.TelegramDesktop_**t4vj0pshhgkwm**!Telegram.TelegramDesktop.Store)

**Comment by gugglegum** [comment] 2020-02-03 15:24
@JayBeeDe I don't want to play with registry changes. I just removed Windows Store version and installed classic version. That's it!

**Comment by Aokromes** [comment] 2020-02-03 15:27
give a look to https://www.howtogeek.com/364263/how-to-open-windows-store-apps-on-startup-in-windows-10/

**Comment by gugglegum** [comment] 2020-02-03 16:45
@Aokromes thanks for advice, possible this will help. Unfortunately I already switched to classic version of Telegram Desktop (not from Windows Store).

**Comment by AxeMill** [comment] 2020-02-03 18:22
I’d been using it for a while until recently. I switched to Unigram now.

Отправлено из приложения "Почта" для Windows 10

От: Paul Melekhov
Отправлено: 3 февраля 2020 г. в 19:45
Кому: telegramdesktop/tdesktop
Копия: Alex Mill; Manual
Тема: Re: [telegramdesktop/tdesktop] Telegram Desktop (Windows Storeversion) doesn't start at boot (#3234)

@Aokromes thanks for advice, possible this will help. Unfortunately I already switched to classic version of Telegram Desktop (not from Windows Store).

**Comment by JRuedas** [comment] 2020-03-03 18:58
How does Unigram handle this issue? Can we take a look at the code that they have developed?. I'm not sure if this is a configuration issue or not

**Comment by AxeMill** [comment] 2020-03-04 08:36
I’m not sure about the code, but it has an option like this 

От: Jonatan Ruedas Mora
Отправлено: 3 марта 2020 г. в 21:58
Кому: telegramdesktop/tdesktop
Копия: Alex Mill; Manual
Тема: Re: [telegramdesktop/tdesktop] Telegram Desktop (Windows Storeversion) doesn't start at boot (#3234)

How does Unigram handle this issue? Can we take a look at the code that they have developed?. I'm not sure if this is a configuration issue or not

**Comment by Novaal** [comment] 2020-03-12 13:53
> 
> 
> How does Unigram handle this issue? Can we take a look at the code that they have developed?. I'm not sure if this is a configuration issue or not

You can see the source code [here](https://github.com/UnigramDev/Unigram/blob/d6d5769e0d9573e85850572bcf7d2e9279c053ba/Unigram/Unigram/Controls/StartupSwitch.xaml.cs).

As far as i understand, the following API is used: [link](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.StartupTask)

**Comment by aflyhorse** [comment] 2020-06-29 02:47
Come on, 3 years have passed and the store version still needs to be opened manually in each boot.

**Comment by Wikibear** [comment] 2020-07-11 14:36
I don't understand why there's no solution in this time. Linux doesn't have this problem. There is an option that telegram starts at windows boot... Please fix this, that we can do it via windows, too... Thanks.

**Comment by EpicLPer** [comment] 2020-10-23 12:33
Anti-Stalebot-Comment... Hate this thing.

**Comment by Wikibear** [comment] 2020-10-23 12:38
Yes, I can confirm...

**Comment by LGFN** [comment] 2020-10-23 13:38
Issue is still persistent on my side.

**Comment by baget** [comment] 2020-10-24 11:32
also in my side

**Comment by ilya-fedin** [comment] 2020-10-24 12:51
> I don't understand why there's no solution in this time.

Because it requires UWP API usage I guess

**Comment by baget** [comment] 2020-10-24 13:22
> > I don't understand why there's no solution in this time.
> 
> Because it requires UWP API usage I guess

no, I think you just need to update the appmanifest, need to add `<desktop:StartupTask>`

**Comment by ilya-fedin** [comment] 2020-10-24 13:25
> no, I think you just need to update the appmanifest, need to add `<desktop:StartupTask>`

App manifest editing will add autostart without possibility to disable it from app

**Comment by baget** [comment] 2020-10-24 14:32
> > no, I think you just need to update the appmanifest, need to add `<desktop:StartupTask>`
> 
> App manifest editing will add autostart without possibility to disable it from app

not sure that it is true, you have StartupTask object that you can able, but anyway user can disable and enable it from task manager (Startup tab)

**Comment by ilya-fedin** [comment] 2020-10-24 14:38
> not sure that it is true, you have StartupTask object that you can able

Don't underastand that part of your message, documentation in the first comment of this issue clearly states that interacting with UWP API is needed in order to install an app to autostart from its code

> but anyway user can disable and enable it from task manager (Startup tab)

Core developers don't count that as an acceptable solution, that's why this is not implemented.

**Comment by olegolegoleg** [comment] 2020-11-09 18:32
Brand new Windows 10 installation and the problem still appears. The latest version of Telegram 2.4.2

**Comment by aflyhorse** [comment] 2020-11-10 04:39
https://blogs.windows.com/windowsdeveloper/2017/08/01/configure-app-start-log/
I simple do not know why the developers don't want a StartupTask with "enabled=false" as a resolution.

**Comment by escape0707** [comment] 2020-11-10 07:40
For everyone who tries to come up with a solution or workaround, thank you for your contribution.
But I also what to mention that the "Start Minimized" function is also an essential part of auto-start. At least I can't do that when using the Store version with manually adding a shortcut in `shell:startup` folder as @Aokromes suggested [here](https://github.com/telegramdesktop/tdesktop/issues/3234#issuecomment-581468369)

**Comment by EpicLPer** [comment] 2021-05-09 10:41
Nope

**Comment by aflyhorse** [comment] 2021-05-10 03:31
> > but anyway user can disable and enable it from task manager (Startup tab)
> Core developers don't count that as an acceptable solution, that's why this is not implemented.

I cannot understand why it is not acceptable. Window Store Apps *should* be managed by Startup tab, since this is the standard way to manage auto-start apps in phones and tablets. Windows Store is just another Google Play.

**Comment by gilbertosilvaoliv** [comment] 2021-09-05 13:28
Hello everyone,

I had created a shortcut in the "shell:startup" folder but when the Telegram application is updated the link is broken and the shortcut no longer works.

I went to investigate what happened and found that **the folder path changes every time the app is updated** because it contains the version number in the folder name.

```
"C:\Program Files\WindowsApps\TelegramMessengerLLP.TelegramDesktop_3.0.1.0_x64__t4vj0pshhgkwm\Telegram.exe"

"C:\Program Files\WindowsApps\TelegramMessengerLLP.TelegramDesktop_2.9.2.0_x64__t4vj0pshhgkwm\Telegram.exe"
```

**Is there any way around this**?

**Comment by john-preston** [comment] 2021-09-05 14:33
@gilbertosilvaoliv At some point I've started to support that the right way, but didn't finish the job yet :( It required access to the modern WinRT APIs that I could get access to at the time, but now I have full C++/WinRT wrappers working and maybe I can get back to it. When I find time :(

**Comment by ilya-fedin** [comment] 2021-09-13 15:30
> it's been 3 years. is it really that hard to fix?

Yes, UWP APIs should be used for that. And there's a problem with using UWP APIs when you produce a static binary (you either create a dll with UWP code or the binary won't work on older versions of Windows). That's a blocker for using UWP APIs in tdesktop.

**Comment by 1111Eugene** [comment] 2021-10-17 17:51
sad lol

**Comment by LoGaIta99** [comment] 2021-11-01 10:35
> 
> 
> > it's been 3 years. is it really that hard to fix?
> 
> Yes, UWP APIs should be used for that. And there's a problem with using UWP APIs when you produce a static binary (you either create a dll with UWP code or the binary won't work on older versions of Windows). That's a blocker for using UWP APIs in tdesktop.

So will we have to wait until 2023 or do you intend to drop support for Windows 7 and 8.1 before then?

**Comment by ilya-fedin** [comment] 2021-11-01 18:33
I don't know, it's a question for @john-preston

**Comment by john-preston** [comment] 2021-11-04 06:50
@LoGaIta99 and everyone.

It looks like I managed to make it work with C++/WinRT.

**Closed** 2021-11-04 08:36 UTC
Labels: windows
