### ISSUE TITLE
[Feature Request] Change the folder order

### ISSUE THREAD

**Issue by farazsahebdel** [telegramdesktop/tdesktop#24088] opened 2022-02-18 06:42 UTC
hi
Please allow all chats to be moved to other folders, for example, the folder that is created will come to the first folder.
thank you

**Comment by farazsahebdel** [comment] 2022-02-25 21:24
Yes, but you can not change above all chats
This means that the desired folder can not be defaulted when the program is opened

**Comment by RememberTheAir** [comment] 2022-02-28 08:57
If this issue boils down to replacing the default folder, then it's a duplicate of #7533

**Comment by 23rd** [comment] 2022-06-16 22:08
This was implemented in the 3.7.6 version as the premium feature.

**Closed by 23rd** 2022-06-16 22:08 UTC
Labels: enhancement, waiting for answer
