### ISSUE TITLE
Doesn't delete any symbols when pressing CTRL+BACKSPACE after a wrong password attempt 

### ISSUE THREAD

**Issue by Satoshics** [telegramdesktop/tdesktop#28143] opened 2024-07-07 22:52 UTC
### Steps to reproduce

Set up a local passcode in settings, when it will ask for a password input a wrong one

### Expected behaviour

deleting all the symbols, that were previously added 

### Actual behaviour

when pressing CTRL+BACKSPACE the cursor moves to the beginning of the string without removing any symbols

### Operating system

Windsows

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment] 2024-07-09 14:46
That's strange, when I submit a wrong passcode it selects all the input and Ctrl+Del clears the field:
1. Submit wrong passcode:
![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/49ac1a89-8bc6-48eb-8e81-9d55854f3de1)
2. Pressed Ctrl+Delete:
![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/0f754daa-39ce-46db-b8e4-4ce1fa8e3951)
So, I guess, can't reproduce.

**Comment by john-preston** [comment] 2024-07-12 08:22
@Satoshics Yes, now I see. Fixed in code, will be in the next version.

**Closed** 2024-07-12 08:33 UTC
Labels: bug
