### ISSUE TITLE
Padding is messed up when toggling `Use system window frame`

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#24214] opened 2022-03-18 20:17 UTC
### Steps to reproduce

1. Menu
2. Settings
3. Advanced
4. Toggle `Use system window frame`

### Expected behaviour

No visual glitches

### Actual behaviour

If the box transitions from checked to unchecked, Telegram has some weird padding inside of it.

If the box transitions from checked to unchecked, the UI loses some of its padding (e.g.: elements are have zero distance to window borders, and some are partially cropped).

This gets fixed whenever the window loses and regains focus. My guess is that it's not resizing its content after toggling the borders, but this is just guessing.

### Operating system

ArchLinux

### Version of Telegram Desktop

3.6 (both Flatpak and Arch-native)

### Installation source

Flatpak

### Logs

```shell
Note: using wayland (swaywm).
```

**Comment by WhyNotHugo** [comment] 2022-03-18 20:57
Oh, this also happens when hiding the emoji sidebar.

Also, if the window is too narrow with the emoji sidebar open, hiding the bar works, but then clicking the button again does nothing -- my guess is that in this case it's also being drawn out-of-bounds.

**Comment by ilya-fedin** [comment] 2022-03-19 01:40
What are you talking about?

https://user-images.githubusercontent.com/17829319/159101834-e7d57615-77ac-4800-aeb0-207c6ff07433.mp4

**Comment by WhyNotHugo** [comment] 2022-03-22 21:21
Glitch with the window frame (not when focus is lost and regains, the glitch inverts):

https://user-images.githubusercontent.com/730811/159574795-6e9a8300-6103-4f21-aa81-0f6d6651433b.mp4

Same with the emoji bar:

https://user-images.githubusercontent.com/730811/159574809-92551871-f1c1-4bbe-818c-9f915dcc2182.mp4

**Comment by ilya-fedin** [comment] 2022-03-22 21:40
So I tried Weston and KDE Wayland. Weston doesn't have support for system window frame and KDE Wayland doesn't display system window frame without closing and re-opening the window. So this is non-reproducible.

The second case is also non-reproducible on both Weston and KDE Wayland, both of them make the window bigger/smaller on closing opening the emoji bar.

I guess it's a bug in your compositor.

**Comment by WhyNotHugo** [comment] 2022-03-22 22:51
I've been asking on IRC, and a summary is:

>https://wayland.app/protocols/xdg-shell#xdg_toplevel:enum:state:entry:tiled_left -- sway sets those four on tiled windows

So the client can know it's being tiled and cannot be resized.

> Wayland doesn't display system window frame without closing and re-opening the window. So this is non-reproducible.

Interesting behaviour, a bit quirky in the closing and re-opening, but not buggy.

> The second case is also non-reproducible on both Weston and KDE Wayland, both of them make the window bigger/smaller on closing opening the emoji bar.

Right, it seems those compositors don't tile windows by default, so they allow freely resizing. Tiled windows are usually non-resizeable. I wonder how this scenario behaves on macOS or Windows tiling compositors.

> I guess it's a bug in your compositor.

Well, I can't find it breaking any rules on the spec side; this seems to be an edge case. I guess clients can just infer that they're non-resizeable because they are being tiled...? Can you imagine this breaking in any scenario?

**Comment by ilya-fedin** [comment] 2022-03-22 22:59
> So the client can know it's being tiled and cannot be resized.

If it talks directly to libwayland I guess, but it's not tdesktop case

> I wonder how this scenario behaves on macOS or Windows tiling compositors.

But Windows doesn't have third-party compositors :thinking: 
I don't know about macOS though, but I guess it doesn't have, too 

> I guess clients can just infer that they're non-resizeable because they are being tiled...? Can you imagine this breaking in any scenario?

If compositor would be able to prohibit resizing, this would be just yet another expectations breakage of cross-platform applications and toolkits thus making Wayland adoption even less pleasant by applications & toolkits developed not primarily for Linux.

**Comment by WhyNotHugo** [comment] 2022-03-22 23:06
> If it talks directly to libwayland I guess, but it's not tdesktop case

I wonder if Qt shouldn't handle this itself then.

> I don't know about macOS though, but I guess it doesn't have, too

https://github.com/ianyh/Amethyst#amethyst
https://github.com/koekeishiya/yabai#about
https://rectangleapp.com

Not sure if these count -- they should handle sizing _somehow_ when changing borders, right?

I believe Windows 11 supports tiling natively now too.

> If compositor would be able to prohibit resizing, this would be just yet another expectations breakage of cross-platform applications and toolkits thus making Wayland adoption even less pleasant by applications & toolkits developed not primarily for Linux.

Some X11 window managers also don't allow clients to resize themselves (and are not new at all). sway is much like i3 and many others WM in that aspect.

**Comment by ilya-fedin** [comment] 2022-03-22 23:12
> Some X11 window managers also don't allow clients to resize themselves (and are not new at all). sway is much like i3 and many others WM in that aspect.

Well, X11 tiling WMs always were pain in the ass. These window managers even frequently don't let tdesktop's media viewer to work fullscreen thus breaking it. i3 also seems to break input methods in tdesktop after opening context menus according to #1041. So I don't think we can say tdesktop works as intended on X11 tiling WMs and I don't think it will on Wayland as well until those WMs start to respect client's expectations to respect client's hints like fullscreen, minimal window size (tdesktop updates minimal window size when opening emoji bar) and etc.

**Comment by ilya-fedin** [comment] 2022-03-22 23:18
> I wonder if Qt shouldn't handle this itself then.

All it does with these hints is sets them to a variable in a private class that is not used anywhere else
https://github.com/qt/qtwayland/blob/v6.2.3/src/client/qwaylandwindow.cpp#L1266-L1269
I don't know how should it handle though, there's no concept like 'system doesn't allow you to resize the window' in Qt.

**Comment by WhyNotHugo** [comment] 2022-03-22 23:23
> I don't think it will on Wayland as well until those WMs start to respect client's expectations to respect client's hints like fullscreen, minimal window size (tdesktop updates minimal window size when opening emoji bar) and etc.

sway respect fullscreen hints, and floating hints. A tiled window should not can't itself, much like a fullscreen window can't.

> there's no concept like 'system doesn't allow you to resize the window' in Qt.

So I guess applications cannot help have these sort of glitches when tiled...? It seems that something as widely used as Qt could handle these cases well.

**Comment by ilya-fedin** [comment] 2022-03-22 23:31
> So I guess applications cannot help have these sort of glitches when tiled...? It seems that something as widely used as Qt could handle these cases well.

Well, all cases when Wayland is differ from other platforms, are handled very badly by Qt. Qt [doesn't support xdg_positioner](https://bugreports.qt.io/browse/QTBUG-99618) making menus appear far away from here they should be, Qt [uses rendering loop approach used by other platforms, but unsuitable for Wayland](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/99#note_1293115) causing deadlocks. The thing is Qt can't change its design just for the only different platform.

> sway respect fullscreen hints, and floating hints.

At least that :D

> A tiled window should not can't itself, much like a fullscreen window can't.

I can't parse that :thinking:

**Comment by WhyNotHugo** [comment] 2022-03-22 23:42
*  A tiled window can't resize itself, much like a fullscreen window can't resize itself.

**Comment by ilya-fedin** [comment] 2022-03-22 23:48
Can we say sway that we don't support tiling so it won't tile?

**Comment by WhyNotHugo** [comment] 2022-03-22 23:50
> Qt [doesn't support xdg_positioner](https://bugreports.qt.io/browse/QTBUG-99618) making menus appear far away from here they should be, Qt

This also happens with regular menus, there's a much older bug: https://bugreports.qt.io/browse/QTBUG-85297

> Qt's APIs are also unsuitable for xdg-activation as you can't set a token to activateWindow.

I'm getting the impression that Qt's API is limited to the lowest common denominator. Wayland tries to solve a lot of issues in previous implementations, but some of these issues are due to their APIs not being transactional enough. Allowing all sorts of race conditions.

> Can we say sway that we don't support tiling so it won't tile?

I don't think there is such a thing. Much like there isn't an API to say you don't support fullscreen.

**Comment by ilya-fedin** [comment] 2022-03-22 23:57
> This also happens with regular menus

But regular menus is exactly what I talk about :D

> there's a much older bug

Yeah, it's linked ti the xdg-positioner bug

> I'm getting the impression that Qt's API is limited to the lowest common denominator.

This is true for a lot of cross-platofrm libraries. The problem with Wayland though it's a very different API with a very small userbase (it's 10% from 2% currently, but even if it would become just 2%, it will still be very small).

> I don't think there is such a thing.

This is unfixable then, unrotunately

**Closed** 2022-03-23 00:10 UTC
Labels: bug, 3rd party issue

**Comment by WhyNotHugo** [comment] 2022-03-23 00:12
> This is unfixable then, unfortunately

Why does telegram resize itself in the first place? Can't it just avoid resizing in the first place?

**Comment by ilya-fedin** [comment] 2022-03-23 00:15
Why should it avoid resizing in the first place? All other platforms handle this just fine and I don't see a reason why sway can't (e.g. send new size with the configure event to Qt to resize it back, as long as it's not less than the minimum window size tdesktop sets, it should be fine).

**Comment by WhyNotHugo** [comment] 2022-03-23 00:24
> I don't see a reason why sway can't

There's no space to resize to the right. There's no more monitor. It could move+resize, but that's really odd for applications to do. There's no "empty space" either when downsizing; it has to be filled when downsizing.

Telegram seems to be in the weird here: If I open a sidebar in Firefox or any other desktop app, the sizebar is shown in the existing screen region of for that client -- it does not resize at annex the sidebar. `sway` doesn't handle clients resizing themselves because clients should not arbitrarily resize themselves or others (note: when tiling, you can't resize one client without affecting others).

> why should cross-platform behavior be changed just because of sway.

It's a shame that other compositors don't as widely support tiling, TBH, maybe this wouldn't be an "only happens in sway" error. I don't see sway doing anything wrong here, there's just no way to signal to the client that is may [not] resize itself.

Maybe this should be kept in mind in future protocol refinements.

**Comment by ilya-fedin** [comment] 2022-03-23 00:31
> There's no space to resize to the right.

Windows can be resized out-of-screen, that's what traditional WMs do if a window is near to the edge.

> Telegram seems to be in the weird here

This looks pretty nice on traditional WMs: the side bar opens without changing the center column, just like a third columns adds to the first two

> I don't see sway doing anything wrong here, there's just no way to signal to the client that is may [not] resize itself.

If it can't tell clients they can't resize, then it's wrong if it doesn't handle resize. I don't see that tiled_* hints prohibit resizing, btw.

**Comment by ilya-fedin** [comment] 2022-03-23 00:32
> There's no space to resize to the right.

Windows can be resized out-of-screen, that's what traditional WMs do if a window is near to the edge.

> Telegram seems to be in the weird here

This looks pretty nice on traditional WMs: the side bar opens without changing the center column, just like a third columns adds to the first two

> I don't see sway doing anything wrong here, there's just no way to signal to the client that is may [not] resize itself.

If it can't tell clients they can't resize, then it's wrong if it doesn't handle resize. I don't see that tiled_* hints prohibit resizing, btw.
