### ISSUE TITLE
Option to disable mobile sound/vibration notifications when using Desktop

### ISSUE THREAD

**Issue by virtualdj** [telegramdesktop/tdesktop#277] opened 2014-11-23 10:19 UTC
Hi, when using Telegram Desktop is it possible to silence out the notifications on the phone?
There are no notifications on the phone, actually they are dismissed successfully, but for every received message I hear the sound/vibration (sometimes it is cut out in the half, as it has been "cancelled").

**Comment by emmaguy** [comment] 2015-01-03 11:06
+1

**Comment by robbiev** [comment] 2015-01-03 11:06
+1

**Comment by teofilcojocariu** [comment] 2015-01-05 17:28
+1

**Comment by alexandrucoman** [comment] 2015-01-05 17:29
+1

**Comment by maltalef** [comment] 2015-01-06 02:27
+1

**Comment by fr0zenone** [comment] 2015-01-15 08:36
+1

**Comment by dbtek** [comment] 2015-01-27 08:11
+1

**Comment by strgt** [comment] 2015-01-27 08:14
+1

**Comment by alkaline9500** [comment] 2015-01-27 23:05
+1

**Comment by IllegalCactus** [comment] 2015-01-29 10:23
+1

**Comment by charlieegan3** [comment] 2015-01-29 10:24
+1

**Comment by TheGoobian** [comment] 2015-02-09 23:37
+1

**Comment by fyahfox** [comment] 2015-02-25 08:57
Right now there is a dirty workaround by muting the conversation on the phone for 1 hour, but we still need a good solution like Kocayine proposed.

Any feedback if the devs see this as a high priority change? I think many users do...

**Comment by joshery420** [comment] 2015-03-02 23:52
+1, this is definitely needed.

**Comment by Katzen-Gott** [comment] 2015-03-03 09:10
+1 but only if it's optional (Sometimes I don't turn off my office PC and just lock screen, and telegram stays open)
By the way, curently, if tdesktop is in focus, my phone recieves notification and dismisses it almost instantly. So instead of 'bzzzzzzzzz' it only makes 'bz' (idk how to explain it more correctly)

**Comment by joshery420** [comment] 2015-03-03 23:42
@Katzen-Gott My device (Nexus 5, Android 5.0.1) usually buzzes fully still, and is probably only 7/10 for dismissing notifications when the desktop application has focus or is focused (on WiFi or a solid mobile data connection, even), but even with short buzzes it can get annoying if you get a flurry of messages.
That said, I totally agree that it should be an optional feature. :+1:

**Comment by mattogodoy** [comment] 2015-03-10 15:10
+1
In "Line" it works in a way that if you are active in your Desktop computer, notifications get disabled in your phone. If you're away from your computer, 5 minutes later notifications start to come into the phone.

**Comment by N0x1k** [comment] 2015-03-17 13:52
+1 would be really usefull.

**Comment by davidmartingonzalez** [comment] 2015-03-17 16:44
+1 here too :)

**Comment by tjaart** [comment] 2015-03-19 12:00
+1 here too!

**Comment by russelgal** [comment] 2015-03-20 17:10
+999

**Comment by Arttse** [comment] 2015-03-23 10:44
+1

**Comment by motiazu** [comment] 2015-04-01 13:31
+over9000

**Comment by kireledan** [comment] 2015-04-01 14:08
wouldn't this involve making a modification to the mobile app as well?

**Comment by joshery420** [comment] 2015-04-01 15:57
@kireledan You're totally right.
Let's bring @DrKLO and @telegramdesktop attention to this!

Any chance this kind of presence detection could be added in?
I'd love to automatically silence the vibration+sound on mobile when I've been actively chatting on desktop and vice-versa for desktop sounds when chatting on mobile.
In my opinion this is one of the best features desktop+mobile chat programs can have! :smile:

**Comment by Katzen-Gott** [comment] 2015-04-02 13:48
@kireledan @joshery420 It looks more like a server thing. Or even overall. At least on iOS, there is the push thing. And I'm not sure, that app can do anything with phone behaviour on pushes. And there is similar thing for androids (google push?), which shoud be considered as well...

**Comment by joshery420** [comment] 2015-04-02 16:24
@Katzen-Gott Oh there's definitely a server component to getting this working well. I wasn't trying to imply it was all inside the apps. :smile: I'm sure the mobile apps are using push notifications, but the apps still have to be setup to handle those notifications and they can adjust how they handle them based on other conditions (there's already a wide variety of notification settings on mobile, even)

I guess the ideal for me would be that if you're considered "present" on the desktop, mobile notifications would still show (until you viewed the message somewhere, of course) but wouldn't vibrate or make sound.
Likewise, if you were considered "present" on mobile the desktop app would show the popups in the corner (maybe?) but not make any sound.

This allows for easy switching between devices/platforms because the notifications are still visible, but not constantly buzzing the phone in my pocket when I chat on desktop or spam ding sounds through my desktop speakers just because I reply on my phone and don't have the desktop app focused.

**Comment by virtualdj** [comment] 2015-04-03 16:30
@joshery420 I totally agree with you.

**Comment by SH-Andre** [comment] 2015-04-04 09:03
+1

**Comment by N0x1k** [comment] 2015-04-04 10:38
@joshery420 +1

**Comment by JordanSekky** [comment] 2015-04-05 14:33
+1

**Comment by cliv3ong** [comment] 2015-04-09 01:36
+1

**Comment by Paratron** [comment] 2015-04-21 08:49
Any update on this? Its driving my insane. I'm now trying to manually disable the mobile session from my desktop app settings. Maybe that will mute the notifications. Still needs me to re-login on my phone when I go away from the pc. Very annoying.

**Comment by IllegalCactus** [comment] 2015-04-21 12:23
@Paratron I usually turn off notifications within the mobile app when I'm at my computer. Works, but can be a bit frustrating if you're doing it often.

**Comment by Paratron** [comment] 2015-04-21 13:10
Yeah, I did the same now, too. The session cancelling was a bit overkill :)

**Comment by YitzhakStone** [comment] 2015-05-02 15:05
+1

**Comment by Brom2** [comment] 2015-05-03 14:23
+1

**Comment by christianromeni** [comment] 2015-05-04 10:16
This should soon be done right? :-)

Smart Notifications
Tired of buzzing notifications from active group chats? Sick of multiple notifications every time somebody forwards you a dozen messages? Getting notifications on mobile while chatting with the same person from your desktop? Fixed! Starting today, you will be notified only when it is necessary.
https://telegram.org/blog/captions-places

**Comment by charlieegan3** [comment] 2015-05-04 13:06
👍 great news.

**Comment by YitzhakStone** [comment] 2015-05-17 01:41
Not works for me... Android app and desktop are updated.

**Comment by fyahfox** [comment] 2015-05-17 14:18
When you are using the Desktop app and you mark the messages as "read" with the Desktop app, your phone stays quiet.

**Comment by N0x1k** [comment] 2015-05-17 20:11
So it seems that this was sadly not part of the "Smart notifications" update :-/

**Comment by fyahfox** [comment] 2015-05-18 08:20
No idea what you are talking about.

Current version has "smart notifications" (set max. x notifications in y minutes) and the phone stays quiet when you are in a conversation on the desktop app.

**Comment by darknight7** [comment] 2015-05-18 08:25
That's correct but only if the desktop app has focus.
I think the problem is all there: different opinions on what "in a conversation on the desktop" ultimately means.

**Comment by N0x1k** [comment] 2015-05-18 08:36
Oh I didn't even notice that I don't get notifications on the phone when the app is in focus on desktop, because I always do other stuff on the PC, that way the app is never in focus when I'm chatting with someone.

**Comment by Paratron** [comment] 2015-05-18 08:37
That definitely needs a fix. I think you can assume to be in a conversion on the desktop if the mobile is locked and the mouse + keyboard is used on desktop, even if the app is NOT focused.

**Comment by SH-Andre** [comment] 2015-05-18 10:11
The developers should probably take a look at how Slack works:


-          If desktop app is active: first notify in desktop app

-          If message(s) unread after X (like 30) seconds: notify in mobile app

-          On top of that (this would probably be bogus for Telegram): if still unread in mobile app, it sends an email notification

If would be even nicer if it also had some options for customization (for example: how long to wait before notifying in mobile app). And it could also account for whether or not there is any activity on the desktop in general – because if the desktop is completely idle, then the notification could go straight to mobile.

**Comment by YitzhakStone** [comment] 2015-05-25 01:08
That's exactly what is on the last comment that I think should be implemented. And this "X minutes" can be configured by the user. He spoke all.

**Comment by nehemiahjacob** [comment] 2015-06-02 12:29
+1

**Comment by takethisusernameidareyou** [comment] 2015-06-02 15:12
+1 from me too. Also have to keep asking a colleague to stop his phone vibrating while he's using telegram desktop as it just constantly buzzing away in our office while he has his headphones on

**Comment by ArtyomKuznetsov** [comment] 2015-06-02 15:31
+1

**Comment by dienavarrete** [comment] 2015-06-03 20:34
+1 Is really annoying

**Comment by FriTOol** [comment] 2015-06-08 12:11
+1

**Comment by Matteomt** [comment] 2015-06-09 20:17
+1 HATE this

**Comment by sublimino** [comment] 2015-06-24 09:12
+1 furiously irritating

**Comment by friesoft** [comment] 2015-07-05 12:42
+1
very annoying... the single thing where hangouts really does a significantly better job..

**Comment by Siguza** [comment] 2015-07-06 19:08
+1

**Comment by Jamesits** [comment] 2015-07-08 01:39
I think this is possible: when a message comes in, first send notifications to currently active device or the last active device. If in 30secs the message is still unread, send notifications to every device.

**Comment by txl263** [comment] 2015-07-08 02:19
+1

**Comment by formatq** [comment] 2015-07-15 08:23
+1

**Comment by sometoby** [comment] 2015-07-15 21:21
+1
Why has this not been implemented yet? This problem is extremely irritating and makes chatting on Telegram a chore. I usually tell people to message me on other platforms instead when I'm on my desktop.

**Comment by takethisusernameidareyou** [comment] 2015-07-15 21:45
I dont think anyone from telegram is even reading this... i've had a load
of +1 emails but no comment from a telegram developer. Please someone take
a look... a lot of people are asking for this to be fixed.

**Comment by christianromeni** [comment] 2015-07-15 21:49
Im pritty sure @telegramdesktop has read it quite often.. But just has not replyed to it..

**Comment by Siguza** [comment] 2015-07-16 09:34
I just realised this is a duplicate of a declined feature request: #36

**Comment by takethisusernameidareyou** [comment] 2015-07-16 10:24
Ha .. so hundreds of people want it but developers wont do it. Nice.  Back to hangouts and whatsapp then

**Comment by Siguza** [comment] 2015-07-16 12:26
Wait, I might have misunderstood the meaning of that answer. They basically only said it's not a desktop issue... @telegramdesktop Would you mind pointing us to a place where we can file feature requests for telegram in general/the mobile client/server-side stuff?

**Comment by Matteomt** [comment] 2015-07-16 12:44
I'm not involved with development, but I think this problem would be managed more efficiently server-side, by getting aware of what device the user is active on and thus sending push notifications accordingly.
I think it would be very hard to do the same client-side without specific support from server.

An idea (maybe not new): 
1. When a message gets marked as read, this event information starts from the active device, goes to the server and propagates to each connected device of the user (this is evidence).
2. So... The event-message is associated with the source device (server knows) and so is the read-mark (suppose the server lets other devices know -- possible, maybe real, MAKE it real otherwise!).
3. (The trick) Each chat message could be marked, not simply as read or not read, but also with a list of all the devices that have visualized the message.
4. Now the client can determine the last active device.
5. Show android notification, or pop-up or other alarm with 0 delay if this is the last active device, long delay (like 30sec or 3sec with silent notification) otherwise.
An alternative to point 3. is keeping a table with device / last-read-timestamp association, like what Hangouts seems to do (then show on screen only the last active device timestamp as an icon following the last read message).

So you get notifications on the last device you used to read a message, then on others with a delay. Note that this is chat-dipendent, but we can solve it:
1. When the user opens telegram, the server knows it is active and the event is associated with the device.
...etc.
The user may not see this info, as not usefull, but the key point may be notifying each device (of the user) was last active.

Anyway, while the problem is not solved server-side, every developer should try to fix problems like this with some sort of duct tape.

Meanwhile, I simply mute my phone while I'm at the PC. Because is reasonable and because I still prefere Telegram.

**Comment by stefan-schweiger** [comment] 2015-07-24 12:00
+1

**Comment by ncravino** [comment] 2015-07-24 15:41
+1

**Comment by williamtguerra** [comment] 2015-08-12 23:29
+1

**Comment by muadnu** [comment] 2015-08-14 12:30
+1
But here's something (maybe) interesting. I've been using the telegram plugin for pidgin (in linux), and it turns out that I don't get notifications on my phone when using it (regardless of the window having focus or not). It is not really behaving smartly, as (I think) I don't get notifications at all on my phone until I close the application on my desktop, but it's still better. Unfortunately, a couple of days ago the pidgin plugin started crashing as soon as I write a message.

**Comment by auchri** [comment] 2015-08-14 21:41
Notifications are send to all devices, but only the last active device shows the notification. If you read the message, the notification is removed from the other devices too.

**Comment by joshery420** [comment] 2015-08-14 22:44
@auchri If I'm understanding what you're saying correctly it just isn't true.
Even if I'm regularly chatting on the desktop, if the desktop client doesn't have focus all of my devices notify with a vibrate or sound. ONLY if the desktop client is focused do the other devices not notify, at least for me.

**Comment by auchri** [comment] 2015-08-14 22:45
Yes, that's true. But that's server related: https://twitter.com/telegram :)

**Comment by joshery420** [comment] 2015-08-14 22:57
Oh it certainly is, I'm just saying that your claim that "only the last active device shows the notification" isn't entirely true. :wink: 
Thanks for being so active @auchri! Glad to have you around.

**Comment by auchri** [comment] 2015-08-15 00:04
All official clients implemented some improvements month's ago: #dde1a5a

I think this issue can be closed?

**Comment by joshery420** [comment] 2015-08-15 08:07
Huh, interesting. That's what I'd assumed had happened with the "Smart Notification" update, but it didn't seem to be the case in my experience. I'll test tomorrow, but I _think_ my phone still buzzes immediately if the desktop client doesn't have focus, which would imply that the delayed notifications aren't working right.

**Comment by darknight7** [comment] 2015-08-15 10:25
If I focus the desktop client within a couple of seconds the phone won't buzz. In other words if chatting is not my main task (almost never is) I still have to silence notifications to avoid annoying other people around. My personal opinion is that not all clients are equal. The desktop client is more equal than the others :wink: and should "capture" the notifications.
At least with an option, that's my use case.

**Comment by joshery420** [comment] 2015-08-16 07:21
Alright, I tested it tonight over maybe 50 messages between a pair of friends and I, so here's how it seems to be working for me.
If the desktop client is open AND has focus AND the chat receiving messages is open, only then will my other devices stay quiet.
However, if any of those conditions aren't met it seems like I get notifications on my desktop first, giving roughly a 2-4 second window (varying network and system conditions I'm sure) to focus the desktop app before all of my other devices notify like normal.
That means that even if I'm actively chatting in one conversation, if I don't switch to the other conversation(s) with new messages within that 4 second window, _all of my devices still buzz_.
This seems to be pretty similar to what @darknight7 described, so I'm assuming it's working the way it was intended.

I would posit that many people logged into Telegram on a computer aren't going to be there for just a couple of minutes. Many of us are at home or work, actively using the system for hours at a time possibly.
In my opionion, as long as the desktop app is logged in and running, if I've used my mouse/keyboard within the last maybe 5-10 minutes it shouldn't notify other devices.
Alternatively, if the desktop is "active" maybe the mobile devices can notify immediately but without making sounds or vibrating? That is, update the mobile clients and show the notification on the device, but do it silently. Not sure how much notification control is there on mobile platforms for something like that. @DrKLO

Also, tweeted about this thread, so hopefully it gets some attention, since this is my single biggest annoyance with Telegram right now.
https://twitter.com/joshery420/status/632810144082976769
@auchri I know this isn't under your control, but it certainly is related to what the desktop client considers an "active" user, so I feel like it's safe to keep open for now.
@telegramdesktop You might have a bit more control over this though, depending on how the active status is determined.

**Comment by Artanisx** [comment] 2015-08-21 15:05
+1

**Comment by anisart** [comment] 2015-09-03 09:07
+1

**Comment by forest-hermit** [comment] 2015-09-07 16:46
+4 (two persons of my job that find it extremely annoying and two more that refuse to use Telegram because that its f***** annoying)

**Comment by atk91** [comment] 2015-09-18 11:01
+1

**Comment by Arcaena** [comment] 2015-09-18 15:20
+1

**Comment by DfKimera** [comment] 2015-09-23 22:09
+1

**Comment by Katzen-Gott** [comment] 2015-09-24 09:55
Please stop adding "+1". It won't make issue resolved any faster (or sooner), and it only bothers those who want to receive updates on the issue.
If you want to receive updates as well, there is "Watch" button at the top, you don't need to add a comment to start "watching" the issue.

**Comment by christianromeni** [comment] 2015-09-24 10:56
+1

:)

**Comment by EmmanuelPREVOST** [comment] 2015-09-28 09:41
+ :100:

**Comment by JarrettBillingsley** [comment] 2015-10-02 17:50
For me there's not even a delay. As SOON as I receive a message -- often even when I have desktop telegram focused -- my phone plinks too. It's incredibly annoying. I don't want to have to log out of mobile telegram (and then have to log back in...) just to get it to shut up.

**Comment by GPardal** [comment] 2015-10-13 16:45
+1

**Comment by mc-suchecki** [comment] 2015-10-16 07:38
+1 :+1:

**Comment by aldovc** [comment] 2015-10-22 20:16
+1

**Comment by vvoody** [comment] 2015-10-28 06:43
+1

Wechat does well in this situation.

**Comment by Jamesits** [comment] 2015-10-28 06:48
@vvoody On my experience, Wechat does simply notify everywhere or none if
you choose to disable phone notification when PC client is logged in.

**Comment by lawrencegs** [comment] 2015-11-01 05:37
Yes please, this is one of the little details that matters. UX matters.

**Comment by vvoody** [comment] 2015-11-02 06:22
@Jamesits Nope. Wechat use different ways to login same account at same time. Say, if you want to use Wechat on PC, you have to use Wechat on your phone to authorize the PC client. In this mode, if you mainly use on desktop, e.g. chatting in work time :D, by default Wechat will mute mobile app. But for Telegram, both mobile app and desktop app are always online, which means receive notifications on both sides. That is annoying.

**Comment by Jamesits** [comment] 2015-11-03 01:18
@vvoody In my use case, I log in Wechat Mac client every morning (it disconnects automatically at night when my Mac falls asleep and AC power is cut off, which is another annoying story) like any other IM I use (Hangouts, Telegram, QQ, etc.), then if I need to leave my computer, I lock it and take my phone around. So if I disable notification on phone when logged in on computer, I got nothing when I'm away with the phone; if I enable that, my computer rings and my phone vibrates when I'm in front of my computer. What's more, if I read a message on my computer, it remains unread on the phone. So basically to me, the notification model of Wechat is unusable.

**Comment by lawrencegs** [comment] 2015-11-03 02:13
Not sure about wechat, but the model of Google Hangouts is working great for me. It detects which one I'm last active, then only push notification to that device. All other devices will update the read/unread statuses periodically.

**Comment by vvoody** [comment] 2015-11-03 03:07
@Jamesits make sense. But at least, Telegram's way is super annoying, absolutely.

**Comment by vially** [comment] 2015-11-18 14:47
:+1:

**Comment by haraldringvold** [comment] 2015-11-27 15:24
:+1: 

Please fix this! :pray: This is super anoying! :anguished:

**Comment by FireEater64** [comment] 2015-11-29 15:30
+1

**Comment by qdi-staceyw** [comment] 2015-12-01 17:41
+1

**Comment by DaFri-Nochiterov** [comment] 2015-12-01 18:21
:+1:

**Comment by zebrasinpyjamas** [comment] 2015-12-02 20:05
+1

**Comment by Emekturkeli** [comment] 2015-12-02 20:05
+1

**Comment by getprice** [comment] 2015-12-03 09:53
This started annoying me 30 seconds after installing the desktop app for the first time. Can't believe Telegram Dev team isn't working on a fix.
Please fix.

**Comment by andres-fortier** [comment] 2015-12-09 17:35
+1

**Comment by farzad123** [comment] 2015-12-12 14:29
+1

**Comment by headache** [comment] 2015-12-14 14:09
+1

**Comment by howellzd** [comment] 2015-12-16 02:13
+1

**Comment by DiThi** [comment] 2015-12-28 17:35
I got a new phone and I'm super annoyed this is not an option. I have Tdesktop visible at all times but rarely active. However, active or not there's a chance I'm not looking at the screen. So the correct thing is what Slack does, described by @SH-Andre above (notify on last used device, waiting for a while before notifying other devices).

**Comment by forest-hermit** [comment] 2015-12-28 17:37
Totally agree with @DiThi

**Comment by joshery420** [comment] 2015-12-28 17:43
Guys and gals, just a reminder.
@auchri [mentioned this before](https://github.com/telegramdesktop/tdesktop/issues/277#issuecomment-131262069), but as much as we'd like this it isn't just a client issue.

If you want some sort of priority between clients, pretty sure we'll need to get it implemented on the server side, and to get that message through we'll need to get the message through on the [main Telegram Twitter](https://twitter.com/telegram). 

Get to tweeting, everyone! ;)

**Comment by DiThi** [comment] 2015-12-28 17:46
@joshery420 You're right. We have to ask Telegram to implement this in the servers. Is there any other way to ask for this to Telegram other than Twitter?

**Comment by auchri** [comment] 2015-12-28 17:48
@DiThi yes, the "Ask a question" feature in one of the official clients.

**Comment by joshery420** [comment] 2015-12-28 17:49
Oh hey, that might be nicer. Everyone, you know what needs to be done haha.

**Comment by Kutsan** [comment] 2016-01-03 11:57
+1

**Comment by iverdo01** [comment] 2016-01-05 14:00
+1

**Comment by Zero3** [comment] 2016-01-05 23:44
# Dear future +1 commenters

As said before, the developers are well aware of the popularity of this issue. Every time somebody posts a +1 comment, almost a hundred people subscribed to this issue receive a notification. Most of us probably via e-mail like me. Since they add little value to the issue and a lot of annoyance, please refrain from posting them. Thanks!

**Comment by DiThi** [comment] 2016-01-06 00:54
To add to what Zero3 said, click the "subscribe" button instead of commenting.

Also, to reiterate, **this is not telegram desktop's fault, but telegram's (the service itself)**. Every person that says +1 should contact **telegram** instead.

Tdesktop could add a button for simulating being in focus, but it would be a bad, half-assed solution (which can satisfy some subscribers here). The proper solution is what Slack does (described above).

**Comment by marzochi** [comment] 2016-06-07 11:09
+1

**Comment by sohantanna** [comment] 2016-07-21 16:05
Has a solution for this been found?

**Comment by DiThi** [comment] 2016-07-21 16:48
Despite what I said previously, now I think it would be perfectly acceptable if Telegram Desktop fakes it's active status: e.g. while I see the window I have a different window active such as the browser or an editor, and TDesktop says "I'm active!" to the server for e.g. 10 minutes, but acts as usual for receiving notifications etc.

**Comment by SkewPL** [comment] 2016-07-26 15:26
+1

**Comment by FezVrasta** [comment] 2016-09-11 18:22
Just do as Slack does. If you receive a message on desktop and you don't have the Slack pc app open for few minutes, it get notified on the smartphone.

**Comment by cmitz** [comment] 2016-09-11 18:50
That'd be also like WhatsApp and is imho a great way of not over-notifying the user

**Comment by FezVrasta** [comment] 2016-09-11 20:47
Ad far I see, right now you have just few seconds to bring the app on top to avoid the smartphone to vibrate. So seems like there's already a timer set. They should just increase it (maybe make it a customizable parameter)

**Comment by SillySina** [comment] 2016-09-23 20:47
I am happy to see this, and also sad to see this. Being over-notified on all devices when I'm active on a given device is super annoying. I tried muting notifications on my mobile, but it also muted notifications for that person on all other devices, too. Per-device notification control needs to happen. :(

**Comment by YiuTerran** [comment] 2017-03-03 02:14
This issue still exists after 2 years... Oh, No!

**Comment by furkansahin** [comment] 2017-03-10 11:15
Any attempt for this issue on side of Telegram? Because it still bothers me after using Telegram appr. 2 years...

**Comment by quimnuss** [comment] 2017-03-10 11:23
But you'll get a new sticker tomorrow, yay!

**Comment by FezVrasta** [comment] 2017-03-10 11:34
Can't wait for the new sticker 😬

**Comment by MacDragon** [comment] 2017-03-12 13:30
This, so annoying to constantly have mobile devices going PING just because tabbed away from telegram on desktop.

**Comment by kasparsklavins** [comment] 2017-03-13 21:22
+1 For this.

**Comment by Darktemp** [comment] 2017-03-15 20:53
It also annoys me every day :(
normally I mute the specific person who I'm writing with to prevent this. but Sometimes I forget to unmute them and then they get mad at me if I don't see new messages later.
On 4 May 2015 the "smart notifications" were mentioned. But I don't get how it should work or where the settings are to activate it.
And on 18 May 2015 the "set max. x notifications in y minutes" setting was mentioned, which could help a little bit, but I only see that option for groups. But that won't fix the problem completely :(

**Comment by 5ulo** [comment] 2017-03-21 22:28
Yep.. beep beep all the time.. and I miss also option for "notification grouping" like don't notify each message inmediatelly - notify only if last message was received eg. minimal 30s before. etc..

**Comment by fdnk** [comment] 2017-04-23 19:35
Hi, can someone take a look on this feature, please? It's really annoying

**Comment by y1n0** [comment] 2017-04-30 19:58
@Darktemp the smart notification is of no use here. It resets the count when the msg is read.

**Comment by fjaguero** [comment] 2017-06-14 10:20
Hopefully this gets done this year 😄

**Comment by N0x1k** [comment] 2017-06-14 10:47
2017 and nothing happened....

**Comment by metaer** [comment] 2017-06-29 11:07
+1

**Comment by Heliosmaster** [comment] 2017-08-01 09:36
Any news on this issue? It's still occurring and annoying as ever :(

**Comment by sstyle** [comment] 2017-09-14 09:12
OMG..is it really so difficult to add a delay between TDekstop and mobile device?!

**Comment by stek29** [comment] 2017-09-14 22:34
Comments bringing nothing new to discussion will be deleted. Use reactions.

**Comment by thiennq** [comment] 2017-11-23 02:40
+1.
I really need this feature.
The current notification feature makes my mobile battery run out very fast.

**Comment by kirsan31** [comment] 2017-12-18 10:04
@andrii-r This is an api issue, and I am afraid, that we can't do anything :(

**Comment by Erquint** [comment] 2018-06-27 16:32
This feature is essential.
If it's not fixed, I swear, I'm gonna rage over it one day and get rid of the app.

**Comment by ivancuric** [comment] 2019-01-31 19:36
If it's an API problem, who do we bug, or how can we contribute to fixing it?

**Comment by stek29** [comment] 2019-02-14 13:13
@ivancuric contact support

**Comment by kirsan31** [comment] 2019-03-09 10:07
In new beta Telegram X for Android:

> - You will no longer receive accidental notifications, when you are chatting on the other device

Can any one comment it?

**Comment by Sasha-Sorokin** [comment] 2019-03-09 11:41
I'll drop **a guess** here: That means that if you are chatting one of the devices, the notifications on other devices must be deferred for a few seconds and by some reason Telegram X previously wasn't complying to this rule and was not deferring the notifications, instantly triggering the sound / vibration, even if the other device is still active and must be “prioritized” to receive this notification first. But again, that's just a guess.

**Comment by ryderr** [comment] 2019-03-15 01:32
please fix

**Comment by ivancuric** [comment] 2019-03-15 13:00
> @ivancuric contact support or bug telegram on twitter

Did both multiple times. No response.

**Comment by batmont** [comment] 2019-08-08 21:58
also there may be a feature for manual disabling notifications for each group/channel/etc for different platform/clients
For example:
chat 1: notifications disabled on desktop, but enabled in mobile app
channel 1: notifications enabled on desktop, but disabled in mobile app
channel 2: notifications disabled on desktop, but anabled in mobile app

**Comment by megapro17** [comment] 2020-02-22 17:51
SIX FUCKING YEARS AND STILL NOT FIXED??????????? THIS IS INSANE!

**Comment by baxenko** [comment] 2020-03-19 09:09
Why is this still not fixed? Even Viber has this feature. Doesn’t it annoy anyone when you are online, then your smartphone constantly makes sounds.

**Comment by wallejak** [comment] 2020-03-19 09:38
It does drive me mad!

**Comment by firnen0** [comment] 2020-04-23 18:34
Is there any news about when this will be fixed?

**Comment by electrofloat** [comment] 2020-04-23 18:35
> 
> Is there any news about when this will be fixed?

Forget it. It won't be fixed.

**Comment by megapro17** [comment] 2020-04-23 22:49
> Is there any news about when this will be fixed?

We should collaborate and spam this message everywhere: creating hundreds of this issues, pull requests, commentaries, if you'll stay quiet nothing will change

**Comment by ryderr** [comment] 2020-04-23 22:51
what a joke

**Comment by Aokromes** [comment] 2020-04-23 22:54
> > Is there any news about when this will be fixed?
> 
> We should collaborate and spam this message everywhere: creating hundreds of this issues, pull requests, commentaries, if you'll stay quiet nothing will change

if you do that be sure i will report you to github.

**Comment by megapro17** [comment] 2020-04-23 23:11
> > > Is there any news about when this will be fixed?
> > 
> > 
> > We should collaborate and spam this message everywhere: creating hundreds of this issues, pull requests, commentaries, if you'll stay quiet nothing will change
> 
> if you do that be sure i will report you to github.

You maybe report one on my fake accounts, but I'll create another thousand of them 😂

**Comment by john-preston** [comment] 2020-04-24 04:19
@megapro17 Be sure to start with pull requests that fix the issue.

**Comment by escape0707** [comment] 2020-04-24 09:39
> 
> 
> @megapro17 Be sure to start with pull requests that fix the issue.

I'm not with megapro17 but if I understood the problem correctly, shouldn't this be fixed in the server side which is not gonna be open sourced by telegram yet?

**Comment by ZexDC** [comment] 2020-05-04 16:57
This is beyond ANNOYING, can we have an official answer saying if this is ever going to be implemented?

**Comment by Haravikk** [comment] 2020-05-04 21:27
Came here to post the same damn thing, only to find it's never been implemented. I only started using Telegram on my phone recently, but the notifications are the most fucking annoying things every, taking up half the screen and appearing over whatever I'm trying to do.

I don't mind the notifications on my desktop computer because they're tiny and out of the way, but on the phone they are just far too disruptive. Why on earth aren't they controlled by the per app notification settings under Apps and Notifications?

On the plus side I've found an easy way to disable Telegram notifications on my phone only; uninstall Telegram.

**Comment by megapro17** [comment] 2020-09-10 01:20
> @megapro17 Be sure to start with pull requests that fix the issue.

I don't think that this can be fixed in client, this is a server side change

**Comment by SmartManoj** [comment] 2020-09-11 06:32
> @andrii-r This is an api issue, and I am afraid, that we can't do anything :(
> I don't know how to reach out to the api developers.
> "Ask a question" not working at all: (((((

Then how telegram-x doesn't have this problem?

**Comment by escape0707** [comment] 2020-09-11 06:37
@SmartManoj Could you kindly provide a Telegram-X iOS client for me to try it out?

**Comment by Aokromes** [comment] 2020-09-11 07:27
> @SmartManoj Could you kindly provide a link to Telegram-X iOS client for me to try it out?

there is no telegram x ios anymore, telegram x ios becomed telegram ios long time ago.

**Comment by escape0707** [comment] 2020-09-11 07:29
@Aokromes But I encounter op's issue when I'm using Telegram-iOS and telegram-desktop. So shall I say the problem is still not solved?

**Comment by baxenko** [comment] 2020-10-15 06:32
Any news?

**Comment by electrofloat** [comment] 2021-01-29 20:18
Anyone tried to report this on https://bugs.telegram.org/?

**Comment by madpipeline** [comment] 2021-02-02 08:33
> Anyone tried to report this on https://bugs.telegram.org/?

When did that start existing? Why is this issue tracker still active if that is the place to report stuff?

**Comment by baxenko** [comment] 2021-02-02 08:38
it was 2021 and the problem is still not fixed... 🤬

**Comment by electrofloat** [comment] 2021-02-02 16:35
> 
> 
> > Anyone tried to report this on https://bugs.telegram.org/?
> 
> When did that start existing? Why is this issue tracker still active if that is the place to report stuff?

On 2020.12.23.: https://telegram.org/blog/voice-chats

**Comment by Aokromes** [comment] 2021-02-02 19:02
> > Anyone tried to report this on [bugs.telegram.org](https://bugs.telegram.org/)?
> 
> When did that start existing? Why is this issue tracker still active if that is the place to report stuff?

because that bugtracker cannot be used by most persons to report bugs.

**Comment by madpipeline** [comment] 2021-02-04 09:14
I've reported it. Here's the link: https://bugs.telegram.org/c/1672

Please add any comments if you feel it helps.

**Comment by megapro17** [comment] 2021-02-12 22:13
SIX YEARS to fix one bug? What a garbage is trying to compete with whatsapp and others 🤦‍♂️

**Comment by megapro17** [comment] 2021-02-12 22:15
omg this issue is so old that i forgot that i wrote here year ago
telegram=garbage

**Comment by RafaelLinux** [comment] 2021-02-15 00:34
> omg this issue is so old that i forgot that i wrote here year ago
> telegram=garbage

So don't use it!!! I don't use WhatsApp and no problem!!

**Comment by Aokromes** [comment] 2021-02-17 19:43
such feature belongs to https://bugs.telegram.org/

**Closed by Aokromes** 2021-02-17 19:43 UTC
Labels: api issue, enhancement

**Comment by mschedrin** [comment] 2021-02-17 19:58
https://bugs.telegram.org/c/1672

**Comment by Erquint** [comment] 2021-03-31 08:47
Okay, this is ridiculous to be taking literal years.
I'm unsubscribing.
Telegram sucks.

**Comment by megapro17** [comment] 2021-03-31 12:26
> Okay, this is ridiculous to be taking literal years.
> I'm unsubscribing.
> Telegram sucks.

🥳 Welcome to VK, the best social network ever 👍
