### ISSUE TITLE
Save as don't work

### ISSUE THREAD

**Issue by CreateLab** [telegramdesktop/tdesktop#7702] opened 2020-04-24 17:10 UTC
### Steps to reproduce
1. Open telegram
2. Select file
3. Click right mouse button
4. Choose 'save as' button

### Expected behaviour
I expect, that dolphin(KDE file manager) will open

### Actual behaviour
Nothing happens

### Configuration
**Operating system:**

Description:    Ubuntu 19.10
**Version of Telegram Desktop:**
2.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Snap
**Used theme**:
KDE
plasmashell 5.16.5
Qt: 5.12.4
KDE Frameworks: 5.62.0
kf5-config: 1.0
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment] 2020-04-24 17:45
Snap has been ported to xdg-desktop-portal, you must install xdg-desktop-portal

**Comment by Aokromes** [comment] 2020-04-24 22:53
#7701

**Comment by alex-obn** [comment] 2020-04-25 18:50
> Snap has been ported to xdg-desktop-portal, you must install xdg-desktop-portal

Have the same problem. Explain, please, what should I do?

**Comment by ilya-fedin** [comment] 2020-04-25 18:56
> Explain, please, what should I do?

Install xdg-desktop-portal package and one of its backends (xdg-desktop-portal-gtk or xdg-desktop-portal-kde) via package manager

**Comment by alex-obn** [comment] 2020-04-26 10:54
> > Explain, please, what should I do?
> 
> Install xdg-desktop-portal package and one of its backends (xdg-desktop-portal-gtk or xdg-desktop-portal-kde) via package manager

I did this but now when I try to save in image a got a pop-up window with "Open" button

**Comment by ilya-fedin** [comment] 2020-04-26 16:56
> I did this but now when I try to save in image a got a pop-up window with "Open" button

Can't reproduce

**Comment by ilya-fedin** [comment] 2020-04-27 07:42
@CreateLab could you try edge channel?

**Comment by Vince972** [comment] 2020-04-27 18:47
Hello,

I have recorded my desktop to show you want happens when I want to save/download a file.

[no_file_name_when_saving.mp4.zip](https://github.com/telegramdesktop/tdesktop/files/4541504/no_file_name_when_saving.mp4.zip)

**Comment by Aokromes** [comment] 2020-04-28 16:07
@CreateLab

**Comment by CreateLab** [comment] 2020-04-30 18:37
> Snap has been ported to xdg-desktop-portal, you must install xdg-desktop-portal

```
xdg-desktop-portal-kde is already the newest version (5.18.4.1-0xneon+18.04+bionic+build65).
xdg-desktop-portal-kde set to manually installed.
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
0 upgraded, 0 newly installed, 0 to remove and 136 not upgraded.

````

**Comment by CreateLab** [comment] 2020-04-30 18:39
> @CreateLab could you try edge channel?

What do u mean? Sry don't understand

**Comment by CreateLab** [comment] 2020-04-30 18:43
try to update by using
```
snap refresh --edge telegram-desktop

**Comment by ilya-fedin** [comment] 2020-04-30 19:03
> I already had this package.

And just `xdg-desktop-portal` too?

**Comment by CreateLab** [comment] 2020-04-30 21:23
> > I already had this package.
> 
> And just `xdg-desktop-portal` too?

I install it but it doesn't help
I has KDE neon

**Comment by ilya-fedin** [comment] 2020-04-30 22:00
> I has KDE neon

Works for me with KDE neon 18.04

**Comment by ilya-fedin** [comment] 2020-04-30 22:00
Snap version: 2.1.0-8-g17de6c1ff

**Comment by ilya-fedin** [comment] 2020-04-30 22:02
```
Operating System: KDE neon 5.18
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.69.0
Qt Version: 5.14.2
Kernel Version: 5.3.0-51-generic
OS Type: 64-bit
```

**Comment by CreateLab** [comment] 2020-05-01 08:31
> ```
> Operating System: KDE neon 5.18
> KDE Plasma Version: 5.18.4
> KDE Frameworks Version: 5.69.0
> Qt Version: 5.14.2
> Kernel Version: 5.3.0-51-generic
> OS Type: 64-bit
> ```

Distributor ID: neon
Description:    KDE neon User Edition 5.18
Release:        18.04
Codename:       bionic

Snap version: 2.1.0-8-g17de6c1ff

Any variant?

**Comment by ilya-fedin** [comment] 2020-05-01 10:32
>     1. Open link doesnt work

This already tracked by another issue


>     2\. if I use show in folder telegram uses dolphin (my default file manager)
>         if I use save as telegram uses some special file dialjg (mb default for gtk i don't know)

:thinking: 
btw, file dialogs are not in file managers, they are in toolkit (in case of KDE - platformtheme plugin) and have nothing to do with dolphin/nautilus/etc.

**Comment by ilya-fedin** [comment] 2020-05-01 11:15
>     2\. if I use show in folder telegram uses dolphin (my default file manager)

I thought for a long time what you mean and understood that it was not about opening a file dialog, but about opening a folder with a file. it's ok, it has always been so.

**Comment by ilya-fedin** [comment] 2020-05-01 11:15
@Aokromes i think you can close this

**Closed** 2020-05-01 11:29 UTC
Labels: waiting for answer
