### ISSUE TITLE
desktop telegram (windows) not opening web-app

### ISSUE THREAD

**Issue by killershotpy** [telegramdesktop/tdesktop#27886] opened 2024-05-06 23:30 UTC
### Steps to reproduce

~~1. update telegram to 5.0.1 version
2. open any bot where opening by button web-app window
3. window IE not load web-app content~~

upd.
1. Set the usage rights for the "C:\Program Files (x86)\Microsoft\EdgeWebView\Application\ххх.х.хххх.хх\msedgewebview2.exe" file to the name of any user who is not an administrator or the current user.
2. try to open any web-app via telegram
3. you will see or not see the error from windows 10 system: "Cannot find ...\msedgewebview2.exe"

### Expected behaviour

content is loaded in an IE window

### Actual behaviour

<img width="293" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/77852725/e81c038b-f924-4bb9-9cd9-1c44c6338d70">

The application hangs without loading the frontend.
At the same time any application opened with any bot does not work at all.

in log file, i have this:
...
[2024.05.07 02:25:13] Skipping message, because it is already in blocks!
...

with that option enabled:
```
{
    "view-profile-in-chats-list-context-menu": true,
    "webview-debug-enabled": true
}
```
I can't even open devtools to debug the problem.

### Operating system

windows 10 home edition (desktop)

### Version of Telegram Desktop

5.0.1 (latest)

<img width="290" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/77852725/f4cec6a1-3596-493b-9cf4-db4e2109fd60">

### Installation source

Static binary from official website

### Logs

```shell
[2024.05.07 02:23:01] Launched version: 5000001, install beta: [FALSE], alpha: 0, debug mode: [FALSE]
...
...
[2024.05.07 02:23:01] Global devicePixelRatio: 1
[2024.05.07 02:23:01] QT_DPI_ADJUSTMENT_POLICY: AdjustDpi
[2024.05.07 02:23:01] Primary screen DPI: 144, Base: 96.
[2024.05.07 02:23:01] Computed screen scale: 150
[2024.05.07 02:23:01] DevicePixelRatio: 1
[2024.05.07 02:23:01] ScreenScale: 150
...
...
[2024.05.07 02:23:02] OpenGL: QOpenGLContext created, version: 3.3.
[2024.05.07 02:23:02] OpenGL: [TRUE] (Window)
[2024.05.07 02:23:03] API Warning: not loaded minimal channel applied.
[2024.05.07 02:23:16] Skipping message, because it is already in blocks!
[2024.05.07 02:23:18] Skipping message, because it is already in blocks!
[2024.05.07 02:24:51] Skipping message, because it is already in blocks!
[2024.05.07 02:24:52] Skipping message, because it is already in blocks!
[2024.05.07 02:24:53] Skipping message, because it is already in blocks!
[2024.05.07 02:25:11] Skipping message, because it is already in blocks!
[2024.05.07 02:25:13] Skipping message, because it is already in blocks!
```

**Comment by aivanouski** [comment] 2024-05-10 10:10
+1 
windows 10 pc, @wallet not loaded and any TMA

**Comment by killershotpy** [comment] 2024-05-11 15:40
related issues:
https://github.com/telegramdesktop/tdesktop/issues/26978
https://github.com/telegramdesktop/tdesktop/issues/27133

**Comment by killershotpy** [comment] 2024-05-11 16:16
> +1 windows 10 pc, @wallet not loaded and any TMA

I found a solution purely by accident.
When you install tdesktop, it searches by default for:
`C:\Program Files (x86)\Microsoft\EdgeWebView\Application\113.0.1774.57\msedgewebview2.exe`

To display the contents of the web-app.
When I explicitly set the telegram.exe executable to "open as Administrator", windows gave me the error "Cannot find ... C:\Program Files (x86)\Microsoft\EdgeWebView\Application\113.0.1774.57\msedgewebview2.exe".

It doesn't matter if you have it enabled in the experimental settings:
`"webview-debug-enabled": true`

or not, it doesn't matter.
Telegram tries to use \msedgewebview2.exe to display web-app content.

It also looks like telegram desktop is passing data to Edge, I wonder what their user agreement says about this?

**Comment by aivanouski** [comment] 2024-05-11 16:20
@killershotpy thx, you are right! Problem was with EdgeWebView

**Comment by john-preston** [comment] 2024-05-13 08:49
Well, if the WebView2 could not be initialized, fallback to WebView Legacy is made.

Telegram bot web apps on all platforms work in system webview components, I see no difference in TDesktop case here.

**Comment by killershotpy** [comment] 2024-05-13 13:46
> Что ж, если WebView2 не удалось инициализировать, выполняется возврат к WebView Legacy.
> 
> Веб-приложения Telegram-ботов на всех платформах работают в компонентах системного веб-просмотра, в случае с TDesktop я не вижу здесь никакой разницы.

Maybe you should specify somewhere to users that if their default webview is not available, then you will not have web applications opening which are initialized through telegram?

**Comment by john-preston** [comment] 2024-05-14 08:26
Well, there are some checks in code about the availability of WebView, two backends are checked on Windows. Maybe the checks aren't enough, then I'm all ears how to make them better.

WebView2 checks the version of the browser used for the webview:

https://github.com/desktop-app/lib_webview/blob/master/webview/platform/win/webview_windows_edge_chromium.cpp#L761

Legacy WebView tries to create a control process:

https://github.com/desktop-app/lib_webview/blob/master/webview/platform/win/webview_windows_edge_html.cpp#L171

If none of those worked you should see a message like that one:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/0fe8a2a0-ce65-49d0-8e10-351ec45104ca)

**Comment by aivanouski** [comment] 2024-05-14 09:08
@john-preston Is it possible to integrate webview to package instead of referrence? In my case I had corrupted folder on windows C:\Program Files (x86)\Microsoft\EdgeWebView\ 
It was moved to Z: disk space.
And portable and standalone version both was in infinite loop to trying to load TMA. I guess portable version should incapsulate webview reference inside her bundle.

**Comment by ilya-fedin** [comment] 2024-05-20 04:01
> Is it possible to integrate webview to package instead of referrence?

tdesktop uses Webview2 exactly because the intention is to not to provide a huge web browser bundle. Otherwise tdesktop would just use Qt WebEngine (which is much simpler to integrate).

**Comment by killershotpy** [comment] 2024-05-20 15:02
> > Is it possible to integrate webview to package instead of referrence?
> 
> tdesktop uses Webview2 exactly because the intention is to not to provide a huge web browser bundle. Otherwise tdesktop would just use Qt WebEngine (which is much simpler to integrate).

as I suggested above - the user should definitely be able to see the explicit behavior of their application.

thus it is necessary to add a system or (and) client alert that will show the absence of default webview.

**as well as a link to the documentation or at least this (or/and) ishy**, so that you can immediately understand what the reason is.

By default, the application is not run as administrator, and for this reason, system alerts (alerts) are not shown.

Again, I discovered the problem purely by accident, because I was running the application "as administrator".

Also, there are some related ish I have listed above, which most likely also depend on the system pre-installed webview.

and also there is another solution that I would suggest:
show a system dialog box with a choice of browser to open the target resource, in cases where the default system webview is not found.

This would solve several problems at once:
1. lack of system webview, which may not be pre-installed in the system
2. no notifications (system or from the Telegram client) about the error of searching for this webview.
3. selecting an already installed browser to open it

Unfortunately, I realize that this will introduce a number of inconveniences and reduced functionality, such as:
1. opening the telegram dialog box by clicking on 3 dots (vertical ...)
2. native passing of arguments for the same authorization via telegram account in the web application

However, the same web.telegram, explicitly passes the URL address with arguments and authorization or other actions embedded in this or that web application.

**Comment by killershotpy** [comment] 2024-05-20 15:20
> Well, there are some checks in code about the availability of WebView, two backends are checked on Windows. Maybe the checks aren't enough, then I'm all ears how to make them better.
> 
> WebView2 checks the version of the browser used for the webview:
> 
> https://github.com/desktop-app/lib_webview/blob/master/webview/platform/win/webview_windows_edge_chromium.cpp#L761
> 
> Legacy WebView tries to create a control process:
> 
> https://github.com/desktop-app/lib_webview/blob/master/webview/platform/win/webview_windows_edge_html.cpp#L171
> 
> If none of those worked you should see a message like that one:
> 
> ![image](https://private-user-images.githubusercontent.com/17900494/330346676-0fe8a2a0-ce65-49d0-8e10-351ec45104ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTcwNTEsIm5iZiI6MTcxNjIxNjc1MSwicGF0aCI6Ii8xNzkwMDQ5NC8zMzAzNDY2NzYtMGZlOGEyYTAtY2U2NS00OWQwLThlMTAtMzUxZWM0NTEwNGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxY2Q3NDNiMDA2MDNkMDAxOGY5YTIyMjliZWQ5Y2ZlNTAwZjQ2Nzk2Mzg2YmZjMTRjYzcxYjVlNjRkZjU4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AAheKA_CC8dFhUY1xWVTWNe2Kb9PF-uBBLP15ldHB6c)

I apologize for the long time reply, above see my comment about the proposed solution.

about your screenshot, I'm not quite sure if I "should have seen it by now" or if you will update the release and users will "further see" the lack of webviews?

**Comment by ilya-fedin** [comment] 2024-05-20 17:37
> show a system dialog box with a choice of browser to open the target resource, in cases where the default system webview is not found.

I'm not sure what would that give. As you can see, there's already a text for such situation, the problem is system APIs are misbehaving and saying the webview is successfully initialized despite it's not. Whatever you would like to show, you just can't detect whether it's found or not in first place with this exact breakage of system files.

**Comment by john-preston** [comment] 2024-05-24 13:24
@killershotpy The problem is that in case of some system configuration the code that I use to detect if the webview is available isn't working correctly -- it should show the "install webview2 runtime" with a link, but it doesn't show anything, as if webview was successfully initialized.

If you can provide a step-by-step way to bringing the system to the state where this happens I can try to make it myself and try to fix the detection.

**Comment by killershotpy** [comment] 2024-05-24 16:15
> @killershotpy The problem is that in case of some system configuration the code that I use to detect if the webview is available isn't working correctly -- it should show the "install webview2 runtime" with a link, but it doesn't show anything, as if webview was successfully initialized.
> 
> If you can provide a step-by-step way to bringing the system to the state where this happens I can try to make it myself and try to fix the detection.

of course, here's the step-by-step detailed instructions:
1. install window 10
2. go to the folder "C:\Program Files (x86)\Microsoft\".
3. set permissions and owner of the "EdgeWebView" folder to any non-administrator group, e.g. "local_services".
4. apply the changes to the folder and all files inside it.
5. run telegram as a normal user (not administrator).
6. try to open any web application.
in this scenario, you will **NOT** get a not

AND
1. install windows 10
2. navigate to "C:\Program Files (x86)\Microsoft\" folder.
3. set the permissions and owner of the "EdgeWebView" folder to any non-admin group, such as "local_services".
4. apply the changes to the folder and all files in it.
5. run telegram as administrator.
6. try to open any web application.
In this scenario, you will **get** a notification from the system that the file "msedgewebview2" is not found.

**Comment by Aokromes** [comment] 2024-05-24 16:36
> > @killershotpy The problem is that in case of some system configuration the code that I use to detect if the webview is available isn't working correctly -- it should show the "install webview2 runtime" with a link, but it doesn't show anything, as if webview was successfully initialized.
> > If you can provide a step-by-step way to bringing the system to the state where this happens I can try to make it myself and try to fix the detection.
> 
> of course, here's the step-by-step detailed instructions:
> 
> 1. install window 10
> 2. go to the folder "C:\Program Files (x86)\Microsoft".
> 3. set permissions and owner of the "EdgeWebView" folder to any non-administrator group, e.g. "local_services".
> 4. apply the changes to the folder and all files inside it.
> 5. run telegram as a normal user (not administrator).
> 6. try to open any web application.
>    in this scenario, you will **NOT** get a system notification
> 
> AND
> 
> 1. install windows 10
> 2. navigate to "C:\Program Files (x86)\Microsoft" folder.
> 3. set the permissions and owner of the "EdgeWebView" folder to any non-admin group, such as "local_services".
> 4. apply the changes to the folder and all files in it.
> 5. run telegram as administrator.
> 6. try to open any web application.
>    In this scenario, you will **get** a notification from the system that the file "msedgewebview2" is not found.

so, you basicaly say to reproduce this bug you must break windows.

**Comment by killershotpy** [comment] 2024-05-24 23:57
> > > @killershotpy The problem is that in case of some system configuration the code that I use to detect if the webview is available isn't working correctly -- it should show the "install webview2 runtime" with a link, but it doesn't show anything, as if webview was successfully initialized.
> > > If you can provide a step-by-step way to bringing the system to the state where this happens I can try to make it myself and try to fix the detection.
> > 
> > 
> > of course, here's the step-by-step detailed instructions:
> > 
> > 1. install window 10
> > 2. go to the folder "C:\Program Files (x86)\Microsoft".
> > 3. set permissions and owner of the "EdgeWebView" folder to any non-administrator group, e.g. "local_services".
> > 4. apply the changes to the folder and all files inside it.
> > 5. run telegram as a normal user (not administrator).
> > 6. try to open any web application.
> >    in this scenario, you will **NOT** get a system notification
> > 
> > AND
> > 
> > 1. install windows 10
> > 2. navigate to "C:\Program Files (x86)\Microsoft" folder.
> > 3. set the permissions and owner of the "EdgeWebView" folder to any non-admin group, such as "local_services".
> > 4. apply the changes to the folder and all files in it.
> > 5. run telegram as administrator.
> > 6. try to open any web application.
> >    In this scenario, you will **get** a notification from the system that the file "msedgewebview2" is not found.
> 
> so, you basicaly say to reproduce this bug you must break windows.

I haven't tested the behavior on other systems, but I've attached similar problems above in the comments, I assume they occur for the same reason - lack of a basic webview

**Comment by ilya-fedin** [comment] 2024-05-25 00:22
> but I've attached similar problems above in the comments

they all are closed as solved

**Comment by john-preston** [comment] 2024-05-28 06:32
@killershotpy Your instructions apparently break the new one, WebView2 runtime. Because I've broken it that way (I can't even open that folder from my or administrative account) and now the modern WebView2 runtime can't initialize, but the fallback to the legacy WebView based on the legacy Edge browser still works fine. In your case it looks like you had broken by permissions issue the new WebView2 runtime + somehow broken the legacy Edge as well. Idk 🤷

**Comment by ilya-fedin** [comment] 2024-05-28 09:23
@killershotpy what @john-preston points out is your steps wasn't enough for him to reproduce the issue, web bots still work but with older system API

**Comment by killershotpy** [comment] 2024-05-28 09:27
> @killershotpy what @john-preston points out is your steps wasn't enough for him to reproduce the issue, web bots still work but with older system API. You're missing something in those steps.



> but the fallback to the legacy WebView based on the legacy Edge browser still works fine

John writes that "but the fallback to the legacy WebView based on the legacy Edge browser still works fine".

but doesn't say where it is?
Point me in the right direction and I'll look it up.

**Comment by ilya-fedin** [comment] 2024-05-28 09:29
> but doesn't say where it is?

Personally I don't know. Not sure @john-preston knows. That might be something you have to find and tell us.

**Comment by killershotpy** [comment] 2024-05-28 09:38
> > but doesn't say where it is?
> 
> Personally I don't know. Not sure @john-preston knows. That might be something you have to find and tell us.

How can I find a default webview with an older API?
If I don't have it, in my case it won't revert to an older version and start the webview.

If you could point out the path where it should be I could take a look, as I don't know what paths or path variables in tdesktop you are using.

Also, you might be trying to pull variables from env system, which could also be where the error lies

The error could also be in the registry, which I also modified by removing all the microsoft edge junk.
Maybe you are relying on the registry to find an older webview API?

**Comment by ilya-fedin** [comment] 2024-05-28 09:45
> If I don't have it, in my case it won't revert to an older version and start the webview.

It should then show the text as @john-preston shown earlier. But I don't think that's possible as it should be integrated in Windows 11. The only supported system not having it out of the box is Windows 7. And, well, it's explicitly blacklisted as tdesktop fails to initialize webview on it even after manual installation of the component.

> If you could point out the path where it should be I could take a look, as I don't know what paths or path variables in tdesktop you are using.

Well, tdesktop doesn't use paths, it uses system APIs, you can see how the code looks like: https://github.com/desktop-app/lib_webview/blob/master/webview/platform/win/webview_windows_edge_html.cpp#L171-L205 (this is the legacy API while the edge_chromium file implements webview2)

That's why no one knows the paths. Unless you can remember what you have broken in the system, it might be impossible to repair it. In which case it might be better to re-install your system and close the issue.

**Closed** 2024-07-01 03:03 UTC
Labels: bug, cant reproduce
