### ISSUE TITLE
Revert UI changes on 0.9.24 regarding own message position

### ISSUE THREAD

**Issue by whagby** [telegramdesktop/tdesktop#1639] opened 2016-02-17 21:39 UTC
So far, displaying own messages to the left has been regarded as annoying to some of the users. We perceive no reason as to what the positioning of such messages should be altered, so we'd like that aspect of the messages to be reverted to its previous position.

Regards.

**Comment by ghtmtt** [comment] 2016-02-17 22:42
agreed. the new visualization is quite confusing for the users

**Comment by gMickey** [comment] 2016-02-17 23:12
+1 
It was a bit more convenient and usable in the prevous version.

**Comment by TiagoDanin** [comment] 2016-02-18 01:00
+1 :+1:

**Comment by definetti** [comment] 2016-02-18 01:19
+1

**Comment by Marinofull** [comment] 2016-02-18 02:12
:+1: 
I agree. The chat now is confusing. :neutral_face:

**Comment by GSTQ** [comment] 2016-02-18 07:45
+1

**Comment by Bogardo** [comment] 2016-02-18 08:39
+1

**Comment by IcyPalm** [comment] 2016-02-18 09:25
I personally prefer the right alignment of my own messages, maybe make it a setting?

**Comment by jesusfer** [comment] 2016-02-18 09:34
I agree. Making it a setting would suit everyone.

**Comment by FloydJohn** [comment] 2016-02-18 09:57
+1

**Comment by Kondra007** [comment] 2016-02-18 09:58
Well, I'd like to see a switcher between old and new, because I like the new design

**Comment by LucaRed** [comment] 2016-02-18 11:56
+1, they new way is very confusing for me and my friends. You can't easily follow conversations with the new layout.

Maybe you could revert to the old layout and then put a max-width with centering, such as `max-width: 1000px; width: 0 auto;` in CSS.

**Comment by LeoDJ** [comment] 2016-02-18 13:38
+1
at least give us a setting entry for it and don't make it default

**Comment by patrick246** [comment] 2016-02-18 13:38
+1
I would like to have it optional

**Comment by khalid-hussain** [comment] 2016-02-18 13:50
This is quite annoying. I maximized my Telegram today to be presented with this. I thought it was just me, so I restarted Telegram; but it was still there.

**Comment by marcovr** [comment] 2016-02-18 16:40
+1

**Comment by markkuit** [comment] 2016-02-18 17:17
Please make it a setting. It's awful.

**Comment by Aokromes** [comment] 2016-02-18 20:27
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/1587

**Comment by sinaa** [comment] 2016-02-18 20:29
+1

Or at least provide an option to satisfy both the users and Telegram developers!

**Closed** 2016-02-18 20:30 UTC

**Comment by telegramdesktop** [comment] 2016-02-21 17:17
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
