### ISSUE TITLE
Telegram Linux Desktop 1.5.8 Resetting back to default

### ISSUE THREAD

**Issue by mohitur** [telegramdesktop/tdesktop#5611] opened 2019-01-24 13:07 UTC
Telegram Linux Desktop Version 1.5.8 is auto downloading images and files on channels & groups. I have tried to disable auto downloading, but when I restart my telegram desktop application, its settings gets reset.

Old version was working fine. Please fix this issue on Linux Dekstop version of telegram.

Please FIX.

**Comment by john-preston** [comment] 2019-01-28 10:13
I can't reproduce that :( When I disable the autodownload of files / videos / music in groups / channels in Settings > Advanced, save and restart the app - the settings are saved correctly.

**Comment by stek29** [comment] 2019-01-28 13:49
@mohitur did you have to sign in again after restart?

**Comment by neesti** [comment] 2019-02-03 05:41
There is this bug in 1.5.11 (Linux version) too.

**Comment by neesti** [comment] 2019-02-12 19:18
This issue is not solved in 15.15.

**Comment by neesti** [comment] 2019-02-23 09:50
in version 1.5.15 (Linux only) these settings Resetting back to default:
Automatic media download
Local storage
Messages (Send by Enter)
![01](https://user-images.githubusercontent.com/14938202/53284746-a3c3ec80-376d-11e9-95bd-1703adc22998.jpg)
![02](https://user-images.githubusercontent.com/14938202/53284747-a3c3ec80-376d-11e9-87a2-44a6c59a3eee.jpg)
![03](https://user-images.githubusercontent.com/14938202/53284748-a45c8300-376d-11e9-9548-4936e42a0b46.jpg)

**Comment by neesti** [comment] 2019-03-10 13:59
Please fix this bug before next stable version.

**Comment by zxzzz8** [comment] 2019-03-13 12:34
i think last time i opened the app and tested it, i found it only reset if i set my ''clear files older then:'' setting to ''Never'' before closing the app.

which is a real shame, sense i really want to set it to never, also i wish i could set the other setting above 10GB....

**Comment by neesti** [comment] 2019-03-13 12:40
When I quit from Telegram (with Ctrl+Q) all of settings that before said, reset to defaults.

**Comment by john-preston** [comment] 2019-03-13 12:50
@zxzzz8 Can you please check the latest beta 1.5.16?

**Comment by john-preston** [comment] 2019-03-13 12:51
@neesti (sorry, not for Linux, maybe for Linux in the next one..)

**Comment by zxzzz8** [comment] 2019-03-13 15:20
just tested on 1.5.16 beta....
still happen. 
when i set everything except ''clear files older then....'' to maximum [that i set on 12 months] and then restart its ok, but when i set the ''clear files older then....'' on never it reset all these settings....

**Comment by john-preston** [comment] 2019-03-13 17:28
@neesti @zxzzz8 Are you using the version from the site or some packaged one?

**Comment by neesti** [comment] 2019-03-13 17:44
I use linux version of 1.5.15 and downloaded from telegram official site.

**Comment by zxzzz8** [comment] 2019-03-13 18:14
originally downloaded from the official site....

btw i also have the swift version running on my mac simultaneously, also from the official site.
but that should be irrelevant r?

**Comment by john-preston** [comment] 2019-03-13 18:15
@zxzzz8 Yes, swift version is irrelevant here, it should not interfere in any way.

**Closed** 2019-03-14 09:28 UTC
