### ISSUE TITLE
Ctrl+A, Ctrl+O, Ctrl+U etc don't work

### ISSUE THREAD

**Issue by Haegin** [telegramdesktop/tdesktop#2899] opened 2017-01-20 20:27 UTC
### Steps to reproduce
1. Open Telegram Desktop and pick a chat
2. Type a message in the chat window
3. Press Ctrl+A

### Expected behaviour
It should jump to the start of the text entry box.
Ctrl+O should to the end of the line.
Ctrl+U should clear any text before the cursor (though this doesn't work in the normal Telegram client either sadly)

### Actual behaviour
Nothing happens

### Configuration
**Operating system:**
Mac OS 10.12.2 (16C68)

**Version of Telegram Desktop:**
1.0.2

**Comment by auchri** [comment] 2017-01-20 20:28
duplicate of #2855

**Closed by auchri** 2017-01-20 20:28 UTC
