### ISSUE TITLE
Font display error on Telegram Desktop

### ISSUE THREAD

**Issue by Zheaoli** [telegramdesktop/tdesktop#7109] opened 2020-01-30 04:20 UTC
![image](https://user-images.githubusercontent.com/7054676/73419597-aa35ed80-435a-11ea-9961-1455aa77c870.png)

the version info

![image](https://user-images.githubusercontent.com/7054676/73419646-cdf93380-435a-11ea-9136-59ffaadf6956.png)

the font display correct on Android/Windows/Telegram Mac Store Version

**Comment by john-preston** [comment] 2020-02-04 08:32
I hope this will be fixed in 1.9.10. What symbols are used there, can you show a screenshot from macOS native app (this Mac Store version you've mentioned).

**Comment by Zheaoli** [comment] 2020-02-04 17:29
the font with text is 𝙲𝚝𝚑𝚞𝚕𝚑𝚞

here's the display effect on App Store Version

![image](https://user-images.githubusercontent.com/7054676/73770124-d7e5c100-47b6-11ea-8be7-f6045ac3c7c1.png)

And here's the desktop version on MacOS

![image](https://user-images.githubusercontent.com/7054676/73770173-ed5aeb00-47b6-11ea-96f6-3c8581cfdc5d.png)

**Comment by chenrylee** [comment] 2020-02-17 02:48
Same problem here.
Latest MAS version (1.9.7) running on MacOS 10.15.3, can't show some Unicode characters.

Those letters were displayed in version 1.8.15, downloaded from MAS.

**Comment by chenrylee** [comment] 2020-02-17 02:51
> the font with text is 𝙲𝚝𝚑𝚞𝚕𝚑𝚞
> 
> here's the display effect on App Store Version
> 

What does "App Store Version" mean? Do you mean the app written in Swift?
Both Telegram clients are available in MAS. :)

**Comment by tharindusathis** [comment] 2020-03-28 04:44
Also not rendering Sinhala Unicode fonts correctly, when an emoji is before it.

![image](https://user-images.githubusercontent.com/34299693/77815043-a4e7eb80-70dc-11ea-93d3-cc3a3f9608e5.png)

In above example, I have typed the exactly same word (පූජ්‍ය), but second time it renders as (පජ්‍ය).

**Comment by AndydeCleyre** [comment] 2020-07-16 18:43
@tharindusathis FWIW I see that same behavior even on my build that uses fontconfig-defined fonts. It looks right in the input field, then changes once I send it. Now that I think of it, my hack doesn't replace the hardcoded emojis, so I don't know what special handling/complications are added when TG renders those.

**Comment by Aokromes** [comment] 2020-07-16 19:15
https://bugreports.qt.io/browse/QTBUG-59553

**Comment by AndydeCleyre** [comment] 2020-07-16 19:18
I don't know if the `macOS` label is meant to be exclusive, but FWIW I reproduced @tharindusathis's example on Arch Linux, albeit with a non-standard build.

**Comment by ilya-fedin** [comment] 2020-07-16 19:21
> I don't know if the `macOS` label is meant to be exclusive, but FWIW I reproduced @tharindusathis's example on Arch Linux

The issue is about math symbols on macOS @tharindusathis's issue is a different issue

**Comment by AndydeCleyre** [comment] 2020-07-16 19:28
@ilya-fedin 

@Aokromes [has deemed](https://github.com/telegramdesktop/tdesktop/issues/5909#issuecomment-595770607) this issue to a catch-all place for "characters failing to render," and is closing other issues on that topic as duplicates of this one. As I understand things, anyway.

**Comment by ilya-fedin** [comment] 2020-07-16 19:34
> @Aokromes [has deemed](https://github.com/telegramdesktop/tdesktop/issues/5909#issuecomment-595770607) this issue to a catch-all place for "characters failing to render," and is closing other issues on that topic as duplicates of this one

Maybe he realized that it was a bad idea :)

**Comment by Aokromes** [comment] 2020-07-21 11:52
https://github.com/telegramdesktop/tdesktop/issues/6056

**Closed by Aokromes** 2020-07-21 11:52 UTC
Labels: 3rd party issue, bug, macOS
