### ISSUE TITLE
Window size and position are not remembered correctly after Aero Snapping

### ISSUE THREAD

**Issue by Zero3** [telegramdesktop/tdesktop#1693] opened 2016-02-26 15:48 UTC
When restoring the Telegram Desktop window from tray, the window size and position are normally restored to the same size and position as the last time it was closed.

However, if the window was resized/repositioned by the Aero Snap feature of Windows 7+ (example of Aero Snap: https://www.youtube.com/watch?v=7XG98bVT2HI), the size and position are not restored correctly. Instead, the last size and position before the Aero Snap are restored.

This is quite annoying if you commonly Aero Snap, close and restore the Telegram Desktop window.

**Comment by DaFri-Nochiterov** [comment] 2016-02-26 17:12
Can confirm this on Windows 10.

And... sometimes, when you restore Telegram from tray, window can lose shadows:
![image](https://cloud.githubusercontent.com/assets/10401817/13359385/9ab3c596-dce6-11e5-9942-dd5aa2276784.png)

**Comment by sunbriel** [comment] 2016-04-08 12:56
Upgraded to Windows 10 yesterday and this has been driving me insane, since I use Telegram a lot and have a habit of closing it to tray.

**Comment by N0x1k** [comment] 2016-10-26 08:33
+1 
I easily reproduced it on Win10 and Win7 with one or two monitors.

Repro steps: 
  1. Position Telegram in the middle of the screen
  2. Snap Telegram to the side of the screen (so that it covers half the screen) - Aero snap
  3. Minimize Telegram to systray (not to task bar!)
  4. Maximize from systray

Expecte:
  Telegram should open with the last used size/position covering half of the screen.

Actual:
  Telegram restores to the last position before the snapping operation (middle of the screen).

System: Win7/10
TDesktop: 0.10.19

**Comment by Tubusy** [comment] 2017-09-06 16:30
I have a similar problem, which is that TD doesn't remember which of my two screens I've set it to use after it has been shutdown and restarted. I like TD on my second screen, but I have to drag the app over there every time it starts. Not a big deal, but a little annoying...

Win 10, TD: 1.1.23

**Comment by nerai** [comment] 2018-09-12 05:42
Confirming that I've experienced this issue for years across Windows 7 and Windows 10.

**Comment by nerai** [comment] 2018-09-12 05:55
Maybe this is related to https://stackoverflow.com/questions/5673242 ?

> [...] You are trying to persist your apps position and size when the app closes down so that you can restore it when it restarts. You are using GetWindowPlacement() to do so and have discovered that it returns an incorrect position when the last sizing of the Window was an Aero Snap.
>
> My own app does exactly the same and I have encountered the exact same problem. The solution I used was to call GetWindowRect() in place of GetWindowPlacement() to obtain the window position and size.

`GetWindowPlacement` appears to be used in two positions in the source code. The first one seems to calculate the window position for a purpose that is not immediately clear to me:

https://github.com/telegramdesktop/tdesktop/blob/a76658ba467581dc13689b328340ec381d39d689/Telegram/SourceFiles/platform/win/windows_event_filter.cpp#L110-L127

The second one seems to relate to shadows, which I've also experienced as an occasional bug:

https://github.com/telegramdesktop/tdesktop/blob/a76658ba467581dc13689b328340ec381d39d689/Telegram/SourceFiles/platform/win/windows_event_filter.cpp#L140-L148

**Closed** 2018-09-28 09:31 UTC

**Comment by stek29** [comment] 2018-10-02 19:08
@Zero3 Yes, I am.
