### ISSUE TITLE
Notifications for read and answered messages showing

### ISSUE THREAD

**Issue by SemperPeritus** [telegramdesktop/tdesktop#6126] opened 2019-06-11 15:55 UTC
### Steps to reproduce
1. Get any new message from somebody
2. Answer using latest Telegram X on Android on this message
3. Notification for this message still showing in Telegram X, but also my answer showing too, so, getting info from the server was done.
(Works every time)

### Expected behavior
Notifications for read and answered messages are not displayed.

### Actual behavior
Notifications for read and answered messages are displayed.

### Configuration
**Operating system:** Windows 10 1903 x64, latest stable update

**Version of Telegram Desktop:** 1.7.7 and latest Telegram X on Android. Issue reproducing for around **1-2 months** with the latests versions for every version in this period.

**Used theme**: Midnight

<details><summary><b>Logs</b>:</summary>
[2019.06.11 06:06:04] Launched version: 1007007, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2019.06.11 06:06:04] Executable dir: C:/Users/plato/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2019.06.11 06:06:04] Initial working dir: C:/Users/plato/AppData/Roaming/Telegram Desktop/
[2019.06.11 06:06:04] Working dir: C:/Users/plato/AppData/Roaming/Telegram Desktop/
[2019.06.11 06:06:04] Command line: C:\Users\plato\AppData\Roaming\Telegram Desktop\Telegram.exe -noupdate
[2019.06.11 06:06:04] Executable path before check: C:/Users/plato/AppData/Roaming/Telegram Desktop/Telegram.exe
[2019.06.11 06:06:04] Logs started
[2019.06.11 06:06:04] Connecting local socket to Global\c8cacb0f0f663cceff6bd2da765c00d1-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2019.06.11 06:06:04] This is the only instance of Telegram, starting server and app...
[2019.06.11 06:06:04] Moved logging from 'C:/Users/plato/AppData/Roaming/Telegram Desktop/log_start0.txt' to 'C:/Users/plato/AppData/Roaming/Telegram Desktop/log.txt'!
[2019.06.11 06:06:04] Primary screen DPI: 96
[2019.06.11 06:06:04] App Info: reading settings...
[2019.06.11 06:06:04] App Info: reading encrypted settings...
[2019.06.11 06:06:04] Error: could not locate 'background.jpg' in a zip file.
[2019.06.11 06:06:04] Error: could not locate 'background.png' in a zip file.
[2019.06.11 06:06:04] Lang Info: Loaded cached, keys: 2325
[2019.06.11 06:06:04] OpenAL Logging Level: (not set)
[2019.06.11 06:06:04] Audio Playback Devices: OpenAL Soft
[2019.06.11 06:06:04] Audio Playback Default Device: OpenAL Soft
[2019.06.11 06:06:04] Audio Capture Devices: OpenAL Soft on Microphone (SADES Snuk)
[2019.06.11 06:06:04] Audio Capture Default Device: OpenAL Soft on Microphone (SADES Snuk)
[2019.06.11 06:06:05] App Info: reading map...
[2019.06.11 06:06:05] App Info: reading encrypted map...
[2019.06.11 06:06:05] App Info: reading encrypted user settings...
[2019.06.11 06:06:05] App Info: encrypted user settings read.
[2019.06.11 06:06:05] App Info: reading encrypted mtp data...
[2019.06.11 06:06:05] MTP Info: read keys, current: 5, to destroy: 0
[2019.06.11 06:06:05] Map read time: 229
[2019.06.11 06:06:05] Export Info: Destroy top bar by controller removal.
[2019.06.11 06:06:05] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
[2019.06.11 06:15:24] Skipping message, because it is already in blocks!
[2019.06.11 06:16:25] Skipping message, because it is already in blocks!
[2019.06.11 06:16:40] Skipping message, because it is already in blocks!
[2019.06.11 06:17:07] Skipping message, because it is already in blocks!
[2019.06.11 06:17:56] Skipping message, because it is already in blocks!
[2019.06.11 06:18:06] Skipping message, because it is already in blocks!
[2019.06.11 06:19:37] Skipping message, because it is already in blocks!
[2019.06.11 07:44:00] Skipping message, because it is already in blocks!
[2019.06.11 07:48:13] Skipping message, because it is already in blocks!
[2019.06.11 07:48:26] Skipping message, because it is already in blocks!
[2019.06.11 09:00:40] HTTP Error: connection refused - Connection refused
[2019.06.11 09:00:40] TCP Error: socket connection refused - Connection refused
[2019.06.11 09:00:48] HTTP Error: connection refused - Connection refused
[2019.06.11 09:00:48] TCP Error: socket connection refused - Connection refused
[2019.06.11 09:01:06] HTTP Error: connection refused - Connection refused
[2019.06.11 09:01:06] HTTP Error: connection refused - Connection refused
[2019.06.11 09:01:06] TCP Error: socket connection refused - Connection refused
[2019.06.11 09:01:06] TCP Error: socket connection refused - Connection refused
[2019.06.11 09:01:14] HTTP Error: connection refused - Connection refused
[2019.06.11 09:01:14] HTTP Error: connection refused - Connection refused
[2019.06.11 09:01:14] TCP Error: socket connection refused - Connection refused
[2019.06.11 09:01:14] TCP Error: socket connection refused - Connection refused
[2019.06.11 09:01:33] HTTP Error: connection refused - Connection refused
[2019.06.11 09:01:33] HTTP Error: connection refused - Connection refused
[2019.06.11 09:01:33] TCP Error: socket connection refused - Connection refused
[2019.06.11 09:01:33] TCP Error: socket connection refused - Connection refused
[2019.06.11 09:01:41] HTTP Error: connection refused - Connection refused
[2019.06.11 09:01:41] TCP Error: socket connection refused - Connection refused
[2019.06.11 14:01:23] API Warning: not loaded minimal channel applied.
[2019.06.11 19:46:00] Audio Info: recreating audio device and reattaching the tracks
[2019.06.11 19:46:44] Audio Info: Closing audio playback device.
[2019.06.11 19:47:30] App Info: writing encrypted user settings...
[2019.06.11 19:47:46] Skipping message, because it is already in blocks!
[2019.06.11 20:22:07] Skipping message, because it is already in blocks!
[2019.06.11 21:21:02] API Warning: not loaded minimal channel applied.
[2019.06.11 21:24:26] Audio Info: recreating audio device and reattaching the tracks
[2019.06.11 21:24:30] Audio Info: Closing audio playback device.
[2019.06.11 21:29:09] Audio Info: recreating audio device and reattaching the tracks
[2019.06.11 21:29:14] Audio Info: Closing audio playback device.
[2019.06.11 22:15:24] Skipping message, because it is already in blocks!
[2019.06.11 22:19:50] Skipping message, because it is already in blocks!
[2019.06.11 22:21:55] Skipping message, because it is already in blocks!
</details>

**Comment by tooomm** [comment] 2019-09-18 22:00
So you don't want to see the outdated and already obsolete notification on your desktop anymore when you read (and even replied) to that message on mobile already?

**Comment by SemperPeritus** [comment] 2019-09-19 00:10
> So you don't want to see the outdated and already obsolete notification on your desktop anymore when you read (and even replied) to that message on mobile already?

Yes, that's right.

**Comment by tooomm** [comment] 2019-09-19 05:28
Ok. I was confused because your ticket says it the other way around. Can you edit that please?
You mixed the expected and actual behavior section up.

I’m having the same issue, it’s very annoying. I totally support that ticket.
But this is a dupe of #6134 then.

**Closed** 2020-01-26 19:18 UTC
