### ISSUE TITLE
Media Preview stays open

### ISSUE THREAD

**Issue by markuznw** [telegramdesktop/tdesktop#5212] opened 2018-10-01 08:38 UTC
While opening media preview to see a picture, sometimes the preview stays open (under telegram window). The only way to "unbug" it is to open a different picture.

This doesn't happen on the other computer that has exactly 100% the same configuration. The only real difference is that the "bugged" computer has a dual monitor setup that I guess might be the culprit at this point.

Running system is win10 / 64 bit and default telegram desktop theme w/dark mode activated.
This is happening from 1.3.x from what we can remember and keeps happening in every beta and in 1.4 stable since then.

Thanks in advance ^^

**Comment by Aokromes** [comment] 2018-10-02 12:10
i had this issue on latest 1.3.7 but no anymore since 1.4 ..

**Comment by stek29** [comment] 2018-10-26 21:16
#5048 related

**Comment by Aokromes** [comment] 2020-01-26 12:57
cannot reproduce for long time, closing.

**Closed by Aokromes** 2020-01-26 12:57 UTC
