### ISSUE TITLE
[Feature Reqeust] Take fonts from the system theme

### ISSUE THREAD

**Issue by ivan-tretyak** [telegramdesktop/tdesktop#7480] opened 2020-03-28 20:11 UTC
It would be great if the telegram could take a font and a font size from the system theme. Because many people can have different fonts from a telegram, and what you can see when you open a telegram on a low resolution 1920×1080 monitor at 21.5 inches (like me, or even up to 27 inches at the same resolution) is terrible.

**Comment by grandsilence** [comment] 2020-04-26 11:30
I'm using Telegram without DirectWrite (Windows 10). Embedded fonts absolutely unreadable without font smoothing. I'd like to use Tahoma or Arial for sharp fonts.

Temporary solution is patching exe in HxD by font names.

**Comment by filimo** [comment] 2020-04-26 15:44
I have 2 monitors 4K and 2K. Font is ok on 4K monitor and it is awful on 2K.

**Comment by grandsilence** [comment] 2020-04-26 15:53
@filimo you are absolutely right. 2K and 1080 just a pain to read.
Patched to `Arial` font version:
![after_patching](https://user-images.githubusercontent.com/9817522/80312691-44d58980-87ef-11ea-8689-92a5afa611de.jpg)

**Comment by ilya-fedin** [comment] 2020-04-27 01:43
> I'm using Telegram without DirectWrite (Windows 10).

What do you mean? DirectWrite backend will be only in Qt 6, Telegram is always rendered through GDI.

**Comment by grandsilence** [comment] 2020-04-27 06:35
> > I'm using Telegram without DirectWrite (Windows 10).
> 
> What do you mean? Qt always uses GDI until **app** specifies custom hinting settings (which is not right in case of tdesktop)
> https://github.com/qt/qtbase/blob/v5.12.8/src/platformsupport/fontdatabases/windows/qwindowsfontenginedirectwrite.cpp#L210

I mean disabling font smoothing in `Advanced system settings`.
![aa](https://user-images.githubusercontent.com/9817522/80341066-6de73000-886a-11ea-944f-960f77262182.png)

**Comment by ilya-fedin** [comment] 2020-04-27 06:38
That's called ClearType :)

**Comment by filimo** [comment] 2020-04-27 06:54
> I have 2 monitors 4K and 2K. Font is ok on 4K monitor and it is awful on 2K.

I forgot to point that I am using telegram-desktop on macOS.

**Comment by oldherl** [comment] 2020-05-08 14:04
Stop fighting over font choices and provide a font selection option
https://github.com/telegramdesktop/tdesktop/issues/7837

**Comment by ilya-fedin** [comment] 2020-08-14 14:39
> I mean disabling font smoothing in `Advanced system settings`.

btw, there are a way to enable another font rendering engine: type `freetype` in settings like a cheat code. It works better with disabled font smoothing.

**Comment by grandsilence** [comment] 2020-08-14 15:25
> > I mean disabling font smoothing in `Advanced system settings`.
> 
> btw, there are a way to enable another font rendering engine: type `freetype` in settings like a cheat code. It works better with disabled font smoothing.

GDI without ClearType anyways much more readable and sharper.

![with_freetype_2](https://user-images.githubusercontent.com/9817522/90265636-8bf99000-de5b-11ea-8990-b8c61b2462c1.png)  

![gdi_2](https://user-images.githubusercontent.com/9817522/90265646-8dc35380-de5b-11ea-94e9-f0d327928848.png)

**Comment by grandsilence** [comment] 2020-10-23 09:25
The feature hasn't lost its relevance. A lot of working computers working without font smoothing for reducing blur and low PPI screens (around 90-110). With custom fonts Telegram is unreadable.

**Comment by gfody** [comment] 2020-10-27 05:51
It also looks pretty lumpy if you use flat/grayscale antialiasing instead of cleartype (which you can set via [Better ClearType Tuner](/bp2008/BetterClearTypeTuner)):

cleartype (rgb):
![cleartype](https://user-images.githubusercontent.com/1146032/97260023-549f4c00-17d9-11eb-9e5c-b8ddae5acd3f.png)

cleartype (grayscale):
![grayscale](https://user-images.githubusercontent.com/1146032/97260033-5a952d00-17d9-11eb-80f1-11df6ddf2fe2.png)

cleartype (disabled):
![disabled](https://user-images.githubusercontent.com/1146032/97260877-ed829700-17da-11eb-8ea4-9d9a91ff14ba.png)

..it looks like bad autohinting to me. swapping the font for something with good embedded hinting should look much better (or check if whatever is doing the autohinting has a grid-fitting feature to enable).

I've tried patching the fonts w/Mactype but Telegram seems to be loading its fonts in such a way that Mactype cannot change them. @grandsilence how did you manage to patch Arial?

**Comment by grandsilence** [comment] 2020-10-27 13:29
@gfody https://github.com/grandsilence/telegram-font-patcher-csharp

**Comment by gfody** [comment] 2020-10-29 07:04
adding this line to `lib_ui/ui/style/style_core_font.cpp` fixes it up:
```diff
	auto appFont = QApplication::font();
	appFont.setStyleStrategy(QFont::PreferQuality);
+	appFont.setHintingPreference(QFont::PreferVerticalHinting);
	QApplication::setFont(appFont);
```
![vhinting](https://user-images.githubusercontent.com/1146032/97535799-6ddefe80-1979-11eb-91a7-c3e541a14e28.png)

**Comment by ilya-fedin** [comment] 2020-10-29 07:58
@gfody you just forced vertical hinting and system settings aren't used anymore

**Comment by gfody** [comment] 2020-10-29 17:06
@ilya-fedin it's still honoring the system Cleartype setting, here it is with RGB:

![vhcleartype](https://user-images.githubusercontent.com/1146032/97607068-bd4f1a00-19cd-11eb-88c2-a7744a805628.png)

..maybe you mean the system Freetype settings, but I'm using Windows and there are no such things afaik

**Comment by ilya-fedin** [comment] 2020-10-29 17:10
> it's still honoring the system Cleartype setting, here it is with RGB:

RGB is an antialiasing type, not a hinting type

**Comment by gfody** [comment] 2020-10-29 17:44
> 
> btw, there are a way to enable another font rendering engine: type `freetype` in settings like a cheat code. It works better with disabled font smoothing.

I just realized you meant to literally type "freetype" into the settings dialog - this looks good enough for me though it doesn't seem to be honoring my grayscale Cleartype setting, the RGB is faint enough that it doesn't look so bad:
![01](https://user-images.githubusercontent.com/1146032/97611157-06ee3380-19d3-11eb-8157-a35684ca5213.png)

**Comment by ilya-fedin** [comment] 2020-10-29 17:50
> the system hinting is bad in this case so that was intentional

This is not right, a lot of people like full hinting with RGB antialiasing, forcing vertical hinting definitely is not an option

**Comment by gfody** [comment] 2020-10-29 18:07
> This is not right, a lot of people like full hinting with RGB antialiasing, forcing vertical hinting definitely is not an option

those people are crazy 😄 I would probably switch to vertical hinting at least when Cleartype is disabled, but either way I'm satisfied with the "freetype" cheat code. maybe a similar thing could be added to set `QFont::NoAntialias` for the likes of grandsilence et al

**Comment by ilya-fedin** [comment] 2020-10-29 18:09
I'm not sure... Core developers are strongly against adding any font settings.

**Comment by ilya-fedin** [comment] 2020-10-29 18:10
btw, this is a duplicate of #90

**Comment by grandsilence** [comment] 2020-10-29 18:37
The point is that the Telegram Client should check whether the font smoothing is disabled in the system.
If it's really turned off — use system fonts rather than built-in ones.

Because built-in fonts always look awful without font smoothing. And the system fonts should be **obtained from the Windows registry**.

The default for Windows 7 and 10 is `Segoe UI`, but you can change them to `Arial` or `Tahoma` (Windows XP default UI fonts) using the registry editor, and then the fonts will be crystal clear everywhere, including Telegram.

To get system font smoothing state using WinAPI call, use:

```
user32.dll
SystemParametersInfo(iuiAction, uiParam, pvParam, fWinIni);
where uiAction = SPI_GET_FONT_SMOOTHING = 74
```

**Comment by ilya-fedin** [comment] 2020-10-29 18:40
> And the system fonts should be **obtained from the Windows registry**.

This sounds like a hack, system fonts should be obtained by Qt

**Comment by grandsilence** [comment] 2020-10-29 18:44
> > And the system fonts should be **obtained from the Windows registry**.
> 
> This sounds like a hack, system fonts should be obtained by Qt

Possibly. But the [Enpass](https://www.enpass.io/) application, which is also written in Qt, uses the correct system fonts, without hard-coding the names of system fonts.

**Comment by ilya-fedin** [comment] 2020-10-29 18:46
> But the [Enpass](https://www.enpass.io/) application, which is also written in Qt, uses the correct system fonts, without hard-coding the names of system fonts.

I don't know why you talking about hardcoding, I said "obtained by Qt".

**Closed** 2020-10-29 18:48 UTC
Labels: enhancement
