### ISSUE TITLE
Restore system window frame of call window 

### ISSUE THREAD

**Issue by EndrII** [telegramdesktop/tdesktop#10521] opened 2021-03-12 15:21 UTC
![telega](https://user-images.githubusercontent.com/12465465/110960287-a3501b80-835f-11eb-9927-6201f783c323.png)

Due to the fact that you have removed the system frame from the call window, it is now impossible to activate a function that is very important for video calls. "Always display the window on top"
 
I don’t know what about other shells, but in GNOME, this function is present and it is very convenient when you work and at the same time use video call.

**Comment by ilya-fedin** [comment] 2021-03-12 23:46
> but in GNOME

Exactly GNOME developers forcing to do this crap since they require all applications have client-side titlebars or there will be no titlebar at all in Wayland since they don't want to support xdg-decoration.
https://gitlab.gnome.org/GNOME/mutter/-/issues/217

Anyway, duplicate of #10002

**Comment by ilya-fedin** [comment] 2021-03-12 23:51
> t is now impossible to activate a function that is very important for video calls. "Always display the window on top"

https://github.com/telegramdesktop/tdesktop/issues/10405#issuecomment-783084967

**Closed** 2021-03-13 00:02 UTC
