### ISSUE TITLE
Interrupts shutdown (Linux Mint/Ubuntu/KDE)

### ISSUE THREAD

**Issue by Nitrosito** [telegramdesktop/tdesktop#633] opened 2015-04-07 16:04 UTC
Hi! Sorry for my english. 

But i have a bug, on my PC (Linux Mint 17 KDE X64) and other pc friends (Linux mint too).

When you pick on Quit > shut down , telegram interrupts this process, and pc not shutdown, the process telegram finish, but not shut down PC( Plasma Desktop show notification about this interrupts) . If you shut down again, the pc shutdown correctly.

![telegram](https://cloud.githubusercontent.com/assets/4531540/7027589/7f822dda-dd50-11e4-97b0-7271321e8e42.png)

**Comment by roberth1990** [comment] 2015-04-12 00:22
I have the same problem in KDE, please fix this.

**Comment by Nitrosito** [comment] 2015-04-12 08:35
I think that this problem appear on  Plasma Desktop's
I can confirm bug in other 3 computers with KDE Desktop

**Comment by whodafly** [comment] 2015-04-14 19:00
I get this on my KDE 4, Debian unstable desktop.

**Comment by Nitrosito** [comment] 2015-04-14 21:21
updated telegram, I think we have already solved.
I think the last time goes well

**Comment by Nitrosito** [comment] 2015-04-17 11:55
Any can confirm this? ¿the problem has fixed?
If i reboot the PC, telegram interrupt this process now T_T

**Comment by SanKro** [comment] 2015-04-17 12:00
Not a fix but on any ubuntu base you should consider to switch to cutegram
http://aseman.co/en/products/cutegram/

because it has desktop integration and it works much better in most cases.

**Comment by whodafly** [comment] 2015-04-17 12:04
I'm still getting this problem. I'll check which version I have and reply.

**Comment by roberth1990** [comment] 2015-04-17 13:46
This problem has nothing to do with distribution, it occours for on both debian jessia and archlinux with kde4.

**Comment by whodafly** [comment] 2015-04-17 22:28
I'm using tdesktop 0.8.4.

**Comment by whodafly** [comment] 2015-04-20 06:49
If the Telegram window is visible, then this bug occurs. If I close the window so that only the icon appears in my system tray, then it doesn't do this.

The bug is because closing the window only minimises the app to the tray. It doesn't obey SIGTERM properly.

**Comment by Nitrosito** [comment] 2015-05-30 14:39
Pls , fix this problem!!!
Today, the bug exist! -.- 
This bug must have critical priority!

**Comment by roberth1990** [comment] 2015-05-30 14:47
The developers are busy adding emoji and stickers support, critical bugs must wait.

**Comment by Nitrosito** [comment] 2015-05-30 14:56
Emoji and stickers are more important than the program cancel the shutdown? O.o

**Comment by roberth1990** [comment] 2015-05-30 15:00
Appearantly, look at the changelog.

**Comment by Kurgan-** [comment] 2015-06-15 11:05
I have the same issue with Linux Mint 17.1 (Cinnamon). Sometimes it shows the windows telling me that shutdown was cancelled by telegram, sometimes it simply does not shut down, without any message shown. 

Giving the shutdown command a second time starts the shutdown.

**Comment by ppparadox** [comment] 2015-07-04 07:36
Me too, Linux Mint MATE 17.1 kernel 3.13.0-37 x64.

**Comment by whodafly** [comment] 2015-07-20 06:37
Still getting this on 0.8.38

**Comment by SukhikhN** [comment] 2015-08-10 18:06
Same with 0.8.48

**Comment by Ocelot92** [comment] 2015-08-12 08:05
Exactly what I tried to say here #527

**Comment by pleonex** [comment] 2015-08-19 15:48
Same problem with 0.8.52, Fedora 22 with Plasma 5.
This is the best client for Telegram but this bug it's really really annoying, it just happens always.
So from now I am using only the web client.

**Comment by jasauders** [comment] 2015-08-26 02:23
Found this issue while Googling around. I'm seeing the same issue on Ubuntu 14.04.3 with Unity. It's easy to replicate and happens on all 3 of my systems running 14.04. All are on Telegram 0.8.52.

**Comment by TommyHernandez** [comment] 2015-08-29 10:24
I have the same problem in Linux Mint KDE Telegram version 0.8.52. Please Fix this Bug improve to critical.

**Comment by Nitrosito** [comment] 2015-08-29 10:28
Please, fix this bug. This is a HIGH CRITICAL bug.

**Comment by evgenymarkov** [comment] 2015-09-04 18:18
This bug appears in XFCE 4.12 too.

**Comment by Nitrosito** [comment] 2015-09-23 09:50
In KDE 5 it seems that the problem is greater. Because when you turn off your computer, you will not turn off if telegram was open, and the screen goes black. TTY must be opened and off manually

Can anyone confirm?

Please, fix this problem...

**Comment by JJ** [comment] 2015-09-24 11:21
Heppens too in Ubuntu 14.04 with Gnome. Interrupts shutdown sequence, shut downs telegram, does nothing else.

**Comment by LendLord** [comment] 2015-09-30 18:39
Kubuntu 15.04, same issue. Fix pls.

**Comment by PhoenixAlx** [comment] 2015-10-07 08:00
Archlinux with xfce too

**Comment by TommyHernandez** [comment] 2015-10-08 14:16
Telegram Version 0.9.2 the problem Still happend 7 month later and 28 comments after ( 29 now).

**Comment by telegramdesktop** [comment] 2015-10-08 14:28
@TommyHernandez fixing pull request from the community will be much appreciated :)

**Comment by Nitrosito** [comment] 2015-10-08 16:01
Developers should have this bug as critical and priority for months

**Comment by auchri** [comment] 2015-10-08 16:44
I think it would be high priority if it would happen on windows :p

**Comment by JJ** [comment] 2015-10-08 17:53
If anyone gives us a hint of where the shutdown sequence happens, we can
have a look at it, @telegramdesktop, but we have no clue.

**Comment by telegramdesktop** [comment] 2015-10-08 18:10
@JJ Currently I have no clue, because I don't know what can possibly interrupt shutdown of some Linux OS.

And not any Linux OS (because Ubuntu 15.04 just closes Telegram Desktop and does the shutdown like any other — normal — OS does), but some specific Linux OS.

And not just interrupt the shutdown, but (as I understood from the topicstarter) successfully close Telegram Desktop (like it should do), but stop the shutdown in that moment.

Any ideas? What exactly that specific Linux OS does, how does it close the app, how it wants the app to catch that desire and close itself or what else?

**Comment by Nitrosito** [comment] 2015-10-08 18:14
This has been going on a particular version of Telegram. Something had to change in telegram

**Comment by telegramdesktop** [comment] 2015-10-08 18:15
@Nitrosito When the tray icon was introduced? Before that closing the window was leading to closing of the app.

**Comment by Nitrosito** [comment] 2015-10-08 18:16
@telegramdesktop  It's posible. I think it occurs from one to two weeks before I opened the issue.

**Comment by whodafly** [comment] 2015-10-08 18:19
@telegramdesktop as per [one of my previous comments](#issuecomment-94372749):

If the Telegram window is visible, then this bug occurs. If I close the window so that only the icon appears in my system tray, then it doesn't do this.

The bug is because closing the window only minimises the app to the tray. It doesn't obey SIGTERM properly.

**Comment by JJ** [comment] 2015-10-08 18:47
2015-10-08 20:10 GMT+02:00 telegramdesktop <notifications@github.com>:

> @JJ <https://github.com/JJ> Currently I have no clue, because I don't
> know what can possibly interrupt shutdown of some Linux OS.
>

Um, you're right. But there must be something in the way Telegramdesktop
handles OS signals. I'll try to find out what kind of code might cause that
and be back to you.

**Comment by telegramdesktop** [comment] 2015-10-08 18:51
@JJ Well, I don't handle any OS signals directly, Qt does. I just handle window close event and skip it and minimize app to tray. As I see in http://doc.qt.io/qt-5/qcloseevent.html QCloseEvent docs there is no way to understand from that event, was it just window-close-by-"X" event or some mega-close-right-now event by OS which is shutting down.

**Comment by whodafly** [comment] 2015-10-08 19:02
@telegramdesktop That's pretty much what I was saying. You ignore the "close" signal. Surely you should check if the window is currently open before just minimizing? If the window is not visible, then continue with the close, otherwise minimize.

**Comment by JJ** [comment] 2015-10-08 19:02
2015-10-08 20:52 GMT+02:00 telegramdesktop <notifications@github.com>:

> @JJ <https://github.com/JJ> Well, I don't handle any OS signals directly,
> Qt does. I just handle window close event and skip it and minimize app to
> tray. As I see in http://doc.qt.io/qt-5/qcloseevent.html QCloseEvent docs
> there is no way to understand from that event, was it just
> window-close-by-"X" event or some mega-close-right-now event by OS which is
> shutting down.
>

I have been checking some linux specific code here
https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/pspecific_linux.cpp,
but I really have no clue, C++ is not my cup of tea. It does seem to handle
a signal, but that's SIGSEGV. I guess the way to go would be to trace an
execution and see what happens.

I'll try to pin down exactly what happens. Theoretically, the same should
happen if we just kill or pkill it.

**Comment by auchri** [comment] 2015-10-08 19:03
@telegramdesktop What's about [`spontaneous`](http://doc.qt.io/qt-5/qevent.html#spontaneous)?
> Returns true if the event originated outside the application (a system event); otherwise returns false.

**Comment by SukhikhN** [comment] 2015-10-08 19:03
old thread, but may be related http://www.qtcentre.org/threads/33320-Break-system-shutdown-when-in-my-program-I-want-minimize-instead-close

**Comment by telegramdesktop** [comment] 2015-10-08 19:03
@JJ I don't handle SIGSEGV, I was going to start to handle it, for crash backtraces, but didn't (yet).

**Comment by mardy** [comment] 2015-10-08 19:04
@SukhikhN suggestion seems reasonable, telegram could handle the commitDataRequest() signal:
http://doc.qt.io/qt-5/qguiapplication.html#commitDataRequest

**Comment by JJ** [comment] 2015-10-08 19:05
2015-10-08 21:03 GMT+02:00 telegramdesktop <notifications@github.com>:

> @JJ <https://github.com/JJ> I don't handle SIGSEGV, I was going to start
> to handle it, for crash backtraces, but didn't (yet).
>

Sorry, by "handling" I just meant I found a reference to it in that place.
It includes signals.h, too.

**Comment by Nitrosito** [comment] 2015-10-08 19:05
Perhaps kdebugdialog dialog enabling obtain some information. See if I can get something

**Comment by JJ** [comment] 2015-10-08 19:07
2015-10-08 21:03 GMT+02:00 SukhikhN <notifications@github.com>:

> old thread, but may be related
> http://www.qtcentre.org/threads/33320-Break-system-shutdown-when-in-my-program-I-want-minimize-instead-close
>

Right, check this out:
```
Check out QApplication::commitDataRequest() signal. By default when the
system is going to shutdown will emit this signal and if you don't get it
QApplication will send closeEvent to all the opened windows, if any window
ignore the close event(like you are doing when minimizing) the shutdown
will be canceled. To avoid such a case just connect to that signal(note you
should explicitly use Qt:irectConnection for this signal as the
documentation says) and rise some flag or send some custom event to your
windows in order to let them know that when they receive closeEvent they
must accept it.
```

**Comment by telegramdesktop** [comment] 2015-10-08 19:12
@SukhikhN Thanks, I'll try to use that one in the next version.

**Comment by mardy** [comment] 2015-10-08 19:17
About QApplication::commitDataRequest(), the documentation says that you shouldn't quit the application when you receive it.
I guess that the solution could be to start a timer of a few seconds when you receive that signal; if while this timer is running you get the closeEvent() on the window, then don't ignore the event but just let it get closed.

**Comment by telegramdesktop** [comment] 2015-10-08 19:20
@mardy Yes, I didn't find any way to understand, did the "shutdown attempt" finish or not. But seconds is not good, as I understand the process, some other window can show a dialog box for saving the unsaved changes, and user can think for a minute in that dialog box and then decide either to save and shutdown should continue or to cancel and shutdown should stop — and window close should minimize app to tray :(

**Comment by whodafly** [comment] 2015-10-08 19:49
@mardy @telegramdesktop I think the idea is that you change a flag somewhere, and when you get the close event, you check that flag and either minimize or shutdown, depending on the value of the flag.

**Comment by telegramdesktop** [comment] 2015-10-08 19:57
@whodafly But when do I change it back? If the shutdown was started, but was cancelled by some other app I need to switch that flag off so that closing the window minimizes it (again).

**Comment by whodafly** [comment] 2015-10-08 20:07
@telegramdesktop I don't have an answer for you off the top of my head, but in my opinion that's still WAY better than what's happening now.

**Comment by telegramdesktop** [comment] 2015-10-08 20:21
@whodafly Sure it is.

**Comment by mardy** [comment] 2015-10-09 06:26
A possibility is that you set the "quitOnLastWindowClosed" to false, and when that flag is let the window get closed and then set the flag back to false. This means that if a user closes the window after a canceled shutdown you will close the window instead of hiding it, but telegram will continue running anyway. Of course, this assumes that you are able to rebuild the window, when needed.

**Comment by telegramdesktop** [comment] 2015-10-09 08:01
@mardy I've looked through some Qt code and I see, that QGuiApplication always tries to close all windows after commitDataRequest() — no matter what other apps did. So there is no difference between closing tdesktop inside commitDataRequest() or not — it will be closed anyway. But the better solution is to check QGuiApplication::isSavingSession() method — and close the window instead of minimizing if it is true. Because this flag is set right in the same place in code, that cancels session_manager shutdown — and we don't want it ever to stop the shutdown process.

**Comment by Nitrosito** [comment] 2015-10-20 21:44
You fixed problem @telegramdesktop ?
On my PC, shut down look good

**Comment by telegramdesktop** [comment] 2015-10-20 21:51
@Nitrosito In the last versions (0.9.6 stable) it should be good.

**Comment by Nitrosito** [comment] 2015-10-21 06:14
someone else can confirm?

**Comment by roberth1990** [comment] 2015-10-21 06:18
Works for me now with plasma 5.

**Comment by LendLord** [comment] 2015-10-21 06:18
It works for me. Problem solved. Thank you

**Comment by auchri** [comment] 2015-10-21 06:42
awesome!

**Closed by auchri** 2015-10-21 06:42 UTC
Labels: bug

**Comment by eljenso** [comment] 2016-06-17 12:09
Since the last update, this issue is back:
When shutting down only Telegram quits but the shutdown is interrupted. Only when I hit shutdown again, the computer shuts down.

I'm running Xubuntu 14.04 with Xfce 4.12

**Comment by Kurgan-** [comment] 2016-06-17 15:56
Yes, the issue is back for me too. (Mint 17.3 with Cinnamon).

**Comment by john-preston** [comment] 2016-06-17 16:27
@Kurgan- I guess the attempt to save message draft to cloud first prevents the shutdown. Can you test with just launched Telegram Desktop? (without even opening any chats)

**Comment by Kurgan-** [comment] 2016-06-17 17:01
No, I don't see this behaviour. On my computer I see a different behaviour. The Telegram client interrupts the shutdown p[rocedure only when its window is visible. If I "close" the window (but leave the tray icon on, so the program is running) I can shut down properly. If I leave the window open, I cannot shutdown. It does not matter whether I open a chat, write a message, or just open Telegram without entering any chat at all and immediately try to shut down the pc.

**Comment by olegantonyan** [comment] 2016-06-21 06:56
0.9.51 openSUSE 64 bit KDE 4.14.9
The problem is still there. Appeared after one of the recent updates
