### ISSUE TITLE
 Allow payment also from desktop Telegram app [Feature Request] 

### ISSUE THREAD

**Issue by mdan312** [telegramdesktop/tdesktop#7933] opened 2020-05-22 13:36 UTC
Allow payment API also from desktop Telegram app... If you want that to be more widely adopted...

**Comment by ilya-fedin** [comment] 2020-05-23 00:01
#7621?

**Comment by RememberTheAir** [comment] 2020-05-23 14:35
@ilya-fedin yes, duplicate of 7621

**Closed** 2020-05-23 17:22 UTC
