### ISSUE TITLE
[Feature Request] Send text above, rather than below, photos

### ISSUE THREAD

**Issue by superclarkk** [telegramdesktop/tdesktop#10300] opened 2021-02-02 14:22 UTC
### Is your feature request related to a problem?
I've lost count of how many times I've forgotten that the text sent with images (photos) will appear below the image rather than above, and had to delete it and send the text separately, so that the text, that refers to the photo, makes sense. Often I want to refer to a previous image, sent earlier in the conversation, that contains an error, and want to say, "this is how it should be" (referring to the image I'm sending), or want to say, "That's how it was then. This is how it is now" 

### Describe the solution you'd like
When sending an image(s), include any text above the image(s).

### Describe alternatives you've considered
The only solution I know is to manually send the text separately, which is not ideal.

### Additional context
I don't want to compare Telegram to Discord, because I love Telegram, and find Discord generally an annoying piece of software to use.  However, one thing it does get right is how it deals with this issue (it behaves in the way I've described above).

**Comment by RememberTheAir** [comment] 2021-02-02 14:29
Duplicate of #6900

**Closed** 2021-02-02 14:49 UTC

**Comment by superclarkk** [comment] 2021-02-02 15:56
This is not a duplicate. This relates to posting images, not forwarding messages.

In fact, forwarded messages appear after the message text, which is what I've requested for images. Thus, it makes it a stronger case for this ticket, as it would make sending images consistent with forwarding messages.

**Comment by RememberTheAir** [comment] 2021-02-02 16:41
Wait I'm not sure I understand what you're asking then - you want the caption to appear _above_ the photos/videos you send? if so, I guess Telegram Desktop can't do much about this as long as it's how it works on every other official client. I guess this belongs to https://bugs.telegram.org (platform-wide suggestions board)

**Comment by superclarkk** [comment] 2021-02-02 17:09
Thank you, @RememberTheAir. I've opened ticket [#1596](https://bugs.telegram.org/c/1596) there.
