### ISSUE TITLE
Updates kill sound on Windows 10

### ISSUE THREAD

**Issue by KChernenko** [telegramdesktop/tdesktop#1117] opened 2015-09-22 21:12 UTC
Guys, every client's update kills sound on my Windows 10 laptop and I always need to restart it. It's really annoying.

P.s. I'm using dev. version if it helps.

**Comment by Aokromes** [comment] 2015-09-25 19:10
You mean when you update telegram it breaks windows 10 playing sounds? or only the ones on telegram?
If the 1st, i am unable to reproduce with 0.9.1 to 0.9.2 update.

**Comment by auchri** [comment] 2015-09-25 22:23
Same as @Aokromes here

**Comment by KChernenko** [comment] 2015-09-26 13:28
The first one. I think it's some incompatibility with my laptop drivers and the library that uses for playing sound in this client. Also, I can't play voice messages in chat - I can just download them.

**Comment by antsiferov** [comment] 2016-02-26 15:20
@KChernenko Are you using Realtek HD Audio?

I've got the same problem -- starting Telegram after the update (so there is a notification) shuts down the audio in Windows 8.1. The problem can be fixed by restarting the audio services after, but it's pretty annoying.

Configuration: Dell Latitude E5450, Realtek HD Audio, Windows 8.1

**Comment by Decadence** [comment] 2016-06-29 14:05
Same situation for me on Windows 10 and Realtek HD Audio. Restarting Telegram solves problem.

**Comment by tdesktop-closer** [comment] 2017-06-27 07:23
Hey there!

We're automatically closing this issue since there was no activity in this issue since 362 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

<sub>(Please note that this is an [automated](https://github.com/auchri/github_auto_closer) comment.)</sub>

**Closed by tdesktop-closer** 2017-06-27 07:23 UTC
Labels: auto closed
