### ISSUE TITLE
Skinning issues on Windows desktop client 

### ISSUE THREAD

**Issue by hholst80** [telegramdesktop/tdesktop#1793] opened 2016-03-17 15:52 UTC
The Telgram client in Windows 7 does not work as expected. By alt-tabbing between applications (on two different monitors in my case), the Telegram klient is drawn with Windows classic skinning. Telegram refreshes itself if I click on it. On the picture below only the menu bar issue is shown, but I have also seen that the minimize and close icons are first shown as Windows Classic buttons.

Windows 7 processional (64-bit) and Telegram Windows desktop client 0.9.32.

![image](https://cloud.githubusercontent.com/assets/6200749/13852026/af85235a-ec60-11e5-802e-a8a74dc0aa06.png)

**Comment by john-preston** [comment] 2016-03-17 15:58
@hholst80 I currently don't know how to fix that :(

**Comment by auchri** [comment] 2016-03-17 18:50
#100

**Comment by auchri** [comment] 2016-03-17 18:50
Duplicate of #1216

**Closed by auchri** 2016-03-17 18:50 UTC
