### ISSUE TITLE
Make posts use more of available window width

### ISSUE THREAD

**Issue by rotanov** [telegramdesktop/tdesktop#2928] opened 2017-01-26 03:50 UTC
Suggestion regarding messaging interface.

I often send patches of code through telegram. While message box with text with current max width may be fine for comfortable reading of text it would be wonderful if it used more horizontal space (which is certainly available) when there's a large chunk of "wide" programming code in the message.

I think it still would be nice not only for programming code but for regular message. This is a desktop application and when I make Telegram window to occupy half of my second monitor it doesn't using all available space. Or at least more of it. You can make it configurable.

Getting to the point when post of 36 characters getting trimmed to 20 chars when replying to it. And it's taking 1/5 of telegram window's width.

**Comment by auchri** [comment] 2017-01-26 06:48
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/2060

**Closed by auchri** 2017-01-26 06:48 UTC
