### ISSUE TITLE
Calls make everything else too quiet

### ISSUE THREAD

**Issue by alexisSruti** [telegramdesktop/tdesktop#4236] opened 2017-12-25 02:59 UTC
### Steps to reproduce
1. Do a call
2. That's it. This happens every single time. It's not in the version notes, so I'm assuming it's not a feature? It did not happen previously.

### Expected behaviour
Everything else should be at the same volume so that I can use their own volume control to adjust.

### Actual behaviour
Everything besides the call becomes very quiet.

### Configuration
**Operating system:**
Mac OS X El Capitan 10.11.6

**Version of Telegram Desktop:**
1.2.1

**Used theme**:
Default?

<details><summary><b>Logs</b>:</summary>
No logs

</details>

**Comment by hehehe426** [comment] 2017-12-25 03:02
Hey, this is the same user. I accidentally used an account for a school project to make this post, but this is my personal account.

**Comment by Aokromes** [comment] 2018-01-02 14:43
IIRC on windows system handles this, so maybe it's not a bug instead one OS feature.

**Comment by Aokromes** [comment] 2018-01-02 14:50
https://i.imgur.com/fcMyIkw.png

**Comment by stek29** [comment] 2018-01-02 15:36
Hm, for me TDesktop never caused it, but macOS native Swift app did

**Comment by hehehe426** [comment] 2018-01-02 18:29
As far as I can tell, no such setting exists on Mac.

**Comment by Aokromes** [comment] 2018-01-03 05:41
https://apple.stackexchange.com/questions/189552/facetime-calls-lower-system-volume
It looks such feature exists on macos, idk if it can be fixed on telegram side.

**Comment by hehehe426** [comment] 2018-01-03 05:44
Did you look at that thread though? It's unusable due to System Integrity Protection. Mac has no proper setting or feature for this.

**Comment by Aokromes** [comment] 2018-01-03 05:45
I said "feature exist" not setting exist :)

**Comment by Aokromes** [comment] 2018-01-03 05:49
Ok, try this:
https://www.applevis.com/forum/macos-mac-app-discussion/how-turn-volume-ducking-os-x-109

**Comment by stek29** [comment] 2018-10-07 23:28
@pressRtowin Windows is another story.

@alexisSruti try `printf "p *(char*)(void(*)())AudioDeviceDuck=0xc3\nq" | PATH="/usr/bin:$PATH" lldb -n Telegram`. This is a feature, not sure what can be done about it.

@grishka maybe it is possible to expose it in libtgvoip so a hidden setting can be added?

**Comment by grishka** [comment] 2018-10-08 00:37
It's a system feature. I'm not sure there's anything that can be done with this except using some undocumented API. I don't really understand what that command @stek29 posted does.

**Comment by stek29** [comment] 2018-10-08 01:03
@grishka that snippet attaches debugger to process, and patches `` CoreAudio`AudioDeviceDuck `` to be just a `ret`.

**Closed by stek29** 2018-10-08 01:03 UTC

**Comment by grishka** [comment] 2018-10-08 02:42
Actually, you can also call that function directly, the full signature is

    OSStatus AudioDeviceDuck(AudioDeviceID inDevice, Float32 inDuckedLevel, const AudioTimeStamp* __nullable inStartTime, Float32 inRampDuration);

Of course that can only be done in the non-appstore version since it's a private API. There's a [usage example in Chromium sources](https://chromium.googlesource.com/chromium/src/media/+/master/audio/mac/audio_low_latency_input_mac.cc).

**Comment by stek29** [comment] 2018-10-08 20:09
@grishka the point is to avoid that function from being called or make it do nothing.

you can also try to make a weak symbol to override it, but I'm not sure that would not be interfered by dyld shared cache inlining.

anyway, patching private library functions is definitely out of scope of normal apps -- it's apple who should provide an option to disable this questionable behavior.

**Comment by grishka** [comment] 2018-10-08 20:16
@stek29 but you can counteract it too by calling it again like that file I linked does. Doesn't require messing with any function internals and hacking things and overwriting machine code which is good enough of a solution for me 😆

**Comment by jlsjonas** [comment] 2019-01-21 21:39
Just updated, works great!

**Comment by Kougeru** [comment] 2019-02-19 22:25
My audio "Communications" thing on Windows 10 is set to "Do nothing" and every other program respects this. Telegram for the past 2 months has been lowering the volume of all my other programs. But on the volume slider, they're still showing 100% volume....that's the weird thing. Telegram is somehow lowering their volume in some other way. As soon as I end calls, volumes return to normal. It's 100% telegram's fault. Any idea how to fix this?

**Comment by grishka** [comment] 2019-02-19 22:42
This issue is about Mac. Are you really sure you have it set to "do nothing"? I don't do anything specifically to lower the volume of other programs. I don't think there's even an API to control that.

**Comment by Kougeru** [comment] 2019-02-19 23:03
My bad, it was the only result related to the issue, I didn't notice it was for Mac. 

I'm 100% sure it's set to "Do Nothing". I stared at during the call in confusion, even lol. No other program controls volume when I'm in calls. I've never seen anything like this before, either. The sliders all remain at 100% like I said, but the volume gets lowered by like 50% on all other programs during the call. I see no setting about this on the...settings, anywhere, so at first I assumed it was a bug but I suppose it could be a forced "feature".  Started happening in January.

**Comment by pressRtowin** [comment] 2019-03-23 14:10
Not to derail the mac discussion, but as I also mistakenly commented above, I can 100% verify @Kougeru's report. Telegram is the only app on windows 10 that does not respect this setting. I have it set to do nothing, yet when I start a call, sounds will drop. If I quit the call, then go back to communication settings, change it to something else, then back to do nothing, telegram respects it for a while, but there's telling when it'll revert again.

**Comment by grishka** [comment] 2019-03-23 14:15
This setting is applied by the system, not by Telegram. The only thing Telegram does is it specifies that its audio streams are for "communication".

As for Mac, we had to remove this from the app store version because apps that use private APIs make Apple unhappy. But the mac app store is useless anyway, so who cares.

**Comment by pressRtowin** [comment] 2019-03-23 14:30
Not sure how the system would specifically only allow telegram to repeatedly ignore this setting. Other voice call applications respect the do nothing setting every time.

**Comment by grishka** [comment] 2019-03-23 14:33
My point is that Telegram doesn't contain any code whatsoever to read and respect this setting. I have absolutely no idea whether there is an API to lower the volume of other apps either. This is all done entirely by the system.

**Comment by oguzbilgic** [comment] 2019-09-12 06:35
> The latest version that came out today does have a setting for this.

for Mac? What is it called?

**Comment by marzapower** [comment] 2019-10-02 19:59
I found out how to turn off this feature on macOS. Open the Telegram app, click on the burger menu in the top left corner, then on the "Calls" menu voice. In the new popup window locate the gears icon near the top right corner, click on it, then scroll to the bottom of this new "Call Settings" popup, and locate the "Mute other sounds during calls".
Uncheck it.
Make profit!
💸

**Comment by marzapower** [comment] 2020-01-20 21:11
Additional info: this setting can only be found in the app that you download from Telegram's website. If you download it from the App Store there is no way to disable the volume ducking mechanism 😤

**Comment by grishka** [comment] 2020-01-21 07:25
It had to be removed from the app store version because it uses a private API to restore the volume.

I'd suggest to never download app store versions of any Telegram clients unless you deliberately want to suffer.

**Comment by dsapsan** [comment] 2020-12-25 10:23
At the moment (version 2.5.1), the bug is still relevant for Windows 10. There is no disable option in the settings. Windows 10 settings are ignored.

**Comment by john-preston** [comment] 2020-12-25 10:29
@dsapsan I'll try another webrtc audio backend in the next beta version, I hope to release it today.

**Comment by Glamurio** [comment] 2021-01-09 13:50
Just popping in because I've been having this issue for weeks as well and finally went out to google if there's a fix. It's still relevant, it still occurs, I'd appreciate this getting looked into because it's very tiresome.

**Comment by john-preston** [comment] 2021-01-09 16:55
@Glamurio Does it happen in 2.5.4 beta version?

**Comment by Glamurio** [comment] 2021-01-10 15:38
> 
> 
> @Glamurio Does it happen in 2.5.4 beta version?

Just updated, seems like it's fixed from what I can tell.

**Comment by dsapsan** [comment] 2021-01-27 11:51
Fixed (tested in version 2.5.6 beta)

**Comment by Zarezy** [comment] 2021-02-20 18:05
Version 2.5.9 (win) lowers the sounds for all apps even with "Do nothing" and for me it's not restoring the volume back after the call ends. I need to restart apps for them to get their volume back. It happens every time.
