### ISSUE TITLE
Telegram comes to focus when clicking notifications from other applications

### ISSUE THREAD

**Issue by jhasse** [telegramdesktop/tdesktop#3298] opened 2017-04-19 12:16 UTC
### Steps to reproduce
1. Open Telegram and minimize it
2. Get a notification from another program e.g. Firefox
3. Click that notification

### Expected behaviour
The other app should come to the foreground (e.g. Firefox).

### Actual behaviour
Telegram comes to the foreground.

### Configuration
**Operating system:** GNOME Shell 3.24.1 on Linux

**Version of Telegram Desktop:** 1.0.29

**Comment by auchri** [comment] 2017-04-19 12:22
@jhasse Please paste the content of the log here

**Comment by jhasse** [comment] 2017-04-19 12:27
```plain
20170419
[14:23:38.955 00-0000145] Debug logs started. (messenger.cpp : 554)
[14:23:41.861 01-0000146] MTP Info: sending ping_delay_disconnect, ping_id: 16749978934526134402 (connection.cpp : 806)
[14:23:41.878 01-0000148] MTP Info: sending request, size: 34, num: 234738628, time: 1492604466 (connection.cpp : 3031)
[14:23:41.911 01-0000154] Message Info: pong received, msg_id: 6410687367568282556, ping_id: 16749978934526134402 (connection.cpp : 2015)
[14:23:41.911 01-0000155] Message Info: requests acked, ids [6410687367568282556] (connection.cpp : 2128)
[14:23:41.911 01-0000156] Message Info: msgId 6410687367568282556 was not found in recent sent, while acking requests, searching in resend... (connection.cpp : 2167)
[14:23:41.911 01-0000157] Message Info: msgId 6410687367568282556 was not found in recent resent either (connection.cpp : 2197)
[14:23:42.728 00-0000158] MTP Info: adding request to toSendMap, msCanWait 0 (facade.h : 217)
[14:23:42.728 00-0000159] MTP Info: added, requestId 333 (session.cpp : 441)
[14:23:42.728 00-0000160] MTP Info: dcWithShift 4 stopped send timer, can wait for 0ms from current 18266723 (session.cpp : 178)
[14:23:42.728 01-0000161] MTP Info: dc 4 trying to send after ping, state: 2 (connection.cpp : 824)
[14:23:42.728 01-0000163] MTP Info: sending request, size: 18, num: 234738632, time: 1492604466 (connection.cpp : 3031)
[14:23:42.782 01-0000169] RPC Info: response received for 6410687367568282568, queueing... (connection.cpp : 1923)
[14:23:42.782 01-0000170] Message Info: requests acked, ids [6410687367568282568] (connection.cpp : 2128)
[14:23:42.782 01-0000171] MTP Info: will send 1 acks, ids: [6410688040644816897] (connection.cpp : 1481)
[14:23:42.782 01-0000172] MTP Info: emitting needToReceive() - need to parse in another thread, haveReceivedMap.size() = 1 (connection.cpp : 1490)
[14:23:42.782 00-0000173] MTP Info: dcWithShift 4 can wait for 10000ms from current 0 (session.cpp : 174)
[14:23:42.828 00-0000174] RPC Info: parser not found for 333 (mtp_instance.cpp : 759)
[14:23:47.252 00-0000175] MTP Info: dcWithShift 4 stopped send timer, can wait for 0ms from current 18277561 (session.cpp : 178)
[14:23:47.252 01-0000176] Will send ping! (connection.cpp : 1260)
[14:23:47.252 01-0000177] MTP Info: sending ping_delay_disconnect, ping_id: 8437738537549162291 (connection.cpp : 806)
[14:23:47.252 00-0000179] MTP Info: adding request to toSendMap, msCanWait 0 (facade.h : 217)
[14:23:47.252 00-0000180] MTP Info: added, requestId 334 (session.cpp : 441)
[14:23:47.253 01-0000181] MTP Info: sending request, size: 34, num: 234738644, time: 1492604466 (connection.cpp : 3031)
[14:23:47.253 00-0000182] MTP Info: dcWithShift 4 stopped send timer, can wait for 0ms from current 0 (session.cpp : 178)
[14:23:47.253 01-0000184] MTP Info: dc 4 trying to send after ping, state: 2 (connection.cpp : 824)
[14:23:47.253 01-0000186] MTP Info: sending request, size: 18, num: 234738648, time: 1492604466 (connection.cpp : 3031)
[14:23:47.286 01-0000192] Message Info: pong received, msg_id: 6410687367568282572, ping_id: 8437738537549162291 (connection.cpp : 2015)
[14:23:47.286 01-0000193] Message Info: requests acked, ids [6410687367568282572] (connection.cpp : 2128)
[14:23:47.286 01-0000194] Message Info: msgId 6410687367568282572 was not found in recent sent, while acking requests, searching in resend... (connection.cpp : 2167)
[14:23:47.286 01-0000195] Message Info: msgId 6410687367568282572 was not found in recent resent either (connection.cpp : 2197)
[14:23:47.304 01-0000200] RPC Info: response received for 6410687367568282584, queueing... (connection.cpp : 1923)
[14:23:47.304 01-0000201] Message Info: requests acked, ids [6410687367568282584] (connection.cpp : 2128)
[14:23:47.304 01-0000202] MTP Info: will send 1 acks, ids: [6410688060070415361] (connection.cpp : 1481)
[14:23:47.304 01-0000203] MTP Info: emitting needToReceive() - need to parse in another thread, haveReceivedMap.size() = 1 (connection.cpp : 1490)
[14:23:47.316 00-0000204] MTP Info: dcWithShift 4 can wait for 10000ms from current 0 (session.cpp : 174)
[14:23:47.352 00-0000205] RPC Info: parser not found for 334 (mtp_instance.cpp : 759)
[14:23:52.430 00-0000206] MTP Info: adding request to toSendMap, msCanWait 0 (facade.h : 217)
[14:23:52.430 00-0000207] MTP Info: added, requestId 335 (session.cpp : 441)
[14:23:52.430 00-0000208] MTP Info: dcWithShift 4 stopped send timer, can wait for 0ms from current 18282095 (session.cpp : 178)
[14:23:52.430 01-0000209] MTP Info: dc 4 trying to send after ping, state: 2 (connection.cpp : 824)
[14:23:52.430 01-0000211] MTP Info: sending request, size: 30, num: 234738660, time: 1492604466 (connection.cpp : 3031)
[14:23:52.467 01-0000217] RPC Info: response received for 6410687367568282588, queueing... (connection.cpp : 1923)
[14:23:52.467 01-0000218] Message Info: requests acked, ids [6410687367568282588] (connection.cpp : 2128)
[14:23:52.467 01-0000219] MTP Info: will send 1 acks, ids: [6410688082242213889] (connection.cpp : 1481)
[14:23:52.467 01-0000220] MTP Info: emitting needToReceive() - need to parse in another thread, haveReceivedMap.size() = 1 (connection.cpp : 1490)
[14:23:52.467 00-0000221] MTP Info: dcWithShift 4 can wait for 10000ms from current 0 (session.cpp : 174)
[14:23:52.791 00-0000222] RPC Info: found parser for request 335, trying to parse response... (mtp_instance.cpp : 729)
```

**Comment by auchri** [comment] 2017-04-19 12:38
That's the wrong one, there should be a "log.txt" near the bin file.

**Comment by jhasse** [comment] 2017-04-19 12:42
Found it:
```plain
[2017.04.19 14:23:55] Launched version: 1000029, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2017.04.19 14:23:55] Executable dir: /home/jhasse/.local/Telegram/, name: Telegram
[2017.04.19 14:23:55] Initial working dir: /home/jhasse/.local/share/TelegramDesktop/
[2017.04.19 14:23:55] Working dir: /home/jhasse/.local/share/TelegramDesktop/
[2017.04.19 14:23:55] Arguments: "/home/jhasse/.local/Telegram/Telegram" "-noupdate" "-tosettings" "-workpath" "/home/jhasse/.local/share/TelegramDesktop/"
[2017.04.19 14:23:55] Logs started
[2017.04.19 14:23:55] Connecting local socket to /tmp/f25919d2bd97c94b1e365bb5afb353d7-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2017.04.19 14:23:55] This is the only instance of Telegram, starting server and app...
[2017.04.19 14:23:55] Moved logging from '/home/jhasse/.local/share/TelegramDesktop/log_start1.txt' to '/home/jhasse/.local/share/TelegramDesktop/log.txt'!
[2017.04.19 14:23:55] Old start log 'log_start0.txt' found, deleted: [TRUE]
[2017.04.19 14:23:56] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
[2017.04.19 14:23:56] Getting DE, XDG_CURRENT_DESKTOP: 'GNOME'
[2017.04.19 14:23:56] Getting DE, DESKTOP_SESSION: 'gnome-xorg'
[2017.04.19 14:23:56] Getting DE, KDE_SESSION_VERSION: ''
[2017.04.19 14:23:56] DE: Gnome
[2017.04.19 14:23:56] Tray Icon: Try Qt = [TRUE], Prefer appindicator = [FALSE]
[2017.04.19 14:23:56] App Info: reading settings...
[2017.04.19 14:23:56] App Info: reading encrypted settings...
[2017.04.19 14:23:56] OpenAL Logging Level: (not set)
[2017.04.19 14:23:56] Audio Playback Devices: OpenAL Soft
[2017.04.19 14:23:56] Audio Playback Default Device: OpenAL Soft
[2017.04.19 14:23:56] Audio Capture Devices: Monitor of HD-Audio Generic Analog Stereo
[2017.04.19 14:23:56] Audio Capture Default Device: Monitor of HD-Audio Generic Analog Stereo
[2017.04.19 14:23:56] App Info: reading map...
[2017.04.19 14:23:56] App Info: reading encrypted map...
[2017.04.19 14:23:56] App Info: reading encrypted user settings...
[2017.04.19 14:23:56] App Error: attempt to write settings while reading them!
[2017.04.19 14:23:56] App Info: encrypted user settings read.
[2017.04.19 14:23:56] App Info: reading encrypted mtp data...
[2017.04.19 14:23:56] Notifications Server: gnome-shell
[2017.04.19 14:23:56] LibNotify capabilities: actions, body, body-markup, icon-static, persistence, sound
[2017.04.19 14:23:56] MTP Info: read keys, current: 3, to destroy: 0
[2017.04.19 14:23:56] Map read time: 42
[2017.04.19 14:23:56] Using Qt tray icon.
[2017.04.19 14:23:56] Tray Icon: Using Qt tray icon, available: [TRUE]
[2017.04.19 14:23:56] Not using Unity Launcher count.
[2017.04.19 14:29:04] Message Info: bad message notification received (error_code 16) for msg_id = 6410688105666115480, seq_no = 57
[2017.04.19 14:34:41] Message Info: bad message notification received (error_code 16) for msg_id = 6410689427147886948, seq_no = 81
[2017.04.19 14:35:54] Audio Info: recreating audio device and reattaching the tracks
[2017.04.19 14:35:55] Audio Info: closing audio playback device
[2017.04.19 14:39:56] Message Info: bad message notification received (error_code 16) for msg_id = 6410690873765832636, seq_no = 111
```

**Comment by zargex** [comment] 2017-05-08 22:13
Hi, I have this issue too. 

**Configuration**
**Operating system:** Debian 8.8 with KDE 4.14.2
**Version of Telegram Desktop:** 1.0.29

**Comment by thnt** [comment] 2017-06-09 07:14
Same here.
Click to notification of other electron apps(Skype, Caprine,...) will open Telegram from tray icon.
System: openSUSE, KDE 5.10
Telegram Desktop v1.1.17

**Comment by Feichtmeier** [comment] 2017-06-29 11:38
Same here.
Ubuntu 16.04 with GNOME3.20
I receive e-mails with geary and klick the notification and telegram pops up

**Comment by auchri** [comment] 2017-08-10 13:11
Duplicate of #1026

**Closed by auchri** 2017-08-10 13:11 UTC

**Comment by jhasse** [comment] 2017-08-10 13:15
I don't think it is a duplicate, since #1026 is from 2015 and I'm very sure this has only started to happen in recent Telegram versions (some update from this year).

**Comment by auchri** [comment] 2017-08-10 13:16
@jhasse But it's basically the same topic

**Comment by stek29** [comment] 2017-08-10 13:16
Or maybe some update of gnome caused it?

**Comment by john-preston** [comment] 2017-08-10 14:20
@jhasse If you could show the exact version when the problem starts it would be helpful. All versions are available here: https://github.com/telegramdesktop/tdesktop/releases

**Comment by jhasse** [comment] 2017-08-30 12:40
1.0.29 seems to be the first version with the bug. These are the ones I've tested:

1.1.19 bug
1.1.12 bug
1.1.10 bug
1.1.0 bug
1.0.29 bug
1.0.28 working
1.0.27 working
1.0.26 working
1.0.23 working
1.0.18 working
1.0.0 working

**Comment by Feichtmeier** [comment] 2017-09-04 09:57
Update: when you disable the tray icon/background process (i guess)
That behaviour is not there! Clicking notifications normally opens the application which sent the notification
