### ISSUE TITLE
Microphone doesn't work for Audio Calls! It only works with Voice Messages.

### ISSUE THREAD

**Issue by iocomxda** [telegramdesktop/tdesktop#8801] opened 2020-10-11 09:20 UTC
### Steps to reproduce
1. Call someone
2. Try to speak with him
3. Telegram doesn't recognize that the Audio Call is using the Microphone

### Expected behaviour
The microphone should be work and activate its self. (There is no icon in the status bar that show Telegram is using it)

### Actual behaviour
Microphone doesn't work with Audio Call, but it works with Voice Message. It's not a problem of "granted microphone access".

### Configuration
Windows 10

**Version of Telegram Desktop:**
2.4.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Dark mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment] 2020-10-11 09:58
Duplicate of #8443

**Closed** 2020-10-11 10:11 UTC
