### ISSUE TITLE
TDesktop freezes until toast notification disappear (Win10)

### ISSUE THREAD

**Issue by Marocco2** [telegramdesktop/tdesktop#2386] opened 2016-08-27 13:12 UTC
### Steps to reproduce
1. Wait a toast notification
2. Open telegram desktop

### Expected behaviour
Telegram desktop should be running without freezes

### Actual behaviour
Telegram desktop waits (freezes). When the toast notification disappear, TD is back to normal.

When there are a lot of messages, this is a critical bug

### Configuration
**Operating system:**
Windows 10 AU (14393)

**Version of Telegram Desktop:**
0.10.2 alpha

**Comment by T3rminat0r** [comment] 2016-09-03 12:05
This became worse with the latest Win10 Update (Build 1607) to the point where TelegramDesktop stays irresponsive after the notifications have been closed. (especially bad after waking up the PC/Laptop from sleep, and TG scrolling through all the notifications that ran up during the time ...) 

Only way to get it back in working order atm is, to kill it via Taskmanager and restart it ...

**Comment by john-preston** [comment] 2016-09-03 15:56
@T3rminat0r Can you make a dump file from the task manager when it freezes? And send it to me at https://telegram.me/preston, perhaps I could see what is going wrong there.

**Comment by T3rminat0r** [comment] 2016-09-03 15:59
Will do :) thanks

**Comment by Simulacrux** [comment] 2016-09-09 22:54
Hi, 
I have a simular hickup on the current Insider Build of Windows 10 (14915). 
If I start Telegram, it comes around, but no window is shown at all. The Telegram icon is in the Taskbar and in the Infosection. The Taskbar is blinking is a new message arrives and both Icons showing the unread mail Count. But no notification is shown anymore and nothing is getting the Window to show up. 
Started with the last build and didn't go away for this one two.

Could provide an dump too, but think it is working normally in the background, only the window is not showing correctly.

Cheers Simulacrux

**Comment by Lillecarl** [comment] 2016-10-06 12:44
https://github.com/telegramdesktop/tdesktop/issues/2506#issuecomment-251913226

Disabling use windows notifications will "resolve" the issue while it's broken :)

**Comment by Aokromes** [comment] 2016-10-06 12:45
duplicate of #2296 no?

**Closed** 2016-10-06 12:46 UTC
