### ISSUE TITLE
Allow to resize message block in chat window

### ISSUE THREAD

**Issue by f1ztech** [telegramdesktop/tdesktop#2060] opened 2016-05-20 13:09 UTC
Long messages has small width and large height, like a newspaper column. Sometimes It's hard to read such messages, also they take a lot of space on screen and make chat history less usable for me. Besides as a programmer I often send a code snippets in telegram, and it is practically impossible to read them because of small message width. 

 
### Steps to reproduce

Open chat window
### Expected behaviour

User can change width of message with mouse
### Actual behaviour

Message width is fixed
### Configuration

**Operating system:**
Windows
**Version of Telegram Desktop:**
0.9.49

**Comment by eode** [comment] 2016-06-15 15:42
Same issue.  Message width adapts appropriately to narrowing window size, but stops expanding after a certain point.  on my screen (1920x1080), that means messages use only 1/3rd of the available space.  As f1ztech pointed out, this also affects code block comments.

**Comment by lexa971** [comment] 2016-06-24 21:35
Same issue. Very annoying. Must fix it asap please...

**Comment by kotep** [comment] 2016-08-04 18:12
Providing an example of wasted space with fixed message width.
Expected behavior would be message width maximum is maximum width of message pane.  
What's the purpose of maximizing if the messages remain fixed-width?

![untitled-1](https://cloud.githubusercontent.com/assets/7033407/17412897/550c3d10-5a3c-11e6-8c25-ba35fbd9dbd4.jpg)

**Comment by Alukardd** [comment] 2017-01-12 07:14
Version 1.0 released and we still seeing ugly narrow column instead of code block, backtrace, etc...
I can understand such behavior on mobile client, but on my laptop with 2880x1620 resolution it is a absurd!

**Comment by rotanov** [comment] 2017-01-26 10:33
I vouch for this. Was waiting for it so long so I decided to make an issue. Since I didn't found this one.

**Comment by valcker** [comment] 2017-02-02 12:35
+1 for this.

**Comment by francescortiz** [comment] 2017-03-10 11:26
Pasting code becomes really annoying with this limited width. It seems kind of contradictory to have the possibility to quote code but not being able to properly see any line with more than 52 characters. Also, some programming languages don't follow the 80 column styling, so limiting the width is limiting usability.

**Comment by linermgn** [comment] 2017-04-21 12:14
Just do it, please, logs and code blocks looks awfull

**Comment by kotep** [comment] 2017-05-15 12:34
In v1.1, the client now uses more screen space on large windows to display a cluttered and distracting emoji window, and still does not let the message size increase beyond its current width.

**Comment by sbagan** [comment] 2017-05-24 14:06
Yay! Issue is opened for more than one year.
Seriously please fix it

**Comment by proea** [comment] 2017-05-25 11:06
Please fix it!

**Comment by Xorboo** [comment] 2017-06-06 20:07
Please, just add msgMaxWidth into settings, I really dont want to fork and compile telegram by myself just for such minor change. There are actually some chats where people write messages longer than "lol haha funny gif".

**Comment by proea** [comment] 2017-06-08 06:27
Please, make it
@Xorboo made a good suggestion

**Comment by eode** [comment] 2017-08-30 20:42
..just use riot.im, or other matrix.org clients.

**Comment by pztrn** [comment] 2017-11-24 02:10
430px message width in Retina and QHD times.

Guys, please, allow us to use full width of window!

**Comment by OnkelTem** [comment] 2017-12-07 21:32
Thanks you @stek29 for inviting me here, into this thread of grief. What's the point?

It's ridiculous to have an ability to mark text as code which is then gonna be screwed up anyway. I can't even paste two lines of preformatted text w/o it to be rendered to unreadable crap like this:

![asd](https://i.gyazo.com/85976e9882799006c5965c49c5b33a70.png)

I should say that this is not an issue even in Skype.

**Comment by stek29** [comment] 2017-12-07 21:50
@OnkelTem You can use Webogram or even macOS native app (lel) for now as a workaround :)

I understand your points and frustration, but I think John has too much other stuff to do for now :(

**Comment by ezverev** [comment] 2018-01-18 10:26
Any updates on the issue?

**Comment by OnkelTem** [comment] 2018-01-18 11:04
Basically, inability to display preformatted text properly abandons Telegram as an app for developers exchange. So it's not a matter of minor enhancement instead - this is severe issue, a show stopper. How the developers don't grasp this - I have no idea.

**Comment by kotep** [comment] 2018-01-18 13:04
People have referenced this in other issues, because the decision to make the width of messages preposterously small means that either the messages have to stack against the left side of the screen, or they're super spread out with a vast gulf of nothingness between them.  (And you can only toggle the super spread out view if you've currently got a chat open, AND have the window large enough that you can only see the super spread out view.)

Hey, here's an idea: What if the message width is some proportion of the width of the entire message panel, instead of the fixed-width nonsense? That would fit with my intuitive understanding of what should happen when I make a window larger. What's the point of letting me maximize a window if 50% of the visual space is never used?

**Comment by OnkelTem** [comment] 2018-01-18 13:24
> What if the message width is some proportion of the width of the entire message panel, instead of the fixed-width nonsense?

[with good humor] What a fresh idea! :) 
Actually, this how it things done nowadays (er... for the last 15 years actually). Instead having something defined in absolute pixels raises questions. How would feel visually impaired if they want to get text bigger? How would behave an app on a wider/narrower screen?

Agreed 100%.

**Comment by john-preston** [comment] 2018-01-18 13:27
@OnkelTem It is not absolute, but it is fixed for a fixed font size.

**Comment by OnkelTem** [comment] 2018-01-18 13:29
@john-preston Oh, it's not that awful then :)

**Comment by ezverev** [comment] 2018-01-18 14:40
@OnkelTem So what`s about making a settings item for that??

**Comment by FichteFoll** [comment] 2018-01-18 21:50
The only reliable way to have preformatted text display properly and to avoid line break entirely is a textarea with a slider within the message that a user can scroll horizontally. This is used on all discussion platforms on the web, including github itself, and has proven to be simple and usable.

**Comment by ezverev** [comment] 2018-01-19 09:05
@FichteFoll forget preformattet text. It will take ages. Give us the all that easy and simple balloon width regulation.

**Comment by OccultScientist** [comment] 2018-02-16 09:55
Another vote for this please.
Posted code or log files in message is difficult to read. Can we not have a Skype-like click and drag to expand?

**Comment by kirsan31** [comment] 2018-02-16 13:46
The problem exists about for 2 years now (#1587, #1634 etc). And nothing has changed :(

**Comment by OccultScientist** [comment] 2018-02-16 14:55
:(

**Comment by JanBizub** [comment] 2018-08-10 10:38
Please do this. I need to send code to my friends and the width is too small.
I don't need to drag to resize. Something like "full message width" checkbox option in options that makes messages fit full width of window will be enough.

**Comment by banderlog** [comment] 2018-12-05 15:24
Just add some input field in Chat Settings "Max Message Width", or make max message width 80 symbols for Monospace formatted messages, they are usually a some code.

**Comment by lDrakonl** [comment] 2019-01-16 11:10
+1
I need this function!

**Comment by tagsemb** [comment] 2019-10-08 18:44
Please fix this, it's the only real annoyance I have with Telegram at the moment.

**Comment by hackhowtofaq** [comment] 2019-10-09 13:06
I cannot believe that this issue is not yet fixed from 2016....

**Comment by Aokromes** [comment] 2019-10-09 14:09
@hackhowtofaq you are free to create one pull request for it :)

**Comment by hackhowtofaq** [comment] 2019-10-09 15:46
@Aokromes guide me to the code which files need patching and I will do it....

**Comment by av-elier** [comment] 2019-10-09 16:07
@hackhowtofaq, @Aokromes, there was one attempt, rejected: https://github.com/telegramdesktop/tdesktop/pull/2339#issuecomment-240178293

**Comment by kirsan31** [comment] 2019-10-09 18:15
> @hackhowtofaq you are free to create one pull request for it :)

> @Aokromes guide me to the code which files need patching and I will do it....

This PR will be rejected, and Aokromes know it ;)

**Comment by beppe9000** [comment] 2019-10-10 10:33
That PR was hardcoding the change. If a new PR is to be done it must be at least an optional setting. 
Also in the PR comments @john-preston never confirmed if a configurable PR wouldn't be rejected.

**Comment by sgregori** [comment] 2020-01-17 10:28
Awaiting for this PR, for 3 years...

**Comment by kenorb** [comment] 2020-01-24 11:08
Native Telegram for macOS app got this working fine (it expands message blocks). So if you're on macOS, [install native client instead](https://macos.telegram.org/).

**Comment by beppe9000** [comment] 2020-01-24 11:14
We shall continue to suffer. Or use web-based client + css.

**Comment by Aokromes** [comment] 2020-01-26 13:07
imho every input field must be resizeable.

**Comment by VertigoRN** [comment] 2020-03-28 08:01
Up!

**Comment by adrav** [comment] 2020-03-28 13:29
Up!

**Comment by kudlatyamroth** [comment] 2020-04-02 15:44
@john-preston if this PR: https://github.com/telegramdesktop/tdesktop/pull/2339
will be configurable, would you accept it?

**Comment by sadoyan** [comment] 2020-04-07 13:21
Another vote for this after 4 years of existence of this issue . 
Is there a special reason, why you guys are not willing to fix this simple issue and ignore all claims that you have about it ? 
It's really awful to have such space loose and split codes just because of not one knows why .

**Comment by beppe9000** [comment] 2020-04-07 20:46
> 
> 
> @john-preston if this PR: #2339
> will be configurable, would you accept it?

I think there is no way to know until someone tries

**Comment by kudlatyamroth** [comment] 2020-04-08 21:03
ok, i have some work on it.. but it looks like my C++ skill is rusted - almost rotten :P 
here are some changes: https://github.com/telegramdesktop/tdesktop/compare/dev...kudlatyamroth:feature/wide-messages?expand=1

it adds setting checkbox (default unchecked):
![wide_msg_width](https://user-images.githubusercontent.com/2165237/78833147-ae325b80-79ec-11ea-97b0-5ac29683662b.png)

but smth' has broke, as if it is unchecked messages are wider then 430px

if anyone wants to work on it, or have suggestions let me know :)

PS. ideally i think that there should be input or slider with px width or even select like scale setting

**Comment by beppe9000** [comment] 2020-04-08 23:34
I noticed the `AdaptiveForWide` flag. Maybe it is involved somehow?

**Comment by kudlatyamroth** [comment] 2020-04-09 04:43
if Adaptive layout for wide screens is checked it makes chat to display all messages on left side after 880px 
uncheck disables avatars in chat and its always left and right

**Comment by kudlatyamroth** [comment] 2020-04-12 18:30
i wonder why this adaptive checkbox not in official client, as the commits with it dating back in 2016:
https://github.com/telegramdesktop/tdesktop/commit/fc9d75b4f01fed32f3b4d5827ac47c5724ea5787

**Comment by Aokromes** [comment] 2020-04-12 20:37
> i wonder why this adaptive checkbox not in official client, as the commits with it dating back in 2016:
> [fc9d75b](https://github.com/telegramdesktop/tdesktop/commit/fc9d75b4f01fed32f3b4d5827ac47c5724ea5787)

it's when the width of the monitor is high enough.

**Comment by kudlatyamroth** [comment] 2020-04-12 20:40
> > i wonder why this adaptive checkbox not in official client, as the commits with it dating back in 2016:
> > [fc9d75b](https://github.com/telegramdesktop/tdesktop/commit/fc9d75b4f01fed32f3b4d5827ac47c5724ea5787)
> 
> it's when the width of the monitor is high enough.

but there is no switch in settings in official client, but when you compile it, its like on screenshot from my comment (without Wide message width checkbox)

**Comment by adrav** [comment] 2020-05-06 08:35
Guys, I do not understand. New version of desktop telegram added many childish features like "catalog of over 20,000 stickers", "Send a single dart emoji to see if you hit the bullseye." or "Send to any chat to try your luck and get a random number from the animated dice."... Is it still serious communicator or a toy?

I would like to see the new important features like allowing to resize message block in chat window that we are discussing here.

**Comment by sadoyan** [comment] 2020-05-06 09:14
Yes indeed Telegram is becoming a toy for kids, Absence of this feature is making me reconsider using Telegram at all. 

I don;t understand why guys are so unwilling to make this .  Is this that much hard thing ?

**Comment by AlexanderAmelkin** [comment] 2020-05-06 12:50
I second that opinion. I totally don't need stickers, dice or dart. I want configurable text width and programming language syntax highlighting in preformatted text.

**Comment by kudlatyamroth** [comment] 2020-05-06 22:54
I'm not having anything to add new stickers and all of the toys - its nice additions which i like :)

And i think i manage to add this small checkbox to chat settings, and it seems to work :)

**Comment by Aokromes** [comment] 2020-05-07 08:59
> I second that opinion. I totally don't need stickers, dice or dart. I want configurable text width and programming language syntax highlighting in preformatted text.

as for stickers, dice and dart, it's the marketing team witch adds new features platform wide, it's not preston.

**Comment by adrav** [comment] 2020-05-07 09:29
> And i think i manage to add this small checkbox to chat settings, and it seems to work :)

What's next with this change? Do we need to wait for the maintainer to accept it and merge to master? What chances do we have?

**Comment by kirsan31** [comment] 2020-05-07 09:34
> > And i think i manage to add this small checkbox to chat settings, and it seems to work :)
> 
> What's next with this change? Do we need to wait for the maintainer to accept it and merge to master? What chances do we have?

Sadly, but - 0% :(

**Comment by sadoyan** [comment] 2020-05-07 09:40
Do any one knows what the reason for not accepting such an important and wanted patch ? 
It seems that TP developers are making "holy war" against this feature .

**Comment by AlexanderAmelkin** [comment] 2020-05-07 09:40
Guys, I think we all need to go and mark that pull request with a heart or like to let the maintainers see that the users are interested in it!

**Comment by sadoyan** [comment] 2020-05-07 09:41
@AlexanderAmelkin  totally agree. You have my heart :-)

**Comment by pztrn** [comment] 2020-05-07 09:54
Reading a comment by @john-preston in #2339:

> This is not going to be merged, sorry. The layout like "Messages after:" was explicitly avoided by setting the maximum width of the text message bubble, because it is less readable (reading the line up till the end in the right side of the monitor you can't quickly jump to the beginning of the next line, you need to follow all the line back). When you use small width of the message layout it is easy to read.

I think #7822 won't be merged due to that. They're stuck with 1366x768 displays, probably. And doesn't care about all IT guys out there who prefer to read logs properly without breaking their eyes with such forced typography shit.

I hope I'm wrong, actually. Let's see what developers would say.

**Comment by adrav** [comment] 2020-05-07 10:27
But.. that's why we have checkbox here. Unchecked by default.

**Closed** 2020-05-12 07:08 UTC
Labels: enhancement

**Comment by pztrn** [comment] 2020-05-12 07:24
Ah shit, why only monospace blocks? You just decline a very good PR just because it adds a checkbox in settings and keeps behavior identical to current release with small bubbles (unchecked by default)? Seriously?

That's ridiculous. Especially that your commit, @john-preston, fixes only a monospace thing, which is just **a part** of what this issue describing. Please, reopen or fix it like #7822 proposes.

**Comment by kirsan31** [comment] 2020-05-12 07:27
As I [said](https://github.com/telegramdesktop/tdesktop/issues/2060#issuecomment-625142673) - no chance :(

**Comment by ChronosX88** [comment] 2020-05-12 07:46
Lol, funny situation - may be we need to fork tdesktop repo and continue the development without Telegram Developers Team?

**Comment by kirsan31** [comment] 2020-05-12 07:51
> Lol, funny situation - may be we need to fork tdesktop repo and continue the development without Telegram Developers Team? And then we just can sync codebase with upstream.

Already, You can try [this](https://github.com/kirsan31/tdesktop). I did it not only for messages, but for all content and only for adaptive layout (check box must be checked).

**Comment by beppe9000** [comment] 2020-05-12 16:39
somebody hire a community manager for @john-preston 😆

**Comment by kudlatyamroth** [comment] 2020-05-12 17:09
maybe on twitter will be more conclusive response from telegram project: https://twitter.com/KudlatyAmroth/status/1260253898994069504?s=20

**Comment by adrav** [comment] 2020-05-12 19:54
@john-preston could you please comment your decision? Why only monospace?

**Comment by kudlatyamroth** [comment] 2020-05-13 17:54
ok, if anyone wants this, i created AUR package: https://aur.archlinux.org/packages/telegram-desktop-wide/
but it not have checkbox, just set max width to 3840px

**Comment by banderlog** [comment] 2020-05-13 21:09
Personally I don't care about message width if it is not a code. Thus, this update is the most expected one, just wondering, why it took so long?)

**Comment by adrav** [comment] 2020-05-13 21:49
You are right @banderlog. Small steps. I have downloaded 2.1.5 and for sourcecode it is working like a charm!

**Comment by kudlatyamroth** [comment] 2020-05-13 21:54
code is the most wanted, but it looks strange if one msg can be full width, and other can't...
