### ISSUE TITLE
Wrong audio length

### ISSUE THREAD

**Issue by SurDno** [telegramdesktop/tdesktop#5060] opened 2018-08-06 06:25 UTC
Sometimes client may display wrong audio length when it's not playing anything/playing another song. 
![image](https://user-images.githubusercontent.com/35204405/43699965-9c24ecfc-9959-11e8-953b-5c8ce52132cb.png)
No idea if it's an issue with particularly this song or this just happens randomly. Relaunching the client does not help.

**Comment by john-preston** [comment] 2018-08-06 07:31
@SurDno When it’s not playing the duration is taken from the attributes of the document (so it could be displayed even before the file was downloaded). So the problem is in the software that was used to send that file and it filled the attributes wrong.

**Comment by Lonami** [comment] 2018-12-08 22:09
Since this isn't a Telegram Desktop issue shouldn't we close this?

**Comment by SurDno** [comment] 2018-12-09 00:01
TD may still probably find out the duration when playing an audio and then fill it in document, if missing.

**Closed** 2020-01-26 12:36 UTC
