### ISSUE TITLE
[Feature Request] Add support to add extensions(addons) to the client.

### ISSUE THREAD

**Issue by mahdiG** [telegramdesktop/tdesktop#2331] opened 2016-08-07 12:25 UTC
Hi. I would be good if people could create plugins for the client. For example a download manager, media player, a visual sticker creator.

**Comment by auchri** [comment] 2016-08-07 12:27
Duplicate of #472, use template next time.

**Closed by auchri** 2016-08-07 12:27 UTC

**Comment by mahdiG** [comment] 2016-08-07 12:55
> use template next time.
I thought templates were for bugs...
