### ISSUE TITLE
Mouse catched on incomming message

### ISSUE THREAD

**Issue by xstable** [telegramdesktop/tdesktop#24482] opened 2022-05-05 08:07 UTC
### Steps to reproduce

1. Start telegram
2. Wait for incomming messages

### Expected behaviour

Somtimes, Telegram Desktop act strange. 
If a message comes in, the mouse is catched by telegram and switched into "move-window" mode.

### Actual behaviour

Means, If I do write in any other app, and a message comes in, the focus is switched to telegram, the mouse cursor is placed at the top of the window and show the crossed-arrows (move window).
To release it, I have to press ESC, or right mouse button. 

That makes telegram desktop useless for me.

### Operating system

Linux secondone 5.15.32-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64 GNU/Linux

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2022-05-06 04:29
> 3.6.1

Current latest version is 3.7.3

**Comment by jpVm5jYYRE1VIKL** [comment] 2022-05-12 07:53
have same

**Comment by jpVm5jYYRE1VIKL** [comment] 2022-05-15 09:06
same on 3.7.1

**Comment by ilya-fedin** [comment] 2022-05-15 16:54
We're waiting for answer from the issue creator

**Comment by xstable** [comment] 2022-05-16 08:13
> We're waiting for answer from the issue creator

which answer? I didn't see any question.

**Comment by jpVm5jYYRE1VIKL** [comment] 2022-05-16 08:16
I can even add another case window switch to window move mode quite often iver in moment of scrolling up/down

**Comment by ilya-fedin** [comment] 2022-05-16 17:44
> which answer? I didn't see any question.

You need to update to latest version before reporting.

**Comment by jpVm5jYYRE1VIKL** [comment] 2022-05-16 20:08
> > which answer? I didn't see any question.
> 
> You need to update to latest version before reporting. Old versions aren't supported.

I have it with latest . Is it really not enough ?

**Comment by ilya-fedin** [comment] 2022-05-16 20:14
No, it's not

**Comment by xstable** [comment] 2022-05-17 05:15
I've installed latest version now. Have to see if it's still appear (I don't get so much messages via Telegram atm.). 

Wonder why it not the same, if @jpVm5jYYRE1VIKL tell, that he/she have the same issue on the latest version.

@jpVm5jYYRE1VIKL can you reproduce, when does the  "sticky windows focus" Bug appear? Is it always or only at given circumstances at your side?

**Comment by ilya-fedin** [comment] 2022-05-17 05:22
> Wonder why it not the same

I don't want to re-ask all the information required by the issue template

**Comment by ilya-fedin** [comment] 2022-05-17 05:28
> I've installed latest version now.

3.7.5 beta?

**Comment by xstable** [comment] 2022-05-17 05:34
Ok, I see. 
Maybe @jpVm5jYYRE1VIKL will provide it here voluntarily, to see if he has another environment as me. That also might give a better overview what kind of bug this might be (e.g if it's also appears on Windows, etc.).

I do have this Version: 
![image](https://user-images.githubusercontent.com/1778068/168736058-fd7770f8-6a77-448c-b118-801ffef3d07f.png)

BTW: At the changelog site, some Versions seems to be missing?!
https://desktop.telegram.org/changelog

**Comment by ilya-fedin** [comment] 2022-05-17 05:36
Get the binary directly from https://desktop.telegram.org, you will be able to enable beta versions in the settings

**Comment by xstable** [comment] 2022-05-17 06:57
I've upgraded as you said: 
Download the binary, activate beta, run the updater.
![image](https://user-images.githubusercontent.com/1778068/168748074-53787807-8680-4ef2-b5b4-86b7c8c310a9.png)

Now I think I can reproduce the error. 
If I move the window (on same screen, but also between two screens)... and if I then release the mouse button, the "move-cursor" is still activated. 
And even if I've  released the mouse button, the window still follow the cursor movement.
I can quit it, with again clicking left mouse button, or press ESC.

After that, if a notice appears in Telegram, the window is immediately focused, and the "move-cursor" is shown again. And on each movement of the mouse, the telegram window move with the cursor.

@jpVm5jYYRE1VIKL can you agree to this behavior to reproduce it, or is it another way you can reproduce it at your side?

**Comment by ilya-fedin** [comment] 2022-05-17 07:01
Sounds like a duplicate of #10348

**Comment by jpVm5jYYRE1VIKL** [comment] 2022-05-17 07:02
@[xstable](https://github.com/xstable) I can confirm same issue . I also have quite often move window self enabled during mouse wheel usage.

**Comment by xstable** [comment] 2022-05-17 10:10
@ilya-fedin don't think so. On my side, nothing is snapping back. It's only that it's described above.

**Comment by ilya-fedin** [comment] 2022-05-17 10:13
I think though. The fact you hit the same bug in different situation doesn't mean it should have a separate issue.

**Closed** 2022-05-17 19:43 UTC
Labels: bug, duplicate, needs user action
