### ISSUE TITLE
Do not display the white color of the Telegram systemtray icon in the KDE panel

### ISSUE THREAD

**Issue by RasoolSaeedNejad** [telegramdesktop/tdesktop#7821] opened 2020-05-06 22:12 UTC
### Steps to reproduce
1. Set Breeze-Light Theme
2. Set Breeze-Dark Panel
3. Run telegram-desktop

### Expected behaviour
Hello.
when the KDE theme is on the Dark, the icons on all apps turn white, and the telegram turns white.
### Actual behaviour
But if the KDE theme isn't dark, but just a dark panel, all icons will turn white except Telegram!

Screenshot: 
![Screenshot_2020-04-23_203400](https://user-images.githubusercontent.com/56765964/81233358-c4dbca80-900b-11ea-94ef-e11bff4b2a83.png)
![Screenshot_2020-05-07_024442](https://user-images.githubusercontent.com/56765964/81233816-c48fff00-900c-11ea-8806-58956e615583.png)

In this category:
/usr/share/icons/breeze-dark/status/22/
/usr/share/icons/breeze-dark/status/24/
/usr/share/icons/breeze/status/22/
/usr/share/icons/breeze/status/24/

For the Dark panel directory, the Telegram icon is white
For the light panel directory, the Telegram icon is black

But it doesn't matter if I choose Dark or Light. In any case, it shows black.
I darken the icon theme and the black telegram icon remains
Only if the entire system theme is dark, the Telegram icon will be displayed in white.

I even replaced the Telegram icon with a system icon for testing, and again it is displayed in black on the Dark Panel and is not white!

### Configuration
**Operating system:** Ubuntu 20.04 and 20.10

**Version of Telegram Desktop:** 2.0.1 and 2.1.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: distributation package

**Used theme**: Breeze-Light Theme and Breeze-Dark Panel

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment] 2020-05-07 04:38
Duplicate of #7399

**Closed** 2020-05-07 09:03 UTC
