### ISSUE TITLE
[Feature Request] Open post in new simple window

### ISSUE THREAD

**Issue by skurgansky-sugarcrm** [telegramdesktop/tdesktop#10299] opened 2021-02-02 14:19 UTC
### Is your feature request related to a problem?
I would like to read news from channel but it takes long time. I would like to open another channel for a moment and not no lose/forget where i saw older news.

### Describe the solution you'd like
I would like to have possibility to open some post from channel in separate simple window. And have possibility to navigate to different channels in main view.

### Describe alternatives you've considered
navigation history with saved scroll position ?

### Additional context
none.

**Comment by RememberTheAir** [comment] 2021-02-02 14:26
Duplicate of #2105

**Closed** 2021-02-02 14:49 UTC
