### ISSUE TITLE
[Question] Why can't I use Telegram with screen readers?

### ISSUE THREAD

**Issue by MesterPerfect** [telegramdesktop/tdesktop#16091] opened 2021-04-04 22:12 UTC
Hello
I am a blind user
I am using windows8.1 operating system
I cannot use Telegram with screen readers
My screen reader cannot read anything inside the program
Are there solutions?
thanks

**Comment by ilya-fedin** [comment] 2021-04-04 23:37
Duplicate of #476

**Closed** 2021-04-05 03:30 UTC
Labels: question
