### ISSUE TITLE
telgegram-desktop 2.1.0 won't start on XFCE - libQt5Widgets.so.5

### ISSUE THREAD

**Issue by vrms** [telegramdesktop/tdesktop#7714] opened 2020-04-25 07:52 UTC
### Steps to reproduce
1. start telegram-desktop (installed from via snap)
2. 
3. 

### Expected behaviour
program starts

### Actual behaviour
nothing happens when running this via the Desktop Shortcut
in a terminal I get 
```
...
...
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
/snap/telegram-desktop/1557/bin/telegram-desktop: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
```
I believe this may be similar to https://github.com/telegramdesktop/tdesktop/issues/7697#issuecomment-619212964

### Configuration
**Operating system:**
debian 9
xfce 4.12

**Version of Telegram Desktop:**
latest/stable:    2.1.0              2020-04-24 (1557) 68MB -

**Installation source (Linux Only)** :
snap package
**Used theme**:
dark

I have removed and reinstalled the snap package, which did not change anything.
reverting to a previous version `# sudo snap refresh telegram-desktop --revision=1498` does not work neither (not allowed)

**Comment by vrms** [comment] 2020-04-25 12:04
solved it for me by removing the snap telegram and installing from flatpak. I guess the issue is still valid (someone else in the references issue had the same error I believe), so I am not closing this yet.

**Comment by ilya-fedin** [comment] 2020-04-25 16:46
Which kernel version do you have? Snap package now supports 3.17+

**Comment by cca310** [comment] 2020-04-26 01:04
I get the same issue in ubuntu on wayland 19.10

the 2.1.0 doesn't open for me and when I try to launch it from terminal, it says `/snap/telegram-desktop/1557/bin/telegram-desktop: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
`

kernel 5.3.0-46-generic

**Comment by ilya-fedin** [comment] 2020-04-26 01:25
`snap connections telegram-desktop`

**Comment by vrms** [comment] 2020-04-26 01:36
> Which kernel version do you have? Snap package now supports 3.17+
```
uname -a
Linux debian 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
```

**Comment by ilya-fedin** [comment] 2020-04-26 01:39
> snap connections telegram-desktop

.

**Comment by cca310** [comment] 2020-04-26 01:40
> `snap connections telegram-desktop`

did you want me to post that? or am I doing something wrong?

```
cole@Lenovo-Laptop:~$ snap connections telegram-desktop
Interface              Plug                                    Slot                            Notes
alsa                   telegram-desktop:alsa                   -                               -
audio-playback         telegram-desktop:audio-playback         :audio-playback                 -
audio-record           telegram-desktop:audio-record           -                               -
content[gtk-3-themes]  telegram-desktop:gtk-3-themes           gtk-common-themes:gtk-3-themes  -
content[icon-themes]   telegram-desktop:icon-themes            gtk-common-themes:icon-themes   -
content                telegram-desktop:kde-frameworks-5-plug  -                               -
content[sound-themes]  telegram-desktop:sound-themes           gtk-common-themes:sound-themes  -
desktop                telegram-desktop:desktop                :desktop                        -
desktop-legacy         telegram-desktop:desktop-legacy         :desktop-legacy                 -
gsettings              telegram-desktop:gsettings              :gsettings                      -
home                   telegram-desktop:home                   :home                           -
network                telegram-desktop:network                :network                        -
network-manager        telegram-desktop:network-manager        -                               -
opengl                 telegram-desktop:opengl                 :opengl                         -
pulseaudio             telegram-desktop:pulseaudio             :pulseaudio                     -
removable-media        telegram-desktop:removable-media        -                               -
unity7                 telegram-desktop:unity7                 :unity7                         -
wayland                telegram-desktop:wayland                :wayland                        -
x11                    telegram-desktop:x11                    :x11                            -
```

**Comment by ilya-fedin** [comment] 2020-04-26 01:41
> content                telegram-desktop:kde-frameworks-5-plug  -

Plug is not connected for some reason, re-installation should help

**Comment by ilya-fedin** [comment] 2020-04-26 01:45
For manual connection:
`snap connect telegram-desktop:kde-frameworks-5-plug kde-frameworks-5-core18:kde-frameworks-5-slot`

**Comment by proedie** [comment] 2020-04-26 18:22
Hello.

I can reproduce this error on Ubuntu 18.04.

> For manual connection:
> `snap connect telegram-desktop:kde-frameworks-5-plug kde-frameworks-5-core18:kde-frameworks-5-slot`

This results in:
`error: snap "telegram-desktop" has no plug named "kde-frameworks-5-plug"`

Removing the snap and re-installing it **did work**. However, the settings were gone. (The assistant to connect to Telegram was shown again.

More information:
````
$ uname -a
Linux kappa 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ snap connections telegram-desktop 
Interface              Plug                              Slot                            Notes
alsa                   telegram-desktop:alsa             -                               -
audio-playback         telegram-desktop:audio-playback   :audio-playback                 -
audio-record           telegram-desktop:audio-record     -                               -
content[gtk-3-themes]  telegram-desktop:gtk-3-themes     gtk-common-themes:gtk-3-themes  -
content[icon-themes]   telegram-desktop:icon-themes      gtk-common-themes:icon-themes   -
content[sound-themes]  telegram-desktop:sound-themes     gtk-common-themes:sound-themes  -
desktop                telegram-desktop:desktop          :desktop                        -
desktop-legacy         telegram-desktop:desktop-legacy   :desktop-legacy                 -
gsettings              telegram-desktop:gsettings        :gsettings                      -
home                   telegram-desktop:home             :home                           -
network                telegram-desktop:network          :network                        -
network-manager        telegram-desktop:network-manager  -                               -
pulseaudio             telegram-desktop:pulseaudio       :pulseaudio                     -
removable-media        telegram-desktop:removable-media  -                               -
unity7                 telegram-desktop:unity7           :unity7                         -
x11                    telegram-desktop:x11              :x11                            -
````

**Comment by ilya-fedin** [comment] 2020-04-26 18:24
`snap --version`

**Comment by ilya-fedin** [comment] 2020-04-26 18:26
> More information

Looks like output for old for version of the package. Or snapd didn't update connections after package updated, which is even worse.

**Comment by proedie** [comment] 2020-04-29 07:58
Sorry for the delay. I didn't feel like reading my email lately.

> `snap --version`
````
snap    2.44.3
snapd   2.44.3
series  16
ubuntu  18.04
kernel  4.15.0-96-generic
````

**Comment by thiagosanches** [comment] 2020-04-29 20:29
Got the same issue here.
Ubuntu 18.04
Cinnamon 3.6.7

```
uname -a
Linux 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

snap --version
snap    2.44.3
snapd   2.44.3
series  16
ubuntu  18.04
kernel  4.15.0-96-generic

```

**Comment by ilya-fedin** [comment] 2020-04-29 20:37
Oh, I have the same version and update goes ok for me :(
I can't suggest anything except snap package reinstallation and most likely it can be fixed only on snapd side, since the problem in content snap connection which is completely on snapd side :(

**Comment by ilya-fedin** [comment] 2020-04-29 20:40
I wonder how problematically it will be if update snap to kde-applictions-5-qt-5-14-core18 later

**Closed** 2020-05-01 13:30 UTC
