### ISSUE TITLE
Chat Tabs

### ISSUE THREAD

**Issue by specter78** [telegramdesktop/tdesktop#7834] opened 2020-05-08 11:47 UTC
I NEED 2 chats open side-by-side which doesn't seem possible with the present version of the app. Please add a feature whereby multiple chats can be opened in tabs.

**Comment by RememberTheAir** [comment] 2020-05-08 12:24
Kind of duplicate of #2105

**Comment by specter78** [comment] 2020-05-08 12:25
Instead of multiple tabs, multiple instance of the same app can also be a solution.

**Comment by ilya-fedin** [comment] 2020-05-08 13:02
Run tdesktop with different workdir
`Telegram -workdir path/to/workdir`

**Closed** 2020-05-08 13:11 UTC

**Comment by specter78** [comment] 2020-05-08 13:33
> Run tdesktop with different workdir
> 
> `Telegram -workdir path/to/workdir`

Thanks.
