### ISSUE TITLE
Mentions have not a notification system

### ISSUE THREAD

**Issue by FraYoshi** [telegramdesktop/tdesktop#2503] opened 2016-10-05 01:26 UTC
### Steps to reproduce
1. open a supergroup you are in
2. mention someone with "**@**"
3. ask to it if he saw that He has been tagged

### Expected behaviour
it should receive a sort of notification (even muted) that tells about the mention

### Actual behaviour
it only receive a notification even if the chat is muted but have to scroll and search for the mention

### Configuration
**Linux 64**

**Version of Telegram Desktop: 0.10.11**

**Comment by stek29** [comment] 2016-10-06 19:02
> Expected:  should receive a sort of notification
> Actual: receive a notification

Other person should receive notification, and he receives it.
Can't see any issue.

**Comment by FraYoshi** [comment] 2016-10-06 21:53
yes, but there's not an area where to check if anybody tagged me somewhere.. people only receive a notification.. in supergroups, It could be anywhere.. (i.e. 8k messages before) so, as a result, any mention is missed..
It's more a feature suggestion than in issue :)

**Comment by auchri** [comment] 2016-10-06 21:56
Duplicate of #610 then.

**Closed by auchri** 2016-10-06 21:56 UTC
