### ISSUE TITLE
Could not send an empty file Error

### ISSUE THREAD

**Issue by Atmo26** [telegramdesktop/tdesktop#2848] opened 2017-01-14 01:36 UTC
I'm having problems with drag and drop images from Firefox to Telegram Desktop: anytime I try it I get this "Could not send an empty file" and an address to its location on the temp folder. Chrome also doesn't allows for drag and drop at all.

Telegram Desktop 1.0 version.

**Comment by john-preston** [comment] 2017-01-14 07:40
@Atmo26 Thank you for your report. This will be fixed in the next version.

**Comment by Aokromes** [comment] 2017-01-16 10:22
#764 ?

**Comment by yurik94** [comment] 2017-01-16 23:07
+1

Something similar happened to me after copying to the clipboard this string from PHPStorm:

`File::delete(Config::get('paths.annunci') . 43 . "/" . 'img_0.png');`

(Can't send empty file <- translated from italian so it may be not identical)

**Closed** 2017-02-19 11:27 UTC

**Comment by JarrettBillingsley** [comment] 2017-03-08 20:04
Hey, why has this issue been closed? With Telegram Desktop 1.0.14, I can no longer drag and drop at all from either Firefox or Chrome; it just shows a 🚫 on the Telegram window when I drag.

If I copy the image and paste it, I get the same "could not send empty file" error as before.

I'm on Win7 64-bit, Chrome v 56.0.2924.87, Firefox 52.

**Comment by Aokromes** [comment] 2017-03-08 20:06
Because it's duplicate of https://github.com/telegramdesktop/tdesktop/issues/764

**Comment by JarrettBillingsley** [comment] 2017-03-08 20:08
I have been using Telegram for over a year and this problem has only cropped up very recently (like since 1.0). I never had any problems dragging or pasting images before.

**Comment by RiskofStorm** [comment] 2020-10-04 14:02
CentOS 8 bug still remains, with png files 
telegram 2.3.2
