### ISSUE TITLE
Propose: remove onmouseover for emoji window

### ISSUE THREAD

**Issue by bertmsk** [telegramdesktop/tdesktop#2826] opened 2017-01-12 21:20 UTC
It's very annoying especially when trying to hit "scroll to bottom" button which is placed near to "emoji" button.

**Comment by beta** [comment] 2017-01-13 04:02
+1. Hope to have a setting for this. It's really annoying sometimes.

**Comment by notmika** [comment] 2017-01-13 10:23
I never really seem to be moving my mouse over that when trying to reach the "scroll to bottom" thing, but hey, a setting to disable it doesn't hurt.

**Comment by MasterGroosha** [comment] 2017-01-13 10:54
Or maybe add a little timeout like 500ms. Seems enough to move cursor more precisely.

**Comment by ex-asu** [comment] 2017-01-13 12:47
+1. I keep getting the emoji popup when trying to click on the scroll to bottom button.

**Comment by fbt** [comment] 2017-01-13 12:48
+1. I keep getting the emoji popup when trying to click on the scroll to bottom button.

**Comment by DarkDibblez** [comment] 2017-01-16 13:45
+1, it's quite annoying especially on smaller screens with high resolutions.

**Comment by gottesman** [comment] 2017-04-10 16:57
Yes, please. This is just SOOO annoying, specially when there is actually a timeout to close it, when the mouse is not over the emoji icon or emoji window.

**Comment by stek29** [comment] 2017-04-10 16:59
#1333 duplicate

**Closed** 2017-04-10 19:30 UTC

**Comment by ldco** [comment] 2018-07-14 06:31
the issue is still very relevant with version 1.3.10, on july 2018, why is it closed?

**Comment by danarrib** [comment] 2019-01-19 15:38
Ok, it's still a thing. Please PLEASE reopen this issue.
The emoji window mouseover is very annoying. Please make a setting to disable the mouseover or add a 500ms delay to show it up.

**Comment by chilivili** [comment] 2019-01-22 12:05
4 years people ask to do it, stupid developers

**Comment by S-U-M-1** [comment] 2019-03-05 22:32
The main topic of this issue got closed to users as "off-topic". Seriously? When is someone just going to program a tiny 250–500ms delay on the emoji button?

**Comment by vadosnaprimer** [comment] 2019-04-21 06:26
This is not fair. Closing all the duplicate issues linking to the main one, and then silently locking the main one without any response or reasoning being any decisions. If it's something that only "stupid users" ever needed and no developer is ever planning to implement, close the main issue saying "won't fix, get lost". If there's a chance, say there's a chance.

**Comment by ldco** [comment] 2019-04-21 07:18
Yes, It's hard to understand this behavior.
