### ISSUE TITLE
sounds use speakers even with usb headset plugged in

### ISSUE THREAD

**Issue by LiamDawe** [telegramdesktop/tdesktop#1803] opened 2016-03-18 21:59 UTC
As the title says, if I plug in a USB headset (Ubuntu) and set my default audio to it, everything but Telegram uses it. Telegram decides to keep using my speakers.

**Comment by auchri** [comment] 2016-03-18 22:10
Does Telegram use the headset if you restart it?

**Comment by LiamDawe** [comment] 2016-03-18 22:25
Yes it does.

**Comment by auchri** [comment] 2016-03-18 22:28
Duplicate of #776 then :)

**Closed by auchri** 2016-03-18 22:28 UTC
Labels: waiting for answer
