### ISSUE TITLE
[accessibility] Tray icon coloring is broken for the attention state since 2.5.1

### ISSUE THREAD

**Issue by AndydeCleyre** [telegramdesktop/tdesktop#10239] opened 2021-01-27 21:14 UTC
### Steps to reproduce
1. use the systray from plasma desktop
2. use the Tela icon theme, or any providing `telegram-attention-panel.svg` and using color scheme (example below)
3. get messages and watch the tray icon

### Expected behaviour
The themed icon should not turn black, but follow the svg definition (+ desktop color scheme):
![BEFORE](https://user-images.githubusercontent.com/1787385/103310007-953b6180-49e4-11eb-90ef-6a6a95f305e7.png)

### Actual behaviour
1. The themed color is replaced with black, even when displayed on a black background:
![AFTER](https://user-images.githubusercontent.com/1787385/103309621-915b0f80-49e3-11eb-8d44-73544418814d.png)
2. Additionally, a distracting, obscuring, low legibility, unwanted counter badge is placed on top of the icon, but that is tracked by #6721.
3. That unwanted badge does not use the theme colors, instead using harsh white and red.

### Configuration
**Operating system:**
Arch Linux
**Version of Telegram Desktop:**
2.5.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Distribution package
**Used theme**:
Irrelevant for the tray icon, right?

---

EDIT: Sample valid themed icon, using desktop's colors:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" version="1">
 <defs>
  <style id="current-color-scheme" type="text/css">
   .ColorScheme-Text { color:#dfdfdf; } .ColorScheme-Highlight { color:#4285f4; }
  </style>
 </defs>
 <circle style="fill:currentColor" class="ColorScheme-Highlight" cx="6" cy="17" r="2"/>
 <path style="fill:currentColor" class="ColorScheme-Text" d="M 18.687469,18.303647 C 18.988656,17.713495 20.719303,7.6225537 20.966707,5.0140234 21.234358,2.4291929 19.838794,2.9098641 18.554652,3.3465233 15.404153,4.4215289 5.4432767,8.2785986 2.7167917,9.7167145 c -0.671236,0.28127 -0.961371,0.7585015 -0.472969,1.1715565 0.420514,0.350114 1.95926,0.830984 3.200218,1.075015 1.057861,0.323857 1.87956,0.01365 2.638057,-0.418712 1.822812,-1.092109 7.2543803,-4.0650435 7.5468763,-4.2586459 0.292496,-0.1936024 0.612628,0.1656936 0.448928,0.3396304 -0.163701,0.173936 -4.010423,3.6599335 -5.27339,5.2360675 -0.669101,0.866629 -0.649059,1.329311 0.0383,1.8758 1.54204,1.221933 5.662057,4.007627 6.275101,4.176004 0.781724,0.214705 1.239555,0.03683 1.569559,-0.609783 z"/>
</svg>
```

**Comment by ilya-fedin** [comment] 2021-01-27 21:15
#6721

**Comment by AndydeCleyre** [comment] 2021-01-27 21:18
@ilya-fedin AFAIU #6721 is tracking the ability to disable the counter, lost in `2.5.1`. 

While I also wish to disable the counter on the tray icon, *this* issue is about the coloring of the icon, independent of whether or not there's a counter.

**Comment by ilya-fedin** [comment] 2021-01-27 21:18
Coloring of the icon is in responsibility of your icon theme, it is a bug in your icon theme.

**Comment by AndydeCleyre** [comment] 2021-01-27 21:20
No, the icon theme is properly providing colors. Ah, I forgot to include the example icon, I will edit it in above.

**Comment by ilya-fedin** [comment] 2021-01-27 21:22
> No, the icon theme is properly providing colors.

I don't believe this is true. Looking by the screenshot, icon theme provides a black pixmap expecting that plasma will color the icon, but it doesn't do that. So it is a bug in icon theme that it relies on private feature of one DE and it doesn't except that not all applications are a part of that DE.

**Comment by AndydeCleyre** [comment] 2021-01-27 21:27
@ilya-fedin 

Have you actually looked at the included SVG? It prefers desktop theme colors, but also provides default colors that will be used in their absence. So the icon itself **absolutely does not** depend on applications being part of a DE.

Further, the icon theme is *for* a DE. Any given application doesn't need to be part of a DE for the icon theme to target one.

**Comment by ilya-fedin** [comment] 2021-01-27 21:28
> Have you actually looked at the included SVG?

Please test with the official binaryto exclude packaging issues.

**Comment by AndydeCleyre** [comment] 2021-01-27 21:37
Yes, the official binary behaves differently:

No messages:
![image](https://user-images.githubusercontent.com/1787385/106056924-30dff080-60bd-11eb-9262-a09458aa1672.png)
(uses fallback colors, fails to use theme at all)

Attention:
![image](https://user-images.githubusercontent.com/1787385/106056808-10b03180-60bd-11eb-85e6-6e89e6c96529.png)
(uses fallback colors, fails to use theme at all)

At least the distro package gets the no-messages icon right.

FWIW, here's the official Arch package's `cmake` command:

```bash
      cmake . \
          -B build \
          -G Ninja \
          -DCMAKE_INSTALL_PREFIX="/usr" \
          -DCMAKE_BUILD_TYPE=Release \
          -DTDESKTOP_API_ID=611335 \
          -DTDESKTOP_API_HASH=d524b414d21f4d37f08684c1df41ac9c \
          -DTDESKTOP_LAUNCHER_BASENAME="telegramdesktop" \
          -DDESKTOP_APP_SPECIAL_TARGET=""

```

**Comment by ilya-fedin** [comment] 2021-01-27 21:40
> FWIW, here's the official Arch package's `cmake` command:

This is probably a bug in platform theme plugin KDE provides, official binary can't use it since it's static.

**Comment by ilya-fedin** [comment] 2021-01-27 21:42
Looking at the blue attention icon, there are also some bug in Qt svg support

**Comment by ilya-fedin** [comment] 2021-01-27 21:46
> fails to use theme at all

don't understand what you mean by that

**Comment by AndydeCleyre** [comment] 2021-01-27 21:46
I meant "fails to use theme [to get the correct colors] at all"

**Comment by ilya-fedin** [comment] 2021-01-27 21:47
We can't get colors from KDE since it requires linking to KDE libraries

**Comment by ilya-fedin** [comment] 2021-01-27 21:48
@Aokromes this is a packaging issue, you can close the issue

**Comment by AndydeCleyre** [comment] 2021-01-27 21:49
> We can't get colors from KDE since it requires linking to KDE libraries

**Again**, this is **already happening** with proper distro packages.

Currently, **the scheme is used** for no-messages state.

**Comment by ilya-fedin** [comment] 2021-01-27 21:50
> **Again**, this is **already happening** with proper distro packages.

Like I said, distro maintainers installing KDE platform theme plugin. We can't link to it in static binary.

**Comment by AndydeCleyre** [comment] 2021-01-27 21:50
> @Aokromes this is a packaging issue, you can close the issue

So you're saying the package can be configured to use the theme's colors for all state icons, not just no-messages? 

Because if not, this isn't immediately just a packaging issue, because repackaging won't address the problem reported....

**Comment by AndydeCleyre** [comment] 2021-01-27 21:51
This issue is not about the specific case of using a static binary.

**Comment by ilya-fedin** [comment] 2021-01-27 21:52
> This issue is not about the specific case of using a static binary.

This is issue tracker only for official binaries. If you're experiening problems with third-party builds, you should report to bug tracker of these builds.

**Comment by ilya-fedin** [comment] 2021-01-27 21:53
> So you're saying the package can be configured to use the theme's colors for all state icons, not just no-messages?

What are you talking about? I see that the issue is only in arch package and doesn't present in official binary according to the screenshots you provided.

**Comment by AndydeCleyre** [comment] 2021-01-27 21:54
The issue presents *worse* in the official binary!

You are being dishonest in your messaging. As far as I understand, and until you correct/answer me on this, is that "repackaging" will not fix the reported issue. This is a choice of the software itself. IF `TDESKTOP_DISABLE_TRAY_COUNTER` still existed, *maybe* this *would* be a packaging issue.

**Comment by AndydeCleyre** [comment] 2021-01-27 21:56
> I see that the issue is only in arch package

So every other distro package you test is using the desktop's color scheme?

Because if not, either I have failed to communicate the issue, or you are choosing not to understand it.

**Comment by ilya-fedin** [comment] 2021-01-27 21:56
If your point about reverting TDESKTOP_DISABLE_TRAY_COUNTER, this is a duplicate of #6721. It is effectively about this option in the UI.

**Comment by AndydeCleyre** [comment] 2021-01-27 21:56
I think if #6721 were fixed than this could probably be closed. But that issue may not get fixed.

**Comment by ilya-fedin** [comment] 2021-01-27 21:59
> So every other distro package you test is using the desktop's color scheme?

I didn't test anything other. I'm judging by your screenshots. You provided a screenshot with black broken icon on arch package and a screenshot with the proper colors from the icon theme (according to what I see in SVG viewer on my machine) on official binary. So this is a pacakging issue.

**Comment by AndydeCleyre** [comment] 2021-01-27 22:02
In the context of a plasma desktop environment, a "proper" color is that specified by the theme's icon + the color scheme. This is not a packaging issue unless you can demonstrate that packaging can fix it.

**Comment by ilya-fedin** [comment] 2021-01-27 22:06
Quoting myself:

> Coloring of the icon is in responsibility of your icon theme, it is a bug in your icon theme.

I see that official binary correctly uses colors from the icon itself, so if it is not as you want, it is a bug of the icon theme.

**Comment by ilya-fedin** [comment] 2021-01-27 22:08
> This is not a packaging issue unless you can demonstrate that packaging can fix it.

packaging issue is about situation when packaging _breaks_ something, not fixes.

**Comment by AndydeCleyre** [comment] 2021-01-27 22:09
I believe the example icon is correctly leaning on the user's color scheme. You say that icon has a bug, which to me means there is a more correct way *to use the user's color scheme*? Do you know of such a way? Or are we still miscommunicating?

**Comment by ilya-fedin** [comment] 2021-01-27 22:10
We don't use any color schemes. We support only XDG specification, it doesn't say about any color schems. We never claimed that we support KDE's color scheme feature, this is not a bug.

**Comment by AndydeCleyre** [comment] 2021-01-27 22:16
It does not matter to me if the developers consider this a bug or a feature request. The UX is broken and I'm interested in a fix.

**Comment by ilya-fedin** [comment] 2021-01-27 22:18
Looks like the only way to fix the UX is to remove icon theme feature. Since linking to KDE library mess is not a way.

**Comment by ilya-fedin** [comment] 2021-01-27 22:31
Well, this is not an issue in 2.5.6 and since we close issues that have a fix in dev branch, this issue should be closed.

**Closed** 2021-01-27 22:40 UTC

**Comment by AndydeCleyre** [comment] 2021-02-11 22:20
Just confirming now that 2.5.8 is out that yes, it does fix the reported issue.

I did not change the icon theme, only the telegram version, and #6721 is still open, so I still do not believe any of these claims from this discussion:

> Duplicate of #6721

>  it is a bug in your icon theme.

>  icon theme provides a black pixmap

> it is a bug in icon theme that it relies on a private feature of one DE and it doesn't except that not all applications are a part of that DE.

> This is probably a bug in platform theme plugin KDE provides

> this is a packaging issue

> the issue is only in arch package and doesn't present in official binary according to the screenshots you provided.

> It is effectively about this option in the UI.

> So this is a pacakging [sic] issue.

> it is a bug of the icon theme.

> the only way to fix the UX is to remove icon theme support.
