### ISSUE TITLE
Add more emoji replacement options (Feature Request)

### ISSUE THREAD

**Issue by elisaado** [telegramdesktop/tdesktop#4370] opened 2018-01-31 17:07 UTC
I'd like an option that makes tdesktop replace `:heart:` but not `<3`.
FYI: If I disable "Replace emoji",  `:heart:` will also not replace.

Thanks!
,
Eli

**Comment by RememberTheAir** [comment] 2018-01-31 17:15
Duplicate of #3738

**Closed** 2018-01-31 17:22 UTC
