### ISSUE TITLE
snap revision 1666 on ubuntu 18.04 doesn't work

### ISSUE THREAD

**Issue by luisguillenc** [telegramdesktop/tdesktop#8010] opened 2020-06-06 19:06 UTC
I revert to revision 1634 and it works again. Please don't upgrade to a stable version if no tests have been done before.

Thanks.

### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment] 2020-06-06 21:56
You even didn't provide any info, I can't reproduce: runs just fine for me

**Comment by ilya-fedin** [comment] 2020-06-07 18:28
I suppose this is a duplicate of #8012

**Closed** 2020-06-07 18:31 UTC
