### ISSUE TITLE
Telegram doesn't connect after Mac goes to sleep

### ISSUE THREAD

**Issue by kolyasya** [telegramdesktop/tdesktop#17397] opened 2021-12-14 09:06 UTC
### Steps to reproduce

1. Run Telegram
2. Put Mac into sleep mode (wait for a while)
3. Wake up Mac — Telegram has a Connecting... spiner at the left bottom corner and never connects until Telegram app restart.

### Expected behaviour

It should successfully reconnect

### Actual behaviour

So this is happening across all of my Mac computers so probably it isn't related to some particular machines or settings.
It is happening for a long time already, I just now decided to report this as a bug.

Here are my sleep settings

![image](https://user-images.githubusercontent.com/3371143/145967393-01f74182-42e6-4688-952f-bdb29a7d127d.png)

### Operating system

MacOS

### Version of Telegram Desktop

3.2

### Installation source

Static binary from official website

**Comment by andrezaycev** [comment] 2021-12-19 06:06
+1

**Comment by yzelensky** [comment] 2021-12-21 11:00
+1
As a quick workaround I used to go in proxy setting and change any setting back and forth (proxy/noptoxy or ip6 support on/off) but it is quite annoying, and you always have a chance to forget to do it and miss some messages or suddenly discover  that your message was not even been sent while you already looking for an answer for hours. Thank you @kolyasya for reporting this problem.

**Comment by soren121** [comment] 2021-12-23 16:39
This happens to me too. Are you using an M1 Mac by chance? I'm wondering if this has something to do with how those keep network connections alive in sleep mode.

**Comment by kolyasya** [comment] 2021-12-27 10:13
> o with how those keep network connections alive in sleep mode.

I do use both: Intel and M1 chips. Happens on Intel the same way.

**Comment by fdterr** [comment] 2021-12-29 03:46
+1 from me

**Comment by niklzz** [comment] 2021-12-29 22:50
+1

**Comment by kromuch** [comment] 2022-01-19 08:15
+1

**Comment by kwerty** [comment] 2022-01-23 07:19
+1

**Comment by xelfer** [comment] 2022-01-26 21:24
+1 Happens every day on my M1 Max. Would love a fix.

**Comment by fdterr** [comment] 2022-01-26 22:03
> +1 Happens every day on my M1 Max. Would love a fix.

I would highly recommend [Telegram for macOS](https://macos.telegram.org/) - the issue completely went away.

**Comment by kolyasya** [comment] 2022-02-11 14:06
Any plans on fixing this? Really annoying issue

**Comment by juahan** [comment] 2022-02-17 07:50
Same thing happens for me in Ubuntu 21.10 as well, although has happened since several versions.

**Comment by conorahern8** [comment] 2022-07-15 16:42
Just wanted to say +1 on this, still happening on latest version on both Intel and M1 MacBook Pros.

**Comment by fdterr** [comment] 2022-07-15 16:43
I would suggest that everyone who is able switch to [Telegram for MacOS](https://macos.telegram.org/). 

The team that maintains the main Telegram app clearly does not care to fix this bug

**Comment by conorahern8** [comment] 2022-07-15 17:04
I'm not interested in the macOS app, I much prefer Telegram Desktop.

The bug is annoying but relatively minor, as it can be fixed by just restarting the app after sleep. The team has 700+ other open issues right now and is probably overworked, comments like this are not helpful or productive.

**Comment by fdterr** [comment] 2022-07-15 17:06
I pity you if you think this will be fixed any time soon

**Comment by conorahern8** [comment] 2022-07-15 17:22
@john-preston I haven't had a chance to look at the code yet, but I currently work with Qt. Are you using the QTcpClient to maintain connections to Telegram's servers? Maybe the solution is to sometimes try deleting and creating a new client when resuming from sleep.

**Comment by john-preston** [comment] 2022-07-15 17:48
@conorahern8 Both, QTcpSocket and QNetworkAccessManager, used for MTProto connections, are re-created from scratch on every attempt to connect.

**Comment by ilya-fedin** [comment] 2022-07-23 01:52
> Both, QTcpSocket and QNetworkAccessManager, used for MTProto connections, are re-created from scratch on every attempt to connect.

It won't be re-created if the socket hangs in a request, though?

> Maybe the solution is to sometimes try deleting and creating a new client when resuming from sleep.

How to check whether resuming from sleep happened? I guess we need a cross-platform solution here as the bug is reproducible on all three systems (an issue about this is created like every month I think and I think I saw multiple issues for every system, most of them are closed by stale bot due to the lack of activity I guess or as duplicates).

**Comment by ilya-fedin** [comment] 2022-07-23 01:53
I found at least one more opened issue about this: #16647

**Comment by ilya-fedin** [comment] 2022-07-23 02:00
And one more: #16093

**Comment by ilya-fedin** [comment] 2022-07-23 02:02
So maybe it's some Qt regression happened between Qt 5.12 and 5.15 and is still not fixed in 6.3, but somewhere in cross-platform networking code rather than Windows thread management

**Comment by ilya-fedin** [comment] 2022-07-23 02:04
Oh, looking further, maybe it's even something that always has been since first version: #5790, #3871, #536

**Comment by conorahern8** [comment] 2022-07-23 02:08
I was trying to get the current code and build it before I started looking into the problem, but I was having issues completing the build as mentioned here: https://github.com/telegramdesktop/tdesktop/issues/24801

**Comment by ilya-fedin** [comment] 2022-07-23 02:14
Unfortunately, I have no idea how to help you as I'm a Linux user and Linux build process is completely different. But the error doesn't look like x86_64 is the problem (it should build both version I think, so should be completely expected). This is apparently something specific to crashpad. It also looks like it's just a warning (maybe some incompatibility between new compiler and old breakpad version?), but it's building with -Werror, so some breakpad patching (e.g. removing -Werror) may help.

**Comment by ilya-fedin** [comment] 2022-07-23 02:15
There's also #24630 that doesn't seem report the same thing initially, but people seem to use it discuss the same thing actually.

**Comment by ilya-fedin** [comment] 2022-07-23 02:16
I believe #16093 is enough

**Comment by conorahern8** [comment] 2022-07-23 02:23
> some breakpad patching (e.g. removing -Werror) may help.

Okay thanks, I'll try that. If not I can try getting a build up in a VM.

**Comment by ilya-fedin** [comment] 2022-07-23 02:32
I also see a suspicious thing i your log: the warning is from file_id.cc, while it says it failed to build macho_walker.cc. So maybe you haven't grabbed actual error that lead to build error.

**Comment by Aokromes** [comment] 2022-07-23 07:00
https://github.com/telegramdesktop/tdesktop/issues/16093

**Closed by Aokromes** 2022-07-23 07:00 UTC
Labels: bug, 3rd party issue
