### ISSUE TITLE
Cannot paste image on Telegram Desktop on Linux

### ISSUE THREAD

**Issue by milankragujevic** [telegramdesktop/tdesktop#7223] opened 2020-02-16 17:02 UTC
### Steps to reproduce
1. Right click on an image in Chrome and select Copy image
2. Control + V into Telegram

### Expected behaviour
Send image dialog shoud appear and the image can be sent.

### Actual behaviour
Usually nothing, sometimes after pressing CTRL + V dozens of times it will paste the image. Sometimes it pastes a link even though I selected Copy image and not Copy image address (checked multiple times).

Note: This was described here: https://github.com/telegramdesktop/tdesktop/issues/1892 and here: https://www.reddit.com/r/ManjaroLinux/comments/bm2soh/telegramdesktop_does_no_paste_images_from/

### Configuration
**Operating system:** Linux Mint 19.3 x64 (Cinnamon edition)

**Version of Telegram Desktop:** 1.9.13

**Used theme**: N/A

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/4210300/log.txt)
</details>

**Comment by twiclo** [comment] 2020-03-02 15:58
This happens for me as well. I've experienced it on Fedora with I3, KDE, and cinnamon.

When I paste it will paste the URL. If I spam paste it will eventually get it right and paste the image

**Comment by Aokromes** [comment] 2020-03-10 21:08
https://github.com/telegramdesktop/tdesktop/issues/6952 ?

**Comment by twiclo** [comment] 2020-03-10 21:10
> #6952 ?

It hasn't failed for me

**Comment by ilya-fedin** [comment] 2020-03-16 10:32
Might be related, can you run telegram from terminal an check?
https://bugreports.qt.io/browse/QTBUG-73044

**Comment by abashurov** [comment] 2020-04-04 08:55
It doesn't report such errors into console. Also, the bug is marked as fixed in Qt 5.13, but it reproduces on https://www.archlinux.org/packages/community/x86_64/telegram-desktop/, which is build against Qt 5.14.
And, for some reason, it works properly once you start telegram-desktop under strace

**Comment by Akhlys** [comment] 2020-04-06 11:49
I had this problem as well, so I could see it being related to #6952, just without crashing the image source. Happened for me with firefox mostly.

purely from memory (not currently on a linux system to test) but I remember that once I tried pasting 30 times in quick succession hoping one of the pastes would bring the dialog up, and that resulted in heavy CPU load (but I don't remember if from TG or from the browser)

**Comment by mumbleskates** [comment] 2020-04-13 06:19
This happens to me as described for weeks now. It is at least most noticeable with Chrome, and the images can always be gotten into Telegram when holding down Ctrl+V so that it rapidly repeats.

Images will also frequently fail to completely send, sometimes a dozen or more times in a row, but it's unclear if this is related.

**Comment by gorghino** [comment] 2020-05-26 09:59
I have the same bug with Elementary OS 5.1.4 Hera and Chrome on Telegram 2.1.7.
Linux version: 4.15.0-99-generic
GTK version: 3.22.30

I made a couple of tests on #7880 finding that e.g. Facebook's rounded profile picture are pasted without any problem but the bug happens with their squared big version.
It also happens copying a Skype (8.60.0.76) group chat image to Telegram sometimes.

**Comment by ilya-fedin** [comment] 2020-05-26 10:16
As you can see, there is nothing to fix: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/history_widget.cpp
Probably it is a GTK<->Qt protocol bug.

**Comment by ilya-fedin** [comment] 2020-06-08 18:28
Most likely, this is the cause of the bug: https://bugreports.qt.io/browse/QTBUG-56595

**Comment by olegon-ru** [comment] 2020-06-09 19:01
Is any workaround of this bug? Some users said, that it's no problem to copy-paste...

**Comment by ilya-fedin** [comment] 2020-06-09 19:04
> Is any workaround of this bug?

No workaround. Until bug would be fixed on Qt side, clipboard will work unstable with non-Qt apps.

**Comment by olegon-ru** [comment] 2020-06-09 19:11
Excuse me, but Firefox is not Qt-app, but it's no problem with it... Are you sure, that it's bug, described by link, you provided above?

**Comment by ilya-fedin** [comment] 2020-06-09 19:13
> Excuse me, but Firefox is not Qt-app, but it's no problem with it

I have problems when copying big images from firefox, it doesn't work all the time

**Comment by ilya-fedin** [comment] 2020-06-09 19:18
> Are you sure, that it's bug, described by link, you provided above?

The bug describes that other app crashes with BadWindow error on pasting (as gimp or xclip in this issue), but if that other app handles the BadWindow error (like chrome), the image just won't paste

The bug definitely looks like the right one
However, there are nothing that can be fixed on tdesktop side, since all the work with clipboard is calling Qt's QMimeData::imageData API

**Comment by ilya-fedin** [comment] 2020-06-11 10:42
@olegon-ru maybe you? :thinking:

**Comment by olegon-ru** [comment] 2020-06-11 11:03
@ilya-fedin excuse me, but I'm too busy to make and test package for my Fedora...
Nowadays, I using workaround for mass pic sending by app in Chrome:
https://chrome.google.com/webstore/detail/telegram/clhhggbfdinjmjhajaheehoeibfljjno
And continue using standart tdesktop from rpm-fusion (repo for Fedora).

**Comment by ilya-fedin** [comment] 2020-06-11 11:08
> excuse me, but I'm too busy to make and test package for my Fedora...

you can just download the artifact and test it
It is debug build and won't change the settings of your main tdesktop instance (it places data in the same directory where the binary is placed)

**Comment by olegon-ru** [comment] 2020-06-11 12:29
I tested artifact and it works with images copy-past well.

**Comment by ilya-fedin** [comment] 2020-06-11 12:32
> I tested artifact and it works with images copy-past well.

 thanks for testing

**Closed** 2020-06-17 16:34 UTC
Labels: 3rd party issue, bug

**Comment by jjolmo** [comment] 2020-07-11 10:35
Maybe it is just coincidence but your build @ilya-fedin works for me too. Can send big images (was ever an issue) and copy directly images from chrome without having issues. I'll test it further

**Comment by ilya-fedin** [comment] 2020-07-11 12:55
The fix is already in release builds

**Comment by gorghino** [comment] 2020-08-27 13:54
This bug happens again with Telegram 2.3.2 on Elementary OS.
To test:
I can copy/paste this picture from Facebook (https://www.facebook.com/deadmau5/posts/10157010537351806:0)
but I can't copy/paste this one (https://www.facebook.com/photo/?fbid=10157010536736806&set=a.442424616805)

**Comment by kav2k** [comment] 2020-08-31 08:22
Possibly related: https://bugs.chromium.org/p/chromium/issues/detail?id=1114385

**Comment by crystaldaking** [comment] 2020-10-22 10:37
Same problem on Gnome
