### ISSUE TITLE
Segmentation fault when using Reply

### ISSUE THREAD

**Issue by drusklo** [telegramdesktop/tdesktop#2007] opened 2016-05-09 15:57 UTC
Every time I use the reply button to answer anyone, I get a Segmentation fault (core dumped)
I click on Replay and after I have written a few words it crashes, this happens every time, it happened to me with the stable version and keeps happening with the Dev Version.

## Configuration
OS: Manjaro Linux
Kernel: 3.14.67-1-MANJARO
DE: Xfce

### Telegram Version: 0.9.47 alpha

This is the output of the terminal where I got Telegram running

`./Telegram 
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fb3640042c0] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[h264 @ 0x7fb364003860] Warning: not compiled with thread support, using thread emulation
[h264 @ 0x7fb364003860] Warning: not compiled with thread support, using thread emulation
[swscaler @ 0x7fb3640d38d0] No accelerated colorspace conversion found from yuv420p to bgra.
Segmentation fault (core dumped)
`

And this is one of the Telegram Crash Logs before being sent

ApiId: 2040
Binary: Telegram
Launched: 05.05.2016 14:43:02
Platform: Linux64bit
UserTag: 2e26540246fd3220
Username: _not_included_
Version: 9047 alpha

Caught signal 11 (SIGSEGV) in thread 140472819947456

Backtrace:
/home/xose/Telegram/Telegram(_ZN14SignalHandlers8internal7HandlerEiP7siginfoPv+0x172)[0x88e8e2]
/usr/lib/libpthread.so.0(+0x10e80)[0x7fc25f203e80]
[0x1]
/home/xose/Telegram/Telegram[0x1b32f85]
[0x1]
/home/xose/Telegram/Telegram[0x1b32f85]
/home/xose/Telegram/Telegram[0xe18f9e]
/home/xose/Telegram/Telegram[0xe1925b]
/home/xose/Telegram/Telegram[0x1192876]
/home/xose/Telegram/Telegram(_ZN14QXcbConnection14handleXcbEventEP19xcb_generic_event_t+0x710)[0x11b7af0]
/home/xose/Telegram/Telegram(_ZN14QXcbConnection16processXcbEventsEv+0x353)[0x11b9593]
/home/xose/Telegram/Telegram[0x1b6030a]
/home/xose/Telegram/Telegram[0xe603bc]
/home/xose/Telegram/Telegram[0xe64958]
/home/xose/Telegram/Telegram[0x1b330d8]
/home/xose/Telegram/Telegram[0x1b35c73]
/home/xose/Telegram/Telegram[0x1b81fe3]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7fc25f459f07]
/usr/lib/libglib-2.0.so.0(+0x4a160)[0x7fc25f45a160]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fc25f45a20c]
/home/xose/Telegram/Telegram[0x1b82727]
/home/xose/Telegram/Telegram[0x1b30e55]
/home/xose/Telegram/Telegram[0x1b3961c]

Google Breakpad caught a crash, minidump written in thread 140472819947456
Minidump: /home/xose/.TelegramDesktop/tdata/dumps/51c20bfe-c079-8c49-4ba964ee-366194e1.dmp

Backtrace:
/home/xose/Telegram/Telegram(_ZN14SignalHandlers8internal7HandlerEiP7siginfoPv+0x172)[0x88e8e2]
/home/xose/Telegram/Telegram(_ZN14SignalHandlers8internal12DumpCallbackERKN15google_breakpad18MinidumpDescriptorEPvb+0x2e)[0x88f16e]
/home/xose/Telegram/Telegram(_ZN15google_breakpad16ExceptionHandler12GenerateDumpEPNS0_12CrashContextE+0x3d4)[0xe48aa4]
/home/xose/Telegram/Telegram(_ZN15google_breakpad16ExceptionHandler13SignalHandlerEiP7siginfoPv+0x97)[0xe48db7]
/usr/lib/libpthread.so.0(+0x10e80)[0x7fc25f203e80]
/home/xose/Telegram/Telegram[0x1b32f85]
/home/xose/Telegram/Telegram[0xe18f9e]
/home/xose/Telegram/Telegram[0xe1925b]
/home/xose/Telegram/Telegram[0x1192876]
/home/xose/Telegram/Telegram(_ZN14QXcbConnection14handleXcbEventEP19xcb_generic_event_t+0x710)[0x11b7af0]
/home/xose/Telegram/Telegram(_ZN14QXcbConnection16processXcbEventsEv+0x353)[0x11b9593]
/home/xose/Telegram/Telegram[0x1b6030a]
/home/xose/Telegram/Telegram[0xe603bc]
/home/xose/Telegram/Telegram[0xe64958]
/home/xose/Telegram/Telegram[0x1b330d8]
/home/xose/Telegram/Telegram[0x1b35c73]
/home/xose/Telegram/Telegram[0x1b81fe3]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7fc25f459f07]
/usr/lib/libglib-2.0.so.0(+0x4a160)[0x7fc25f45a160]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fc25f45a20c]
/home/xose/Telegram/Telegram[0x1b82727]
/home/xose/Telegram/Telegram[0x1b30e55]
/home/xose/Telegram/Telegram[0x1b3961c]
/home/xose/Telegram/Telegram(main+0xa0)[0x67b6c0]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7fc25e957710]
/home/xose/Telegram/Telegram[0x6901bd]

**Comment by Aokromes** [comment] 2016-05-09 16:10
I suggest you to compile telegram on debug mode.

**Comment by drusklo** [comment] 2016-05-09 16:53
Is any way to get a Teleram binary with debug mode enabled?

**Comment by drusklo** [comment] 2016-05-09 16:58
I have enabled debug mode typing "debugmode" on settings, does this counts?

**Comment by stek29** [comment] 2016-05-10 20:54
I think so.

**Comment by drusklo** [comment] 2016-05-11 14:11
@stek29 I've already have the Alpha Version 0.9.48 with debug mode enabled

**Comment by john-preston** [comment] 2016-06-23 15:59
When you press Reply and start typing the words, does the cursor blink in the message input field? Because crashes are somehow Qt-related, and as I see they happen when an unfocused input field starts to receive compose keys input. I can't reproduce that myself in Manjaro Xfce :( So I have two questions:

1. Does the cursor blink after the Reply is pressed? (as I understand in the not-focused input field it won't blink)
2. Do the letters appear there before it crashes? (for example, if you choose english keyboard layout and just type english letters -- without dead keys, compose keys, accents etc) does it work fine with english letters?
3. Does it crash only when you use some complex input method (like dead keys or compose keys)?

Can you please submit a crash report (which will be offered when it crashed and then launched again) and copy a "Crash Report Tag" here (it will be shown in the crash report window).

**Comment by john-preston** [comment] 2016-06-24 18:26
The crash should be fixed in 0.9.55, but I'm afraid the symbols are not appearing in the field :(

**Closed** 2016-06-26 17:16 UTC
