### ISSUE TITLE
Uploading files/images on different chats wait for each other

### ISSUE THREAD

**Issue by sh4dowb** [telegramdesktop/tdesktop#24102] opened 2022-02-22 15:38 UTC
### Steps to reproduce

1. Start the upload of a big file, like 100 MB, on chat X
2. Then send your friend Y a small file, or a compressed image.
3. Small file / image to friend Y will be uploaded after big file on X finishes uploading.

### Expected behaviour

Start uploading immediately on different chats, or for compressed images, or small files. (async)

### Actual behaviour

Small file or image on chat X waits for big file upload on another chat Y to finish.

### Operating system

Ubuntu 20.04.3 LTS

### Version of Telegram Desktop

3.5.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment] 2022-02-22 17:10
not a bug, and duplicate of another ticket i cannot remember.

**Closed by Aokromes** 2022-02-22 17:10 UTC
Labels: bug
