### ISSUE TITLE
Bulk download images

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1382] opened 2015-12-12 13:17 UTC
For example my friend upload and send me 10 pictures to me. Please provide an option to download all of them together, not one by one.

**Comment by amiremami** [comment] 2016-03-04 14:57
@auchri is it possible to add this feature? Takes so much time to download one by one.

**Comment by Aokromes** [comment] 2016-04-20 09:57
#809 ?

**Comment by auchri** [comment] 2016-04-20 10:59
@Aokromes it's related to #809, but it's not the same.

**Comment by amiremami** [comment] 2016-06-22 19:50
My sister sent me 100 photos from the trip we went and I wasn't able to download the images one by one! So she emailed me. Here is a real situation when telegram lacks this feature.

**Comment by amiremami** [comment] 2016-10-03 14:30
Please provide this feature, this is really practical. Thanks.

**Comment by qgates** [comment] 2017-01-11 01:34
+1. Would find this really useful, especially on desktop. I'd like to see this ability for selecting and downloading multiple images, non-compressed images and files.

Getting a bunch of pictures or files out of the telegram ecosystem is a PITA at the moment.

**Comment by kyle-miller** [comment] 2017-02-05 04:20
+1 For a useful feature.

**Comment by eziel** [comment] 2017-02-05 18:36
+1, please add this option. (or allow to save all images just like the video's are being saved automatically)

**Comment by raelmiu** [comment] 2017-02-20 09:26
+1 this would be really great at times.

**Comment by MasterGroosha** [comment] 2017-03-02 13:00
@amiremami I know this is a dumb workaround, but:
1) Set "Default download path" to the folder you want your photos to be downloaded.
2) Open the most recent photo in a batch.
3) Hover mouse over "Download" icon.
4) Now repedeately press "Left" (or "Right", I don't remember) on keyboard and click left mouse button.

This is the fastest (IMO) method (~2 photos per second) to bulk download images.

**Comment by amiremami** [comment] 2017-03-02 15:08
Hey @MasterGroosha thanks a lot for this trick. Yeah it works, or we can use gmail for sending images, much more easier! 

Hope Telegram adds this feature 😞

**Comment by Speeddymon** [comment] 2017-07-03 20:56
Upvote from me. Android has an option to auto save all images to gallery, but that feature is missing on Windows (PC) version. Would like to be able to auto save all images on PC so that I can avoid filling up my sd card, as I have a 36 terabyte NAS server which I can save images to instead.

**Comment by anfimovir** [comment] 2017-08-13 18:57
+1

**Comment by pedrogarcia** [comment] 2017-09-12 23:45
I thought it already was possible, was surprised it was not.
Ideally, what I would like to do is to select a few pictures/messages and right click > save image as...
Saving to the default download folder is limited to the current image being viewed, and for a  Telegram Desktop folder with a lot of files it is really inconvenient to have to look and find the ones I want right now.

**Comment by danger89** [comment] 2017-09-30 23:15
yep, I really need this feature now. I need to download 40+ images...

**Comment by ashinkov** [comment] 2017-10-12 00:07
wow 2017 is here :) I am amazed. 5 clicks per photo to save it to the default location.

**Comment by Julian1984** [comment] 2018-02-01 10:33
Just an up to this enhancement. It's necessary to get this option and it should't be very difficult to implemnt...

**Comment by Zebradil** [comment] 2018-02-03 22:32
Quick tip. It is possible to download media with small python script.

1. Goto https://my.telegram.org and generate api id and api hash
2. Install [Telethon library](https://github.com/LonamiWebs/Telethon) with `pip3 install telethon`
3. Run following code (replace `api_id`, `api_hash` and `username` with your values):
```python
from telethon import TelegramClient
api_id=123456
api_hash='secretHashYO'
client = TelegramClient('test_session', api_id, api_hash)
client.start()
for message in client.get_message_history('username', limit=25):
    client.download_media(message)
```

This code downloads media from the last 25 messages from the dialog with `username` user.

**Comment by moham96** [comment] 2018-02-22 05:49
This would be extremely useful not for images only but also for files

**Comment by ganeshdeshmukh1612** [comment] 2018-07-11 09:55
@Zebradil , nice trice to download, but can it download all videos of specific group?

**Comment by Zebradil** [comment] 2018-07-11 10:19
@ganeshdeshmukh1612, At the moment I used this approach there was no way to request only media files. If Telegram API is not changed, you have to iterate over all messages in a channel and process each of them one by one.

**Comment by drakmail** [comment] 2018-10-06 15:43
@ganeshdeshmukh1612 I used this script to download all media from specific group:

requirements.txt

```
beautifulsoup4==4.6.0
certifi==2017.11.5
chardet==3.0.4
click==6.7
Django==1.11.9
dparse==0.4.1
idna==2.6
mercurial==4.4.2
packaging==17.1
protobuf==3.5.1
pycairo==1.17.0
pygobject==3.28.2
pyparsing==2.2.0
pytz==2017.3
PyYAML==3.13
requests==2.18.4
safety==1.8.4
six==1.11.0
sshuttle==0.78.3
urllib3==1.22
virtualenv==15.1.0
```

```bash
pip install -r requirements.txt
```

```python3
from telethon import TelegramClient
import telethon.sync

import asyncio
import socks

api_id = PLACE_YOUR_APP_ID_HERE
api_hash = PLACE_YOUR_API_HASH_HERE

# to use with TOR proxy
client = TelegramClient('my_session', api_id, api_hash, proxy=(socks.SOCKS5, 'localhost', 9150))
# to use without proxy
# client = TelegramClient('my_session', api_id, api_hash)

client.start()

def load_messages():
    dialogs = client.get_dialogs()
    chat = None

    for dialog in dialogs:
        if dialog.name == YOUR_GROUP_NAME_HERE:
            chat = dialog
            break

    for message in client.iter_messages(chat):
        if message.media:
            print('Downloading...')
            client.download_media(message)

load_messages()
```

**Comment by Nachtalb** [comment] 2019-05-12 15:09
Would you please implement that feature. 

My use-case here is that I want to download some (not all) images from a channel. And as I see it the user-friendliest method to implement it would just be a simple `SAVE   TO PC` button to the bar of buttons on top when you selected some messages. Like this eg.
![DeepinScreenshot_select-area_20190512165549](https://user-images.githubusercontent.com/9467802/57584157-78cd7700-74d8-11e9-8764-b03c3a284ced.png)

**Comment by nicofirst1** [comment] 2019-06-04 10:45
Are there any news about this?

**Comment by vijaychandra800** [comment] 2019-06-05 05:49
> Quick tip. It is possible to download media with small python script.
> 
> 1. Goto https://my.telegram.org and generate api id and api hash
> 2. Install [Telethon library](https://github.com/LonamiWebs/Telethon) with `pip3 install telethon`
> 3. Run following code (replace `api_id`, `api_hash` and `username` with your values):
> 
> ```python
> from telethon import TelegramClient
> api_id=123456
> api_hash='secretHashYO'
> client = TelegramClient('test_session', api_id, api_hash)
> client.start()
> for message in client.get_message_history('username', limit=25):
>     client.download_media(message)
> ```
> 
> This code downloads media from the last 25 messages from the dialog with `username` user **in current directory.**

From which channel/group will it download?

**Comment by RememberTheAir** [comment] 2019-06-05 07:00
@vijaychandra800 "This code downloads media from the last 25 messages **from the dialog with `username` user** in current directory"

**Comment by teo1978** [comment] 2019-06-10 17:39
This is pathetic.
The need for this feature should have been obvious the very moment saving an image was conceived (which I guess was when Telegram Desktop was created, given that sending photos in the mobile app probably already existed when the Desktop app was created).
It has been explicitly asked for by users for three f****ng years and we are still waiting??

**Comment by Zebradil** [comment] 2019-06-10 18:10
@teo1978 is there a pull request for this already? If not, you can go and implement this feature, it’s open source project and authors aren’t obligated to implement everything people ask them.

**Comment by edmundlaugasson** [comment] 2019-06-15 20:10
Would be also interested about the feature. Also currently up to 100 images can be selected and not more. Download should be possible for all or selected images.

**Comment by RememberTheAir** [comment] 2019-06-17 06:45
Since nobody mentioned it yet, you can export the content of a chat and decide to export images only. You can also select a timeframe so you don't have to download the whole pictures history

![image](https://user-images.githubusercontent.com/16143208/59583662-41a44400-90dc-11e9-8a34-605850c89ba2.png)

**Comment by amiremami** [comment] 2019-06-17 06:57
> Since nobody mentioned it yet, you can export the content of a chat and decide to export images only. You can also select a timeframe so you don't have to download the whole pictures history
> 
> ![image](https://user-images.githubusercontent.com/16143208/59583662-41a44400-90dc-11e9-8a34-605850c89ba2.png)

Nice trick, thanks ;)

**Comment by teo1978** [comment] 2019-06-17 08:36
Thank you, nice workaround.

Of course, the fact that a few workarounds exist is no excuse for not being able to just select a few images and download them in the exact same way you would a single image (I.e. right-click download).

By the way, I also tried selecting the images, copying with Ctrl+c, and pasting then into a folder in Nautilus. I would expect that to work too,  as long as the only thing you've selected is images, videos, and files.

**Comment by pannakocka** [comment] 2019-07-01 22:10
Thank you!

what worked for me here (a year after this script was published) - adding 'import asyncio' as a second line.

> Quick tip. It is possible to download media with small python script.
> 
> 1. Goto https://my.telegram.org and generate api id and api hash
> 2. Install [Telethon library](https://github.com/LonamiWebs/Telethon) with `pip3 install telethon`
> 3. Run following code (replace `api_id`, `api_hash` and `username` with your values):
> 
> ```python
> from telethon import TelegramClient
> api_id=123456
> api_hash='secretHashYO'
> client = TelegramClient('test_session', api_id, api_hash)
> client.start()
> for message in client.get_message_history('username', limit=25):
>     client.download_media(message)
> ```
> 
> This code downloads media from the last 25 messages from the dialog with `username` user **in current directory.**

**Comment by chaitanyakush** [comment] 2019-07-24 18:52
> Thank you!
> 
> what worked for me here (a year after this script was published) - adding 'import asyncio' as a second line.
> 
Not working for me :( showing error.

`AttributeError:` 'TelegramClient' object has no attribute 'get_message_history'

How to overcome this?

**Comment by pannakocka** [comment] 2019-07-24 19:42
> > Thank you!
> > what worked for me here (a year after this script was published) - adding 'import asyncio' as a second line.
> 
> Not working for me :( showing error.
> 
> `AttributeError: 'TelegramClient' object has no attribute 'get_message_history'`
> 
> How to overcome this?
Oh, yes, this part is aoutdated too. I
I used the following code:


`from telethon import TelegramClient
import telethon.sync

import asyncio

api_id=123456
api_hash=124343
client = TelegramClient('test_session', api_id, api_hash)
client.start()
#for dialog in client.iter_dialogs():
 #   print(dialog.name, 'has ID', dialog.id)
for message in client.get_messages(ID, limit=50):
    client.download_media(message)
`

I used the commented lines to see all the IDs and find the one I need
(I was looking to download images from a group chat, so it took time to understand that group ID starts with "-")

**Comment by chaitanyakush** [comment] 2019-07-25 18:44
> ```
> from telethon import TelegramClient
> import telethon.sync
> 
> import asyncio
> 
> api_id=123456
> api_hash=124343
> client = TelegramClient('test_session', api_id, api_hash)
> client.start()
> #for dialog in client.iter_dialogs():
>  #   print(dialog.name, 'has ID', dialog.id)
> for message in client.get_messages(ID, limit=50):
>     client.download_media(message)
> ```
> 
> I used the commented lines to see all the IDs and find the one I need
> (I was looking to download images from a group chat, so it took time to understand that group ID starts with "-")

Thanks for the quick reply :)
For some reasons I was not able to use your mentioned script due to telethon update(maybe). So after some research I was able to build a new version of this script. Thanks again.

from telethon import TelegramClient
import telethon.sync
import asyncio
from tqdm import tqdm
api_id = 12345
api_hash = 'HASH'
with TelegramClient('SESSION', api_id, api_hash) as client:
    messages = client.get_messages(ID, limit=15)
    print(len(messages))
    for msg in tqdm(messages):
        client.download_media(msg)

**Comment by diniewan** [comment] 2019-11-01 20:46
https://github.com/telegramdesktop/tdesktop/issues/1382#issuecomment-502555459

Exporting and then choosing your options worked for me... awesome!!! Thanks!

**Comment by raelmiu** [comment] 2019-11-04 08:41
> Since nobody mentioned it yet, you can export the content of a chat and decide to export images only. You can also select a timeframe so you don't have to download the whole pictures history
> 
> ![image](https://user-images.githubusercontent.com/16143208/59583662-41a44400-90dc-11e9-8a34-605850c89ba2.png)

How is this done? I can't find an export option.

**Comment by Nachtalb** [comment] 2019-11-04 08:43
> How is this done? I can't find an export option.

Three dot menu top right or when you open the chat info again on the top right of that one

**Comment by raelmiu** [comment] 2019-11-04 08:46
Strangely not available?

<img width="527" alt="Screenshot 2019-11-04 at 09 45 31" src="https://user-images.githubusercontent.com/186083/68108387-eb4b6c80-fee7-11e9-9f5c-cf77c26e6e3d.png">

**Comment by Speeddymon** [comment] 2019-11-04 09:15
> Strangely not available?
> 
> <img alt="Screenshot 2019-11-04 at 09 45 31" width="527" src="https://user-images.githubusercontent.com/186083/68108387-eb4b6c80-fee7-11e9-9f5c-cf77c26e6e3d.png">

I'm not surprised that you're not seeing it given that this thread is for the desktop client and you're looking at your phone.......

**Comment by raelmiu** [comment] 2019-11-04 09:23
That screenshot is from the desktop client on MacOS.

**Comment by Nachtalb** [comment] 2019-11-04 09:26
There are two desktop clients for mac. This one and one from the app store. The one you are looking at is must be from the app store and has no relation to this one. In other words this is not the place you're looking for.

**Comment by Speeddymon** [comment] 2019-11-04 09:27
Strange, the original screenshot looks identical to my phone. Apologies for my tone earlier.

**Comment by raelmiu** [comment] 2019-11-04 09:27
Thank you @Nachtalb !
Don't worry about it @Speeddymon .

**Comment by Nachtalb** [comment] 2019-11-04 09:50
@Zebradil I just saw realized that you don't use a takeout session in your code-snippet (https://github.com/telegramdesktop/tdesktop/issues/1382#issuecomment-362860530). I would use it / update your code-snippet:
> Some of the calls made through the takeout session will have lower flood limits. This is useful if you want to export the data from conversations or mass-download media, since the rate limits will be lower.
> https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.account.AccountMethods.takeout

**Comment by Zebradil** [comment] 2019-11-14 21:25
Hey @Nachtalb, thanks for pointing that out. I've checked the approach with `takeout` object and decided to stay with usual client object instead. The reason is that the "takeout" approach requires handling export request, so just replacing `client` by `takeout` will break the example, which is meant to be as simple as possible — it is needed just to give an idea of how to approach the solution.

**Comment by zignd** [comment] 2020-01-04 16:07
For some reason, the built-in exportation option is not downloading all the images from a group I'm in. I ended up creating a script based on the ones on this thread allowing me to search for a chat by name and them downloading all its media. In case it might be helpful for anyone here's the link to the repository: https://github.com/zignd/telegram-media-downloader

**Comment by MenOfWar** [comment] 2020-01-24 00:00
+1 for this feature, plz allow download of albums (bulk of 10 pictures for example) at once. thank you

**Comment by maxim-kukushkin** [comment] 2020-04-26 12:06
Seriously? So much time passed and this issue is still not implemented?? Telegram, when? It's the most obvious thing that had to be available from day 0.

**Comment by RememberTheAir** [comment] 2020-04-26 12:13
@maxim-kukushkin see https://github.com/telegramdesktop/tdesktop/issues/1382#issuecomment-502555459

**Comment by maxim-kukushkin** [comment] 2020-04-26 12:26
@RememberTheAir, thanks, that definitely simplifies the saving

However it's still a trick and not what the author asked for. If a person sent me several bunches of photos I may not want to export all of them. Or if it was say several days ago I shouldn't need to remember the date and reproduce it in the dialog window. It should be point and click feature - I look at what I need to save, click it and save it.

**Comment by RememberTheAir** [comment] 2020-04-26 12:34
I guess this issue kind of conflicts with the more recent #6984. Bulk downloading can be done using the export tool, while selectively saving selected images is still something missing. It's related to what one want "bulk downloading" to mean. Since #6984 has not been closed as a duplicate, I guess we can split the two topics (bulk downloading/exporting and saving a selection)

**Comment by Speeddymon** [comment] 2020-10-23 21:01
Please do not close this.

**Comment by ElGordoEncodes** [comment] 2020-10-30 20:55
I was about to create a new issue, but remembered I could search first. This feature would make even more sense right now, as the latest update features grouping files into a single message. It shouldn't be available only for images, but for any type of file.

### Is your feature request related to a problem?
Not really a **problem**, but something a bit inconvenient. Since the latest update (https://telegram.org/blog/pinned-messages-locations-playlists at the date of writing), Telegram for Android enables the user to select multiple files, be it all of them grouped in a single message, or each in a separate message, and then tap on a single button at the top to download all the selected files at once. On desktop, we still have to click on the download button for all files, one by one.

### Describe the solution you'd like
For messages that consist of grouped files, offer a button inside the context menu to download everything contained within that single message. If multiple files are selected, show a _Download_ button at the top, next to the _Forward_ and _Delete_ buttons, that allows for downloading the selected files. If possible, and even better, ask the user where to save the files when the button is pressed (as it happens when right clicking a file -> save file as).

### Describe alternatives you've considered
The "alternative" would be to only offer the Download button when selecting multiple files, and discard the option inside the context menu.

### Additional context
Since we can now send multiple files grouped in a single message, it's similar to sending zipped files. The advantage here is that you can download individual files if you want, and are not forced to download the whole zip for a single file (which you would have to do if, let's say, you deleted one single file from inside the zip by accident).
Before, we could send both the individual files + a zip file to accomplish this very same system, but now sending an extra zip file shouldn't be required anymore, saving both user's upload bandwitdh and time, and Telegram's server available storage. And this would only be possible by allowing the download of multiple files at once.

**Comment by Croydon** [comment] 2021-04-29 03:15
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by Balls0fSteel** [comment] 2022-04-24 14:02
One year later, still a huge issue. Have to export all images, and all content from chats each and every time I wish to save like 10+ pictures. It's a huge pain and an incredible waste of resources on both my and Telegram's side. Please fix it?

**Comment by conkerts** [comment] 2022-10-22 08:38
I agree, why is it so difficult to add "download selected media" ?
I mean ok, if tg wants me to bulk dl everything from the day, then whatever, but it's really unnecessary.

**Comment by Nabsta** [comment] 2022-10-27 18:53
I accept that this feature is necessary. Ok tg keep images encrypted on machine so we cant just go and get all (i.e. last cashed) images from some directory. But nor any bulk download option/functionality is provided instead. Will be waiting for that feature! Thnx!

**Comment by 23rd** [comment] 2022-11-05 16:37
Please check the 4.3.0 version.

**Comment by Sonico98** [comment] 2022-11-05 17:59
> Please check the 4.3.0 version.

Thank you! It works. It took me a while to figure out how to use it because the button won't show if the option "Ask download path for each file" is active, but it's working perfectly with that option disabled.

**Closed** 2022-11-05 20:33 UTC
Labels: enhancement

**Comment by amiremami** [comment] 2022-11-05 21:35
6 years ago I requested this feature, finally added, thanks a lot guys 🙏 With every update, it's getting better and better.

**Comment by php4fan** [comment] 2022-11-09 19:16
When will the Arch package be released??

**Comment by Aokromes** [comment] 2022-11-09 19:17
> When will the Arch package be released??

only arch devs knows.

**Comment by maxim-kukushkin** [comment] 2022-11-10 13:48
> When will the Arch package be released??

@php4fan, it's already available. Though probably it's in AUR. The package is `telegram-desktop-bin`. I have 4.3.0-1 currently installed

**Comment by Sonico98** [comment] 2022-11-10 14:22
> When will the Arch package be released??

It's already been released, maybe update your mirrors. No need to install the bin from AUR



> **Could you allow us to choose a folder when using this feature?**
> 
> So all I am asking for is a native folder picker. Not even a fancy one, same as "Save As", just for folder picking.
> 
> **Why / rationale**: The feature is GREAT but it's very hard, even for myself to go into Telegram's Download folder and then dig out the newly saved files. Even for a new user, it'd be way easier (in my opinion) to select a folder they want, and they can find the downloaded pictures easier.
> 
> Thank you!

That's what I expected to be able to do as well, as I had the "Ask download path for each file" option enabled

**Comment by mikkovedru** [comment] 2022-11-25 19:57
@Aokromes @23rd 

The progress is great! Unfortunately, the feature is still not complete.
1. Doesn't work if the option "Ask download path for each file" is active.
2. Is not obvious that one has to click the right mouse button and choose from there. 
![image](https://user-images.githubusercontent.com/2521942/202952185-67b7221d-dc51-49df-9e82-47f6127af24b.png)
There is space for the third button on top of the window and logically speaking that's where it should be as well.

**Comment by php4fan** [comment] 2022-11-25 21:04
This should be reopened. As is, this feature is basically useless.

When I right-click on  a single image and do Save As, I get a browse-files window allowing me to select where to download the file, as expected (I don't know whether or not I have the "ask download path for each file" option enabled or not, I assumed I do, but I haven't been able to find it in settings).
However, when I select multiple messages, right-click and select "Save selected", it **just saves them into the default Download folder,** which is better than not being able to save at all, but still basically useless, as I have to navigate to that folder and then figure out by myself what are the files that I have just downloaded. Isn't that basically the same as before this feature was implemented? This is so stupid.

**Comment by php4fan** [comment] 2022-11-25 21:16
> (I don't know whether or not I have the "ask download path for each file" option enabled or not, I assumed it was, but I haven't been able to find it in settings).

Ok so I found it, and:

1) When I right-click on a **single file** and do _Save As_:
-- whether or not the option "ask download path for each file" is selected, it **always asks me** where to save the file, regardless. It's what I want, but then I don't understand what the option is for

2) When I select **multiple messages**, right-click and do _Save Selected_:
-- if the option "ask download path for each file" is not enabled, it saves everything to Downloads without asking
-- if the option is  enabled, then "Save Selected" is not available in the context menu in the first place, so you cannot save multiple files at all, let alone choose where.

This makes no sense whatsoever. The option "ask download path for each file" does not do what it says it does, and its only effect, when enabled, is to remove the option to save multiple files.
