### ISSUE TITLE
Insert unicode symbols with keyboard shortcut Ctrl+Shift+U

### ISSUE THREAD

**Issue by bedf** [telegramdesktop/tdesktop#1288] opened 2015-11-10 01:57 UTC
It is well known that in GNU/Linux environments you can enter Unicode symbols with keyboard shortcut Ctrl+Shift+U followed by the Unicode code and enter.

Unfortunately, it does not work in telegram-desktop. After entering the keyboard shortcut, to write the unicode code erases the previous text.

Note: An alternative way to enter emojis and other symbols.

Thanks

**Comment by giordano** [comment] 2015-11-10 09:24
It is well known this works only if the GTK+ library has been used, and this is not the case for Telegram Desktop, which has been built upon Qt.

Duplicate of #1033.

**Comment by bedf** [comment] 2015-11-10 12:56
I am aware that Telegram-Desktop is a QT application, but this is a feature that I use a lot and remember it worked fine in KDE environments.
Moreover, it works well in other qt applications that have installed such as Skype, VLC, Popcorntime (RIP), Viber and Jitsi.

When not working in viber, performing the keyboard shortcut nothing happened, however, in Telegram appears the "u" underlined, simply by entering the unicode code, it overwrites the previous text, which I think is a bug .

Can you at least be considered?

**Comment by auchri** [comment] 2015-11-10 13:02
Sounds like a bug :+1:

**Comment by giordano** [comment] 2015-11-10 13:09
>  Moreover, it works well in other qt applications that have installed such as Skype, VLC, Popcorntime (RIP), Viber and Jitsi.

Why I can't reproduce in Skype and VLC?  Could you please give me a recipe to try this feature in these programs?  In which fields you can insert Unicode symbols with CTRL+Shift+U?

**Comment by bedf** [comment] 2015-11-10 13:57
There are two ways to use this shortcut:
- Press Ctrl+Shift+U (stop pressing keys). after a U is underlined, insert Unicode code. (enter)
- Press Ctrl+Shift+U (hold down Ctrl). A "U" underlined appears, keep hold Ctrl, enter unicode code, then you release the key.

To insert "Psi" symbol (Ψ) , the unicode code is "03a8"

I've tried other qt applications and java applications and works well, the only application that has the same behavior that Telegram-desktop is transmission-qt.

**Comment by giordano** [comment] 2015-11-10 14:04
I didn't ask "how" but "where" ("which fields").  I know this feature (otherwise I wouldn't be able to comment), but for me always worked only in GTK+ applications, as it is GTK+ specific.

For me in Skype it doesn't work in message input (where it would be most useful), for one.  In VLC it doesn't work in Media → Open file... → "Name" field, nor in View → Playlist → "Search" field.  I would like to know in which fields it does work for you.  Maybe the OS is relevant?  Debian here.

**Comment by bedf** [comment] 2015-11-10 14:35
Sorry, I misunderstood.
I do not know if it is a specific feature, but I use a lot this function and had no problems above using gnome or KDE (Qt, GTK+ and java applications).

It works for me in every field you mention. It actually works in any field that allows text input.

I am trying to create a small screencast that shows it works.

System: 
fedora 23 64 bit (GNOME)
skype 4.3.0.37
vlc 2.2.2

Cheers

**Comment by bedf** [comment] 2015-11-10 20:54
My curiosity led to install and test the three major desktop environments.
Conclusions:
- This feature seems to be the work of GTK and ibus, like a gnome service.
- It operates under all applications used in gnome (QT, GTK, java, etc)
- Partially it works on XFCE. It works almost entirely if they activate gnome services and ibus daemon.
- Plasma Workspace 5 does not work (needs a lot of config).
- In gnome, Qt4 applications work well. nstead, part of the QT5 applications not working properly. See: https://bugreports.qt.io/browse/QTCREATORBUG-9221

I think the bug report remains valid, perhaps with lower priority. It is a nice feature for an IM application. 

Cheers

I can not create a quality screencast, but take screenshots of the applications mentioned. Note Telegram appears as "u" underlined.
![choose_avatar_skype](https://cloud.githubusercontent.com/assets/5126124/11075376/c4577f0e-87d3-11e5-96ce-a23882c1cdcd.png)
![clementine](https://cloud.githubusercontent.com/assets/5126124/11075377/c45965b2-87d3-11e5-895f-8abc2024d5ac.png)
![popcorntime](https://cloud.githubusercontent.com/assets/5126124/11075380/c463ef14-87d3-11e5-8d87-cd05bfa165c7.png)
![skype](https://cloud.githubusercontent.com/assets/5126124/11075379/c4627cce-87d3-11e5-9af3-c54443b9ec46.png)
![telegramdesktop](https://cloud.githubusercontent.com/assets/5126124/11075378/c45f3c3a-87d3-11e5-8090-553ddd00771b.png)
![terminal](https://cloud.githubusercontent.com/assets/5126124/11075381/c466fa88-87d3-11e5-973e-9700c2a4fd9c.png)
![vlc](https://cloud.githubusercontent.com/assets/5126124/11075382/c4804484-87d3-11e5-8490-3a8f272e3f98.png)

**Comment by giordano** [comment] 2015-11-11 09:04
> In gnome, Qt4 applications work well. nstead, part of the QT5 applications not working properly. See: https://bugreports.qt.io/browse/QTCREATORBUG-9221 

If you go to the Wikipedia article mentioned there (https://en.wikipedia.org/wiki/Unicode_input#In_X11_.28Linux_and_other_Unix_variants.29) you'll find

> For example, GTK+ is an ISO 14755-conformant system. The beginning sequence is `Ctrl`+`⇧ Shift`+`U` and the ending sequence is `↵ Enter` or `Space`. Programs based on GTK+, such as GNOME applications, support Unicode input.
> [...]
> In non-GTK applications, however, there usually is no escape sequence to input arbitrary input characters. For example, Qt, KDE rely on the standard X Input Method (XIM) framework, and do not implement their own solutions.[7]

For me entering Unicode characters in the way you described never worked in Qt applications, no matter the surrounding desktop environment (either GNOME, KDE, LXDE, or XFCE, because what's important here is the library with which the program has been built), always on Debian-based distros (Debian and Ubuntu mostly), and you can see I'm not the only one claiming this.

Maybe Fedora, contrary to Debian & Co., ships a Qt version which enables this features, but I think Telegram Desktop uses its own patched Qt version.

**Comment by ralesk** [comment] 2015-11-17 22:47
Chiming in: Yes, this is a GTK only feature and Qt has refused to add it because X11 doesn't support it: https://bugreports.qt.io/browse/QTBUG-8

Has nothing to do with the desktop you're using, it's only to do with the framework the application is using.  I've never seen a Qt-based application (including Skype and all of KDE) work, and I've used both Debian-based distros and Fedora.

**Comment by bedf** [comment] 2015-11-18 01:50
>Has nothing to do with the desktop you're using, it's only to do with the framework the application is using. I've never seen a Qt-based application (including Skype and all of KDE) work, and I've used both Debian-based distros and Fedora.

-Yes, according to the documentation, it is a GTK+ feature (including the ibus input method).
-Based on my testing, this feature works completely in "gnome 3.18" in GTK+ and Qt4 applications. (see screenshots above ... there are Skype and other QT4 applications)

I asked questions in the corresponding mailing lists to get out of the doubt, since only QT5 applications do not work (perhaps related to ibus-qt?)

The final conclusion is that only affects QT5 applications and therefore is not a Telegram Desktop bug. 

Thank you.

**Closed** 2015-11-18 07:45 UTC
Labels: bug, linux

**Comment by diazbastian** [comment] 2016-06-22 06:57
Update:
In fedora Workstation 24 using Gnome 3.20.2 this method to insert unicode characters works perfectly... weird

**Comment by stormyqq** [comment] 2018-10-29 10:46
I can't type sinhalese fonts in telegram desktop client. I use rsinglish software to type sinhalese fonts. there is no problem when using the rsinglish with other applications such as word, chrome etc.. but telegram makes problems. when i type one letter, it types multiple letters.
