### ISSUE TITLE
Does not respect Auto-hidden Taskbar when the window is maximized

### ISSUE THREAD

**Issue by mrahimygk** [telegramdesktop/tdesktop#3579] opened 2017-06-26 12:08 UTC
### Steps to reproduce
1. enable Auto hide the taskbar in windows 8.1
2. maximize the main window of telegram
3. hover on taskbar to show it ...

### Expected behaviour
It should show taskbar, but the telegram window is not  allowing it.

### Actual behaviour
Taskbar is hidden when trying to show it by hovering the mouse.

### Configuration
**Operating system:** Windows 8.1

**Version of Telegram Desktop:** 1.1.7

**Used theme**: Default

**Comment by ThigSchuch** [comment] 2018-07-31 13:32
One year later, version v1.3.10, Windows 10.
Still happen... Sad.

**Comment by LookedPath** [comment] 2019-01-04 15:34
Still happening on Windows 10 with version 1.5.4 and I can't really understand how no one on the dev team didn't notice this.

**Comment by Lambda1Elite** [comment] 2019-01-21 13:57
The same is true of me, on **Windows 10 Enterprise LTSB 64-bit**

**Comment by john-preston** [comment] 2019-04-09 13:06
@rkitover Yeah, sure. That won't break other cases, of course.

**Comment by rkitover** [comment] 2019-04-09 13:15
I have no idea, there is always potential for breakage with any kind of development, this is really annoying though.

**Comment by lexx790** [comment] 2019-06-17 22:20
Experiencing this problem as well in Windows 10 as of 6/2019. Would like a fix for this.

**Comment by caeslucio** [comment] 2019-06-30 17:36
The same issue here

**Comment by namandixit** [comment] 2019-07-05 03:32
I do not have a development environment set up. Can someone who does have it set up please see if the following "patch" fix this issue:

After [this](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/win/main_window_win.cpp#L591) line, add the following:

    HWND taskbar_handle = ::FindWindowW(L"Shell_TrayWnd", NULL);
    ::SetWindowPos(taskbar_handle, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE );

This sets the taskbar as the topmost window once again without (hopefully) messing with the Z-order. To test if it works in Windows 10, go to `Settings` app, then `Personalisation` -> `Taskbar` and set `Automatically hide the taskbar in Desktop mode` as `true` and `Taskbar location on screen` as `Left`. Finally, open the newly compiled Telegram, maximize it and hover over the left edge of the screen. Hopefully, the taskbar will come up.

**Comment by Fedorov113** [comment] 2020-01-14 13:39
I am experiencing this issue too.
Windows 10 Pro 1909 64bit, Telegram v1.9.3

**Comment by LookedPath** [comment] 2020-01-15 10:32
This bug is the only reason that prevents me from using the Telegram app and that pushed me towards Unigram

**Comment by gonewild8** [comment] 2020-03-28 13:19
same problem here

Windows 10 Pro 1909 64bit, Telegram v1.9.22 beta

**Comment by TeijiW** [comment] 2020-04-26 05:30
Same problem here.
Is very sad that problem still occurs with almost three years of open this issue.
Windows 10 Pro 1909
Telegram 2.1

**Comment by Nyuhnyash** [comment] 2020-05-09 17:19
Same problem on Windows 10
TDesktop 2.1.4

**Comment by PavelStefanov** [comment] 2020-08-03 11:53
3 year old bug is still here =(

**Comment by ilya-fedin** [comment] 2020-08-29 12:35
> 3 year old bug is still here =(

No one knows why it appears and how to fix it

**Comment by john-preston** [comment] 2020-08-29 12:45
@ilya-fedin Btw I think it should not happen with system window frame.

**Comment by LookedPath** [comment] 2020-09-01 08:45
This is for me the last really annoying issue of Telegram Desktop.
Do devs read these issues or is it just users?
In the past I've tried setting up @namandixit "fix" but I wasn't able to successfully setup the dev env due to some old instructions in the repository that did not reflect the actual state of the code.
I'll try again this week so I can hopefully test it.

**Comment by Aokromes** [comment] 2020-09-01 08:48
> Do devs read these issues or is it just users?

you need to read the post over your.

**Comment by LookedPath** [comment] 2020-09-01 09:02
> > Do devs read these issues or is it just users?
> 
> you need to read the post over your.

Damn, I'm really blind aren't I?

> @ilya-fedin Btw I think it should not happen with system window frame.

I can confirm that with the system window frame it works as intended.

**Comment by X04N** [comment] 2020-09-15 11:02
OK, for anyone with this issue, setting telegram to use the system window frame will fix the problem.
To do that you need to open your telegram desktop, go to settings -> advanced settings -> System integration -> Make sure the "Use system window frame" option is enabled.
This should fix the issue for you :)

**Closed** 2020-09-30 16:14 UTC
Labels: bug, windows
