### ISSUE TITLE
Crash in Windows when removing active monitor and after using remote desktop

### ISSUE THREAD

**Issue by JasperAlgra** [telegramdesktop/tdesktop#450] opened 2015-01-26 10:38 UTC
When using windows remote desktop (mstsc) telegram crashes. I think this bug is easily reproducable. Can I do anything to provide debug info?

**Comment by JasperAlgra** [comment] 2015-01-27 18:52
I've got something from my visual studio debugger:
>Unhandled exception at 0x54975ac4 in Telegram.exe: 0xC000041D: TAn unhandled exception was encountered during a user callback.

But since i'm just running the compiled version I can only get a disassembly jump point.. So, if someone is willing to spend some time on this, I could build telegram from source to see the actual breakpoint.. Just drop me an email or a reply here.

**Comment by telegramdesktop** [comment] 2015-01-29 10:38
When Telegram crashes it is saving crash minidumps to %AppData%/Telegram Desktop/tdumps folder (right near Telegram.exe), could you please see, if there are some dumps?

**Comment by JasperAlgra** [comment] 2015-01-29 10:41
Thanks for your reply. 
Sure, just looked into that. Since I cant seem to upload anything other than images to github I've placed the last dump here:
https://www.dropbox.com/s/7d74oooq5wkftag/Telegram-0.7.9-20150127-194645-12364-44.dmp?dl=1

**Comment by telegramdesktop** [comment] 2015-01-29 11:32
I'm sorry, I'm afraid I can't help you with that crash at the moment, it looks like it is happening somewhere far outside my binary, I have saved program databases (debug info symbols) for all deployed versions, including 0.7.9, and usually when I debug a crash report I see some stack frames and data, but this one looks like that:
![image](https://cloud.githubusercontent.com/assets/6113871/5956894/a5348a4a-a7c3-11e4-8f4d-a4a16d517f77.png)

**Comment by JasperAlgra** [comment] 2015-01-29 20:35
No worries and thanks for trying anyway. Not the biggest issue in the world anyhow, but if I find out some more I'll post here.

Jasper



Op 29 jan. 2015 om 12:33 heeft telegramdesktop <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I'm sorry, I'm afraid I can't help you with that crash at the moment, it looks like it is happening somewhere far outside my binary, I have saved program databases (debug info symbols) for all deployed versions, including 0.7.9, and usually when I debug a crash report I see some stack frames and data, but this one looks like that:
[https://cloud.githubusercontent.com/assets/6113871/5956894/a5348a4a-a7c3-11e4-8f4d-a4a16d517f77.png]<https://cloud.githubusercontent.com/assets/6113871/5956894/a5348a4a-a7c3-11e4-8f4d-a4a16d517f77.png>

**Comment by daedalus01** [comment] 2015-05-07 16:00
I too am having this issue. Telegram seems to close itself when I transition between having my Windows session locked at console, and then RDP'ing in (and vice versa), but doesn't produce any crash dumps in %AppData%/Telegram Desktop/tdumps.

Once I RDP in and start Telegram back up again, I seem to be able to RDP in subsequently without Telegram closing itself. However, if I then go back to physical console (when I'm not remote) and log in, I find that Telegram has closed itself and I need to start it back up again. This doesn't seem to happen with any other applications that use/that live in the tray.

Are there logs or debug that I can run to help diagnose this? A friend of mine also is having this problem, and I can work with him to get logs/debugs too. My friend and I both have Nvidia graphics cards if that makes any difference.

**Comment by daedalus01** [comment] 2015-05-13 03:04
Quick update - I was able to reproduce this without RDP entirely - I had telegram on one of my three monitors, and I disabled that monitor - upon doing so, Telegram closed instead of repositioning onto another monitor.

**Comment by Dmkaz** [comment] 2015-05-19 14:42
I am having this issue as well. To echo daedalus01's comments, I can indeed produce this in RDP as well without RDP entirely using  the process he described. 

I also see no logs/crash drumps in %AppData%/Telegram Desktop/tdumps

**Comment by franklesniak** [comment] 2015-05-27 02:49
Me too!

**Comment by daedalus01** [comment] 2015-05-28 20:50
@JasperAlgra can we rename the title of this bug to something like "Crash in Windows when removing active monitor" ?

**Comment by JasperAlgra** [comment] 2015-06-02 18:07
@daedalus01 Sorry for delay in response, was on holiday. Fine by me, seems like a better fit. 
Will see if I can somehow edit that...

**Comment by auchri** [comment] 2015-08-14 22:00
#796

**Closed by auchri** 2015-08-14 22:00 UTC
