### ISSUE TITLE
[Feature Request] Separate subscribers in channel as contacts, bots, and others.

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#8623] opened 2020-09-20 04:47 UTC
Missing feature

**Comment by ilya-fedin** [comment] 2020-09-20 17:16
Stop deleting the template

**Comment by SmartManoj** [comment] 2020-09-20 17:19
I thought the template is not suitable for missing features.

The feature is currently available on mobile.

**Comment by RememberTheAir** [comment] 2020-09-21 06:46
Duplicate of #6620

**Closed** 2020-09-21 07:00 UTC
