### ISSUE TITLE
Windows 10 - Beta 1.7.12 Blocked 18+ chats

### ISSUE THREAD

**Issue by TeksuneStudio** [telegramdesktop/tdesktop#6228] opened 2019-07-06 15:45 UTC
![image](https://user-images.githubusercontent.com/30129546/60758266-60af3b00-9fe3-11e9-9d2a-9579fd50b799.png)

Telegram Desktop is blocking access on a Windows PC to an adult chat for an iOS/Mac flag. Can someone explain to me what's happening here?

**Comment by Johnnynator** [comment] 2019-07-06 15:53
Know bug that should be fixed in 1.7.13

Duplicate of #6224

**Closed** 2019-07-08 14:56 UTC
