### ISSUE TITLE
Program received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by tsuibin** [telegramdesktop/tdesktop#597] opened 2015-03-25 15:25 UTC
This is GDB Debug massages:

Type "apropos word" to search for commands related to "word"...
Reading symbols from Telegram...done.
(gdb) r
Starting program: /opt/Telegram/Telegram 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
libs init..
[New Thread 0x7ffff4f94700 (LWP 3805)]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000bbe169 in g_signal_connect_data ()

**Comment by tsuibin** [comment] 2015-03-25 15:26
system:
Linux tsuibin-pc 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
libs:
tsuibin@tsuibin-pc:/opt/Telegram$ ldd Telegram 
	linux-vdso.so.1 =>  (0x00007fff4c7b7000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f61806fc000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f61804fa000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f61802da000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f61800d6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f617fece000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f617fbc5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f617f9a7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f617f6a3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f617f39c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f617f186000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f617edc1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6180a5b000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f617ebbc000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f617e9b6000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f617e778000)

**Comment by dkadashev** [comment] 2015-04-08 09:45
This is probably a duplicate of #588 - I get the same message (segfault in g_signal_connect_data())

**Closed** 2015-08-14 23:12 UTC
