### ISSUE TITLE
[feature request] Allow more than 5 pinned chats

### ISSUE THREAD

**Issue by Supuhstar** [telegramdesktop/tdesktop#4249] opened 2017-12-28 01:44 UTC
## Argument
The number of chats I can pin shouldn't be limited... I understand that the feature is for _Really Important Chats_, but for people like me that number is greater than 5 (right now it is 6), which makes sense because I probably have over 100 chats.

### Steps to reproduce
1. Join more than 5 chats
2. Pin 5 chats
3. Attempt to pin a 6th

### Expected behaviour
4. The 6th chat should be pinned

### Actual behaviour
4. A dialog appears saying "Sorry, you can pin no more than 5 chats to the top."

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2.1

**Used theme**: Custom

<details><summary><b>Logs</b>:</summary>
None
</details>

**Comment by RememberTheAir** [comment] 2017-12-28 07:22
Duplicate of #3026

**Closed** 2017-12-28 07:24 UTC
