### ISSUE TITLE
"Ə" font not working for Azerbijan language

### ISSUE THREAD

**Issue by emilalsgndr** [telegramdesktop/tdesktop#7272] opened 2020-02-24 12:07 UTC
### Steps to reproduce
1. 
2. 
3. 
<img width="253" alt="Screen Shot 2020-02-24 at 4 02 39 PM" src="https://user-images.githubusercontent.com/36768068/75151292-c04b8980-571f-11ea-99e5-3239350fd407.png">

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
10.14.6
**Version of Telegram Desktop:**
1.9.14
**Used theme**:
Day
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment] 2020-02-24 22:15
i am sure this is duplicate of another ticket, but cannot find it.

**Comment by Aokromes** [comment] 2020-03-02 07:01
can you try updating your OS?

**Comment by Aokromes** [comment] 2020-03-16 12:10
@emilalsgndr

**Comment by Aokromes** [comment] 2020-04-06 05:50
no answer after more than 1 month, closing.

**Closed by Aokromes** 2020-04-06 05:50 UTC
Labels: waiting for answer
