### ISSUE TITLE
[FEATURE] - more string->emoticon replacements

### ISSUE THREAD

**Issue by JimmyS83** [telegramdesktop/tdesktop#3671] opened 2017-07-18 06:11 UTC
Hello,
this is not bug report, morelike feature request. As custom emoticon strings/assigments isnt possible, could be added just few most widely used codes? I am thinking about shorter emoticons, without - : 
:-) =  :)
;-) =  ;)
:-( =  :(
:-O =  :O

those are most used (not only me), it should be quite easilly just change to

### **emoji_box.cpp**
```
EmojiReplace Replaces[] = {
	{ 0xD83DDE0AU, ":-)" },
	{ 0xD83DDE0AU, ":)" },
	{ 0xD83DDE0DU, "8-)" },
	{ 0xD83DDE0DU, "8)" },
	{ 0x2764U, "<3" },
	{ 0xD83DDC8BU, ":kiss:" },
	{ 0xD83DDE01U, ":grin:" },
	{ 0xD83DDE02U, ":joy:" },
	{ 0xD83DDE1AU, ":-*" },
	{ 0xD83DDE1AU, ":*" },
	{ 0xD83DDE06U, "xD" },
	{ 0xD83DDC4DU, ":like:" },
	{ 0xD83DDC4EU, ":dislike:" },
	{ 0x261DU, ":up:" },
	{ 0x270CU, ":v:" },
	{ 0xD83DDC4CU, ":ok:" },
	{ 0xD83DDE0EU, "B-)" },
	{ 0xD83DDE0EU, "B)" },
	{ 0xD83DDE03U, ":-D" },
	{ 0xD83DDE03U, ":D" },
	{ 0xD83DDE09U, ";-)" },
	{ 0xD83DDE09U, ";)" },
	{ 0xD83DDE1CU, ";-P" },
	{ 0xD83DDE1CU, ";P" },
	{ 0xD83DDE0BU, ":-p" },
	{ 0xD83DDE0BU, ":p" },
	{ 0xD83DDE14U, "3(" },
	{ 0xD83DDE1EU, ":-(" },
	{ 0xD83DDE1EU, ":(" },
	{ 0xD83DDE0FU, ":]" },
	{ 0xD83DDE22U, ":'(" },
	{ 0xD83DDE2DU, ":_(" },
	{ 0xD83DDE29U, ":((" },
	{ 0xD83DDE28U, ":o" },
	{ 0xD83DDE10U, ":|" },
	{ 0xD83DDE0CU, "3-)" },
	{ 0xD83DDE0CU, "3)" },
	{ 0xD83DDE20U, ">(" },
	{ 0xD83DDE21U, ">((" },
	{ 0xD83DDE07U, "O:)" },
	{ 0xD83DDE30U, ";o" },
	{ 0xD83DDE33U, "8|" },
	{ 0xD83DDE32U, "8o" },
	{ 0xD83DDE37U, ":X" },
	{ 0xD83DDE08U, "}:)" },
};
```

### **data.cpp**
```
Replace Replaces[] = {
	{ 0xD83DDE0AU, ":-)" },
	{ 0xD83DDE0AU, ":)" },
	{ 0xD83DDE0DU, "8-)" },
	{ 0xD83DDE0DU, "8)" },
	{ 0x2764U, "<3" },
	{ 0xD83DDC8BU, ":kiss:" },
	{ 0xD83DDE01U, ":grin:" },
	{ 0xD83DDE02U, ":joy:" },
	{ 0xD83DDE1AU, ":-*" },
	{ 0xD83DDE1AU, ":*" },
	{ 0xD83DDE06U, "xD" },
	{ 0xD83DDC4DU, ":like:" },
	{ 0xD83DDC4EU, ":dislike:" },
	{ 0x261DU, ":up:" },
	{ 0x270CU, ":v:" },
	{ 0xD83DDC4CU, ":ok:" },
	{ 0xD83DDE0EU, "B-)" },
	{ 0xD83DDE0EU, "B)" },
	{ 0xD83DDE03U, ":-D" },
	{ 0xD83DDE03U, ":D" },
	{ 0xD83DDE09U, ";-)" },
	{ 0xD83DDE09U, ";)" },
	{ 0xD83DDE1CU, ";-P" },
	{ 0xD83DDE1CU, ";P" },
	{ 0xD83DDE0BU, ":-p" },
	{ 0xD83DDE0BU, ":p" },
	{ 0xD83DDE14U, "3(" },
	{ 0xD83DDE1EU, ":-(" },
	{ 0xD83DDE1EU, ":(" },
	{ 0xD83DDE0FU, ":]" },
	{ 0xD83DDE22U, ":'(" },
	{ 0xD83DDE2DU, ":_(" },
	{ 0xD83DDE29U, ":((" },
	{ 0xD83DDE28U, ":o" },
	{ 0xD83DDE10U, ":|" },
	{ 0xD83DDE0CU, "3-)" },
	{ 0xD83DDE0CU, "3)" },
	{ 0xD83DDE20U, ">(" },
	{ 0xD83DDE21U, ">((" },
	{ 0xD83DDE07U, "O:)" },
	{ 0xD83DDE30U, ";o" },
	{ 0xD83DDE33U, "8|" },
	{ 0xD83DDE32U, "8o" },
	{ 0xD83DDE37U, ":X" },
	{ 0xD83DDE08U, "}:)" },
};
```

**Comment by JimmyS83** [comment] 2017-07-18 06:34
I would create PR (https://github.com/JimmyS83/tdesktop/commit/e22ff49c4dc2f13bc56c552ac0bcde52487f6664) but I have Czech language added in my repo (I maintain it on regular base, and github helps me to offer it to czech people through http://telegram.zde.cz)...

**Comment by stek29** [comment] 2017-07-18 13:30
@JimmyS83 Just rebasing that commit on top of upstream dev should do the trick.
However, I highly doubt it would be merged.

Also, what's the point of maintaining a fork just for language? Just offer them a strings file, and let them chose it by shift-clicking on "change language" in settings or typing `loadlang`.

You can have a look at what https://t.me/langbot offers.

**Comment by stek29** [comment] 2017-07-18 13:35
oh, and also #307

**Comment by JimmyS83** [comment] 2017-07-18 13:35
_Also, what's the point of maintaining a fork just for language?_

Ability to easilly track changes between releases, and keep history for older versions (some of version you cant install on older androids, some variables was renamed), one single link with always up-to-date version ...  

It worth effort, Telegram dropped transifex, and until they didnt have up and running lang. platform, which I could contribute, this is in my opinion best all-round solution, unfortunatelly.

**Comment by stek29** [comment] 2017-07-18 13:40
> Telegram dropped transifex

No, They've just made it private :)
@MasterGroosha is maintaining russian localizations, and you can have a look at https://github.com/MasterGroosha/telegram-ru-translation.
Maybe he can help you.

**Comment by MasterGroosha** [comment] 2017-07-18 13:44
@stek29 it's completely unofficial.

**Comment by stek29** [comment] 2017-07-18 13:46
@MasterGroosha I know, so is @JimmyS83's fork. But I guess maintaining .strings files is better than maintaining a fork.

**Comment by JimmyS83** [comment] 2017-07-18 19:11
_No, They've just made it private :)_

A while ago I made my best, really, to try contribute and offer official Czech language support. I send msgs to Markus Ra, contact developers, already translate 100% of Android, Desktop and Web version. I tried to join via transifex.. Contact transifex admins, telegram admins, former Czech contrubuter @transifex. But unfortunatelly, I can officialy contribute. According John Preston - https://github.com/telegramdesktop/tdesktop/pull/3367  transifex should be dropped. And I should wait for new platform. Thats latest news Ive got, until then, no news or updates :(

So it is to me, since I really want to make Telegram accesible also for Czech users, which dont know english well (old folks, and also new users are pretty picky when choosing messaging platform: absence of native language is big deal for them), I decide to support it best I can.

Of course it isnt well propagated (most users just download it from Google Play and write review: no Czech language, uninstall etc)., but I really think Telegram is best messaging software and platform nowadays, so I keep working on translation since then.

**Comment by stek29** [comment] 2017-07-18 19:32
> I send msgs to Markus Ra

Well, I'm not sure if it was a good idea. Markus is a very busy person, and he may read your message but never answer -- sometimes :)

> According John Preston - #3367 transifex should be dropped. And I should wait for new platform. Thats latest news Ive got, until then, no news or updates :(

Well, AFAIK, currently "cloud" translations are taken from transifex -- "the new platform" is just a new way to deliver translation updates.

> most users just download it from Google Play and write review: no Czech language, uninstall etc

Russian is almost same (it's even a bit better actually -- it's probably going to be added to cloud localizations).

I really hope that after "new platform" stabilization it'd become more open. 

Also, speaking of transifex getting closed. At first Telegram was considered an open source project, so it was free for TG, and it also was open. But one day Transifex showed a message about payment due, and shortly after that Telegram translations became inaccessible through the web interface. Recently they've become inaccessible through the API too. _This paragraph is my personal opinion, it's not backed by any facts or proofs, and I'm not even sure about it_.

But what I'm trying to say is that making users to switch to your fork isn't such a good idea. Applying custom localization files can (and should) be used on TDesktop -- same way which is used on iOS and Android. 
Webogram doesn't support custom locales, so it makes sense to have a fork of it. But not for TDesktop.

Anyway, this is not related to this issue, which is duplicate of #307 and many others.

**Closed** 2017-08-30 12:35 UTC
