### ISSUE TITLE
[Feature Request] An Option To Hide "All Chats" Folder

### ISSUE THREAD

**Issue by aminhitman** [telegramdesktop/tdesktop#24750] opened 2022-07-04 10:41 UTC
### Is your feature request related to a problem?

It's an eyesore to see that despised mess of all chats in one place mixed together.

### Describe the solution you'd like

An option to hide "All Chats" from the list of folders would be very nice both in desktop and mobile version
Since the reason for the creation of folders was to eliminate clutter and mess of chats
Having a section called "All Chats" exactly violates this reason and creates the same confusion and redundancy.

### Describe alternatives you've considered

An alternative would be to never open that "All Chats" folder. But it's right there, at the top, unnecessarily taking up space, even AFTER I arrange it all nice-and-tidy-like into separate folders.

### Additional context

Can't think of any.

**Comment by RememberTheAir** [comment] 2022-07-05 14:26
Hiding the "all chats" folder is a premium feature, you can do it by subscribing to Telegram Premium (also a duplicate of #7869/#7533)

By the way, judging from what you've written in the issue description, I think you might not be aware of this: you can archive the chats you've already organized in your folders (right click -> archive), and they will not appear in your main chats list (unless they are not muted, in this case they will be un-archived the moment you receive a new message). This way your "all chats" view will be less way chaotic, and you can keep the "clutter"/"low priority" content in your folders

**Closed** 2022-07-05 15:09 UTC
Labels: enhancement
