### ISSUE TITLE
Provide a Build for Debian Wheezy or better build instructions

### ISSUE THREAD

**Issue by Hypfer** [telegramdesktop/tdesktop#1329] opened 2015-11-25 17:36 UTC
The current released build doesn't work with glibc 2.13. Please provide a working build or fix the Build instructions.
Installing QT Creator and messing with it's settings can't be the way to go. It just can't. Stuff like this needs to be automated.

**Comment by luckyluke** [comment] 2016-10-21 19:12
duplicate of #253

**Comment by Hypfer** [comment] 2016-10-21 19:15
Not really. Also, what the heck.
Since when do non maintainers do this kind of shit?

**Comment by stek29** [comment] 2016-10-22 05:45
Maintainer != Developer.

**Comment by tdesktop-closer** [comment] 2017-11-08 16:03
Hey there!

We're automatically closing this issue since there was no activity in this issue since 382 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

<sub>(Please note that this is an [automated](https://github.com/auchri/github_auto_closer) comment.)</sub>

**Closed by tdesktop-closer** 2017-11-08 16:03 UTC
Labels: auto closed, help wanted
