### ISSUE TITLE
[Question] Download photos with sent\received datetime as filename?

### ISSUE THREAD

**Issue by Trost123** [telegramdesktop/tdesktop#4951] opened 2018-07-08 04:35 UTC
Telegram surely remembers when did I send\receive photos, but if I try to download them for local backup, all files are named with current date and time, not the time they were taken.
Is there any way to get those photos with sent\received date as a filename instead?
Thanks.

**Comment by stek29** [comment] 2018-07-08 14:58
this is probably done on purpose, so recently downloaded photos can be easily found.

**Comment by Nachtalb** [comment] 2018-12-26 14:46
> How about letting us download the file with the file name it originally had, so that I can have human readable file names on stuff? 

To my knowledge, Telegram only remembers the filename for files (uncompressed) and not for photos (compressed). At least this is the case for the Bot API https://core.telegram.org/bots/api#document, https://core.telegram.org/bots/api#photosize

**Comment by Draco18s** [comment] 2018-12-27 00:32
That it does. Its the compressed files which get shared that I have no ability to source. Sometimes reverse image search works, but only about 30% of the time. I can't do an md5 search (a few places support this) because the file's been compressed, so the hash changes.

**Comment by Draco18s** [comment] 2020-10-23 13:22
Considering that just 17 days ago a feature request was closed as a duplicate of this one: Stalebot you are bad at your job.

**Comment by Aokromes** [comment] 2021-02-17 19:54
such feature belongs to https://bugs.telegram.org/

**Closed by Aokromes** 2021-02-17 19:54 UTC
Labels: api issue, question
