### ISSUE TITLE
No sound in telegram-client

### ISSUE THREAD

**Issue by newmrdenis** [telegramdesktop/tdesktop#8000] opened 2020-06-05 14:01 UTC
### Steps to reproduce
1. Install any version of telegram-desktop on KDE Neon
2. Start to play any sound inside telegram, e.g. video massage

### Expected behaviour
Sound play

### Actual behaviour
No sound is there

### Configuration
**Operating system:**
KDE Neon 

**Version of Telegram Desktop:**
2.1.7

**Installation source (Linux Only)** 
Bin, Snap

**Used theme**:
Dark (idk may be something different you meant)

In sound menu of KDE during playback It displays that sound goes somewhere (empty field) though I have only two sinks Sound card and HDMI. When I toggle it to HDMI nothing happens. I thought It was by Snap version of App (It is sort of typical problems) but on Bin same behavior appears. I have tried a lot of different solutions including #5481 in particular https://github.com/telegramdesktop/tdesktop/issues/5481#issuecomment-579402940
But nothing worked

Finally I got like a solution It needs reloading of pulseaudio after os initialization and restarting telegram client then sound appears.

**Comment by ilya-fedin** [comment] 2020-06-05 14:48
Can't reproduce
```
Operating System: KDE neon 5.18
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.3.0-53-generic
OS Type: 64-bit
```

**Comment by Aokromes** [comment] 2020-07-14 17:26
no answer over a month, closing, if this bug is still valid open a ticket with updated versions of your OS and telegram.

**Closed by Aokromes** 2020-07-14 17:26 UTC
Labels: linux

**Comment by newmrdenis** [comment] 2020-07-15 00:15
I still trying to find wrongs in my system.) And finally can say only after reinstalling my system apparently.
And yep, I still experience this bug.

**Comment by ilya-fedin** [comment] 2020-07-15 00:18
> I still trying to find wrongs in my system.

Maybe you have a not typical sound system? E.g. more than two channels? Or some pro audio card? Any info about your system would be useful.

**Comment by newmrdenis** [comment] 2020-07-15 00:50
No, nothing special. Ordinary notebook with HDMI and analog port. It seems the problem really lies on my system, because the sound works from time to time. I plan to stay at Neon, that's why I will tell when I am 100% sure that's problem not with my system. Thank you very much.

**Comment by ilya-fedin** [comment] 2020-07-15 01:32
1. Start a video/audio in tdesktop and check on "Playback" and "Output Devices" tabs that the stream and the device are not muted
2. Start alsamixer, press F6, select your sound card and check that outputs are not muted (you should have OO, not MM)
3. If nothing helps, try to disable pulseaudio and check if the issue persits with plain alsa:
1.. `mv /usr/share/alsa/pulse-alsa.conf{,bak}`
2.. Set `autospawn = no` in `/etc/pulse/client.conf`
3.. `pulseaudio -k`
4.. Don't forget to restart tdesktop.
