### ISSUE TITLE
Unable to download files in telegram desktop only

### ISSUE THREAD

**Issue by Sibasish** [telegramdesktop/tdesktop#16588] opened 2021-07-08 07:38 UTC
Files, images, web links aren't getting downloaded on my Telegram desktop on my PC running win 10, even though I am using the latest version. I have reinstalled it twice and even checked all the settings but nothing seems wrong anywhere. It works fine when I try downloading files in the android app. I have attached the screenshots for reference.
![files](https://user-images.githubusercontent.com/8840620/124881967-8c5bc600-dfed-11eb-9b8d-20014d06d148.png)
 All the notifications and posts are coming fine but only thing is that the files aren't downloading. It was working fine till yesterday and I have never experienced such an issue unless there is some internet problem. P
![images](https://user-images.githubusercontent.com/8840620/124881996-9382d400-dfed-11eb-948f-6ce337bdb791.png)
Please let me know how can I resolve this issue.

**Comment by Kgf123** [comment] 2021-07-08 07:42
Even I have the same problem.
I thought my ISP has blocked stuff and used vpn and got the same result.
Cleared cache and tried again which just made stuff worse.
In telegram web it works properly so not telegram account problem.

**Comment by Austin70** [comment] 2021-07-08 08:54
I also have same problem

**Comment by ilya-fedin** [comment] 2021-07-08 09:07
Maybe it's a problem on server side?

**Comment by vkpraveen** [comment] 2021-07-08 09:18
I am also facing the same issue with desktop app, can some one help here. Web and android app are working fine.

**Comment by Austin70** [comment] 2021-07-08 09:20
could it be related to windows 10 update problem..i think this happened after the update i think

**Comment by vkpraveen** [comment] 2021-07-08 09:22
@Austin70 It worked till yesterday for me and there are no updates in my system from last week.

**Comment by vkpraveen** [comment] 2021-07-08 10:18
> Maybe it's a problem on server side?

Can you confirm on this?

**Comment by ilya-fedin** [comment] 2021-07-08 10:44
> Can you confirm on this?

Can I confirm the issue? No, I have no problems with media loading

**Comment by Kgf123** [comment] 2021-07-08 11:26
> 
> 
> Maybe it's a problem on server side?

No it works on telegram web and telegram phone. Only the desktop app has a problem.

**Comment by Kgf123** [comment] 2021-07-08 11:27
> 
> 
> could it be related to windows 10 update problem..i think this happened after the update i think

I have windows 7 and still have the same problem so it can not be windows 10 problem.

**Comment by ilya-fedin** [comment] 2021-07-08 11:28
> No it works on telegram web and telegram phone. Only the desktop app has a problem.

Applications may connect to the server differently and the server may break only tdesktop. Given that I'm not affected, this can be a sign that not all DCs affected.

**Comment by Kgf123** [comment] 2021-07-08 11:30
> 
> 
> > No it works on telegram web and telegram phone. Only the desktop app has a problem.
> 
> Applications may connect to the server differently and the server may break only tdesktop. Given that I'm not affected, this can be a sign that not all DCs affected.

I have a US account and another Indian account. So it has different DCs. Both show problem in TG desktop but works in telergam web and telegram app in phone.

**Comment by ilya-fedin** [comment] 2021-07-08 11:32
> I have a US account and another Indian account. So it has different DCs. Both show problem in TG desktop but works in telergam web and telegram app in phone.

But I still don't have any problems.

**Comment by vkpraveen** [comment] 2021-07-08 11:47
I have uninstalled and installed still same issue, tried with latest release also tried with beta version. Just to cross also tried with older version as well but still the same issue.
Web and mobile app working as is with the same network.

**Comment by Kgf123** [comment] 2021-07-08 13:31
> 
> 
> I have uninstalled and installed still same issue, tried with latest release also tried with beta version. Just to cross also tried with older version as well but still the same issue.
> Web and mobile app working as is with the same network.

as @ilya-fedin told [here](https://github.com/telegramdesktop/tdesktop/issues/16588#issuecomment-876361732) I think telegram servers are breaking on telegram desktop only.....

**Comment by 6388504347** [comment] 2021-07-08 15:15
Why is the photo not downloding, is there a problem? 
please do it right...

**Comment by 6388504347** [comment] 2021-07-08 15:15
Plzz help me

**Comment by Aokromes** [comment] 2021-07-08 15:50
i wonder if it's datacenter issue, because they work for me.
https://i.imgur.com/4GqAxT5.png

**Comment by 6388504347** [comment] 2021-07-08 16:17
When will this problem be right fix this problem soon plzz sir

**Comment by Demetri0** [comment] 2021-07-08 16:29
Looks like I have a similar problem in Ubuntu. Restart of telegram solves the problem, but it then appears after some time.
It starts after upgrade to 2.8 version. (But actually it is still 2.8.0 in my repository, maybe it was fixed in some patch version)

**Comment by john-preston** [comment] 2021-07-08 16:34
@Sibasish @Kgf123 @Austin70 @vkpraveen @6388504347

Please post your Telegram Desktop version. Don't write "latest version", because there are usually at least two latest versions (stable and beta) and some different "latest" versions in Linux repositories.

Which version do you see at the bottom of the left main menu?

**Comment by john-preston** [comment] 2021-07-08 16:35
Also if somebody with the problem is ready to share debug logs, you can contact me at t.me/preston

**Comment by Aokromes** [comment] 2021-07-08 16:58
https://t.me/TelegramDesktopTalk/67675

**Closed by Aokromes** 2021-07-08 16:58 UTC
Labels: question
