### ISSUE TITLE
Telegram Desktop to detect timezone change

### ISSUE THREAD

**Issue by vladon** [telegramdesktop/tdesktop#3904] opened 2017-09-18 14:39 UTC
This is a feature request:

Please make Telegram Desktop to detect timezone change (in Windows, for example).

How to reproduce:

Open Telegram Desktop.
Open some chat.
Open system datetime settings and change timezone.
Continue chatting in Telegram Desktop.
Time of the messages will be with previous timezone setting.
Restart of Telegram Desktop fixes this, but other Windows apps can detect timezone change (catch WM_TIMECHANGE for example).

**Comment by loganrosen** [comment] 2017-09-29 04:04
This is a duplicate of #1576.

**Closed** 2017-09-29 04:57 UTC
