### ISSUE TITLE
[Feature Request] Gif SIZE !

### ISSUE THREAD

**Issue by Unkn9wn1** [telegramdesktop/tdesktop#7119] opened 2020-01-31 10:04 UTC
Hi, why you guys removed gif size?
we need it, make it ok please

**Comment by RememberTheAir** [comment] 2020-01-31 10:07
Duplicate of #7061

**Comment by Unkn9wn1** [comment] 2020-01-31 10:12
Yes, it's because it's a problem for me, i want is back

**Comment by RememberTheAir** [comment] 2020-01-31 10:18
One issue is enough. Duplicate issues will be closed

**Comment by Unkn9wn1** [comment] 2020-01-31 10:40
i know, but before closing, developers read it 😄

**Closed** 2020-01-31 11:05 UTC
