### ISSUE TITLE
[Feature Request] Add quick "add to folder ..." button in chat right click menu

### ISSUE THREAD

**Issue by alloky** [telegramdesktop/tdesktop#8129] opened 2020-06-24 11:05 UTC
### Is your feature request related to a problem?
The folder editing is too long. You need click several time and find concrete chat, in order to add this chat for specific folder. This is the most frequent action that user need to execute, while working with folders.

### Describe the solution you'd like
Just add "add to folder ..." button to chat context menu, where you choose folder, in which you would like to add this chat. This will decrease number of action from 4 + typing to 3 fast and convenient clicks "under the hand". This will save a lot of time for everyone.

**Comment by RememberTheAir** [comment] 2020-06-24 11:13
Duplicate of #7927

**Closed** 2020-06-24 13:15 UTC
