### ISSUE TITLE
fontconfig warnings while using telegram

### ISSUE THREAD

**Issue by shirishag75** [telegramdesktop/tdesktop#517] opened 2015-02-24 18:25 UTC
Hi all, 
I am running telegram and coming across these fontconfig warnings while running it. Am running the latest stable 0.7.17 :-

```
$ ./Telegram
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```

Can somebody figure this out.

**Comment by EmptyStackExn** [comment] 2015-02-25 22:38
Would you mind at least give some details regarding the operating system you are running ?

**Comment by bil-elmoussaoui** [comment] 2015-02-25 22:40
I had the same thing on ubuntu 14.04 (elementaryt os 0.3 beta 2) pantheon dekstop manager! Linux Kernel 3.19

**Comment by shirishag75** [comment] 2015-02-26 11:55
I am running on Debian Jessie/testing (amd64) . I am running kernel 3.16.0-4 . Please let me know if you need any more info. about my setup.

**Comment by icaroperseo** [comment] 2015-03-04 01:55
I also have the same problem with both versions (stable & dev):

```
user@system~> $ ./Telegram
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```

Currently I'm using **Slackware x86_64 MATE**. Moreover, the *fontconfig* directory is automatically created in my *home* directory each time it starts (if not exist the directory). It seems like does not use the *~/.cache/fonconfig* as default.

**Comment by shirishag75** [comment] 2015-03-15 15:55
which fonts are these, if they are freely-licensed then we could get them packaged for various GNU/Linux distributions and let telegram just check for the existence of the fonts. 

If not, then probably something else.  Do think that the warnings themselves say something about how good/bad the fonts are but unable to know how to fix it.

**Comment by neteler** [comment] 2015-06-04 06:36
The same thing happens on Fedora 21 (using the current Telegram Desktop version 0.8.21)

**Comment by rcoacci** [comment] 2015-06-20 15:19
It seems the version of fontconfig used in TDesktop is too old, see: https://bugs.freedesktop.org/show_bug.cgi?id=70258, this seems to be the problem with Steam too.

**Comment by KeiroD** [comment] 2015-11-29 01:58
Try `rm -rf` the relevant `fontconfig` file that Telegram complains about. After that, run `fc-cache -fv`. Should work for just about every distro, but if not, google how to do a font cache rebuild for your specific distro.

This should resolve the fontconfig error for you.

**Comment by lindhe** [comment] 2016-01-21 10:07
That didn't do it for me. I'm running Arch Linux. Any idea?

**Comment by cyberkatze** [comment] 2016-04-23 18:17
```
Ubuntu 16.04
Linux AE 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
c:~/dev/programms/Telegram$ ./Telegram &
[1] 2466
c:~/dev/programms/Telegram$ Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
c:~/dev/programms/Telegram$ 
```

v 0.9.42 stable

**Comment by shirishag75** [comment] 2016-04-23 18:49
@KeiroD your instructions worked like a charm. running just a bit behind stable, 0.9.33. Would try to see if the updater works or would have to get the new version manually.

**Comment by KeiroD** [comment] 2016-04-23 21:40
@shirishag75 Glad to hear it worked for ya.

The updater worked for me just fine after I did the `fontconfig` rebuild. You should be able to update Telegram using the updater.

**Comment by liuxueyang** [comment] 2016-05-04 14:01
@KeiroD Thanks for your help, it works on openSUSE Leap 42.1 :+1:

**Comment by frangio** [comment] 2017-04-24 00:13
How is deleting this file a solution? This is a file installed by a different package!

Telegram complains because it's linked to an old fontconfig version, not because the file is at fault.

**Comment by fancywriter** [comment] 2017-07-12 09:04
@frangio why do you think that telegram is linked to an old fontconfig version? I don't see any exact version specified in `Telegram/gyp/qt.gypi`.

**Comment by KeiroD** [comment] 2017-07-12 11:35
Deleting the file and using the command I provided to rebuild the cache solves the problem. I don't see what the problem is?

**Comment by mjg** [comment] 2017-08-04 13:56
@KeiroD These files are installed by a distro package (fontconfig), so simply removing looks like an odd solution - telegram's fontconfig can't cope with conf files that the system's fontconfig can cope with, apparently.

**Comment by telmotrooper** [comment] 2018-03-25 19:47
For those on Arch Linux who, like me, couldn't fix it with the instructions by @KeiroD and @lindhe, I'd just like to point out that Telegram has finally been released in the official repositories, so you can get a working version with a simple `sudo pacman -S telegram-desktop`.

**Comment by Aokromes** [comment] 2018-11-13 16:46
Test after 8ee958bfa08b2ba87cffaf8de4b65b6890e59ea3

**Closed** 2018-12-08 21:56 UTC
Labels: bug, linux, waiting for answer

**Comment by shirishag75** [comment] 2018-12-19 17:45
With the latest telegram desktop the issue is no longer there. There are issues with font issues but that's a separate issue.
