### ISSUE TITLE
No longer able to select and copy part of a code block

### ISSUE THREAD

**Issue by lilydjwg** [telegramdesktop/tdesktop#23968] opened 2022-01-24 12:35 UTC
### Steps to reproduce

1. Someone pastes lines of logs as a code block
2. I need to copy part of it (e.g. a path or error message)
3. Try to select that part

### Expected behaviour

That part is selected and I can copy it elsewhere.

### Actual behaviour

The whole code block is selected and then copied.

Also, the code block is only copied to the `CLIPBOARD` selection but not `PRIMARY` one, despite it's selected briefly.

I don't care what a click on the code block does, but if I drag over text on it, the dragged-over part should be selected.

### Operating system

Arch Linux

### Version of Telegram Desktop

3.4.8

### Installation source

Other (unofficial) source

**Comment by RememberTheAir** [comment] 2022-01-24 17:31
Duplicate of #23938

**Closed** 2022-01-24 18:43 UTC
Labels: bug
