### ISSUE TITLE
Multiaccount

### ISSUE THREAD

**Issue by LeshaRB** [telegramdesktop/tdesktop#5421] opened 2018-11-25 15:12 UTC
Can you add support multi account?

**Comment by RememberTheAir** [comment] 2018-11-25 16:31
Duplicate of #4987 #4261 #4328 #4447 #4448 #4744 #4889

**Comment by RememberTheAir** [comment] 2018-11-25 16:33
Oh and how to forget #5269

**Closed** 2018-11-25 17:16 UTC
