### ISSUE TITLE
Start minimized option doesn't work

### ISSUE THREAD

**Issue by ykurganov** [telegramdesktop/tdesktop#7948] opened 2020-05-26 11:27 UTC
### Steps to reproduce
1. Go to Settings -> Advanced; check "Start Telegram on system start" and "Start minimized"
2. Restart Kubuntu

### Expected behaviour
Telegram should start minimized in system tray

### Actual behaviour
Telegram starts with its window open

### Configuration
**Operating system:** Kubuntu 20.04 LTS

**Version of Telegram Desktop:** telegram-desktop:amd64/focal 2.0.1+ds-1build1 uptodate

**Installation source (Linux Only):** sudo aptitude install telegram-desktop

**Used theme**: Kubuntu / Breeze

### Workaround
1. Check "Start Telegram on system start" and "Start minimized" in Telegram settings
2. Go to KDE System Settings -> Startup and Shutdown -> Session Control. Enter in "Applications to be excluded from sessions" telegram-desktop (it's comma or colon separated list)

**Comment by ilya-fedin** [comment] 2020-05-26 20:04
Please check on the latest version

**Comment by ilya-fedin** [comment] 2020-05-26 20:06
> **Used theme**: Kubuntu / Breeze

Don't forget that KDE have it's own session restoring functionality and it will open tdesktop window.

**Comment by nourserry** [comment] 2020-05-28 15:54
Happens on the latest snap for Ubuntu 20.04 LTS
Snap: telegram-desktop         Version 2.1.7              Rev: 1634  latest/stable

**Comment by ilya-fedin** [comment] 2020-05-28 15:56
Can't reproduce.

**Comment by nourserry** [comment] 2020-05-28 16:04
The current command I have in Startup Applications:
`env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/telegram-desktop_telegram-desktop.desktop /snap/bin/telegram-desktop -- %u`
Not sure if this helps, but I removed it and will try again to enable it through the app settings

**Comment by ilya-fedin** [comment] 2020-05-28 16:07
> The current command I have in Startup Applications:

It's wrong, it should have `-autostart` argument :thinking:

**Comment by nourserry** [comment] 2020-05-28 16:51
changing it to 
`env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/telegram-desktop_telegram-desktop.desktop /snap/bin/telegram-desktop -autostart`
worked, thanks.
Any idea why isn't the command added to Startup Applications automatically when enabling it from settings?

**Comment by ilya-fedin** [comment] 2020-05-29 06:39
> Any idea why isn't the command added to Startup Applications automatically when enabling it from settings?

Are you sure that previous command was added by tdesktop and not by some daemon or you?

**Comment by nourserry** [comment] 2020-05-29 16:58
The previous one added by selecting Telegram through gnome tweaks Startup Apps
I didn't modify the command myself.
I did that because enabling Telegram startup settings didn't actually do anything

**Comment by ilya-fedin** [comment] 2020-05-29 17:19
> I did that because enabling Telegram startup settings didn't actually do anything

Oh, I tested this feature with installed package with `--devmode`. Looks like snap sandbox doesn't allow access for files and dirs started with a dot. Probably, these checkbox should be removed from snap since snap doesn't allow this and doesn't have any api for adding to autostart.

**Comment by ykurganov** [comment] 2020-05-29 18:13
I found a workaround:

1. Uncheck "Start Telegram on system start" and "Start minimized" in Telegram settings
2. Go to KDE System Settings -> Startup and Shutdown -> Session control. Enter in "applications to be excluded from sessions" telegram-desktop (it's comma or colon separated list)
3. Go to KDE System Settings -> Startup and Shutdown -> Autostart. Add Telegram to startup list and modify command to "telegram-desktop -startintray -- %u"
4. Restart and enjoy

But the bug still exists. If you unable to fix it, may be just hide this settings in Telegram if KDE was detected?

**Comment by ilya-fedin** [comment] 2020-05-29 18:18
>     3\. Go to KDE System Settings -> Startup and Shutdown -> Autostart. Add Telegram to startup list and modify the command to "telegram-desktop -startintray -- %u"

You can just leave the checkboxes checked

> But the bug still exists. If you unable to fix it, may be just hide this settings in Telegram if KDE was detected?

This is not a bug, but a KDE's feature.

**Comment by ykurganov** [comment] 2020-05-29 19:02
> You can just leave the checkboxes checked, there is no need to create it yourself
I tried and confirm

Workaround:
1. Check "Start Telegram on system start" and "Start minimized" in Telegram settings
2. Go to KDE System Settings -> Startup and Shutdown -> Session control. Enter in "Applications to be excluded from sessions" telegram-desktop (it's comma or colon separated list)
3. Restart and enjoy

Maybe display some hints in Telegram UI for KDE users?
Even better, maybe Telegram itself can change this system setting?

**Comment by ilya-fedin** [comment] 2020-05-29 19:10
> Maybe display some hints in Telegram UI for KDE users?

Some time ago I found that Qt gives API to interact with session manager. The next version should ignore this KDE feature.

**Comment by nourserry** [comment] 2020-05-30 17:14
> > I did that because enabling Telegram startup settings didn't actually do anything
> 
> Oh, I tested this feature with installed package with `--devmode`. Looks like snap sandbox doesn't allow access for files and dirs started with a dot. Probably, these checkboxes should be removed from snap package since snap doesn't allow this and doesn't have any api for adding to autostart.

for this command to work
`env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/telegram-desktop_telegram-desktop.desktop /snap/bin/telegram-desktop -autostart`
the app settings must be there 

@ykurganov 's command `"telegram-desktop -startintray -- %u"`
works without enabling the settings

**Comment by ilya-fedin** [comment] 2020-05-30 17:18
Yes, that's right

**Comment by ilya-fedin** [comment] 2020-05-30 17:18
`-- %u` makes no sense for autostart desktop file

**Comment by Aokromes** [comment] 2020-06-03 15:48
fixed on 2.1.8

**Closed by Aokromes** 2020-06-03 15:48 UTC
