### ISSUE TITLE
No tray icon under gnome 3

### ISSUE THREAD

**Issue by FeiWongReed** [telegramdesktop/tdesktop#944] opened 2015-07-28 17:49 UTC
Just subject.
There is no tray icon when running under gnome 3

**Comment by EmptyStackExn** [comment] 2015-08-01 10:14
I have the same problem in GNOME 3 Fallback Session. According to the changelog. It appears that, since 0.8.41 ("*use Qt tray icon in all Linux systems*"), @telegramdesktop will drop `libappindicator` and **only** use `QSystemTrayIcon`. Is that correct ?

As a matter of fact, the icon I had has disappeared as I only use `libappindicator`... I thought we  solved this problem already in issue #491 ? I do not understand this design choice.

**Comment by wiiiky** [comment] 2015-08-03 02:46
No tray icon problem in Fedora 22 GNOME 3.16.2

**Comment by dawidr83** [comment] 2015-08-03 18:44
no tray icon under ubuntu mate. in 0.8.38 the tray icon was ok. since update i looks like:

![screenshot-25](https://cloud.githubusercontent.com/assets/13630017/9044943/569af88e-3a20-11e5-90a1-c25fb1758801.png)

**Comment by EmptyStackExn** [comment] 2015-08-04 08:49
Fixed in 0.8.45. Thanks @telegramdesktop team. :+1:

**Comment by dawidr83** [comment] 2015-08-04 10:38
nope. still no icon. i deleted all files and user settings and downloaded the latest telegram 0.8.45 and still no tray icon.

**Comment by dario86** [comment] 2015-08-04 13:21
Same problem with Xubuntu 14.04 and Telegram Desktop 0.8.45.

![telegramtray](https://cloud.githubusercontent.com/assets/1636255/9061511/870e416e-3abc-11e5-8dcf-0df727b714fd.png)

**Comment by kanishkablack** [comment] 2015-08-04 18:14
libappindicator just solved the issue

**Comment by telegramdesktop** [comment] 2015-08-05 15:31
Should be well in the last update. Try to install libappindicator, it is used instead of Qt tray icon, which is broken some times. Tried in Xubuntu right now, it does use libappindicator which is in the system by default.
![image](https://cloud.githubusercontent.com/assets/6113871/9089898/250b7f1a-3ba0-11e5-95e0-665c6ebc287a.png)

**Closed by telegramdesktop** 2015-08-05 15:31 UTC

**Comment by matheusgeres** [comment] 2016-03-16 18:52
Same problem here! 
![screenshot at 2016-03-16 15 50 56](https://cloud.githubusercontent.com/assets/6884466/13824962/07eb28f0-eb8f-11e5-9ee7-fa2f61d3521c.png)

**Comment by ol-loginov** [comment] 2016-03-17 14:46
Same problem with broken icon

Can be fixed with starting as:
`DBUS_SESSION_BUS_ADDRESS="" ~/bin/Telegram/Telegram `

**Comment by FeiWongReed** [comment] 2016-03-18 19:44
I have no libappindicator and can't install it.

Linux is not just Ubuntu.

**Comment by john-preston** [comment] 2016-03-18 20:04
@FeiWongReed I disabled Qt tray icon in gnome, perhaps it didn't work right there. So I try libappindicator and gtk_status_icon api. If both don't work I don't know how else the tray icon can work there. Perhaps Qt have fixed something already and it's implementation can be enabled in gnome, I don't know.

I know perfectly that Linux is not just anything: I can have four VMs installed for Windows testing, three VMs for OS X testing and currently thirteen (!) VMs on my work machine for Linux testing -- and all the time there arrives some new distro with his unique problems, that do not happen on any other Linux. I've already spent x10 more time on Linux tray icons than on Windows and OS X tray icons both, Linux is some kind of a nightmare for a software developer.

Do you know, which tray icon api or library is working well on your system?

**Comment by FeiWongReed** [comment] 2016-03-21 20:47
Hm. I have no idea, but now skype, goldendict and chromium displays their tray icons correctly.

So, I suppose that QtTrayIcon should be working.

What about my distro - it's gentoo with gnome 3.18.

**Comment by MCSH** [comment] 2016-04-04 00:13
On Arch Linux, gnome 3.18.4, no tray icon.

However other applications (VLC as an example) have no problem showing notifications.

**Comment by xdirex** [comment] 2016-05-19 03:39
fix:
`#!/bin/bash
export XDG_CURRENT_DESKTOP=GNOME
${HOME}/Soft/Telegram/Telegram "$@"`

**Comment by anon5** [comment] 2016-06-26 00:59
See also: https://github.com/telegramdesktop/tdesktop/issues/1975#issuecomment-228575901 — solves stuff for some.

**Comment by Noori** [comment] 2016-12-09 15:06
On Fedora 25, Gnome on Wayland, Telegram doesn't has tray icon. 
Other Qt apps like Goldendict have tray icons.

**Comment by renepavlik** [comment] 2017-01-04 13:54
Same on Cinnamon.
`XDG_CURRENT_DESKTOP` is set to `X-Cinnamon` here.

Running:
```
$ XDG_CURRENT_DESKTOP=GNOME ./Telegram
```
partially solves it, the icon **is shown**, but there is a menu without any item under the icon, and logs:

```
(Telegram:5546): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
```
The menu works correctly when the icon is hidden - as shown on the screenshots above.

**Comment by renepavlik** [comment] 2017-01-04 14:16
Thanks, @anon5, that worked perfectly, just placing it here again for highlighting the good solution:
```
dbus-launch ~/bin/TelegramDesktop/Telegram -- %u
```

**Comment by yupvr** [comment] 2017-01-13 10:32
@renepavlik I've received next error message and tray icon does not appear:
`(Telegram:15599): libnotify-WARNING **: Failed to connect to proxy`

**Comment by maxkoryukov** [comment] 2017-11-25 19:15
The problem is still here.

```
Telegram Desktop
Vesion 1.1.23
Linux Mint 18, Cinnamon 3.4.6
```

![tooltip_005](https://user-images.githubusercontent.com/8887971/33233830-88cc15e6-d23e-11e7-8806-1f3d5f5d7e80.png)

The solution by @renepavlik works (`dbus-launch /path/to/telegram/Telegram -- %u`) :+1:

Patch env (`XDG_CURRENT_DESKTOP=GNOME ./Telegram`) didn't help.

**Comment by Neasden** [comment] 2019-08-26 06:23
Fedora 30 here. Telegram does not have a tray icon. Quitting the application by closing its window does not end process, which keeps running in the background. Installed via Flathub. Version 1.8.1. Since GNOME Shell displays a drop down menu for the program in the top bar, there is a Quit button there, but that doesn't really end the process either. The only workaround to end Telegram process is by exiting with CTRL+Q.

**Comment by ph1-xyz** [comment] 2020-06-12 14:53
Fedora 31 here. Same as in @Neasden's [message](https://github.com/telegramdesktop/tdesktop/issues/944#issuecomment-524732388).
