### ISSUE TITLE
[Feature Request] grouping channels and groups and chats separately   [make diffrent attributes such as color or category]

### ISSUE THREAD

**Issue by rezaei** [telegramdesktop/tdesktop#6420] opened 2019-08-19 03:44 UTC
we need to have the ability to manage and categorize groups and channels and chats, because there are many channels and groups and chats that make me confuse and  also make telegram unhelpful,  I think its better for me if I can add these elements in the desired categorize with desired names like 'education' 'industry' 'family' 'friends' 'colleagues' 'sport' and so on ...

**Comment by ArmeF97** [comment] 2019-08-20 06:37
Duplicate of #1107

Meanwhile you can try Telefuel, Unigram, Plus Messenger, Nicegram

**Comment by 360fun** [comment] 2019-08-21 09:56
grouping chats is "a must" feature, hope to see it very very soon 🙏 
sadly right now there's nothing working for Mac desktop: Bettegram is probably dead (hope somebody revives it) and Telefuel is still in beta (they ask to put your credit card to test it...weird) and will be _free_ but **not opensource**. 😢

**Comment by ArmeF97** [comment] 2019-08-21 09:58
For now, it's better than nothing. The future can be only better :) be positive

**Comment by 360fun** [comment] 2019-08-21 10:03
I'm very positive, just need to coordinate a lot of groups and with the original app is impossible 😜 I'll keep using Bettergram until works 🌳

**Comment by ArmeF97** [comment] 2019-08-21 10:04
Unigram?

**Comment by 360fun** [comment] 2019-08-21 10:15
it's for Windows 10 only: I use Mac ;)

**Closed** 2019-08-28 11:25 UTC
