### ISSUE TITLE
"Telegram did not start correctly" message on startup. followed by crash

### ISSUE THREAD

**Issue by Zelmor** [telegramdesktop/tdesktop#1649] opened 2016-02-19 10:32 UTC
I have moved the telegram client and updater executable to my /bin folder so that I would be able to start it from the command line. The updater did not work, of course, with the folder being read only for normal users, so I have attempted to run both telegram and telegram-updater as root. No cigar, however, since then I get an error message saying that Telegram did not close properly.

Checking the logs in .TelegramDesktop I have found the following:

[2016.02.19 11:25:29] Launched version: 9024, dev: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2016.02.19 11:25:29] Executable dir: /home/zelmor/Telegram/, name: Telegram
[2016.02.19 11:25:29] Initial working dir: /home/zelmor/Telegram/
[2016.02.19 11:25:29] Working dir: /home/zelmor/.TelegramDesktop/
[2016.02.19 11:25:29] Arguments: "/home/zelmor/Telegram/Telegram"
[2016.02.19 11:25:29] Logs started
[2016.02.19 11:25:29] Connecting local socket to /tmp/#removed#..
[2016.02.19 11:25:29] This is the only instance of Telegram, starting server and app..
[2016.02.19 11:25:29] Moved logging from '/home/zelmor/.TelegramDesktop/log_start0.txt' to '/home/zelmor/.TelegramDesktop/log.txt'!
[2016.02.19 11:25:29] TCP Error: network - Network unreachable
[2016.02.19 11:25:29] HTTP Error: network error 99 - Network unreachable

**Comment by DaFri-Nochiterov** [comment] 2016-02-19 10:36
```bash
sudo ln -s /home/user/TDesktop/Telegram /usr/bin/telegram
```
Why not symbolic link?

**Comment by Zelmor** [comment] 2016-02-19 10:40
You are right, and I did realize the mistake I made. However, this does not help at all, giving me the logs in terminal:

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Segmentation fault

**Comment by telegramdesktop** [comment] 2016-02-19 10:43
@Zelmor so it does not start even if you download it from https://desktop.telegram.org and just unpack to some folder like "~/Desktop/Telegram/"?

**Comment by Zelmor** [comment] 2016-02-19 10:47
@telegramdesktop Yeah, I purged the executables and configuration files completely, downloaded the newest version from the site, 64bit Linux distribution and attempted to run as for the first time. The error box shows an option for network config, however, the box itself disappear after 1 second or so. I cannot even take a screencap of it, it's that fast. No process for telegram is running in the background, according to `ps aux | less`

**Comment by telegramdesktop** [comment] 2016-02-19 10:59
@Zelmor so it does start, but crashes somewhere in the very beginning (even before installing crash handler) :(

**Comment by Zelmor** [comment] 2016-02-19 11:03
@telegramdesktop That is correct, sorry for the misleading report title. I am unsure how to proceed on this one.

**Comment by jderuiter** [comment] 2016-02-19 11:59
I have the same problem with the segfault since yesterday with the 64-bit Linux client on Ubuntu 15.10. Removing all files and downloading the latest version again from the website did not solve this.

**Comment by Zelmor** [comment] 2016-02-19 12:14
@jderuiter Seems to be an issue with the latest version of the software. I rolled back to tsetup.0.9.18.tar.xz (had the tarball still in my Downloads) and the application started without fault.

**Comment by Zelmor** [comment] 2016-02-19 12:49
Confirmed, as the software upgrades to version 0.9.24, the segfault is back and the application breaks. 

**workaround**

My issue has been resolved by downgrading to version 0.9.18, deleting the Updater that comes along in the tarball, and starting the client. This forces you to manually check for updates, and the software does not automatically update and break on its own. 

I would propose the automatic updater to be set to an off state by default for the first run on the application in future versions.

**Comment by telegramdesktop** [comment] 2016-02-19 13:20
@Zelmor You can just disable auto update in settings. I don't understand yet how to reproduce the problem and what is causing it :( it works fine in Ubuntu 15.04 and some other distros for me.

**Comment by Zelmor** [comment] 2016-02-19 13:29
@telegramdesktop 
>You can just disable auto update in settings.

In my experience, the updater pulls the binaries on its own automatically, and will update automatically upon the next startup of the application.

Have you tried upgrading from the official 0.9.18 binaries, or you built from source? Here is the one I used, and the instructions on recreating the issue:

Purge /home/user/.TelegramDesktop, telegram binaries.
Download tsetup.0.9.18.tar.xz
Extract folder
Run Telegram executable
Log in, verify, etc.
Go to settings, wait for updater to pull the packages 
Click the restart now option when prompted
8 out of 8 times I get "Telegram did not start correctly" which disappears or freezes in place, sometimes not even showing.

My system information: Debian Stable x86_64, up to date, running XFCE with no desktop composition.

Purging then downloading the latest version from the Telegram website generates the same outcome.

**Comment by telegramdesktop** [comment] 2016-02-19 14:05
I've just tried that on Debian KDE, Manjaro XFCE and Xubuntu, all 64 bit and it all works :/ Looks like I'll have to build some amount of test binaries with detailed logging and ask someone who has crashes to run them one after another %)

**Comment by ethernet-zero** [comment] 2016-02-19 14:09
I can confirm the same issue. Since version 0.9.20 Telegram Desktop crashes upon starting.

My environment: Debian Stable 32bit up to date, using dwm.

**Comment by telegramdesktop** [comment] 2016-02-19 14:16
Well, if someone is ready to help me with testing (I'll build new versions -- something between 0.9.19 and 0.9.20 -- and ask you to run them), you can contact me at telegram.me/preston through https://web.telegram.org (for example) and I'll send you .tar.xz binaries for testing there. But I don't know how long this will take because there were _alot_ of changes, and each build (if we take Release optimized builds as close as possible to the ones that are distributed through site) takes about 20 minutes %)

**Comment by jipipayo** [comment] 2016-02-19 17:55
same issue here.
dmesg says:Telegram[3319] general protection ip:7f8fc04f5824 sp:7ffddd2cacf0 error:0 in libpthread-2.21.so[7f8fc04ec000+18000]

**Comment by riki343** [comment] 2016-02-21 10:41
telegramdesktop, I'm ready to help you with testing.

My config: ubuntu 15.10, XFCE4 env.

**Comment by telegramdesktop** [comment] 2016-02-21 17:06
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It should be fixed there (e.g. if 0.9.18 worked fine for you, this one should be working as well).

**Closed by telegramdesktop** 2016-02-21 17:06 UTC
Labels: linux
