### ISSUE TITLE
tdesktop 0.9.60 alpha crashes on file choose dialog (gentoo, kde)

### ISSUE THREAD

**Issue by kvaster** [telegramdesktop/tdesktop#2278] opened 2016-07-26 08:12 UTC
1. Start telegram
2. Try to send file
3. You'll not see file choose dialog - telegram will crash

### Configuration
gentoo ~x64, kde

**Version of Telegram Desktop:**
0.9.60alpha

### Logs
http://pastebin.com/XFuv2awH

**Comment by john-preston** [comment] 2016-07-26 08:13
@kvaster Is there a crash report submitted? Can you post a crash report tag (should be seen in the crash report submit box).

**Comment by kvaster** [comment] 2016-07-26 08:14
No. There is no crash report dialog. I've attached logs from gdb and strace. Anything else I can do ?

**Comment by john-preston** [comment] 2016-07-26 08:17
@kvaster Looks like I need to disable the gtk file chooser in KDE somehow. But it should work, not crash, anyway :(

**Comment by kvaster** [comment] 2016-07-26 08:18
@john-preston, It is working on pre 0.9.60alpha

**Comment by john-preston** [comment] 2016-07-26 08:34
@kvaster I'm afraid it does only on 0.9.56 stable — where no gtk file chooser is used. Are you sure you did check 0.9.59.alpha?

**Comment by kvaster** [comment] 2016-07-26 08:39
I'm sure. But I will recheck in few minutes.

**Comment by kvaster** [comment] 2016-07-26 08:44
@john-preston, 0.9.57alpha is the last working version.

**Comment by john-preston** [comment] 2016-07-26 08:46
@kvaster That is really strange, 0.9.57 alpha introduces the gtk chooser — it should be the first _not_ working version. Are you sure not the 0.9.56 alpha or whatever is the last working version?

**Comment by john-preston** [comment] 2016-07-26 08:47
@kvaster Please check it from scratch:

https://updates.tdesktop.com/tlinux/tsetup.0.9.57.alpha.tar.xz

**Comment by kvaster** [comment] 2016-07-26 08:49
@john-preston, I've checked all versions from scratch. Starting from 0.9.60alpha till 0.9.57alpha. 50, 59, 58 - do not work. 57 - works and shows GTK file chooser (it does not look good on kde :) )

**Comment by john-preston** [comment] 2016-07-26 09:15
@kvaster Thanks for the info. I guess it is the pkg-config pull request. I need to make a test version with the old way of linking.

**Comment by john-preston** [comment] 2016-07-26 10:38
@kvaster Can you please test that one:

https://updates.tdesktop.com/other/TelegramTest01.tar.xz

This is a 0.9.60 alpha version Debug build with other link way (the old one, not using pkgconfig).

**Comment by kvaster** [comment] 2016-07-26 10:41
No. It does'nt - same crash.

**Comment by john-preston** [comment] 2016-07-26 11:59
@kvaster Well, it won't be quick then :/ Please try out those two:

https://updates.tdesktop.com/other/TelegramTest02.tar.xz
https://updates.tdesktop.com/other/TelegramTest03.tar.xz

The 02 is a Debug build of the next-after-0.9.57.alpha version, just to be sure, that we start from a working one.

The 03 is a Debug build of the first-after-videoplayer version, just to be sure, that it crashes already.

**Comment by john-preston** [comment] 2016-07-26 12:00
@kvaster (I'm sorry to do it that way, but I can't reproduce that myself, at least in Manjaro KDE).

**Comment by kvaster** [comment] 2016-07-26 12:06
@john-preston, no problems. Test02 - no crash, gtk file chooser. Test03 - crash.

**Comment by john-preston** [comment] 2016-07-26 12:37
@kvaster And now:

https://updates.tdesktop.com/other/TelegramTest04.tar.xz

The first release with the pkgconfig usage.

**Comment by kvaster** [comment] 2016-07-27 07:49
Sorry for the delay. Test04 - doesn't work.

**Comment by john-preston** [comment] 2016-07-27 09:33
I'll have to walk through that once again :/
Because Test04 differs from Test02 only by switching to pkgconfig linking - and it starts crashing. But when I tried to go back to old linking in Test01 - it still crashed. I'll need to make several more tests, I've missed something..

**Comment by kvaster** [comment] 2016-07-27 09:52
Is there any 'standart' way to build Telegram without patched qt and without ubuntu libs ? In that case I can try to debug it myself.

**Comment by john-preston** [comment] 2016-07-27 10:46
https://updates.tdesktop.com/other/TelegramTest05.tar.xz - old
https://updates.tdesktop.com/other/TelegramTest06.tar.xz - next to old without pkgconfig
https://updates.tdesktop.com/other/TelegramTest07.tar.xz - new without pkgconfig

I'm afraid no. There is no way to build it without patched Qt, and I'm not sure there is any sense in custom build with other dependencies list, because currently it starts to crash after some small change in the way it is linked.

**Comment by kvaster** [comment] 2016-07-27 11:57
05 - works, 06 & 07 - crash

**Comment by john-preston** [comment] 2016-07-27 12:25
Looks like something goes wrong with libssl/libcrypto/libz linking. I'll have one more version for you to test, if it will work, then it's done and next alpha will have everything working :)

**Comment by john-preston** [comment] 2016-07-27 12:44
@kvaster I hope that is the last one, no way to be sure though

https://updates.tdesktop.com/other/TelegramTest08.tar.xz - with linking to local libz, libcrypto, libssl (seems like the only difference between 05 and 06).

**Comment by kvaster** [comment] 2016-07-27 12:45
Works good! No crash!

**Comment by john-preston** [comment] 2016-07-27 12:47
@kvaster wow, that's great. It has version 0.9.60 in the About, right?

**Comment by kvaster** [comment] 2016-07-27 12:48
Yes, it's 0.9.60.

**Comment by john-preston** [comment] 2016-07-27 13:33
So, please test the Release build:

https://updates.tdesktop.com/other/TelegramTest09.tar.xz

**Comment by john-preston** [comment] 2016-07-27 13:33
@kvaster So, please test the Release build:

https://updates.tdesktop.com/other/TelegramTest09.tar.xz

**Comment by kvaster** [comment] 2016-07-27 13:43
@john-preston, works good.

**Comment by john-preston** [comment] 2016-07-27 13:48
Great, thanks!
It'll be fixed in the next version then.

**Closed** 2016-08-04 18:55 UTC
