### ISSUE TITLE
Reversed message preview in RTL languages

### ISSUE THREAD

**Issue by tomer953** [telegramdesktop/tdesktop#8215] opened 2020-07-07 15:16 UTC
### Steps to reproduce
1. set the language interface to a RTL Language (ie: Hebrew: https://t.me/setlanguage/he-raw )
2. type a message start with LTR language (ie: "Hello World")
3. then in the same message, add some RTL language (ie: "שלום לכולם")
4. send the message, and view it in the preview left panel

### Expected behaviour
see the correct message: 'Hello World - שלום לכולם"
![image](https://user-images.githubusercontent.com/1807493/86802714-f6115f00-c07d-11ea-8acf-26d1f6ac0fa8.png)

### Actual behaviour
"שלום לכולם - dlroW olleH"
![image](https://user-images.githubusercontent.com/1807493/86802420-b0ed2d00-c07d-11ea-908c-40427fd4d01c.png)

### Configuration
**Operating system:** Win 10 64bit

**Version of Telegram Desktop:** 1.17.2 beta

**Comment by mugavri** [comment] 2020-07-08 09:09
QT issue
הבעיה היא בספריה של QT

**Comment by ItielMaN** [comment] 2020-10-23 13:43
> Hey there!
> 
> This issue will be automatically closed in 7 days if there would be no activity. We therefore assume that the user has lost interest or resolved the problem on their own.
> 
> Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the issue.
> 
> Thanks!

This is still an issue.

**Comment by tomer953** [comment] 2020-11-22 17:09
Not solved yet.

**Comment by ilya-fedin** [comment] 2020-11-22 23:26
Duplicate of #5518

**Closed** 2020-11-22 23:42 UTC
