### ISSUE TITLE
Screencast not working on ubuntu

### ISSUE THREAD

**Issue by a-badalyan** [telegramdesktop/tdesktop#27404] opened 2024-01-26 08:53 UTC
### Steps to reproduce

1. video call someone
2. press on "screencast" 

### Expected behaviour

screen demonstration

### Actual behaviour

call ends

### Operating system

ubuntu 22.04

### Version of Telegram Desktop

4.11.6

### Installation source

Snap

**Comment by ilya-fedin** [comment] 2024-01-26 11:48
Can't confirm, it works

**Comment by Aokromes** [comment] 2024-01-26 12:52
also, latest version is 4.11.9 / 4.11.11 (beta)

**Comment by k2biru** [comment] 2024-01-30 07:24
i'm updating to 4.14.9 stable , Ubuntu 20.04.6 LTS. 
i can confirm, screencast crash telegram.

**Comment by ilya-fedin** [comment] 2024-01-30 07:35
Sorry but reproduction steps that work for sure are required. The ones in the issue don't work, I don't get a crash. If working reproduction steps won't be provided, the issue will be closed by a bot in 2 weeks.

**Comment by k2biru** [comment] 2024-01-30 07:36
it mention on #25525. 
i think it's crash when displaying preview window when screencast

**Comment by ilya-fedin** [comment] 2024-01-30 07:40
Well, what was said in #25525 is still valid, snaps are undebuggable so if you have a crash, just switch to static binary. I won't work and nothing could be done about that until the snap platform will provide a way to provide debug symbols.

**Comment by a-badalyan** [comment] 2024-01-30 08:26
> i think it's crash when displaying preview window when screencast

Yes ! Sometimes i see moment of preview screencast window, before app will crashes

**Comment by a-badalyan** [comment] 2024-01-30 11:40
I`m install old app version - 3.6.1 - and its work

**Comment by Aokromes** [comment] 2024-01-30 12:09
works for me on ubuntu 23.10 and telegram desktop 4.14.9 to telegram desktop 4.14.9 on windows.

**Comment by ilya-fedin** [comment] 2024-01-30 16:42
Yeah, something is definitely missing in steps to reproduce

**Comment by JohananOppongAmoateng** [comment] 2024-02-04 16:41
for me the call does not end it just it says an error occured and screencast stopped

**Comment by willww64** [comment] 2024-02-07 04:46
> it mention on #25525. i think it's crash when displaying preview window when screencast

I can reproduce exactly the same issue. My environment:

Ubuntu 22.04 with Nvidia 2080Ti and drivers from Nvidia's repo (not from Ubuntu's repo). Telegram Desktop was installed from Ubuntu Software (i.e. official snap store) with latest stable version (4.14.13).

The CLI output:

```
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
D/tgvoip: === Updating voip config ===
D/tgvoip: {"enable_vp8_encoder":true,"enable_vp8_decoder":true,"enable_vp9_encoder":true,"enable_vp9_decoder":true,"enable_h265_encoder":true,"enable_h265_decoder":true,"enable_h264_encoder":true,"enable_h264_decoder":true,"audio_frame_size":60,"jitter_min_delay_60":2,"jitter_max_delay_60":10,"jitter_max_slots_60":20,"jitter_losses_to_reset":20,"jitter_resync_threshold":0.5,"audio_congestion_window":1024,"audio_max_bitrate":20000,"audio_max_bitrate_edge":16000,"audio_max_bitrate_gprs":8000,"audio_max_bitrate_saving":8000,"audio_init_bitrate":16000,"audio_init_bitrate_edge":8000,"audio_init_bitrate_gprs":8000,"audio_init_bitrate_saving":8000,"audio_bitrate_step_incr":1000,"audio_bitrate_step_decr":1000,"use_system_ns":true,"use_system_aec":true,"force_tcp":false,"jitter_initial_delay_60":2,"adsp_good_impls":"(Qualcomm Fluence)","bad_call_rating":true,"use_ios_vpio_agc":false,"use_tcp":false,"audio_medium_fec_bitrate":20000,"audio_medium_fec_multiplier":0.1,"audio_strong_fec_bitrate":7000}
[OpenH264] this = 0x0x7f74a7a13510, Warning:[Rc] iDid = 0,iContinualSkipFrames(3) is large
[OpenH264] this = 0x0x7f74a7a13510, Warning:Actual input framerate 0.000000 is different from framerate in setting 29.000000, suggest to use other rate control modes
Segmentation fault (core dumped)
```

I've tested my environment with https://mozilla.github.io/webrtc-landing/gum_test.html, which showed my environment is OK for screen sharing.
I've also tried installing telegram-desktop with apt-get, which version is 3.6.1, screen sharing works on it.

So, it seems like the problem is related to snap or some latest changes of telegram-desktop.

**Comment by ilya-fedin** [comment] 2024-02-07 11:01
if NVIDIA is indeed required to reproduce the issue then it's a big problem: no developer has NVIDIA hardware as far as I'm aware. This makes solving the problem literally impossible.

**Closed** 2024-02-14 00:17 UTC
Labels: bug, cant reproduce
