### ISSUE TITLE
[Bug] Echo and noize on voice calls (and group voice chats since 2.5)

### ISSUE THREAD

**Issue by KaMeHb-UA** [telegramdesktop/tdesktop#9980] opened 2020-12-23 13:40 UTC
### Steps to reproduce
1. Call someone
2. Try to talk and listen

### Expected behaviour
There is no echo and noize

### Actual behaviour
There is echo and noize

### Configuration
**Operating system: Manjaro Linux 20.2 Nibia with KDE 5.76.0 / Plasma 5.20.3**

**Version of Telegram Desktop: 2.5 (2.4 is affected too)**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
I've tried the next sources: official website, distribution package and snap - all of them behave the same
**Used theme**: default

**Additional information:**
Echo and noize appears only in Telegram.
There is no such problem with voice messages.
This is not about echo cancellation - it appears with seperated microphone and headphones, and even if microphone is turned off

**Comment by twizmwazin** [comment] 2020-12-24 05:38
I am noticing something similar on Windows 10 in the new voice chats, there does not appear to be any echo cancellation present, Version 2.5.1, installed from the windows store. A friend was able to test on the cross platform client for Mac, and did not appear to have the same issue.

**Comment by KaMeHb-UA** [comment] 2020-12-26 21:30
@twizmwazin sorry, I was not as clear as it possible, so I've added some additional information

**Comment by Aokromes** [comment] 2020-12-26 22:46
iirc it was said it will be implemented soon.

**Comment by cskr** [comment] 2021-01-11 13:19
I experience this when using Telegram desktop app on Debian. The other person in the voice call can hear their own voice echoed back. The echo is present even if headphones are connected.

Other voice chat applications like Google Meet and Jitsi are not exhibiting this on the same system.

**OS:** Debian Unstable/Sid
**Desktop Environment:** 3.38.2
**Telegram Desktop App Version:** 2.2

**Comment by noname-3** [comment] 2021-01-26 14:14
Please tell me when this bug will be approximately fixed, because an important function of the messenger does not work correctly ?

**Comment by Aokromes** [comment] 2021-01-26 14:15
> Please tell me when this bug will be approximately fixed, because an important function of the messenger does not work correctly ?

echo cancelation will be implemented platform wide.

**Comment by noname-3** [comment] 2021-01-26 18:20
> > Please tell me when this bug will be approximately fixed, because an important function of the messenger does not work correctly ?
> 
> echo cancelation will be implemented platform wide.

You misunderstood me, I will write differently, a fix for this bug is under development and will be released with the next telegram release?

**Comment by Aokromes** [comment] 2021-01-26 20:20
> > > Please tell me when this bug will be approximately fixed, because an important function of the messenger does not work correctly ?
> > 
> > 
> > echo cancelation will be implemented platform wide.
> 
> You misunderstood me, I will write differently, a fix for this bug is under development and will be released with the next telegram release?

"echo cancelation will be implemented platform wide." means this bug will be fixed some day, on all telegram aplications.

**Comment by KaMeHb-UA** [comment] 2021-01-31 09:45
@Aokromes, please take a look at Additional Information section:
![image](https://user-images.githubusercontent.com/20382677/106379403-671aba00-63b4-11eb-9681-9e63fa043787.png)

But now calls are working as expected (at least in 2.5.7). If @cskr confirms everything is ok I think that you may close this issue

**Comment by cskr** [comment] 2021-02-14 02:58
The issue is resolved for me too in 2.5.8.

**Closed** 2021-02-14 06:10 UTC
