### ISSUE TITLE
macOS autocorrect not working, some other native keyboard features not working

### ISSUE THREAD

**Issue by NeverwinterMoon** [telegramdesktop/tdesktop#5268] opened 2018-10-16 12:12 UTC
### Expected behaviour
- Autocorrect should work, it does work in any other macOS app that I use
- When holding and pressing some of the letters that have slight variations in other languages, it should show a popup with all possible variations. For example, if I press and hold "o" in any other macOS app I use, the popup will display: ô, ö, ò, ó, œ, ø, ō, õ

### Actual behaviour
- No autocorrect altogether 
- No popup showing variations of letters

### Configuration
**Operating system: macOS 10.13.6**

**Version of Telegram Desktop:**
1.4.3 (and any other, actually)

**Comment by john-preston** [comment] 2018-10-16 12:15
@NeverwinterMoon In Qt input fields this doesn't work :( at least in Qt 5.6.2 that I'm using.

**Comment by john-preston** [comment] 2018-10-16 12:52
@NeverwinterMoon Telegram Desktop uses Qt widgets, not QML.

**Comment by NeverwinterMoon** [comment] 2018-10-16 13:02
@john-preston No plans to move to some other framework then? For a service that is built for messaging, it certainly makes sense to have an app that supports one of the most handy OS features.

I use Telegram in multiple languages, so I would benefit greatly from macOS dictionary highlights. I also keep forgetting that Telegram ignores that feature - I do use a lot of apps where I type on macOS (Bear, for example) and all of them support predictive text/highlights :(

**Comment by john-preston** [comment] 2018-10-16 13:06
@NeverwinterMoon Rewrite Telegram Desktop in other framework will mean rewrite pretty much all the Telegram Desktop :( You can try the native macOS app (non cross-platform), it should have those features: https://macos.telegram.org

**Comment by NeverwinterMoon** [comment] 2018-10-16 13:10
@john-preston I actually tried the other client just 30 minutes ago. Not only I didn't like it (lacking some UI things I like in your app), but it still has no autocorrect or error highlighting!

But it does have showing variations of letters (when pressing and holding some letter for a long time). This is a nice but very minor feature. I needed the predictive text much greater.

**Comment by Aokromes** [comment] 2019-11-06 15:45
Autocorrect implemented on 1.9.0 beta.

**Comment by john-preston** [comment] 2019-11-06 15:49
@Aokromes No autocorrection.

**Comment by ilya-fedin** [comment] 2020-10-24 13:40
Duplicate of #6819 and #6064

**Closed** 2020-10-24 13:42 UTC
Labels: enhancement, macOS
