### ISSUE TITLE
Need a setting to disable exit on Ctrl-W

### ISSUE THREAD

**Issue by Low-power** [telegramdesktop/tdesktop#4258] opened 2017-12-30 08:43 UTC
### Steps to reproduce
1. Start Telegram desktop client
2. Open a chat
3. Press Ctrl-W

### Expected behaviour
A setting to control this behavior should be available in the Settings dialog. I prefer to completely ignore this key binding, but the setting should also provide a behavior to this key binding that close the current chat session, instead of exit the program.

### Actual behaviour
The whole Telegram program exited.

### Configuration
**Operating system:**
Debian GNU/Linux 8

**Version of Telegram Desktop:**
1.1.10

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>

[15:32:30.844 00-0000713] Waiting for taskThread to finish (localimageloader.cpp : 128)
[15:32:32.947 00-0000714] Shortcut event catched: Ctrl+W (mainwindow.cpp : 592)
[15:32:32.949 00-0000715] Session Info: stopping session dcWithShift 5 (session.cpp : 158)
[15:32:32.950 00-0000716] Session Info: marked session dcWithShift 5 as killed (session.cpp : 168)
[15:32:32.950 00-0000717] Waiting for connectionThread to finish (connection.cpp : 281)
[15:32:33.002 00-0000718] Telegram finished, result: 0 (main.cpp : 48)

</details>

**Comment by john-preston** [comment] 2017-12-30 08:45
@Low-power It should just close to tray if the tray icon is available and enabled.

**Comment by Low-power** [comment] 2017-12-30 08:49
Sorry I want to say Ctrl-Q

**Comment by Low-power** [comment] 2017-12-30 08:53
I known the program will not exit if I enabled the tray icon, however I expect the program to exit when I pressing Alt-F4 (that is closing the window).

**Comment by stek29** [comment] 2017-12-31 10:14
> that close the current chat session, instead of exit the program.

Didn't understand this. You mean what <kbd>Esc</kbd> does?

**Comment by Low-power** [comment] 2018-01-01 14:34
> You mean what Esc does?
Yes

**Comment by Low-power** [comment] 2018-01-01 14:35
> You mean what Esc does?

Yes

**Comment by stek29** [comment] 2018-01-02 05:21
@Low-power then just use it

**Comment by Low-power** [comment] 2018-01-02 06:42
@stek29 You probably misunderstood this issue. I mean I want to disable `CRTL-W` key binding; I'm not looking for a way to close a chat that `Esc` does.

**Comment by stek29** [comment] 2018-01-02 09:15
Disable for what? Can't you just not press it?

**Comment by Low-power** [comment] 2018-01-02 09:34
I often press this key binding mistakenly when trying to press `CTRL-V`, because `W` is near to `V` in my keyboard.

**Comment by thetoastcaper** [comment] 2018-01-08 18:09
Perhaps only make Ctrl+W close the window when it's on the toplevel chat list?

**Comment by thetoastcaper** [comment] 2018-03-17 07:26
Ctrl+W is a quite common shortcut for closing the current tab/window on many programs.

**Comment by Ceda-EI** [comment] 2018-03-17 13:02
It is a common shortcut for closing tabs in browsers and by analogy, it should close the chat in TG Desktop. There is not a single application that I know of which uses Ctrl + W to exit.

**Comment by john-preston** [comment] 2018-03-17 14:12
@Ceda-EI If you press it in a Chrome window with last tab the window is closed. The window is closed in tdesktop as well.

**Comment by Ceda-EI** [comment] 2018-03-17 19:43
**With last tab**
You cannot specify a special case and call it common. Also, carrying the analogy, it should do that if I only have **1 chat** (analogous to last tab)

**Comment by john-preston** [comment] 2018-03-17 20:14
@Ceda-EI In tdesktop you always have only one "tab" opened, which is closed by Ctrl+W. If I find time to implement chrome-like tabs in tdesktop, Ctrl+W will close a single tab.

**Comment by Ceda-EI** [comment] 2018-03-17 20:19
@john-preston No, you don't have only one "tab" opened, you have only one "tab" focused just like you can focus only one tab in browser. Each "chat" is a "tab". Ctrl+W makes no sense in this context. It is best to disable it rather than make it a duplicate of Esc (or disable esc and use that solely to cancel replies and edits and use ctrl+W to leave chat)

**Comment by SmartManoj** [comment] 2019-07-25 07:16
Use AHK as workaround

**Comment by Aokromes** [comment] 2019-12-22 16:44
https://github.com/telegramdesktop/tdesktop/issues/3366#issuecomment-299989401 better ticket.

**Closed by Aokromes** 2019-12-22 16:44 UTC
Labels: enhancement

**Comment by up_the_irons** [comment] 2021-01-19 10:23
> Why does Telegram Desktop need to introduce a non-standard keyboard shortcut to exit it when the functionality already exists in practically every window manager / desktop environment? This should be disabled.

I agree.  I can't stand that CTRL-W closes the window.  I'm on Linux and this key-binding is used to delete a word.  Works in every other app I use: Chrome, Firefox, Skype, etc...
I also can't use CTRL-SHIFT-U to insert Unicode, useful for emojies too.  And this works fine in WhatsApp for Web.

**Comment by ilya-fedin** [comment] 2021-01-19 18:00
Ctrl+Shift+U is a gtk feature, it doesn't work in any apps that using other toolkits.
