### ISSUE TITLE
Pictures cropped on secondary screen

### ISSUE THREAD

**Issue by Artim96** [telegramdesktop/tdesktop#1559] opened 2016-01-27 12:57 UTC
I'm using my laptop as my main computer with an external screen, so I only enable the big screen in Win10 (Pro, x64), but when I open pictures in Telegram, the picture view gets cropped like that:
![image](https://cloud.githubusercontent.com/assets/16918678/12613869/bb7c533a-c4fc-11e5-9e1b-137446e63fc1.png)

but it should more look like that:
![image](https://cloud.githubusercontent.com/assets/16918678/12613891/dcb7b2f6-c4fc-11e5-91e1-ad055865ac6c.png)

It doesn't matter on pictures like that, but it's really annoying when important info get cropped out because of that. And it is like that since about 6 month (so since I have a new secondary screen). I don't think I had that bug on my old screen but I'm not fully sure. Differences between the two secondary screens: different resolution (then 1280x1024, 5:4; now 1920x1080, 16:9) and different connection method (then: VGA, now DisplayPort, both natively on my Laptop).
I hope that helps to fix that bug.

**Comment by Gollam** [comment] 2016-02-04 18:32
Hi,
This is a duplicate of https://github.com/telegramdesktop/tdesktop/issues/1542

**Closed** 2016-02-04 18:33 UTC
Labels: bug
