### ISSUE TITLE
[Feature Request] Create folders for channels/chats that can be collapsed

### ISSUE THREAD

**Issue by webworker01** [telegramdesktop/tdesktop#4344] opened 2018-01-25 08:54 UTC
The current system where the last chat that had a message bubbling to the top makes focusing on a few chats difficult. 

If we could create folders in our chats list, we could organize chats how we like and let some of the chats we don't need to have an update on minute by minute be further down in the list.

When folders are collapsed perhaps the entire group can be muted, reducing some of the network activity needed as well (or this could be a right click option for the folder?)

Alternatively, please allow for unlimited pinned chats. 💃

**Comment by RememberTheAir** [comment] 2018-01-25 11:51
Likely duplicate of #1107

**Closed** 2018-01-25 12:22 UTC
