### ISSUE TITLE
Show / preview all direct link images (in a single message)

### ISSUE THREAD

**Issue by dogancelik** [telegramdesktop/tdesktop#4039] opened 2017-11-02 22:57 UTC
### Steps to reproduce
1. Share multiple direct link images (`http://example.com/image1.jpg`) in a single message

### Expected behaviour
Show all images in that message in a 2x2 preview table

(If more than 4 images, 4th box should "+" that will open image viewer and you can scroll through images.)

### Actual behaviour
Only first image is previewed

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:**  1.1.23

**Used theme**: Default with different background image

### 2 images
![double](https://user-images.githubusercontent.com/486818/32354034-f8f79ede-c038-11e7-8e49-852ce57da3fb.jpg)

### 4 images
![four](https://user-images.githubusercontent.com/486818/32354286-2279fd78-c03a-11e7-833a-1b243390f715.jpg)

### 5 images

Replace last image with "+" icon, that's it and it will open image and you can scroll through them (with <kbd>Left</kbd> & <kbd>Right</kbd>).

**Comment by auchri** [comment] 2017-11-02 23:04
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/2712

**Closed by auchri** 2017-11-02 23:04 UTC

**Comment by dogancelik** [comment] 2017-11-02 23:16
This is not a duplicate, Twitter images are direct link images are different, there is no API issue here.

**Comment by stek29** [comment] 2017-11-02 23:51
@dogancelik No, tdesktop can't fetch anything from any third party url.
It's an API issue for two reasons:
1) API only returns preview for first link it is able to fetch
2) API limits preview to have just one photo

Second issue can also be considered duplicate of #2712.

**Comment by dogancelik** [comment] 2017-11-03 09:22
@stek29 I understand now thanks!

**Comment by dogancelik** [comment] 2017-11-03 09:57
@stek29 I understand now thanks! Any idea when API will be changed to fetching more than 1 image?

**Comment by auchri** [comment] 2017-11-03 09:58
No sorry.

**Comment by stek29** [comment] 2017-11-03 18:35
@dogancelik Never, I guess. For cases like this TG has Instant View, but it's not supported in TDesktop yet.
