### ISSUE TITLE
Feature request: grouped channels, contacts and groups by different categories?

### ISSUE THREAD

**Issue by Warmuser** [telegramdesktop/tdesktop#4341] opened 2018-01-24 13:50 UTC
I would like to suggest you an enhancement for Telegram Desktop by dividing the kind of contacts by categories. Like a dropdown list with all the subscriptions by the discussion category. For example:

Group one = All the Subscribed Groups (dropdown)

Group one,
Group two,
Group three,
etc..

Group two = All the Subscribed Channels (dropdown)

Channel one,
Channel two, 
Channel three,
etc..

Group three = All the people Contacts (dropdown)

Contact one,
Contact two,
Contact three, 
etc..

PS: I also want to suggest you to add a function to drag and sort manually or automatically. And another setting to force the history deletion where is not permitted. Because some groups doesn't let me to delete the history. 

Please, let me know If it would be possible in future. Thanks for these beautiful program!

**Comment by RememberTheAir** [comment] 2018-01-24 15:07
Duplicate of #1107

**Closed** 2018-01-24 23:11 UTC
