### ISSUE TITLE
Media viewer does not display on correct monitor in Gnome3

### ISSUE THREAD

**Issue by Pecon** [telegramdesktop/tdesktop#5176] opened 2018-09-20 16:29 UTC
### Steps to reproduce
1. Run Telegram
2. Place Telegram on non-primary display
3. Open a piece of media. Close.
4. Open a piece of media again.

### Expected behaviour
The media viewer used to correctly appear on the display that Telegram is currently on.

### Actual behaviour
The first time you open media it will appear correctly sized to the display and on the correct one. On the second and all subsequent attempts, the media viewer will show up on the primary display regardless of the display Telegram is on. The media viewer will also be sized correctly for the display Telegram is on, but will show up on the primary monitor.

This started being an issue about a month ago, it used to work fine.

![When viewing media the first time (normal)](https://user-images.githubusercontent.com/7043178/45832602-e3d00080-bcf1-11e8-9eeb-18d9c61f1c1d.png)
![All subsequent attempts](https://user-images.githubusercontent.com/7043178/45832603-e4689700-bcf1-11e8-9199-d11e4a16b95e.png)

### Configuration
**Operating system:** Debian 9 (Default DE)

**Version of Telegram Desktop:** 1.3.14

**Used theme**: Default dark theme

<details><summary><b>Logs</b>:</summary>
[2018.09.20` 09:17:59] Launched version: 1003014, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2018.09.20 09:17:59] Executable dir: /home/rexana/Downloads/Telegram/, name: Telegram
[2018.09.20 09:17:59] Initial working dir: /home/rexana/
[2018.09.20 09:17:59] Working dir: /home/rexana/.local/share/TelegramDesktop/
[2018.09.20 09:17:59] Command line: /home/rexana/Downloads/Telegram/Telegram --
[2018.09.20 09:17:59] Executable path before check: /home/rexana/Downloads/Telegram/Telegram
[2018.09.20 09:17:59] Logs started
[2018.09.20 09:17:59] Connecting local socket to /tmp/0bd8808a276e78f82777d1dc9221ec84-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2018.09.20 09:17:59] This is the only instance of Telegram, starting server and app...
[2018.09.20 09:17:59] Moved logging from '/home/rexana/.local/share/TelegramDesktop/log_start0.txt' to '/home/rexana/.local/share/TelegramDesktop/log.txt'!
[2018.09.20 09:17:59] Could not load 'appindicator3' with version 1 :(
[2018.09.20 09:17:59] Error: failed to load 'gdk_set_allowed_backends' function!
[2018.09.20 09:17:59] Getting DE, XDG_CURRENT_DESKTOP: 'GNOME'
[2018.09.20 09:17:59] Getting DE, DESKTOP_SESSION: 'default'
[2018.09.20 09:17:59] Getting DE, KDE_SESSION_VERSION: ''
[2018.09.20 09:17:59] DE: Gnome
[2018.09.20 09:17:59] Tray Icon: Try Qt = [TRUE], Prefer appindicator = [FALSE]
[2018.09.20 09:17:59] App Info: reading settings...
[2018.09.20 09:17:59] App Info: reading encrypted settings...
[2018.09.20 09:17:59] Lang Info: Loaded cached, keys: 1973
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_channel_admin_sure'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_context_remove_admin'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_animation#few'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_animation#many'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_animation#one'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_animation#other'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_animation#two'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_animation#zero'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_clear_some'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_empty'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_image#few'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_image#many'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_image#one'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_image#other'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_image#two'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_image#zero'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_months#few'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_months#many'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_months#one'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_months#other'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_months#two'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_months#zero'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_never'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_weeks#few'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_weeks#many'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_weeks#one'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_weeks#other'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_weeks#two'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_limit_weeks#zero'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_round#few'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_round#many'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_round#one'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_round#other'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_round#two'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_round#zero'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_size_limit'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_sticker#few'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_sticker#many'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_sticker#one'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_sticker#other'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_sticker#two'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_sticker#zero'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_summary'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_time_limit'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_voice#few'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_voice#many'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_voice#one'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_voice#other'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_voice#two'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_local_storage_voice#zero'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_passport_fix_errors'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_passport_front_side_name'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_passport_main_page_name'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_passport_reverse_side_name'
[2018.09.20 09:17:59] Lang Warning: Unknown key 'lng_passport_selfie_name'
[2018.09.20 09:17:59] OpenAL Logging Level: (not set)
[2018.09.20 09:17:59] Audio Playback Devices: OpenAL Soft
[2018.09.20 09:17:59] Audio Playback Default Device: OpenAL Soft
[2018.09.20 09:17:59] Audio Capture Devices: Built-in Audio Analog Stereo;Monitor of Built-in Audio Analog Stereo
[2018.09.20 09:17:59] Audio Capture Default Device: Built-in Audio Analog Stereo
[2018.09.20 09:17:59] App Info: reading map...
[2018.09.20 09:17:59] App Info: reading encrypted map...
[2018.09.20 09:17:59] App Info: reading encrypted user settings...
[2018.09.20 09:18:00] App Info: encrypted user settings read.
[2018.09.20 09:18:00] App Info: reading encrypted mtp data...
[2018.09.20 09:18:00] MTP Info: read keys, current: 5, to destroy: 0
[2018.09.20 09:18:00] Map read time: 162
[2018.09.20 09:18:00] TCP Error: network - Network unreachable
[2018.09.20 09:18:00] HTTP Error: network error 99 - Network unreachable
[2018.09.20 09:18:00] Notifications Server: gnome-shell
[2018.09.20 09:18:00] LibNotify capabilities: actions, body, body-markup, icon-static, persistence, sound
[2018.09.20 09:18:00] Export Info: Destroy top bar by controller removal.
[2018.09.20 09:18:00] Using Qt tray icon.
[2018.09.20 09:18:00] Tray Icon: Using Qt tray icon, available: [TRUE]
[2018.09.20 09:18:00] Not using Unity Launcher count.
[2018.09.20 09:18:00] Lang Info: Up to date.
[2018.09.20 09:18:01] TCP Error: network - Network unreachable
[2018.09.20 09:18:01] TCP Error: network - Network unreachable
[2018.09.20 09:18:01] HTTP Error: network error 99 - Network unreachable
[2018.09.20 09:18:01] HTTP Error: network error 99 - Network unreachable
[2018.09.20 09:18:52] TCP Error: network - Network unreachable
[2018.09.20 09:18:52] HTTP Error: network error 99 - Network unreachable
[2018.09.20 09:19:32] Audio Info: recreating audio device and reattaching the tracks
[2018.09.20 09:19:35] Audio Info: Closing audio playback device.
</details>

**Comment by stek29** [comment] 2018-09-21 07:44
See #5048

Duplicate of #5126

**Closed by stek29** 2018-09-21 07:44 UTC
