### ISSUE TITLE
Blocked user messages appear in chat groups

### ISSUE THREAD

**Issue by dalu** [telegramdesktop/tdesktop#6107] opened 2019-06-07 10:11 UTC
### Steps to reproduce
1. Join a chat group 
2. Block a user
3. You still see his messages

### Expected behaviour
Messages from the blocked user aren't visible

### Actual behaviour
Messages from the blocked user are visible

Opening this because https://github.com/telegramdesktop/tdesktop/issues/1281 is closed for comments.

This bug is over 4 years old! I'm close to uninstalling telegram and deleting everything.
Fix this!

**Comment by RememberTheAir** [comment] 2019-06-07 11:06
#1281 is a duplicate of #1025

**Comment by dalu** [comment] 2019-06-19 05:57
And you are?

**Comment by gravax** [comment] 2019-06-19 07:12
Maybe, @dalu  what you are looking for if you want something that is implemented on the server, is what admins can do... Restrict a user (cannot send messages, cannot send media, and other features...) or even remove from a group. If you perceive the user as toxic, report them to the admin who will take appropriate action. If the admin doesn't, themselve, perceive the user as toxic... maybe it's something else you need to consider.

Blocking would be more of a client side feature that would be easier to manage. Each client dev can decide to implement or not some display feature.

**Comment by Aokromes** [comment] 2019-09-06 20:59
not a bug (even i will like to see this handled, it must be fixed by api, not telegram desktop)

**Closed by Aokromes** 2019-09-06 20:59 UTC
