### ISSUE TITLE
telegram 3.1 window size is not remembere

### ISSUE THREAD

**Issue by bagasik** [telegramdesktop/tdesktop#16997] opened 2021-09-23 08:06 UTC
### Steps to reproduce

Hello.
I am using telegram without system window frame.
If you restart the system, the position and size of the window are not saved.
The position of the window and its size are saved only if the parameter telegram system window frame is used.

`In telegram settings -> advanced settings -> System integration: Window system frame.`

```
Version of the installed program.
net-im/telegram-desktop-bin-3.1.0
```

```
My system.
Linux 5.10.61-gentoo x86_64
xfce4 4.16.0
```

### Expected behaviour

f

### Actual behaviour

f

### Operating system

Gentoo Linux x86_64

### Version of Telegram Desktop

telegram-desktop-bin-3.1

### Installation source

Other (unofficial) source

### Logs

```shell
f
```

**Comment by Aokromes** [comment] 2021-09-23 08:50
plz try downloading official version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment] 2021-09-23 09:06
> If you restart the system, the position and size of the window are not saved.

Just restarting the app doesn't seem to reproduce the bug (or I and a lot of other people already saw that), so provide detailed steps to reproduce

**Comment by ilya-fedin** [comment] 2021-09-23 09:10
> Gentoo Linux x86_64

I think the string from Privacy & Security -> Show all sessions would be more informative than this

**Comment by bagasik** [comment] 2021-09-23 09:16
> Just restarting the app doesn't seem to reproduce the bug (or I and a lot of other people already saw that bug), so provide detailed steps to reproduce

Made a reproduction of the error in pictures.

Window size and locations are not saved after a system restart.
[https://ibb.co/tz1x5T3](url)

After a system reboot, the window size and locations are retained.
[https://ibb.co/cKqdz3X](url)

**Comment by ilya-fedin** [comment] 2021-09-23 09:20
I don't quite understand what do you want to say by these pictures. When you switch between the modes, window size will differ, I don't think that's a problem, you can resize the window however you want after that.

**Comment by bagasik** [comment] 2021-09-23 09:23
> I don't quite understand what do you want to say by these pictures. When you switch between the modes, window size will differ, I don't think that's a problem, you can resize the window however you want after that.

I agree to resize and relocate the window once, but not after every system reboot.

**Comment by ilya-fedin** [comment] 2021-09-23 09:23
Will you provide steps to reproduce or not?

**Comment by bagasik** [comment] 2021-09-23 09:24
> > Gentoo Linux x86_64
> 
> I think the string from Privacy & Security -> Show all sessions would be more informative than this

Why do you need to see on which devices I have telegram running. There are two devices in the list.

**Comment by ilya-fedin** [comment] 2021-09-23 09:24
> Why do you need to see on which devices I have telegram running

I need info about your systems since info you provided is not enough.

**Comment by bagasik** [comment] 2021-09-23 09:25
And how can I do it, shoot a video?

**Comment by ilya-fedin** [comment] 2021-09-23 09:26
> And how can I do it, shoot a video?

If you're talking about steps to reproduce, that would be ideal.

**Comment by bagasik** [comment] 2021-09-23 09:40
> > Why do you need to see on which devices I have telegram running
> 
> I need info about your system since info you provided is not enough.

https://ibb.co/qrktyyV

**Comment by bagasik** [comment] 2021-09-23 09:40
> If you're talking about steps to reproduce, that would be ideal.

no, I can't make a video.

**Comment by ilya-fedin** [comment] 2021-09-23 09:41
> https://ibb.co/qrktyyV

I was needed only the "Linux XFCE X11 glibc 2.33"

**Comment by ilya-fedin** [comment] 2021-09-23 09:42
> no, I can't make a video.

You still should provide steps to reproduce, then

**Comment by bagasik** [comment] 2021-09-23 09:50
> You still should provide steps to reproduce, then

What are the steps?
I remove in the telegram settings (Системная рамка окна -> Window system frame), change the location and size of the window.
I'm restarting the system.
The window locations and size are not saved.
https://ibb.co/tz1x5T3

If you activate the setting in telegram (Системная рамка окна -> Window system frame) and change the location of the telegram window, then after restarting the location and size of the window is saved.
https://ibb.co/cKqdz3X

I do not know how else to explain!

**Comment by bagasik** [comment] 2021-09-23 09:51
Закрывайте мою созданную тему, мне надоело, видео я не буду снимать!!!
У меня нет времени, объяснять разжевывать баги вашего софта.

**Comment by ilya-fedin** [comment] 2021-09-23 09:52
> What are the steps?

Well, you launch Telegram. You should describe steps-by-stepps, in detail, what to do in order to see the issue. I tried to just restart the app, but I can't reproduce, window size restores just fine.

**Comment by ilya-fedin** [comment] 2021-09-23 09:53
> Закрывайте мою созданную тему, мне надоело, видео я не буду снимать!!!

А что еще делать, если объяснить нормально не можешь

**Comment by bagasik** [comment] 2021-09-23 09:56
Да любое расположение и размер окна на рабочем столе, хоть с верху, хоть с низу рабочего стола, хоть по центру.
У меня нет времени на это все, может у больше го народа этот проявится и у кого-то хватит терпения и времени расписывать каждое действие.
Мне не критично!

**Comment by bagasik** [comment] 2021-09-23 09:56
Можно тему удалить!

**Comment by ilya-fedin** [comment] 2021-09-23 09:56
> Да любое расположение и размер окна на рабочем столе, хоть с верху, хоть с низу рабочего стола, хоть по центру.

Ну вот я делаю и у меня сохраняет...

**Comment by bagasik** [comment] 2021-09-23 09:57
> > Да любое расположение и размер окна на рабочем столе, хоть с верху, хоть с низу рабочего стола, хоть по центру.
> 
> Ну вот я делаю и у меня сохраняет...

Значит повезло, я не знаю что еще добавить!

**Comment by ilya-fedin** [comment] 2021-09-23 09:58
Ну, ладно, нет времени, значит нет времени, будем ждать кого-то еще
@Aokromes can you close the issue?

**Closed** 2021-09-23 10:08 UTC
Labels: bug
