### ISSUE TITLE
right click menu is broken after 5.5.1 update on Hyprland (Linux)

### ISSUE THREAD

**Issue by pmoieni** [telegramdesktop/tdesktop#28368] opened 2024-09-08 17:18 UTC
##

# Steps to reproduce

1. install telegram from the official website
2. open a chat
3. right click on a message

### Expected behaviour

the menu should display correctly

### Actual behaviour

the menu is zoomed out and some items are not shown, moving the mouse over the menu causes it to flicker ending up in a full app crash

example:

https://github.com/user-attachments/assets/501a586d-6af4-4cc3-bb27-f5b708ae0304

### Operating system

OpenSuse Tumbleweed - Hyprland

### Version of Telegram Desktop

5.5.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2024-09-08 21:08
Hm. It was ok on 5.4.x but is broken with 5.5.x? I think the only thing changed is Qt updated so I have no idea what could be done about that...

**Comment by ilya-fedin** [comment] 2024-09-08 22:40
And I can't reproduce on my KDE machine...

**Comment by pmoieni** [comment] 2024-09-09 08:55
@ilya-fedin  can't reproduce on KDE either but I get this error in the terminal on Hyprland:
> qt.qpa.wayland: Creating a popup with a parent, QWidgetWindow(0x7f34e42b0920, name="TWidgetClassWindow") which does not match the current topmost grabbing popup, QWidgetWindow(0x7f34aef4fc60, name="TWidgetClassWindow") With some shell surface protocols, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly. Please fix the transient parent of the popup.

**Comment by DWarez** [comment] 2024-09-12 08:08
+1, I'm also getting this error:

Happens both with telegram-desktop and materialgram.

> qt.qpa.wayland: Creating a popup with a parent, QWidgetWindow(0x7a1e70dfebc0, name="TWidgetClassWindow") which does not match the current topmost grabbing popup, QWidgetWindow(0x7a1e0ff2d780, name="TWidgetClassWindow") With some shell surface protocols, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly. Please fix the transient parent of the popup.

**Comment by ilya-fedin** [comment] 2024-09-12 08:38
Sadly no one provided valid reproduction steps that would work in a controlled environment so the bot is going to close the issue if this won't change.

**Comment by asgmojtaba** [comment] 2024-09-14 08:56
I have same issue on hyprland when enabling scaling (150% on my 4k display). here are the journalctl logs when working with contextual menus :

```
Sep 14 12:23:27 tiny Telegram[27409]: qt.qpa.wayland: Creating a popup with a parent, QWidgetWindow(0x7f39dd6fc100, name="TWidgetClassWindow") which does not match the current topmost grabbing popup, QWidgetWindow(0x7f39baae34e0, name="TWidgetClassWindow") With some shell surface protocols, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly. Please fix the transient parent of the popup.
```

I don't know it could be reproduced on KDE, but for my setup (which is hyprland) it reproduces every times when using telegram with scaling enabled on my 4k monitor.

thanks in advance

**Comment by DWarez** [comment] 2024-09-14 08:59
> I have same issue on hyprland when enabling scaling (150% on my 4k display). here are the journalctl logs when working with contextual menus :
> 
> ```
> Sep 14 12:23:27 tiny Telegram[27409]: qt.qpa.wayland: Creating a popup with a parent, QWidgetWindow(0x7f39dd6fc100, name="TWidgetClassWindow") which does not match the current topmost grabbing popup, QWidgetWindow(0x7f39baae34e0, name="TWidgetClassWindow") With some shell surface protocols, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly. Please fix the transient parent of the popup.
> ```
> 
> I don't know it could be reproduced on KDE, but for my setup (which is hyprland) it reproduces every times when using telegram with scaling enabled on my 4k monitor.
> 
> thanks in advance

For me, setting the scaling to 2 solves the issue.

**Comment by ilya-fedin** [comment] 2024-09-14 09:06
sadly logs won't help - a way to reproduce is needed

**Comment by wchichih** [comment] 2024-09-15 03:09
<img width="422" alt="图片" src="https://github.com/user-attachments/assets/152e5d36-352e-4bcc-8a23-9ffd5edbbb3c">

Same problem with telegram flatpak 5.5.x under KDE 5 Wayland. 2.2K display with 150% scale.

App doesn't crash, but right click menu zoomed out.

![图片](https://github.com/user-attachments/assets/4dc94295-345f-41d1-b49c-f3c1060ed468)

Enable precise High DPI scaling in experimental features can get right click menu fully showed, but get icons in app blurry.

![图片](https://github.com/user-attachments/assets/401c9b62-14b1-4658-9c89-e56f6b29a021)
![图片](https://github.com/user-attachments/assets/606552d1-2755-4db5-9e77-b0680221c2bb)

**Comment by wchichih** [comment] 2024-09-15 04:57
Update: add `QT_WAYLAND_DISABLED_INTERFACES=wp_fractional_scale_manager_v1` to env can get menu shows correctly.

![图片](https://github.com/user-attachments/assets/acb2f8d7-8347-4c69-8b7c-e5c888dce146)

**Comment by ilya-fedin** [comment] 2024-09-15 08:07
I still can't reproduce.

**Comment by DWarez** [comment] 2024-09-15 10:24
> <img alt="图片" width="422" src="https://private-user-images.githubusercontent.com/4954007/367556632-152e5d36-352e-4bcc-8a23-9ffd5edbbb3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTQ5ODAsIm5iZiI6MTcyNjM5NDY4MCwicGF0aCI6Ii80OTU0MDA3LzM2NzU1NjYzMi0xNTJlNWQzNi0zNTJlLTRiY2MtOGEyMy05ZmZkNWVkYmJiM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMTAwNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRlNzIxNDI2YTA4OWJjMWY1NGZhNDViZjk3MTQzNGY4NWE1NDQwYzk2YWM4ZTNmMDMyNmM3MTc2NzNmZDc0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lfKrXPmKSIfjBrQ24mLplLRvUck51hP410EbbfMLOnU">
> 
> Same problem with telegram flatpak 5.5.x under Debian sid KDE 5 Wayland. 2.2K display with 150% scale.
> 
> App doesn't crash, but right click menu zoomed out.
> 
> ![图片](https://private-user-images.githubusercontent.com/4954007/367556720-4dc94295-345f-41d1-b49c-f3c1060ed468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTQ5ODAsIm5iZiI6MTcyNjM5NDY4MCwicGF0aCI6Ii80OTU0MDA3LzM2NzU1NjcyMC00ZGM5NDI5NS0zNDVmLTQxZDEtYjQ5Yy1mM2MxMDYwZWQ0NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMTAwNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGJmOWExMWUzNjNhOTlhODAzMWE1OTAwMDkwY2FjMWIzMmRiYmIzZGRkM2Q5YjM4NTRkMWQyZGRmNDc0MGViYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mY5zH4Pg-FnQKpC9x61ctFjn6gaXO3l_eSEUx151Y9I)
> 
> Enable precise High DPI scaling in experimental features can get right click menu fully showed, but get icons in app blurry.
> 
> ![图片](https://private-user-images.githubusercontent.com/4954007/367556822-401c9b62-14b1-4658-9c89-e56f6b29a021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTQ5ODAsIm5iZiI6MTcyNjM5NDY4MCwicGF0aCI6Ii80OTU0MDA3LzM2NzU1NjgyMi00MDFjOWI2Mi0xNGIxLTQ2NTgtOWM4OS1lNTZmNmIyOWEwMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMTAwNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE1NDZmZGM5NDg0MWNlMWQzNmQxNjc5MGIxYmQ0N2ZlYjJkZWU1NTVmN2Y2NTY1MmZmNGIxNTE0NjQzOTJhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.q1hofluli38dkJuEOMD8x4sfE5_uGTsgO8eB7fNfjrs) ![图片](https://private-user-images.githubusercontent.com/4954007/367556840-606552d1-2755-4db5-9e77-b0680221c2bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTQ5ODAsIm5iZiI6MTcyNjM5NDY4MCwicGF0aCI6Ii80OTU0MDA3LzM2NzU1Njg0MC02MDY1NTJkMS0yNzU1LTRkYjUtOWU3Ny1iMDY4MDIyMWMyYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMTAwNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZhYjc2MDIxYzVmZjUwYjA1MDdmOGRkNzMwZWY0OTkwZmQyMDE5NDMxMjZmMWY0MmJlM2I1ZGVjZTM2ZTkzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eW9vyMGQtia4JF7QLWLCzjyxXXjTQM-ZV-8OS5_ySqU)

that fixed it, thanks a lot!

**Closed** 2024-09-15 11:16 UTC
Labels: bug, cant reproduce

**Comment by ilya-fedin** [comment] 2024-09-15 11:56
Searching by hyprland bugtracker I found [this](https://github.com/hyprwm/Hyprland/issues/2433) which looks exactly like the issue described here (popup menu gets wrong scale factor).

**Comment by wchichih** [comment] 2024-09-16 06:14
> I still can't reproduce.

@ilya-fedin I have reproduced it. Here is how-to:

1. prepare virt-manager and debian-12.7-kde-live ISO.
2. create new virtual machine and install system with Debian 12.7 KDE live ISO image.
3. boot vm.
4. set vm's display to 1920*1200, scale to 150%.
5. install flatpak.
6. flatpak install telegram.
7. run telegram.

And then see screenshot below:

![图片](https://github.com/user-attachments/assets/2f4b663c-c378-4197-a7ae-f4daa2d900a5)

**Comment by ilya-fedin** [comment] 2024-09-16 12:09
> 2\. Debian 12.7 KDE live ISO image.

It contains old KDE version that is known to be bugged with fractional scaling. It's a bug on KDE/Hyprland side, not tdesktop. In case of KDE you have to wait for version 6, in case of hyprland people have to wait until the linked bug gets fixed on hyprland side.
