### ISSUE TITLE
Mouse scroll crashes app

### ISSUE THREAD

**Issue by alx0k** [telegramdesktop/tdesktop#25986] opened 2023-03-02 11:28 UTC
### Steps to reproduce

Scroll the mouse

### Expected behaviour

Scrolling

### Actual behaviour

Crash

### Operating system

Ubuntu 22.10

### Version of Telegram Desktop

4.6.6 beta

### Installation source

Snap

### Logs

```shell
The Wayland connection experienced a fatal error: Resource temporarily unavailable
```

**Comment by Aokromes** [comment] 2023-03-02 12:16
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by alx0k** [comment] 2023-03-02 13:32
> plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

why?

**Comment by alx0k** [comment] 2023-03-02 13:36
> Are you using a mouse with high-resolution scroll?

Not exactly mouse, since its Logitech Pebble.
Although I think issue has something to do with wayland update in ubuntu 22.10, some of desktop applications like Firefox reacting like scroll is way to fast.
So, yes, I do think high scroll resolution is the issue here.

**Comment by ilya-fedin** [comment] 2023-03-02 13:38
can you run tdesktop like `WAYLAND_DEBUG=1 telegram-desktop > log.txt 2>&1`, reproduce the crash and upload the log here?

**Comment by alx0k** [comment] 2023-03-02 13:43
> `WAYLAND_DEBUG=1 telegram-desktop > log.txt 2>&1`
[log.txt](https://github.com/telegramdesktop/tdesktop/files/10871918/log.txt)

**Comment by ilya-fedin** [comment] 2023-03-02 14:31
I tried to show the log some KDE people experienced in Wayland, sadly they don't seem to find the cause in the log and tdesktop project has no state Wayland expert, so I'm not sure how we can proceed with that... This is likely a bug in Qt as 4.6.6 has a Qt update, if you can build Qt 6.5.0-beta3 from sources and reproduce the problem with any of the examples with scrolling then you can report this to Qt, if not then it's a dead end sadly...

**Comment by yanovich** [comment] 2023-03-03 12:16
snap package v4.6.5 works. v4.6.7-beta-6-gccbab25fa is unusable.

**Comment by ilya-fedin** [comment] 2023-03-03 12:51
In order for this issue to stay open, please do actions required by @Aokromes in https://github.com/telegramdesktop/tdesktop/issues/25986#issuecomment-1451775936. This is a requirement.

**Comment by yanovich** [comment] 2023-03-03 15:50
![image](https://user-images.githubusercontent.com/576586/222764771-3e173c77-6ffc-4c76-899d-28f95af93cfa.png)

Ubuntu uses your snap packages.
```
$ snap info telegram-desktop 
name:      telegram-desktop
summary:   Fast. Secure. Powerful.
publisher: Telegram FZ-LLC (telegram-desktop✓)
store-url: https://snapcraft.io/telegram-desktop
contact:   https://github.com/telegramdesktop/tdesktop/issues
license:   unset
description: |
  Pure instant messaging — simple, fast, secure, and synced across all your devices. One of the
  world's top 10 most downloaded apps with over 500 million active users.
  
  FAST: Telegram is the fastest messaging app on the market, connecting people via a unique,
  distributed network of data centers around the globe.
  
  SYNCED: You can access your messages from all your phones, tablets and computers at once. Telegram
  apps are standalone, so you don’t need to keep your phone connected. Start typing on one device
  and finish the message from another. Never lose your data again.
  
  UNLIMITED: You can send media and files, without any limits on their type and size. Your entire
  chat history will require no disk space on your device, and will be securely stored in the
  Telegram cloud for as long as you need it.
  
  SECURE: We made it our mission to provide the best security combined with ease of use. Everything
  on Telegram, including chats, groups, media, etc. is encrypted using a combination of 256-bit
  symmetric AES encryption, 2048-bit RSA encryption, and Diffie–Hellman secure key exchange.
  
  100% FREE & OPEN: Telegram has a fully documented and free API for developers, open source apps
  and verifiable builds to prove the app you download is built from the exact same source code that
  is published.
  
  POWERFUL: You can create group chats with up to 200,000 members, share large videos, documents of
  any type (.DOCX, .MP3, .ZIP, etc.) up to 2 GB each, and even set up bots for specific tasks.
  Telegram is the perfect tool for hosting online communities and coordinating teamwork.
  
  RELIABLE: Built to deliver your messages using as little data as possible, Telegram is the most
  reliable messaging system ever made. It works even on the weakest mobile connections.
  
  FUN: Telegram has powerful photo and video editing tools, animated stickers and emoji, fully
  customizable themes to change the appearance of your app, and an open sticker/GIF platform to
  cater to all your expressive needs.
  
  SIMPLE: While providing an unprecedented array of features, we take great care to keep the
  interface clean. Telegram is so simple you already know how to use it.
  
  PRIVATE: We take your privacy seriously and will never give any third parties access to your data.
  You can delete any message you ever sent or received for both sides, at any time and without a
  trace. Telegram will never use your data to show you ads.
  
  We keep expanding the boundaries of what you can do with a messaging app. Don’t wait years for
  older messengers to catch up with Telegram — join the revolution today.
commands:
  - telegram-desktop
snap-id:      jpdoHqMd90M39DdH2JSZbeQxipqHtwLo
tracking:     latest/stable
refresh-date: today at 15:20 MSK
channels:
  latest/stable:    4.6.5                   2023-02-25 (4654) 379MB -
  latest/candidate: ↑                                               
  latest/beta:      ↑                                               
  latest/edge:      4.6.7-beta-6-gccbab25fa 2023-03-02 (4678) 381MB -
installed:          4.6.5                              (4654) 379MB -
```

**Comment by ilya-fedin** [comment] 2023-03-03 15:52
@yanovich bug report must be confirmed using reference build in order to be accepted

**Comment by yanovich** [comment] 2023-03-03 16:12
Scrolling works in 4.6.7-beta-6-gccbab25fa if I drag scrollbar thumb. So it's not absolute unusable, but it's still very bad experience.

**Comment by yanovich** [comment] 2023-03-03 16:13
> @yanovich bug report must be confirmed using the reference build in order to be accepted.

Snap packages are shipped by Telegram FZ-LLC. Telegram FZ-LLC set https://github.com/telegramdesktop/tdesktop/issues as its contact URL.

**Comment by ilya-fedin** [comment] 2023-03-03 16:14
@yanovich that's right, still this is required as a part of the pre-check process.

**Comment by yanovich** [comment] 2023-03-03 16:14
It's a good practice to test software before it's shipped. You may try it for better user experience.

**Comment by ilya-fedin** [comment] 2023-03-03 16:15
@yanovich you're using the edge channel that builds from dev branch of the git repo, not the stable channel that provides the shipped version.

**Comment by yanovich** [comment] 2023-03-03 16:21
> @yanovich you're using the edge channel that builds from dev branch of the git repo, not the stable channel that provides the shipped version.

Nope. I use the stable channel ATM, because the edge is broken. This is seen in a `snap info` snippet I posted above. I spent some time informing you that your edge channel is broken. Feel free to close this bug. You seem to want it in the news.

**Comment by ilya-fedin** [comment] 2023-03-03 16:22
Oh, I use the info from the issue template

**Comment by ilya-fedin** [comment] 2023-03-03 16:25
> Nope. I use the stable channel ATM, because the edge is broken.

Well, you're saying that the shipped version is broken what is a lie as only the automatically-built-from-dev-branch version is broken.

**Comment by ilya-fedin** [comment] 2023-03-03 16:28
> Feel free to close this bug.

It couldn't be fixed if you don't want to help in investigating.

**Comment by yanovich** [comment] 2023-03-03 16:30
If I have your software it's been shipped. I have no intention to continue this discussion after you called me a liar.

**Comment by ilya-fedin** [comment] 2023-03-03 16:33
@yanovich it's a common thing to provide nightly builds, snap does that automatically without the possibility for the developer to disable it, yet it's expected that the user is aware that such versions are supposed to be buggy and shouldn't install them if he wants stable experience.

**Comment by yanovich** [comment] 2023-03-07 11:55
This bug is snap only. I've just built 6f16014232174dfe38130691749447c1474f89d8 from source. No crashes.

**Comment by ilya-fedin** [comment] 2023-03-07 13:35
> I've just built [6f16014](https://github.com/telegramdesktop/tdesktop/commit/6f16014232174dfe38130691749447c1474f89d8) from source.

Have you built it using Docker?

**Comment by ilya-fedin** [comment] 2023-03-07 15:24
Oh, that's bad... It means Qt's high-resolution scrolling code is not the culprit and I can't build testing binaries for tests (as static binary builds are not affected).

**Comment by ilya-fedin** [comment] 2023-03-20 14:15
Can someone affected say whether this bug is reproducible with the following executable?
https://drive.google.com/file/d/1rBSRsIY4UBdo6f_4rCoibTBRkKZPnGSQ/view?usp=sharing

**Comment by harshil21** [comment] 2023-03-27 14:21
> Can someone affected say whether this bug is reproducible with the following executable? https://drive.google.com/file/d/1rBSRsIY4UBdo6f_4rCoibTBRkKZPnGSQ/view?usp=sharing

I can confirm this is working correctly for me, so no I can't reproduce from this build :)

**Comment by ilya-fedin** [comment] 2023-03-27 14:26
meh... so it's not the patch that was fixing the build on CentOS 7 making the difference... apparently there's something in snap runtime itself which makes the problem way harder to solve :cry:

**Comment by ilya-fedin** [comment] 2023-03-27 14:28
and it seems the snap no more builds on snapcraft.io, CI and locally. CI just hangs in the middle of the process, local build fails due to some weird apparmor errors, so I have no idea how proceed with fixing the build on snapcraft.io.

**Comment by ilya-fedin** [comment] 2023-04-06 17:09
Is this still a problem?

**Closed** 2023-04-21 00:17 UTC
Labels: bug, waiting for answer, wayland

**Comment by Palatis** [comment] 2023-04-22 15:35
I'm having the issue with telegram-desktop 4.8.0 from snap on ubuntu 23.04 under gnome (wayland).
worked fine with 4.6.5.
```
$ snap list | grep telegram
telegram-desktop             4.8.0             4743   latest/stable    telegram-desktop**  -
```

how do I collect the logs?

**Comment by alinpr18** [comment] 2023-04-22 15:38
> Is this still a problem?

Yes

![Screenshot from 2023-04-22 11-38-29](https://user-images.githubusercontent.com/79379711/233793653-5ca42358-9658-43cd-8a69-c790bacd1386.png)

**Comment by Palatis** [comment] 2023-04-22 16:23
> > Is this still a problem?
> 
> Yes
> 
> ![Screenshot from 2023-04-22 11-38-29](https://user-images.githubusercontent.com/79379711/233793653-5ca42358-9658-43cd-8a69-c790bacd1386.png)

snap version does crash for me, too.
pre-built version works fine (https://desktop.telegram.org/)

**Comment by sadalsuud** [comment] 2023-04-22 16:25
hi, same problem in ubuntu 23-04 and telegram snap 4.8.0 :(

**Comment by diakudza** [comment] 2023-04-23 16:07
Hello. I have problem with scroll too...
![image](https://user-images.githubusercontent.com/77148342/233851004-5ed6e5f9-0c28-4661-8f27-9ee8d2389c95.png)

**Comment by linermgn** [comment] 2023-04-24 08:54
> > > Is this still a problem?
> > 
> > 
> > Yes
> 
> snap version does crash for me, too. pre-built version works fine (https://desktop.telegram.org/)

the same, scroll crashes

**Comment by alirezanqp** [comment] 2023-04-24 18:26
I have this problem too,
It crashes when scrolling

**Comment by odofad** [comment] 2023-04-24 18:49
I can confirm this. I have this issue on Telegram-desktop snap 4.8.0 and Ubuntu 23.04. It crashes when scrolling.

**Comment by mwanago** [comment] 2023-04-24 22:12
I have the same problem. In the terminal, I can see
```
The Wayland connection experienced a fatal error: Bad address
```
It works fine when using the touchpad, though.

**Comment by ilya-fedin** [comment] 2023-04-24 22:33
I tend to think it's https://gitlab.freedesktop.org/wayland/wayland/-/issues/159. Why it happens only in snap is still a big mystery though, maybe snap slows down the application to the point it can't process event fast enough? I'm not sure how we would be able to fix this then. The only thing coming to my mind is abandoning the snap package as it means it's just unfixable.

**Comment by ilya-fedin** [comment] 2023-04-24 22:57
Does setting `QT_WAYLAND_RECONNECT=1` environment variable help?

**Comment by EyalRo** [comment] 2023-04-25 02:42
I can confirm the bug persists when running via `QT_WAYLAND_RECONNECT=1 telegram-desktop`

**Comment by linermgn** [comment] 2023-04-26 06:31
The lastest update fixes the bug, now works

**Comment by mwanago** [comment] 2023-04-28 20:20
It works fine now for me too :+1: 
Great job, thanks.
