### ISSUE TITLE
cannot turn off preview

### ISSUE THREAD

**Issue by halcion** [telegramdesktop/tdesktop#725] opened 2015-05-16 18:34 UTC
unchecked "show message preview" and telegram does not respect the setting. still seeing a message previews on all links.please remove this feature until there is a way for users to turn it off,

**Comment by Brawl345** [comment] 2015-05-18 19:36
The option is for message preview in notifications.
Bug is a duplicate of #687

**Comment by halcion** [comment] 2015-05-22 01:35
i see now, ok. thank you for the info.

**Closed** 2015-08-14 21:37 UTC
