### ISSUE TITLE
Feature Request: Add an option to hide messages from/to blocked users

### ISSUE THREAD

**Issue by elboletaire** [telegramdesktop/tdesktop#4928] opened 2018-07-01 10:31 UTC
### Steps to reproduce

1. Add a user to a group
2. Block it
3. You still see their messages.

### Expected behaviour

To hide their messages.

### Actual behaviour

Everything works the same under groups, you can still see the blocked user messages, and he'll be able to see yours.

### Configuration
**Operating system:** All of them.
**Version of Telegram Desktop:** All of them.
**Used theme**: All of them.

### Request

To add a new option, apart from the `block user` one, to hide their messages (and hide yours to them).

I know this has been discussed, but the [discussion was about](https://github.com/telegramdesktop/tdesktop/issues/1281) changing the current behavior of the blocked users. Note that I'm not asking for that, instead I think that an additional option could be given (and that option could be shown when blocking a user, just a simple confirmation after blocking them saying if you also want to hide messages en groups for both).

And about how to show it, I think that showing `Hidden user` in the name and  `Hidden text` in the messages, could be enough. Doing it this way wouldn't be so weird to have blocked users in groups.

**Comment by elboletaire** [comment] 2018-07-01 10:33
So sorry if this is not the project to ask this. I know this would be better in the API project, but there's no public repo for it AFAIK.

**Comment by zeroone2numeral2** [comment] 2018-07-01 11:05
Duplicate of #1281 (and many other, but this one has the longest and most detailed discussion)

**Comment by elboletaire** [comment] 2018-07-01 11:22
Indeed, that's the discussion I've already linked in my issue.

**Closed** 2018-07-01 11:35 UTC

**Comment by elboletaire** [comment] 2018-07-01 12:08
Nice, good debate. I already said I wasn't searching to change the current behavior (which is what was discussed in #1281). I was asking for an alternate option, maintaining the old behavior intact.
