### ISSUE TITLE
I had a crash while Creating a Topic in the group!

### ISSUE THREAD

**Issue by itmehr** [telegramdesktop/tdesktop#27071] opened 2023-11-09 01:56 UTC
### Steps to reproduce

-

### Expected behaviour

when click on create , the software chrashes and closed.

### Actual behaviour

it has been said 

### Operating system

windows 11 pro x64

### Version of Telegram Desktop

4.11.5 

### Installation source

Static binary from official website

**Comment by joecool1029** [comment] 2023-11-09 18:01
Duplicate of  #27061

**Closed** 2023-11-09 18:21 UTC
Labels: bug
