### ISSUE TITLE
[Feature Request] [Linux] Implement systray icon via Status Notifier 

### ISSUE THREAD

**Issue by andrey-krutov** [telegramdesktop/tdesktop#679] opened 2015-04-28 08:58 UTC
KUbuntu 15.04 ships with new KDE5. The KDE5 developers drops old systray implementation via xembed. Now they use Status Notifire API (http://api.kde.org/frameworks-api/frameworks5-apidocs/knotifications/html/classKStatusNotifierItem.html). So  there is no tray icon anymore in KDE5.

Related links
http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/
http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/

**Comment by focuz** [comment] 2015-04-30 17:47
Confirmed... This Plasma5/KDE5 issue needs to be addressed a.s.a.p. since Kubuntu 15.05, Netrunner 15, along with some other distros, now ship with Plasma 5.

**Comment by AndydeCleyre** [comment] 2015-05-04 18:35
Related to #516.

**Comment by xpumax** [comment] 2015-07-30 15:00
any progress on this?

**Comment by AndydeCleyre** [comment] 2015-08-03 15:31
Fixed with 0.8.45!

**Comment by datamaan** [comment] 2015-08-03 16:24
Awesome! Thanks a lot.

2015-08-03 17:31 GMT+02:00 Andy Kluger <notifications@github.com>:

**Comment by focuz** [comment] 2015-08-04 21:02
The change log ought to be a bit more specific than "Bug fixes and other minor improvements", but thanks for properly implementing this much needed functionality!

**Closed** 2015-08-15 08:38 UTC
