### ISSUE TITLE
Group underhandedly updated to supergroup when changing admin titles, no options to undo

### ISSUE THREAD

**Issue by Niko-O** [telegramdesktop/tdesktop#7961] opened 2020-05-28 18:50 UTC
Edit
Original title was "Group underhandedly updated to supergroup when changing admin titles, no options to undo". See second message in this issue for details.
/Edit

Yesterday I created an invite link to a group I am an admin (not creator) of.
Today I noticed that I cannot respond to old messages. I get an error message saying "Sorry, you can't reply to a message that was sent before the group was updated to a supergroup. [...]". This is bad because it is very annoying to not be able to quickly link back to a conversation in the past. But the real problem is that I never got a warning that I'd update to a supergroup.

By trying to respond to various messages I narrowed the border between respondable and non-respondable messages down to the exact time I created the invite link for this group.

Today I tried to reproduce this by creating a completely new group (see "Steps to reproduce" below), but there I can respond to messages just fine after creating an invite link. So there must be something specific to that group.

This is all very confusing for me. Particularly the fact that I have seen a big warning pop up sometime in the past, that says you can't undo the update to a supergroup. I never saw such a warning when I created the invite link.
Instead of randomly poking at things and seeing what breaks I'd like to have a detailed explanation of how groups work in Telegram.
I don't know how to approach this issue because I cannot reproduce it and I can't even voluntarily change a group to a supergroup. Again, it's very confusing.

### Steps to reproduce
1. Be in a group where you are an admin.
2. Type a message.
3. Click on the three dots in the top right corner.
4. Click on "Manage group".
5. Click on "Group type".
6. Click on "Create an invite link".
7. Confirm the warning "Telegram users will be able to join your group by following this link." with "OK".
8. Click "Save".
9. Try to respond to the message you typed earlier.

### Expected behaviour
I should be able to respond to the message.

### Actual behaviour
When I tried to reproduce it today, I could respond to the message just fine, so it seems this is not easily reproducable.
Actual behaviour in the problematic group: I get a message telling me that I "can't reply to a message that was sent before the group was updated to a supergroup".

### Configuration
**Operating system:** Windows 10 Pro  64bit
**Version of Telegram Desktop:** 2.6.1
**Used theme**: Uuuh. A custom one? It's the "Classic" theme except for the background image and scrollbar colors.

### Logs
The log.txt only contains entries from today, not from yesterday when the problem occurred.

**Comment by ilya-fedin** [comment] 2020-05-29 10:09
> Today I tried to reproduce this by creating a completely new group (see "Steps to reproduce" below), but there I can respond to messages just fine after creating an invite link. So there must be something specific to that group.

New groups are supergroups

**Comment by RememberTheAir** [comment] 2020-05-29 10:50
@ilya-fedin you sure about that? Aren't there some actions that simply trigger the conversion?

**Comment by Niko-O** [comment] 2020-05-29 12:01
> New groups are creating as supergroups
Please provide a source for this.
The "actual steps to reproduce" I posted in the second comment clearly contradict your statement.

**Comment by Aokromes** [comment] 2020-05-29 12:28
on android, if you do "create new group" it tells you "up to 200 000 members" and that's a super group.

**Comment by Niko-O** [comment] 2020-05-29 12:34
@Aokromes 
When I create a new group on Android, I see the "up to 200 000 members" thing.
Then when I follow the "actual steps to reproduce", I still get the "can't reply to a message that was sent before the group was updated to a supergroup" error when I try to respond to the message I sent.
So no, a group created on Android is not automatically a supergroup.

**Comment by Aokromes** [comment] 2020-05-29 12:57
https://i.imgur.com/U7jmqFg.png i made this group on telegram desktop.

**Comment by frozenbrain** [comment] 2020-05-29 15:07
I can confirm the observations by @Niko-O. Some sort of conversion is performed in the background when assigning custom titles. The group even briefly disappears from the chat list. Also, the "Recent actions" menu item is added to the "Edit group" dialog, which shows that I "transferred ownership to [me]". The three-dot-menu in the "Group Info" also changes: "Delete and leave" is replaced by "Leave group".

Another side effect of this is that you can no longer export the full chat history of the affected group. Trying to do so results in a truncated chat history starting with the following message at the very top:
_"[me] converted a basic group to this supergroup «[group name]»"_
This leads me to believe that @Aokromes is in incorrect in assuming that all groups are created as supergroups by default.

This seems like an oversight and should be fixed by at least warning the user before converting the group.

**Comment by RememberTheAir** [comment] 2020-05-30 11:34
By default, every group is created as normal group (aka non-supergroup). There are a set of actions that trigger the group conversion to supergroup silently.

There's a bit more detailed conversation about this in ♯5593, and the up-to-date list of actions that trigger the conversion can be found [here](https://t.me/tgbetachat/59941)

**Comment by Niko-O** [comment] 2020-06-01 17:44
Well, that makes me wonder: Why do these actions not show up

**Comment by RememberTheAir** [comment] 2020-06-03 11:36
The implications are:

- admins badges being visible
- when an user is removed by an administrator from the group, the chat history disappears (with normal groups, it stays there in your chats list)
- the ability to delete a chat message just for you (and not for everyone) is lost (with also the ability to delete someone else's message just for you)

These are the main differences between a group and a supergroup. Telegram flattered these two types of groups because the distinction was very confusing for the average user - now, apart from the things I listed above, there's no tangible difference between a normal group and a supergroup. The end users always sees the same options, some of which will trigger the conversion silently. You don't get any warning because users are not supposed to know that underneath, the API and clients work with two different group types. Displaying a warning about something they didn't even know was a thing would simply confuse users.

Telelgram probably thought that the tradeoff between removing the distinction between groups and supergroups (with all the linked unnecessary complexity for the average user) and having some inconsistencies between the UX before and after a group conversion, was overall worth it. Instead of bringing to the surface the distinction between groups and supergroups again, I think they should just work on flattering the remaining differencies between the two groups, or simply start to create supergroups directly when an user creates a group. We can argue about how annoying are the discrepancies listed above (and they do are annoying - in my experience, it happened a couple of times that some friends asked me why they weren't able to delete a message in a group just for them. The answer was that the group was converted silently, and they didn't know), but none of them is as annoying as having to explain that there's a different set of features available only if you tap on the magic and super-obvious "convert to supergroup" button

**Comment by Aokromes** [comment] 2020-06-07 16:13
well, group supergroup thing is platform wide, imho contact in-application support.

**Closed** 2020-08-29 18:47 UTC
Labels: api issue
