### ISSUE TITLE
Very high CPU usage with GIFs sidebar visible

### ISSUE THREAD

**Issue by erodewald** [telegramdesktop/tdesktop#4209] opened 2017-12-20 02:00 UTC
### Steps to reproduce
1. Open the sidebar to the GIFs tab
2. Ensure there are at least a few GIFs visible
3. Observe CPU usage > 60-80%

### Expected behaviour
CPU should not rise much at all

### Actual behaviour
CPU is nearly pegged

### Configuration
**Operating system:** macOS 10.13.2

**Version of Telegram Desktop:** 1.2.1

**Used theme**: night mode

[Video (.zip)](https://github.com/telegramdesktop/tdesktop/files/1573915/telegram_desktop_cpuissue_2017-12-19.at.7.42.02.PM.mov.zip)

<details><summary><b>Logs</b>:</summary>
Tried to log but nothing appeared.

</details>

**Comment by AntonMalyshev** [comment] 2017-12-20 15:15
Experiencing the same issues even when "somebody is typing" animation is shown, the same macOS 10.13.2 and Telegram Desktop 1.2.1

**Comment by Meynex** [comment] 2017-12-22 16:01
the same is with windows 10, too. if i have the gif sidebar visible and window is not minimized it takes >=30%. so it should be fixed by if window is not active.

**Comment by fotonmoton** [comment] 2017-12-23 15:08
On Linux machine get identical behavior, if I open chat with gif sidebar CPU usage jumps up to 100-120% in htop. 
`4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
![image](https://user-images.githubusercontent.com/7763084/34320394-210e4184-e802-11e7-9c59-ef69ffb0b544.png)

**Comment by Aokromes** [comment] 2018-01-03 05:59
https://github.com/telegramdesktop/tdesktop/issues/2464 related?

**Comment by AntonMalyshev** [comment] 2018-01-03 09:18
No, I think high memory usage is completely separate issue

**Comment by samtygier** [comment] 2018-08-12 09:45
Same on Linux. CPU stays high even when gif panel is closed.

**Comment by BobbieGoede** [comment] 2018-12-18 14:10
Same on Windows 10, CPU usage at 100% even when sticker/gif panel is hidden but the gif section within the panel has been selected. When selecting the emoji or stickers section CPU usages returns to a reasonable amount.

**Comment by BaZzz01010101** [comment] 2019-04-02 09:07
Have this issue in latest version. It happens only if smiles pane is open and GIF tab activated but persists even if Telegam application is inactive and all GIF animations are paused. So it looks like it stop update animation on the screen but continue to decode it in memory.

**Comment by Aokromes** [comment] 2020-01-25 14:13
this bug is still valid?

**Comment by Sam-Tygier** [comment] 2020-01-25 15:16
I cant reproduce now on linux with 1.8.15 from flathub.

**Comment by samtygier** [comment] 2020-01-25 15:17
I cant reproduce now on linux with 1.8.15 from flathub.

**Closed** 2020-02-24 23:25 UTC
Labels: waiting for answer
