### ISSUE TITLE
[Feature Request] Add new "Mark as read" context action in widget with folders

### ISSUE THREAD

**Issue by mikhail-pashkov** [telegramdesktop/tdesktop#7689] opened 2020-04-23 15:45 UTC
### Is your feature request related to a problem?
I frequiently run into the problem when I want to "mark as read" all chats in specific folder.

### Describe the solution you'd like
Add new "Mark as read" context action in widget with folders in main application window. (In addition to "Edit Folder" and "Remove")

### Additional context
I think it will be very useful feature)

**Comment by RememberTheAir** [comment] 2020-04-23 15:48
Duplicate of #7507

**Closed** 2020-04-23 15:50 UTC
