### ISSUE TITLE
Online indicators have different status when user goes offline

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6544] opened 2019-09-13 17:08 UTC
### Steps to reproduce
1. open a chat with a person that is online
2. that person goes offline

### Expected behaviour
Both online indicators (status beneath the user name in conversation & green dot in user list) should be uniform and change their status at the same time.

### Actual behaviour
The status message below the users name in the chat window updates first to e.g. "Last seen recently", while the green dot in the user list next to the users avatar picture stays there. Only when clicking a different conversation it updates/disappears.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.8.8

**Used theme**: none/default

**Comment by 23rd** [comment] 2019-09-14 12:48
I'm afraid this is a duplicate of #6410.

**Closed by 23rd** 2019-09-14 12:48 UTC

**Comment by tooomm** [comment] 2019-09-18 14:40
You are absolutely right! I didn't see it because of the different naming. :)
