### ISSUE TITLE
Linux client resets itself randomly

### ISSUE THREAD

**Issue by Madden91** [telegramdesktop/tdesktop#4435] opened 2018-02-19 13:58 UTC
As I wrote in title, Telegram desktop for Linux randomly resets itself to zero, without updating it or doing something else.

**Steps to reproduce**
I cannot tell how this happens or why or when, seems like the app restarts from zero totally random.

**Expected behaviour**
Surely this is not a feature, I don't think that the client has to reset itself every time I shut down the system. I expect to find the client in the same way I left it the evening before.

**Actual behaviour**
After 2 or 3 weeks of normal behaviour, every setting of the client (themes, notifications, settings, ...) wipes out completely, I have to login into it and re-insert every data or setting that I normally use.

**Configuration**
Ubuntu 17.04 on Asus UX510U

**Version of Telegram Desktop:**
1.2.6, Linux desktop client

**Comment by d0tfile** [comment] 2018-02-19 14:30
@Madden91, may it be connected to unexpected laptop shutdown or problems with hdd/ssd? (I mean it can be caused by file corruption, for example)

**Comment by stek29** [comment] 2018-02-22 13:20
Does it happen after reboot? Maybe DE isn't closing Telegram gracefully?

**Comment by Aokromes** [comment] 2018-05-06 11:56
#3963 ?

**Closed** 2018-05-12 10:32 UTC
Labels: waiting for answer
