### ISSUE TITLE
I need to separate conversation type, and have separate tab for Messages, Groups, Channels, Bots.

### ISSUE THREAD

**Issue by NabiKAZ** [telegramdesktop/tdesktop#5582] opened 2019-01-17 22:12 UTC
I need to separate conversation type, and have separate tab for Messages, Groups, Channels, Bots.
Why don't implement this features?

**Comment by RememberTheAir** [comment] 2019-01-17 22:13
Duplicate of other 100000 issues, use search next time

**Comment by NabiKAZ** [comment] 2019-01-17 22:14
Oh sorry for dublicated, seem there are many issue for this:
https://github.com/telegramdesktop/tdesktop/issues/4463
https://github.com/telegramdesktop/tdesktop/issues/3416
https://github.com/telegramdesktop/tdesktop/issues/2511

But, Why don't implement this?

**Comment by Aokromes** [comment] 2019-01-18 01:15
you can close the ticket yourself, reason is durov brothers doesnt like them

**Closed** 2019-01-19 22:30 UTC
