### ISSUE TITLE
Copy/paste works unstable, stops functioning randomly.

### ISSUE THREAD

**Issue by fractalvision** [telegramdesktop/tdesktop#7494] opened 2020-03-29 19:37 UTC
Subj, copy/paste operations generally work, but the client inevitably stops doing that properly. I've tried different versions of the client and distribution channels: flatpak, snap, finally and seems that the problem still persists, from version to version, after all the updates. Right now, I'm using the dev- branch package of the original client, but copy/paste keeps getting itself disabled randomly. It definitely works after start/restart the app, but then, in some moment, you notice that it doesn't and needs a restart again.

### Steps to reproduce
Start the client and begin chatting intensively, using copy/paste of texts, links and images.

### Expected behaviour
The functionality should not be randomly lost.

### Actual behaviour
The app keeps pasting the content that once was present, but not the actual, latest one, which pastes itself normally in all other open applications. 

### Configuration
Ubuntu 18.04.4 LTS

**Version of Telegram Desktop:**
1.9.22 beta

**Used theme**:
default

**Comment by jeffythedragonslayer** [comment] 2020-03-29 22:50
What about middle-click paste work, does that work?

**Comment by fractalvision** [comment] 2020-03-31 14:29
Nope. When it works (after start/restart), it works by all ways, when stops, all operations shortcuts within the app stop functioning the right way as well.

BTW, the client has updated itself up to the version 2.0 and the problem is still here, so it doesn't depend much on version.

**Comment by Bryophyllum** [comment] 2020-04-20 22:34
I'm able to reproduce this with the Flatpak version of Telegram on GNOME 3.36 Wayland (Fedora Workstation/Silverblue 32):
- Copy text or an image within the client, paste it into a chat, and send it.

Now, copying text and images from other apps to paste them in Telegram should be borked.

**Comment by mariobaldini** [comment] 2020-05-02 17:38
I can confirm this bug in Telegram Desktop Client 2.0.1 (Linux) running in Fedora 32 (kernel 5.6.7-300.fc32.x86_64). 

**Steps to reproduce:** 
- Start the client, it works as expected. Regular paste works.
- Right click any message (ie. to inline reply, forward/edit msg, etc)
- Paste functionality stop working (ctrl+v does not paste anything). 
- Until the client is restarted. If restarted, it works fine again. 

Running the client with `-debug` I can see the following event immediately after the right click: 

`qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

Apparently there is an incompatibility between Telegram Desktop client for Linux and Wayland (which is now default after Fedora 31). 

Cheers,

Mario

**Comment by Aokromes** [comment] 2020-05-02 18:31
try telegram destkop 2.1.1 downloaded from github.

**Comment by virus-found** [comment] 2020-05-17 08:46
Reproduces for telegram desktop 2.1.6 (Wayland Sway).

**Comment by Aokromes** [comment] 2020-05-17 09:24
soooo this bug is wayland only? @fractalvision ?

**Comment by shtirlic** [comment] 2020-05-17 09:56
Nope, latest gnome and Xorg same bug.

**Comment by fractalvision** [comment] 2020-05-22 13:48
> soooo this bug is wayland only? @fractalvision ?

No, currently I'm using the client under the regular Gnome shell (3.28.2), installed from a standalone distribution package, without flatpak, snap or smth. like that. By the way, it was working almost flawlessly for a while, couple of minor updates before it has recently updated itself to the last version (2.1.5).

**Comment by ilya-fedin** [comment] 2020-05-27 01:11
Probably, this is a duplicate of #7223

**Comment by ilya-fedin** [comment] 2020-06-11 10:43
Anyone? :thinking:

**Comment by ilya-fedin** [comment] 2020-06-11 16:46
If no one want to test how then the issue can be solved?

**Comment by Bryophyllum** [comment] 2020-06-11 17:02
@ilya-fedin I'm on 2.1.11 from Flathub; I cannot reproduce by following my instructions:

> I'm able to reproduce this with the Flatpak version of Telegram on GNOME 3.36 Wayland (Fedora Workstation/Silverblue 32):
> 
>     * Copy text or an image within the client, paste it into a chat, and send it.
> 
> 
> Now, copying text and images from other apps to paste them in Telegram should be borked.

..and I haven't experienced any problems with the clipboard itself.

**Comment by ilya-fedin** [comment] 2020-06-11 17:04
> I'm on 2.1.11 from Flathub

but none was done with clipboard in 2.1.11

**Comment by ilya-fedin** [comment] 2020-06-18 19:19
Does anyone have the issue on 2.1.12?

**Comment by shtirlic** [comment] 2020-06-20 09:40
Nope, everything is looking good now, even on big images, I think it's resolved. Gnome/Xorg.

**Closed** 2020-06-20 10:20 UTC
Labels: bug
