### ISSUE TITLE
Telegram-desktop font scale-bitmap-fonts error

### ISSUE THREAD

**Issue by interduo** [telegramdesktop/tdesktop#4109] opened 2017-12-03 11:19 UTC
**### Steps to reproduce**
1. Run Telegram on ubuntu terminal by typing ./Telegram

**### Expected behaviour**
No errors.

**### Actual behaviour**
Got errors on console:
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element

**### Configuration
**Operating system:****
Ubuntu 17.10 with Linux jklntb 4.13.0-18-generic #21-Ubuntu SMP Tue Nov 21 17:01:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
Default

**Comment by auchri** [comment] 2017-12-03 11:22
Duplicate of #517

**Comment by interduo** [comment] 2017-12-03 11:22
Thanks did not found that. Also find that error dosn't exist on alpha.

**Closed by auchri** 2017-12-03 11:22 UTC
