### ISSUE TITLE
Cannot send Photos with Telegram 0.9.10 under Windows 10

### ISSUE THREAD

**Issue by GAlexMES** [telegramdesktop/tdesktop#1320] opened 2015-11-23 20:07 UTC
I can't send photos with the current Telegram version under Windows 10. Telegram tries to send the photo, but it still has the waiting circle after over 20 minutes of waiting.

**Comment by twiforce** [comment] 2015-11-23 20:53
Can confirm this. Files are affected too. Bug has started to appear on Windows 10 version 1511 (build 10586).
Sometimes Telegram app sends file instantly though. Running in compatibility mode or with higher privileges did not helped in my case.

**Comment by tyga** [comment] 2015-11-26 16:10
I also can confirm this after the update to Windows 10 version 1511. Just tried a clean reinstall of the tdesktop app and it fixed the issue for me.

**Comment by GAlexMES** [comment] 2015-11-27 07:29
What exactly do you mean with clean install? I tried a "normal" reinstall, and it did not fix the issue for me.

**Comment by DaFri-Nochiterov** [comment] 2015-11-27 08:00
@GAlexMES, I think, "clean reinstall" is FULLY deleting of app (files, cache, registry)

**Comment by auchri** [comment] 2015-11-27 08:45
And it doesn't work with 0.9.13 either?

**Comment by bereap** [comment] 2015-11-27 14:59
I tried to reinstall the app first and it doesn't work (version 0.9.13). But then I tried to send a compressed image with caption and oddly enough the image could be send. After that sending files worked, too.

**Comment by GAlexMES** [comment] 2015-11-27 18:20
Yes, maybe the 0.9.13 fixed the problem. I uninstalled it, deleted the cache and everything in %appdata% and reinstalled it. That worked for me.

**Comment by twiforce** [comment] 2015-11-27 20:53
File sharing was working for a whole day but right now it stuck again. Don't really know what is triggering this.

**Comment by GAlexMES** [comment] 2015-12-03 20:05
@twiforce yeah, same here. It was more then a day, but is failing now too.
I don't know, what is triggering this too.

**Comment by telegram-error** [comment] 2015-12-12 22:00
This needs to be fixed. It seems to work for like an hour a day and then just stop working at all. The images will not be sent immediatelly but instead hours afterwards.

**Comment by twiforce** [comment] 2015-12-25 19:59
Images are still stuck sometimes.
This might be irrelevant, but I've just sent some images from clipboard (PrtScr, Ctrl+V in Telegram) and after a while app alerted with this:
https://github.com/telegramdesktop/tdesktop/blob/50222ad87e7cb2deb78582985c54f3a70e96ab7e/Telegram/SourceFiles/localimageloader.cpp#L412 ("Could not send an empty file :(")

**Comment by GAlexMES** [comment] 2016-01-06 20:59
Same problem with version 0.9.18.

**Comment by kuyantus** [comment] 2016-01-27 10:04
I can confirm this bug too. Telegram desktop 0.9.18 + windows 10 build 10586, images are not sending.

**Comment by eddiezato** [comment] 2016-02-03 08:24
I confirm this bug too. This is annoying. Telegram 0.9.19 dev, Windows 10586.71

**Comment by srcanseco** [comment] 2016-02-19 05:50
Confirmed this, it is really annoying, even sending an 33 KB image, it freezes at [ 32 / 33KB ]

[Imgur](http://i.imgur.com/msQcIcZ.png)

**Comment by srcanseco** [comment] 2016-02-26 21:36
Can reproduce in tdesktop 0.9.28

**Comment by eddiezato** [comment] 2016-03-01 09:40
Still bugged. Telegram 0.9.28 dev, Windows 10586.104

**Comment by SilentPrayeCG** [comment] 2016-03-14 12:04
My friend, have same problem. I tried figure out what's wrong, but can't. We both have win 10 x64, and for me telegram works fine, for him - is not. Also it start working, kinda, after titling one of sending photo, but bug is return after restarting telegram.

**Comment by twiforce** [comment] 2016-03-14 12:19
When sending large files, e.g. mp3, flac or zip, it stucks just like the images. Hovewer, I've noticed that app fails to send on last 0.2 Mb

**Comment by telegramdesktop** [comment] 2016-03-14 12:59
@twiforce Please try the latest 0.9.30 dev version with files upload. Still the same problem?

**Comment by twiforce** [comment] 2016-03-14 14:32
@telegramdesktop I couldn't find 0.9.30 so I've downloaded 0.9.31 from [here](https://updates.tdesktop.com/tsetup/tportable.0.9.31.zip) (bulit-in updater didn't saw update yet). Drag-and-dropped a large file, same problem:

![telegram](https://cloud.githubusercontent.com/assets/4412289/13747333/d097d20e-ea08-11e5-9e93-b754f385a6b7.gif)

I've tried sending image as a photo by clicking on the button in input, same. Tried to run with compatibility mode (Windows 8) or as administrator — no luck.
Same home network, on phone it works like a charm. Starting to appear on Windows 10 after update to 1511 version. I'll try this update on newer Windows builds, though.

**Comment by telegramdesktop** [comment] 2016-03-14 14:52
@twiforce so it didn't even start to upload?.. Would you please do the following:

1. go to Settings, type "debugmode" and enable debug logs
2. go to any chat and try to upload a photo
3. wait for a minute or two while it tries to upload, without doing anything else
4. quit Telegram and archive DebugLogs folder near Telegram.exe for me

(you can contact me directly at https://telegram.me/preston instead of here, I would suggest you not to upload it here because of the private data in logs, it contains full network activity)

**Comment by SilentPrayeCG** [comment] 2016-03-14 16:01
I also asked friend check 30dev, and then 31stable, and it still doesn't work for him. I mean sending, it didn't stuck, it doesn't start sending at all, except if image was titled, it start working (but sometimes).

**Comment by twiforce** [comment] 2016-03-14 17:04
Done with logs, just checked on Windows 1511, build 14279 (newest Insider build), same troubles.

**Comment by alex04103** [comment] 2016-03-27 17:34
I just want to confirm this. I already uninstalled the desktop client, removed all temporary files and deleted every single Telegram registry key. After reinstalling the client, the behaviour has not changed.

On rare ocassions, the transfer works, but most of the time the progress indicator just shows a dot spinning around. Sometimes I experience another behaviour: The transfer seems to start, the progress indicator shows some progress, but when the indicator shows a complete circle, it just does not disappear and the image is still not transfered.

**Comment by andrew2511** [comment] 2016-04-04 11:31
I have the same problem. Can't find a solution, I've also formatted my pc.

**Comment by andrew2511** [comment] 2016-04-04 16:26
I solved it disabling the function **Large Send Offload** in my ethernet driver settings. Try it!

**Comment by puraminy** [comment] 2016-04-05 14:34
I have this problem in windows 8.1 and Telegram 0.9.32, I am located in Iran,

@andrew2511  where can I find such an option? please guide exactly where should I go.

**Comment by andrew2511** [comment] 2016-04-05 14:46
I've a Killer E2200 Ethernet Controller on Windows 10, I solved in this way:
- Enter in **Device Manager**: (press Win+R, type _devmgmt.msc_ and hit Enter)
- Select your Network device and go to **Driver** tab then **Advanced**
Set:
- Large Send Offload (IPv4) = **Disabled**
- Large Send Offload v2 (IPv4) = **Disabled**
Then reboot. Good luck :)

![image](https://cloud.githubusercontent.com/assets/395639/14285994/d586a578-fb4d-11e5-825b-a17099156bd6.png)

**Comment by puraminy** [comment] 2016-04-05 15:59
@andrew2511  thank you, however I use a wireless modem to connect to internet. However, yet I can plug in with wire. but before I try that I just Restart my computer and now can send pictures!

Then sometimes a restart may fix the problem!

**Comment by pol117** [comment] 2016-04-09 10:00
> I solved it disabling the function Large Send Offload in my ethernet driver settings. Try it!

@andrew2511 Thank you! Worked for me :)

**Comment by twiforce** [comment] 2016-04-09 14:46
Well, can confirm now, it is working well since then, thanks @andrew2511.
Is this still a telegram bug, are you going to fix it?

**Comment by john-preston** [comment] 2016-04-09 15:23
@twiforce I don't know how to fix that :( In the logs it looks like the server always shuts down the connection. Server does not shut it down, looks like OS or something shuts it down.

**Comment by SilentPrayeCG** [comment] 2016-04-22 04:39
I understand disabling this "Large Send Offload" will have a negative impact on network/cpu performance?

**Comment by Extremezhazha** [comment] 2016-05-22 08:16
@andrew2511 Works, and amazingly solved another uploading issue in Chrome. Seems like a system bug or something.

**Comment by jLuca** [comment] 2016-06-07 21:08
Same problem with Telegram Desktop v 0.9.49 and Windows 10 Pro N x64 v 1511 OS Build 10586.318: when uploading files/images, both compressed or uncompressed, the upload doesn't start or hangs most of the times.

**Comment by jLuca** [comment] 2016-06-07 21:16
Disabling Large Send Offload setting of the Network Adapter seems to solve the problem, I had similar troubles with Vivaldi x64 and Chrome x64 trying to upload files/photos (on Twitter etc.): those problems are gone too

**Comment by codercms** [comment] 2016-06-08 12:08
@telegramdesktop do u have a plans to fix this bug?

**Comment by john-preston** [comment] 2016-06-08 12:21
@codercms I don't know how I can fix that "Large Send Offload" problem. From the app it just looks like the server closing the connection when you try to send a part of the file.

**Comment by auchri** [comment] 2016-06-08 12:23
@codercms did you try the following:

> I've a Killer E2200 Ethernet Controller (atheros) on Windows 10, I solved in this way:
- Enter in **Device Manager**: (press Win+R, type _devmgmt.msc_ and hit Enter)
- Select your Network device and go to **Driver** tab then **Advanced**


> Set:
- Large Send Offload (IPv4) = **Disabled**
- Large Send Offload v2 (IPv4) = **Disabled**

> Then reboot. Good luck :)


> ![image](https://cloud.githubusercontent.com/assets/395639/14286036/f8cd38ee-fb4d-11e5-85fe-63407de83f71.png)

**Comment by stek29** [comment] 2016-06-08 13:32
Well, it doesn't seem like a good fix.
But in other hand it looks like windows issue, not TDesktop.

**Comment by andrew2511** [comment] 2016-06-08 13:37
I think it's a driver bug but since this is the only way to fix it, I'm following it...

**Comment by jLuca** [comment] 2016-06-08 17:23
![share](https://cloud.githubusercontent.com/assets/16053048/15903719/55409be2-2dae-11e6-8e48-20c17b39d30e.png)
I reported the issue to Windows Feedback, if you find this useful, please upvote!

**Comment by robsonsobral** [comment] 2016-06-08 23:17
@jLuca , how? I believe you forget the link. ;-)

**Comment by jLuca** [comment] 2016-06-12 14:43
here is the link:
Windows-Feedback:?contextid=79&feedbackid=0ff85153-fdfd-426f-aaba-8c1c33e28a31&form=1&src=2

**Comment by staleo** [comment] 2016-06-23 07:35
Telegram 0.9.51, Win 10, can confirm an issue.

Cmon Telegram guys, seems like lots of Win 10 users cant just upload a thing! Still, how come 8 months later issue still unfixed?

Tried a Large Send Offload thing, that worked for me. But how to deal with tons of others who never google for a solution and just switch to skype back?

**Comment by john-preston** [comment] 2016-06-23 08:05
@staleo Well, the problem is — I don't know, how to fix that from tdesktop side, not from connection properties on Windows :/ maybe we should add an illustrated guide on this Large Send Offload right inside the app.

**Comment by x5f3759df** [comment] 2016-07-22 14:30
Confirmed. Turning off LSO fix the problem.

**Comment by anindis** [comment] 2016-08-08 06:59
windows 10, telegram 0.10.1 file upload is still not working after disabling LSO and rebooting. Skype sends files, VK too

**Comment by Aokromes** [comment] 2016-11-08 09:37
anyone else than codercms have Killer E2200 nic? if yes, i suggest to change killer network drivers by atheros version, killer's driver have one huge memory leak causing a lot of problems.

**Comment by alfalfa31** [comment] 2017-11-04 08:01
Is there a reason this was closed?  It seems like a persistent bug and even in newer versions.

**Comment by Aokromes** [comment] 2017-11-04 09:56
It's opened.

**Comment by stek29** [comment] 2019-03-02 22:04
is this still a thing?

**Comment by Aokromes** [comment] 2019-03-02 23:58
it's drivers bug not telegram bug.

**Closed** 2019-03-03 20:02 UTC
Labels: bug, windows
