### ISSUE TITLE
Telegram desktop 2.7.2 won't flash when receiving a new message.

### ISSUE THREAD

**Issue by javad94** [telegramdesktop/tdesktop#16196] opened 2021-04-26 23:25 UTC
### Steps to reproduce
1. open Telegram desktop
2. minimize it to the taskbar
3. wait until you get a new message

### Expected behaviour
Telegram desktop on taskbar should flash when receiving a new message.

### Actual behaviour
Telegram desktop on taskbar doesn't flash when receiving a new message.

### Configuration
**Operating system:**
Windows 10 x64 version 20H2
**Version of Telegram Desktop:**
2.7.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ronkoren** [comment] 2021-04-27 08:55
Happens to me too on Linux:
- I have a dual-monitor setup
- starting with version 2.7.2 telegram marks new messages on my latest chat as read and does not send notifications, even while not being used (e.g, i am actively using the browser, the focus is not on the telegram window)

**Comment by john-preston** [comment] 2021-04-27 09:11
I can't reproduce that with minimized window. When I minimize the window the notifications appear as before. The second one happens indeed, the messages are marked as read in non-active-but-fully-visible window now, so you can keep an eye on a discussion and still work in some other app without constantly switching back and forth. If you don't want them to mark as read you can simply close the chat by escape or minimize the window.

**Comment by Amir-m-a** [comment] 2021-04-27 11:33
same here with win10 x64 1909 and telegram 2.7.2 .
also I don't get desktop notifications at all.

**Comment by john-preston** [comment] 2021-04-27 11:35
@Amir-m-a Maybe you have Focus Assist set to Alarms Only or Priority Only in the Windows 10 menu?

**Comment by ronkoren** [comment] 2021-04-27 11:46
@john-preston Can't say about others, but specifically for me this behavior change is far from being ideal, actually hurt my work, and also makes my colleges believe i saw their messages while I was focused on other stuff

If this behavior change was planned, I wish there was a way to switch it on/off in the settings

**Comment by Amir-m-a** [comment] 2021-04-27 11:48
> 
> 
> @Amir-m-a Maybe you have Focus Assist set to Alarms Only or Priority Only in the Windows 10 menu?

yeah that was the case, thanks.
I expected only native notifications be affected by that, although this is also reasonable behavior.

**Comment by vonedo3011** [comment] 2021-04-27 13:32
> @john-preston the messages are marked as read in non-active-but-fully-visible window now, so you can keep an eye on a discussion and still work in some other app without constantly switching back and forth. If you don't want them to mark as read you can simply close the chat by escape or minimize the window.

If it's not a bug then it's a horrible decision. Here is a use case: on desktop open chat A, change focus to another window, forget that you have that open chat, go away from your screen but take your phone with you. Phone won't receive any notifications because of that open chat window on desktop, which you forgot about. Get back to your desktop. Turns out you've missed a lot of urgent messages in chat A because telegram-desktop was eating your notifications.

>If you don't want them to mark as read you can simply close the chat by escape or minimize the window.

Yeeeeah, I bet people will often forget to do that (myself included) and wonder where did their notifications go.

**Comment by john-preston** [comment] 2021-04-27 13:39
@vonedo3011 Your use case doesn't differ from "on desktop open chat A, don't (!) change focus to another window, forget that you have that open chat, go away from your screen but take, etc".

For that the messages are marked as read only while you interact with your computer, by mouse or keyboard. No matter if the window is focused or not.

**Comment by vonedo3011** [comment] 2021-04-27 13:59
>@john-preston Your use case doesn't differ from "on desktop open chat A, don't (!) change focus to another window, forget that you have that open chat, go away from your screen but take, etc".

It does. You have said it yourself - "so you can still work in some other app", this implies that yours (user's) attention is somewhere else and not on the chat. Having three monitors I don't want to always keep an eye on some far-away corner. I want to have notifications.

Focused and unfocused behaviors should differ. Focus always implies that user actively paying attention. Unfocused doesn't. Don't break that please, or at least give us a setting to change it back.

>messages are marked as read only while you interact with your computer, by mouse or keyboard.

They aren't. In 2.7.2 I don't have to interact at all for telegram-desktop to mark the messages as "read".  
Even worse, messages are still getting "read" **even when my screen is locked** and the monitors turn off by the lock-screen.

**Comment by john-preston** [comment] 2021-04-27 14:04
@vonedo3011 2.7.3 fixes the locked screen issue.

**Comment by vonedo3011** [comment] 2021-04-27 14:12
@john-preston 2.7.3 still has the same behavior with the lock-screen, at least for me
![image](https://user-images.githubusercontent.com/60707420/116255657-20521b80-a77b-11eb-94f4-69cd601d1f0f.png)

But I guess it will get fixed eventually. What about multi-monitor setups? Do I really have to always keep an eye on some far-away corner to not miss an important message? What if someone has, I don't know, six monitors? 

Can you please give us a setting that flashes notifications for unfocused window?

**Comment by palkalocka** [comment] 2021-04-27 15:21
Same issue. Even when desktop is locked I don't get phone notifications and it's marking as read for the chat that was left open on Telegram desktop. I can't imagine this is the intended behavior. Never had any issues until the last update.

**Comment by john-preston** [comment] 2021-04-27 15:48
@palkalocka Is it happening in 2.7.3? I checked locked screen on 2.7.3, it was not marking them as read :(

**Comment by palkalocka** [comment] 2021-04-27 15:56
Didn't test lockscreen in 2.7.3, but it's still marking as read when it's out of focus. I have five monitors and just leave telegram up in the corner of one, so that's not going to work for me. I went back to 2.7.1. Hopefully if this is supposed to be a "feature" they allow to turn it off in a future version.

**Comment by RidenShark** [comment] 2021-04-27 16:09
I have created an issue for notification problem #16215. Please check/discuss there as this issue looks like it's related to taskbar flashing. Related perhaps.

**Comment by RidenShark** [comment] 2021-04-27 16:11
I have created an issue for notification problem #16215. If any, please discuss there as this issue looks like it's related to taskbar flashing. Related perhaps.

**Comment by javad94** [comment] 2021-04-27 16:11
> I can't reproduce that with minimized window. When I minimize the window the notifications appear as before. The second one happens indeed, the messages are marked as read in non-active-but-fully-visible window now, so you can keep an eye on a discussion and still work in some other app without constantly switching back and forth. If you don't want them to mark as read you can simply close the chat by escape or minimize the window.

I disabled the notifications because I want only the icon flashing in the taskbar. based on your other comments, it seems now this behavior is related to Windows Focus Assist feature because when Focus Assist set to Alarms Only icon in the taskbar is not flashing but when Focus Assist is off, the telegram icon in the taskbar flashing normally (with a slight delay now).

**Comment by SelfDestructor** [comment] 2021-04-27 18:50
I have a quad monitor setup and with 2.7.2 and 2.7.3 Telegram marks messages as read and does not notify of new messages when it is open, visible and not the active window.

I have missed out on about 30 messages so far that I didn't even know arrived because it was automatically marked as read and I don't pay attention to my chat apps unless a notification plays. And if I leave my PC unlocked and walk away to do something, then I will not se a single notification on my phone either.

I do not wish to minimize or close the active chat because I will read it on my own pace once notifications comes in.

As others has said, if this is not a bug but a feature, PLEASE at least add a toggle to enable or disable this.
If it's to prevent multiple notifications, do it like Discord and have an option to only send out mobile notifications after X-minutes of inactivity on a desktop platform.

**Comment by tmelorc** [comment] 2021-04-28 01:47
@john-preston I'm using Telegram 2.7.3 (updated today) on Linux Mint 18 and the icon flashing only appears if the Telegram window is minimized. 
With Telegram opened but another window on top, there is no icon flashing indicating new messages in red circle.

**Comment by Ingvin** [comment] 2021-04-28 09:04
> @john-preston I'm using Telegram 2.7.3 (updated today) on Linux Mint 18 and the icon flashing only appears if the Telegram window is minimized.
> With Telegram opened but another window on top, there is no icon flashing indicating new messages in red circle.

Fedora 33, the same problem.

**Comment by benplumley** [comment] 2021-04-28 15:16
> The second one happens indeed, the messages are marked as read in non-active-but-fully-visible window now, so you can keep an eye on a discussion and still work in some other app without constantly switching back and forth. 

I think this is a bad call - people with a lot of monitors don't look at the entire visible area at all times, and might not even notice movement in their peripheral vision. This caused me to miss a lot of notifications today. I didn't realise until I read this bug report thread that the messages weren't just failing to notify, they were actually being _marked as read_ - I must have looked quite rude.

It also breaks how desktop OS users expect 'focus' and 'unfocus' to work. We expect unfocused windows to notify in exactly the same way a minimised window does - this is a rule that's widely understood and followed by software that uses notifications or title-bar flashes.

If I want to keep an eye on a chat while working undisturbed in another window, I can use the "focus assist" settings that already exist in Windows to achieve this.

**Comment by palkalocka** [comment] 2021-04-28 16:08
> > I think this is a bad call - people with a lot of monitors don't look at the entire visible area at all times, and might not even notice movement in their peripheral vision. This caused me to miss a lot of notifications today. I didn't realise until I read this bug report thread that the messages weren't just failing to notify, they were actually being _marked as read_ - I must have looked quite rude.

The lack of desktop notifications on an unfocused window is bad, but marking as read so I don't even get the notification on my phone is the real killer for me. If I don't notice or walk away from the computer, now I'm missing messages all day on my phone, yet the person thinks I've received them. 

Someone had to SMS me yesterday to see if I was okay because I wasn't getting any notifications from them in Telegram. Ended up clearing all my custom notifications and reinstalling Telegram on my phone before I realized it was the desktop app causing the issue. First world problems for sure, but why fix something that's not broken 🙂

**Comment by DenisPolishchuk** [comment] 2021-04-28 19:00
Hello, i have same problem. _Sorry for my English, i'm Ukrainian._. I found a small solution but it is inconvenient. When you finish chatting, press **X** instead **_** and don't press Alt+Tab.

**Comment by SelfDestructor** [comment] 2021-04-28 20:44
A fix has been pushed! Thank you team! https://github.com/telegramdesktop/tdesktop/releases/tag/v2.7.4

**Comment by palkalocka** [comment] 2021-04-28 21:16
2.7.4 is working for me! Thank you!

**Closed** 2021-04-28 22:13 UTC
