### ISSUE TITLE
Option to disable "autoplay next" on voice messages, audio, video messges, etc?

### ISSUE THREAD

**Issue by surashu** [telegramdesktop/tdesktop#3649] opened 2017-07-11 17:41 UTC
### Steps to reproduce
1. Play a voice message, audio,, or video message which was sent some time ago.
2. After the media finishes playing, the next media after it starts playing automatically.
3. It's going to play until it reaches the last media file sent.

### Expected behaviour
I wanted to make it so that if I play a voice message or something, after that plays, it's going to stop at that and not continue further. Of course since this is an option, it's up to the user to decide which behavior they want.

### Actual behaviour
It plays all the media files consecutively.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.1.10
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Tuupertunut** [comment] 2017-07-15 15:05
Yes! This is needed. In my opinion, this should even be the default option.

Reasoning:
A conversation has a certain order. Usually consecutive messages are responses to each other and therefore must be read/listened in order. Currently, Telegram will autoplay next voice messages even when there are text messages in between. It makes no sense to jump over 10 messages from the previous voice message to the next without reading the 10 text messages in the middle. Also if you browse the history and want to listen to an old voice message, you end up listening all of them until present.

**Comment by Scvairy** [comment] 2017-07-17 19:24
There is better solution for "middle text messages". Add an option "play media consecutively only if followed one by one".

**Comment by christophemarois** [comment] 2017-11-05 03:38
+1

**Comment by mbasaglia** [comment] 2017-12-02 12:59
I agree with this, the current behaviour makes it difficult to catch up with old messages because it can skip dozens of text messages between voice messages.

**Comment by utmuk** [comment] 2018-01-04 13:27
I vote for this one too

**Comment by francoyo1998** [comment] 2019-02-08 00:34
I think that it is a very important option. I don't believe that this is not implemented yet.

**Comment by douglasanpa** [comment] 2019-09-24 01:21
+1

**Comment by MajeQafouri** [comment] 2019-11-09 18:00
I need this option to do my exam :(((

**Comment by kavnik** [comment] 2019-12-12 11:13
Please add at least in the settings the ability to disable auto-play!
It is very inconvenient when it's need to listen only one message.

**Comment by superboot** [comment] 2019-12-12 13:16
Yes, Please add this option. It is so useless the way it is.

**Comment by taimaiduc** [comment] 2020-02-25 03:40
Yes. Please add this option 🙏

**Comment by leodcs** [comment] 2020-03-19 18:43
I don't understand how this is not an option from the beginning. I hate the way it is currently implemented. Please add this option

**Comment by superboot** [comment] 2020-03-19 19:15
Does anyone know where this is in the code? How hard can it be? Let's submit a pull request with it fixed. Who wants this anyway? At the very least it shouldn't loop back to the first media file after playing the most recent.

**Comment by RememberTheAir** [comment] 2020-03-20 10:31
> Let's submit a pull request with it fixed

I doubt there is no option to disable this behaviour because the dev wasn't able to add it, or didn't have time. It's designed to be this way - no option to disable autoplay. Also because the mobile clients don't have it either. Even if you open a pr, I highly doubt it will ever be merged :( but you never know

**Comment by rkcell** [comment] 2020-08-25 08:13
Please add this option. 🙏

It's absolutely necessary to make orderly flows of audio messages, for example in language learning bots with lots of audition.

**Comment by mbasaglia** [comment] 2020-10-24 09:18
I would still like this option

**Comment by utmuk** [comment] 2020-10-24 10:33
I think most of the users would like this option. Who likes telegram jumping through whole text sections of conversation to play all audio messages automatically?

**Comment by Noxware** [comment] 2020-10-26 03:02
Nobody. It amazes me how this issue still exists after 3 years. It is absolutely necessary to fix this. Telegram will never be perfect if this issue continues existing. Why isn't this problem solved after 3 years!?

**Comment by mbasaglia** [comment] 2020-10-26 06:36
it's funny because I'd be willing to fix it but telegram desktop doesn't have working instructions on how to build it

**Comment by RememberTheAir** [comment] 2020-10-26 07:45
@Noxware because it's not a bug, it's the intended behavior

**Comment by asterisk753** [comment] 2021-01-05 07:23
This the most urgent single bug to fix in Telegram (both mobile and desktop) and many people I personally know agree it's really annoying the way it works now.
Autoplay in any form is deprecated for many good reasons in 2020, and however you see it, it should never - ever - be forced onto users. Please Telegram, at least give the option to disable it!

**Comment by gilshani07** [comment] 2021-02-04 08:03
Autoplaying next was the best feature in telegram.  When this feature was enabled nobody needs any other platfrom, all music is there in the most convenient way to play.

**Comment by eioo** [comment] 2021-02-04 08:06
@gilshani07

> ...was...

Does it not exist anymore?

**Comment by gilshani07** [comment] 2021-02-04 08:37
Yes it is, my mistake. The thing is you can't reverse the order of playing, and it played the last track

**Comment by utmuk** [comment] 2021-02-04 11:28
@gilshani07
What are you talking about? This is an app for messages mainly. When there are text messages between voice message it is really stupid to play next. I wish devs made it like in whatsapp - adjacent messages autoplay, but separated messages don't. This is most logical way

**Comment by RememberTheAir** [comment] 2021-02-04 11:44
> What are you talking about? This is an app for messages mainly. When there are text messages between voice message it is really stupid to play next

This issue is asking to a change in behavior of _audio_ messages too (= music), this is why @gilshani07 left a comment about uninterrupted music play. I too think think that uniterrupted play for audio messages is cool, but it might result annoying for voice messages. This issue is too broad in its requests - audio and voice messages are perceived by the user in a different way and used/played in different contexts, and thus a change in behavior is justified by different motives. Also, autoplay for videos and GIFs can be disabled from the advanced settings. I think we should have different issues for audio messages autoplay and voice/video messages autoplay

**Comment by gilshani07** [comment] 2021-02-04 12:50
> > What are you talking about? This is an app for messages mainly. When there are text messages between voice message it is really stupid to play next
> 
> This issue is asking to a change in behavior of _audio_ messages too (= music), this is why @gilshani07 left a comment about uninterrupted music play. I too think think that uniterrupted play for _audio_ messages is cool, but it might result annoying for _voice_ messages. This issue is too broad in its requests - audio and voice messages are perceived by the user in a different way and are used/played in different contexts, and thus a change in behavior would be justified by different motives. I think we should have different issues for audio messages autoplay and voice/video messages autoplay

Some channels has no voice messages sent into them at all only audio like music as voice messages what makes telegram a very nice platform for playing music, it could be also added as feature that can be set by current chat/channel

**Comment by RememberTheAir** [comment] 2021-02-04 14:02
@gilshani07 I think that having a per-channel option would be too verbose considering 99% of channels are not used to share music, so such an option would be useless in most cases. Anyway the player bar has a "repeat" option - when enabled, Telegram will not auto-play the next track, but will loop the current one. Maybe adding an additional state there to play the current track _once_ and then stop would be a good compromise between options cluttering and music-playing tuning. This would not conflict with an additional setting to disable non-consecutive voice messages auto-play, so the music player will continue to work as always.

I've just searched for such a suggestion on https://bugs.telegram.org about voice messages autoplay, and it looks like nobody opened it yet. I think it's worth to bring this there, since nobody moderating this issues tracker can decide to change Telegram's behavior on every official app

**Comment by guictr** [comment] 2021-08-12 16:09
We need this urgently.

**Comment by ciricc** [comment] 2021-08-28 19:00
We need this urgently.

**Comment by zawawimanja** [comment] 2021-12-06 04:55
Still not having this feature after a lot years?!

**Comment by bpsib** [comment] 2022-01-05 19:42
The dev obviously doesn’t give a toss about us. Autoplay next winding me up like bloody hell. IT DRIVES ME BLOODY BALMY. I NEED A DISABLE AUTOPLAY OPEN NOW. IT’S UNBELIEVABLE IT DOESN’T HAVE A DISABLE AUOTOPLAY NEXT OPTION. Implementing it is NOT rocket science for Christ sake.

**Comment by neruthes** [comment] 2022-02-23 14:08
Let's just wait for another century!

**Comment by goldmont** [comment] 2022-03-04 09:15
+1

**Comment by mineLdiver** [comment] 2022-03-05 06:39
Thought it was just a simple issue I was having, but it has been out here in the issues for FIVE years?!

**Comment by OlliC** [comment] 2022-03-05 09:00
+1

**Comment by RememberTheAir** [comment] 2022-03-09 07:54
I've just updated to version 3.5.6 and under _settings_ -> _advanced_ -> _experimental settings_, there's an option to disable this behavior

**Closed** 2022-03-09 08:43 UTC
Labels: enhancement

**Comment by guictr** [comment] 2022-03-09 09:00
I think the Beta version in only available for desktop.
