### ISSUE TITLE
Problem with the application window frame

### ISSUE THREAD

**Issue by postusername** [telegramdesktop/tdesktop#16721] opened 2021-07-30 15:51 UTC
### Steps to reproduce
1. Update Telegram Desktop to 2.9 version
2. Move the window OR scroll in chat OR scroll chat list OR etc.

### Expected behaviour
The frame remained as before

### Actual behaviour
The frame is mixed with the system one, as well as the buttons.

### Configuration
**Operating system:** Windows 7 SP1 (64-bit)
**Version of Telegram Desktop:** 2.9
**Used theme**: Don`t matters. as well as ANGLE graphic backend settings (Different backend just give different amount of bug.)

![image](https://user-images.githubusercontent.com/35779067/127678789-fe110a58-0801-4343-8b46-692b9f765577.png)

**Comment by ilya-fedin** [comment] 2021-07-30 16:04
this bug is as old as the application, last time reported at #8218

**Comment by postusername** [comment] 2021-07-30 16:10
> this bug is as old as the application, last time reported at #8218
Anyway, it isn`t happened with me before this version and still not resolved.

**Comment by ilya-fedin** [comment] 2021-07-30 16:11
It's not known why this is happening, so it's not known how to resolve this

**Comment by postusername** [comment] 2021-07-30 16:35
2.8.11 works fine :thinking: Maybe trouble in new in-chat animations: kind of graphical library support?

**Comment by ilya-fedin** [comment] 2021-07-30 16:38
Main window was switched to Ui::RpWindow used by other windows (video/voice calls/chats)

**Comment by snorlax212** [comment] 2021-07-30 19:01
sup. appeared after update to 2.9.0. using telegram-desktop on windows 7 x64 for about 1 year, never saw this. 

![](https://i.imgur.com/Y5ve6Ta.png)

**Comment by WPMGPRoSToTeMa** [comment] 2021-07-30 23:44
Experiencing the same issue, never seen this before.

**Comment by Kommprog** [comment] 2021-07-31 07:29
Also have the same bug with this blue frame after the new update. It's seen on both day/night themes.

![bug1](https://user-images.githubusercontent.com/84424346/127732382-bfbdcbbe-bb6c-469d-b96f-aedbe155c110.jpg)
![bug2](https://user-images.githubusercontent.com/84424346/127732383-93f1d069-3843-4027-a52c-ca54a6aae9f4.jpg)

**Comment by romanpastu** [comment] 2021-07-31 08:49
Related issue there too after the update.
I cant move the window around now.
It seems to be in constant full screen mode.

**Comment by Hobbix** [comment] 2021-07-31 11:03
I confirm this problem. Windows 7 SP1 (64-bit), Version of Telegram Desktop: 2.9.
The previous version did not have this problem.

Screenshot:
![frame](https://user-images.githubusercontent.com/8199105/127737856-3431c46f-6656-465a-8bfd-8e7e39a2e4b2.png)

**Comment by servokot** [comment] 2021-07-31 14:28
Confirm. Windows 7 SP1 (x64), Telegram Desktop: 2.9.0 (x64)
Previous version (2.8) did not have this problem.
![Screenshot_1](https://user-images.githubusercontent.com/37119134/127742984-f273aaaf-1f49-4a5b-9dcf-3d33c9828ccb.jpg)

**Comment by SanderBouwhuis** [comment] 2021-07-31 14:31
I have the same problem. Is there a way I can go back to a previous version?
I cannot move the window, and worse : I cannot close it with <ESC> key anymore.
Now I have to choose 'Quit Telegram' in the icon tray just to close the window.

Please heeeeeeeeeeeeeeeelp!!!

**Comment by Aokromes** [comment] 2021-07-31 15:13
> I have the same problem. Is there a way I can go back to a previous version?
> I cannot move the window, and worse : I cannot close it with key anymore.
> Now I have to choose 'Quit Telegram' in the icon tray just to close the window.
> 
> Edit:
> I tried installing an older version, but now I'm in DEEP trouble. It asks for a verification code that they claim they sent to my 'previous app' (huh?!?! What?!?!)
> It says I need to open Telegram on 'my phone', but I'm using Telegram instead of Whatsapp because I don't have a smartphone. Clicking on 'Send SMS' tells me to open the QR code on my phone. I DON'T HAVE A SMARTPHONE.
> 
> Please heeeeeeeeeeeeeeeelp!!!
> Please heeeeeeeeeeeeeeeelp!!!
> Please heeeeeeeeeeeeeeeelp!!!
> Please heeeeeeeeeeeeeeeelp!!!
> Please heeeeeeeeeeeeeeeelp!!!
> Please heeeeeeeeeeeeeeeelp!!!
> Please heeeeeeeeeeeeeeeelp!!!
> Please heeeeeeeeeeeeeeeelp!!!
> 
> PS
> All the data files are still on my harddisk (I just tried to install an older version).

try enabling use system window frame with 2.9.

**Comment by SanderBouwhuis** [comment] 2021-07-31 16:13
> 
> 
> > I have the same problem. Is there a way I can go back to a previous version?
> > I cannot move the window, and worse : I cannot close it with key anymore.
> > Now I have to choose 'Quit Telegram' in the icon tray just to close the window.
> > Edit:
> > I tried installing an older version, but now I'm in DEEP trouble. It asks for a verification code that they claim they sent to my 'previous app' (huh?!?! What?!?!)
> > It says I need to open Telegram on 'my phone', but I'm using Telegram instead of Whatsapp because I don't have a smartphone. Clicking on 'Send SMS' tells me to open the QR code on my phone. I DON'T HAVE A SMARTPHONE.
> > Please heeeeeeeeeeeeeeeelp!!!
> > Please heeeeeeeeeeeeeeeelp!!!
> > Please heeeeeeeeeeeeeeeelp!!!
> > Please heeeeeeeeeeeeeeeelp!!!
> > Please heeeeeeeeeeeeeeeelp!!!
> > Please heeeeeeeeeeeeeeeelp!!!
> > Please heeeeeeeeeeeeeeeelp!!!
> > Please heeeeeeeeeeeeeeeelp!!!
> > PS
> > All the data files are still on my harddisk (I just tried to install an older version).
> 
> try enabling use system window frame with 2.9.

That is impossible because I cannot log in to Telegram Desktop anymore. It keeps asking for a code I don't have that is supposedly send to a 'previous app' (what is that?) that I don't have. It also says to scan a QR code, that I can't.
I have all the files still on my harddisk, so I don't understand what the problem is.

I'm very desperate because I got a bunch of people to use Telegram because I don't have a smartphone. I really REALLY prefer not to switch to another messenger.

**Comment by ilya-fedin** [comment] 2021-07-31 18:07
As soon as you running old version, it cleans tdata since downgrade is not supported. You can't log in without app on smartphone (yeah, now Telegram is like WhatsApp regarding this).

**Comment by SanderBouwhuis** [comment] 2021-07-31 19:21
> 
> 
> As soon as you running old version, it cleans tdata since downgrade is not supported. You can't log in without app on smartphone (yeah, now Telegram is like WhatsApp regarding this).

WTF?!?
I cannot believe it. I have to move to another platform because of this?!?!?!??!?!?!??!?!?!?!?!?!?!
I am absolutely stunned.

Would restoring a backup work?
If so, which files are essential to make sure I can log in?

**Comment by ilya-fedin** [comment] 2021-07-31 19:27
It should work, just copy entire tdesktop profile directory (tdata)

**Comment by WPMGPRoSToTeMa** [comment] 2021-07-31 19:31
> 
> 
> As soon as you running old version, it cleans tdata since downgrade is not supported. You can't log in without app on smartphone (yeah, now Telegram is like WhatsApp regarding this).

By the way, will installing Telegram app on a VM with Android work for that purpose?

**Comment by SanderBouwhuis** [comment] 2021-07-31 19:33
> 
> 
> It should work, just copy entire tdesktop profile directory (tdata)

Where is that directory located please?

**Comment by ilya-fedin** [comment] 2021-07-31 19:37
Theoretically it should

**Comment by andmm** [comment] 2021-08-04 19:12
Reporting the same problem here since updating to the latest stable release (2.9), this never happened before with me.

**Closed** 2021-08-10 12:46 UTC
