### ISSUE TITLE
Telegram can not connect to server when KIS is running

### ISSUE THREAD

**Issue by ilyahoilik** [telegramdesktop/tdesktop#849] opened 2015-06-25 01:36 UTC
Hello! After update to latest version, Telegram can not connect to server. I see "Connecting..." status. And after ~10 second Telegraam freezes.

I investigated and... This problem occurred when Kaspersky Internet Security is running. I close KIS and I see notice about Akamai NetSession Client, blocked by my firewall. If I press Allow, Telegram unfreezes and connection established. There is no problem with connecting if KIS is not running.

Telegram 0.8.30
Kaspersky Internet Security 15.0.0.463(b)

![2015-06-25 04-09-56 telegram](https://cloud.githubusercontent.com/assets/7265704/8345076/ab612746-1af2-11e5-996f-1b4fd937f608.png)

**Comment by mchernetsky** [comment] 2015-06-25 08:32
The same problem after updating to version 0.8.30 Telegram.
Only I should Kaspersky Ani-Virus 14.0.0.4651(i).
Solution: added proxy server settings Telegram.

**Comment by Mindstormer619** [comment] 2015-06-25 09:00
Oh wow the same issue. And KIS as well. Is there a fix I can do without killing my antivirus?

**Comment by telegramdesktop** [comment] 2015-06-25 09:05
Does it have some sort of whitelist? IPv6 connection attempt was added in the last version, I'm afraid KIS on some reason blocks all the network activity when sees it :/

**Comment by Mindstormer619** [comment] 2015-06-25 09:08
I checked my KIS settings and Telegram is allowed on all permissions. I also added it manually in Windows Firewall here:

![image](https://cloud.githubusercontent.com/assets/441849/8351010/b04ce18c-1b47-11e5-8c45-66c12cf7e4dd.png)

The problem is still not fixed. I uninstalled and reinstalled it and now I cannot even sign in as my sending my number says "Connecting..." forever.

**Comment by Mindstormer619** [comment] 2015-06-25 09:22
@telegramdesktop I really cannot use Telegram Desktop at all till you guys fix this. Could you temporarily revert it to IPv4? I tried allowing it through all the settings Kaspersky has... the problem still persists.

**Comment by telegramdesktop** [comment] 2015-06-25 10:05
And even when it is allowed on all permissions in KIS settings, still temporarily disabling it allows Telegram to connect?

**Comment by Mindstormer619** [comment] 2015-06-25 10:31
Yes. That's right. It works perfectly when KIS is disabled completely.

**Comment by telegramdesktop** [comment] 2015-06-25 10:33
I'm preparing 0.8.32 version now with a hotfix for critical crashing bug + I've disabled IPv6 connection there, let's check if that will work. If it will, I'll move IPv6 connection enabling in Settings, disabled by default until we have some contact with KIS.

**Comment by Mindstormer619** [comment] 2015-06-25 10:35
Thank you so much for the quick fix. I assume this will update into the stable channel? Please comment here when the fix is up, I'll update and test immediately.

**Comment by telegramdesktop** [comment] 2015-06-25 11:38
The stable version 0.8.32 is released, please check if it works with KIS enabled. Connecting through IPv6 is disabled there.

**Comment by mchernetsky** [comment] 2015-06-25 11:38
Updated to 0.8.32 - works fine running KAV.

**Comment by Mindstormer619** [comment] 2015-06-25 11:43
Updated, seems to be working fine for me right now. Howvever it was connecting and disconnecting frequently earlier, so I don't know if it would continue working reliably. If it stops anytime, I'll let you know here. Thanks for the quick reponse @telegramdesktop

**Comment by Mindstormer619** [comment] 2015-06-25 12:10
It looks to be working fine so far. I suppose the issue is fixed. @ilyahoilik you can possibly close the issue.

**Closed** 2015-06-25 12:11 UTC
