### ISSUE TITLE
Cyrillic "й" and "ё" broken

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8140] opened 2020-06-25 19:00 UTC
### Steps to reproduce
1. copy and paste text from instagram https://www.instagram.com/p/CB2iMpBpW48/
2. all words with "й" and "ё" will be "broken":
![image](https://user-images.githubusercontent.com/39812401/85781240-26780580-b72e-11ea-8482-b563d1097d67.png)

It's happens only in TDesktop. If I copy-paste these words to [pastebin ](https://pastebin.com/EF7W2MsA)for example, they will be ok. On iOS official telegram app all is ok too:
![image](https://user-images.githubusercontent.com/39812401/85781663-9a1a1280-b72e-11ea-84cd-8fedef18d7f6.png)

And they broken if I copy-paste them from telegram to another telegram chat:
![image](https://user-images.githubusercontent.com/39812401/85783212-c4200480-b72f-11ea-8ec9-b2b8553c009c.png)

**UPD**: Same issue with some youtube videos, example:
https://www.youtube.com/watch?v=fYzPmrAwnHk
![image](https://user-images.githubusercontent.com/39812401/85786491-fbdc7b80-b732-11ea-926c-c8a1dd175338.png)

All fonts is default.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:**  2.1.13
**Used theme**: dark default

**Comment by ilya-fedin** [comment] 2020-06-26 01:26
> It's happens only in TDesktop.

I can reproduce in qBittorrent and other Qt applications in my system as well:
![image](https://user-images.githubusercontent.com/17829319/85810847-d5770a00-b74b-11ea-8f58-69f13631e49f.png)
Keep in mind that this doesn't real `й` and `ё`, but an unicode character sequence, probably, auto-replaced on typing on iOS/macOS.

**Comment by Neurotoxin001** [comment] 2020-09-11 14:33
I tested it in qBittorrent 4.2.5:
![image](https://user-images.githubusercontent.com/39812401/92937915-986e0a00-f454-11ea-84e5-82c9625ddb9b.png)
![image](https://user-images.githubusercontent.com/39812401/92937925-9b68fa80-f454-11ea-8c52-5e691ec4142b.png)
No issue.

Also I created ticket on QT Bug Reports website:
https://bugreports.qt.io/projects/QTBUG/issues/QTBUG-86588?filter=allopenissues

And developer said he can't reproduce this bug:
![image](https://user-images.githubusercontent.com/39812401/92938042-c2273100-f454-11ea-8228-9e1e792f1d17.png)

So I think this bug is only in TDesktop. Or it's because of older version of QT that TDesktop uses.

Can you please look into it?

**Comment by ilya-fedin** [comment] 2020-11-06 06:01
Looks like I found an older report of this: https://github.com/telegramdesktop/tdesktop/issues/2651

**Comment by Neurotoxin001** [comment] 2020-11-06 11:15
Seems like it's not a Qt problem
https://github.com/telegramdesktop/tdesktop/commit/9210cf6d365f5f9122431901039e2310e01b84a3
After this I still have issue on 2.4.8 beta
![image](https://user-images.githubusercontent.com/39812401/98360232-81096280-203a-11eb-9482-5fecf3051a2f.png)

**Comment by guzszisvww** [comment] 2020-11-21 14:55
The Russian letter "**й**" (**U+0439**) is sometimes displayed incorrectly, and sometimes displayed correctly. After copying this letter into **Notepad**, it is displayed correctly in both cases: when it is incorrectly displayed in **Telegram Desktop**, and when it is displayed correctly in **Telegram Desktop**.

I noticed that the Russian letter "**й**" (**U+0439**) is displayed normally in **Qt** (and therefore displayed normally in **Telegram Desktop**), and the combination of symbols "и" (**U+0438**) and **U+0306** is not displayed correctly.

Some texts contain the **U+0439** symbol, and some texts contain a combination of symbols **U+0438** and **U+0306**.
In text, both of these variants look the same in **Notepad**, but the two variants look different in **Telegram Desktop**.

I found examples where the Russian letter "**й**" is represented both by the symbol **U+0439** and by a combination of the symbols **U+0438** and **U+0306**.
And we can see what both of these variants look like.

1. Example 1
https://t.me/skgovby/3395
![photo_2020-11-13_07-40-18 (2)](https://user-images.githubusercontent.com/48548398/99880057-efd4e700-2c08-11eb-87b7-a2cafc69bf31.jpg)

2. Example 2
https://t.me/skgovby/3406
![wrongый](https://user-images.githubusercontent.com/48548398/99880063-f9f6e580-2c08-11eb-85e8-d95ae3dffe53.jpg)

**Comment by Neurotoxin001** [comment] 2021-05-20 19:55
+

**Comment by Neurotoxin001** [comment] 2021-11-17 05:36
+

**Comment by opentitan** [comment] 2022-05-04 16:14
Still actual

Real life cases [are produced by iOS devices](https://github.com/telegramdesktop/tdesktop/issues/8140#issuecomment-649897597)

**Comment by Neurotoxin001** [comment] 2022-06-14 20:46
So it's only visual bug in tdesktop. App must not shift right these symbols:
`ё`
`й`

I can even copy these dots:
`̆ `
`̈ `

**Comment by Neurotoxin001** [comment] 2022-12-12 06:13
`+`

**Comment by Neurotoxin001** [comment] 2022-12-12 18:25
Stale bot is broken?

**Comment by vehlwn** [comment] 2023-02-11 11:50
+1. Combining symbols are still broken, and not only in Telegram Desktop, but on Android too. Seems like it's some global issue with fonts.

Try something + [Combining Breve](https://unicode-table.com/en/0306/) U+0306 or [Combining Diaeresis](https://unicode-table.com/en/0308/) U+0308 :

```
s̆
ӹ
```

![Screenshot_20230211_153407](https://user-images.githubusercontent.com/36479428/218256007-2c0ac1a5-02db-4409-b912-eb4f74a1e26e.jpg)
![Screenshot_20230211_153506](https://user-images.githubusercontent.com/36479428/218256008-e40a353b-b727-47ea-b3fd-82b81e5fc815.png)

PS: Why not apply some form of Unicode normalization to combine diacritics before sending message?

**Comment by lilydjwg** [comment] 2023-02-11 12:46
> PS: Why not apply some form of Unicode normalization to combine diacritics before sending message?

Only some characters have a pre-combined version. Also, I don't like it to alter my message. The partial markdown translation has already caused trouble when sending code snippet.

**Comment by ilya-fedin** [comment] 2023-02-11 13:04
> Try something + [Combining Breve](https://unicode-table.com/en/0306/) U+0306 or [Combining Diaeresis](https://unicode-table.com/en/0308/) U+0308 :

Ah, so it's a duplicate of #6362. The bad news is these characters are a part of the character blacklist which won't be changed due to potential regressions it can create.

**Closed** 2023-02-11 13:16 UTC
