### ISSUE TITLE
[Feature Request] Customize no of chats to pin only in Telegram Desktop

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5298] opened 2018-10-25 03:09 UTC
Currently the no of chats to pin in 5 which is inadequate.
Maybe a Frequent chat horizontal list would be useful like in Android

**Comment by RememberTheAir** [comment] 2018-10-25 06:19
Duplicate of so many issues I'm not even going to link them here

**Comment by SmartManoj** [comment] 2018-10-25 07:50
Due to small size of mobile screen, maybe they limit it to 5.
It would be nice something like favourites in Plus messenger only in Desktop Client since it has wide screen

**Comment by RememberTheAir** [comment] 2018-10-25 08:01
#3026 #3406 #4037 #4249 #4600 #4870 #5261 duplicate of these, your suggestion has already been discussed there. The current behaviour is not going to change uless the API changes this number

**Closed** 2018-10-25 08:11 UTC
