### ISSUE TITLE
1.3.10 fails to build with gcc-7.3.0

### ISSUE THREAD

**Issue by adrianopol** [telegramdesktop/tdesktop#5014] opened 2018-07-25 14:00 UTC
Building telegram-desktop-1.3.10 fails when compiling with gcc-7.3.0:

    /var/tmp/portage/net-im/telegram-desktop-1.3.10/work/telegram-desktop-1.3.10/Telegram/SourceFiles/export/data/export_data_types.cpp: In lambda function:
    /var/tmp/portage/net-im/telegram-desktop-1.3.10/work/telegram-desktop-1.3.10/Telegram/SourceFiles/export/data/export_data_types.cpp:413:59: internal compiler error: 
    Segmentation fault
        if constexpr (MTPDphotoCachedSize::Is<decltype(data)>()) {
                                                               ^
    Please submit a full bug report,
    with preprocessed source if appropriate.

### Configuration
* OS: Gentoo GNU/Linux, amd64
* GCC: https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-devel/gcc/gcc-7.3.0-r3.ebuild
* telegram ebuild: https://github.com/reagentoo/gentoo-overlay/blob/master/net-im/telegram-desktop/telegram-desktop-9999.ebuild
* enabled USE-flags: abi_x86_64 amd64 elibc_glibc kernel_linux pulseaudio userland_GNU

**Comment by john-preston** [comment] 2018-07-25 14:01
@adrianopol Report ICE to gcc bugtracker please.

**Comment by adrianopol** [comment] 2018-07-25 14:04
OK.

**Comment by Johnnynator** [comment] 2018-07-25 14:11
Duplicate oft #4967

**Closed** 2018-07-25 14:13 UTC
