### ISSUE TITLE
File handle isn't closed after uploading a video

### ISSUE THREAD

**Issue by aarivex** [telegramdesktop/tdesktop#10007] opened 2020-12-25 12:53 UTC
### Steps to reproduce
1. Upload a video/send a video to somebody or yourself.
2. Attempt to delete the uploaded video after the upload has finished.

### Expected behaviour
The file handle should've been closed because Telegram is not using the video file anymore.

### Actual behaviour
You have to close/restart the Telegram window in order to remove the video file because its still using it.

### Configuration
**Operating system:** Windows 10 64-bit

**Version of Telegram Desktop:** 2.5.1 (hasn't been fixed in ages)

**Comment by ilya-fedin** [comment] 2020-12-25 14:43
> The file handle should've been closed because Telegram is not using the video file anymore.

It uses. It plays the file in chat.
Anyway, duplicate of #7818

**Comment by aarivex** [comment] 2020-12-25 15:22
Thanks. Seems like you can remove the file when switching the chat, but that doesn't make sense.

Why should Telegram use the local video file to generate the preview instead of the uploaded one?
Or at least move it into a cache.

**Closed** 2020-12-25 16:05 UTC
