### ISSUE TITLE
[Feature Request] Add a possibility to regroup groups in a "Parent group"

### ISSUE THREAD

**Issue by llann** [telegramdesktop/tdesktop#2333] opened 2016-08-07 15:21 UTC
### Steps to reproduce
1. User create a Parent group and give it a name
2. User select the groups he want to put together
3. Save the new Parent group
4. User can see the "Parent group" and click on it to "Expand the children and then to close it back again

### Expected behaviour
Have a way to quickly see how many messages are unread for a topic, for exemple "University" and be able to organise groups in a clean way to improve efficiency.

**Exemple:**

![telegram subgroup closed](https://cloud.githubusercontent.com/assets/5268385/17463268/868fca54-5cc2-11e6-98f5-cd79b28584fe.png)

![telegram subgroup open](https://cloud.githubusercontent.com/assets/5268385/17463267/868f9ec6-5cc2-11e6-930f-bc44e8ec587c.png)

### Actual behaviour
Same topic groups are lost in the middle of other conversations and the best way to see them all at a glance is to give them the same name, like "University - Project xyz", "University Assignment", etc. and then make a Search with "University".

### Configuration
**Operating system:**
Operating system: Windows 10.0.14393

**Version of Telegram Desktop:**
Telegram v 0.10.1

**Comment by Kondra007** [comment] 2016-08-08 10:30
That's API Issue, "nested" groups are not available.

**Comment by auchri** [comment] 2016-08-08 10:31
Yes and it's a duplicate of another one.

**Closed by auchri** 2016-08-08 10:31 UTC
