### ISSUE TITLE
[Feature Request] Add disable sticker animations option

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [telegramdesktop/tdesktop#6246] opened 2019-07-08 15:12 UTC
### Is your feature request related to a problem?
There is no possibility to disable the animated stickers.

### Describe the solution you'd like
I'd add the possibility to disable it adding an option in `Advanced` → `Performance` with the Enable animations and Autoplay GIFs.

![image](https://user-images.githubusercontent.com/7454137/60821202-589df980-a1a3-11e9-8401-c24aacaa0f4a.png)

**Comment by PeterFeicht** [comment] 2019-07-08 17:52
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/6234

**Closed** 2019-07-08 17:54 UTC
Labels: duplicate
