### ISSUE TITLE
Let admins change user permissions right from the chat

### ISSUE THREAD

**Issue by Intenditore** [telegramdesktop/tdesktop#7176] opened 2020-02-10 17:02 UTC
If you want to permanently block the user you can do it right from the chat while deleting his message. But what if you want to block it temporary? You have to go to "chat info" and find him amongst all the rest of users! 
I propose to let admins do it right from the chat through context menu

**Comment by RememberTheAir** [comment] 2020-02-10 17:05
Duplicate of #6136

**Comment by MasterGroosha** [comment] 2020-02-10 17:54
Not a solution, but an advice: if you deleted someone's message, you can right-click their avatar in Recent actions and choose "Restrict user" option.

**Closed** 2020-02-10 18:13 UTC
