### ISSUE TITLE
[Feature request] Toggle the visibility by clicking on the notification icon

### ISSUE THREAD

**Issue by bpierre** [telegramdesktop/tdesktop#938] opened 2015-07-24 10:43 UTC
On Ubuntu, I would like to have a mode where the Open / Minimize / Quit menu is replaced by an app visibility toggle (close and open the window, without quitting the app), à la Twitter.app on OS X.

That mode could use the left click if activated in the settings, or it could just be available all the time using the right / middle click.

If implemented using an option and the left click, it would still be possible to quit the app using the Unity launcher or Ctrl+Q if #703 is fixed at some point in the future.

**Comment by ralesk** [comment] 2015-08-03 09:06
In KDE at least, this is how it behaves and has behaved forever.

(Though in 0.8.43 it seems that one click will set Urgent on the window if it's otherwise unhidden (WHY), the second click hides the window, yet another click shows and focuses the window)

**Comment by auchri** [comment] 2015-08-14 22:19
I think this is a duplicate of #481?

**Comment by auchri** [comment] 2017-02-08 11:11
Hey there!

We're automatically closing this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 528 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

<sub>(Please note that this is an [automated](https://github.com/auchri/github_auto_closer) comment.)</sub>

**Closed by auchri** 2017-02-08 11:11 UTC
Labels: auto closed, linux
