### ISSUE TITLE
[X][linux] xclipboard not working when selecting messages from message window.

### ISSUE THREAD

**Issue by fjfalcon** [telegramdesktop/tdesktop#961] opened 2015-08-05 08:16 UTC
In linux, so as in any X server there is clipboard that works when you select text by mouse. After selection can be pasted anywhere by middle click on mouse. 
Problem here: 

in telegram desktop if you select your message, while you typing it - xclipboard gets text from it. 
When you select text in messages - nope.

**Comment by Quarx2k** [comment] 2015-08-05 13:26
Same problem on Ubuntu 15.04 + Unity

**Comment by aluminiumgeek** [comment] 2015-08-06 10:11
+1

**Comment by auchri** [comment] 2015-08-29 23:13
Duplicate of #530

**Closed by auchri** 2015-08-29 23:13 UTC
Labels: linux

**Comment by chernomyrdin** [comment] 2016-01-27 11:36
+1
