### ISSUE TITLE
Telegram uses GTK file picker instead of QT

### ISSUE THREAD

**Issue by Germano0** [telegramdesktop/tdesktop#5003] opened 2018-07-21 16:49 UTC
### Expected behaviour
Telegram uses Qt lib so it should use QT file picker. It uses GTK file picker instead

### Configuration
**Operating system:**
Fedora 28 KDE Spin

**Version of Telegram Desktop:**
1.3.10

**Used theme**:
Default

**Comment by john-preston** [comment] 2018-07-21 16:56
@Germano0 There are several issues demanding the opposite 😔

**Comment by Germano0** [comment] 2018-07-21 17:19
> @Germano0 There are several issues demanding the opposite pensive

Can you explain?

**Comment by Aokromes** [comment] 2018-07-21 17:54
@Germano0 
https://github.com/telegramdesktop/tdesktop/issues/2411 (this ticket is sort of duplicate of this)
https://github.com/telegramdesktop/tdesktop/issues/982

**Closed** 2018-07-22 04:33 UTC

**Comment by msva** [comment] 2018-09-17 03:13
By the way, @Germano0, https://github.com/telegramdesktop/tdesktop/pull/3778
There is a way to disable GTK things for about a year already.

And @john-preston was mean that gtk file chooser was added because of ubuntuers whining that "qt file chooser is very ugly under our unity" and so on.

Although, that decision wasn't take in account that KDE users was pretty fine with "Qt" dialogs (since KDE, as Qt-based DE can replace them by native ones), and suffers from GTK dialogs...

Anyway, if you building tdesktop from source, you're definitelly able to disable that gtk crap.

// and if you're using "binary" builds:
1) it's on maintainer decision (if we're talking about distro's binary repos)
2) you'll continue to suffer (if we're talking about prebuilt packages from telegram.org (or whatever).
