### ISSUE TITLE
[Feature Request] Hold mobile notifications for a bit longer after focus change

### ISSUE THREAD

**Issue by roobre** [telegramdesktop/tdesktop#1738] opened 2016-03-06 14:55 UTC
I usually use Telegram on my desktop while doing other tasks on my pc. Sometimes I'm talking with someone and I alt-tab to another window to chek my email, for example. Then, 3 seconds later, a message arrives. As TD is not in foreground, the notification is sent to my phone, which is a bit annoying since I'm still using Desktop.

Could we get an option to keep mobile notifications off a bit longer (like, 20s) after TD goes to background?
Or even an option to keep them off as long as the app is running but not minimized, for example?

Regards

**Comment by diazbastian** [comment] 2016-03-07 19:24
@roobre I am not a developer, but I understand the functioning of the Telegram service.

Telegram clients are synchronized with your account (TDesktop, Android, webogram, etc) and these show notifications at the same time if they are connected to the Internet. There is no synchronization between clients, therefore it is not possible what you ask.

You can mute notifications on Android or iOS and focus on the use of TDesktop while at your desk.

**Comment by auchri** [comment] 2016-03-07 19:26
Duplicate of #277 btw.

**Closed by auchri** 2016-03-07 19:26 UTC
