### ISSUE TITLE
Telegram 3.3.0 will not run Raspberry pi 4 8GB 

### ISSUE THREAD

**Issue by Maltesecanuck** [telegramdesktop/tdesktop#17388] opened 2021-12-11 18:57 UTC
### Steps to reproduce

installed from snap
package installs fine.
Will not run from command line, or from desktop icon. 

### Expected behaviour

up to 1 day ago telegram opened and ran perfect. 

### Actual behaviour

will not run. in command line warning: cgroup v2 not fully supported yet, proceeding with partial confinement
a list of error files follow.

### Operating system

Raspbian GNU/Linux 11 (bullseye) armv

### Version of Telegram Desktop

raspberry pi snapd v3.3.0

### Installation source

Snap

### Logs

```shell
pi@raspberrypi:~ $ telegram-desktop
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Segmentation fault
```

**Comment by ilya-fedin** [comment] 2021-12-12 07:32
You need to run the application with gdb and get a stacktrace of the crash

**Comment by Maltesecanuck** [comment] 2021-12-13 01:21
not sure how qualified I am to do this but here it goes.  I ran this first 
-> pi@raspberrypi:~ $ gdb -q telegram-desktop
Reading symbols from telegram-desktop...
(No debugging symbols found in telegram-desktop)
->(gdb) run 
Starting program: /snap/bin/telegram-desktop 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xa6b7d440 (LWP 22410)]
[New Thread 0xa61ff440 (LWP 22411)]
[New Thread 0xa57ff440 (LWP 22412)]
[New Thread 0xa4ffe440 (LWP 22413)]
[New Thread 0xa43ff440 (LWP 22414)]
[Thread 0xa43ff440 (LWP 22414) exited]
[Thread 0xa4ffe440 (LWP 22413) exited]
[Thread 0xa57ff440 (LWP 22412) exited]
[Thread 0xa61ff440 (LWP 22411) exited]
[Thread 0xa6b7d440 (LWP 22410) exited]
process 22407 is executing new program: /snap/core/11997/usr/bin/snap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb6dce440 (LWP 22418)]
[New Thread 0xb63ff440 (LWP 22419)]
[New Thread 0xb59ff440 (LWP 22420)]
[New Thread 0xb51fe440 (LWP 22421)]
[New Thread 0xb47ff440 (LWP 22422)]
[Detaching after fork from child process 22423]
[New Thread 0xb3bff440 (LWP 22424)]
[Thread 0xb3bff440 (LWP 22424) exited]
[Thread 0xb47ff440 (LWP 22422) exited]
[Thread 0xb51fe440 (LWP 22421) exited]
[Thread 0xb59ff440 (LWP 22420) exited]
[Thread 0xb6dce440 (LWP 22418) exited]
process 22407 is executing new program: /snap/core/11997/usr/lib/snapd/snap-confine
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
need to run as root or suid
[Inferior 1 (process 22407) exited with code 01]
->(gdb)backtrace
no stack.
(gdb)quit
->pi@raspberrypi:~ $ gdb -q \
      -batch \
      -ex 'set print thread-events off' \
      -ex 'handle SIGALRM nostop pass' \
      -ex 'handle SIGCHLD nostop pass' \
      -ex 'run' \
      -ex 'thread apply all backtrace' \
      --args \
      telegram-desktop \
      arguments-to-telegram-desktop
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
process 23393 is executing new program: /snap/core/11997/usr/bin/snap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[Detaching after fork from child process 23409]
process 23393 is executing new program: /snap/core/11997/usr/lib/snapd/snap-confine
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
need to run as root or suid
[Inferior 1 (process 23393) exited with code 01]

I know this is not what you were asking for directly but for my skill level this is the best I came up with.

**Comment by ilya-fedin** [comment] 2021-12-13 01:25
`snap run --gdb telegram-desktop

**Comment by Maltesecanuck** [comment] 2021-12-13 04:03
pi@raspberrypi:~ $ snap run --gdb telegram-desktop
GNU gdb (Raspbian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /snap/core/11997/usr/lib/snapd/snap-confine...
(No debugging symbols found in /snap/core/11997/usr/lib/snapd/snap-confine)
Starting program: /snap/core/11997/usr/lib/snapd/snap-confine --base core20 snap.telegram-desktop.telegram-desktop /usr/lib/snapd/snap-exec --command=gdb telegram-desktop
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[Detaching after fork from child process 20631]
[Detaching after fork from child process 20632]
process 20628 is executing new program: /usr/lib/snapd/snap-exec
[New LWP 20634]
[New LWP 20635]
[New LWP 20636]
[New LWP 20637]
[New LWP 20638]
[LWP 20638 exited]
[LWP 20637 exited]
[LWP 20636 exited]
[LWP 20635 exited]
[LWP 20634 exited]
process 20628 is executing new program: /usr/bin/dash
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

**Comment by ilya-fedin** [comment] 2021-12-13 04:07
You need to enter `run` and then it can multiple times pause the executable, enter `cont` until it really crashes (and then `bt full`)

**Comment by Maltesecanuck** [comment] 2021-12-13 04:32
no subsequent commands are accepted after the above mentioned command. snap run --gdb telegram-desktop

**Comment by ilya-fedin** [comment] 2021-12-13 04:34
It means the binary is running

**Comment by aiskendi** [comment] 2021-12-13 14:42
I have this problem too after update telegram 3.3.0 on Raspberry Pi 3b+ running latest Raspberry Pi OS bullseye.

**Comment by mr-massimo** [comment] 2021-12-15 18:21
I have the same problem after update telegram 3.3.0 (snap package) on Raspberry Pi 4 B running latest Raspberry Pi OS bullseye 32 bit.

**Comment by N0NJY** [comment] 2021-12-22 20:08
I am running this on a RasPi 4 (inserted intoa RasPad 3 tablet).  I have been unable to get TG to work except elderly versions (using either flatpak which is 2.2 I think, or a sudo apt install version which is 1.1 and will not allow update).  The following is my output from the --gdb:

GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /snap/core/11997/usr/lib/snapd/snap-confine...(no debugging symbols found)...done.
Starting program: /snap/core/11997/usr/lib/snapd/snap-confine --base core20 snap.telegram-desktop.telegram-desktop /usr/lib/snapd/snap-exec --command=gdb telegram-desktop
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[Detaching after fork from child process 2323]
[Detaching after fork from child process 2326]
process 2320 is executing new program: /usr/lib/snapd/snap-exec
[New LWP 2334]
[New LWP 2335]
[New LWP 2336]
[New LWP 2337]
[New LWP 2338]
[LWP 2338 exited]
[LWP 2337 exited]
[LWP 2336 exited]
[LWP 2335 exited]
[LWP 2334 exited]
process 2320 is executing new program: /usr/bin/dash
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

**Comment by ilya-fedin** [comment] 2021-12-22 20:27
ARM Linux is not an officially supported platform, so this would be fixed only by someone interested in fixing this

**Comment by Maltesecanuck** [comment] 2021-12-23 15:20
Interesting. I have installed the new POP! For pi. Telegram works fine on that OS.

**Comment by Aokromes** [comment] 2021-12-23 15:43
maybe it's kernel issue.

**Comment by ilya-fedin** [comment] 2021-12-23 15:53
If that was a kernel issue, it was something like the sendfile issue on update, but there's a segfault. We can't know what's the problem without a crash trace and no one provided one (no of the provided gdb outputs have a backtrace)

**Comment by ilya-fedin** [comment] 2021-12-23 15:57
> using either flatpak which is 2.2 I think

flatpak's runtime stopped to provided 32-bit ARM builds a year ago. In order to use flatpak, you need to install a 64-bit OS. I guess, Canonical will eventually do the same and snap won't have 32-bit ARM builds, as well.

**Comment by ilya-fedin** [comment] 2021-12-23 16:28
> maybe it's kernel issue.

This can be an issue with snapd, though. I wonder whether they checked other snaps.

**Comment by aoitori-asd** [comment] 2021-12-24 05:00
> > maybe it's kernel issue.
> 
> This can be an issue with snapd, though. I wonder whether they checked other snaps.

I'm not OP, but I just tried with with gedit and it worked fine.

**Comment by ilya-fedin** [comment] 2021-12-24 09:54
> I'm not OP, but I just tried with with gedit and gedit worked fine, just not telegram-desktop.

Is gedit strictly confined like tdesktop or classic confined? You should check other strictly confined apps like tdesktop, not classic confined, the latters are just like AppImages and have no sanboxing (so the thing that may break snaps won't affect them).

**Comment by Maksim-Bartoshyk** [comment] 2022-01-13 21:34
Could you please suggest any way to install 3.2.x version? Looks like snap only has latest one, which does not work.

**Comment by ilya-fedin** [comment] 2022-01-13 21:35
I guess snap doesn't allow to install old versions by design

**Comment by ilya-fedin** [comment] 2022-01-13 21:37
I believe the best bet for you guys is to switch to a distro that has software from this century (e.g. Arch) and use tdesktop from distro repository

**Comment by Maksim-Bartoshyk** [comment] 2022-01-13 21:39
Is there any way to download old source and build?

**Comment by ilya-fedin** [comment] 2022-01-13 21:41
That has no sense, old version won't even let you to log in

**Comment by Maksim-Bartoshyk** [comment] 2022-01-13 21:43
Got it, thanks.

**Comment by Maltesecanuck** [comment] 2022-01-14 15:12
PopOS on the pi runs telegram no problem. A pretty good distro. Ubuntu has just released a pi desktop as well.

**Comment by alexander-uljev** [comment] 2022-05-22 07:32
I had the same issue, switched to 64 bit version of official Raspberry Pi OS and I can confirm Telegram works there with no issues (installed it from snap).

**Closed** 2022-05-22 09:12 UTC
Labels: bug
