### ISSUE TITLE
`NoArchive` folder filter is handled inconsistent with mobile iOS app when a chat is both included and excluded

### ISSUE THREAD

**Issue by yeputons** [telegramdesktop/tdesktop#8427] opened 2020-08-15 08:57 UTC
### Steps to reproduce
1. Choose an arbitrary chat X.
2. Archive the chat X.
3. Create a folder which "includes" the chat X (as an individual chat, not by chat type), but "excludes" all archived chats. 
4. Check whether the folder shows the chat X in tdesktop.
4. Check whether the folder shows the chat X in mobile app (I've used iOS).

### Expected behaviour
Behavior should be consistent between tdesktop and iOS app: either chat X is consistently shown both in tdesktop and mobile app, or the folder is consistently empty.

### Actual behaviour
Behavior is inconsistent: tdesktop 2.3 shows the chat X (i.e. its exclusion by "archived" does not work), but iOS app 7.0 does not (i.e. it excludes all archived chats, even if they're explicitly listed in the "archived" section).

### Configuration
**Operating system:** Windows 10 Pro 2004 (build 19041.450)

**Version of Telegram Desktop:** 2.3

**Used theme**: the default one

### Extra thoughts

I believe the correct behavior is the one where "exclude" rules have priority (it also coincides with iOS app's logic). Usecase: I archive/unarchive a chat on a regular basis and I would like it to be hidden/shown in all folders where it participates. E.g. some chats are for non-urgent work, so I archive them from "Work" folder while on vacation.

### Possible fix

Fix should probably land around `ChatFilter::contains` around [`data_chat_filters.cpp:215`](https://github.com/telegramdesktop/tdesktop/blob/887b6629f66e3e15786938f3bf7593bca39eaa31/Telegram/SourceFiles/data/data_chat_filters.cpp#L215): mass exclusion policies (`NoMuted`, `NoRead`, `NoArchived`) are checked for chats included by a mass inclusion policy (`Bots`, `Contacts`, etc), but not for chats included individually (`_always`). Note that I have zero experience in tdesktop code, and there may be other places need fixing, e.g. `ChatFilters::archiveNeeded` and its users, maybe?

**Comment by RememberTheAir** [comment] 2020-08-17 07:16
On Android, manually included chats have the priority over exclusionary filters (which as far as I know is the intended behavior), so you _should_ always see that chat on iOS too

**Comment by RememberTheAir** [comment] 2020-10-23 09:31
In #8428 @john-preston clarified this is the expected behavior and this should be fixed in the iOS app. I guess this issue can be closed?

**Closed** 2020-10-23 10:04 UTC
