### ISSUE TITLE
In the desktop version there is no view statistics button but in the mobile version there is

### ISSUE THREAD

**Issue by hero442** [telegramdesktop/tdesktop#9975] opened 2020-12-23 11:49 UTC
![image](https://user-images.githubusercontent.com/68087530/102993334-46da1e80-451d-11eb-9e7d-4a960b9aa38f.png)

**Comment by hero442** [comment] 2020-12-23 11:50
![photo_2020-12-23_12-49-59](https://user-images.githubusercontent.com/68087530/102993383-5fe2cf80-451d-11eb-9522-1e28b91ce040.jpg)
mobile version

**Comment by RememberTheAir** [comment] 2020-12-23 11:55
Duplicate of #7678

**Closed** 2020-12-23 13:50 UTC
Labels: question
