### ISSUE TITLE
This issue hit is unfortunate that they have blocked a very important request such as sensitivity for people with disabilitiesas been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

### ISSUE THREAD

**Issue by discapacidad5** [telegramdesktop/tdesktop#16060] opened 2021-03-27 16:43 UTC
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

_Originally posted by @github-actions[bot] in https://github.com/telegramdesktop/tdesktop/issues/10328#issuecomment-806485409_

In the United States and some other countries by law it is mandatory that all applications must have a minimum of accessibility also the reason tells us that it should be compatible for people with disabilities to have the same opportunity as other people to use the application This is something that shouldn't be blocked If it hasn't been resolved yet

instead of blocking it they should work on developing the necessary accessibility accessibility

the fact that there is no constant participation It is not that there is no interest in its development, but unfortunately people with disabilities do not have the same do that as the rest of the people to be able to demand their service and that is why the rest of us must advocate for they

**Comment by Aokromes** [comment] 2021-03-27 16:50
that issue is duplicate of another opened.

**Comment by Aokromes** [comment] 2021-03-27 16:50
https://github.com/telegramdesktop/tdesktop/issues/476

**Closed by Aokromes** 2021-03-27 16:50 UTC
