### ISSUE TITLE
Client should use the date format defined by the system

### ISSUE THREAD

**Issue by ronakg** [telegramdesktop/tdesktop#618] opened 2015-03-30 23:01 UTC
Right now the date is shown in DD.MM.YY format on the list of conversations. This is not how it's shown everywhere else on my system.

It should ideally take the format from the system.

**Comment by auchri** [comment] 2015-09-04 17:13
@telegramdesktop http://doc.qt.io/qt-5/qt.html#DateFormat-enum

**Comment by PerryVerheij** [comment] 2016-01-26 19:22
@telegramdesktop, this is still not solved and I would like it very much if it would be.

**Comment by alindt** [comment] 2016-03-28 20:12
Indeed, both date _and_ time should use the system defined formats

**Comment by XP1** [comment] 2016-05-22 01:41
See also:

[feature request][improvement] customizable short date format in session list #1920:
https://github.com/telegramdesktop/tdesktop/issues/1920

**Comment by BryanEllis** [comment] 2016-08-16 18:27
The DD.MM.YY format is very annoying.  I use YYYYMMDD everywhere else in my system.  Being backwards in Telegram is disorienting.

**Comment by lindhe** [comment] 2017-07-11 09:40
I was just about to say. It really should look at the systems locale setting to choose date/time format accordingly. And if it doesn't, it should definitely use ISO 8601, not some random string of integers that I need to guess what it means.

![Preposterous date format](https://user-images.githubusercontent.com/7773090/28062217-85107302-662d-11e7-8059-3f14562f31ff.png)

**Comment by guzszisvww** [comment] 2019-07-12 09:04
Serious bug not fixed in 4 years !!! Developers, stop working on design themes and other nonsense, fix major bugs.

**Comment by JulyIghor** [comment] 2019-12-22 01:18
This is not only Date problem. Need Time format setting also (12/24 mode)

**Comment by Aokromes** [comment] 2020-01-19 09:44
imho a setting to allow people to use system date and custom is the way to go.
https://i.imgur.com/bVnrL5n.png

**Comment by anibyl** [comment] 2020-02-26 13:59
It would awesome to have date/time format settings.

**Comment by anibyl** [comment] 2020-10-24 01:03
The issue is still there.

**Comment by NilsIrl** [comment] 2020-12-15 22:07
To change the date and time format, change the [`LC_TIME`](https://wiki.archlinux.org/index.php/Locale#LC_TIME:_date_and_time_format) environment variable.

**Comment by SaltfishAmi** [comment] 2020-12-17 11:42
> To change the date and time format, change the [`LC_TIME`](https://wiki.archlinux.org/index.php/Locale#LC_TIME:_date_and_time_format) environment variable.

DD.MM.YY is hard coded.
https://github.com/telegramdesktop/tdesktop/search?utf8=%E2%9C%93&q=%22d.MM.yy%22

**Comment by NilsIrl** [comment] 2020-12-17 18:18
> > To change the date and time format, change the [`LC_TIME`](https://wiki.archlinux.org/index.php/Locale#LC_TIME:_date_and_time_format) environment variable.
> 
> DD.MM.YY is hard coded.
> https://github.com/telegramdesktop/tdesktop/search?utf8=%E2%9C%93&q=%22d.MM.yy%22

From what I can tell, this is code related to the API. I am on nixos which doesn't seem to ship [a modified a version of telegram](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix).

Running telegram in the following way does work:

```sh
LC_TIME=en_GB.UTF8 telegram-desktop
```

**Comment by anibyl** [comment] 2021-06-15 18:47
The issue is still there.

**Comment by AmirHosseinKarimi** [comment] 2021-06-21 11:59
Yea. Just **6 years** need to fix this bug. 
oh, wait! it's not fixed yet?

**Comment by SaltfishAmi** [comment] 2021-06-21 12:34
No, it's not.
Come on...

**Comment by landry314** [comment] 2021-07-10 03:11
Wow, this is an annoying bug. I see the date on my mac desktop as DD.MM.YY written as a number. This confuses me because I am in the United States. It is fine on Android where it spells out the month.

6 years and this bug is still here? Add a setting for date format or make a English (United States) option for language which fixes this or spell out the month as mmm or take it from MacOS from my region. Just pick one. Wow.

**Comment by SaltfishAmi** [comment] 2021-07-10 03:49
Yeah, that's really annoying and as an Asian when I write date in English I always spell out the month because oh well I really don't make things more complicated...             SaltfishAmi   Sent from phone   ---- On Sat, 10 Jul 2021 11:11:48 +0800  ***@***.******@***.***> wrote ---- 
Wow, this is an annoying bug. I see the date on my mac desktop as DD.MM.YY written as a number. This confuses me because I am in the United States. It is fine on Android where it spells out the month. 
6 years and this bug is still here? Add a setting for date format or make a English (United States) option for language which fixes this or spell out the month as mmm or take it from MacOS from my region. Just pick one. Wow.

**Comment by zeroskyx** [comment] 2021-07-21 10:28
Any news one the topic? Same issue exists for time; if mapping it to system settings is too complicates for now, why not allow users to select it in advanced settings?

- MM/dd/yyyy
- dd.MM.yyyy
- yyyy-MM-dd

And for times

- h:mm a
- HH:mm

Etc?

**Comment by psydrin** [comment] 2021-09-12 20:16
Issue still exists here on the Windows desktop version.

**Comment by CoderTimZ** [comment] 2021-09-12 20:34
I don’t know if the developers are just being stubborn or what. I realize the American date format makes no sense, but it’s not like it’s our fault. It is what it is. And this isn’t just an aesthetic preference. Any date less than 13 is ambiguous. For example, today’s date in Telegram is written as 12.09.2021. To an American this looks like December 9th. It leads to so much confusion having to remember to convert the format. I don’t understand why it’s so difficult to use the localization settings in the operating system to determine the date format like every other sensible app.

**Comment by landry314** [comment] 2021-09-14 06:50
yeah it makes no sense they would ignore this.

**Comment by ilya-fedin** [comment] 2021-09-14 14:52
>  I don’t understand why it’s so difficult to use the localization settings in the operating system to determine the date format like every other sensible app.

This is not a priority, apparently. If this is priority for you, you can fix it yourself and create a PR. Or wait another 5 years.

**Comment by uzabojrumn** [comment] 2021-09-29 11:14
To fix this bug, Telegram teem needs professional programmers educated at the university after several years of training.
Amateurs who think they became programmers after reading one little book called "Programming for Dummies" or after a 2-month training course, will not be able to fix this bug.
And I will add one more thing. Real programming professionals wouldn't have had to fix this bug because they wouldn't have made it.

Try something like this.
```
QDate    dateCurrent = QDate::currentDate();
QString   sDateForUsersEmbitteredAfterManyYearsOfWaiting = dateCurrent.toString(QLocale::system().dateTimeFormat());
```

**Comment by teohhanhui** [comment] 2021-09-29 13:35
@uzabojrumn Why not send a PR instead of making fun of the developers?

**Comment by BryanEllis** [comment] 2021-09-29 15:42
@uzabojrumn I started programming when I was 9 years old. Way back in the cassette tape to boot days.  I learned by having a mentor, not formal education. By the time I went to university for Computer Science I knew more than my professors. The only difference was I knew the concepts but not the "ivory tower" technical names for them. In fact, most of my professors had a PhD but had never worked in a real environment. Some had never written more than 100 lines of code for a single project.  At the time I was working in FoxPro and wrote a 60,000 line application in 8 weeks.  It ran slow so I rewrote the primary worker in C++ but the API failed to work.  Anyway, I totally disagree with the university idea unless they change how they teach.
To learn a spoken language you lean the alphabet, then words that match concepts, then sentence structure, and finally you start writing.  Many times computer programming languages are taught by throwing the dictionary (online help or textbook) at the student to see what sticks.  If the concepts are not learned first that future programmer will have a hard time learning new languages or moving to other platforms.  I've programmed in about 13 different languages professionally.  I never could learn foreign spoken languages (I barely seem to know English most of the time) since the concepts were so tied to English words in my mind.  The most important skill for a future programmer is knowing how to learn.  Secondarily they must be able to visualize and organize the requirements prior to writing code.  I've always thought a short-order cook (from a place that yells out the orders to them - like Waffle House in US) might be a good person to train since they keep multiple customer's orders in their head, time the food to complete with the order, and complete the orders quickly. This is basically Agile type workflow in a physical realm.

**Comment by ilya-fedin** [comment] 2021-09-29 18:32
If you think you move the issue forward by teaching the you're wrong... The problem is not in that know someone how to implement or not, but in the priority of the issue (so paid developers don't have time for that issue, they have a way more prioritized tasks). You can continue to complain in the issue or create a PR and start a review process, so that core developers tell you what's wrong with this approach and what should be done.

**Closed** 2021-10-11 17:56 UTC
Labels: bug
