### ISSUE TITLE
CPU high load

### ISSUE THREAD

**Issue by sstyle** [telegramdesktop/tdesktop#4238] opened 2017-12-26 10:10 UTC
![2017-12-26 13 07 56](https://user-images.githubusercontent.com/6489964/34354276-34eb72f6-ea3e-11e7-89f0-b73f41eb4c69.png)
### Steps to reproduce
1. Open Telegram app as a front window
2. Look at System monitor

### Expected behaviour
Very high load CPU. 40-60%

### Actual behaviour
Have to be 0-5%

### Configuration
10.13.2

**Version of Telegram Desktop:**
1.2.3

**Used theme**:
Dark

**Comment by MaineKampfCoon** [comment] 2017-12-27 09:51
Issue reproduces legit for me too on macOS High Sierra 10.13.2
<img width="912" alt="2017-12-27 12 48 04" src="https://user-images.githubusercontent.com/1559803/34377926-7c287f58-eb04-11e7-8458-6bbc38053985.png">

<img width="698" alt="2017-12-27 12 51 10" src="https://user-images.githubusercontent.com/1559803/34377956-ac65d2d8-eb04-11e7-9e2a-edadfa004e70.png">

**Comment by vng** [comment] 2018-01-01 15:38
Same thing for me. Started after the regular update about a month ago.
Laptop becames very noisy with coolers.

**Comment by Scukerman** [comment] 2018-01-01 17:43
I'm experiencing the same thing since a long time ago.

![image](https://user-images.githubusercontent.com/6469803/34469611-3608562c-ef34-11e7-9ec9-9917e238a08c.png)

**Comment by Aokromes** [comment] 2018-01-07 00:33
generic bug #4132 ?

**Comment by auchri** [comment] 2018-01-09 11:55
Duplicate of #3640

**Closed by auchri** 2018-01-09 11:55 UTC
