### ISSUE TITLE
[Feature Request]: Hidding the person's messages.

### ISSUE THREAD

**Issue by lokot0k** [telegramdesktop/tdesktop#8117] opened 2020-06-22 14:57 UTC
A function that hides all messages from a person just for you in group chat. Others can see them, but only if they haven't hidden them.

**Comment by RememberTheAir** [comment] 2020-06-22 15:13
Not really a duplicate of #1025 or #1281 or #5492, but both the functions would result in a similar experience, so you can refer to the discussion in these issues (anyway we still miss an API in the protocol schema for that, so tdesktop can't do nothing about it)

**Closed** 2020-06-22 16:36 UTC
