### ISSUE TITLE
Telegram's window/text too small on HiDpi screen

### ISSUE THREAD

**Issue by mareg** [telegramdesktop/tdesktop#4586] opened 2018-04-10 17:26 UTC
### Steps to reproduce
1. Dell XPS 13 with 4k screen 
2. MATE Desktop correctly recognizes hiDPI screen and sets `QT_SCALE_FACTOR` to `2`, which works great for most of the QT based application
3. Text in Telegram Desktop is smaller - roughly 60% of text in menus/apps

### Expected behaviour
Text size should be same as desktop's size - 12pt, it seems telegram is either 9 or 8pt.

### Actual behaviour
Text is too small to comfortably read.

### Configuration
**Operating system:**
Fedora Linux 27 with MATE Desktop 1.20.1

**Version of Telegram Desktop:**
telegram-desktop-1.2.15-1.fc27.x86_64

**Used theme**:
No theme/standard theme used

Additional information:
switch like `--force-scale-factor=2.5` would be nice, I can change `QT_SCALE_FACTOR` to `2.5` globally, but it upscales all Qt based apps, I just need Telegram to match the text size on the desktop.
e.g. vlc has correct text size in menus/preferences.

**Comment by lucidyan** [comment] 2018-09-13 20:34
Looks like a duplicate of https://github.com/telegramdesktop/tdesktop/issues/1121

**Comment by stek29** [comment] 2018-09-14 09:36
Also see #4064

**Closed** 2018-09-14 09:36 UTC
