### ISSUE TITLE
1.9.14 win7 x64 group members list not loading/can't ping some users

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#7352] opened 2020-03-10 13:23 UTC
When you type @ in the chat the list is not showing all members, so you can't for example ping users that have no username if they do not appear in the list.
Also when you hover over group name the dropdown list will not show all users in the group.

**Comment by RememberTheAir** [comment] 2020-03-10 13:32
Duplicate of #7345 and somehow #7325, probably the issues have the same root

**Closed** 2020-03-10 13:56 UTC
