### ISSUE TITLE
Crash in Ubuntu 14.10

### ISSUE THREAD

**Issue by WHK102** [telegramdesktop/tdesktop#808] opened 2015-06-08 19:18 UTC
Open app and start session but in ~5 minutes crash and lost session:

me@machine:~/Downloads/Telegram$ ./Telegram
libs init..
loading appindicator3 with version 1..
loaded appindicator3 with version 1!
loading gtk-3 with version 0..
loaded gtk-3 with version 0!
loaded gtk funcs!
loaded appindicator funcs!
status icon api loaded
loading unity with version 9..
loaded unity with version 9!
unity count api loaded
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

(process:13018): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
QThread: Destroyed while thread is still running

**Comment by bil-elmoussaoui** [comment] 2015-08-15 22:09
@auchri duplicate of #786

**Closed** 2015-08-15 22:23 UTC
