### ISSUE TITLE
[Feature Request] Allow edit planed (delayed) messages.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [telegramdesktop/tdesktop#7918] opened 2020-05-20 14:13 UTC
### Is your feature request related to a problem?
Now, on desktop version this is not possible to edit planned (delayed) massages,

### Describe the solution you'd like
Allow edit planed (delayed) messages.

**Comment by RememberTheAir** [comment] 2020-05-20 14:19
Duplicate of #6496

**Closed** 2020-05-20 14:26 UTC
