### ISSUE TITLE
Telegram tray icon is white

### ISSUE THREAD

**Issue by maharvey** [telegramdesktop/tdesktop#7566] opened 2020-04-03 00:53 UTC
### Steps to reproduce
1. Launch Telegram
2. Enable the tray icon
3. Observe the tray icon color, if you can find it

### Expected behaviour
The icon should be Telegram logo (blue)

### Actual behaviour
The icon is white,which is virtually invisible on a standard light gray taskbar

### Configuration
Linux

**Version of Telegram Desktop:** 1.19.21

**Used theme**: Don't know what you mean? XFCE using default Adwaita icon theme I guess. Other apps change their icons with them, Telegram always

<details>
The white tray icon is nearly invisible. I am constantly unable to locate it and think that Telegram is not running, and try to re-launch it. When I figured out the the blank spot on the taskbar was Telegram I wondered if it was unstable and unable to display the icon correctly... the appearance is that if a white "hole" where the icon should be, as if it is unable to render or perhaps grayed out.

Did you change the icon recently? If so please change it back to the normal blue icon (which matches the app and the launcher), or provide an option to select what tray icon to use.
</details>

**Comment by Aokromes** [comment] 2020-04-03 01:13
update to 2.0.1 stable from github -> releases or desktop.telegram.org

**Comment by MasterGroosha** [comment] 2020-04-03 12:14
![изображение](https://user-images.githubusercontent.com/2780044/78359308-85116580-75bd-11ea-8116-91eaf6bb8f45.png)
Don't know if it's a bug, but yes, the icon is white and it looks really good on dark theme, while it's barely visible on light theme
![изображение](https://user-images.githubusercontent.com/2780044/78359423-bd18a880-75bd-11ea-928f-cfe13187e92b.png)

On these screenshots, KDE's Breeze and Breeze Dark themes are used.

**Comment by xvitaly** [comment] 2020-04-03 21:37
Duplicate of #7399.

**Closed** 2020-04-03 21:52 UTC
