### ISSUE TITLE
Telegram force draw attention on mose move on "typeing..." event after switching to other program

### ISSUE THREAD

**Issue by nerozero** [telegramdesktop/tdesktop#16759] opened 2021-08-05 06:03 UTC
### Steps to reproduce
1. chat with someone in telegram
2. switch to other window (not telegram, eg, browser, text editor, etc.... )
3. happens randomly, telegram focus itself and switch to window drag mode. In telegram window I can see that the person i recently talking with is "typing..."

### Expected behaviour
Do not draw attention to telegram window.

### Actual behaviour
Sometimes telegram taking a focus from active application if I just switched to other window and the person who I talking to is start typing.  If I move mouse without even clicking, telegram switching to focus to itself and force window drag (entire telegram window moving with mouse)
Option: "Notification->Draw attention to the window" is off.

### Configuration
**Operating system:** Linux Mint 20.2 Uma  (similar behavior on other versions/computers on mint with cinnamon)

**Version of Telegram Desktop: 2.9**

**Installation source (Linux Only):** the official website
**Used theme**: Dark

**Comment by Aokromes** [comment] 2021-08-05 08:08
disable focus assist.

**Comment by nerozero** [comment] 2021-08-05 10:43
@Aokromes, Didn't found this option in telegram, could u please give me a clue where I should find it ?

**Comment by Aokromes** [comment] 2021-08-05 11:18
I use windows, so i cannot help you on this.

**Comment by nerozero** [comment] 2021-08-05 11:31
@Aokromes,so could you please why did you close the  bug if you don't even know how to fix this issue applying to Linux which doesn't even has this option?

**Comment by Aokromes** [comment] 2021-08-05 13:10
> @Aokromes,so could you please why did you close the bug if you don't even know how to fix this issue applying to Linux which doesn't even has this option?

i closed the issue because this "bug" was reported before and closed because it's not a bug, i simply don't remember where it's.

**Comment by nerozero** [comment] 2021-08-05 13:14
> p.s. the exact name for setting is "Draw attention to the window"

If you read carefully the text I wrote while filing a but, you can find this line: 
  > Option: "Notification->Draw attention to the window" is off.

So it is not the case.

**Comment by Aokromes** [comment] 2021-08-05 13:20
then maybe your issue is https://github.com/telegramdesktop/tdesktop/issues/10495#issuecomment-809826531

**Comment by nerozero** [comment] 2021-08-05 13:30
Yes, looks like this is exactly it, but it is not resolved. Have fresh installed mint 20.2 (Uma) (which is based on Ubuntu 20.04) and have this issue still present.

**Comment by john-preston** [comment] 2021-08-13 16:40
@nerozero We can keep it open, but I have no idea how and what can cause this. The only thing that sometimes was focusing the window on Linux was QApplication::alert, but it is controlled by the mentioned option.

**Comment by nerozero** [comment] 2021-08-13 16:42
this issue literally started right after "Draw attention" option appeared in notification menu. I remembered all users in my office had "WTF" effect after updating...

**Comment by ilya-fedin** [comment] 2021-08-14 16:57
> The only thing that sometimes was focusing the window on Linux was QApplication::alert, but it is controlled by the mentioned option.

The issue sounds like #10348

> and switch to window drag mode

**Comment by ilya-fedin** [comment] 2021-08-25 05:17
@Aokromes this issue is clearly a duplicate of #10348

**Closed** 2021-08-25 06:52 UTC
