### ISSUE TITLE
Sound lowers Sample Rate in Linux

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#16515] opened 2021-06-28 00:24 UTC
### Steps to reproduce
0. install a USB complaint Sound card, like Focusrite Clarett USB or Scarlett mk2
1. make sure pavucontrol or similar has selected USB interface as Output device.
1. Play a YouTube Music Video in FireFox, sounds OK. Sample Rate Converter in USB driver work Ok.
2. Open Telegram, 
3. open a channel with lots of videos recorded at 44.1Khz or less, videos play automatically..

### Expected behaviour
Nothing.

### Actual behaviour
Sample Rate of the entire Operating System Changes.
the song in FireFox sounds slower from 48Khz to 44.1Khz = -8.125%.
Driver Sample Rate Converter Slows YouTube, instead of Up-scaling Telegram 44.1Khz to 48Khz.

can also be done with a standard Broadcast SMPTE Sine Tone A440 video,

### Configuration
**Operating system:**
Kubuntu 20.10 Groovy Gorilla

**Version of Telegram Desktop:**
Latest.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Discover
or PPA

**Used theme**:
Dark

**Comment by ilya-fedin** [comment] 2021-06-28 00:48
1. This is a duplicate of #1548
2. This is a pulseaudio bug, not a tdesktop bug

**Closed** 2021-06-28 06:44 UTC
