### ISSUE TITLE
The app consumes an unexpectedly large amount of RAM

### ISSUE THREAD

**Issue by TheLightTwist** [telegramdesktop/tdesktop#16084] opened 2021-04-03 11:37 UTC
### Steps to reproduce
1) Apparently, leaving the application running in the background for quite a long time

### Actual behavior
I don't know exactly how much the app should consume normally. I left my computer running overnight with the app just running in the background. In the morning I opened the task manager and saw that the app was currently consuming about 720 MB of RAM. Only Plasma was consuming more than that.
After restarting, the app was consuming about 150 megabytes from the start, after about an hour and as of this writing, the app is consuming 340 MB of memory, a figure that is slowly growing.
The behavior looks like a memory leak.

### Configuration
OS: Arch Linux, 5.11.11-arch1-1
TG ver.: 2.7.1
Source: installed from community repository of my distribution.
Theme: Color, with enabled Night Mode.

I'm sorry, I don't know if a log is needed here or how to get one.

**Comment by ilya-fedin** [comment] 2021-04-03 12:43
please check with the latest version

**Comment by TheLightTwist** [comment] 2021-04-03 16:01
Updated the application, at the moment (the moment of launch) it consumes 180 MB

**Comment by TheLightTwist** [comment] 2021-04-04 22:21
> please check with the latest version (2.7.1)

So, on the new version the behavior is exactly the same (in the beginning it was 180 MB, now after five hours it's about 470).
True, for certain reasons I changed the distribution, now I have the original Arch Linux, but essentially the package is the same

**Comment by TheLightTwist** [comment] 2021-04-07 08:55
So, the application ran for about two days, I did not end the session, only put the computer to sleep. However, I also used the application, not just kept it in the background, but at this point the memory consumption has increased to 850 MB

**Comment by TheLightTwist** [comment] 2021-04-08 10:11
Eventually the consumption increased to 1.1 GB, after which I restarted the application.
Updated the description according to the current information

**Comment by marshevms** [comment] 2021-04-09 07:22
This is an old sore of telegram that they can't solve in any way. Perhaps this is a problem with a third-party library. Perhaps it will always be. Although it was not so pronounced on windows, it may be platform specific.

**Comment by marshevms** [comment] 2021-04-09 07:25
https://github.com/telegramdesktop/tdesktop/issues/10516

**Comment by ilya-fedin** [comment] 2021-04-09 07:27
> Perhaps this is a problem with a third-party library.

It is a problem with the code that loads/unloads media from memory. Probably it doesn't always unload the media when the chat is closed. Since tdesktop uses smart pointers, valgrind reports are useless. The only thing that is helpful is debugging with memory profiler. @john-preston usually can't reproduce these memory leaks, so he can't fix them.

> Although it was not so pronounced on windows, it may be platform specific.

The only thing that stops Windows version for eating a lot of RAM is the fact it's 32-bit. It just crashes with OOM when memory consuming is about 1GB.

**Comment by marshevms** [comment] 2021-04-09 07:54
Why can't he reproduce it? Does he use windows?

**Comment by ilya-fedin** [comment] 2021-04-09 07:59
> Why he can't reproduce it?

I don't know. It just doesn't reproduce on his machine and that's it.

> Does he use windows?

Yeah. AFAIK he can't debug that on Linux since there's no memory profiler that profiles memory in live mode.

**Comment by marshevms** [comment] 2021-04-09 08:00
Strange smart pointers. Is it a shared?

**Comment by ilya-fedin** [comment] 2021-04-09 08:01
> Is it a shared?

I don't know, I know only Linux platform code. Ask @john-preston.

**Comment by john-preston** [comment] 2021-04-09 18:10
@marshevms They just don't really leak memory, it is all cleared on application close. Just some memory is not cleared while moving through chats and I don't really know which, all single cases I did find I fixed. But messages and media metadata are always kept in memory, I don't know if they can lead to some significant amounts of RAM used (without the media content).

**Comment by nb1dev** [comment] 2021-04-13 10:30
I have the same issue.
Up to 4.5GB after 1 day running
Same configuration (Arch Linux, Telegram-Desktop 2.7.1)

**Comment by ilya-fedin** [comment] 2021-04-19 01:00
Will the issue disappear if you try to run tdesktop without tray icon?

**Comment by fcore117** [comment] 2021-04-20 10:13
I always switch that media auto download off for lot of reasons and my usage currently is 34mb on W10 x64 and on Ubuntu it is usually between 25-50mb usage. Wish i could disable link previews too.

**Comment by skorpi-and-friends** [comment] 2021-04-20 12:00
Facing similar issues on Linux (Manjaro (which is also, curiously, a derivative of Arch Linux)). It balloons to 500 megs after a few hours, especially if I'm spending time in media heavy chats. Shit, once, I saw it using like 2 gigs.

![image](https://user-images.githubusercontent.com/61868957/115392188-f0d66880-a1e8-11eb-9705-8d40a96f17d6.png)
I was able to get it to 600 megs in just about 15 minutes for demonstration.

I use Telegram with similar patterns on Windows and I've never faces such issues. In fact, if I'm not mistaken, this behavior only showed up like a month or two ago. 

Maybe an option disable it from keeping media in memory would be nice if this behavior is intended.

**Comment by NotStatilko** [comment] 2021-04-28 03:00
> I always switch that media auto download off for lot of reasons and my usage currently is 34mb on W10 x64 and on Ubuntu it is usually between 25-50mb usage. Wish i could disable link previews too.

Wow. Do you watching videos / play music? If you do then write, please, more about your linux system. Is it 64bit or 32bit, and from what source do you downloaded Telegram? I disabled auto download too, and this doesn't help (#10516).

**Comment by phoe** [comment] 2021-05-01 12:44
I also suffer from this.

### Steps to reproduce
1. Keep Telegram running for several days.
2. Observe it taking almost 1.9 GB of RAM.

![Zrzut ekranu z 2021-05-01 14-11-46](https://user-images.githubusercontent.com/15045546/116782040-2d2a8400-aa87-11eb-8349-e7adc9cccec9.png)

### Configuration
Debian sid, Telegram 2.7.4, installed from the official website, dark theme.

**Comment by ilya-fedin** [comment] 2021-05-01 12:55
Such messages won't help, we need a way to determine source for the leak, but there doesn't seem to be one.

**Comment by phoe** [comment] 2021-05-01 15:36
> but there doesn't seem to be one.

Seriously?

A simple run of `valgrind --leak-check=full /opt/phoe/Telegram/Telegram` lasting for about two or three minutes seems to capture multiple memory leak points. Here's the summary:

```
==1454416== LEAK SUMMARY:
==1454416==    definitely lost: 10,548 bytes in 74 blocks
==1454416==    indirectly lost: 8,721,543 bytes in 265 blocks
==1454416==      possibly lost: 1,146,728 bytes in 28 blocks
==1454416==    still reachable: 1,897,890 bytes in 22,648 blocks
==1454416==                       of which reachable via heuristic:
==1454416==                         stdstring          : 164 bytes in 3 blocks
==1454416==                         length64           : 6,544 bytes in 127 blocks
==1454416==                         newarray           : 2,128 bytes in 53 blocks
==1454416==                         multipleinheritance: 64 bytes in 1 blocks
==1454416==         suppressed: 0 bytes in 0 blocks
==1454416== Reachable blocks (those to which a pointer was found) are not shown.
==1454416== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1454416== 
==1454416== Use --track-origins=yes to see where uninitialised values come from
==1454416== For lists of detected and suppressed errors, rerun with: -s
==1454416== ERROR SUMMARY: 361693 errors from 214 contexts (suppressed: 0 from 0)
```

Indirect losses after startup and a minute of gentle usage are 8M - I can see this bubbling up over time.

**Comment by ilya-fedin** [comment] 2021-05-01 15:38
@phoe please read the thread
https://github.com/telegramdesktop/tdesktop/issues/16084#issuecomment-816476234

**Comment by ilya-fedin** [comment] 2021-05-13 12:31
Looks like there's something wrong with glibc malloc :roll_eyes: 
When I scroll https://t.me/tdesktop_crash, I get ~1.2 GB RAM and it doesn't free when I close the channel. When @john-preston tries to do the same on Windows, RAM is freed. If i load jemalloc, I have ~940 MB at channel start, it slowly frees RAM after closing the channel, now the process has ~490 MB allocated accordign to htop.

**Comment by c0re100** [comment] 2021-05-13 14:34
@ilya-fedin 
seems same as gif auto play🤔
https://github.com/telegramdesktop/tdesktop/issues/7287#issuecomment-606990532

**Comment by ilya-fedin** [comment] 2021-05-14 10:14
Heh, tried alpine's build on tdesktop, it doesn't seem to leak at all. As soon as I close the tdesktop_crash channel, memory deallocates back to ~200 MB RAM. Alpine has tdesktop 2.4.11, so I tried to check 2.4.11 official binary, but it leaks :roll_eyes: 
I thought it could be musl, but void musl's tdesktop build leaks as well. Weird results.

**Comment by ilya-fedin** [comment] 2021-05-14 11:36
Setting `MALLOC_MMAP_THRESHOLD_` environment variable to `128` seem to fix the issue for me

**Comment by marshevms** [comment] 2021-05-14 12:20
> Setting `MALLOC_MMAP_THRESHOLD_` environment variable to `128` seem to fix the issue for me

cool, it's finally clean up.

**Comment by NotStatilko** [comment] 2021-05-15 10:50
> Setting `MALLOC_MMAP_THRESHOLD_` environment variable to `128` seem to fix the issue for me

Wow, **Respect +**

@john-preston This fixes issue with "memory-leak" on Linux.

**Comment by ilya-fedin** [comment] 2021-05-15 10:52
I don't think it's a real fix, that feels like a hack that can do something really bad at any moment

**Comment by NotStatilko** [comment] 2021-05-15 10:53
> I don't think it's a real fix, that feels like a hack that can do something really bad at any moment

Btw how did you figured that this fixes bug?

**Comment by ilya-fedin** [comment] 2021-05-15 11:03
> Btw how did you figured that this bypasses bug?

It was not me, but @mymedia2.

But I found a way more interesting thing: tdesktop doesn't leak on alpine. I found their allocator as separated library: https://github.com/richfelker/mallocng-draft. Built it, loaded via LD_PRELOAD and... tdesktop doesn't leak, at all.

**Comment by ilya-fedin** [comment] 2021-05-15 11:04
I'l try to ask preston to build official builds with that mallocng.

**Closed** 2021-05-17 07:35 UTC
