### ISSUE TITLE
MP4 File Converted to Gif

### ISSUE THREAD

**Issue by leonoctem** [telegramdesktop/tdesktop#23934] opened 2022-01-20 02:05 UTC
### Steps to reproduce

1. Drag and drop MP4 file into Saved Messages on desktop
2. Open Saved Messages on telegram on android mobile and the video has been converted to a GIF with no way to save it as a video, but is still an MP4 on desktop

### Expected behaviour

file should stay as MP4 on mobile

### Actual behaviour

MP4 is converted to GIF when going from desktop to mobile

### Operating system

Windows 10 & Android

### Version of Telegram Desktop

3.4.3 (desktop) & 8.4.3 (android)

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment] 2022-01-20 10:31
This is kind of a duplicate of #2053, which has been closed. Anyway, if the mp4 file is h264 encoded, has no sound, and is smaller than 10mb, and uploading it results in a Telegram GIF, then it's not a bug - it's the intended behavior (more info in the linked issue). I'm not a big fan of this either, but it is supposed to work like that

**Closed** 2022-01-22 19:19 UTC
Labels: bug, api issue
