### ISSUE TITLE
Autostart and workdir parameter do not function in conjunction

### ISSUE THREAD

**Issue by sirati97** [telegramdesktop/tdesktop#4140] opened 2017-12-10 03:22 UTC
### Steps to reproduce
1.  login into telegram desktop
2.  activate autostart
3.  close telegram
4. delete autostart shortcut from startup
5. move tdata to another folder
6. start telegram with 
(case 1) -autostart -workdir ".\{relative path to parent of tdata}\" 
(case 2)  -workdir ".\{relative path to parent of tdata}\" -autostart

### Expected behaviour
Case 1 & 2 telegram starts respecting autostart settings like minimized start

### Actual behaviour
Case 1:
Telegram creates a new folder called tdata in its root and then closes itself
Case 2:
Telegram creates a new folder called tdata in its root and then shows login mask

### Configuration
**Operating system:**
Win10 FCU

**Version of Telegram Desktop:**
Alpha 1.1.29 alpha

**Used theme**:
not applicable

**Comment by john-preston** [comment] 2017-12-10 05:48
@sirati97 I can't reproduce. Here is what I do:

1. Create folder "C:\TestWorkdir"
2. Place the 1.1.29 alpha version Telegram.exe into it.
3. Launch it from there.
4. Log in.
5. In Settings check both "Launch Telegram when system starts" and "Launch minimized".
6. Quit the app fully (Ctrl+Q, for example).
7. Create new folder "C:\TestWorkdir\testdir".
8. Move "tdata" from "C:\TestWorkdir" to "C:\TestWorkdir\testdir".
9. Delete shortcut "Telegram.lnk" from "C:\Users\[user]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup".
10. Open command prompt.
11. Go to "C:\TestWorkdir" in the command prompt.
12. Launch there command:

Telegram.exe -autostart -workdir ".\testdir"

For me it works — the app is started logged in and minimized in tray (the tray icon is hidden under an arrow in tray, but it is there). If I close it and launch:

Telegram.exe -workdir ".\testdir" -autostart

It still works the same.

**Comment by sirati97** [comment] 2017-12-10 23:44
after further inspection (now with 1.26 alpha) I can confirm the launching from PowerShell works.
However launching via shortcut or cmd does not work on my machine

What i executed
![image](https://user-images.githubusercontent.com/14129557/33810955-f47ff156-de03-11e7-8137-5b4d5976b27a.png)

**Comment by tdesktop-closer** [comment] 2019-04-03 23:44
Hey there!

We're automatically closing this issue since there was no activity in this issue since 478 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

<sub>(Please note that this is an [automated](https://github.com/auchri/github_auto_closer) comment.)</sub>

**Closed by tdesktop-closer** 2019-04-03 23:44 UTC
