### ISSUE TITLE
Telegram Desktop crashes frequently

### ISSUE THREAD

**Issue by Gliscor** [telegramdesktop/tdesktop#7555] opened 2020-04-01 21:40 UTC
### Steps to reproduce
1. Open Telegram Desktop
2. Try to use it normally for a while
3. wait 'till it crashes randomly, even if left idle or minimized

### Expected behaviour
Telegram desktop doesn't crash

### Actual behaviour
Telegram desktop crashes at random moments

### Configuration
**Operating system:**
Windows 7 Home Premium 64 bits.
**Version of Telegram Desktop:**
2.0.1 (beta on)
**Used theme**:
Night (default)
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)

[log.txt](https://github.com/telegramdesktop/tdesktop/files/4417807/log.txt)

</details>
Report sent:

![image](https://user-images.githubusercontent.com/11700855/78189157-887ee280-743f-11ea-8ba4-e40dbd6c3afd.png)

**Comment by john-preston** [comment] 2020-04-02 12:41
@Gliscor This crash is somewhere inside text processing :( Right now I'm not sure how to fix that and I can't reproduce it myself.

Maybe if you contact me at t.me/preston I could send you a debug build of the app that will write some additional logs (which string it is parsing right now) and ask you for logs and crash dump from this debug build — there is a chance that I'll learn something from that.

**Comment by calexil** [comment] 2020-04-10 18:14
I am facing this issue as well, but on the linux client, check your dm's

**Comment by nlstart** [comment] 2020-10-02 08:55
I experience this on Win10 when waiting long enough, then at a certain point Telegram is minimized in the Windows task bar, and doesn't maximimze. Not even after closing the Telegram app and restarting the app.  An reboot is necessary to fix this behavior.

**Comment by srezasm** [comment] 2020-11-01 11:09
Yes, recently it crashes frequently at random moments.
telegram v2.4.5 with [an people-made theme](https://t.me/addtheme/MountainSolitude)
windows 10 v2004

**Comment by aquatix** [comment] 2020-12-06 13:08
Any news on this? I encounter this on multiple machines, multiple times per day. It does not matter if I use a custom theme, or a default theme, or whether I use UI scaling or not.

On my Linux machines I get:

Assertion Failed! Unexpected: Values in addNextCluster() text_block.cpp:166

This is the binary downloaded from desktop.telegram.org

**Comment by Aokromes** [comment] 2020-12-06 13:32
https://github.com/telegramdesktop/tdesktop/issues/7555#issuecomment-607821807

**Comment by ilya-fedin** [comment] 2020-12-29 09:47
Is this valid with 2.5.1?

**Comment by Aokromes** [comment] 2021-04-22 17:05
no answer after 4 months, closing. if this issue is still valid, plz open a new ticket using updated telegram desktop.

**Closed by Aokromes** 2021-04-22 17:05 UTC
Labels: bug
