### ISSUE TITLE
Window error in window (1.9.19 beta)

### ISSUE THREAD

**Issue by winqooq** [telegramdesktop/tdesktop#7294] opened 2020-02-26 23:11 UTC
### Steps to reproduce
1. Open video in chat
2. Click on the window-in-window icon
video starts playing in a separate window
3. Place this window on top of the Telegram Desktop window.
4. Open photo in a chat
5. Close photo
6. Open photo in the chat
7. Close photo

### Expected behaviour
Video window does not hide under the Telegram Desktop window

### Actual behaviour
The photo closes, the video window hides under the window Telegram Desktop

### Configuration
Windows 7 x64 Ultimate (Assembly 7601)
Telegram Desktop 1.9.19 beta
Built in. Classic

**Comment by jeffythedragonslayer** [comment] 2020-03-17 04:34
I can't reproduce this on 1.19.20 (windows 10).  Does it have something to do with opening and closing the video twice or does it still go underneath by opening/closing the photo once?

**Comment by winqooq** [comment] 2020-03-19 23:09
As it turned out this is not related to the telegram desktop, if I open the video via firefox then activate the "picture in picture", and through the telegram desktop open the photo then firefox loses the edge on holding the top layer...
Apparently these are problems in windows 7 itself

**Closed** 2020-03-19 23:12 UTC
Labels: waiting for answer
