### ISSUE TITLE
telegram-desktop Linux client can not display name correctly when the name has some special characters.

### ISSUE THREAD

**Issue by chongxu1980** [telegramdesktop/tdesktop#8778] opened 2020-10-07 14:13 UTC
### Steps to reproduce
1. Download the Linux 64 bit telegram client from "https://desktop.telegram.org/" .
2. Login and take a look at someone(such as @chongxu), who's name(not username) has some special characters(such as "𝓪").
3. The special characters will be display as rectangles.
![2020-10-07 21-50-48屏幕截图](https://user-images.githubusercontent.com/67814304/95340115-5b782480-08e7-11eb-8e56-0cbbd413fc52.png

### Expected behaviour
My username should be display as this "冲虚𝓪".

### Actual behaviour
M username has been display as below:
![2020-10-07 21-50-48屏幕截图](https://user-images.githubusercontent.com/67814304/95340404-b447bd00-08e7-11eb-8ac6-abd44bb5b26e.png)

### Configuration
**Operating system:**
Ubuntu 20.04.1 desktop (with Gnome desktop, language is "Chinese Simplified")
**Version of Telegram Desktop:**
Telegram Desktop 2.4.2 Linux 64 bit
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
the official website
**Used theme**:
Ubuntu 20.04.1 desktop default theme (The system language is "Chinese Simplified")
<details><summary><b>Logs</b>:</summary>
Telegram-Message: 22:00:36.433: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
</details>

**Comment by chongxu1980** [comment] 2020-10-07 14:26
When the special characters(such as "𝓪") are in messages, it can be display correctly.

**Comment by ilya-fedin** [comment] 2020-10-07 14:32
Looks like you just don't have a font that contain that symbol in your system
![image](https://user-images.githubusercontent.com/17829319/95345050-de7a8a00-08a9-11eb-9204-fcb5a5db9137.png)

**Comment by chongxu1980** [comment] 2020-10-07 14:40
> Looks like you just don't have a font that contain that symbol in your system
> ![image](https://user-images.githubusercontent.com/17829319/95345050-de7a8a00-08a9-11eb-9204-fcb5a5db9137.png)

But why the "𝓪" character can be display correctly in the messages?
![2020-10-07 22-38-37屏幕截图](https://user-images.githubusercontent.com/67814304/95345982-eb20d180-08ed-11eb-8260-e8a3a56e8eee.png)

**Comment by ilya-fedin** [comment] 2020-10-07 14:42
Duplicate of #6056 then

**Closed** 2020-10-07 14:59 UTC

**Comment by chongxu1980** [comment] 2020-10-07 15:07
> Duplicate of #6056 then

Thank you for your reply.
