### ISSUE TITLE
Incomplete HIEC support on desktop version of Telegram. The files have sent without the previews.

### ISSUE THREAD

**Issue by smasharov** [telegramdesktop/tdesktop#23886] opened 2022-01-12 07:11 UTC
### Steps to reproduce

Send HEIC file as file from the Desktop version of Telegram

### Expected behaviour

The files were sent should have previews like with jpeg files. But they don't.

### Actual behaviour

The HEIC files are send without the preview despite of HEIC support in the OS. The same files have sent from iOS client have the previews even on desktop version of Telegram. So the issue is with the desktop version.

### Operating system

Windows Server 2019

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2022-01-12 09:54
Duplicate of #5522

**Closed** 2022-01-12 10:33 UTC
Labels: bug

**Comment by smasharov** [comment] 2022-01-12 12:18
it is not a duplicate, just related to the old and unsolved for more than 3 years issue
