### ISSUE TITLE
Telegram crashes

### ISSUE THREAD

**Issue by lekoOwO** [telegramdesktop/tdesktop#7771] opened 2020-05-01 22:41 UTC
### Steps to reproduce
1. Open the app
2. The app should close automatically in seconds. If not, click some buttons.

### Expected behaviour
Should not crash

### Actual behaviour
Crashes

### Configuration
**Operating system:**
Windows 10 2004

**Version of Telegram Desktop:**
It crashes since 1.9, now 2.1 still not fixed

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs (Seems nothing special...)</b>:</summary>
<pre>
[2020.05.02 06:32:27] Launched version: 2001001, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.05.02 06:32:27] Executable dir: D:/Apps/Telegram/, name: Telegram.exe
[2020.05.02 06:32:27] Initial working dir: D:/Apps/Telegram/
[2020.05.02 06:32:27] Working dir: D:/Apps/Telegram/
[2020.05.02 06:32:27] Command line: D:\Apps\Telegram\Telegram.exe
[2020.05.02 06:32:27] Executable path before check: D:/Apps/Telegram/Telegram.exe
[2020.05.02 06:32:27] Logs started
[2020.05.02 06:32:27] Connecting local socket to Global\3b632deaf7425daaf13bce01c9238316-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.05.02 06:32:27] This is the only instance of Telegram, starting server and app...
[2020.05.02 06:32:27] Moved logging from 'D:/Apps/Telegram/log_start0.txt' to 'D:/Apps/Telegram/log.txt'!
[2020.05.02 06:32:27] Opened 'D:/Apps/Telegram/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 472
[2020.05.02 06:32:38] Update Info: MTP is unavailable.
[2020.05.02 06:32:40] App Error: _basePath is empty in writeSettings()
[2020.05.02 06:32:40] Primary screen DPI: 96
[2020.05.02 06:32:40] App Info: reading settings...
[2020.05.02 06:32:40] App Info: reading encrypted settings...
[2020.05.02 06:32:40] Lang Info: Loaded cached, keys: 2663
[2020.05.02 06:32:40] OpenAL Logging Level: (not set)
[2020.05.02 06:32:40] Audio Playback Devices: OpenAL Soft on 單 (Realtek(R) Audio);OpenAL Soft on  (Realtek(R) Audio);OpenAL Soft on  (VB-Audio Cable A);OpenAL Soft on 訾唾 (S/PDIF) (Realtek(R) Audio);OpenAL Soft on  (VB-Audio Cable B);OpenAL Soft on  (Boom Audio)
[2020.05.02 06:32:40] Audio Playback Default Device: OpenAL Soft on 單 (Realtek(R) Audio)
[2020.05.02 06:32:40] Audio Capture Devices: OpenAL Soft on 暻亙憸冽(USB PnP Audio Device(EEPROM));OpenAL Soft on CABLE-B Output (VB-Audio Cable B);OpenAL Soft on CABLE-B Output (VB-Audio Cable A)
[2020.05.02 06:32:40] Audio Capture Default Device: OpenAL Soft on 暻亙憸冽(USB PnP Audio Device(EEPROM))
[2020.05.02 06:32:40] App Info: reading map...
[2020.05.02 06:32:40] App Info: reading encrypted map...
[2020.05.02 06:32:40] App Info: reading encrypted user settings...
[2020.05.02 06:32:40] App Info: encrypted user settings read.
[2020.05.02 06:32:40] App Info: reading encrypted mtp data...
[2020.05.02 06:32:40] MTP Info: read keys, current: 4, to destroy: 0
[2020.05.02 06:32:40] Map read time: 15
[2020.05.02 06:32:40] Export Info: Destroy top bar by controller removal.
[2020.05.02 06:32:40] Window Shadow: 1, 1, 1, 1, 1, 2, 3, 6, 9, 13, 18, 23, 28, 33
</pre>
</details>

BTW, there are empty .dmp files in tdata/dumps

**Comment by Aokromes** [comment] 2020-05-02 00:07
i sugest you to contact preston on telegram to ask him a debug build.

**Comment by onroundit** [comment] 2020-05-03 18:52
it makes me so mad :(((

**Comment by onroundit** [comment] 2020-05-03 18:53
is there a temporary solution to the problem?

**Comment by onroundit** [comment] 2020-05-03 18:54
Re-installation doesn't help, I guess this problem came with the last update?

**Comment by Aokromes** [comment] 2020-06-04 10:08
this issue is still valid?

**Comment by onroundit** [comment] 2020-06-04 10:33
> this issue is still valid?

everything seems to be working as it should.

**Comment by rexx0520** [comment] 2020-06-04 10:52
> this issue is still valid?

yes it's still valid

still can't find the reason why it crashes

**Comment by Aokromes** [comment] 2020-06-04 10:54
well, like i told you contact preston on telegram to get a debug build.

**Comment by rexx0520** [comment] 2020-06-04 20:07
> well, like i told you contact preston on telegram to get a debug build.

well, i get it and still get no log...
It just crashes magically w/o any clue :(

**Comment by rexx0520** [comment] 2020-07-30 06:08
A guy just told me that they just encountered this issue.
The common point is that we both have a lot (100GiB+ for me) of fonts installed in system.

launching with `-freetype` flag solves the issue.

**Comment by ilya-fedin** [comment] 2020-07-30 06:58
> The common point is that we both have a lot (100GiB+ for me) of fonts installed in system.

Will 64-bit crash? There are an unofficial 64-bit builds.
https://github.com/TDesktop-x64/tdesktop/releases

**Comment by rexx0520** [comment] 2020-07-31 21:27
> > The common point is that we both have a lot (100GiB+ for me) of fonts installed in system.
> 
> Will 64-bit build crash? There are unofficial 64-bit builds.
> https://github.com/TDesktop-x64/tdesktop/releases

hmmm
It has not been crashing. Seems working well!

**Comment by ilya-fedin** [comment] 2020-08-01 06:40
> It has not been crashing.

How much RAM it consumes on start?

**Comment by rexx0520** [comment] 2020-08-01 14:13
> > It has not been crashing.
> 
> How much RAM it consumes on start?

About 300 MB.
32-bit version official version with `-freetype` flag only comsumes about 90MB.

**Comment by ilya-fedin** [comment] 2020-08-01 14:15
> About 300 MB.

Without `-freetype`?
That's strange, if you getting an OOM crash on the official version, it should be around 1GB or more

**Comment by rexx0520** [comment] 2020-08-01 15:07
> > About 300 MB.
> 
> Without `-freetype`?
> That's strange, if you're getting an OOM crash on the official version, it should be around 1GB or more

Yes, without `-freetype`

**Comment by ilya-fedin** [comment] 2020-08-12 17:27
> Yes, without `-freetype`

:thinking: maybe there are some surge on start when Qt loads fonts and after that the memory is released, but it is enough to get a crash on 32-bit version?

**Comment by ilya-fedin** [comment] 2020-09-20 18:52
@lekoOwO can you archive and post your C:\Windows\Fonts folder?

**Comment by lekoOwO** [comment] 2020-09-20 18:53
> @lekoOwO can you archive and post your C:\Windows\Fonts folder?

I'm not sure... It's about hundreds GiBs...

**Comment by ilya-fedin** [comment] 2020-09-20 18:54
> I'm not sure... It's about hundreds GiBs...

This is the only way I can reproduce the issue I guess

**Comment by lekoOwO** [comment] 2020-09-20 19:04
> > I'm not sure... It's about hundreds GiBs...
> 
> This is the only way I can reproduce the issue I guess

Well... I'll try doing it

**Comment by ilya-fedin** [comment] 2020-11-24 03:52
Qt was updated in 2.4.8, is this valid with it?

**Comment by lekoOwO** [comment] 2020-11-24 15:09
> Qt was updated in 2.4.8, is this valid with it?

dunno, it looks good now.
I'll let it run for a little longer and see if it crashes.

**Comment by lekoOwO** [comment] 2020-11-25 01:31
It seems stable now!

**Comment by ilya-fedin** [comment] 2020-11-25 01:38
Glad to hear. You can close the issue then.

**Closed** 2020-11-25 01:39 UTC
Labels: bug, waiting for answer
