### ISSUE TITLE
[Feature Request]  Scroll to top

### ISSUE THREAD

**Issue by devcline** [telegramdesktop/tdesktop#7462] opened 2020-03-27 23:04 UTC
This feature will be usefull to scroll on top if you want to read whole chat from the beginning

**Comment by RememberTheAir** [comment] 2020-03-27 23:35
Kind of duplicate of #4699

**Comment by mymedia2** [comment] 2020-03-28 05:13
Open a calendar for the chat and click the "Beginning" button. To get the calendar, click to any date label in chat history.

**Comment by devcline** [comment] 2020-03-28 06:09
@mymedia2 exuse me, but where is calendar?

**Comment by mymedia2** [comment] 2020-03-28 08:02
![simplescreenrecorder-2020-03-28_10 59 51](https://user-images.githubusercontent.com/9163157/77818453-73265300-70e3-11ea-9888-c2e1ca3de901.gif)

**Comment by devcline** [comment] 2020-03-28 18:30
@mymedia2  thanks , how to do this on phone? when i click a date, nothing happens.

**Comment by Aokromes** [comment] 2020-03-28 18:46
your request is android? if yes, it doesn't belongs here.

**Comment by RememberTheAir** [comment] 2020-03-28 19:23
@devcline it's not possible to go to the first message from android. A workaround is to select a very very old date, at least previous to the chat creation, the app will bring you to the oldest message (the first one). Or alternatively, you can just use Telegram X for Android, it has this feature

**Comment by devcline** [comment] 2020-03-28 20:54
@RememberTheAir @Aokromes for IOS
I dont know how but near the text input i saw a small calendar icon, i dont remember how to bring it .
thanks! 

**Well still** one small button in the chat corner or in the top menu would be great to scroll to the top.

**Closed** 2020-03-28 21:12 UTC

**Comment by Aokromes** [comment] 2020-03-28 21:14
https://github.com/TelegramMessenger/Telegram-iOS
