### ISSUE TITLE
Sorry, you can only pin 5 chats to the Top.

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24250] opened 2022-03-25 01:11 UTC
### Is your feature request related to a problem?

yes.

### Describe the solution you'd like

allow more pins.

### Describe alternatives you've considered

nothing.

### Additional context

my phone allows to see 7.5 chats on the screen.
the desktop allows 16x chats with FullHD screen.

6 or 7 pins would be better..
Yandex.Translate.Bot
Yandex.Mail.360
Note to Self
Receipts "Monthy Bills, Gas, Electricity, Taxes, etc..."
3 more for friends and strangers on internet.

**Comment by RememberTheAir** [comment] 2022-03-25 07:38
This can't be implemented by tdesktop without the API/other apps being updated too. Please upvote https://bugs.telegram.org/c/64

btw duplicate of #3026 and many many other

**Closed** 2022-03-25 09:35 UTC
Labels: enhancement
