### ISSUE TITLE
Message count is not readable from the windows tray 

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#3576] opened 2017-06-24 17:30 UTC
### Steps to reproduce
1. Have more than 100 unread messages
2. Go to Windows tray and look at Telegram's icon

### Expected behaviour
I will see the number of unread messages I have. Or some indication of an estimation if it's hard to show it on such a small area. Also, it can be added to the hover text.

### Actual behaviour
I see `..2` instead of `162`

### Configuration
**Operating system:** Windows 10 version 1703 (Build 16226.1000)

**Version of Telegram Desktop:** v1.1.7 alpha

![image](https://user-images.githubusercontent.com/3811594/27510546-abf87c86-591b-11e7-90fa-01b6d15d6841.png)

**Comment by mrexodia** [comment] 2017-09-12 09:12
isn't this a duplicate of https://github.com/telegramdesktop/tdesktop/issues/2937 ?

**Comment by auchri** [comment] 2017-09-12 09:13
@mrexodia Yes, thank you.

**Closed by auchri** 2017-09-12 09:13 UTC

**Comment by arieljannai** [comment] 2017-09-12 09:17
Correct!
Sorry about that, probably searched with keywords that didn't matched 😅

**Comment by mrexodia** [comment] 2017-09-12 09:31
@auchri quick question, what is the name of this internally?

![](https://image.prntscr.com/image/XKjP2sV9RKaVx_J43ovqtg.png)

I'm looking to change some behaviour (add an additional checkbox/change behaviour of notification checkbox to not update this count on osx when notifications are disabled) and send a pull request but my search terms don't find any issues (message count, icon).
