### ISSUE TITLE
Weird crashes when loading the chats

### ISSUE THREAD

**Issue by alsoGAMER** [telegramdesktop/tdesktop#7342] opened 2020-03-07 14:08 UTC
### Steps to reproduce
1. Set a local passcode
2. Lock telegram
3. Then unlock it

### Actual behavior
When I go to unlock the app, this will crash for no reasons, literally yesterday worked fine, i haven't changed/updated anything in the meantime

### Configuration
**Operating system:** Manjaro 19.0.2

**Version of Telegram Desktop:** Beta 1.9.19

**Used theme**: Pitch Dark

<details><summary><b>Logs</b>:</summary>
ApiId: 2040
Binary: Telegram
Launched: 07.03.2020 14:56:55
Platform: Linux64bit
UserTag: a4a3072aaca99670
Version: 1009019 beta

Caught signal 11 (SIGSEGV) in thread 139811104501248

Backtrace:
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x17d9e38]
/usr/lib/libpthread.so.0(+0x14800)[0x7f284f9db800]
[0x1]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x10960bc]
[0x1]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x10960bc]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x1096c54]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN8Platform12Spellchecker10ThirdParty15UpdateLanguagesESt6vectorIiSaIiEE+0x160)[0x1096e50]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN8Platform12Spellchecker15UpdateLanguagesESt6vectorIiSaIiEE+0x1b)[0x109a0db]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN12Spellchecker5StartEN3gsl8not_nullIPN4Main7SessionEEE+0x9d7)[0x1889f47]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Main7SessionC1EN3gsl8not_nullIPNS_7AccountEEERKN2tl5boxedI7MTPuserEEONS_8SettingsE+0xc1e)[0x14a74de]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Main7Account13createSessionERKN2tl5boxedI7MTPuserEE10QByteArrayiONS_8SettingsE+0x62)[0x14a7722]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Main7Account8startMtpEv+0xfcb)[0x14ad0ab]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core11Application14unlockPasscodeEv+0x95)[0x183dd75]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN6Window18PasscodeLockWidget6submitEv+0xec)[0x11bac8c]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2acc90a]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN2Ui16MaskedInputField13keyPressEventEP9QKeyEvent+0xf8)[0xd5d808]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x22228c7]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x22eaada]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN2Ui15RpWidgetMethods11handleEventEP6QEvent+0x4f6)[0xd32616]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x21f45c1]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x21fcbe5]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core7Sandbox6notifyEP7QObjectP6QEvent+0x12e)[0x17cf42e]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2aa0320]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x223d780]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x21f45c1]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x21fc5e0]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core7Sandbox6notifyEP7QObjectP6QEvent+0x12e)[0x17cf42e]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2aa0810]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2520743]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2524fbd]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x24feecc]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x1f5337a]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x27e)[0x7f284fa5351e]
/usr/lib/libglib-2.0.so.0(+0x6c2d1)[0x7f284fa552d1]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x31)[0x7f284fa55311]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2af5777]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2a9edbf]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2aa85b6]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core7Sandbox5startEv+0x6b8)[0x180bd68]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core8Launcher18executeApplicationEv+0x61)[0x180d911]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core8Launcher4execEv+0x72)[0x180da22]

Google Breakpad caught a crash, minidump written in thread 139811104501248
Minidump: /home/ag/.local/share/TelegramDesktop/tdata/dumps/f35bb594-f495-417f-7a09cc8a-167cd540.dmp

Backtrace:
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0xbccbcf]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x1798023]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN15google_breakpad16ExceptionHandler12GenerateDumpEPNS0_12CrashContextE+0x396)[0x2d71906]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN15google_breakpad16ExceptionHandler13SignalHandlerEiP9siginfo_tPv+0xa8)[0x2d71c48]
/usr/lib/libpthread.so.0(+0x14800)[0x7f284f9db800]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x10960bc]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x1096c54]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN8Platform12Spellchecker10ThirdParty15UpdateLanguagesESt6vectorIiSaIiEE+0x160)[0x1096e50]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN8Platform12Spellchecker15UpdateLanguagesESt6vectorIiSaIiEE+0x1b)[0x109a0db]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN12Spellchecker5StartEN3gsl8not_nullIPN4Main7SessionEEE+0x9d7)[0x1889f47]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Main7SessionC1EN3gsl8not_nullIPNS_7AccountEEERKN2tl5boxedI7MTPuserEEONS_8SettingsE+0xc1e)[0x14a74de]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Main7Account13createSessionERKN2tl5boxedI7MTPuserEE10QByteArrayiONS_8SettingsE+0x62)[0x14a7722]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Main7Account8startMtpEv+0xfcb)[0x14ad0ab]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core11Application14unlockPasscodeEv+0x95)[0x183dd75]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN6Window18PasscodeLockWidget6submitEv+0xec)[0x11bac8c]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2acc90a]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN2Ui16MaskedInputField13keyPressEventEP9QKeyEvent+0xf8)[0xd5d808]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x22228c7]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x22eaada]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN2Ui15RpWidgetMethods11handleEventEP6QEvent+0x4f6)[0xd32616]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x21f45c1]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x21fcbe5]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core7Sandbox6notifyEP7QObjectP6QEvent+0x12e)[0x17cf42e]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2aa0320]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x223d780]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x21f45c1]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x21fc5e0]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core7Sandbox6notifyEP7QObjectP6QEvent+0x12e)[0x17cf42e]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2aa0810]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2520743]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2524fbd]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x24feecc]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x1f5337a]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x27e)[0x7f284fa5351e]
/usr/lib/libglib-2.0.so.0(+0x6c2d1)[0x7f284fa552d1]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x31)[0x7f284fa55311]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2af5777]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2a9edbf]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0x2aa85b6]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core7Sandbox5startEv+0x6b8)[0x180bd68]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core8Launcher18executeApplicationEv+0x61)[0x180d911]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(_ZN4Core8Launcher4execEv+0x72)[0x180da22]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram(main+0x25)[0xb6aed5]
/usr/lib/libc.so.6(__libc_start_main+0xf3)[0x7f284f6c8023]
/home/ag/.local/bin/tmulti/.TDeskMulti/bin/Telegram/Telegram[0xb6d96c]
</details>

**Comment by alsoGAMER** [comment] 2020-03-07 14:10
When started with the terminal, this is the output:
<details>
Gtk-Message: 15:09:31.090: Failed to load module "appmenu-gtk-module"
error: : cannot open
error: : cannot open
error: : cannot open
zsh: segmentation fault (core dumped)  /home/ag/.local/bin/Telegram/Telegram
</details>

**Comment by alsoGAMER** [comment] 2020-03-07 19:44
I have some updates: I've deleted all the files and folder into $HOMEDIR/.local/share/TelegramDesktop and all the files into the downloads folder, and now is working.
Any clue?

**Comment by jeffythedragonslayer** [comment] 2020-03-16 22:28
Can you import the core dump into gdb and get a backtrace?  This might be a duplicate of #7330 if the crash happened in ZN8Platform12Spellchecker10ThirdParty15UpdateLanguagesESt6vectorIiSaIiEE

**Comment by Aokromes** [comment] 2020-04-21 13:48
can you try updating to 2.0.1?

**Comment by alsoGAMER** [comment] 2020-04-25 01:59
> can you try updating to 2.0.1?

The problem seems to have already been resolved since version 1.9.22

**Closed** 2020-04-25 02:00 UTC
Labels: needs user action
