### ISSUE TITLE
After updating to the latest version, the application began to close unexpectedly

### ISSUE THREAD

**Issue by TarasovSavely** [telegramdesktop/tdesktop#26216] opened 2023-04-24 18:11 UTC
### Steps to reproduce

1) Start Telegram Desktop
2) Wait - it will close itself

### Expected behaviour

Normal operation of the application

### Actual behaviour

It will close itself

### Operating system

Linux Ubuntu 22.04.2 LTS Gnome 42.5 (Wayland)

### Version of Telegram Desktop

4.8

### Installation source

Snap

### Logs

```shell
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.qpa.wayland.input: Unexpected GestureStarted while already active
Ошибка сегментирования (образ памяти сброшен на диск)
```

**Comment by ilya-fedin** [comment] 2023-04-24 18:14
No, #26205 is not a segfault. It's a display connection break.

**Comment by ilya-fedin** [comment] 2023-04-24 18:19
Given that it mentions GestureStarted, it seems to be similar to #25993, but it's not exactly that as #25993 has gesture update without gesture start while this one has gesture update twice. But who knows, maybe #25993 actually happened here after another compositor bug the warning says about.

@TarasovSavely to proceed, we need you first migrate to the binary build from https://desktop.telegram.org. Then you should go to Settings -> Advanced and enable "Install beta versions". After that, reproduce the bug and on nexrt tdesktop launch you will see crash reporter asking you to send a crash report. First copy crash ID to clipboard (to send it to this issue late) and click "SEND CRASH REPORT" button. After that, send the crash ID to this issue.

**Comment by TarasovSavely** [comment] 2023-04-25 19:43
I know how to reproduce the bug!!! Here are the actions that lead to a 100% crash of the application (even what is installed from the official site):
1) Open the app
2) Go to settings -> battery life and animations. A window will open in front of you in which you can configure the ability to turn off animations when the battery is low.
3) Put your laptop in power saving mode
4) The application will immediately crash

Please note: This does not work without step 2
Version: 4.8.1

**Comment by ilya-fedin** [comment] 2023-04-25 19:45
@TarasovSavely I test in a VM, so I'm afraid I can't do step 3. Sorry, but we need you to switch to static binary and send us a crash report. That's a requirement.

**Comment by TarasovSavely** [comment] 2023-04-25 19:53
Sent a report. Crash ID: 67689a3f-c6c6-40cf-7603ed8d-0e6f87a1

**Comment by ilya-fedin** [comment] 2023-04-29 09:43
Fixed in lib_base master

**Closed** 2023-04-29 09:43 UTC
Labels: bug

**Comment by TarasovSavely** [comment] 2023-04-29 09:58
I'm sorry, but what do you mean?

**Comment by ilya-fedin** [comment] 2023-04-29 10:23
The bug was in lib_base library, the fix was committed to its master branch
