### ISSUE TITLE
Resizing crashes Telegram when AquaSnap and/or TidyTabs is installed

### ISSUE THREAD

**Issue by Qwerty-Space** [telegramdesktop/tdesktop#4074] opened 2017-11-18 17:54 UTC
### Steps to reproduce
1. Hover over the border of the window until the resize cursor appears
2. Click
3. Crashes

### Expected behaviour
Telegram should resize

### Actual behaviour
Telegram freezes, and crashes

### Configuration
**Operating system:**
Windows 10 Pro 64 bit

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
Custom

**Comment by Qwerty-Space** [comment] 2017-11-18 17:59
Video of the bug:
https://a.doko.moe/lnutbd.mp4

**Comment by gdude2002** [comment] 2018-05-28 18:16
Surprisingly, this is still a problem, and still hasn't been addressed.

**Comment by gdude2002** [comment] 2018-05-28 19:39
@john-preston It does not offer to send a crash report I'm afraid.

**Comment by john-preston** [comment] 2018-05-28 19:42
@gdude2002 Does it show a "Telegram Desktop was not closed properly" window on restart?

I'm afraid I won't be able to fix this, if those software products (TidyTabs / AquaSnap) crash this app in such a hard way that it even can't generate a crash report =(

**Comment by gdude2002** [comment] 2018-05-28 19:43
It doesn't - the entire app just freezes up, and I have to kill it myself using the task manager or Windows' crashed process detection thing.

It seems odd that this would affect specifically Telegram, though - I have tons and tons of stuff that works great with both AquaSnap and TidyTabs.

**Comment by john-preston** [comment] 2018-05-28 19:45
@gdude2002 Freezing is not crashing. If it freezes this is another issue. Perhaps there is some sort of deadlock when one of those apps try to resize the window in some way that it tries to avoid ¯\_(ツ)_/¯ I'm not sure.

**Comment by gdude2002** [comment] 2018-05-28 19:46
Very tricky.

How should I go about debugging this?

**Comment by john-preston** [comment] 2018-05-28 19:50
@gdude2002 When you experience the freeze you can open task explorer, right click the frozen Telegram.exe and press Create dump file.

I guess the dump will be huge, but I don't know what else you can do. I guess it will contain some sensitive data too. Then you can archive it (I hope the size will be reduced greatly) and send it me at https://t.me/preston, at least I'll be able to see the stack trace at the freeze moment.

**Comment by gdude2002** [comment] 2018-05-28 19:54
Interestingly, during the time it took to grab the dump file, it unfroze and resized.

I do have the dump file, but it's over 200MiB and my upload speed in this building is 0.5Mbit/s. I'm a developer myself though; is there anything I can locate in it for you?

**Comment by gdude2002** [comment] 2018-05-28 19:56
As an addendum, I don't get this issue with just AquaSnap. The issue lies squarely with TidyTabs.

**Comment by john-preston** [comment] 2018-05-28 19:58
@gdude2002 To watch into it you need the debug symbols for that build, so unfortunately I need it on my workstation to see the backtraces.

The fact that it does unfreeze after that makes finding something useful in the dump even less likely, because it clearly isn't a deadlock then.

If you compress (rar, zip) this dump, how much is it?

**Comment by gdude2002** [comment] 2018-05-28 20:00
7-zip gives me a much more manageable 55MiB file.

I'll see if I can figure out a way to upload this for you without taking the rest of the network down.

**Comment by john-preston** [comment] 2018-05-28 20:11
@gdude2002 I'm not sure it'll help anything to be honest. Perhaps I need to reproduce your config and try to see what slows it down (if it unfreezes then its just some huge lag), but currently I don't have time for this =(

**Comment by gdude2002** [comment] 2018-05-28 21:01
It probably won't surprise you to hear that it's still uploading. :P 

I guess there just aren't too many of us using this combination of apps. But I can live without TidyTabs for now.

**Comment by Qwerty-Space** [comment] 2018-05-28 23:40
[Here is my dump file](https://a.doko.moe/xypmfe.DMP)

**Comment by Qwerty-Space** [comment] 2018-05-29 22:36
@gdude2002 I just never move Telegram lol. 

I do find that AutoHotkey can move it without it crashing.

**Comment by gdude2002** [comment] 2018-05-30 09:29
@Qwerty-Space Yeah, I can actually move mine, but resizing breaks it. But yeah, I also have mine in a single spot :P

**Comment by Qwerty-Space** [comment] 2018-05-30 19:08
I can move mine too.  Sorry, I meant that AHK can resize it without it crashing.

**Comment by bigjay517** [comment] 2019-01-28 14:31
I am facing this issue as well.  A workaround which seems to be working for me is to exclude Telegram from TinyTabs.

**Comment by jacobslewis** [comment] 2019-02-10 16:36
I've been having the exact same issue! I run both TidyTabs and Aquasnap, and was wondering why Telegram seems so darned buggy.

Per @bigjay517 , I added Telegram to my TidyTabs exclusion list, and the problem seems to be solved.

**Comment by Aokromes** [comment] 2020-01-25 14:09
this bug is still valid?

**Comment by Qwerty-Space** [comment] 2020-01-25 19:05
Definitely still valid.
I can create yet another dump file if you want?

**Comment by HarryGoatleaf** [comment] 2020-05-20 12:32
this bug still exists :(

**Comment by dylanroscover** [comment] 2020-08-24 20:42
This still exists. Can confirm on two of our machines.

**Comment by Agha-Shadi** [comment] 2020-08-28 21:15
first report was on 2017 and it's 2020 now, but the same problem still exists!!

**Comment by shayaknyc** [comment] 2020-10-12 17:53
Came here to confirm that resizing the telegram window either results in a really long freeze most of the time, regardless of any other desktop management software. I have Windows 10 Pro (64-bit) - even on a brand new clean install with nothing else on it, if you click and resize, the whole thing hangs. Sometimes it correctly resizes and resumes, but most times, it will just hang forever "not responding in taskman" and only killing it and reloading it solves the issue. truly bizarre bug.

**Comment by AbelLykens** [comment] 2021-05-13 07:06
Years later this still happens... I don't dare to resize my screen because it WILL crash my Telegram.

**Comment by gdude2002** [comment] 2021-05-13 11:54
Since the stale bot has closed this, you should probably open a new issue - just remember to point out that this one was closed pre-emptively.

I really hate these stale bots honestly, projects add them with the assumption that the only reason an issue would go stale is that the reporter doesn't follow up - but more often than not it's the project's fault that it goes stale.

**Comment by Aokromes** [comment] 2021-05-13 12:01
> Since the stale bot has closed this, you should probably open a new issue - just remember to point out that this one was closed pre-emptively.
> 
> I really hate these stale bots honestly, projects add them with the assumption that the only reason an issue would go stale is that the reporter doesn't follow up - but more often than not it's the project's fault that it goes stale.

slate bot helps to find already fixed issues still opened, sometimes lack of answer of OP makes ticket to be closed incorrectly, and even less times closed even with answer.

**Comment by AbelLykens** [comment] 2021-06-13 09:39
This is still a problem. Very annoying, too ;)

**Comment by AbelLykens** [comment] 2021-12-10 15:37
This is still a problem. Very annoying, too ;)

**Comment by shayaknyc** [comment] 2021-12-14 17:35
This issue is also not specific to AquaSnap and/or TidyTabs. One of the display libraries gets borked during an in-app upgrade. If I download and reinstall over the existing installation, I do not experience this problem, but if the Windows program updates by clicking on the bottom "Update Telegram" banner button, it 100% of the time will hang/freeze when resizing.

**Comment by AbelLykens** [comment] 2022-06-13 06:12
This is (annoyingly) still happening.

**Comment by Aokromes** [comment] 2022-06-13 08:22
interesting, i use windows 11 + fancyzones and it works fine there.

**Comment by AbelLykens** [comment] 2022-09-15 12:48
This now appears fixed for me

**Closed** 2022-09-30 00:36 UTC
Labels: bug, waiting for answer, windows
