### ISSUE TITLE
telegram closes itself after random time

### ISSUE THREAD

**Issue by pantar85** [telegramdesktop/tdesktop#1114] opened 2015-09-21 19:34 UTC
linux issue.

tested on amd laptop & intel desktop

tested with ubuntu14.04 & ubuntu15.04 & arch

open telegram.
everything is fine.
don't use it or have it focused for X minutes = closes when i click on it.

**Comment by pantar85** [comment] 2015-09-24 10:53
adding further information.
the app will never crash if i select the title bar first, its only if i were to click on the actual ui of the app itself.

**Comment by marek287** [comment] 2015-09-25 07:01
+1 same problem with arch and same specs

**Comment by IncubusRK** [comment] 2015-10-14 13:44
+1 same problem on windows

this is help me

diff --git a/Telegram/SourceFiles/mainwidget.cpp b/Telegram/SourceFiles/mainwidget.cpp
index ee8d9b1..fa095db 100644
--- a/Telegram/SourceFiles/mainwidget.cpp
+++ b/Telegram/SourceFiles/mainwidget.cpp
@@ -4291,7 +4291,7 @@ void MainWidget::feedUpdate(const MTPUpdate &update) {
 			history.update();
 		}
 		if (History *h = App::historyLoaded(id)) {
-			if (h->lastMsg->out() && h->lastMsg->id <= d.vmax_id.v) {
+			if (h->lastMsg && h->lastMsg->out() && h->lastMsg->id <= d.vmax_id.v) {
 				dlgUpdated(h, h->lastMsg->id);
 			}
 		}

**Comment by telegramdesktop** [comment] 2015-10-14 13:56
@IncubusRK Looks like possible crash place, thanks! I'll look into that and if it is a real crash place, I'll include that fix in today release.

**Comment by telegramdesktop** [comment] 2015-10-14 21:09
@IncubusRK I've added such patch to the 0.9.5 stable version

@pantar85 @marek287 if this is not fixed in 0.9.5 version, please run Telegram Desktop from terminal using command "catchsegv ./Telegram" in the directory where Telegram Desktop binary is held.

When it crashes can you please save the output in the console (it should have the backtrace) to a text file and send it to me (here or at https://telegram.me/preston), thanks.

**Comment by marek287** [comment] 2015-12-31 20:36
I think this issue can be closed. I haven't noticed this issue any more.

**Comment by auchri** [comment] 2015-12-31 20:38
@marek287 thx for the report!

**Closed** 2015-12-31 20:37 UTC
Labels: bug, linux

**Comment by marek287** [comment] 2016-01-19 08:26
I have connected second monitor to laptop (lead closed). If I disconnect second monitor and reconnect it and open telegram from system tray - it crashes.
At home I didn't use second monitor so I didn't notices this issue long time (holiday).
[log.txt](https://github.com/telegramdesktop/tdesktop/files/95534/log.txt)

**Comment by ElessarWebb** [comment] 2016-02-26 16:53
@marek287 I've noticed this too. It indeed happens on second monitor connect/remove. Even if already open, it will simply close.

**Comment by marek287** [comment] 2016-05-11 09:18
@ElessarWebb Now the issue is gone. I am using Telegram 0.9.48 alpha.

**Comment by grobza** [comment] 2017-08-15 22:20
Issue is still (or 'again') in place, Telegram closes on it's own.
Debian 9, Telegram 1.1.19. 
Does not happen on Windows 7.
