### ISSUE TITLE
Some text editing shortcuts not working

### ISSUE THREAD

**Issue by jesset** [telegramdesktop/tdesktop#729] opened 2015-05-18 10:25 UTC
When composing a new message, some system editing shortcuts wan't working, but works elsewhere in almost whole system (OS X), such as ctrl+k/h for deleting characters.

I am just wandering was it designed to be, or a bug (to be fixed) ?

Telegram Desktop version 0.8.13 , OS X

Thanks.

**Comment by radaiming** [comment] 2016-03-23 03:40
Looks some OS X shortcuts like ctrl + f/b works in previous versions, after upgrading to 0.9.32 they are not working anymore.

**Comment by stek29** [comment] 2016-03-23 14:34
I have 0.9.34 dev, and they work for me.
Btw what OS X version are you using? Are you using TDesktop from AppStore or from tdesktop.com?

**Comment by radaiming** [comment] 2016-03-24 07:55
My OS X version is 10.11.4, I tried both from AppStore and tdesktop.com, neither of them work.

**Comment by stek29** [comment] 2016-03-24 11:43
Ok looks like 0.9.32 is really broken, shortcuts don't work for me too.
but they are ok on 0.9.34...

**Comment by john-preston** [comment] 2016-03-24 12:55
@stek29 As I can see in git I've changed nothing related to the shortcuts from 0.9.32 to 0.9.34 %) What exactly are you talking about?

**Comment by john-preston** [comment] 2016-03-24 14:02
The original issue is about some key shortcuts that do not work in Qt apps in general, I suppose. So I can't do anything about it.

@radaiming what the shortcut should do? I define my own shortcut Cmd+F for search inside the current conversation, but no Ctrl+F/B are defined. In what version did they work?

**Comment by radaiming** [comment] 2016-03-24 15:47
Those shortcuts are like Emacs keybindings, please check the "Document shortcuts" part [here](https://support.apple.com/en-us/HT201236). These shortcuts are available in many Mac Apps when editing text, like Chrome, Firefox, but not available on some others, like Wireshark, but I'm not sure what extra work have to do to support them :(

**Comment by stek29** [comment] 2016-03-25 13:00
@john-preston I can't see any changes too, but they work. I don't know how and why, but they worked on 0.9.34 and didn't on 0.9.32, but maybe it's because 0.9.34 is self-built, i don't know 0_0

**Comment by john-preston** [comment] 2016-03-25 13:05
@stek29 Can you try 0.9.34 dev version from the bottom of https://desktop.telegram.org page? Will it work?

**Comment by stek29** [comment] 2016-03-25 15:58
@john-preston No, it won't.

**Comment by radaiming** [comment] 2016-03-26 04:31
By the way, it works on another telegram client: https://itunes.apple.com/cn/app/telegram/id747648890?l=en&mt=12

**Comment by john-preston** [comment] 2016-03-26 06:40
@radaiming if they are native OS X shortcuts they should work in the other client app, because it is native (uses OS X text input controls), while tdesktop is not (uses Qt custom text input controls). It seems that I need to handle all of those myself somehow. Are you sure they've worked before? Can you name a version where they worked maybe?

**Comment by radaiming** [comment] 2016-03-26 08:17
I downloaded https://updates.tdesktop.com/tmac/tsetup.0.9.28.dmg and it's working, 0.9.31 does not work. I'm not able to find download link of 0.9.29 dev and 0.9.30 dev, so could not try it.

**Comment by john-preston** [comment] 2016-03-26 08:20
@radaiming what about updates.tdesktop.com/tmac/tsetup.0.9.29.dev.dmg ? seems that my shortcuts handling broke it :(

**Comment by radaiming** [comment] 2016-03-26 08:28
0.9.29 dev works, 0.9.30 dev doesn't work.

**Comment by tkimnguyen** [comment] 2016-05-24 15:27
Not working for me on 0.9.49 on OS X 10.11.5

**Comment by kjvic** [comment] 2016-05-28 22:21
Emacs-style shortcuts are **not** working for me on OS X 10.11.5, Telegram Desktop v0.9.49, which has the same icon as the version available here: https://desktop.telegram.org/#changelog
![flat paper airplane icon](https://cloud.githubusercontent.com/assets/10302065/15630262/d7126ff8-2500-11e6-86f6-f570be993882.png)

Emacs-style shortcuts **are** working for me on same OS, with Telegram Version 2.13.46728, which has the same icon as the version available from the Apple App Store https://itunes.apple.com/us/app/messenger-for-telegram/id747648890 
![3d paper airplane icon](https://cloud.githubusercontent.com/assets/10302065/15630259/c4120878-2500-11e6-93a7-cbaddc369cac.png)

**Comment by radaiming** [comment] 2016-09-24 06:14
This issue is not fixed in latest version, I'm still using 0.9.29 dev :(

**Comment by longkai** [comment] 2017-01-14 10:30
+1

Now it's 1.0.0 but still not fixed.

**Comment by Aokromes** [comment] 2017-01-16 08:36
#1060 ?

**Comment by pragmader** [comment] 2017-02-08 09:04
Version 1.0.5, the shortcuts are still not working. I use them everywhere and Telegram is the only app on my machine that does not support it.

**Comment by aifreedom** [comment] 2017-05-31 21:53
I'm on Telegram Desktop v1.1.7 and OS X 10.12.5. None of the Emacs-style shortcuts works in the text editor. 

Can someone maintaining this project give a pointer to where to start to fix this issue? I can try to look into it and send out a PR.

**Comment by tkimnguyen** [comment] 2017-06-01 15:03
I didn't see any change notes related to Mac keyboard shortcuts. Presumably it's in this folder https://github.com/telegramdesktop/tdesktop/tree/81e728ada01713f562b0d7694eec57ed954e1786/Telegram/SourceFiles/platform/mac

**Comment by stek29** [comment] 2017-06-02 05:14
@tkimnguyen Because they were made in Qt, not in TDesktop. And TDesktop has updated Qt version. Have a look at https://bugreports.qt.io/browse/QTBUG-53085

**Comment by tamsky** [comment] 2018-04-11 22:15
I'm going to ask, almost a year later, what @aifreedom asked, and continue to expect no useful response.

I'm on Telegram Desktop v1.2.17 (please ignore that https://desktop.telegram.org/changelog doesn't even list that version -- I digress.)

I too am still experiencing non-furnctional Emacs-style Control key + {a,b,d,e,h,k,n,o,p,t,v,y} movement within text input boxes.

Can someone maintaining this project give a pointer to where to start to fix this issue? I can try to look into it and send out a PR.

**Comment by tamsky** [comment] 2018-04-11 22:34
Possibly relevant upstream bugs:
- https://bugreports.qt.io/browse/QTBUG-393 "Mac OS X: Qt does not provide basic emacs bindings like native Cocoa controls"
- https://bugreports.qt.io/browse/QTBUG-33627 "Regression: GNU Emacs Style Key Sequences doesnt work on MAC"

**Comment by john-preston** [comment] 2018-04-12 00:07
@tamsky The first bug in Qt seems to be describing, why they don't work in Qt applications and so they don't work here.

**Comment by tamsky** [comment] 2018-04-12 17:45
@john-preston says:
> The first bug in Qt seems to be describing, why they don't work in Qt applications and so they don't work here.

Communicating on github, a text-only medium, isn't always easy.
I'm fairly certain you wanted to share your conclusion with all of us... but I have absolutely no clue what you're trying to communicate.  

To clear things up, can you please:
1. cite the bug (by number) that has information
2. restate your conclusion, but omit the indefinite articles.  Your statement doesn't convey much information: 
> "why they don't work in Qt applications and so they don't work here"
3. any specific text you can quote from the QT bug that supports your conclusion

Thanks!

**Comment by john-preston** [comment] 2018-04-12 17:48
@tamsky As far as I understood: QTBUG-393 says that the issue with basic emacs bindings is not resolved in Qt up till version 5.9. Telegram Desktop uses Qt 5.6.2, so it doesn't have the issue with basic emacs key bindings resolved.

The last comment in that bug from 04.07.2017 proposes some possible solutions for that problem in Qt. While it doesn't work in Qt it won't work in Telegram Desktop as well.

**Comment by Aokromes** [comment] 2020-01-25 10:56
this bug is still valid?

**Comment by Aokromes** [comment] 2020-02-24 23:21
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Closed by Aokromes** 2020-02-24 23:21 UTC
Labels: macOS, waiting for answer

**Comment by qorg11** [comment] 2020-07-24 23:52
is anyone working on this

**Comment by RavenKyu** [comment] 2020-08-27 06:36
I'm using macOS Catalina v10.15.6 and Telegram for desktop v3.2.1 
 
in macOS, shortcut "command + a" is used to locate the cusor at the start of line.  but it doesn't work now. anyone like me?
