### ISSUE TITLE
Recent used emojis not saving after restart app

### ISSUE THREAD

**Issue by AliN11** [telegramdesktop/tdesktop#4145] opened 2017-12-10 18:00 UTC
### Actual behaviour
When I use an emoji, It appears in recent used panel. But when I restart the app, recent used emoji panel containing previous emojis (Default emojis)
Note: One way to save them permanently is that click on emoji icon (At bottom-right of the app)

### Expected behaviour
Recent used emojis must not revert to default after restart app.

### Configuration
**Operating system:**
Windows 7 Ultimate
The problem exists on Ubuntu 17 too.
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
Default

**Comment by auchri** [comment] 2017-12-19 10:16
Duplicate of #4018

**Closed by auchri** 2017-12-19 10:16 UTC
