### ISSUE TITLE
Telegram using 9 GB of RAM

### ISSUE THREAD

**Issue by Germano0** [telegramdesktop/tdesktop#8552] opened 2020-09-04 21:17 UTC
My system that has 16 GB of RAM started to swap, so I opened task manager and I have noticed Telegram using 9 GB of RAM.
![telegram](https://user-images.githubusercontent.com/5477747/92285507-c60efc80-ef04-11ea-8ccf-6634e5af7205.jpg)

### Configuration
**Operating system:**
Fedora 32 KDE

**Version of Telegram Desktop:**
2.3.2

**Installation source** - the official website 

**Used theme**:
Classic

**Comment by danielleontiev** [comment] 2020-09-06 16:11
I can confirm memory leaking after the last update
![screen](https://i.imgur.com/HmmenUh.png)

Arch Linux, Telegram Desktop 2.3.2

**Comment by axel-verse** [comment] 2020-09-08 10:53
I can confirm memory leaking each time when Telegram Desktop ready to upgrade - Telegram Desktop using 9.5GB RAM when upgrade is pending.

Manjaro Linux - official package downloaded from website, Ubuntu Linux 18.04, 20.04 - official snap package

**Comment by Zupirio** [comment] 2020-09-11 08:07
I too can confirm that after the last update, telegram has been slowing down my machine.

PopOs! - downloaded from Pop store, Ubuntu 20.04, flatpak

**Comment by marshevms** [comment] 2020-09-28 10:08
Duplicate of #https://github.com/telegramdesktop/tdesktop/issues/7361

**Closed** 2020-10-05 05:31 UTC

**Comment by ilya-fedin** [comment] 2020-11-04 00:55
Are you all using native notifications? Will the leak disappear if you disable native notifications?

**Comment by danielleontiev** [comment] 2020-11-14 22:35
Here is Telegram 2.4.7 without native notifications:
[screen](https://i.imgur.com/bbzx9Od.png)
It seems native notification are not related for the issue

**Comment by ilya-fedin** [comment] 2020-11-15 05:00
@danielleontiev your leak doesn't seem to be of size ~9GB and is not this issue

**Comment by axel-verse** [comment] 2020-11-16 20:23
After upgrade to 2.4 I had no memory leaking anymore

**Comment by Germano0** [comment] 2020-11-16 21:46
I confirm the bug on 2.4.7

**Comment by ilya-fedin** [comment] 2020-11-17 09:27
> I confirm the bug on 2.4.7

Can you answer my question above?

**Comment by Germano0** [comment] 2020-11-17 09:29
> Are you all using native notifications? Will the leak disappear if you disable native notifications?

What are native notifications? I am using notifications from Telegram not from my desktop environment

**Comment by ilya-fedin** [comment] 2020-11-17 09:34
> What are native notifications? I am using notifications from Telegram not from my desktop environment

Ah, ok. Native notifications were rewritten to a different library with a C-style memory management in the version specified in thisissue and I thought they might be the cause. But if you saying that you're using internal notifications, this is definitely a duplciate of #7361
