### ISSUE TITLE
[UI] Add alternative style of talks in Tdesktop (like Telegram Web)

### ISSUE THREAD

**Issue by bedf** [telegramdesktop/tdesktop#1286] opened 2015-11-09 15:54 UTC
I think unlike a smartphone or tablet, bubbles style talks in Tdesktop  is not the best and most comfortable. I think similar to that used in Telegram Web style is best for a desktop application. (Add a different background color for each participant).

In the Channel Telegram "Ideas for Telegram" (http://tchannels.me/c/featurerequests) they added some mockups for Telelgram Web but are validity to the desktop version. 

Thanks
![photo_2015-11-09_12-41-48](https://cloud.githubusercontent.com/assets/5126124/11038296/fbf66860-86e0-11e5-990a-6d0c6923a400.jpg)

**Comment by auchri** [comment] 2015-11-09 17:57
Duplicate of #934, #525 and #321 :)

**Closed by auchri** 2015-11-09 17:57 UTC
