### ISSUE TITLE
When executing prepare.py to compile breakpad, an error is reported,

### ISSUE THREAD

**Issue by StraussLupusson** [telegramdesktop/tdesktop#17344] opened 2021-12-05 07:40 UTC
![image](https://user-images.githubusercontent.com/47448295/144738137-caeb8d22-3040-45b6-be70-1f39668ec79a.png)
When executing prepare.py to compile breakpad, an error is reported, how can I solve this problem?

**Comment by ilya-fedin** [comment] 2021-12-05 23:19
Duplicate of #16939

**Closed** 2021-12-06 06:49 UTC
Labels: question

**Comment by StraussLupusson** [comment] 2021-12-06 15:08
ok，thanks
