### ISSUE TITLE
OSX: unable to add accented characters while holding key

### ISSUE THREAD

**Issue by tasinttttttt** [telegramdesktop/tdesktop#3526] opened 2017-06-14 07:19 UTC
### Steps to reproduce
1. Open a chat window
2. Hold the key ```e``` / ```y``` / ```u``` / ```i``` / ```o``` / ```a``` / ```s``` / ```l``` / ```z``` / ```n```.

### Expected behaviour
Holding the key should open the accented characters tooltip as shown in official apple support https://support.apple.com/en-au/HT201586

### Actual behaviour
The character repeats.

### Configuration
**Operating system:**
OSX 10.11
OSX 10.12

**Version of Telegram Desktop:**
1.1.7

**Used theme**:
?
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment] 2017-06-14 14:22
#729

**Comment by ironicmoka** [comment] 2017-08-05 20:45
Same here. Pretty annoying: I'm forced use another app just for type then copy then past the accented character in a telegram conversation or open up the emoji & symbol OS panel

**Comment by stek29** [comment] 2017-08-06 18:58
Duplicate of #3377 #2830 #2587 #1939

**Closed** 2017-08-08 09:54 UTC
Labels: duplicate
