### ISSUE TITLE
Switching between chats lags.

### ISSUE THREAD

**Issue by FunkSpunk** [telegramdesktop/tdesktop#28576] opened 2024-10-25 09:23 UTC
### Steps to reproduce

Started happening after the latest 5.6.4 Beta (pre-release) update. switching between chats takes a few seconds with freezes in the chat switching animations. verified on 2 different desktops.

![tgdesktop](https://github.com/user-attachments/assets/6a38e9ba-1baf-4a30-a849-3cf556753605)

### Expected behaviour

.......

### Actual behaviour

.......

### Operating system

Windows 11 x64

### Version of Telegram Desktop

5.6.4 Beta

### Installation source

Static binary from official website

**Comment by Aokromes** [comment] 2024-10-25 09:39
can't reproduce

**Comment by originalitay** [comment] 2024-10-25 13:36
I'm getting this as well. Seems to happen regardless of chat. It's currently unusable.

**Comment by techoji** [comment] 2024-10-25 16:23
same here

**Comment by john-preston** [comment] 2024-10-25 16:27
I have an idea, I started checking for available microphone and camera when switching chats, to show the correct "record voice" / "record video" / "send" button without app restart. I guess this could be slow, though I need to check this. I'll add some logs.

**Comment by techoji** [comment] 2024-10-25 17:31
> same here

I changed my settings in Speakers and Camera and sped up chat opening by specifying my camera's exact name in the Input device. Now, opening a chat takes around 300ms instead of 2 seconds.

![image_2024-10-25_20-28-45](https://github.com/user-attachments/assets/e30b57fd-ded5-42bb-9da6-5af530f15040)

**Comment by FunkSpunk** [comment] 2024-10-25 19:46
> > same here
> 
> I changed my settings in Speakers and Camera and sped up chat opening by specifying my camera's exact name in the Input device. Now, opening a chat takes around 300ms instead of 2 seconds.
> 
> ![image_2024-10-25_20-28-45](https://private-user-images.githubusercontent.com/81591798/380266517-e30b57fd-ded5-42bb-9da6-5af530f15040.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4ODUwOTksIm5iZiI6MTcyOTg4NDc5OSwicGF0aCI6Ii84MTU5MTc5OC8zODAyNjY1MTctZTMwYjU3ZmQtZGVkNS00MmJiLTlkYTYtNWFmNTMwZjE1MDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE5MzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZGQ2MmZhMzJhNjZmMTYzNmFmNzhmZWVkNjU5NmI4MzEwZDI1NDViN2IwYTY0MjVkMzE3NmM1MTE1ZTE4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ldd2Yd-tXboRgJ2XUmFXWTGl0rluITYpHtYhLgdmAIY)

both my machines dont have any camera attached to it. so default is the only option there.

**Comment by bekliev** [comment] 2024-10-25 19:58
Downgrading to 5.6.3 helps!
Download link: https://telegram.org/apps

Downside is you have to relogin again - because it logged out in my case

**Comment by arsLan4k1390** [comment] 2024-10-26 15:17
Can confirm lags (switching between accounts and opening/closing any chats) on TDesktop v5.6.4. I don't even have a physical camera (but "Link to windows" emulates a webcam).
Device: MSI Z690 Edge WiFi, Windows 11 Pro 23H2
![image](https://github.com/user-attachments/assets/bfc72887-d3c9-4df1-be8b-ddd8c64faf6b)

**Comment by FunkSpunk** [comment] 2024-10-27 11:12
> Downgrading to 5.6.3 helps!
> 
> Download link: https://desktop.telegram.org/
> 
> Downside is you have to relogin again - because it logged out in my case
> 
> Also: never install beta for critical communications

Downgrading seems to be the only solution for now. I think the problem is only for desktop/laptops which don't have any dedicated Web Camera attached or built into them.

**Comment by Aokromes** [comment] 2024-10-27 11:26
> > Downgrading to 5.6.3 helps!
> > Download link: [desktop.telegram.org](https://desktop.telegram.org/)
> > Downside is you have to relogin again - because it logged out in my case
> > Also: never install beta for critical communications
> 
> Downgrading seems to be the only solution for now. I think the problem is only for desktop/laptops which don't have any dedicated Web Camera attached or built into them.

i don't have camera and i don't have lags.

**Comment by Mattia-Marino** [comment] 2024-10-27 15:37
I got this problem too, but it's present only on my desktop. I have updated Telegram at 5.6.4 beta on my laptop too, but strangely enough no problems there.

**Comment by john-preston** [comment] 2024-10-28 06:23
I hope this will be fixed in the upcoming version, I've moved device availability refreshing to a background thread.

**Comment by hendrops** [comment] 2024-10-29 03:17
i got this problem too. its very slow/lagging every time opening the chat

**Comment by DelmorS** [comment] 2024-10-31 07:53
I also have this problem, can provide any required data. Can replicate this problem in 100% of time on the latest version 5.6.4 beta. I even had to downgrade to 5.6.2 and disable autoupdates - no issues for this version and below.

**Closed** 2024-10-31 15:21 UTC
Labels: bug, waiting for answer, cant reproduce

**Comment by john-preston** [comment] 2024-11-01 06:41
Is it ok in 5.7? @DelmorS @Dustver @hendrops

**Comment by Dustver** [comment] 2024-11-01 09:00
> Is it ok in 5.7? @DelmorS @Dustver @hendrops

I disabled the use of the smartphone camera as a webcam device. After that, the lags disappeared. And I can't say now whether the lags have been removed on version 5.7

**Comment by hendrops** [comment] 2024-11-01 10:18
> Is it ok in 5.7? @DelmorS @Dustver @hendrops

its already fixed on 5.7, i already updated to 5.7 and its ok ! @john-preston

**Comment by DelmorS** [comment] 2024-11-01 13:06
> Is it ok in 5.7? @DelmorS @Dustver @hendrops

Yes, for me it is fixed on 5.7, no lags at all
Thank you!
