### ISSUE TITLE
[Feature Request] Add sticky conversations to the conversation list.

### ISSUE THREAD

**Issue by alvarocasadoc** [telegramdesktop/tdesktop#2488] opened 2016-10-02 12:08 UTC
I was thinking that it would be great if the user could choose some conversations and mark them as "sticky" so they stay at the top of the conversations list, just like in some forums. That would be great so "important chats" are no more lost among all the other conversations.

**Comment by stek29** [comment] 2016-10-06 18:33
Duplicate of #296 and #2425.

**Closed** 2016-10-06 18:47 UTC
