### ISSUE TITLE
[Linux] PiP window disappears when Telegram loses focus

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#8149] opened 2020-06-27 09:20 UTC
### Steps to reproduce
1. Open video and switch to picture-in-picture (PiP) mode
2. Click on your desktop or focus on another application

### Expected behaviour
PiP should stay on screen, probably above all other windows

### Actual behaviour
When main Telegram window loses focus, PiP disappears, but keeps playing and producing sound.
I've recorded this bug: https://youtu.be/bJNtRhpfhDM

### Configuration
**Operating system:** Manjaro 20.0.3 Lysia (KDE Edition), Windows doesn't seem to be affected, but needs further testing.
**Version of Telegram Desktop:** 2.1.13, but it was even in previous versions.
**Installation source (Linux Only)** - GitHub releases (new versions come from autoupdater)

**Comment by ilya-fedin** [comment] 2020-06-27 16:23
Wayland?

**Comment by MasterGroosha** [comment] 2020-06-27 16:44
No, X. If more precise:
DE: KDE 5.70.0 / Plasma 5.18.5
WM: KWin

**Comment by ilya-fedin** [comment] 2020-06-27 16:51
Can't reproduce on anything but KDE. Probably a kwin bug?

**Comment by magnus-gross** [comment] 2020-06-28 07:55
Sounds similar to this https://www.reddit.com/r/kde/comments/4roa7l/windows_disappear_when_interacting_with_the/

Most people there seem to have Nvidia drivers. Do you have Nvidia as well?

**Comment by MasterGroosha** [comment] 2020-06-28 09:45
@magnus-gross Yes, I do have Nvidia on both laptop and stationary PC, however on laptop (running Manjaro as well) I have the same issue even when Nvidia videocard is not being used (at least I guess so).
Also in that person's video (from the link you posted) all windows disappear when click on desktop. In my case, TDesktop's PiP is the only thing affected. All other windows stay visible (like on Windows)

@ilya-fedin maybe, though I don't have this bug with YouTube PiP (in Firefox)

**Comment by ilya-fedin** [comment] 2020-06-28 09:50
> maybe, though I don't have this bug with YouTube PiP (in Firefox)

Firefox is a GTK program, while Telegram is a Qt program. Different toolkits, different behavior.

**Comment by mubashir-rehman** [comment] 2021-03-18 22:44
Using Linux Mint 20.1 with i3 7100U. Same issue.

**Comment by ilya-fedin** [comment] 2021-03-19 09:31
@mubashir-rehman can't confirm. Doesn't disappears when I switching window focus from Telegram to Nemo.

**Comment by MasterGroosha** [comment] 2021-03-20 07:50
Looks like Plasma/KDE-specific issue. I still have this on Manjaro KDE Edition

**Comment by ilya-fedin** [comment] 2021-03-20 07:51
Have you reported to KDE? I don't think this will be fixed on its own.

**Comment by MasterGroosha** [comment] 2021-03-20 08:05
Not yet unfortunately. Last time I decided to do that KDE team was in process of migrating to GitLab, so I couldn't find a proper place to report this.

**Comment by Aokromes** [comment] 2021-03-20 08:07
https://bugs.kde.org/ ?

**Comment by ilya-fedin** [comment] 2021-03-20 08:07
@MasterGroosha as far as I know it's still https://bugs.kde.org/buglist.cgi?component=platform-x11-standalone&product=kwin&resolution=---
The issue is not reproducible on KDE Wayland, so it's only in X11 backend of kwin.

**Comment by ilya-fedin** [comment] 2021-03-25 08:58
@MasterGroosha have you reported to KDE? If not, probably we should close the issue since there's no point to have an issue for a KDE bug.

**Closed** 2021-03-25 09:00 UTC
Labels: 3rd party issue, linux
