### ISSUE TITLE
[Feature Request]  More friendly spellchecker

### ISSUE THREAD

**Issue by devcline** [telegramdesktop/tdesktop#7496] opened 2020-03-30 07:33 UTC
To spellcheck the word i need click once and navigate to the word throu a menu

The best way will be like in google chrome (right click and chose ) or gmail (auto completion with a tab)

**Comment by RememberTheAir** [comment] 2020-03-30 07:39
Kind of duplicate of #7492

**Closed** 2020-03-30 10:21 UTC
