### ISSUE TITLE
[Feature Request] Default Folder

### ISSUE THREAD

**Issue by Qwerty-Space** [telegramdesktop/tdesktop#8344] opened 2020-07-29 16:23 UTC
### Is your feature request related to a problem?
When switching accounts, the "all chats" folder is automatically selected.  This is annoying, and kind of defeats the purpose of folders, and even discourages using them.

### Describe the solution you'd like
Set a default folder to be opened when switching accounts, and starting tdesktop.  Or, remember last used folder.  Or both!

### Describe alternatives you've considered
An alternative is running two separate telegram clients.  At least this way the folder I want open is open.

**Comment by yashpalgoyal1304** [comment] 2020-07-29 16:55
duplicate of https://github.com/telegramdesktop/tdesktop/issues/7533
if u think u have some point which is not covered in that issue already, then report there (:

**Closed** 2020-07-29 17:10 UTC

**Comment by Qwerty-Space** [comment] 2020-07-29 18:05
Ah bugger, missed that one.  Sorry!
