### ISSUE TITLE
Telegram not using system notification on Linux

### ISSUE THREAD

**Issue by portaloffreedom** [telegramdesktop/tdesktop#2380] opened 2016-08-23 18:06 UTC
### Steps to reproduce
1. watch a youtube video
2. receive a notification
3. trying to read the subtitles under the notifications

### Expected behaviour
Use the system notification. The Desktop Environment knows better how to handle the notification.

### Actual behaviour
The notification gets in the way of everything. Playing a game (covering usefull stuff) and watching a video for starters. And it doesn't disappear easily. Very annoying.

### Configuration
**Operating system:**
Any linux distribution

**Version of Telegram Desktop:**
0.9.56

**Comment by auchri** [comment] 2016-08-23 18:12
Duplicate of <use search>

**Comment by portaloffreedom** [comment] 2016-08-23 18:12
example:
![spectacle j11606](https://cloud.githubusercontent.com/assets/1150666/17903980/c450d1a0-696d-11e6-875a-b29a61e530c9.png)

**Closed by auchri** 2016-08-23 18:12 UTC

**Comment by portaloffreedom** [comment] 2016-08-23 18:13
Duplicate of _what_?

**Comment by auchri** [comment] 2016-08-23 18:14
> use search
