### ISSUE TITLE
Context / Right-Click Menu Opens in Wrong Display / dual gfx / amd

### ISSUE THREAD

**Issue by antoniscy** [telegramdesktop/tdesktop#7099] opened 2020-01-28 14:24 UTC
I usually keep my Telegram Desktop window on my secondary monitor (I've got 3). Sometime along the 1.9.x versions the context menu started appearing on the primary display only. 

If i move the app on the primary display, right-click menu works as expected. When it goes back in its normal position on the 2nd monitor then context menu appears on primary display (the x,y coordinates change depending on where the right-click was - just on the wrong monitor!)

**Comment by antoniscy** [comment] 2020-01-28 14:25
Currently on version 1.9.8 on Windows 10

**Comment by Aokromes** [comment] 2020-01-28 15:15
strange, cannot reproduce myself on windows 10 20h1, telegram desktop 1.9.8 and dual monitor system, what's your gfx?

**Comment by antoniscy** [comment] 2020-01-28 15:31
AMD Radeon R7 200, and
Intel HD Graphics 4600

**Comment by Aokromes** [comment] 2020-01-28 15:38
try updating video drivers to see if that changes something....

**Comment by antoniscy** [comment] 2020-01-28 19:58
i did... no change

by the way, desktop client was working fine for more than 2 years...this is a recent bug

**Comment by Aokromes** [comment] 2020-01-28 20:07
dunno, i don't have a 3 monitors or amd gfx to test :/

**Comment by antoniscy** [comment] 2020-01-29 06:32
1.8.15 portable works correctly. 

not sure where to get newer versions of the portable - https://desktop.telegram.org/changelog#old-system-versions only has 1.8.15

**Comment by antoniscy** [comment] 2020-01-29 06:35
i think you are right about it being a qt problem... https://bugreports.qt.io/browse/QTBUG-76162

**Comment by Aokromes** [comment] 2020-01-29 07:15
you can get other portable builds here https://github.com/telegramdesktop/tdesktop/releases

**Comment by antoniscy** [comment] 2020-01-29 08:39
thanks.

1.9.0 shows the problematic behavior so 1.8.15 is the last version working correctly

**Comment by Aokromes** [comment] 2020-01-29 08:53
strange, theorically it was already fixed on 5.12 on jun 2019....

**Comment by antoniscy** [comment] 2020-02-17 07:02
TD just updated to 1.9.13 - problem still exists!

**Comment by antoniscy** [comment] 2020-02-19 07:12
TD just updated to 1.9.14 - problem still exists!

**Comment by Aokromes** [comment] 2020-02-19 08:30
imho you need to report to QT.

**Comment by antoniscy** [comment] 2020-02-19 08:37
well, i am not a developer and i am not familiar with TD source code so i don't know where/how/what level of detail&information would be required for the report to QT

**Comment by Aokromes** [comment] 2020-02-24 22:37
you may try asking on https://wiki.qt.io/Online_Communities to get confirmation or denial of someone there :)

**Comment by antoniscy** [comment] 2020-02-25 13:11
Today updated to 1.9.18beta - issue still there...

**Comment by Aokromes** [comment] 2020-02-25 13:13
ofc, it very likely needs fix QT5 side.

**Comment by lipusal** [comment] 2020-03-15 13:07
I've also been facing the same issue for some months now, I also have 3 monitors and a Radeon RX 580 with updated drivers. In my case, when the main monitor is off the right-click menu works correctly. When I turn it on, the right-click menu goes back to the main monitor regardless of where the Telegram window is.

@antoniscy if you've reported it anywhere on QT5 please post a link so I can help.

**Comment by alextor70** [comment] 2020-03-23 07:50
I have 4 monitors on two adapters: ATI Radeon HD 5700 and Intel HD 4000.
This issue reproduced when my main monitor is one of two on Radeon (and telegram is on any other monitor).
When my main monitor is one of two on Intel HD, then telegram context menu works correctly (telegram can be on any of monitors).

**Comment by nichitapavel** [comment] 2020-04-11 15:52
Same for me, version 2.0.1.

**Comment by Aokromes** [comment] 2020-04-24 12:55
can you try on 2.1?

**Comment by nichitapavel** [comment] 2020-04-24 13:30
> 
> 
> can you try on 2.1?

Checked: still happens.

**Comment by lipusal** [comment] 2020-04-25 13:24
Still happening to me too on 2.1, behavior:
![a](https://user-images.githubusercontent.com/5761629/80281011-832f5380-86de-11ea-8514-9bb29ccdd3ac.gif)

This is on my Windows desktop.  In a similar setup with a Macbook (left monitor connected via USB-C => HDMI adapter + Macbook screen), the context menu works correctly.

**Comment by TheDjEzio** [comment] 2020-06-03 18:37
Same to me
Radeon RX 580 Series
i5-4460
Telegram 2.1.8 beta

**Comment by pmartiamarista** [comment] 2020-06-09 20:59
same...
Windows 10  19041
i5-4460
r9 270x driver 20.5.1
Telegram 2.1.10

**Comment by nichitapavel** [comment] 2020-06-24 08:41
Version 2.1.13 persists.
I recently had an opportunity to switch to combination nvidia + intel gpu's: it worked, the problem must be strictly related to amd gpu's.

**Comment by ekinig** [comment] 2020-08-18 23:47
Same problem on latest build (2.3) on Mac OS.

**Comment by ilya-fedin** [comment] 2020-08-19 00:02
> Same problem on latest build (2.3) on Mac OS.

Are you sure that this is a right issue? All previous affected users are using Windows with AMD graphics (i.e. some bug in interacting between Qt & AMD drivers)

**Comment by ekinig** [comment] 2020-08-19 00:15
> > Same problem on latest build (2.3) on Mac OS.
> 
> Are you sure that this is a right issue? All previous affected users are using Windows with AMD graphics (i.e. some bug in interacting between Qt & AMD drivers)

The description is the same. Using multiple monitors, when the telegram window is not on the primary monitor, the context menu appears in the main desktop.

**Comment by Kigunix** [comment] 2020-10-20 12:52
Same problem. I'm using 2 different GPU's for two monitors. RX 570 + GTX 660, main screen on RX and secondary on GTX. 
![Telegram_2020-10-20_15-50-20](https://user-images.githubusercontent.com/73176296/96588288-25c23b00-12ec-11eb-8f24-446b10daabe2.jpg)

**Comment by ilya-fedin** [comment] 2020-11-13 19:48
Qt was updated in 2.4.8, maybe they fixed this bug finally?

**Comment by ilya-fedin** [comment] 2020-11-22 22:04
Hmm, no response for 10 days, should I assume that the issue is fixed and could be closed?

**Comment by lipusal** [comment] 2020-11-22 23:06
Unfortunately I am away from the offending system for at least a month, won't be able to try until then.  If this issue gets closed and 2.4.8+ does not solve the issue when I can try it, I will open a new issue

**Comment by antoniscy** [comment] 2020-11-23 07:44
Problem is still there on 2.4.11 beta

**Comment by ilya-fedin** [comment] 2020-11-23 07:50
Ok.

**Comment by Fratee** [comment] 2020-12-29 09:49
Same problem here in 2.5.1 . Windows10, 2 screens (primary below, secondary on top). Telegram desktop app on secondary screen, context menu opens on primary.

**Comment by ilya-fedin** [comment] 2020-12-29 10:12
> edit: i bet is due to the coordinate on the screen going negative in reference to the primary screen, my two cents

This happening only on AMD cards, so this is either a bug in AMD drivers or how Qt works with gfx API

**Comment by www10177** [comment] 2021-01-18 07:51
> > edit: i bet is due to the coordinate on the screen going negative in reference to the primary screen, my two cents
> 
> This happening only on AMD cards, so this is either a bug in AMD drivers or how Qt works with gfx API

AMD RX580, TG version 2.5.1 , context menu show in main screen(RX580) only,
primary screen connect with RX580, secondary one go integrated graphics
when I switch primary screen(primary:Integrated, secondary:RX580) , It show on primary one(Intergrated) only.

nothing wrong on my another dual screen NVIDIA PC(TG version not sure, both connect to NVIDIA graphic card)

so maybe it's a bug of AMD?

**Comment by kaserblade99** [comment] 2021-01-18 16:47
I'm running off of a Nvidia GTX 1660Ti and I'm having the same problem. Doesn't seem like it's exclusive to just AMD cards.

**Comment by ilya-fedin** [comment] 2021-01-18 16:51
in your issue you said you have Radeon graphics as well

**Comment by kaserblade99** [comment] 2021-01-18 17:34
I tried disabling the AMD integrated graphics drivers and replicated the scenario. I seem to still have the same issue.

**Comment by ilya-fedin** [comment] 2021-01-18 17:40
> Seems to be an AMD rooted issue like you mentioned

I hope someone report this to them...

**Comment by Ondra1230** [comment] 2021-01-18 20:41
How  much for it? Thx  😊 it is joke, I like  Nvidia,amd too...  sur 18/01/2021 le 10:48, kaserblade99 écrivit:
                
            
            
                
                    De: "kaserblade99" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                
I'm running off of a Nvidia GTX 1660Ti and I'm having the same problem. Doesn't seem like it's exclusive to just AMD cards.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762363727",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762363727",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ondra1230** [comment] 2021-01-18 20:46
radeon? Is maybe Good, I don’t know.. it is long time.. I buying best  sur 18/01/2021 le 10:52, ilya-fedin écrivit:
                
            
            
                
                    De: "ilya-fedin" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                
in your issue you said you have Radeon graphics as well

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762365846",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762365846",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ondra1230** [comment] 2021-01-18 20:55
It is not same for 100€ or 200€ 😅 It is about money sur 18/01/2021 le 11:35, kaserblade99 écrivit:
                
            
            
                
                    De: "kaserblade99" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                
I tried disabling the AMD integrated graphics drivers and replicated the scenario. I seem to still have the same issue.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762387010",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762387010",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ondra1230** [comment] 2021-01-18 20:57
no, WY? sur 18/01/2021 le 11:40, Aokromes écrivit:
                
            
            
                
                    De: "Aokromes" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                
@antoniscy can you edit title of issue and add amd gfx there?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762389030",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762389030",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ondra1230** [comment] 2021-01-18 20:59
GFX is many types  sur 18/01/2021 le 11:40, Aokromes écrivit:
                
            
            
                
                    De: "Aokromes" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                
@antoniscy can you edit title of issue and add amd gfx there?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762389030",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762389030",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ondra1230** [comment] 2021-01-18 21:02
No Nvidia? sur 18/01/2021 le 11:41, ilya-fedin écrivit:
                
            
            
                
                    De: "ilya-fedin" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                

Seems to be an AMD rooted issue like you mentioned

I hope someone report this to them...

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762389644",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762389644",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ondra1230** [comment] 2021-01-18 21:12
No, For Graphic Card NVIDIA... For processor INTEL sur 18/01/2021 le 11:41, ilya-fedin écrivit:
                
            
            
                
                    De: "ilya-fedin" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                

Seems to be an AMD rooted issue like you mentioned

I hope someone report this to them...

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762389644",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762389644",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ilya-fedin** [comment] 2021-01-19 07:48
@Ondra1230 are you a spammer? :see_no_evil:

**Comment by Ondra1230** [comment] 2021-01-19 09:00
? I don't even know what it Fake news?On 1/19/21 at 01:49, ilya-fedin wrote:
                
            
            
                
                    From: "ilya-fedin" <notifications@github.com>Date: January 19, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Ondra1230" <Ondra123@mail.com>,"Mention" <mention@noreply.github.com>Subject: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                

@Ondra1230 are you a spammer? 🙈



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762664730",

"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762664730",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ilya-fedin** [comment] 2021-01-19 09:02
@Ondra1230 exit outside of your mail to this issue on GitHub and look how you spammed this thread with your big posts

**Comment by Ondra1230** [comment] 2021-01-19 09:08
I'm not going there anymore !!!  it completely ruined my cell phoneOn 1/19/21 at 03:03, ilya-fedin wrote:
                
            
            
                
                    From: "ilya-fedin" <notifications@github.com>Date: January 19, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Mention" <mention@noreply.github.com>,"Ondra1230" <Ondra123@mail.com>Subject: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                
@Ondra1230 exit outside of your mail to this issue on GitHub and look how you spammed this thread with your big posts

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762702150",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762702150",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by john-preston** [comment] 2021-01-19 09:45
@Ondra1230

This is the way your replies look like:

![image](https://user-images.githubusercontent.com/17900494/105016794-82083880-5a5c-11eb-9dac-1c8afafc9172.png)

Please don't reply that way anymore, use GitHub web version instead. Otherwise I'll have to block you, because your replies make the issue completely unreadable.

**Comment by Ondra1230** [comment] 2021-01-19 09:52
I don’t understand... Have a nice dayOn 1/19/21 at 03:45, John Preston wrote:
                
            
            
                
                    From: "John Preston" <notifications@github.com>Date: January 19, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Mention" <mention@noreply.github.com>,"Ondra1230" <Ondra123@mail.com>Subject: Re: [telegramdesktop/tdesktop] Context / Right-Click Menu Opens in Wrong Display (#7099)
                
                
@Ondra1230
This is the way your replies look like:

Please don't reply that way anymore, use GitHub web version instead. Otherwise I'll have to block you, because your replies make the issue completely unreadable.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762726578",
"url": "https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-762726578",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by john-preston** [comment] 2021-01-19 09:53
@Ondra1230 you too.

**Comment by blancoek** [comment] 2021-02-25 02:05
Having the same happen:
Windows 10 19041.508
Intel Core i7-2700K
Radeon RX480 4GB + NVIDIA RTX 1060 SC 3GB
T22C301 22" Samsung Monitor + SyngMaster SA300 21" Samsung Monitor
Telegram Desktop 2.6 running on secondary monitor on the 1060 and messages appearing on the primary one on the 480

**Comment by NZeee** [comment] 2021-03-09 11:03
I have the same issue on my MacBook Pro mid 2015 with integrated graphics :(

**Comment by a7lan** [comment] 2021-04-20 06:02
any news?

**Comment by Aokromes** [comment] 2021-04-20 06:44
> any news?

maybe amd or QT must fix it.

**Comment by ilya-fedin** [comment] 2021-04-20 10:37
> any news?

no one reported this to Qt nor to AMD AFAIK yet

**Comment by a7lan** [comment] 2021-04-23 06:06
Found bug in qt bug tracker 
https://bugreports.qt.io/browse/QTBUG-84545
https://bugreports.qt.io/browse/QTBUG-84462

**Comment by ilya-fedin** [comment] 2021-04-23 14:35
> Found bug in qt bug tracker

They are closed

**Comment by ilya-fedin** [comment] 2021-04-23 14:39
They are also about standard menus, while tdesktop uses custom menu widgets, so the bug should be somewhere in Qt platform code or in QWidget. Probably Qt incorrectly handles geometry with multiple GPUs.

**Comment by ilya-fedin** [comment] 2021-04-23 14:49
This issue probably won't move forward until someone with such hardware debug this

**Comment by TheNoim** [comment] 2021-05-05 15:36
Ok this just sucks. Any workaround for this? This is really annoying. It also happens for Images if you click on them.

**Comment by a7lan** [comment] 2021-05-05 20:34
> 
> 
> Ok this just sucks. Any workaround for this? This is really annoying. It also happens for Images if you click on them.

I found a workaround for myself. Made the second monitor the main monitor. The context menu is now displayed correctly

**Comment by TheNoim** [comment] 2021-05-09 10:00
> > Ok this just sucks. Any workaround for this? This is really annoying. It also happens for Images if you click on them.
> 
> I found a workaround for myself. Made the second monitor the main monitor. The context menu is now displayed correctly

I mean, the thing is, it not always happens. I have three monitors and sometimes it is correct, sometimes it isn't. In this exact moment, it is correct. Context and images show on the same monitor as telegram. But yesterday it wasn't correct.

**Comment by epigramx** [comment] 2021-06-10 03:54
Consistently happening on the latest drivers here. Tg is on a secondary monitor. There's also an intel output to another monitor but that may be unrelated.

**Comment by epigramx** [comment] 2021-06-10 03:57
PS All the qtbugs you list above are CLOSED!

**Comment by ilya-fedin** [comment] 2021-06-10 15:34
Someone listed wrong qtbugs, this issue was never reported to qt

**Comment by JDTm** [comment] 2021-08-17 17:50
Also happen on MacBook Pro 13" early 2020 - i5 with Intel Iris Plus Graphics 1536 MB .
Telegram 2.9.3
MacOs 11.4

**Comment by rdaraujo** [comment] 2021-09-15 18:18
It seems bug's still present.
```
Telegram 3.0.4 beta x64
Windows 10 20H2 (19042.1237)
RX580 (Radeon 21.8.2) + Intel HD Graphics 4000
```
With same setup (hardware, drivers) and Telegram 1.8.15 it works just fine. So maybe it's not a AMD problem.
Also Unigram (Telegram alternative client) works fine (I don't know if it uses Qt).

**Comment by ilya-fedin** [comment] 2021-09-15 18:20
Qt was updated two times since 1.8.15. In 1.9.0 and 2.4.8. Unigram doesn't use Qt.

**Comment by Aokromes** [comment] 2021-09-15 19:04
> It seems bug's still present.
> 
> ```
> Telegram 3.0.4 beta x64
> Windows 10 20H2 (19042.1237)
> RX580 (Radeon 21.8.2) + Intel HD Graphics 4000
> ```
> 
> With same setup (hardware, drivers) and Telegram 1.8.15 it works just fine. So maybe it's not a AMD problem.
> Also Unigram (Telegram alternative client) works fine (I don't know if it uses Qt).

try qbittorrent.

**Comment by MIOsystems** [comment] 2021-10-01 07:52
This problem gets really annoying. Still in the latest (3.1.5 beta x64). Shouldn't we add up the priority on this one?

![image](https://user-images.githubusercontent.com/46918729/135584771-85f7524c-d7a8-4a4f-9f2d-29ec5860dc59.png)

**Comment by Aokromes** [comment] 2021-10-01 08:05
> This problem gets really annoying. Still in the latest (3.1.5 beta x64). Shouldn't we add up the priority on this one?
> 
> On a: AMD Ryzen 7 4800H with Radeon Graphics
> 
> ![](https://user-images.githubusercontent.com/46918729/135584771-85f7524c-d7a8-4a4f-9f2d-29ec5860dc59.png)

it's very likely bug on qt or amd gfx drivers or a combination of both.

**Comment by MIOsystems** [comment] 2021-10-01 09:05
Can i do some testing to locate the problem?

**Comment by Aokromes** [comment] 2021-10-01 09:37
> Can i do some testing to locate the problem?

try qbittorrent, if it fails it's clear it's not telegram desktop bug.

**Comment by TheDjEzio** [comment] 2021-10-01 10:07
Sorry for the (maybe stupid) question. What does qbittorrent have to do with telegram?

**Comment by Aokromes** [comment] 2021-10-01 11:11
> Sorry for the (maybe stupid) question. What does qbittorrent have to do with telegram?

it uses QT like telegram desktop.

**Comment by TheDjEzio** [comment] 2021-10-01 15:57
ok i tried qbittorrent, it works fine, open the right button on the right screen at the right position

**Comment by ilya-fedin** [comment] 2021-10-01 20:14
> Can i do some testing to locate the problem?

Yes, you can add some logging (I can send a patch with such logging) with positions of the menus and screens, build tdesktop from sources, reproduce the problem and publish these log lines here

**Comment by ilya-fedin** [comment] 2021-10-01 20:15
> it uses QT like telegram desktop.

both tdesktop and qbiittorrent don't use Quick Time, they use Qt ;)

**Comment by ilya-fedin** [comment] 2021-10-01 20:17
Testing with qBittorrent doesn't really has sense, tdesktop has custom menu widgets and Qt changed something that affects only tdesktop's custom menus, while the standard QMenu widget seem to work just fine

**Comment by MIOsystems** [comment] 2021-10-04 07:04
> 
> 
> > Can i do some testing to locate the problem?
> 
> Yes, you can add some logging (I can send a patch with such logging) with positions of the menus and screens, build tdesktop from sources, reproduce the problem and publish these log lines here

Okay. Please help me build the patch. I will try to implement and build it

**Comment by ilya-fedin** [comment] 2021-11-07 09:50
mac & linux official binaries use Qt 6.2 since 3.2, is something changed to this bug on macos?

**Comment by MIOsystems** [comment] 2021-12-01 07:48
I don't think closing this issue is a solution. What information can i deliver to explorer more?

**Comment by ilya-fedin** [comment] 2021-12-01 09:37
@MIOsystems see this post https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-962573245. If the question will be answered, the issue will be reopened.

**Comment by ilya-fedin** [comment] 2021-12-01 10:32
> Nothing has changed for me on Big Sur 11.6

What's your tdesktop version?

**Comment by sanderjn** [comment] 2021-12-01 10:33
> > Nothing has changed for me on Big Sur 11.6
> 
> What's your tdesktop version?

3.2

**Comment by sanderjn** [comment] 2021-12-01 11:31
Sometimes with the external monitor setup even left clicks seem to be off when selecting a chat. For example: I click the first chat and the one that is at the bottom of the screen opens.
Makes me close and reopen Telegram Desktop a few dozen times a day.

**Comment by Pl4yingNight** [comment] 2021-12-08 13:28
Quite frankly it seems this Issue is still evident....

Here are some extra specs (mine) and as described above:
The Contect-Menue opens one the same x and y as the curser but always on the primary Monitor.
**Specs: Win 10 Pro + 3 Screens**
<ins>Graphics:</ins>
AMD Radeon RX 6800 XT (2 Screens) (1 is the Main-Screen)
NVIDIA GeForce GTX 1050 Ti (1 Screen)

**Comment by kandreak** [comment] 2021-12-09 09:55
came up this morning, versione 3.2.1
That's REAALLY annoying.

Happens to me on win10, integrated intel graphic card, 2 screens with a couple desktops.
the menu does not even appear in the other screen!

**Comment by hellodit** [comment] 2021-12-10 07:47
Does anyone know how to fix this issue?

**Comment by sanderjn** [comment] 2021-12-10 09:41
Not really, but restarting Telegram works for me.

**Comment by hellodit** [comment] 2021-12-10 17:21
> Not really, but restarting Telegram works for me.

it's happen when starting the app, restarting not work for me

**Comment by Drakulas01** [comment] 2021-12-13 20:05
Forcing app to use nvidia gpu seems to solve the issue. 
Go to settings -> Display -> Scroll down to graphics settings -> In this menu choose in drop-down list Desktop application -> Browse -> Choose the telegram .exe and then set it to use the gpu you need, then restart the app.
https://www.itechtics.com/use-specific-gpu/  - same instructions but with images

**Comment by Aokromes** [comment] 2021-12-13 20:43
> Forcing app to use nvidia gpu seems to solve the issue. Go to settings -> Display -> Scroll down to graphics settings -> In this menu choose in drop-down list Desktop application -> Browse -> Choose the telegram .exe and then set it to use the gpu you need, then restart the app. [itechtics.com/use-specific-gpu](https://www.itechtics.com/use-specific-gpu/) - same instructions but with images

then it's clear it's amd bug....

**Comment by MIOsystems** [comment] 2021-12-14 08:01
> Forcing app to use nvidia gpu seems to solve the issue

Great! Works for me. Although it not the the fix it supposes to be. I'm happy to see a workaround for it.

**Comment by hellodit** [comment] 2021-12-14 09:24
> Forcing app to use nvidia gpu seems to solve the issue. Go to settings -> Display -> Scroll down to graphics settings -> In this menu choose in drop-down list Desktop application -> Browse -> Choose the telegram .exe and then set it to use the gpu you need, then restart the app. https://www.itechtics.com/use-specific-gpu/ - same instructions but with images

Thanks it's work for me! using AMD+Nvdia GPU

**Comment by Aokromes** [comment] 2021-12-14 09:32
amd users, i suggest you to report here https://www.amd.com/es/support/kb/faq/amdbrt

**Comment by Drakulas01** [comment] 2021-12-14 11:38
Reported to AMD

**Comment by rdaraujo** [comment] 2021-12-17 17:17
Well, I've purchased a HDMI do DVI adapter and plugged both monitors I have to the same videoboard (AMD) and the problem is gone.
Previously, I was using one monitor (the main) plugged to that videoboard and the other one (secundary) plugged to the integrated video (Intel). So, now Windows only have to deal with one video driver, not both as before.

So, maybe the problem occurs when using two different video vendors?

**Comment by mvdan** [comment] 2021-12-17 17:38
I can reproduce this bug with my AMD laptop (just one GPU, the integrated one) and an external monitor, so the bug isn't caused by multiple GPUs or multiple video drivers.

**Comment by Aokromes** [comment] 2021-12-17 17:48
> I can reproduce this bug with my AMD laptop (just one GPU, the integrated one) and an external monitor, so the bug isn't caused by multiple GPUs or multiple video drivers.

https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-993346994

**Comment by ilya-fedin** [comment] 2022-04-17 02:00
Is this issue still present with tdesktop 3.7?

**Comment by mvdan** [comment] 2022-04-17 09:00
I still experience it on Arch Linux, latest versions of all deps as of a couple of days ago.

**Comment by ilya-fedin** [comment] 2022-04-17 09:01
This issue is about Windows + AMD

**Closed** 2022-05-02 00:17 UTC
Labels: waiting for answer, 3rd party issue
