### ISSUE TITLE
Windows close/min/max buttons very small

### ISSUE THREAD

**Issue by GrinJ** [telegramdesktop/tdesktop#2841] opened 2017-01-13 15:11 UTC
Hello, can you please do something with close/min/max buttons on Windows client? In the previous version as I can understand you used custom buttons but after 1.0 update on windows 10 the size of the buttons is really small, it is smaller than on system apps. 

![telegram](https://cloud.githubusercontent.com/assets/4682965/21934581/fdd58368-d9ba-11e6-8b18-b9b3a33cfe0c.png)

May be something like this? 

![telegram](https://cloud.githubusercontent.com/assets/4682965/21934602/122cf9ae-d9bb-11e6-9d22-b6af7fdfa5ba.jpg)

**Comment by virtualdj** [comment] 2017-01-13 17:31
Duplicate of #2818.

**Comment by KreAch3R** [comment] 2017-01-13 23:35
I really think that @nshishov is right and the application should use the default OS elements. Besides design, it also messes up touch input (i.e. when you try to use it on a Windows tablet, the buttons are not very responsive).

**Closed** 2017-01-14 09:42 UTC

**Comment by luckydonald** [comment] 2017-01-15 16:41
@auchri  Why did you close this without reason?

**Comment by john-preston** [comment] 2017-01-15 16:42
@luckydonald Because it is a duplicate of an open issue so there is no need for a second one.

**Comment by luckydonald** [comment] 2017-01-15 16:51
My apologies, missed that.
