### ISSUE TITLE
Incorrect behaviour when pop-up menu disappeared

### ISSUE THREAD

**Issue by feriman** [telegramdesktop/tdesktop#25108] opened 2022-09-21 22:03 UTC
### Steps to reproduce

1. Open pop-up menu.
2. Close pop-up menu.

### Expected behaviour

Telegram main window should remain in the same position in windows hierarchy.

### Actual behaviour

Telegram main window brings above other opened windows.

### Operating system

Gentoo Linux, dwm, X11

### Version of Telegram Desktop

4.2.0

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment] 2022-09-22 08:22
should already be fixed on dev branch

**Closed** 2022-09-22 08:23 UTC
Labels: bug

**Comment by ilya-fedin** [comment] 2022-09-22 08:28
Oh, I just re-read the issue, I don't think it's actually fixed. I'd say it's the intended behavior (even though you don't like it). There always was focus transition to popup's parent window, but it didn't work due to delayed call and Qt not handling it correctly what was breaking input methods (i.e. people can't use dead keys). Now this works and it behaves as it should.

**Comment by john-preston** [comment] 2022-09-24 06:29
I don't quite understand the problem. There is code to focus the window after the tdesktop pop-up menu is closed. This is done because it is assumed tdesktop window was in focus _before_ the menu was shown.

**Comment by feriman** [comment] 2022-09-24 07:51
> I don't quite understand the problem. There is code to focus the window after the tdesktop pop-up menu is closed. This is done because it is assumed tdesktop window was in focus _before_ the menu was shown.

I made a small video to illustrate the issue.
https://user-images.githubusercontent.com/7603357/192086877-72affe32-1c00-4efe-a1b9-3f145c5d16a4.mp4

**Comment by ilya-fedin** [comment] 2022-09-24 07:54
I don't see any bug in the video

**Comment by feriman** [comment] 2022-09-24 08:06
I made a new one. Perhaps on this video it would be seen better.
https://user-images.githubusercontent.com/7603357/192087567-f8f5b9ae-1854-4875-9382-f7def25d2f12.mp4

**Comment by ilya-fedin** [comment] 2022-09-24 08:08
Can you check 4.2.2?

**Comment by john-preston** [comment] 2022-09-24 08:15
@feriman Well, in my understanding making the window active (when you type a message in it and click to show the menu) already should bring the window to front, above all non-keep-on-top windows. So after menu closing nothing changes.

It happens that way on all systems that I've seen (win, macos, basic linux setups).

In your case you somehow manage to make the window active and receive keyboard and mouse input without bringing it to front. I don't know how to do that programmatically (so I could do that instead of fully activating, with bringing it to front).

**Comment by feriman** [comment] 2022-09-24 12:39
I made some investigations and results are: 4.1.0 - no issue, 4.2.0 - issue present, 4.2.2 - no issue. Thank you for help guys.
https://user-images.githubusercontent.com/7603357/192098438-6c692349-dce2-4972-ad64-53e9b7becfa7.mp4
