### ISSUE TITLE
[Feature Request] Add Instant View Support

### ISSUE THREAD

**Issue by sapurtcomputer30** [telegramdesktop/tdesktop#23910] opened 2022-01-17 10:42 UTC
### Is your feature request related to a problem?

Instant view has been supported in **Mobile** Telegram for many years and can be easily opened on mobile, but **in desktop versions we have to open it as a browser.**
In some cases, due to the conditions of the countries' sanctions, it is not possible to use the software to remove the sanctions for Mosha

### Describe the solution you'd like

I have two ideas to solve this problem

The first idea
Use the appearance of a chat and show Instant view

The second idea
Open an additional page (such as the Add Account page when you want to add a second account) and display instant content on that page (which I don't think makes sense)

### Describe alternatives you've considered

I explained everything that was needed in the previous two parts

### Additional context

<h2>This is almost an idea I have</h2>

![tg instant view](https://user-images.githubusercontent.com/26039089/149754659-1e43d4d6-28e6-4275-8d3c-e63385995850.png)

**Comment by powerd3v** [comment] 2022-01-17 10:47
I think that's so good idea!

**Comment by RememberTheAir** [comment] 2022-01-17 12:00
Duplicate of #3492 - there's a discussion there on why it's taking so long/it's not on top of this app's priorities

**Closed** 2022-01-17 17:47 UTC
Labels: enhancement
