### ISSUE TITLE
[Feature Request] "Mark as readed" menu item for folder

### ISSUE THREAD

**Issue by V1RTUOZ** [telegramdesktop/tdesktop#7540] opened 2020-03-31 15:11 UTC
"Mark as readed" menu item for folder looks like useful feature, isn't it?

**Comment by Sergey1011010** [comment] 2020-03-31 15:52
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/7507

**Closed** 2020-03-31 18:35 UTC
