### ISSUE TITLE
[Flatpak] Can't type grave accent characters using intl. with AltGr dead keys layout

### ISSUE THREAD

**Issue by c3n21** [telegramdesktop/tdesktop#24080] opened 2022-02-15 07:56 UTC
### Steps to reproduce

1. Update to the latest flatpak version of Telegram
2. Open Telegram and try to type è (AltGr + ` + e)

I had to revert to **529c6a8348866b2b8ab039e4d885d5893d7e7b2f3677a9845061f14c084ebcb3** to momentarily avoid the issue.

### Expected behaviour

When typing (AltGr + ` + e) it should input **è**

### Actual behaviour

When typing (AltGr + ` + e) `e is displayed instead (two separate characters as if I didn't press AltGr), whereas (AltGr + e) works properly displaying **é**.

### Operating system

Arch Linux (Plasma KDE 5.24.0)

### Version of Telegram Desktop

965320fccf11326a771a74262e3800d7e1bd632c614bf2de6e0a7b0d6852e400

### Installation source

Flatpak

**Comment by ilya-fedin** [comment] 2022-02-15 14:54
I don't know where it gets these hashes from, but there are no such commits on the repo. Anyway, sounds like a duplicate of #1041.

**Closed** 2022-02-15 14:58 UTC
Labels: bug
