### ISSUE TITLE
[feature request] Switching colour palette to 'dark' theme

### ISSUE THREAD

**Issue by BAPostma** [telegramdesktop/tdesktop#1019] opened 2015-08-19 21:59 UTC
Love the desktop client, but for us geeks working till post-midnight, a 'dark' theme would be easy on the eyes.
I propose (well, feature request) an extra setting that allows us to change the colourful Telegram colour palette into a darker theme, such as the new Windows 10 apps. Black, white, 2-3 shades of grey (not 50! :laughing:) and deep-blue.

The following theme from the Windows 10 Photo's app is an example of a very appealing, eye-friendly colour palette.

![screenshot_1](https://cloud.githubusercontent.com/assets/5364372/9370139/3fb7f314-46ce-11e5-854d-ab01e5c360c0.png)

**Comment by auchri** [comment] 2015-08-19 22:40
Nice description, but duplicate of #185

**Closed by auchri** 2015-08-19 22:40 UTC

**Comment by auchri** [comment] 2015-08-19 22:44
I've copied your description to the other issue, thanks!

**Comment by wildcolin** [comment] 2016-09-15 22:21
FYI, https://github.com/NXij/tdesktop-dark
