### ISSUE TITLE
 Telegram Linux app crashes while try to play video

### ISSUE THREAD

**Issue by romankspb** [telegramdesktop/tdesktop#26784] opened 2023-09-13 08:26 UTC
### Steps to reproduce

1. open any chat
2. find any video
3. try to play video

### Expected behaviour

Playing video

### Actual behaviour

Telegram Desktop application hang with error message `The Wayland connection experienced a fatal error: Protocol error`

```
$ LANG=C ./Telegram 
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment

(Telegram:13820): Gtk-WARNING **: 11:24:16.797: Theme parsing error: <data>:1:0: Expected a valid selector
The Wayland connection experienced a fatal error: Protocol error
```

### Operating system

Fedora release 38 (Thirty Eight)

### Version of Telegram Desktop

4.9.6

### Installation source

Static binary from official website

### Logs

```shell
$ cat ./.local/share/TelegramDesktop/log.txt
[2023.09.13 11:24:14] Launched version: 4009006, install beta: [FALSE], alpha: 0, debug mode: [FALSE]
[2023.09.13 11:24:14] Executable dir: /home/romank/Загрузки/Telegram/, name: Telegram
[2023.09.13 11:24:14] Initial working dir: /home/romank/Загрузки/Telegram/
[2023.09.13 11:24:14] Working dir: /home/romank/.local/share/TelegramDesktop/
[2023.09.13 11:24:14] Command line: ./Telegram
[2023.09.13 11:24:14] Executable path before check: /home/romank/Загрузки/Telegram/Telegram
[2023.09.13 11:24:14] Logs started
[2023.09.13 11:24:14] App ID: org.telegram.desktop._0a70f1faa8ad16c2f029e42dfbb677f8
[2023.09.13 11:24:14] Connecting local socket to dc35a6a1ed42c65ea859a0ca947395b1-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2023.09.13 11:24:14] Socket connect error 0, starting server and app...
[2023.09.13 11:24:14] Moved logging from '/home/romank/.local/share/TelegramDesktop/log_start0.txt' to '/home/romank/.local/share/TelegramDesktop/log.txt'!
[2023.09.13 11:24:14] Opened '/home/romank/.local/share/TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0
[2023.09.13 11:24:14] Global devicePixelRatio: 1
[2023.09.13 11:24:14] Primary screen DPI: 96, Base: 96.
[2023.09.13 11:24:14] Computed screen scale: 100
[2023.09.13 11:24:14] DevicePixelRatio: 1
[2023.09.13 11:24:14] ScreenScale: 100
[2023.09.13 11:24:14] Icon theme: Adwaita
[2023.09.13 11:24:14] Fallback icon theme: 
[2023.09.13 11:24:14] System tray available: [FALSE]
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2023.09.13 11:24:14] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2023.09.13 11:24:14] App Info: reading settings...
[2023.09.13 11:24:14] App Info: reading encrypted settings...
[2023.09.13 11:24:14] Lang Info: Loaded cached, keys: 5266
[2023.09.13 11:24:14] OpenAL Logging Level: (not set)
[2023.09.13 11:24:14] Audio Playback Devices: Family 17h/19h HD Audio Controller Аналоговый стерео
[2023.09.13 11:24:14] Audio Playback Default Device: Family 17h/19h HD Audio Controller Аналоговый стерео
[2023.09.13 11:24:14] Audio Capture Devices: Family 17h/19h HD Audio Controller Аналоговый стерео;Monitor of Family 17h/19h HD Audio Controller Аналоговый стерео
[2023.09.13 11:24:14] Audio Capture Default Device: Family 17h/19h HD Audio Controller Аналоговый стерео
[2023.09.13 11:24:14] OpenGL Profile: Compatibility.
[2023.09.13 11:24:14] OpenGL Renderer: AMD Radeon Graphics (renoir, LLVM 16.0.5, DRM 3.52, 6.3.8-200.fc38.x86_64)
[2023.09.13 11:24:14] OpenGL Vendor: AMD
[2023.09.13 11:24:14] OpenGL Version: 4.6 (Compatibility Profile) Mesa 23.1.2
[2023.09.13 11:24:14] OpenGL Extensions: GL_EXT_packed_pixels, GL_ARB_gpu_shader5, GL_NV_shader_atomic_int64, GL_EXT_shader_integer_mix, GL_NV_ES1_1_compatibility, GL_EXT_compiled_vertex_array, GL_EXT_gpu_program_parameters, GL_ARB_shader_group_vote, GL_EXT_blend_color, GL_ANGLE_texture_compression_dxt5, GL_ARB_indirect_parameters, GL_EXT_draw_buffers2, GL_ARB_shadow, GL_ARB_shader_clock, GL_ARB_texture_env_crossbar, GL_EXT_packed_depth_stencil, GL_ARB_point_parameters, GL_ARB_direct_state_access, GL_NV_conditional_render, GL_EXT_vertex_array_bgra, GL_MESA_texture_signed_rgba, GL_ARB_shading_language_include, GL_ARB_fragment_shader, GL_ARB_polygon_offset_clamp, GL_ARB_uniform_buffer_object, GL_EXT_vertex_attrib_64bit, GL_ARB_copy_image, GL_ARB_compute_shader, GL_ARB_texture_query_lod, GL_EXT_debug_label, GL_ARB_texture_mirror_clamp_to_edge, GL_ARB_base_instance, GL_EXT_framebuffer_blit, GL_EXT_texture_shared_exponent, GL_ARB_robustness, GL_ARB_tessellation_shader, GL_ARB_ES2_compatibility, GL_ATI_fragment_shader, GL_ARB_compatibility, GL_ARB_depth_texture, GL_ARB_shading_language_100, GL_ARB_multi_draw_indirect, GL_ARB_texture_cube_map, GL_NV_light_max_exponent, GL_NV_texture_barrier, GL_ARB_shader_atomic_counter_ops, GL_ARB_texture_storage, GL_NV_copy_depth_to_color, GL_EXT_bgra, GL_MESA_framebuffer_flip_y, GL_KHR_debug, GL_SGIS_texture_border_clamp, GL_ARB_texture_mirrored_repeat, GL_EXT_stencil_two_side, GL_ARB_texture_gather, GL_ARB_vertex_shader, GL_ARB_shader_ballot, GL_EXT_texture_compression_latc, GL_SGIS_texture_lod, GL_ARB_compressed_texture_pixel_storage, GL_EXT_blend_equation_separate, GL_NV_half_float, GL_EXT_point_parameters, GL_ARB_ES3_2_compatibility, GL_EXT_texture_buffer_object, GL_EXT_texture_object, GL_NV_primitive_restart, GL_EXT_texture_integer, GL_NV_compute_shader_derivatives, GL_ARB_transform_feedback_overflow_query, GL_ARB_buffer_storage, GL_KHR_texture_compression_astc_sliced_3d, GL_ARB_arrays_of_arrays, GL_ARB_shading_language_420pack, GL_ARB_seamless_cube_map, GL_ARB_map_buffer_range, GL_KHR_parallel_shader_compile, GL_ARB_conservative_depth, GL_EXT_shader_samples_identical, GL_MESA_shader_integer_functions, GL_EXT_subtexture, GL_ARB_robust_buffer_access_behavior, GL_ARB_fragment_program_shadow, GL_ATI_texture_compression_3dc, GL_ARB_texture_rgb10_a2ui, GL_AMD_draw_buffers_blend, GL_ARB_sparse_texture2, GL_NV_depth_clamp, GL_ARB_vertex_attrib_64bit, GL_ARB_multisample, GL_ARB_fragment_program, GL_EXT_texture_sRGB_R8, GL_ARB_texture_rectangle, GL_ARB_debug_output, GL_ARB_texture_float, GL_ARB_draw_instanced, GL_AMD_query_buffer_object, GL_ARB_get_program_binary, GL_ARB_texture_compression_bptc, GL_SUN_multi_draw_arrays, GL_ARB_explicit_uniform_location, GL_ARB_program_interface_query, GL_AMD_shader_trinary_minmax, GL_ARB_occlusion_query, GL_EXT_transform_feedback, GL_EXT_demote_to_helper_invocation, GL_EXT_separate_specular_color, GL_ARB_shader_atomic_counters, GL_AMD_texture_texture4, GL_EXT_draw_instanced, GL_ATI_texture_float, GL_ARB_compute_variable_group_size, GL_MESA_window_pos, GL_EXT_timer_query, GL_ARB_get_texture_sub_image, GL_ARB_instanced_arrays, GL_EXT_abgr, GL_ARB_clear_buffer_object, GL_EXT_texture_compression_rgtc, GL_ARB_shader_subroutine, GL_ARB_sampler_objects, GL_EXT_memory_object, GL_EXT_copy_texture, GL_ARB_provoking_vertex, GL_EXT_texture_swizzle, GL_KHR_no_error, GL_ARB_texture_barrier, GL_EXT_vertex_array, GL_EXT_semaphore, GL_ARB_bindless_texture, GL_NV_alpha_to_coverage_dither_control, GL_ARB_seamless_cubemap_per_texture, GL_ARB_sync, GL_ARB_separate_shader_objects, GL_EXT_texture_compression_dxt1, GL_OES_EGL_image, GL_ARB_gpu_shader_fp64, GL_ARB_pixel_buffer_object, GL_EXT_texture_lod_bias, GL_ARB_internalformat_query, GL_SGIS_texture_edge_clamp, GL_NV_fog_distance, GL_AMD_multi_draw_indirect, GL_ATI_draw_buffers, GL_ARB_sparse_buffer, GL_EXT_texture_compression_s3tc, GL_NV_texgen_reflection, GL_ARB_draw_indirect, GL_ARB_half_float_pixel, GL_AMD_vertex_shader_viewport_index, GL_AMD_shader_stencil_export, GL_ARB_texture_cube_map_array, GL_EXT_texture_snorm, GL_ATI_texture_mirror_once, GL_NV_texture_env_combine4, GL_ARB_viewport_array, GL_ARB_draw_elements_base_vertex, GL_ARB_shader_stencil_export, GL_EXT_EGL_image_storage, GL_IBM_multimode_draw_arrays, GL_ARB_gpu_shader_int64, GL_ARB_shader_image_load_store, GL_ARB_shader_texture_image_samples, GL_ARB_shader_draw_parameters, GL_INGR_blend_func_separate, GL_ARB_texture_compression, GL_EXT_shadow_funcs, GL_ARB_shader_texture_lod, GL_ARB_multitexture, GL_EXT_framebuffer_sRGB, GL_ARB_timer_query, GL_EXT_blend_subtract, GL_ARB_spirv_extensions, GL_ARB_vertex_program, GL_EXT_texture_env_add, GL_ARB_color_buffer_float, GL_AMD_framebuffer_multisample_advanced, GL_ATI_separate_stencil, GL_ARB_blend_func_extended, GL_ATI_texture_env_combine3, GL_ARB_derivative_control, GL_EXT_EGL_sync, GL_EXT_texture_edge_clamp, GL_ARB_clear_texture, GL_IBM_texture_mirrored_repeat, GL_EXT_shader_image_load_formatted, GL_ARB_texture_storage_multisample, GL_ARB_occlusion_query2, GL_ARB_vertex_array_object, GL_EXT_texture3D, GL_ARB_shader_storage_buffer_object, GL_ARB_texture_env_combine, GL_ARB_framebuffer_no_attachments, GL_ARB_invalidate_subdata, GL_ARB_texture_border_clamp, GL_EXT_texture_filter_anisotropic, GL_ARB_transform_feedback3, GL_ARB_texture_view, GL_AMD_pinned_memory, GL_ARB_pipeline_statistics_query, GL_NV_copy_image, GL_OES_read_format, GL_ARB_framebuffer_object, GL_ARB_enhanced_layouts, GL_EXT_texture_sRGB, GL_ARB_cull_distance, GL_ARB_texture_buffer_object_rgb32, GL_EXT_provoking_vertex, GL_ARB_vertex_array_bgra, GL_ARB_transpose_matrix, GL_ATI_meminfo, GL_ARB_depth_clamp, GL_ARB_texture_env_dot3, GL_ARB_texture_multisample, GL_EXT_window_rectangles, GL_ARB_shader_image_size, GL_EXT_fog_coord, GL_AMD_depth_clamp_separate, GL_ARB_texture_compression_rgtc, GL_ARB_fragment_coord_conventions, GL_ARB_sample_shading, GL_EXT_framebuffer_multisample, GL_EXT_blend_minmax, GL_ARB_shader_precision, GL_ARB_multi_bind, GL_KHR_robustness, GL_ARB_sparse_texture, GL_EXT_direct_state_access, GL_ARB_ES3_compatibility, GL_ARB_explicit_attrib_location, GL_EXT_pixel_buffer_object, GL_ARB_shader_bit_encoding, GL_INTEL_blackhole_render, GL_EXT_rescale_normal, GL_EXT_texture_array, GL_NV_packed_depth_stencil, GL_ARB_transform_feedback_instanced, GL_ARB_conditional_render_inverted, GL_EXT_polygon_offset_clamp, GL_EXT_draw_range_elements, GL_ARB_internalformat_query2, GL_EXT_depth_bounds_test, GL_EXT_texture_env_combine, GL_AMD_vertex_shader_layer, GL_ARB_clip_control, GL_ARB_texture_query_levels, GL_ARB_map_buffer_alignment, GL_EXT_texture_shadow_lod, GL_ARB_transform_feedback2, GL_ARB_parallel_shader_compile, GL_NV_vdpau_interop, GL_ARB_texture_buffer_object, GL_IBM_rasterpos_clip, GL_KHR_texture_compression_astc_ldr, GL_ARB_texture_env_add, GL_ARB_window_pos, GL_EXT_texture, GL_ANGLE_texture_compression_dxt3, GL_ARB_texture_non_power_of_two, GL_APPLE_packed_pixels, GL_ARB_depth_buffer_float, GL_EXT_semaphore_fd, GL_EXT_framebuffer_object, GL_ARB_shader_objects, GL_EXT_shader_image_load_store, GL_ARB_sparse_texture_clamp, GL_EXT_stencil_wrap, GL_ARB_vertex_type_2_10_10_10_rev, GL_ARB_point_sprite, GL_ARB_copy_buffer, GL_AMD_performance_monitor, GL_ARB_fragment_layer_viewport, GL_ARB_texture_stencil8, GL_KHR_robust_buffer_access_behavior, GL_ARB_shading_language_packing, GL_ARB_ES3_1_compatibility, GL_ARB_shader_viewport_layer_array, GL_AMD_seamless_cubemap_per_texture, GL_ATI_blend_equation_separate, GL_MESA_pack_invert, GL_KHR_blend_equation_advanced, GL_ARB_vertex_type_10f_11f_11f_rev, GL_EXT_framebuffer_multisample_blit_scaled, GL_EXT_blend_func_separate, GL_ARB_query_buffer_object, GL_ARB_texture_rg, GL_EXT_secondary_color, GL_SGIS_generate_mipmap, GL_KHR_context_flush_control, GL_EXT_texture_rectangle, GL_NVX_gpu_memory_info, GL_ARB_texture_swizzle, GL_EXT_packed_float, GL_ARB_texture_buffer_range, GL_EXT_texture_env_dot3, GL_EXT_gpu_shader4, GL_EXT_texture_cube_map, GL_ARB_half_float_vertex, GL_ARB_draw_buffers, GL_ARB_vertex_attrib_binding, GL_EXT_memory_object_fd, GL_ARB_framebuffer_sRGB, GL_EXT_texture_mirror_clamp, GL_ARB_vertex_buffer_object, GL_ARB_stencil_texturing, GL_AMD_conservative_depth, GL_ARB_draw_buffers_blend, GL_NV_blend_square, GL_EXT_multi_draw_arrays, GL_NV_texture_rectangle, GL_EXT_texture_sRGB_decode, GL_ARB_gl_spirv, GL_S3_s3tc, GL_ARB_texture_filter_anisotropic
[2023.09.13 11:24:14] OpenGL: QOpenGLContext created, version: 4.4.
[2023.09.13 11:24:14] App Info: reading accounts info...
[2023.09.13 11:24:14] App Info: reading encrypted info...
[2023.09.13 11:24:14] App Info: reading map...
[2023.09.13 11:24:14] App Info: reading encrypted map...
[2023.09.13 11:24:14] App Info: reading encrypted user settings...
[2023.09.13 11:24:14] App Info: encrypted user settings read.
[2023.09.13 11:24:14] App Info: reading encrypted mtp data...
[2023.09.13 11:24:14] MTP Info: read keys, current: 5, to destroy: 0
[2023.09.13 11:24:14] Map read time: 12
[2023.09.13 11:24:14] App Info: reading encrypted mtp config...
[2023.09.13 11:24:14] Export Info: Destroy top bar by controller removal.
[2023.09.13 11:24:14] OpenGL: [TRUE] (Window)
[2023.09.13 11:24:14] Notification daemon product name: gnome-shell
[2023.09.13 11:24:14] Notification daemon vendor name: GNOME
[2023.09.13 11:24:14] Notification daemon version: 44.2
[2023.09.13 11:24:14] Notification daemon specification version: 1.2
[2023.09.13 11:24:14] Notification daemon capabilities: actions, body, body-markup, icon-static, persistence, sound
[2023.09.13 11:24:16] API Warning: not loaded minimal channel applied.
```

**Comment by d3cryptofc** [comment] 2023-09-13 08:40
Same thing here

**Comment by ilya-fedin** [comment] 2023-09-13 10:10
Protocol error means that Qt and your compositor haven't agreed...

**Comment by romankspb** [comment] 2023-09-13 12:12
Version 4.9.5 work fine, problem on 4.9.6 still persist

**Comment by ilya-fedin** [comment] 2023-09-13 12:24
tdesktop doesn't talk to Wayland directly so I'm not sure anything could be done on tdesktop level

**Comment by ilya-fedin** [comment] 2023-09-13 12:44
Maybe the client has detected your OpenGL is broken and disabled it. Check whether OpenGL works in the log.txt.

**Comment by romankspb** [comment] 2023-09-13 12:46
No, I haven't updated my system. I just updated tdesktop to 4.5.6. Nothing more

**Comment by ilya-fedin** [comment] 2023-09-13 12:48
@romankspb so far I believe you should report to Qt, mesa or GNOME. Not sure where exactly, I guess you have to look at your compositor's log for a better error.

**Comment by NTMan** [comment] 2023-09-14 19:13
I have same bug experience when playing video
```
❯ ~/Downloads/Telegram/Telegram

QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment

(Telegram:8845): Gtk-WARNING **: 00:06:53.557: Theme parsing error: <data>:1:0: Expected a valid selector
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
[libvpx-vp9 @ 0x7f40d4465000] v1.11.0
[libvpx-vp9 @ 0x7f40d4465000] v1.11.0
[libvpx-vp9 @ 0x7f40d4465400] v1.11.0
[libvpx-vp9 @ 0x7f40d4465400] v1.11.0
The Wayland connection experienced a fatal error: Protocol error
```

And starting video chat or audio call
```
❯ ~/Downloads/Telegram/Telegram

QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)

(Telegram:9060): Gtk-WARNING **: 00:07:03.129: Theme parsing error: <data>:1:0: Expected a valid selector
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
The Wayland connection experienced a fatal error: Protocol error
```

The crashes started happens after update Telegram to 4.9.6 version and continued on 4.9.7 version.
Please check working of Telegram application on Fedora Rawhide.

**Comment by NTMan** [comment] 2023-09-14 19:14
> I'm not sure what we can do? Your log just says protocol error and that's it. I can't reproduce. Maybe you got a system update with a new bug in mesa.

I am 200% sure that the telegram update is to blame

**Comment by sbrener1610** [comment] 2023-09-14 20:19
disabling wayland helps

**Comment by xscd** [comment] 2023-09-14 22:01
this is a funny one because videos actually play fine. the issue is when you open first a video it crashes. try this:

1) open a photo
2) then open a video (it will play fine)
3) in that session opening videos will work 
4) leave app and re-open try opening a video first, crash again

let me know if this works for people commented here.

**Comment by ilya-fedin** [comment] 2023-09-15 02:58
> I am 200% sure that the telegram update is to blame

Without a more verbose error, a reproduction (sorry, I still can't reproduce that in a VM, perhaps that's hardware-dependent) or a bisect by someone affected to find the offending code, I don't think anything could be done

**Comment by mlsokolova** [comment] 2023-09-15 04:28
Fedora 38, Telegram 4.9.7, the same error

**Comment by mlsokolova** [comment] 2023-09-15 05:56
> Fedora 38, Telegram 4.9.7, the same error

It fixed after set WaylandEnable=false in /etc/gdm/custom.conf and reboot
thanks @sbrener1610

**Comment by NTMan** [comment] 2023-09-15 06:44
> Without a more verbose error, a way for contributors to reproduct (sorry, I still can't reproduce that in a VM, perhaps that's hardware-dependent) or a bisection by someone affected to find the offending commit, I don't think anything could be done

I don't know what are you mean by `verbose error`, but I recorded video which prove that downgrade  Telegram helps workaround this issue: https://youtu.be/Xn8VUCCjWCI

**Comment by ilya-fedin** [comment] 2023-09-15 06:46
> I don't know what are you mean by `verbose error`

I mean something more detailed than just 'protocol error'

**Comment by NTMan** [comment] 2023-09-15 06:49
> I mean something more detailed than just 'protocol error'

Can you guide me? Or maybe exist step by step instruction?

**Comment by ilya-fedin** [comment] 2023-09-15 06:52
> Can you guide me? Or maybe exist step by step instruction?

I have no idea how to get a better errpr, sorry. Help on this would be highly appreciated.

**Comment by mlsokolova** [comment] 2023-09-15 07:07
I made trace file before switching to `WaylandEnable=false`   
 `strace -o telegram.trace -v -f  -s 1024 ./Telegram`  

Maybe some from the trace file could be useful  ?  
For example  

``` 
11278 futex(0x7fde7e915274, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
11305 recvmsg(9, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\0\0\0\0<\0E\0\0\0\0\0\0\0%\0\0\0exported surface had an invalid role\0\0\0\0", iov_len=1768}, {iov_base="", iov_len=2328}], msg_iovlen=2, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 60
11305 futex(0x7fde7e915274, FUTEX_WAKE_PRIVATE, 2147483647 <unfinished ...>
11278 <... futex resumed>)              = 0
11305 <... futex resumed>)              = 1
11305 write(2, "The Wayland connection experienced a fatal error: Protocol error\n", 65 <unfinished ...>
11278 futex(0x7fde7e915218, FUTEX_WAKE_PRIVATE, 1) = 0
11305 <... write resumed>)              = 65
11305 exit_group(1 <unfinished ...>
```

**Comment by ilya-fedin** [comment] 2023-09-15 07:09
strace shows kernel syscalls what is completely useless given that this doesn't seem to be a bug with kernel syscalls

**Comment by ilya-fedin** [comment] 2023-09-15 07:11
That seem to a bug with communicating between Qt and compositor so perhaps compositor logs may have an evidence. Although this may require enabling some debug logging on compositor side and how to enable it only your compositor devs know...

**Comment by ilya-fedin** [comment] 2023-09-15 07:12
The best way is for someone affected to do `git bisect` on Telegram sources and find the commit that added the bug. That would perhaps be the fastest way to the fix.

**Comment by ilya-fedin** [comment] 2023-09-15 08:50
video call? hm, video call and media viewer are using opengl so I wonder whether disabling opengl helps?

**Comment by aolo2** [comment] 2023-09-15 08:53
Disabling OpenGL doesn't help, sadly. I also confirmed that the issue was introduced between Telegram 4.9.5 (works) and 4.9.6 (doesnt work).

**Comment by ilya-fedin** [comment] 2023-09-15 08:54
Have you restarted the client after disabling OpenGL?

**Comment by aolo2** [comment] 2023-09-15 08:55
Yes, as prompted

**Comment by aolo2** [comment] 2023-09-15 09:09
Out of the 4.9.5 -> 4.9.6 commits only a few touch wayland-related code, the main suspect being this sumbodule update: https://github.com/telegramdesktop/tdesktop/commit/289257dd0f2642901cacf52ae91ed21731611233

Maybe someone who has the issue can try building before and after this commit to see if it's it?

**Comment by ilya-fedin** [comment] 2023-09-15 09:14
There's only call to xdg_toplevel_show_window_menu on right click at titlebar and xdg-decoration check on application startup. There's no custom Wayland code on window open afaik, so it should be some change in high-level code that triggers some bug in Qt. So literally any commit.

**Comment by aolo2** [comment] 2023-09-15 09:21
Not strictly relevant to Telegram, but relevant to this issue: since about the same time (can't say exactly) screenshare in *all other programs* has broken for me as well. I can't screenshare in chrome/firefox etc. Might be a coincidence though.

**Comment by ilya-fedin** [comment] 2023-09-15 09:29
How can we get what exactly protocol error happens? I guess answering that question would simplify things a lot.

**Comment by aolo2** [comment] 2023-09-15 09:32
Building in debug mode and setting a breakpoint my give more details that are not printed to stdout?

**Comment by ilya-fedin** [comment] 2023-09-15 09:33
Where would you set breakpoint though?

**Comment by aolo2** [comment] 2023-09-15 09:35
Whereever the error is printed and then track it back from there.

**Comment by ilya-fedin** [comment] 2023-09-15 09:36
I don't think we can get something helpful with a breakpoint from here? It writes the line from the event loop, not where the error actually happens.
https://github.com/qt/qtwayland/blob/v6.5.2/src/client/qwaylanddisplay.cpp#L75

**Comment by aolo2** [comment] 2023-09-15 09:41
I see. Then I guess we need some debug options in wayland/qt/qtwayland/compisotor etc? Like WAYLAND_DEBUG=1

**Comment by aolo2** [comment] 2023-09-15 09:43
Launching Telegram with `WAYLAND_DEBUG=1` works and prints this (only showing the latest message):

```
[2614717.648]  -> zwp_idle_inhibit_manager_v1@47.create_inhibitor(new id zwp_idle_inhibitor_v1@62, wl_surface@28)
[2614717.762]  -> zxdg_exporter_v2@43.export_toplevel(new id zxdg_exported_v2@45, wl_surface@28)
[2614717.764]  -> wl_display@1.sync(new id wl_callback@67)
[2614717.805] wl_display@1.error(zxdg_exporter_v2@43, 0, "surface must be an xdg_surface")
The Wayland connection experienced a fatal error: Protocol error
```

**Comment by ilya-fedin** [comment] 2023-09-15 09:43
Yeah, try running with that

**Comment by aolo2** [comment] 2023-09-15 09:49
Full log of me opening telegram 4.9.6, clicking on a dialog and pressing the "call" button
[wayland_debug.log](https://github.com/telegramdesktop/tdesktop/files/12618034/wayland_debug.log)

**Comment by aolo2** [comment] 2023-09-15 09:51
The offending like `zxdg_exporter_v2@33.export_toplevel(new id zxdg_exported_v2@35, wl_surface@66)` looks suspiciosly like the commit you mentioned "xdg_toplevel_show_window_menu"

**Comment by ilya-fedin** [comment] 2023-09-15 09:53
No, it's nowhere related. That's QWaylandXdgSurface::externWindowHandle().

**Comment by tokalek** [comment] 2023-09-15 09:53
Telegram crashes when trying to play a video. version telegram-4.9.7, GNOME Shell 44.4, Qt version 5.15.10, Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.2.0
![Снимок экрана от 2023-09-15 14-33-39](https://github.com/telegramdesktop/tdesktop/assets/25418389/77494c78-8dc8-48e3-826d-8dd36e47078c)
![Снимок экрана от 2023-09-15 14-35-09](https://github.com/telegramdesktop/tdesktop/assets/25418389/4c00841f-9e4f-439a-bc1c-fab98b30ee3b)

**Comment by ilya-fedin** [comment] 2023-09-15 10:27
Looks like display sleep inhibition is created before native window is created. Apparently it was silently not working before on Wayland but now it started crashing for some reason.

**Comment by aolo2** [comment] 2023-09-15 10:30
Since you can't reproduce the issue, how do we verify that the fix is working? Would you like me to build from source and test once it's pushed?

**Comment by ilya-fedin** [comment] 2023-09-15 10:31
If you can test from sources then yes. If you can't then probably pushing updates with fix attempts until we find the right fix.

**Comment by aolo2** [comment] 2023-09-15 10:33
I can build fine. I just couldn't do git bisect to find the issue since each build takes 10+ minutes on my machine, and it's the middle of a workday.

**Comment by ilya-fedin** [comment] 2023-09-15 10:37
Try this then: https://github.com/desktop-app/lib_base/pull/213
Not sure it would help though, I actually fail to understand how that happens. The error looks like inhibitor creation happens after [this](https://github.com/qt/qtwayland/blob/v6.5.2/src/client/qwaylandwindow.cpp#L100C1-L102) line but before [this](https://github.com/qt/qtwayland/blob/v6.5.2/src/client/qwaylandwindow.cpp#L138) line, that's impossible given that all this code is in one function.

If it won't help then I guess we have to unimplement display sleep on Wayland in order to fix the crash.

**Comment by aolo2** [comment] 2023-09-15 10:59
Ok, I'm like 20 minutes into compiling Qt, will report back as soon as I can

**Comment by ilya-fedin** [comment] 2023-09-15 13:35
*2 hours later*

**Comment by aolo2** [comment] 2023-09-15 13:55
Have some work calls to go through, sadly can't do that while CPU is pinned at 100% :/

**Comment by john-preston** [comment] 2023-09-15 17:29
@aolo2 Is it possible to check? I'd like to build a bugfix release and would be great to know if the fix works.

**Comment by aolo2** [comment] 2023-09-15 18:10
I left the build running and just came back to `#134 4245.8 lto-wrapper: fatal error: write: No space left on device` :O

**Comment by aolo2** [comment] 2023-09-15 18:12
How much disk space is needed for the build to succeed? I have like 50 gigs

**Comment by ilya-fedin** [comment] 2023-09-15 18:13
You can pull the image from https://github.com/telegramdesktop/tdesktop/pkgs/container/tdesktop%2Fcentos_env

**Comment by aolo2** [comment] 2023-09-15 18:21
Unfortunately the build with the image fails for me as well with:
```
CMake Error at Telegram/cmake/lib_tgcalls.cmake:7 (add_library):
  Cannot find source file:

    /usr/src/tdesktop/Telegram/ThirdParty/tgcalls/tgcalls/ChannelManager.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  Telegram/CMakeLists.txt:30 (include)
```

**Comment by ilya-fedin** [comment] 2023-09-15 18:23
Have you cloned the repository with --recusive?

**Comment by aolo2** [comment] 2023-09-15 18:24
I have done `git submodule update --recursive` separately. Let me try the clone

**Comment by ilya-fedin** [comment] 2023-09-15 18:24
Try `git submodule update --init --recursive`

**Comment by aolo2** [comment] 2023-09-15 18:25
Oh, and I see you since merged the pull request. Ok, trying a clean clone now

**Comment by aolo2** [comment] 2023-09-15 18:27
Ok, it's building

**Comment by aolo2** [comment] 2023-09-15 18:47
My system is seemingly completely frozen, responding to inputs about once in 3 minutes. Is there a way to limit memory/CPU it uses while building?

**Comment by ilya-fedin** [comment] 2023-09-15 18:51
Change Telegram/build/docker/centos_env/build.sh from `--parallel` to `-j` with manual thread count as you see fit

**Comment by aolo2** [comment] 2023-09-15 18:54
This is much more manageable, thanks.

**Comment by aolo2** [comment] 2023-09-15 19:01
The latest build is confirmed **NOT CRASHING**.

**Comment by ilya-fedin** [comment] 2023-09-15 21:47
Looks like found the actual culprit, it's [that](https://github.com/qt/qtwayland/blob/8df7c0e96a010807fab3bb7a9d63948f59995e5c/src/client/qwaylandwindow.cpp#L62). Qt creates a wl_surface on QWaylandWindow creation but doesn't fully initialize it so tdesktop code thinks it can go on while it really can't. This initial window state is completely inconsistent with the state after `show(); hide();` given that Qt deletes wl_surface after that. Looks like it exists just because plasmashell can't handle the absence of wl_surface on window creation: https://bugreports.qt.io/browse/QTBUG-58423.

**Comment by aolo2** [comment] 2023-09-16 07:53
Once 4.9.8 is released it would probably be best if someone besides me also tests if their crashes are fixed, since I'm not even the original author of the issue?

**Comment by savelov** [comment] 2023-09-16 11:51
> Once 4.9.8 is released it would probably be best if someone besides me also tests if their crashes are fixed, since I'm not even the original author of the issue?

I can test - I experience crashes in video playback in 4.9.7 version on wayland

**Comment by Spurlos** [comment] 2023-09-16 17:54
4.9.8 update -> no crashes in Ubuntu 23.04 (Gnome, Wayland)
Previously crashed on video window popup\calls window popup

**Comment by savelov** [comment] 2023-09-16 18:38
> > Once 4.9.8 is released it would probably be best if someone besides me also tests if their crashes are fixed, since I'm not even the original author of the issue?
> 
> I can test - I experience crashes in video playback in 4.9.7 version on wayland

I can also confirm that 4.9.8 version stopped crashing on video windows in telegram

**Comment by aolo2** [comment] 2023-09-16 20:07
It is fixed, however, there is not a new problem. When I click the 📞 icon to start the call, and then close the call window, Telegram crashes with a Segmentation fault

**Comment by aolo2** [comment] 2023-09-16 20:08
Should I create a new issue for this?

> It is fixed, however, there is now a new problem. When I click the 📞 icon to start the call, and then close the call window, Telegram crashes with a Segmentation fault

Should I create a new issue for this?

**Comment by ilya-fedin** [comment] 2023-09-16 20:14
Yeah, please create a new issue and don't forget to specify crash ID

**Closed** 2023-09-16 20:26 UTC
Labels: bug, help wanted, cant reproduce, 3rd party issue
