### ISSUE TITLE
[Request] Option to block animated stickers in groups

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6203] opened 2019-07-03 16:43 UTC
Animated stickers release soon, so we need option to disable permissions for animated stickers in groups (without disabling common stickers).

![image](https://user-images.githubusercontent.com/39812401/60609600-bceb4280-9dca-11e9-8ab3-0605197541fc.png)

**Comment by Neurotoxin001** [comment] 2019-07-03 17:05
Right now users can forward animated stickers from other chats even if stickers is restricted for all users in group settings.

Or even send it from packs, it user is on beta app.

**Comment by DASPRiD** [comment] 2019-07-06 22:21
Please also allow to disable animated stickers client-side, they are really annoying (Already disabled GIF autoplay for that reason).

**Comment by Neurotoxin001** [comment] 2019-07-07 15:40
> Please also allow to disable animated stickers client-side, they are really annoying (Already disabled GIF autoplay for that reason).

Agree. It's also uses too much CPU.

**Comment by Neurotoxin001** [comment] 2019-07-30 09:48
On beta tg for iOS now user can disable animated stickers
![image](https://user-images.githubusercontent.com/39812401/62119464-502f6f00-b2c8-11e9-95ca-112d200c8778.png)

Waiting it for desktop.

**Comment by Aokromes** [comment] 2020-10-24 15:16
wanted

**Comment by Neurotoxin001** [comment] 2020-10-24 17:26
Is this bot remove "stale" tag only if issue creator answers?

**Comment by Aokromes** [comment] 2020-10-24 17:27
other times it removes to any answer.

**Comment by Aokromes** [comment] 2020-10-24 17:27
https://github.com/telegramdesktop/tdesktop/issues/4175#issuecomment-716002131

**Comment by yashpalgoyal1304** [comment] 2020-12-24 12:29
Since #8303 is marked as duplicate of this issue, i would suggest widening the scope of this issue in the title from groups to all general/chats.

**Closed** 2021-01-26 11:52 UTC
Labels: api issue, enhancement

**Comment by Aokromes** [comment] 2021-03-06 23:11
such feature belongs to https://bugs.telegram.org/
