### ISSUE TITLE
[Question] Font size on linux (system font?)

### ISSUE THREAD

**Issue by kaytrance** [telegramdesktop/tdesktop#17510] opened 2022-01-04 19:01 UTC
1. [Here](https://github.com/telegramdesktop/tdesktop/issues/16888#issuecomment-912242872) it is mentioned that app uses system font.
2. On Linux app has tiny font in chat (on k monitor it just hurts my eyes), scaling does not give it a better look since it scales everything and app UI becomes bloated instead of being more readable (yes, text becomes bigger, but blurier).

So what is meant by "system font" and can it be substituted to some other font?

P.S. I wonder why no one haven't made a MR with better fonts built in..

**Comment by ilya-fedin** [comment] 2022-01-04 22:07
Apparently, he uses a patched version of tdesktop because tdesktop itself never allowed to change the font to seomthing rather than Open Sans. And yeah, this looks like yet another duplicate of #90.

**Closed** 2022-01-04 22:11 UTC
Labels: question
