### ISSUE TITLE
Unreaded posts in channels

### ISSUE THREAD

**Issue by okopok** [telegramdesktop/tdesktop#5735] opened 2019-02-26 12:44 UTC
### Steps to reproduce
1. Have channel with unread posts
2. Opening this channel - clear all unread posts counter
3. When you opening channel after restart Tdesktop, you are on bottom of this channel.
### Expected behaviour
Starts from first unread posts

### Actual behaviour
Starts from the last post

### Configuration
Operating system:
Windows 10 - 1809
Version of Telegram Desktop:
1.5.15
Used theme:
custom theme

When channel has more than 1k+ unread posts, opening this channel with tdesktop makes all unread posts as readed. And after this, you opening channel again, and see only the last post, even on mobile telegram. Please make read counter like on telegram for mobile devices, when you are open channel and start to see only real unread posts.

**Comment by 23rd** [comment] 2019-02-26 21:23
Duplicate of #775.

**Closed** 2019-09-06 20:55 UTC
