### ISSUE TITLE
Photo viewer breaks on higher resolutions

### ISSUE THREAD

**Issue by michi7x7** [telegramdesktop/tdesktop#1542] opened 2016-01-21 20:20 UTC
The Photo-Viewer looks broken on higher resolutions.

My system:
- Win7 64bit
- Telegram 0.9.18
- Single Screen on 2560x1440

Here is a (blurred) screenshot:
![issue](https://cloud.githubusercontent.com/assets/238211/12493164/1d34ae10-c084-11e5-85ca-05c304b388ce.png)

It looks like the resolution is correctly detected, as the image is perfectly centered. It just seems like the window is to small sized: I can click outside, move windows and activate controls.

Buttons to switch to the next picture and to download are not accessible, but the button for the previous picture works.

**Comment by Zenexer** [comment] 2016-01-23 09:39
What's your DPI set to?

**Comment by michi7x7** [comment] 2016-01-23 19:21
Both Windows and Telegram are set to 100%

**Comment by Gollam** [comment] 2016-02-04 18:36
Hi,
I'm also having this issue.

Steps to reproduce:
1. Open Telegram, with a given screen resolution.
2. Change the screen resolution, doesn't matter if it becomes bigger or smaller.
3. Open a picture in telegram.

Workaround: restarting the application with the new screen resolution fixes the problem.

**Comment by ofalvai** [comment] 2016-02-21 13:59
It also happens when a secondary display is plugged in or unplugged, so it's a much frequent issue than changing resolutions.

**Comment by Gollam** [comment] 2016-04-07 11:03
This seems to be fixed in 0.9.40. Could you please check it?

**Comment by Torvin** [comment] 2016-05-31 00:42
Another workaround: keep telegram window non-maximized. Then screen resolution change does not affect window size, which prevents the bug from happening.

**Comment by XGowe** [comment] 2016-05-31 04:10
I am not sure whether I have understood @Torvin 's description of the workaround. But what broken after changing resolution is the photo viwer, not the chat windows of Telegram client. Besides, while the chat window was hidden or non-maximized, and the built-in photo viwer was not open during resolution change, the photo viwer still got broken.

**Comment by Torvin** [comment] 2016-05-31 06:23
@XGowe you got me right. But it shouldn't matter if the window was hidden (minimised) or not, because a window can be minimised and maximised at the same time (when you click the icon - it will be shown maximised - so Windows remember the window was maximised). What does matter is, when a window is maximised, it will get automatically resized by OS to the current screen working area's size. And this, in turn, triggers the photo viewer's bug (I don't know why).

So if you make telegram's window smaller then the current screen resolution and then change the screen resolution in some way (rotate the display, connect via rdp, change display resolution settings) AND the window is still smaller then the new resolution (so the window has NOT automatically resized) - the bug won't happen! Weird.

**Comment by XGowe** [comment] 2016-05-31 10:45
@Torvin 
All right. But what you said is slightly different from the problem I got. What I found is, while the size of the chat window (the main window) of Telegram was always far smaller than the screen's resolution (I connected via RDP and opened the photo viewer which was opened and then closed previously when I operate my PC directly. ), the problem still occurred.

**Comment by kipusoep** [comment] 2016-06-17 18:29
This is so annoying and has been going on for months now, any chance on a fix?

**Closed** 2016-06-26 17:16 UTC
Labels: bug
