### ISSUE TITLE
Feature request: sign out group without deleting its messages

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [telegramdesktop/tdesktop#6083] opened 2019-06-02 17:28 UTC
I'm not sure if I should open this issue here.

Please kindly inform me of the correct direction to file this issue.

Telegram is awesome and has a lot of features. But one simple feature is missing.

We can't sign out from a group without deleting it?
This is a very handy and needed feature.

So I filing this issue to ask for this one.

**Comment by RememberTheAir** [comment] 2019-06-03 05:21
This sounds more like an API issue, tdesktop can't do much by itself

**Comment by Danilo-Araujo-Silva** [comment] 2019-06-04 01:25
Which is the repo of the Telegram API?

**Comment by kirsan31** [comment] 2019-06-04 08:51
> Which is the repo of the Telegram API?

**Many** most  wanted improvements/features of teleram rely on API, and **no one** know where to bug/suggest/discuss about it :(

**Comment by Danilo-Araujo-Silva** [comment] 2019-06-06 12:28
> > Which is the repo of the Telegram API?
> 
> **Many** most wanted improvements/features of teleram rely on API, and **no one** know where to bug/suggest/discuss about it :(

Wow, this is crazy o.O

I thought telegram was completely open source and with the possibility to actively receive contributions from the community.

**Comment by RememberTheAir** [comment] 2019-06-06 12:44
> Many most wanted improvements/features of teleram rely on API, and no one know where to bug/suggest/discuss about it :(

@kirsan31 you can suggest them on Twitter o to the in-app support. Telegram is not a community-driven project, but they listen to what users are asking for. They are surely aware of most of the stuffs suggested here that require API support. If they haven't decided to introduce them it's either because they have different priorities or because they think they're not good ideas

> I thought telegram was completely open source and with the possibility to actively receive contributions from the community.

@Danilo-Araujo-Silva they have never said they're open to contributions in terms of new features and ideas. They publish the sourcecode of their apps to let the community evaluate whether mtproto is properly implemented. The development of the mobile apps is pretty closed and tdesktop seems to be the only app accepting contributions from third parties as long as they do not break platform consistency and rules (see @23rd's contributions, for example). As I said above they do listen to the community (although sometime it might not seem so), but the final words on what to implement in the next update and what has the priority over other things is up to whoever is in charge to take these decisions at Telegram

**Comment by RememberTheAir** [comment] 2019-06-06 12:47
That said, I personally support the cause of this issue. I've always thought that being able to keep a chat's history after being removed from it was one of the things Telegram had over other apps. As far as I know, it still works like that in normal groups (non-supergroups). But I wouldn't be surprised if they decided to change this behavior after the famous "unsedn anything" update, that made it possible to delete a message with no time limit from normal groups too

**Comment by kirsan31** [comment] 2019-06-06 12:53
@RememberTheAir 

> you can suggest them on Twitter o to the in-app support. Telegram is not a community-driven project, but they listen to what users are asking for. They are surely aware of most of the stuffs suggested here that require API support. If they haven't decided to introduce them it's either because they have different priorities or because they think they're not good ideas

Twitter - really? :)  As for in-app support, I was doing it several times - never got an answer...

**Comment by RememberTheAir** [comment] 2019-06-06 13:26
> Twitter - really? :)

Yep, [Twitter](https://twitter.com/Telegram). Their account has been pretty active lately and you might get an answer as well if you ask them something. The in-app support doesn't usually answer to feature requests if they have been reported many times. But (depending on your country and how many TSF members your region has) they usually read and propose suggestions to Telegram (although, I don't really know how it works internally. Note also that messages you send to the in-app support get marked as read only when the support answers you, so a single tick does not mean nobody have read your message). Yes, I kind of agree that these two ways are not the ideal solution to gather feedbacks from your users, especially considering a lot of platform-wise suggestions are posted here in this issue tracker, but at least you have a way to make them hear your voice

**Comment by Danilo-Araujo-Silva** [comment] 2019-06-07 16:01
> That said, I personally support the cause of this issue. I've always thought that being able to keep a chat's history after being removed from it was one of the things Telegram had over other apps. As far as I know, it still works like that in normal groups (non-supergroups). But I wouldn't be surprised if they decided to change this behavior after the famous ["unsend anything" update](https://telegram.org/blog/unsend-privacy-emoji#unsend-anything), that made it possible to delete a message with no time limit from normal groups too

Well, I tried to do that with normal groups, but it didn't work.

The only way was using webogram, load all chat history and then downloading the webpage (in other to keep the chat history as a file in my computer, at least).

**Comment by RememberTheAir** [comment] 2019-06-07 21:26
> Well, I tried to do that with normal groups, but it didn't work.

Oh, well. I'm not surprised. That probably changed with the "unsend anything" update I've mentioned above.

> The only way was using webogram, load all chat history and then downloading the webpage (in other to keep the chat history as a file in my computer, at least).

Wait, do you mean that webogram allows you to load the history of normal groups you've been kicked from?

**Comment by Danilo-Araujo-Silva** [comment] 2019-06-09 23:45
> > Well, I tried to do that with normal groups, but it didn't work.
> 
> Oh, well. I'm not surprised. That probably changed with the "unsend anything" update I've mentioned above.
> 
> > The only way was using webogram, load all chat history and then downloading the webpage (in other to keep the chat history as a file in my computer, at least).
> 
> Wait, do you mean that webogram allows you to load the history of normal groups you've been kicked from?

No, I was in the chat, I've just wanted to leave but have a chat history.

**Closed** 2019-08-28 19:37 UTC
Labels: api issue
