### ISSUE TITLE
Flatpak Version is too slow after update

### ISSUE THREAD

**Issue by jawadalkassim** [telegramdesktop/tdesktop#8718] opened 2020-10-03 10:54 UTC
### Steps to reproduce
1. updated to 2.4.2
2. try scroll between chats or between messages especially with touchpad
3. scroll between settings options also slow

### Expected behaviour
Tell us what should happen
smooth scrolling 

### Actual behaviour
Tell us what happens instead
stuck sometimes for a while then continue scrolling 
Also Cursor pointer not following the theme and changed to another pointer icon

### Configuration
**Operating system:**
POP_OS 20.04 under Wayland
Linux
**Version of Telegram Desktop:**
2.4.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Flatpak
**Used theme**:
Tinted
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment] 2020-10-03 15:39
Flatpak-specific issues should be reported to https://github.com/flathub/org.telegram.desktop/issues

**Comment by ilya-fedin** [comment] 2020-10-03 15:40
Ah, looks like this is a duplicate of https://github.com/telegramdesktop/tdesktop/issues/8347
@Aokromes can you reopen?

**Closed** 2020-10-03 15:42 UTC
