### ISSUE TITLE
[Feature request] Grouping chats.

### ISSUE THREAD

**Issue by AntonBoch1244** [telegramdesktop/tdesktop#3942] opened 2017-09-29 11:26 UTC
### Steps to reproduce
Not require to reproduce

### Configuration
**Operating system: any**

**Version of Telegram Desktop: latest**

**Used theme**: standart

I just want feature of grouping chats as i wanted, this feature has been useful not only for me.

**Comment by RememberTheAir** [comment] 2017-09-29 13:22
Duplicate of #1107, and many other

**Comment by AntonBoch1244** [comment] 2017-09-29 14:17
Groups is not equal categories.

**Comment by auchri** [comment] 2017-09-29 14:18
@AntonBoch1244 But there's no for both of them 🤷‍♂️

**Closed** 2017-09-29 14:18 UTC

**Comment by AntonBoch1244** [comment] 2017-09-29 14:24
Groups can make only user but not automatically.
Categories make only automatically instead of user choice.
