### ISSUE TITLE
Telegram on snap doesn't write accents

### ISSUE THREAD

**Issue by DiogoConstantino** [telegramdesktop/tdesktop#5545] opened 2019-01-01 20:25 UTC
### Steps to reproduce
1. try to type á on telegram

### Expected behaviour
It show write á

### Actual behaviour
It only writes a

### Configuration
Ubuntu with snap package (with other packaging options it doesn't happen)

**Version of Telegram Desktop:**
All

**Used theme**:
Default

</details>

**Comment by stek29** [comment] 2019-01-07 21:31
#5487

**Comment by alfalco** [comment] 2019-02-14 20:38
### Steps to reproduce
1. Type ã on Telegram

### Expected behaviour
It show write ã

### Actual behaviour
It only writes a

### Configuration
Ubuntu/Kubuntu with snap package

**Version of Telegram Desktop:**
Snap from channel stable, version 1.5.15

**Used theme**:
Default

**Comment by tcarrondo** [comment] 2019-04-24 08:51
@stek29 this is not a duplicate of #5487

**Comment by stek29** [comment] 2019-04-27 11:30
@tcarrondo indeed, thanks.

**Comment by thiagoabreu** [comment] 2019-05-10 02:23
Same problem. I tried the usual DBus workaround I found in other issues (#1360) for no avail.

**Comment by Germoluso** [comment] 2019-05-28 15:28
Can confirm. Accents work fine on Telegram obtained via ppa or .deb package (Ubuntu 16.04), but Telegram on Snap simply cannot reproduce them.

**Comment by vekat** [comment] 2019-06-02 18:39
accents don't work for me either on 18.04, I'm using the regular download version from the website

**Comment by bernardodomingues-hotmart** [comment] 2019-06-05 11:36
This might be a problem with snap itself. I've just tested another app installed via `snap`(Spotify) and had the same problems with accentuated characters.

**Comment by maxan** [comment] 2019-06-30 18:51
Hello, everyone! I'm facing the same problem. I'm using the Telegram 1.7.10 within Linux Mint 19.1 from snap.

**Comment by REIS0** [comment] 2019-07-18 17:13
Same thing here, using telegram desktop from ubuntu repos i have no problems but with snap version, which is more up to date, i can't type any accents.
Telegram 1.7.13 in Pop_OS! 19.04.

**Comment by leandroramos** [comment] 2019-07-21 03:52
Accents work only if we use en-us as system language, which doesn't make any sense.

**Comment by abnersn** [comment] 2019-07-21 17:13
Same problem in Brazilian Portuguese and pt_BR.UTF-8 as LANG.

**Comment by Aokromes** [comment] 2019-08-28 18:53
https://github.com/telegramdesktop/tdesktop/issues/1041

**Closed by Aokromes** 2019-08-28 18:53 UTC
Labels: bug, linux

**Comment by leandroramos** [comment] 2019-10-03 21:34
I think issue #1041 mixes a lot of issues, this should not be closed because it is a snap package exclusive (and very old) issue. This doesn't happen with the tar.gz downloaded from desktop.telegram.org. Different issues.

**Comment by DiogoConstantino** [comment] 2020-01-03 11:30
I agree, even today someone complained to me about it.

**Comment by ilosamart** [comment] 2020-01-03 14:18
This is still a problem in Ubuntu 19.10. I'm removing Telegram snap.

**Comment by leandroramos** [comment] 2020-01-03 14:25
That's why non verified snaps should not appear in the store.

Em sex, 3 de jan de 2020 11:19, Fábio Tramasoli <notifications@github.com>
escreveu:

**Comment by ilosamart** [comment] 2020-01-03 14:29
I dunno if this is the case, since the app is alledgedly from this team: https://snapcraft.io/telegram-desktop .

**Comment by carlosnovaduarte** [comment] 2020-02-13 18:40
This is also happening to me. I have a PT-PT keyboard and my system language is set to EN-US. However I am also not able to use accentuated characters such as 'ã' or 'á'.
