### ISSUE TITLE
Issue submitted via apport

### ISSUE THREAD

**Issue by Articxok** [telegramdesktop/tdesktop#26746] opened 2023-09-03 07:50 UTC
**ProblemType**
Bug

**Date**
Sun Sep  3 09:45:11 2023

**CurrentDesktop**
ubuntu:GNOME

**ProcEnviron**
LANG=it_IT.UTF-8
PATH=(custom, no user)
SHELL=/bin/bash
TERM=xterm-256color
XDG_RUNTIME_DIR=<set>

**DistroRelease**
Ubuntu 23.04

**Uname**
Linux 6.2.0-31-generic x86_64

**Architecture**
amd64

**Snap**
telegram-desktop 4.9.4 (latest/stable)

**SnapChanges**
nessuna modifica trovata

**SnapConnections**
Interfaccia            Spina                              Slot                            Note
alsa                   telegram-desktop:alsa              -                               -
audio-playback         telegram-desktop:audio-playback    :audio-playback                 -
audio-record           telegram-desktop:audio-record      :audio-record                   -
camera                 telegram-desktop:camera            :camera                         -
content[gtk-3-themes]  telegram-desktop:gtk-3-themes      gtk-common-themes:gtk-3-themes  -
content[icon-themes]   telegram-desktop:icon-themes       gtk-common-themes:icon-themes   -
content[sound-themes]  telegram-desktop:sound-themes      gtk-common-themes:sound-themes  -
desktop                telegram-desktop:desktop           :desktop                        -
desktop-legacy         telegram-desktop:desktop-legacy    :desktop-legacy                 -
gsettings              telegram-desktop:gsettings         :gsettings                      -
hardware-observe       telegram-desktop:hardware-observe  -                               -
home                   telegram-desktop:home              :home                           -
mpris                  -                                  telegram-desktop:mpris          -
network                telegram-desktop:network           :network                        -
network-bind           telegram-desktop:network-bind      :network-bind                   -
network-status         telegram-desktop:network-status    :network-status                 -
opengl                 telegram-desktop:opengl            :opengl                         -
removable-media        telegram-desktop:removable-media   -                               -
unity7                 telegram-desktop:unity7            :unity7                         -
wayland                telegram-desktop:wayland           :wayland                        -
x11                    telegram-desktop:x11               :x11                            -

**SnapInfo.telegram-desktop**
name:      telegram-desktop
summary:   Fast. Secure. Powerful.
publisher: Telegram FZ-LLC (telegram-desktop**)
store-url: https://snapcraft.io/telegram-desktop
contact:   https://github.com/telegramdesktop/tdesktop/issues
license:   unset
description: |
  Pure instant messaging — simple, fast, secure, and synced across all your
  devices. One of the world's top 10 most downloaded apps with over 500
  million active users.
  
  FAST: Telegram is the fastest messaging app on the market, connecting
  people via a unique, distributed network of data centers around the globe.
  
  SYNCED: You can access your messages from all your phones, tablets and
  computers at once. Telegram apps are standalone, so you don’t need to keep
  your phone connected. Start typing on one device and finish the message
  from another. Never lose your data again.
  
  UNLIMITED: You can send media and files, without any limits on their type
  and size. Your entire chat history will require no disk space on your
  device, and will be securely stored in the Telegram cloud for as long as
  you need it.
  
  SECURE: We made it our mission to provide the best security combined with
  ease of use. Everything on Telegram, including chats, groups, media, etc.
  is encrypted using a combination of 256-bit symmetric AES encryption,
  2048-bit RSA encryption, and Diffie–Hellman secure key exchange.
  
  100% FREE & OPEN: Telegram has a fully documented and free API for
  developers, open source apps and verifiable builds to prove the app you
  download is built from the exact same source code that is published.
  
  POWERFUL: You can create group chats with up to 200,000 members, share
  large videos, documents of any type (.DOCX, .MP3, .ZIP, etc.) up to 2 GB
  each, and even set up bots for specific tasks. Telegram is the perfect tool
  for hosting online communities and coordinating teamwork.
  
  RELIABLE: Built to deliver your messages using as little data as possible,
  Telegram is the most reliable messaging system ever made. It works even on
  the weakest mobile connections.
  
  FUN: Telegram has powerful photo and video editing tools, animated stickers
  and emoji, fully customizable themes to change the appearance of your app,
  and an open sticker/GIF platform to cater to all your expressive needs.
  
  SIMPLE: While providing an unprecedented array of features, we take great
  care to keep the interface clean. Telegram is so simple you already know
  how to use it.
  
  PRIVATE: We take your privacy seriously and will never give any third
  parties access to your data. You can delete any message you ever sent or
  received for both sides, at any time and without a trace. Telegram will
  never use your data to show you ads.
  
  We keep expanding the boundaries of what you can do with a messaging app.
  Don’t wait years for older messengers to catch up with Telegram — join the
  revolution today.
commands:
  - telegram-desktop
snap-id:      jpdoHqMd90M39DdH2JSZbeQxipqHtwLo
tracking:     latest/stable
refresh-date: 2023-09-01T17:06:20+02:00
channels:
  latest/stable:    4.9.4              2023-08-31T20:44:16Z (4989) 425MB -
  latest/candidate: ^                                                    
  latest/beta:      ^                                                    
  latest/edge:      4.9.4-3-g119f7e757 2023-09-01T09:26:45Z (4993) 425MB -
installed:          4.9.4                                   (4989) 425MB -

**SnapInfo.core22**
name:      core22
summary:   Runtime environment based on Ubuntu 22.04
publisher: Canonical**
store-url: https://snapcraft.io/core22
contact:   https://github.com/snapcore/core-base/issues
license:   unset
description: |
  The base snap based on the Ubuntu 22.04 release.
type:         base
snap-id:      amcUKQILKXHHTlmSa7NMdnXSx02dNeeT
tracking:     latest/stable
refresh-date: 2023-08-30T22:02:54+02:00
channels:
  latest/stable:    20230801 2023-08-30T22:10:06Z (864) 77MB -
  latest/candidate: 20230801 2023-08-03T14:05:28Z (864) 77MB -
  latest/beta:      20230801 2023-08-02T00:05:49Z (864) 77MB -
  latest/edge:      20230823 2023-08-23T10:01:33Z (882) 77MB -
installed:          20230801                      (864) 77MB base

**SnapInfo.gtk-common-themes**
name:      gtk-common-themes
summary:   All the (common) themes
publisher: Canonical**
store-url: https://snapcraft.io/gtk-common-themes
contact:   https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues
license:   unset
description: |
  A snap that exports the GTK and icon themes used on various Linux distros.
snap-id:      jZLfBRzf1cYlYysIjD2bwSzNtngY0qit
tracking:     latest/stable/ubuntu-22.04
refresh-date: 2022-06-29T21:03:03+02:00
channels:
  latest/stable:    0.1-81-g442e511 2022-06-28T18:10:06Z (1535) 96MB -
  latest/candidate: 0.1-81-g442e511 2022-06-24T16:30:46Z (1535) 96MB -
  latest/beta:      0.1-81-g442e511 2022-06-24T16:30:46Z (1535) 96MB -
  latest/edge:      ^                                                
installed:          0.1-81-g442e511                      (1535) 96MB -

**SnapGitOwner**
telegramdesktop

**SnapGitName**
tdesktop

**CrashDB**
snap-github

**Tags**
wayland-session lunar

**UpgradeStatus**
Upgraded to lunar on 2023-08-07 (27 days ago)

**ProcVersionSignature**
Ubuntu 6.2.0-31.31-generic 6.2.15

**ProcCpuinfoMinimal**
processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 126
model name	: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
stepping	: 5
microcode	: 0xbc
cpu MHz		: 3400.000
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 27
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple pml ept_mode_based_exec tsc_scaling
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds mmio_stale_data retbleed eibrs_pbrsb gds
bogomips	: 2380.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

**ApportVersion**
2.26.1-0ubuntu2

**CasperMD5CheckResult**
unknown

**Comment by Articxok** [comment] 2023-09-03 08:01
When writing a message to an Esperanto group, if i write some words with Esperanto letters, the application crashes.

For example it crashed writing "komenciĝos" (when I wrote the "ĝ") or "eĥo" (when I wrote the "ĥ")

Maybe it depends on some spell-checker?
I was able to insert the message in the picture, by writing the whole message without the letter "ĝ", then inserting it and immediately pressing "enter".

![immagine](https://github.com/telegramdesktop/tdesktop/assets/69844703/c82d1ed9-771e-43ac-a8c6-7a33cd94af0a)

But if I try to edit ("Redakti") it, telegram crashes.

**Comment by Aokromes** [comment] 2023-09-03 08:11
i think duplicate of https://github.com/telegramdesktop/tdesktop/issues/26737

**Comment by ilya-fedin** [comment] 2023-09-03 09:06
apport reports to Canonical, so upstream developers can't see what you reported. If you want to report upstream, you can get the binary from http://desktop.telegram.org that has integrated crash reporter and provide the crash id. Although it's likely a duplicate, yes.

**Closed** 2023-09-03 09:07 UTC

**Comment by susphir** [comment] 2023-09-03 09:58
Would be great to share the screen of the entire team to celebrate Labor
Day Massacre Celebration!! I support this idea in the name of them push to
jump but leave your save a life vest to the ones that need it the most
🤠🤠🤠 Howdy Lone Star State! Why ignoring l de tras??
