### ISSUE TITLE
Allow to play video without full screen.

### ISSUE THREAD

**Issue by krasoffski** [telegramdesktop/tdesktop#4369] opened 2018-01-31 13:38 UTC
### Steps to reproduce
1. Send any video in the chat.
2. Press play icon on the video.

### Expected behaviour
There is ability to play video full screen or play within telegram chat window (minimized or embedded) like e.g. gif image.

### Actual behaviour
Video is showed full screen without ability to embed or minimize like in the mobile client.

**Comment by Aokromes** [comment] 2018-02-02 19:16
#1710

**Comment by Aokromes** [comment] 2018-02-02 19:19
Also maybe:
https://github.com/telegramdesktop/tdesktop/pull/3021
https://github.com/telegramdesktop/tdesktop/issues/2349#issuecomment-354831540

**Comment by krasoffski** [comment] 2018-02-03 09:55
The issue above looks like this, but a little different.
The idea is to able to play video e.g. embedded like gif w/o full screen.

**Comment by tdesktop-closer** [comment] 2019-04-03 23:46
Hey there!

We're automatically closing this issue since there was no activity in this issue since 398 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

<sub>(Please note that this is an [automated](https://github.com/auchri/github_auto_closer) comment.)</sub>

**Comment by krasoffski** [comment] 2019-04-04 07:09
I am still waiting this functionality.

**Comment by Aokromes** [comment] 2019-04-04 09:40
it's duplicate of #1710

**Comment by krasoffski** [comment] 2019-04-05 13:06
To be honest this issue is not the same. In the issue above user requested ability to click on image.
I my case I am requesting to play videos within a chat like for example as gif.

**Comment by thedutchess** [comment] 2019-08-01 10:59
I would also like to see this functionality. I use Telegram Desktop in compact mode, as small as it will go, and when playing videos it completely takes over my screen. Please add an option where the user can set their preference whether to play videos full-screen or in the chat window.

**Comment by dvborzov** [comment] 2019-08-11 16:34
t’s very inconvenient to work when the video is in full screen, sometimes you need to compare 2 forms and for this you have to open it in a third-party player

**Comment by nikserg** [comment] 2019-12-30 07:56
Need this feature so much!

**Comment by cen3fuga** [comment] 2020-01-07 13:31
I would also appreciate this feature. 
For a long time now, I avoid playing videos at all...
Thank you!

**Comment by Aokromes** [comment] 2020-02-05 17:50
comming soon on 1.9.10
https://github.com/telegramdesktop/tdesktop/commit/ca5c9271a3c1a89ca019c9fb1fc98e1145465ee4

**Comment by Aokromes** [comment] 2020-02-06 09:00
https://github.com/telegramdesktop/tdesktop/releases/tag/v1.9.10

**Closed by Aokromes** 2020-02-06 09:00 UTC
Labels: enhancement

**Comment by krasoffski** [comment] 2020-02-06 10:21
@Aokromes 
Many thanks!
Is it possible to make picture-in-picture mode by default for playing videos w/o every time pressing?

**Comment by nikserg** [comment] 2020-02-10 14:54
Have anyone tried this feature yet? I can't find this settig.

**Comment by Aokromes** [comment] 2020-02-10 15:22
> Have anyone tried this feature yet? I can't find this settig.

it's not setting, it's button.

https://i.imgur.com/KDZAmDa.png

**Comment by krasoffski** [comment] 2020-02-11 05:53
@Aokromes 
Yea, I know this. Just an options It would be great to switch picture-in-picture by default when pressing play video button. 
Now press play video -> video maximized full screen -> press button picture in picture.
Improvement is:  press play video -> video picture in picture without full screen (option in configuration)

**Comment by nikserg** [comment] 2020-02-11 06:09
> > Have anyone tried this feature yet? I can't find this settig.
> 
> it's not setting, it's button.
> 
> https://i.imgur.com/KDZAmDa.png

Thats strange, I don't have this button: https://imgur.com/a/wk4QJcW

**Comment by Aokromes** [comment] 2020-02-11 06:14
> > > Have anyone tried this feature yet? I can't find this settig.
> > 
> > 
> > it's not setting, it's button.
> > https://i.imgur.com/KDZAmDa.png
> 
> Thats strange, I don't have this button: https://imgur.com/a/wk4QJcW
> Version 1.9.9

like i said, coming soon on 1.9.10. you need to update to 1.9.11.

**Comment by nikserg** [comment] 2020-02-11 06:17
> > > > Have anyone tried this feature yet? I can't find this settig.
> > > 
> > > 
> > > it's not setting, it's button.
> > > https://i.imgur.com/KDZAmDa.png
> > 
> > 
> > Thats strange, I don't have this button: https://imgur.com/a/wk4QJcW
> > Version 1.9.9
> 
> like i said, coming soon on 1.9.10. you need to update to 1.9.11.

Thanks, it works in beta version!

**Comment by farshad007** [comment] 2020-02-22 04:44
> 
> 
> @Aokromes
> Many thanks!
> Is it possible to make picture-in-picture mode by default for playing videos w/o every time pressing?

That would be nice.
Please consider it.

cheers

**Comment by netocavalcanti** [comment] 2021-02-10 23:09
Please give us an option to play the video without having to go full screen.

**Comment by krasoffski** [comment] 2021-02-12 08:58
It seems like we need to open new defect for this:

> Please give us an option to play the video without having to go full screen.

**Comment by krasoffski** [comment] 2021-02-12 09:07
> Please give us an option to play the video without having to go full screen.
It seems like we need to open new defect.

**Comment by nikserg** [comment] 2021-02-12 11:12
It's better now, but not satisfies what was described in issue: to play video embeded, like GIFs. It still opens full-screen in separate window, and then you can minimize it in small overlaying window.
We need embeded video, not separated window.
