### ISSUE TITLE
Telex stops working on version Telegram Desktop version 3.2

### ISSUE THREAD

**Issue by ngtrhieu** [telegramdesktop/tdesktop#17194] opened 2021-11-04 15:10 UTC
### Steps to reproduce

1. On OS, Install/Upload Telegram Desktop to version 3.2
2. Go to System Preference > Keyboard > Input Sources and add Vietnamese (Simple Telex)
3. Go to chat box in Telegram, try typing `chafo bajn` or any Vietnamese phrase (if you know how to type)
4. Try backspace

### Expected behaviour

Expect to see the text rendered to `chào bạn`.

### Actual behaviour

Doesn't render properly at each keystroke.

### Operating system

MacOS Big Sur 11.6

### Version of Telegram Desktop

3.2

### Installation source

Static binary from official website

**Comment by hieuhtr** [comment] 2021-11-05 04:40
Same for `VNI` input source. We can go Keyboard setting for reproducing issue.

MacOS Catalina

<img width="780" alt="image" src="https://user-images.githubusercontent.com/10110737/140458984-0de02d73-523d-4324-83c6-381f93c7a2a3.png">

**Comment by ilya-fedin** [comment] 2021-11-05 05:01
Sounds as a duplicate of #17176

**Closed** 2021-11-05 06:50 UTC
Labels: bug

**Comment by john-preston** [comment] 2021-11-15 05:27
@ngtrhieu  Can you please check this version: https://td.telegram.org/tmac/tsetup.3.2.5.dmg

Does it work fine?

**Comment by ngtrhieu** [comment] 2021-11-15 05:31
@john-preston I just tested. It is working fine now. Thank all for updating.

![Screenshot 2021-11-15 at 1 30 53 PM](https://user-images.githubusercontent.com/8876396/141727615-e32308af-6396-4874-8aba-78bc26d7138f.png)

![Screenshot 2021-11-15 at 1 30 44 PM](https://user-images.githubusercontent.com/8876396/141727637-5a73139d-4361-48d1-bbf4-321532db15e7.png)
