### ISSUE TITLE
Dark title bar when use dark theme

### ISSUE THREAD

**Issue by nguyenkien** [telegramdesktop/tdesktop#7863] opened 2020-05-10 17:03 UTC
Window title bar remain light even if I use telegram dark theme

![Screenshot from 2020-05-11 00-03-34](https://user-images.githubusercontent.com/1940081/81505645-04135f80-931b-11ea-9bc3-08d5578e3176.png)

If I manually run command `xprop -f _GTK_THEME_VARIANT 8u -set _GTK_THEME_VARIANT "dark"` I can change title bar to dark UI

![Screenshot from 2020-05-11 00-03-27](https://user-images.githubusercontent.com/1940081/81505639-fbbb2480-931a-11ea-903b-8565c895d90f.png)

### Expected behaviour
Switch to dark titlebar when use dark theme

### Configuration
**Operating system:**
- Debian 10, Gnome

**Version of Telegram Desktop:**
- 2.1.4

**Installation source (Linux Only)** 
- the official website

**Comment by ilya-fedin** [comment] 2020-05-10 17:10
Telegram is written on Qt, i can't use Gtk APIs

**Comment by ilya-fedin** [comment] 2020-05-10 17:15
Sounds like a duplicate of #5714

**Comment by nguyenkien** [comment] 2020-05-10 17:25
> Telegram is written on Qt, it can't use Gtk APIs

I see telegram use gtk title bar on gnome, so I think it could switch to dark theme when needed

**Comment by ilya-fedin** [comment] 2020-05-10 17:27
> I see telegram use gtk title bar on gnome

Telegram doesn't use gtk title bar, window manager of your DE renders the title bar

**Closed** 2020-05-13 17:53 UTC
