### ISSUE TITLE
[Fedora KDE X11] Screen sharing only works once, and then I have to kill telegram and open it up again to share again

### ISSUE THREAD

**Issue by pizzadude** [telegramdesktop/tdesktop#16513] opened 2021-06-27 23:55 UTC
This is on Fedora 34 KDE on X11 with the Telegram flatpak.

### Steps to reproduce
1. Use X11
2. Start screen sharing and stop screen sharing
3. Can no longer screen share until you restart telegram

### Expected behaviour
Screen sharing should work after stopping and starting it again, without restarting telegram.

### Actual behaviour
Screen sharing only works once, and then I have to kill telegram and open it up again to share again.

### Configuration
**Operating system:**

Fedora 34 KDE

**Version of Telegram Desktop:**

2.8.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

Flatpak

**Used theme**:

Default dark theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment] 2021-06-27 23:57
@Aokromes can you close the issue since template was removed?

**Comment by pizzadude** [comment] 2021-06-28 00:05
@ilya-fedin My apologies, I added the template.

**Comment by ilya-fedin** [comment] 2021-06-28 00:07
>     3\. Can no longer screen share until you restart telegram

Can you add more details? Why you can't?

**Comment by pizzadude** [comment] 2021-06-28 00:10
> > 1. Can no longer screen share until you restart telegram
> 
> Can you add more details? Why you can't?

For some reason I can't reproduce this issue all the time. When I can reproduce it, the screen share button does nothing after picking a screen / window, and only worked until I restarted telegram again.

**Comment by ilya-fedin** [comment] 2021-06-28 00:11
I can't reproduce, the button works for me all the time

**Comment by pizzadude** [comment] 2021-06-28 00:12
I have a friend who uses Gnome and X11 and he had this issue also, but now he doesn't anymore. No version update either.

**Comment by ilya-fedin** [comment] 2021-06-28 00:12
maybe this was a problem on server side?

**Comment by pizzadude** [comment] 2021-06-28 00:13
That would make sense, but I don't know.

**Comment by swiperflue** [comment] 2021-06-28 00:14
Same, I experienced this bug once, but can't reproduce it now.
I tried to record a video showing it, but suddenly everything works now.

**Comment by ilya-fedin** [comment] 2021-07-05 04:13
Could the issue be closed?

**Closed** 2021-07-05 09:03 UTC
