### ISSUE TITLE
Don't put the window in full-screen mode

### ISSUE THREAD

**Issue by rock59** [telegramdesktop/tdesktop#1710] opened 2016-02-29 20:44 UTC
When a user clicks on an image to load that, the window is placed in full-screen mode. If the user have a low-speed connection, he/she will not be able to access other applications until the image loads completely or the user must cancel loading the image to access other applications
Please don't put the windows in full-screen or at least place a minimize button somewhere in image loader window
Thanks

**Comment by DiThi** [comment] 2016-08-09 13:13
I have a problem with this for a different reason: my monitor is huge 4K and all the pictures are tiny in the middle. There should be an option to have the image viewer limited to the application window, so I'll maximize the window myself if I want them bigger. Related: #1111

**Comment by auchri** [comment] 2016-11-14 16:14
#2349

**Comment by DiThi** [comment] 2016-11-14 17:10
@auchri It's not a duplicate. This is about the photo viewer, the other one is for the video player. The problems of both OP and me are also different.

**Comment by MELCHEZEDEK776** [comment] 2017-03-28 19:17
My Waves and JesusCoins and other assets disappeared from Waves wallet .. any ideas ?

**Comment by Mistero5050** [comment] 2017-05-28 12:46
This is still a bug in telegram.
(I'm using Windows 10 last stable version)

**Comment by stek29** [comment] 2017-05-28 13:16
@Mistero5050 well, technically speaking it's a feature :D

**Comment by ChrisHeerschap** [comment] 2018-04-05 22:26
This is really, really annoying... taking over the screen to display a tiny image and then having to mouse over to the X to close it is just bad. Most chat clients will open it within the window. Having the option to go full screen is nice, but mandating it and not giving any other option?

**Comment by ArmeF97** [comment] 2018-04-06 07:14
@john-preston , not in linux. In linux you can't close the picture, and you're stuck

**Comment by john-preston** [comment] 2018-04-06 07:55
@ArmeF97 I tested it in Ubuntu and if I click on an image it shows in a viewer, then I click on the image in the viewer, and the viewer is closed.

**Comment by ArmeF97** [comment] 2018-04-06 07:57
@john-preston  on xubuntu it crashes. I can make a video if you don't believe me

**Comment by john-preston** [comment] 2018-04-06 08:07
@ArmeF97 I'll try. Which version of Xubuntu do you use? Do you use tdesktop binary from https://desktop.telegram.org?

**Comment by ArmeF97** [comment] 2018-04-06 08:34
@john-preston , 
Telegram 1.2.15 from official site
XFCE 4.12

```
arme@demorgan:~$ uname -a
Linux demorgan 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by john-preston** [comment] 2018-04-06 10:03
@ArmeF97 I can't reproduce that. I took Xubuntu 16.04 from the official site, installed it, downloaded Telegram from https://desktop.telegram.org, launched, logged in, clicked on a photo once - it opened in a viewer, clicked on it in the viewer — it closed back.

**Comment by ChrisHeerschap** [comment] 2018-04-06 16:10
@john-preston in Mac OS if I click anywhere but the X it cycles through images in the current conversation. I was expecting the "click anywhere but the image to close" behavior and that would have made the full screen a little less annoying.

Hmm, testing more and I find that if I click _under_ the image, or to the right of the image, yes, it does close it. Clicking to the left of the image, either above or below the image but clear of it to the left causes it to cycle through previous images in the conversation.

If I have the window on  the left, then my mouse is there to begin with so it defaults to cycling. Moving the window to the right corner of the screen gets the "click off the image to close" to work. That still leaves the same issue @DiThi mentions of taking over my high-res screen to display a 100px image, and honestly, having the inconsistent action of cycling to the left and closing to the right is counterintuitive.

So, moving my window from the left corner to the right corner "fixes" this bug, but that's not what I would consider a proper fix. 😜

**Comment by ChrisHeerschap** [comment] 2018-04-06 16:11
Jeez, testing out @ArmeF97 's case of changing to another app with CMD-tab (Mac OS) and I can switch away without it crashing, but it puts the opened image _over_ the app list that appears with CMD-Tab, so I'm switching blind.

**Comment by john-preston** [comment] 2018-04-06 16:14
@ChrisHeerschap In macOS do you use Telegram Desktop or another macOS Telegram app? I guess the second.

You can try Telegram Desktop (this repository) from https://desktop.telegram.org

**Comment by ChrisHeerschap** [comment] 2018-04-06 16:29
Yep, I was using the Telegram app. Installed Telegram Desktop and images close as described. CMD-Tab also works as expected.

Still disagree with the mandatory full screen, but I'm less annoyed by it now. Thanks!

**Comment by ArmeF97** [comment] 2018-04-06 23:25
@john-preston , I don't know if my issue #3144 is a duplicate of this. If not, I hope you'll come to comment mine, but. If it's a duplicate. Let's discuss it here. I can make a video, maybe tomorrow I'll do that

**Comment by ArmeF97** [comment] 2018-12-24 10:13
Update, I've done the video https://www.youtube.com/watch?v=QzqPQ5yAbSU&feature=youtu.be

**Comment by hazzus** [comment] 2019-02-14 20:25
Anybody is going to do this? It's really annoying I can't watch photos or videos and do something in another window!

**Comment by memboc** [comment] 2019-04-01 09:34
I agree full screen sometimes is not comfortable and annoying. Especially relevant for music videos. Can you make switch button to floating video (pip window) like in Android client?

**Comment by memboc** [comment] 2019-04-01 09:35
@auchri

**Comment by kirsan31** [comment] 2020-02-08 09:26
@john-preston Any chance new (1.9.10) PiP viewer will be used for images too?

**Comment by agmemon10** [comment] 2020-02-16 02:09
this issue is extremely annoying. i keep the telegram app and my browser app side by side, but whenever I click on a picture, my whole monitor becomes useless until i exit out from the picture, which in turn makes the picture too small for me to see properly. i'm left with maximizing the picture, exiting, going to my browser window to search some term related to the picture, etc. etc.

**Comment by kirsan31** [comment] 2020-02-18 09:28
Because in TD video and picture viewer basically the same thing. I think we need to rename this issue to something like:

> Don't put the **media viewer** window in full-screen mode.

cc @Aokromes 

People want to be able see and list (navigate back/forward) all there media without going to full screen, and navigate to F.S. only if needed.  And I am afraid, that new PiP video player was designed for other things...

**Comment by Aokromes** [comment] 2020-02-18 10:35
> Because in TD video and picture viewer basically the same thing. I think we need to rename this issue to something like:
> 
> > Don't put the **media viewer** window in full-screen mode.
> 

my permissions doesn't allows to do it.

**Comment by kirsan31** [comment] 2020-02-18 10:39
> > Because in TD video and picture viewer basically the same thing. I think we need to rename this issue to something like:
> > > Don't put the **media viewer** window in full-screen mode.
> 
> my permissions doesn't allows to do it.

Oh :( thanks any way.

cc @rock59

**Comment by Ares9323** [comment] 2020-03-30 16:47
The fact this issue is still open from 2016 makes me a little sad..
Fortunately I have a second monitor and I can view a picture while writing in another! (I've been doing this for years)
I hoped this will get fixed one day!

**Comment by kouhe3** [comment] 2020-03-31 13:19
OK
It's tg 6.0 now, I don't know why this feature has not been added for 4 years. But this problem is really inconvenient.

**Comment by dayvough** [comment] 2020-04-21 07:33
This really is quite an issue as I need to copy text from images but I can't even use Spotlight as it gets in the way. This needs to be changed and should use Quick Look instead.

**Comment by mvxxx** [comment] 2020-05-05 20:13
@kouhe3 is right. It should have been added long time ago.

**Comment by wanderseeme** [comment] 2020-05-28 12:19
Yes please add an option to open the media viewer in windowed mode! The full screen media viewer is always so frustrating!

**Comment by thethinker990** [comment] 2020-07-02 12:33
This is super annoying. I want to open a picture and compare it to another, this is not possible. I have to download the picture(s) and compare them side by-side with my picture-viewer. It would be nice if this is boxed or limited to the Telegram window.

**Comment by init4** [comment] 2020-07-14 07:26
+1 please get rid of the full screen image viewer, it sucks

**Comment by kxjhwbb** [comment] 2020-11-10 04:21
+1 please!!!

**Comment by AhyaH-YHWH** [comment] 2020-11-13 11:14
yes, This Fullscreen when I open an image Just disable me from Multi Tasking on Windows 10

I want to open a Photo/Video in Telegram, and without closing it use other Apps, 
\while the Photo/Video is just filling frames of Telegram Desktop, that is half of my screen or less

This happens A lot

**Comment by rock59** [comment] 2020-11-13 15:06
This is super annoying with slow and busy MTProto proxies

**Comment by nathanredblur** [comment] 2020-12-06 14:40
And additional will be great that when you go back and next in media viewer you can change between gifs too.

**Comment by mayeaux** [comment] 2021-01-30 09:11
Full screen is a really bad feature. It makes it so you have to use your entire monitor to view a video a fraction of the size, terrible use of space, and terrible user experience as it makes it impossible to click between tabs and applications without the video stopping playing. Most people on the web do not watch their videos as full screen by default. Honestly, I would consider this functionality borderline broken considering its impact on user experience. The only workaround is to download a video in its entirety, and then open with Quicktime (for example). Hardly a solution.

The video should by default take the width of the Telegram app's window size. And then there should be a button to toggle fullscreen.

**Comment by stefanheijnen** [comment] 2021-08-11 07:50
I was trying out TG desktop today, but I switched back to the web version because of this issue. I have a large 4k wide screen. I use info from images from tg to work with in another app.

**Comment by tarocco** [comment] 2022-01-29 02:27
The full-screen picture viewer doesn't play nicely with programs like XSOverlay used for seeing windows on your computer while in VR games/applications.

**Comment by mvxxx** [comment] 2022-01-29 11:05
This issue has been 6 years. Does it really need so much time to fix that?

**Comment by mayeaux** [comment] 2022-01-31 00:15
![Screen Shot 2022-01-31 at 1 14 41 AM](https://user-images.githubusercontent.com/7200471/151723916-24c5d793-8d5f-46dd-8ac1-5fe536ef2b2a.jpg)
Turns out you can click this button to make the video no longer take up the entire screen, it works for me, doesn't really bother me anymore.

**Comment by ronaldpoi** [comment] 2022-01-31 18:53
It still doesn't work for images, just videos. And usability is terrible. You can't dismiss it with ESC. Instead, the OTHER window, the main chat list, gets the ESC input and closes the current conversation. At this point, I have no hopes of Telegram doing anything properly.

**Comment by john-preston** [comment] 2022-01-31 19:22
@ronaldpoi This is called Picture-in-Pictute. It is not supposed to receive input, it is supposed to let you watch anything in the background while still doing whatever.

**Comment by fauzie811** [comment] 2022-03-18 08:07
I can't believe this is still open. Just, WHY???

**Comment by ScienceDiscoverer** [comment] 2022-03-27 13:08
How is this not solved yet?

**Comment by infonut** [comment] 2022-04-11 03:58
Hi,
This looks to have been a reported issue since 2016 - now 6 years! Why has this never been addressed?

It is like a stone in my shoe - I am growing more and more irritated. 

Can you please, please fix this bug so TG desktop - both app and web - will play a video in the log stream vs opening to full screen? I feel like I am being put in jail. I REALLY want to listen to the video but it is like being slammed in the face - can't do anything else on the whole computer. 
Who has time for that?!?!?!
I am not saying this idly. I don't want to leave TG, but I am going to if this is not fixed. It's just so basic and SO irritating. I can't stand it any more. Better to not see it than to see it and not be able to play it b.c I don't have time to sit like a zombie in front of my screen and just listen to a video. 

If nothing else, could someone from TG please respond? Why has this never been addressed?

thank you.

**Comment by Ares9323** [comment] 2022-04-11 07:00
> Hi, This looks to have been a reported issue since 2016 - now 6 years! Why has this never been addressed?
> 
> It is like a stone in my shoe - I am growing more and more irritated.
> 
> Can you please, please fix this bug so TG desktop - both app and web - will play a video in the log stream vs opening to full screen? I feel like I am being put in jail. I REALLY want to listen to the video but it is like being slammed in the face - can't do anything else on the whole computer. Who has time for that?!?!?! I am not saying this idly. I don't want to leave TG, but I am going to if this is not fixed. It's just so basic and SO irritating. I can't stand it any more. Better to not see it than to see it and not be able to play it b.c I don't have time to sit like a zombie in front of my screen and just listen to a video.
> 
> If nothing else, could someone from TG please respond? Why has this never been addressed?
> 
> thank you.

You can already do it with videos, as I said in my comment there's a hidden setting to use an external player (go to settings and type "videoplayer" in the nothing, not joking, I discovered this recently and I don't know why this is not a public setting)

The problem still remains for pictures and that's just terrible since I can't even see them correctly

**Comment by ronaldpoi** [comment] 2022-04-11 23:17
> there's a hidden setting to use an external player

A hidden setting is not a real solution. Not complaining about your alternative approach. Just saying the Telegram should really improve the UX of the app.

**Comment by jmorgannz** [comment] 2022-04-11 23:25
> > there's a hidden setting to use an external player
> 
> A hidden setting is not a real solution. Not complaining about your alternative approach. Just saying the Telegram should really improve the UX of the app.

Seems a bit entitled to be honest.  
I'm all for giving deveopers constructive feedback. 
But IMHO expectations 'they should', and threats 'I'm leaving if its not fixed' are way out of line.
As a developer if someone treated my free time this way, I'd suggest they go create a PR to implement it themself.

**Comment by Artyom-K** [comment] 2022-07-24 13:25
This is also a problem for me when I use PIP in Firefox for most of the ultrawide screen and use Telegram on the rest of the screen. When I open an image in Telegram it opens underneath the floating video from Firefox.

**Comment by RaSan147** [comment] 2022-08-06 14:07
> @ronaldpoi This is called Picture-in-Pictute. It is not supposed to receive input, it is supposed to let you watch anything in the background while still doing whatever.

at least kindly make a button to disable STAY ON TOP (like any other media player software)
should be a easy task...

**Comment by profcaju** [comment] 2022-08-12 18:03
> I was trying out TG desktop today, but I switched back to the web version because of this issue. I have a large 4k wide screen. I use info from images from tg to work with in another app.

Thanks for the tip. Using web version don't full screen every image I open :D

**Comment by just-a-boy** [comment] 2022-09-26 07:41
> When a user clicks on an image to load that, the window is placed in full-screen mode. If the user have a low-speed connection, he/she will not be able to access other applications until the image loads completely or the user must cancel loading the image to access other applications Please don't put the windows in full-screen or at least place a minimize button somewhere in image loader window Thanks

no body from the developer doing it. is there any way we can contact developer to address this simple problem or do we have to fork the source code and develop ourself?

**Comment by ii7ussieN** [comment] 2022-12-21 19:56
I use [url=https://apps.microsoft.com/store/detail/unigram—telegram-for-windows/9N97ZCKPD60Q?hl]Unigram[/url] it's like a client for telegram, it's free and safe (you can open pics without full-screen

**Comment by ii7ussieN** [comment] 2022-12-21 19:58
I use unigram, it's a client for telegram on Microsoft store (you can open pics without full screen)
https://apps.microsoft.com/store/detail/unigram—telegram-for-windows/9N97ZCKPD60Q?hl

**Comment by endrift** [comment] 2023-01-23 03:22
This is, and has always been, an anti-feature. It also breaks horribly on multi-monitor.

**Comment by sheldonrrr** [comment] 2023-02-10 02:47
This is a problem for me, too.

**Comment by Aokromes** [comment] 2023-02-18 18:20
https://github.com/telegramdesktop/tdesktop/commit/5d9383b8e4fe33cdb706a4f50cce1aff146ad0b2

**Closed by Aokromes** 2023-02-18 18:20 UTC
Labels: enhancement

**Comment by Aokromes** [comment] 2023-03-21 18:34
works for me (TM) on 4.7.

**Comment by 1111Al** [comment] 2023-03-21 20:06
> 

I've 4.7, I can just maximixe it, there is not an option/button to enter fullscreen
