### ISSUE TITLE
Linux settings under ~/.TelegramDesktop

### ISSUE THREAD

**Issue by Trippler** [telegramdesktop/tdesktop#219] opened 2014-10-26 11:22 UTC
The linux settings are currently located under ~/.TelegramDesktop
They should be located under ~/.local/share/TelegramDesktop OR ~/.config/TelegramDesktop

~/.local/share/ is for user data
~/.config/ is for configuration files
~/.cache/ is for non-essential data files

**Comment by bil-elmoussaoui** [comment] 2015-08-15 22:01
this is the same as #624

**Comment by auchri** [comment] 2015-08-15 22:03
Duplicate of #107

**Closed** 2015-08-15 22:03 UTC
