### ISSUE TITLE
Not Updating - Not Connecting when update available

### ISSUE THREAD

**Issue by sks1123** [telegramdesktop/tdesktop#7732] opened 2020-04-27 09:31 UTC
The Desktop version on Windows 10 64 bits is causing issues.
1. It seems when new update is available, the program acts up. The 'Connecting' message keeps showing and messages outgoing and incoming is sporadic.
2. In earlier versions 'Update' button used to be visible in bottom left, but now it is not so.
3. Every few days this 'Connecting' issues comes up and the whole program needs to be reinstalled.

**Comment by Aokromes** [comment] 2020-06-04 09:51
cannot reproduce myself.

**Comment by Aokromes** [comment] 2020-07-18 23:18
no answer for more than 1 month, closing.

**Closed by Aokromes** 2020-07-18 23:18 UTC
Labels: waiting for answer
