### ISSUE TITLE
Telegram crashes while playing video and activating window mode

### ISSUE THREAD

**Issue by brmmm3** [telegramdesktop/tdesktop#25435] opened 2022-11-25 04:23 UTC
Since one of the latest updates Telegram video playback always starts in full screen mode (first bug). When I activate window mode for video playback Telegram crashes (second bug). This happens always.

OS is Kubuntu Linux 22.04.

**Comment by brmmm3** [comment] 2022-11-25 04:53
Disabling OpenGL solves the issue.

**Comment by ilya-fedin** [comment] 2022-11-25 06:10
@Aokromes can you close this due to the lack of template?

**Comment by MrSwed** [comment] 2022-11-25 06:44
ubuntu 20, kubuntu 22
4.3.2, 4.3.3 - the problem is still there.
downgrade to 4.3.1 helped

**Closed** 2022-11-25 07:34 UTC

**Comment by Aokromes** [comment] 2022-11-25 07:37
also, it's duplicated.

**Comment by MrSwed** [comment] 2022-11-25 08:01
where is the link to the duplicate issue?
