### ISSUE TITLE
Calls Protocol V11.0.0 not working when P2P is disabled

### ISSUE THREAD

**Issue by Laky-64** [telegramdesktop/tdesktop#27660] opened 2024-03-28 15:21 UTC
### Steps to reproduce

Just try to use Call Protocol V11.0.0 in Relay Mode (With p2p not allowed) and with Signaling V2

### Expected behaviour

Should also work on Call Protocol V11also work

### Actual behaviour

Not Connecting and keeps locked on "key exchanging"

### Operating system

Windows

### Version of Telegram Desktop

4.15.2

### Installation source

Static binary from official website

### Logs

```shell
2024-3-28 16:3:39:741 (turn_port.h:68): Attempt to use TURN to connect to port 596
2024-3-28 16:3:39:741 (basic_port_allocator.cc:1700): Failed to create relay port with 91.108.13.x:596
2024-3-28 16:3:39:741 (basic_port_allocator.cc:1670): Server and local address families are not compatible. Server address: 2001:b28:f23d:x:x:x:x:x Local address: 192.168.1.x
2024-3-28 16:3:39:741 (turn_port.h:68): Attempt to use TURN to connect to port 597
2024-3-28 16:3:39:741 (basic_port_allocator.cc:1700): Failed to create relay port with 91.108.9.x:597
2024-3-28 16:3:39:741 (basic_port_allocator.cc:1670): Server and local address families are not compatible. Server address: 2001:67c:4e8:x:x:x:x:x Local address: 192.168.1.x
2024-3-28 16:3:39:741 (turn_port.h:68): Attempt to use TURN to connect to port 598
2024-3-28 16:3:39:741 (basic_port_allocator.cc:1700): Failed to create relay port with 91.108.17.x:598
```

**Comment by Aokromes** [comment] 2024-03-28 15:52
As Telegram official apps don’t currently use calls protocol v11 I’m closing this ticket as it’s not a bug.

**Closed by Aokromes** 2024-03-28 15:52 UTC
Labels: bug
