### ISSUE TITLE
Notification interaction doesn't do anything

### ISSUE THREAD

**Issue by gianmarcogg03** [telegramdesktop/tdesktop#16408] opened 2021-06-05 15:43 UTC
### Steps to reproduce
1. Getting any kind of notification from Telegram
2. Clicking on it or on a button to mark as read or reply

### Expected behaviour
It should do the respective actions.

### Actual behaviour
The notification acts like it's doing the action but it actually does nothing.

### Configuration
**Operating system:** Arch Linux with kernel 5.12.6-zen1-1-zen

**Version of Telegram Desktop:** 2.7.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: pacman

**Used theme**: night theme

**Comment by ilya-fedin** [comment] 2021-06-06 01:03
Your steps to reproduce are wrong, can't reproduce with them, works just fine.

**Comment by Aokromes** [comment] 2021-06-06 13:25
can you try downloading from desktop.telegram.org ?

**Comment by gianmarcogg03** [comment] 2021-06-06 20:03
That didn't solve the issue.

**Comment by ilya-fedin** [comment] 2021-06-07 07:11
> That didn't solve the issue.

Please provide correct reproduction steps or the issue will be closed

**Comment by gianmarcogg03** [comment] 2021-06-07 07:38
They are correct, just do anything with a notification and it won't work.

**Comment by ilya-fedin** [comment] 2021-06-07 07:40
You definitely miss something since it works on my machine

**Comment by gianmarcogg03** [comment] 2021-06-07 07:51
Do you have any idea of what could be wrong with my system? You are the dev here.

**Comment by ilya-fedin** [comment] 2021-06-07 07:56
> Do you have any idea of what could be wrong with my system?

You haven't provided any info about your system except of useless kernel version

**Comment by gianmarcogg03** [comment] 2021-06-07 08:01
What info do you need?

**Comment by ilya-fedin** [comment] 2021-06-07 08:02
DE/WM, notification daemon at least the state of 'Use native notifications' option

**Comment by gianmarcogg03** [comment] 2021-06-07 08:04
KDE Plasma 5.21.5 with KWin and Plasma's own notification system.

**Comment by ilya-fedin** [comment] 2021-06-07 08:11
Still can't reproduce. When I click on the notification itself, the window is raised, when I click on 'Mark as read', the chat is marked as read (without window focus, of course).

**Comment by ilya-fedin** [comment] 2021-06-07 10:48
Waiting for more info or the issue will be closed

**Comment by ilya-fedin** [comment] 2021-06-11 05:44
@Aokromes looks like @gianmarcogg03 specially ignores the information request, I don't think it's worth to wait 3 days

**Comment by gianmarcogg03** [comment] 2021-06-11 09:16
You didn't ask me what info you need.

**Comment by ilya-fedin** [comment] 2021-06-11 09:22
> You didn't ask me what info you need.

You should provide valid reproduction steps that I can do and see your bug. If I can't reproduce them, it means you miss something, I can't know how you customized your system and can't suggest what you should check. If you don't know as well, that means you should create a VM with a clean system and reproduce in it, then, if you still don't understand what you miss, you can send its image to me (I use VirtualBox, so it should have format that VirtualBox can read), so that I can just run it and see the bug.

**Comment by ilya-fedin** [comment] 2021-06-11 09:36
Should I wait for new reproduction steps/VM image or you just silently ignore my message again?

**Comment by gianmarcogg03** [comment] 2021-06-11 09:37
I'm trying with a VM, give me time!

**Comment by ilya-fedin** [comment] 2021-06-11 09:38
Ok. Just want to know because I waited 4 days an answer from you.

**Comment by gianmarcogg03** [comment] 2021-06-11 09:51
I tried on a Manjaro KDE VM, installed Telegram Desktop via pacman and notifications seem to work perfectly there.

**Comment by ilya-fedin** [comment] 2021-06-11 09:55
Yeah, it's some tweaks in your system...

**Comment by gianmarcogg03** [comment] 2021-06-11 10:00
![image](https://user-images.githubusercontent.com/28053717/121669337-81744b00-caac-11eb-9948-95ba1732676c.png)
I tried to get logs from Plasma and TG and now the notifications work. They like to work and not work at random apparently and these logs aren't helping.

**Comment by ilya-fedin** [comment] 2021-06-11 10:01
Maybe it's some bug in Plasma then?

**Comment by ilya-fedin** [comment] 2021-06-11 10:03
Also, TG doesn't log to output, TG logs to log.txt file in profile directory (typically, `~/.local/share/TelegramDesktop`)

**Comment by gianmarcogg03** [comment] 2021-06-11 10:05
[log.txt](https://github.com/telegramdesktop/tdesktop/files/6637561/log.txt)
Here it is, in the meanwhile I will try to upgrade my system, maybe this will also update Plasma and get some bugs fixed up hopefully.

**Comment by ilya-fedin** [comment] 2021-06-11 10:08
It is, but it seems ok, it contains only errors about incorrect server messages, but nothing wrong about notifications. I think it's a Plasma bug most likely.

**Comment by ilya-fedin** [comment] 2021-06-11 10:11
You can monitor dbus socket with Bustle to see what happens when you click a button on notification. Usually it should throw an ActionInvoked signal.

**Closed** 2021-07-14 20:09 UTC
Labels: waiting for answer
