### ISSUE TITLE
-startintray on Ubuntu 17.04 doesn't open window

### ISSUE THREAD

**Issue by tonyedgecombe** [telegramdesktop/tdesktop#3391] opened 2017-05-13 07:24 UTC
### Steps to reproduce
1. telegram-desktop -startintray
2. Right click on tray icon
3. Select Open Telegram

### Expected behaviour
Telegram window should open.

### Actual behaviour
Nothing

### Configuration
Ubuntu 17.04

**Version of Telegram Desktop:**
1.0.29

**Used theme**:

<details><summary>**Logs**:</summary><pre>
Qt: Session management error: Could not open network socket
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock

(telegram-desktop:21175): libappindicator-CRITICAL **: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
</pre>

**Comment by TheAppService** [comment] 2017-05-13 11:11
#422

**Comment by SnuggIes** [comment] 2017-08-09 01:05
I can confirm this bug occurs on Ubuntu 17.04.

Please see this video demonstrating this bug: https://www.youtube.com/watch?v=Lwx1g51Kv4E
Telegram **only** opens at 0:27.

**The only way to get the Telegram window to open is to:**
_1. Click on tray icon
2. Click "Minimize to tray"
3. Click on tray icon again
4. Click "Open Telegram"_

**System Configuration:**
![image](https://user-images.githubusercontent.com/26250962/29100887-82bd7c8c-7ca6-11e7-8d5b-493d4ce032a8.png)

**Comment by Aokromes** [comment] 2017-10-02 16:48
Duplicate of #422

**Closed** 2017-10-02 16:48 UTC
