### ISSUE TITLE
telegram resets custom hidpi settings on every launch (ubuntu 20.10)

### ISSUE THREAD

**Issue by nergdron** [telegramdesktop/tdesktop#9059] opened 2020-11-13 06:41 UTC
### Steps to reproduce
1.  set a custom hidpi scaling setting, like 125%
2. logout
3. login

### Expected behaviour
hidpi scaling settings are retained when telegram opens.

### Actual behaviour
hidpi scaling settings are lost, and everything is tiny.

### Configuration
**Operating system:** Ubuntu 20.10

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website

**Comment by ilya-fedin** [comment] 2020-11-13 08:08
Can't reproduce

**Comment by nergdron** [comment] 2020-11-13 08:54
oh looks like I got the repro case wrong, it's not every time it's opened, it's only when you logout and login again. but I can repro on every new login, telegram starts and has forgotten my scaling settings.

**Comment by nergdron** [comment] 2020-11-13 08:54
is there a log somewhere I should be looking in to attach here?

**Comment by ilya-fedin** [comment] 2020-11-13 08:58
It is a GNOME issue, it reports 100% scaling at the time it processes autostart

**Comment by ilya-fedin** [comment] 2020-11-13 09:05
And a duplicate of #6773

**Comment by nergdron** [comment] 2020-11-13 09:05
hmmm except I'm putting in a manual scaling setting, telling telegram to ignore the OS. which it should save and retain regardless of what the desktop environment reports, no?

if telegram ignores that setting if the desktop env tells it to, then it really needs to communicate that it doesn't do what you expect when you turn off "default scaling".

**Comment by ilya-fedin** [comment] 2020-11-13 09:08
> hmmm except I'm putting in a manual scaling setting, telling telegram to ignore the OS. which it should save and retain regardless of what the desktop environment reports, no?

This is a either a bug or a feature in settings saving that when current scale == system scale, it enable the default scale setting. I don't know if this is a bug, this is a question for @john-preston

**Comment by ilya-fedin** [comment] 2020-11-13 09:12
> if telegram ignores that setting if the desktop env tells it to, then it really needs to communicate that it doesn't do what you expect when you turn off "default scaling".

I don't understand this part of your message

**Closed** 2020-11-13 10:36 UTC

**Comment by ShrirajHegde** [comment] 2020-11-13 11:26
@nergdron execute ```sleep 5 && Telegram -autostart``` to fix the problem.
