### ISSUE TITLE
[bug] "favorite" and "recent" stickers icons gone from sticker panel

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#4780] opened 2018-06-02 18:22 UTC
### Steps to reproduce
1. Watch the bottom of the sticker panel where all icons are located.
2. Trending stickers "fire" icon should be on the right, so if have unseen trending stickers, scroll all of them until the icon no longer has the number on it.
3. If no favorite stickers are added, then add some. You should have the "star" icon and the "clock" icon next to it.
4. Remove all stickers from favorite.

### Expected behaviour
After favorite stickers are all deleted, only "star" icon should disappear, and "star" should be back if you add some favorite stickers again.

### Actual behaviour
After favorite stickers are all deleted, both "star" and "clock" icons disappear. If you add some stickers to favorite again, "clock" icon appears again, but "star" never appears.
The bug seem to occur only when you have no unseen trending stickers, i.e. when "fire" icon is on the right and has no number on it, but that may not be the point.

Screenshot 1: no favorite stickers => no icon for recent stickers, also "Frequently used" header is missing
![screen1](https://user-images.githubusercontent.com/39861574/40879452-4f5a0cac-66e3-11e8-87b1-a408a1943950.JPG)

Screenshot 2: added some favorite stickers => "frequently used" icon and header both are back, but no "favorite stickers" icon and header.
![screen2](https://user-images.githubusercontent.com/39861574/40879453-5053ea92-66e3-11e8-8f2a-d5d5ac68cee6.JPG)

### Configuration
**Operating system:**
Win 7 64
**Version of Telegram Desktop:**
 1.2.17, then continued on 1.3 after update. Reinstalling did not help. Happened just yesterday after removing favorite stickers(NOT after update), so I doubt this is a new feature, as some people were suggesting. At least 5 people reproduced this bug following the steps above.
**Used theme**:
Default

**Comment by john-preston** [comment] 2018-06-03 17:52
Star icon was removed, because only five stickers can be added as favourite and the recent pack icon is enough to jump to the top of the list.

If the first set is recent or favourite the header is hidden by design.

But indeed there is a bug when there are no favourite stickers, some recent and all trending sets are marked as read.

**Comment by roleard** [comment] 2018-06-03 20:41
Will there be more than 5 favorite stickers some day? They said "that's just to start with" https://twitter.com/telegram/status/905001411334873088
we definitely need more, at least 20, maybe 50 or even 100.

Also, the star icon disappeared although I was not updating before it happened, how is this possible? I thought UI is on the client side.

**Comment by john-preston** [comment] 2018-06-03 22:14
@roleard I think you did update. I don't know about the plans with the limit :(

**Comment by roleard** [comment] 2018-06-04 09:45
In which version they deleted the star? Because I believe it WAS there on 1.2.17 and then it WASN'T on the same version. I actually updated to 1.3 because I thought they could have fixed it. But maybe I'm insane. I asked some people and they confirmed the star disappeared not so long ago.

**Closed** 2018-06-16 10:01 UTC
