### ISSUE TITLE
High CPU usage out of nowhere

### ISSUE THREAD

**Issue by SinTan1729** [telegramdesktop/tdesktop#23899] opened 2022-01-15 04:09 UTC
### Steps to reproduce

1. Just keep the app running in the background.

### Expected behaviour

It should work with normal usage (1-2% in background will be expected).

### Actual behaviour

Randomly starts using tons of CPU.

### Operating system

EndeavourOS KDE, also happened in Manjaro KDE

### Version of Telegram Desktop

3.4.3-2

### Installation source

Other (unofficial) source

### Screenshot

![image](https://user-images.githubusercontent.com/35728385/149608312-62bec84f-77c4-46af-b5df-48e96e0363e3.png)

**Comment by fabgrel10** [comment] 2022-03-23 20:32
I'm experiencing the same issue on Manjaro KDE using version 3.6.1

**Comment by top4ek** [comment] 2022-04-11 07:33
3.6.1, Archlinux, KDE — the same.
![Screenshot_20220411_102801](https://user-images.githubusercontent.com/16016/162687007-827d1f87-1e29-4ebb-b445-d1af3c775ad2.png)

**Comment by IgnatBeresnev** [comment] 2022-04-13 17:24
Started happening randomly on `3.6.1` as well, didn't experience it before. 

Killing `telegram-desktop` and opening it again helps

Arch, i3, X11

**Comment by simoneruffini** [comment] 2022-06-06 21:34
I have this issue too, 20% usage even when in background and with no audio/video/gif playing.

My version is the 3.6 from nix (package telegram-desktop).

My only suspect is this line 
`[2022.06.06 23:30:45] Native Notification Error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
that gets logged with a high frequency in `.local/share/TelegramDesktop/log.txt`
I'm not sure but could it be something to do with gnome-keyrings?

**Comment by pmoieni** [comment] 2022-07-14 18:34
Same issue. version 4.0.2 on Fedora KDE.
![image](https://user-images.githubusercontent.com/62774242/179056850-ebde6a04-c300-49ab-8674-281a34b04862.png)
and the process doesn't finish when I fully close the telegram. I need to manually quit the process from the system monitor.

**Comment by pmoieni** [comment] 2022-07-15 09:02
I enabled use system window frame in settings and looks like the issue is fixed. on default setting I was getting the application launch bouncing feedback (which KDE shows next to the pointer when an application is launching) on every click.

**Comment by nakdes** [comment] 2022-08-06 09:07
same issue, it's annoying

**Comment by ilya-fedin** [comment] 2022-08-08 04:50
If you're using Fedora, switch to the official binary provided by https://desktop.telegram.org. Third-party builds frequently use wrong library versions that lead to instability and various bugs. This is especially known to happen with the package provided by Fedora community on a regular basis.

**Comment by pmoieni** [comment] 2022-08-08 05:50
@ilya-fedin switched to flatpak version and haven't seen the issue for a long time. Thanks.

**Comment by simoneruffini** [comment] 2022-08-10 16:21
> If you're using Fedora, switch to the official binary provided by https://desktop.telegram.org. Third-party builds frequently use wrong library versions that lead to instability and various bugs. This is especially known to happen on a regular basis with the package provided by the Fedora community.

Can you share which are the correct libraries to build upon?

**Comment by ilya-fedin** [comment] 2022-08-10 19:20
> Can you share which are the correct libraries to build upon?

The correct library version to avoid this bug is ffmpeg 4.4.

**Comment by ilya-fedin** [comment] 2022-08-10 21:46
Is there anyone who can confirm high CPU usage with official binary? If not, this is going to be closed as 3rd party builds bug.

**Comment by ohhai** [comment] 2022-08-12 17:36
@ilya-fedin
> If you're using Fedora, switch to the official binary provided by https://desktop.telegram.org. Third-party builds frequently use wrong library versions that lead to instability and various bugs. This is especially known to happen on a regular basis with the package provided by the Fedora community.

I see that Fedora uses ffmpeg 5.0.1, which is official stable release: https://ffmpeg.org/download.html#releases
Does it have specific bugs? Or why it's wrong?

**Comment by ilya-fedin** [comment] 2022-08-13 00:30
> Or why it's wrong?

No one ported tdesktop to ffmpeg 5.x. There was a big API break, so apparently tdesktop's usage of ffmpeg APIs is no longer valid (even though it compiles with ffmpeg 5.x). They should either build with the supported version or put the effort to port tfedktop to ffmpeg 5.x.

**Comment by ilya-fedin** [comment] 2022-08-13 00:31
The same with OpenSSL 3.x. tdesktop builds, but e.g. voice chats don't work.

**Comment by xvitaly** [comment] 2022-08-13 13:02
> Third-party builds frequently use wrong library versions that lead to instability and various bugs. This is especially known to happen on a regular basis with the package provided by the Fedora community.

Liar. If you don't want to fix bugs, close issue, but stop blaming innocent people.

**Comment by ilya-fedin** [comment] 2022-08-13 13:09
> stop blaming innocent people

Innocent? Fedora and Arch are the leaders by amount of various packaging issues reported here. With the only difference that Arch usually applies the recommended fix while Fedora problems continue happen as they like to patch the build and over-engineering problems due to the church.

Even Gentoo package got a good maintainer when the previous one stepped down due to having little free time. Still, Fedora package seem to continue getting into troubles.

**Comment by leigh123linux** [comment] 2022-08-13 13:12
> > Or why it's wrong?
> 
> No one ported tdesktop to ffmpeg 5.x. There was a big API break, so apparently tdesktop's usage of ffmpeg APIs is no longer valid (even though it compiles with ffmpeg 5.x). They should either build with the supported version or put the effort to port tdesktop to ffmpeg 5.x.

Fuck it, time to move on to Whatsapp and get away from the bullshit excuses.

**Comment by ilya-fedin** [comment] 2022-08-13 13:13
Folks, it's called 'technical details', not 'excuses'. If you don't want to hear 'excuses', use the support, not GitHub.

**Comment by xvitaly** [comment] 2022-08-13 18:25
> With the only difference that Arch usually applies the recommended fix while Fedora problems continue happen as they like to patch the build and over-engineering problems due to the church.

Do you have proof of your words? I see that both [Arch](https://github.com/archlinux/svntogit-community/blob/packages/telegram-desktop/trunk/PKGBUILD) and [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-im/telegram-desktop/telegram-desktop-4.0.2.ebuild) uses packaged Qt 6 and all other libraries, just like Fedora. Once they get ffmpeg 5 they will have the same issues.

Arch uses compatibility version of ffmpeg4.4.

> Then they complain about problems they created on their own that could be avoided just by doing what's recommended by upstream.

Fedora is a bleeding edge distribution. That's why we always have the latest versions of compilers and libraries.

**Comment by ilya-fedin** [comment] 2022-08-14 02:29
> Do you have proof of your words?

The most long-standing issue with Fedora package is it's built with non-recommended build flags, e.g. GTK integration was disabled [right until its deletion](https://github.com/rpmfusion/telegram-desktop/commit/0c540b528192631ab210a7ad80357df5f40dd76e#diff-0d32684b48352f1f2b2f02b473e2ddde969e4ad053a21f410126f14045ee4179L5) what was causing issues with clipboard and etc.

> Btw, [Fedora build](https://github.com/rpmfusion/telegram-desktop) has 0 downstream patches.

Nice to see

> Arch uses compatibility version of ffmpeg4.4.

Yeah. As you can see, Arch already fixed this problem. I don't know what Gentoo will do when they get ffmpeg 5, but I believe they will do something instead of complaining.

> Fedora is a bleeding edge distribution. That's why we always have the latest versions of compilers and libraries.

Fedora shouldn't remove old version of packages if some packages still depend on them. Even Arch still has ffmpeg 4.4.

**Comment by xvitaly** [comment] 2022-08-14 07:24
> The most long-standing issue with Fedora package is it's built with non-recommended build flags, e.g. GTK integration was disabled [right until its deletion](https://github.com/rpmfusion/telegram-desktop/commit/0c540b528192631ab210a7ad80357df5f40dd76e#diff-0d32684b48352f1f2b2f02b473e2ddde969e4ad053a21f410126f14045ee4179L5) what was causing issues with clipboard and etc.

All these issues were resolved over a year ago. Fedora build uses standard build flags and standard configuration (even for static tg_owt).

> Yeah. As you can see, Arch already fixed this problem.

This is a temporary workaround, not a fix. Such compatible packages are not permanent.

More and more distributions get ffmpeg 5.x:

[![latest packaged version(s)](https://repology.org/badge/latest-versions/ffmpeg.svg)](https://repology.org/project/ffmpeg/versions)

> Fedora shouldn't remove old version of packages if some packages still depend on them.

There is only one version of each package in Fedora repositories. This is a part of the development process. We test builds against new versions and then report issues to upstreams.

**Comment by pmoieni** [comment] 2022-08-14 07:29
@xvitaly also I should note that the Persian font used in the fedora repos for telegram is not the one used for the official version Which is _**vazir matn**_ font.
You can't even differentiate between the numbers 3 and 4.

**Comment by xvitaly** [comment] 2022-08-14 07:31
> @xvitaly also I should note that the Persian font used in the fedora repos for telegram is not the one used for the official version Which is vazir matn font.

That's true. We can't use bundled fonts for legal reasons. We use build-in option to prefer packaged version. I think if you install Vazir fonts system-wide, Telegram Desktop will start using them.

**Comment by ilya-fedin** [comment] 2022-08-14 07:32
> All these issues were resolved over a year ago. Fedora build uses standard build flags and standard configuration (even for static tg_owt).

Nice to hear. You asked for proofs, I provided them.

> This is a temporary workaround, not a fix. Such compatible packages are not permanent.

Yeah, at some point someone would port tdesktop to ffmpeg 5 guess. Right now this doesn't seem to be a priority for anyone, so compatibility package is a must for you if you don't have the power to make the port on your own.

> There is only one version of each package in Fedora repositories. This is a part of the development process. We test builds against new versions and then report issues to upstreams.

Well, your development process should include either compatibility packages for transition time or some team that would help upstreams porting to newer libraries. Not all upstreams have manpower to follow your speed. tdesktop is one of them, there's only one person working full-time (just like with any other official Telegram client).

**Comment by ilya-fedin** [comment] 2022-08-14 07:32
> also I should note that the Persian font used in the fedora repos for telegram is not the one used for the official version

Oh, so they still differ in build options. What a shame.

**Comment by pmoieni** [comment] 2022-08-14 07:35
> > @xvitaly also I should note that the Persian font used in the fedora repos for telegram is not the one used for the official version Which is vazir matn font.
> 
> That's true. We can't use bundled fonts for legal reasons. We use build-in option to prefer packaged version. I think if you install Vazir fonts system-wide, Telegram Desktop will start using them.

I've already tried that but doesn't seem to detect the font. Looks like telegram uses an XML config file for storing font metadata. That needs to change too.
Anyway, I'm not sure if this bug is related to this issue.
_**Vazir matn**_ font is open-source on GitHub though.

**Comment by ilya-fedin** [comment] 2022-08-14 07:35
> I think if you install Vazir fonts system-wide, Telegram Desktop will start using them.

Choosing the default for some writing system is not trivial with fontconfig, unfortunately. One needs to dig into the fontconfig's XML configuration world. The result won't be identical anyway as the bundled fonts are patched to workaround some Qt bugs about bold variants. That's why the default is to used bundled fonts.

**Comment by xvitaly** [comment] 2022-08-14 07:40
> The result won't be identical anyway though as the bundled fonts are patched to workaround some Qt bugs about bold variants. That's why the default is to use bundled fonts.

OK. I'll ask for an exception for using bundled fonts.

**Comment by xvitaly** [comment] 2022-08-14 08:02
@ilya-fedin Fonts should be fixed now: https://github.com/rpmfusion/telegram-desktop/commit/ebe700feb81d5fe9523e75f739c003b715bedaa9

**Comment by xvitaly** [comment] 2022-08-14 15:48
@ilya-fedin Fixed in [telegram-desktop-4.1.0-1.fc36](https://koji.rpmfusion.org/koji/buildinfo?buildID=23434) by building against openssl 1.1 and ffmpeg 4.4.
@pmoieni Fonts should be fixed too.

**Comment by Aokromes** [comment] 2022-08-14 15:52
so, i can close this?

**Comment by xvitaly** [comment] 2022-08-14 15:59
> so, i can close this?

I guess so.

**Closed** 2022-08-14 23:43 UTC
Labels: bug, waiting for answer

**Comment by pmoieni** [comment] 2022-08-16 09:58
> Fonts should be fixed too.
@xvitaly sorry for late response, but I installed telegram using **_dnf_** and the previous Font was still there. Even though I have **_vazir matn_** font installed system-wide.

**Comment by xvitaly** [comment] 2022-08-16 11:26
> sorry for late response, but I installed telegram using dnf and the previous Font was still there. Even though I have vazir matn font installed system-wide.

New build is still in testing. Use this command to get it:
```
sudo dnf upgrade --refresh telegram-desktop --enablerepo=rpmfusion-free-updates-testing
```
