### ISSUE TITLE
Switch Account Keyboard Shortcut

### ISSUE THREAD

**Issue by erfanmola** [telegramdesktop/tdesktop#8605] opened 2020-09-17 14:03 UTC
Any ideas about adding Switch Account Keyboard Shortcut ? I'm really having time wasted for switching between accounts while I'm using i3wm in Linux Keyboard-Only

**Comment by RememberTheAir** [comment] 2020-09-17 14:33
Duplicate of #8179

**Closed** 2020-09-17 15:06 UTC
