### ISSUE TITLE
Sending a venue/location

### ISSUE THREAD

**Issue by gleb-chipiga** [telegramdesktop/tdesktop#4423] opened 2018-02-18 09:26 UTC
### Steps to reproduce
1. Click "Attach" button
2. Select "Location" item
3. Position the marker on the map
4. Click "Send" button

### Expected behaviour
The behavior should look like that there is in Telegram for Android.
1. Click "Attach" button
2. Select "Location" item
3. Position the marker on the map
4. Click "Send" button

### Actual behaviour
Now it's not possible to send a location

### Configuration
**Operating system:**
Any.

**Version of Telegram Desktop:**
Any.

**Used theme**:
Any.

**Comment by auchri** [comment] 2018-02-18 10:31
Duplicate of #1193

**Closed by auchri** 2018-02-18 10:31 UTC
