### ISSUE TITLE
Enermous size of log file

### ISSUE THREAD

**Issue by vgarvardt** [telegramdesktop/tdesktop#2709] opened 2016-12-13 14:45 UTC
### Steps to reproduce
1. Just use Telegram Desktop actively

### Expected behaviour
Enjoying communication

### Actual behaviour
Run out of free space

### Configuration
**Operating system:** macOS Sierra 10.12.1

**Version of Telegram Desktop:** 0.10.19

### Logs
$ ls -lah ~/Library/Containers/org.telegram.desktop/Data/Library/Application\ Support/Telegram\ Desktop/ | grep log
-rw-r--r--@  1 ***  ***   180G Dec 13 17:20 log.txt

**Comment by john-preston** [comment] 2016-12-13 14:46
@vgarvardt What do you have there? O_o like, a hundred of last lines?

**Comment by vgarvardt** [comment] 2016-12-13 14:48
Sorry, could not do this, had to rm -rf it as OS just got stuck

**Comment by mattoopie** [comment] 2016-12-17 12:29
Exactly this same thing happened to me. http://i.imgur.com/4R0Bqkc.png
Huge file size, filled up my full C drive. Windows 10 TG 0.10.19

**Comment by john-preston** [comment] 2016-12-17 13:03
@mattoopie Can you close Telegram Desktop, delete this file and open it once again, see if it will grow and copy some lines from the end? I don't understand what causes such a big log size.

**Comment by mattoopie** [comment] 2016-12-17 13:06
@john-preston I deleted the file about half an hour ago and it has since started growing again, with about 2MB/sec. I tailed the file and found these lines, hope it helps.

[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input
[2016.12.17 14:05:52] Audio Error: Unable to avcodec_send_packet() for file '', data size '945694', error -1094995529, Invalid data found when processing input

**Comment by john-preston** [comment] 2016-12-17 13:41
@mattoopie Wow. Thanks. Looks like ffmpeg-sound related. Does it start growing right when you lauch it or after you receive a message (that should be accompanied by a notification sound) or maybe when you start playing a voice message or a music file? Or maybe just when you open a chat with some voice message that tries to count its wave form.. I'll remove that logging in the next version, but I'm interested what data causes it exactly.

**Comment by mattoopie** [comment] 2016-12-17 14:44
@john-preston I've tried some different things and found out the growing starts when I open the GIF interface or when I open a chat with some recent GIFs. Some of these GIFs were made on my phone (Android v3.15.0(884)arm-v7a) and did not play on any of my devices, nor on my friends' devices. I removed these GIFs from the recent GIF interface and the issue has now stopped occurring when I open  the recent GIF interface, but still happens when I open a chat in which i sent it recently (ie loaded when chat opens). I then spammed enough lines of chat so the failed GIF was not loaded when chat is opened which helped and the log file does not grow. Scrolling back up (ie making the gif(s) load) causes the issue again.

Hope you can investigate more into why this issue is occurring and find a way to fix it.

**Comment by john-preston** [comment] 2016-12-17 16:45
@mattoopie Great information, thank you. Can you please contact me at https://telegram.me/preston and send me this such GIF animation? I hope I'll see the same behavior.

**Comment by john-preston** [comment] 2016-12-17 20:34
@mattoopie I reproduced that issue, it will be fixed in the next version. Thank you for your help!

**Comment by john-preston** [comment] 2016-12-18 17:35
@mattoopie Please check the version 0.10.20, it should be fine there. And thanks again for the investigation.

**Comment by mattoopie** [comment] 2016-12-18 21:29
@john-preston Thank you, the program has updated now and problem is not occurring anymore. Thanks for the fix!

**Closed** 2017-11-17 20:34 UTC
