### ISSUE TITLE
High CPU load in background with open GIFS tab in the ESG-Panel

### ISSUE THREAD

**Issue by Leukodi** [telegramdesktop/tdesktop#3687] opened 2017-07-20 19:21 UTC
### Steps to reproduce
1. Open the Client.
2. Resize it until the ESG (Emoji-Stickers-Gifs) Panel is visible.
3. Select the "GIFS" tab.
4. Focus another window, so the client window is no longer active and the gifs pause.

### Expected behaviour
Minimal to none CPU load.
The other tabs (Emoji, Stickers) put the CPU at around 0% - would expect the same for the GIFs tab.

### Actual behaviour
High CPU load (~13% on my machine).

### Configuration
**Operating system:**
Windows 10
AMD Phenom II X6 1055T Processor
**Version of Telegram Desktop:**
1.1.10
**Used theme**:
Default

**Comment by codepearlex** [comment] 2017-10-30 12:18
#3640

**Comment by sstyle** [comment] 2018-01-09 11:54
#4238

**Comment by auchri** [comment] 2018-01-09 11:55
Duplicate of #3640

**Closed by auchri** 2018-01-09 11:55 UTC
