### ISSUE TITLE
Spell checker doesn't work on manjaro 18.1.5

### ISSUE THREAD

**Issue by alsoGAMER** [telegramdesktop/tdesktop#6907] opened 2019-12-30 01:38 UTC
I've installed the latest beta (1.9.2) but the spellchecker doesn't work even with enchant installed.

$ pacman -Qi enchant
<pre>Name            : enchant
Version         : 2.2.7-1
Description     : A wrapper library for generic spell checking
Architecture    : x86_64
URL             : https://abiword.github.io/enchant/
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : aspell  hunspell  hspell  libvoikko  glib2
Optional Deps   : None
Required By     : gspell  gtkspell  gtkspell3  python-pyenchant  webkit2gtk
Optional For    : hexchat
Conflicts With  : None
Replaces        : None
Installed Size  : 167,00 KiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : thu 26 september 2019, 08:06:28 AM
Install Date    : tue 15 october 2019, 11:42:59 AM
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature</pre>

$ yay -Sy enchant
<pre>warning: enchant-2.2.7-1 is up to date -- reinstalling</pre>

$ yay -Syu
<pre>:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 there is nothing to do</pre>

**Comment by ANaumann85** [comment] 2019-12-30 12:27
Using debian-10 with enchant 1.6.0, I get the only a meaningless error message in gdb:
````
  terminate called after throwing an instance of 'enchant::Exception'
    what():
````
Is there some way to disable the spell checker?

**Comment by Aokromes** [comment] 2019-12-30 13:01
if it's the same way as on windows, on settings.

**Comment by ANaumann85** [comment] 2019-12-30 13:07
It crashes already when I click at the settings button 
null

**Comment by Aokromes** [comment] 2019-12-30 13:30
I don't get crash trying to reach settings.
https://i.imgur.com/A9SGgOg.png

**Comment by ANaumann85** [comment] 2019-12-30 13:48
I tried again and changed the language to english. But I get the same behavior, see: https://imgur.com/a/TfHTzAO
Do you need further information for reproducing?

**Comment by Aokromes** [comment] 2019-12-30 13:53
when you get the crash run:
https://github.com/TrinityCore/TrinityCore/blob/master/contrib/debugger/crashreport.gdb on gdb window.

**Comment by ANaumann85** [comment] 2019-12-30 13:56
did it and got the appended backtrace.log file
[backtrace.log](https://github.com/telegramdesktop/tdesktop/files/4009917/backtrace.log)

**Comment by john-preston** [comment] 2019-12-31 15:02
@ANaumann85 I'll try to log exceptions instead of crash in 1.9.3 version, if you launch it with debug logs enabled we'll be able to see at least which command causes the exception.

**Comment by ANaumann85** [comment] 2019-12-31 16:11
Can you tell me, how I can enable the debug log? The command 
``
Telegram --help
``
prints nothing on the commandline

**Comment by ANaumann85** [comment] 2019-12-31 16:43
[log_17_30.txt](https://github.com/telegramdesktop/tdesktop/files/4013099/log_17_30.txt)
[mtp_17_30.txt](https://github.com/telegramdesktop/tdesktop/files/4013100/mtp_17_30.txt)
[tcp_17_30.txt](https://github.com/telegramdesktop/tdesktop/files/4013101/tcp_17_30.txt)

**Comment by alsoGAMER** [comment] 2019-12-31 17:47
EDIT: Now the option to enable or disable the spell checker has appeared in the settings, but still no effective spell check. I can literally write anything, not even taking into account the basic rules of the English language, but nothing is highlighted as an error

**Comment by ANaumann85** [comment] 2019-12-31 18:09
At least it does not crash anymore, but spellchecking is not available on debian 10

**Comment by Aokromes** [comment] 2019-12-31 18:18
works for me (TM) https://i.imgur.com/qsLUSKV.png

**Comment by alsoGAMER** [comment] 2019-12-31 18:20
> At least it does not crash anymore, but spellchecking is not available on debian 10

Have you installed enchant?

**Comment by ANaumann85** [comment] 2019-12-31 18:30
Yes, it is installed. But when I run strace on Telegram, i recognize two things:
1. Telegram spawns a new process now, hence I have to trace it twice
2. It opens empty dictionaries in my local folder.
Can you give me any pointer, what to check now? I think, I miss some dictionary or configuration of enchant. At the moment, I have an aspell-dictionary installed.

**Comment by alsoGAMER** [comment] 2020-01-01 01:21
I think I have understood what the problem is, on manjaro / arch, the CLI command for enchant is enchant-2, not enchant.

Proofs:
~ >>> echo "wrongWord" | enchant -a -d "en"                                                                                           
zsh: command not found: enchant

~ >>> echo "wrongWord" | enchant-2 -a -d "en"                                                                                         
@(#) International Ispell Version 3.1.20 (but really Enchant 2.2.7)
& wrongWord 3 0: wrong Word, wrong-word, wrongdoing


@john-preston I think that is really easy to fix, just read the /etc/os-release file, and if the distro is manjaro or arch, add a "-2" to the enchant command in the code

**Comment by ilya-fedin** [comment] 2020-01-01 09:18
> @john-preston I think that is really easy to fix, just read the /etc/os-release file (or more easily use "lsb_release -a") and if the distro is manjaro or arch, add a "-2" to the enchant command in the code (eg enchant-2...)

This ignores all other distros with actual enchant2. Debian has an outdated enchant2 before renaming binaries and libs.

**Comment by ilya-fedin** [comment] 2020-01-01 09:27
> I think I have understood what the problem is, on manjaro / arch, the CLI command for enchant is enchant-2, not enchant.

(also, i can't find any calls of  any cli command https://github.com/desktop-app/lib_spellcheck/blob/master/spellcheck/platform/linux/linux_enchant.cpp)

**Comment by mymedia2** [comment] 2020-01-01 09:29
@alsoGAMER, Telegram Desktop does not use command `enchant` directly. It loads Enchant shared library with dlopen.

https://github.com/desktop-app/lib_spellcheck/blob/3ed9533de41c5d14a8592071eaacc6efeb7f9664/spellcheck/platform/linux/linux_enchant.cpp#L221

**Comment by ANaumann85** [comment] 2020-01-01 11:25
Do you write something related to the spellchecking, or the user interaction to the log file? After enabling debugging, I did not find anything in the log file.

**Comment by alsoGAMER** [comment] 2020-01-01 12:30
> @alsoGAMER, Telegram Desktop does not use command `enchant` directly. It loads Enchant shared library with dlopen.
> 
> https://github.com/desktop-app/lib_spellcheck/blob/3ed9533de41c5d14a8592071eaacc6efeb7f9664/spellcheck/platform/linux/linux_enchant.cpp#L221

Ok, sorry, my fault.

**Comment by ilya-fedin** [comment] 2020-01-01 20:04
I found the root of the problem. On debian enchant compiled without hspell, but on others with hspell. Because the current algorithm adds all dictionaries (which is incorrect), on non-debian distros, when enchant tries to check a word with hspell - it getitng an error. I'll send a pr with fix.

**Comment by mymedia2** [comment] 2020-01-02 08:10
@ilya-fedin, you think that loading of all dictionaries at a time is wrong behavior. So what do you suggest to do instead?

**Comment by ilya-fedin** [comment] 2020-01-02 15:04
@mymedia2 
https://sourceforge.net/p/gtkspell/gtkspell/ci/master/tree/gtkspell/gtkspell.c (line 699-735)
https://gitlab.gnome.org/GNOME/gspell/blob/master/gspell/gspell-language.c#L407-461
https://github.com/manisandro/qtspell/blob/master/src/Checker.cpp#L101-L127

**Comment by mymedia2** [comment] 2020-01-02 18:24
@ilya-fedin, sorry, I don't get you. Could you focus on the specificity of Telegram Desktop? Let's suppose we have the next message: "test 试验 проверка elprovo". Against which language this string should be checked? 

What if a user has several dictionaries installed and we need to check a document in undeclared language? As far as I know, Telegram has no idea of chat language so we can't choose a single dictionary to check spelling.

**Comment by ilya-fedin** [comment] 2020-01-02 19:18
> What if a user has several dictionaries installed and we need to check a document in undeclared language?

As you can see, adding all dictionaries produces a crash. So there are three options:
1. Use only one language
2. Write a very complicated message language detector (example: https://github.com/kitone/subtitleeditor/blob/master/src/gui/automaticspellchecker.cc)
3. Switch to a more appropriate library

**Comment by winterwolf** [comment] 2020-01-03 13:09
I have the same problem on Manjaro. Spell checker and newly uploaded gif animations doesn't works at all.

**Comment by viktor-w** [comment] 2020-01-05 01:47
Manjaro 18.1.5; Workaround for me -  Spell checker work perfectly with [enchant-pure] (2.2.7-1) from AUR. (tdesktop 1.9.3)

**Comment by winterwolf** [comment] 2020-01-06 19:11
@viktor-w thank you!

**Comment by rkakrik** [comment] 2020-01-07 06:23
Same problem on arch linux

**Comment by farseerfc** [comment] 2020-01-07 14:45
On Arch Linux I found another workaround is removing hspell by `pacman -Rdd hspell` while ignoring dependency and keep enchant installed.
enchant-pure is not configured with hspell support, so I think this is related to @viktor-w 's workaround.

Does this means Hebrew support is broken with lib_spellchecker?

**Comment by jcrush2** [comment] 2020-01-08 11:16
as I understand it, the problem on manjaro / arch is that it costs enchant-2 and the telegram wants enchant, I installed enchant and the EN dictionary from aur, but it still doesn’t work

**Comment by farseerfc** [comment] 2020-01-09 03:48
@jcrush2 telegram tried to load enchant and enchant2, whichever is available:
https://github.com/desktop-app/lib_spellcheck/blob/master/spellcheck/platform/linux/linux_enchant.cpp#L220-L222
And it actually loaded it, with hunspell, aspell and their dicts, you can confirm this by strace. But if your enchant sees hspell available on the system, telegram spellchecker stopped working for some unknown reason.

**Comment by ilya-fedin** [comment] 2020-01-09 21:45
> for some unknown reason

hspel tries to convert the text to local Hebrew codepage

**Comment by 23rd** [comment] 2020-02-25 08:37
Should be fixed now.

**Closed** 2020-02-25 12:40 UTC
Labels: bug
