### ISSUE TITLE
Window slowly moves upwards everytime it's opened from the tray

### ISSUE THREAD

**Issue by limdingwen** [telegramdesktop/tdesktop#2585] opened 2016-10-30 09:30 UTC
### Steps to reproduce
1. Close Telegram to the tray
2. Click on the tray icon to open the main window
### Expected behaviour

The window should reopen at the same position it was closed at when the tray icon is clicked.
### Actual behaviour

The window reopens slightly higher than the position it was closed at when the tray icon is clicked.
### Configuration

**Operating system:** Linux Mint Cinnamon 18 (64-bit), Intel i5, 1440x900

**Version of Telegram Desktop:** 0.10.7

**Comment by AndydeCleyre** [comment] 2016-11-22 21:04
I'm using `0.10.19` in the plasma desktop (with kwin) and this bug does not occur.

**Comment by tavrez** [comment] 2017-04-06 11:59
Is this fixed? In 1.0.29 maximize minimize bug #2883 which is referenced here still happening.

**Comment by rusins** [comment] 2017-05-12 14:12
Still happening in Telegram version 1.0.29.
It seems like the amount it moves upwards is the exact hight of the window title/border/close-min-max button border. Most likely a bug in either saving the previous location, or when passing the window's desired position when drawing the window to the screen.

Happens to me when opening telegram anyhow, not only from the tray.
Tested on Gnome 3.24.2 on Arch Linux, 12th of May.

**Comment by tdesktop-closer** [comment] 2018-06-01 18:51
Hey there!

We're automatically closing this issue since there was no activity in this issue since 385 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

<sub>(Please note that this is an [automated](https://github.com/auchri/github_auto_closer) comment.)</sub>

**Comment by Dabuka** [comment] 2018-09-12 23:16
I use devilspie2 package as a workaround (ubuntu 18.04).

**Comment by a5trocat** [comment] 2019-05-15 16:58
Still happening in Telegram 1.7.0 (flathub)
Gnome 3.32.1 on Manjaro Linux

**Comment by ilya-fedin** [comment] 2020-07-13 18:21
A Gnome/Cinnamon bug:
https://bugreports.qt.io/browse/QTBUG-71671
https://bugreports.qt.io/browse/QTBUG-75312
https://gitlab.gnome.org/GNOME/mutter/-/issues/400
https://github.com/linuxmint/cinnamon/issues/8546

**Comment by mikkovedru** [comment] 2020-10-14 22:46
This bug ( https://github.com/linuxmint/cinnamon/issues/8546 ) seems to be fixed in Linux Mint Cinnamon 20.

**Comment by ilya-fedin** [comment] 2020-10-14 23:39
Telegram some time ago got custom decorations, this issue won't reproduce with them, since the bug is that mutter counts margins wrong with server-side decorations. You should enable "Use system window frame" option in order to reproduce the issue.

**Comment by mikkovedru** [comment] 2020-10-15 21:50
@ilya-fedin 
I enabled the option but I still can't reproduce the bug anymore.

**Comment by rusins** [comment] 2020-10-16 13:22
I can still reproduce the issue.

Telegram 2.4.3, system window frame option enabled, Gnome 3.38.1, Arch Linux.

**Comment by rusins** [comment] 2021-04-14 20:17
Not the most important bug, but definitely still present. Commenting to stop the bot from closing the issue.

Telegram 2.7.1, Gnome 40.0.0, X11

**Comment by ilya-fedin** [comment] 2021-04-15 06:18
@Aokromes can you close the issue to indicate that people should move to the linked GNOME bug?

**Closed** 2021-04-15 06:46 UTC
Labels: 3rd party issue, linux
