### ISSUE TITLE
Compose Key doesn't work

### ISSUE THREAD

**Issue by Alkaris** [telegramdesktop/tdesktop#2193] opened 2016-06-26 02:26 UTC
### Steps to reproduce
1. Enable Compose key, for me it's <kbd>Left WinKey</kbd>
2. Press your compose key and type a symbol or ASCII character into a chat
3.  ie; © ( <kbd>Winkey</kbd> + <kbd>O</kbd> + <kbd>C</kbd>)
### Expected behaviour

Should be able to type Unicode characters and other ASCII characters with the Compose Key in Telegram
### Actual behaviour

Nothing happens, Compose Key doesn't work in Telegram.
### Configuration

**Operating system:** Linux Mint (Cinnamon 64-bit)

**Version of Telegram Desktop:** 0.9.51

**Comment by Alkaris** [comment] 2016-06-30 10:17
@dgadelha there is no AltGr on my keyboard. And I can't do Alt code like you can on Windows, you can only use the set Compose Key chosen on Linux. I have tried many other Qt apps and it works normally in there.

**Comment by dgadelha** [comment] 2016-06-30 20:11
Well, I used to be a Linux user and Alt codes worked fine there.

**Comment by Alkaris** [comment] 2016-06-30 20:38
That probably worked for you with whatever keyboard layout setup you used whenever you last used it. But this is how mine is setup. Which will be different from whatever you previously used.

Now if you don't mind, I would prefer if I got help from people who actually manages or contributes the code base for Telegram that will be able to help find a fixable solution. Since your not either of those, your information is all but useless.

**Comment by ralesk** [comment] 2016-07-07 09:27
@Alkaris Hmm, my Compose key is Caps Lock, and I can enter ©, ® or ı or anything that's in my compose table, with it.
@dgadelha I've never seen Alt codes work on Linux, and I've used many different distros; it's a Windows-specific input method.  In GTK it's possible to do Ctrl+Shift+u, and then the Unicode position in hexadecimal, but since Telegram Desktop is Qt, that's not available there either.
No idea what that Shift+AltGr thing is. That produces shifted level 3 (is this called level 4?) characters on most layouts that have AltGr, eg. on U.S. International AltGr+P produces ö and AltGr+Shift+P produces Ö.

**Comment by Alkaris** [comment] 2016-07-07 11:13
@ralesk Qt apps always seem to have their own specific issues when it comes to usability or features.

**Comment by lindhe** [comment] 2016-08-06 16:50
Ctrl+Shift+u+[unicode code] does now work either. Please fix this, it's working in all other desktop programs I have.

**Comment by ralesk** [comment] 2016-08-08 08:46
> Ctrl+Shift+u+[unicode code] does now work either. Please fix this, it's working in all other desktop programs I have.

There is no Ctrl+Shift+U in non-GTK applications.  Occasionally, Gnome 3 seems to manage to hijack the input and simulate Ctrl+Shift+U in "foreign" apps, but it doesn't always work.  If you use any other environment, only GTK based applications will have this input method.

**Comment by lindhe** [comment] 2016-08-08 10:12
Interesting, I had no idea that was the case. I'm using i3 with some Gnome stuff as a base, so I guess that's why I have it.

So there is no standardized way of writing Unicode characters in Linux then? :(

**Comment by Alkaris** [comment] 2016-08-08 10:52
@lindhe You can, but it's rather tedious way, just use Character Map and get whatever Unicode characters you want to use.

**Comment by lindhe** [comment] 2016-08-08 11:53
Uh, no. I don't have time for that.

**Comment by ralesk** [comment] 2016-08-08 12:57
The only more or less standard thing is Compose (which comes due to X11), and creating your own layout (which isn't hard, but it's cumbersome to keep inside the system folders as there is no user extensibility for them (eg. a `xkb.d` directory or something like that))

I use both, Compose only very rarely, my own layout giving me pretty much all the characters I want to use on a daily basis.

**Comment by mxa** [comment] 2017-02-28 10:05
This was an issue for me, then it worked, and now this issue is back. 1.0.16 alpha

**Comment by mxa** [comment] 2017-02-28 10:13
This is related: https://github.com/telegramdesktop/tdesktop/issues/2112

**Comment by ralesk** [comment] 2017-02-28 10:24
@mxa Have you tried setting `QT_IM_MODULE=xim`?  That seems to fix both #2112 and #1041

**Comment by mxa** [comment] 2017-02-28 11:17
@ralesk indeed that fixes the issue. However I didn't have to do this before to make it work, why suddenly this workaround?

**Comment by ralesk** [comment] 2017-02-28 11:52
Maybe your distro / desktop environment switched to another default IM.

**Comment by mxa** [comment] 2017-02-28 11:54
@ralesk indeed I am using IBUS for the moment because of bugs in nimf.

**Comment by mxa** [comment] 2017-03-10 13:35
@ralesk If I start Telegram with `QT_IM_MODULE=xim`, then the compose key works, but I can't input Korean. If I start Telegram without `QT_IM_MODULE=xim`, then Korean works, but not the Compose Key.

**Comment by mxa** [comment] 2017-08-14 16:12
@auchri I think this needs the labels **bug**, **help-wanted**, **linux**. Maybe?

**Comment by mxa** [comment] 2017-08-14 16:28
To add the `QT_IM_MODULE=xim` option to the Cinnamon launcher see here: https://github.com/linuxmint/Cinnamon/issues/6365#issuecomment-287631274

**Comment by mxa** [comment] 2017-08-14 16:29
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/3690 and https://github.com/telegramdesktop/tdesktop/issues/1360

**Comment by mxa** [comment] 2017-08-28 10:01
@auchri can we get some attention to this issue?

**Comment by mxa** [comment] 2017-11-13 13:08
B U M P

**Comment by mfrasca** [comment] 2018-06-03 17:29
it is indeed a duplicate of #1360, but @auchri closed #1360 after @camilosampedro found a workaround, but before it was included in the software, and as far as I can see, the issue is still an issue.

**Comment by jchook** [comment] 2019-05-17 01:08
Skype, Discord, Signal, and Slack all support the compose key. Telegram is the odd one out here.

**Comment by mxa** [comment] 2019-05-17 22:39
> Skype, Discord, Signal, and Slack all support the compose key. Telegram is the odd one out here.
It works for me in Telegram 1.7 on Linux (KDE)

**Comment by jchook** [comment] 2019-05-17 23:15
@mxa interesting! I run gnome + xmonad and it doesn't work.

**Comment by mfrasca** [comment] 2019-05-18 21:51
I can't remember where it has been mentioned, but I think that this problem is gnome-specific.
the saddest part is that the fix is very simple, just alter the `telegram.desktop` file, and this file will be rewritten without the fix every time you update Telegram, unless you copy it to a safe place somewhere else.

**Comment by jchook** [comment] 2019-05-19 00:20
@mfrasca what happens if you apply the fix and run Telegram in other non-gnome envs (e.g. KDE)? 

Does this mean we can do a "one-liner" fix for this in the source or build process?

**Comment by mfrasca** [comment] 2019-05-19 16:02
there's much more real information in the #1360, closed as of https://github.com/telegramdesktop/tdesktop/issues/1360#event-851450888.  not so clear to me why it was closed really.

**Comment by jchook** [comment] 2019-05-19 20:13
Thanks I found that very helpful. My `QT_IM_MODULE` env var says `ibus`. 

Changing it to `xim` when starting telegram fixed my compose key:

```
#!/bin/bash
export QT_IM_MODULE=xim
/path/to/telegram/Updater
```

**Comment by johannesE** [comment] 2019-05-23 08:35
> Thanks I found that very helpful. My `QT_IM_MODULE` env var says `ibus`.
> 
> Changing it to `xim` when starting telegram fixed my compose key:
> 
> ```
> #!/bin/bash
> export QT_IM_MODULE=xim
> /path/to/telegram/Updater
> ```

Mine is also ibus, but changing it to xim prior to starting did not fix the issue for me :S
Do I need to compile the source manually for this to work?
I noticed that the jetbrains products have the same issue.

**Comment by jchook** [comment] 2019-05-23 15:16
> Mine is also ibus, but changing it to xim prior to starting did not fix the issue for me :S

Maybe (just for kicks) try putting `export QT_IM_MODULE=xim` in your `~/.profile`. Ensure that it's set globally, and see if that fixes it?

> Do I need to compile the source manually for this to work?

Unlikely. You do need at least version 1.7 (iirc). So make sure you downloaded the latest version and did not install via your DE's "App Store" or similar.

> I noticed that the jetbrains products have the same issue.

Which WM and DE do you run? You can try launching your WM with `dbus-launch`. That fixed some weird text issues for me before.

**Comment by ralesk** [comment] 2019-05-29 16:15
for the record, I use ibus (for far-eastern IME), and my compose key does seem to work just fine... (on Fedora 28 and MATE)

**Comment by mxa** [comment] 2019-07-24 21:26
not working in 1.7.15 beta

**Comment by AndydeCleyre** [comment] 2019-08-20 22:27
I'm using `1.8.2` on Arch Linux, KDE Plasma, X11, and the compose key works (albeit with inconsistent, hideous, irresponsibly insecure fonts, that tdesktop goes out of its way to enforce, in an affront to users, usability, consistency, accessibility, etc., and as was discussed in the [five year old issue](https://github.com/telegramdesktop/tdesktop/issues/90) until the devs *banned* such discussion three years ago):

![image](https://user-images.githubusercontent.com/1787385/63388878-dbf06480-c377-11e9-9165-62183c1aca43.png)

My `QT_IM_MODULE` var is unset.

**Comment by ralesk** [comment] 2019-08-22 09:33
Lately, pressing Compose key has been adding a temporary underlined ⎄ (COMPOSITION SYMBOL) to my inputs, similarly to the underlined u for Unicode codepoint input and underlined e for emoji.  I think it's a feature of IBUS, not quite sure.  Telegram is the only application where if I don't manage to combine characters (but, say, abort composition by pressing backspace) the composition symbol will remain in the text entry :(

**Comment by Aokromes** [comment] 2019-08-28 19:14
https://github.com/telegramdesktop/tdesktop/issues/1041

**Closed by Aokromes** 2019-08-28 19:14 UTC
