### ISSUE TITLE
Extra pinned chats from premium subscription aren't selectable with keybinds

### ISSUE THREAD

**Issue by meribold** [telegramdesktop/tdesktop#25647] opened 2022-12-31 12:07 UTC
### Steps to reproduce

1. Have a premium subscription.
2. Pin at least 6 chats.
3. Confirm that the first 5 pinned chats can be selected with Control+1, Control+2, Control+3, Control+4, and Control+5, respectively.
4. Try to select the 6th pinned chat using Control+6.

### Expected behaviour

I'd expect that hitting Control+6 selects the 6th pinned chat.

### Actual behaviour

Hitting Control+6 doesn't result in any action as far as I can tell.

### Operating system

Arch Linux with i3

### Version of Telegram Desktop

4.4.1

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment] 2022-12-31 12:48
not a bug, only the 1-5 are assigned to chats.

**Comment by meribold** [comment] 2022-12-31 13:29
How about a feature request? :)

**Comment by Aokromes** [comment] 2022-12-31 14:24
well, 9-0 are asigned to other things...

**Comment by meribold** [comment] 2022-12-31 15:42
I didn't realize. But I'd also be quite happy with just Control+6/7/8 selecting pinned chats.

**Closed** 2023-01-03 06:00 UTC
Labels: bug
