### ISSUE TITLE
broken scroll acselerator in windows desktop client

### ISSUE THREAD

**Issue by kasumiru** [telegramdesktop/tdesktop#26546] opened 2023-07-21 15:58 UTC
### Steps to reproduce

Then I scroll in menu or chat - quickly scroll doesn't worked in version 4.8.5
in Telegram Desktop 4.8.3 quickly scroll worked correctry.

please, fix old bugs, not create new, I'm crying alone!! 

### Expected behaviour

scroll worked quickly

### Actual behaviour

scroll working slowly

### Operating system

windows 10 build 19045.3086

### Version of Telegram Desktop

4.8.5

### Installation source

Static binary from official website

**Comment by bodayw** [comment] 2023-07-22 06:59
I would like to second this.

The issue was introduced together with the overscroll effect on the chat list, likely since 4.8.5.

Now it seems the scrolling is always at a constant speed within a chat, no matter how fast one swipes on the touchpad.

**Comment by alekseyl1992** [comment] 2023-07-23 21:27
For me scrolling in chats and menus works fine - as it was before. But scrolling chats list using mouse in 4.8.7 is weird: one mouse wheel movement moves the list almost one screen higher, previously it was only 3-ish items per wheel movement.
Maybe the issue is only reproducible on a high Windows/Telegram UI scale: I have a 4k display and use 300% scale factor both in Windows (10) and in Telegram client.

**Comment by bodayw** [comment] 2023-07-24 04:20
> For me scrolling in chats and menus works fine - as it was before.

I guess you are using a mouse scroll wheel, but not a touchpad (on a laptop)?

It seems the scrolling behavior is a bit different between the two. For example, the "overscroll" effect, now found on many web browsers, recently introduced to the chat list of tdesktop 4.8.5, can only be triggered with the touchpad, but not the mouse scroll wheel.

BTW, I don't mind the overscroll effect to be added, but it should be implemented consistently. Right now it seems only available in the chat list, but not within a chat (when scrolling through messages) nor in the Settings (apart from the new acceleration issue in these places).

**Comment by Aokromes** [comment] 2023-07-28 07:35
check on 4.8.9

**Comment by bodayw** [comment] 2023-07-28 10:29
4.8.9 feels like nothing changed to me. It's still slow when scrolling through messages, and there is no "overscroll" effect.

**Comment by alekseyl1992** [comment] 2023-07-29 21:43
4.8.10: nothing changed for me either

**Comment by kasumiru** [comment] 2023-08-09 09:34
up please. 4.8.10 TDesktop official. the bug is still here.
Dell XPS 13 - 9310-5316. official windows 10, scroll standard - two finger. 
Telegram Desktop 4.8.3 - have no bug.
![image](https://github.com/telegramdesktop/tdesktop/assets/25246740/246acfe7-83b5-41fe-b9b8-2867a9c87ae8)

**Comment by john-preston** [comment] 2023-08-11 15:19
A new API is used for scrolling starting with 4.8.5, the same Google Chrome and Firefox use.

It feels fine for me on Dell XPS laptop, so I guess some parameters should be optimized. It feels really quick by touchpad on XPS, I wonder what should be done differently.

**Comment by bodayw** [comment] 2023-08-11 17:16
> A new API is used for scrolling starting with 4.8.5, the same Google Chrome and Firefox use.
> 
> It feels fine for me on Dell XPS laptop, so I guess some parameters should be optimized. It feels really quick by touchpad on XPS, I wonder what should be done differently.

I can see that it can be tricky to describe the feel of scrolling with just words, but let's try and see.

To me, the scrolling feels fine in the chat list (the left panel). I have about 80 "chats", i.e. individuals, groups and channels in the list, and on a 1080p monitor, 100% DPI scaling, with Telegram window maximized, a single very fast swipe can get me from the top almost to the bottom, that is, pretty fast.

By a "very fast swipe" here, I mean swiping as fast as one can with two fingers on the touchpad, and lift the fingers off the touchpad, such that the inertia would make it scroll further for 2-3 seconds. Sometimes when I want to have more control, I swipe as fast as I can without lifting my fingers, to prevent the inertia scrolling.

On the contrary, the scrolling in the message list (the right panel), feels much slower. A single fast swipe with inertia can only scroll over about 20 messages (text only, 2-3 lines each), and the distance scrolled with a single fast swipe without inertia is even less than a single press of PageUp/PageDown, much slower than before (prior 4.8.5).

If we want to compare the scrolling speed with a modern browser that uses the same API, take the current GitHub issue page for example, again on a 1080p monitor, 100% DPI scaling, with latest FireFox, window maximized, a single swipe with inertia can easily get me from top to bottom or vice versa, which also feels nice and fast to me.

The scrolling speed in the Settings pages might also be slow.

I'm using an ASUS laptop running Windows 10 22H2, with a Microsoft's Precision Touchpad compatible touchpad, all relevant settings are system default.

---

Also as I mentioned above, the "overscroll" effect should be implemented consistently throughout the app. Right now it's only there in the chat list, but not in the message list nor in the settings pages.

In Telegram's mobile clients (both iOS and Android), "overscrolling" at the bottom of a channel will take the user to the next channel that has unread messages, so you might want to implement that in tdesktop as well.

**Comment by john-preston** [comment] 2023-08-11 17:39
Yes, overscroll event is done in a custom scroll area implementation that is currently used only in chats list (still testing it), nice feedback on that one.

I guess the default Qt scroll area, used in messages list and settings and all other places handle my custom-generated scroll events (from the new API which I handle manually, not by Qt).

Later in the future all Qt-managed scroll areas are supposed to be replaced with mine own, like chats list right now, but maybe there is a possibility to fix the scroll in existing faster. I don't feel much difference in scrolling of chats list and other lists, which is strange with those reports. But I'll try to check more accurately.

**Comment by john-preston** [comment] 2023-08-11 17:40
For me scrolling in messages list and in Google Chrome work the same from a laptop touchpad.

**Comment by bb010g** [comment] 2023-08-15 08:19
> Later in the future all Qt-managed scroll areas are supposed to be replaced with mine own, like chats list right now, but maybe there is a possibility to fix the scroll in existing faster.

What are the benefits of replacing Qt's native scrolling?

**Comment by john-preston** [comment] 2023-08-15 10:44
@bb010g Qt native scrolling doesn't provide a way to handle modern touchpad events and implement overscrolling or handle scroll-start / scroll-end that is used in stories pull-out mechanics in the new version.

Also Qt uses old scrolling API (WM_MOUSEWHEEL), while all modern software (Google Chrome, Firefox, modern Windows apps like System Settings) use a modern API, like DirectManipulation, which provides a much smoother inertial scrolling and ability to handle different touch-scroll states correctly.

**Comment by kkalugin** [comment] 2023-08-23 06:50
just did a little test on my laptop with old version of client:

v4.8. 1 mouse wheel scroll = 1 item in chat list goes up
updatet client
v4.9.2. 1 mouse wheel scroll = 2 item in chat list goes up

1080p 100% scale. It seems like it DOES change with resolution/scailing

I personally prefered 1 item scroll

**Comment by kasumiru** [comment] 2023-08-25 12:37
I have the opposite - scrolling is not faster, but now it has become slower in chats. I have no problems in other programs - Firefox, Chrome, Slack. Only in telegram > 4.8.5 - scrolling is slow! Slow, not fast. Telegram Desktop 4.8.3 - scrolling speed is normal.

**Comment by kasumiru** [comment] 2023-09-13 14:28
people continue to suffer from "opened this issue on Jul 21 · 16 comments"

**Comment by f242** [comment] 2023-09-29 09:57
@john-preston 
when it will be fixed?
4k display, win 11 scale 200% telegram interface scale 220%
In 3 mouse wheel steps I have one screen almost completely scrolling chats list from bottom to up, it's very fast!
0 | 1 | 2 | 3
🟢🟢🟢🟢
🟢🟢🟢🔴
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🟢🔴🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🔴🟢🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🟢🟢🟢🟢
🔴🟢🟢🟢

**Comment by ilya-fedin** [comment] 2023-12-23 16:31
Can someone using Windows and having a touchpad build tdesktop with applied patch? That's likely to speed up fixing the issue a lot.

Does chat list (not message view) scrolling with a touchpad (not mouse wheel) depend on system scale (not Telegram scale)?

**Comment by kkalugin** [comment] 2024-01-01 10:04
4.14 back to normal? I'm scrolling one item in chatlist after update (finally)
I think it how it was before the issue

**Comment by john-preston** [comment] 2024-01-01 11:37
@kkalugin Yeah, @ilya-fedin did the trick finally.

**Closed** 2024-01-01 12:06 UTC
Labels: bug
