### ISSUE TITLE
Drag and drop a conversation into a folder

### ISSUE THREAD

**Issue by ehsan-mosadeq** [telegramdesktop/tdesktop#8823] opened 2020-10-14 10:23 UTC
Is there such a feature available in the current veriosn?

**Comment by ilya-fedin** [comment] 2020-10-14 10:47
no

**Comment by RememberTheAir** [comment] 2020-10-14 10:50
Duplicate of #7463, kinda contained in #7500. If it wasn't for the discussion that is already happening there, 7500 should be closed because it's a list of requests that should have each one its own issue

**Closed** 2020-10-14 11:00 UTC
