### ISSUE TITLE
[Feature request] Open each chat in separate window (desktop, linux)

### ISSUE THREAD

**Issue by m00nk** [telegramdesktop/tdesktop#981] opened 2015-08-09 11:02 UTC
Let telegram opens each chat in separate window.
1. Very comfortable to switch from one chat to another with Alt+Tab
2. Every chat will be able to have the different keyboard layout (one chat with english layout, another - with russian, etc). It is very useful.
3. user will be able to know how many unread messages in every chat (if the windows' titles will have the number of unread messages)

**Comment by Sushubh** [comment] 2015-08-13 22:09
+1

**Comment by navjotjsingh** [comment] 2015-08-13 22:11
+1

**Comment by auchri** [comment] 2015-08-15 07:15
Duplicate #533

**Comment by Qwerty-Space** [comment] 2016-01-25 21:56
I think it's a little different than multiple instances.

**Comment by m00nk** [comment] 2016-05-21 23:27
@auchri you closed this ticked without any comments about the feature I asked for. The multiple instances feature is not what I talked about.

Please, answer, are you going to add an ability to open every chat in the separate window with the separate keyboard layouts or not?

**Comment by stek29** [comment] 2016-05-23 00:04
@auchri Multiple instances is about multiple accounts.
However this one is about opening some chats in separate windows, while using one instance and one account.

**Comment by kirsan31** [comment] 2016-06-01 10:34
Yes, it is a very useful feature - may be realized it through the tabs interface?

**Comment by m00nk** [comment] 2016-06-01 12:14
using tabs is not a solution, because that way does not allow to use the different keyboard layout for each tab.

**Comment by m00nk** [comment] 2016-06-01 12:17
I have opened [another request](https://github.com/telegramdesktop/tdesktop/issues/2105)

**Comment by kirsan31** [comment] 2016-06-01 12:33
@m00nk 
> using tabs is not a solution, because that way does not allow to use the different keyboard layout for each tab.

No, it's possible, for example: [tabsrmm](http://wiki.miranda-ng.org/index.php?title=Plugin:TabSRMM/en) (miranda plugin), [TabLang](https://addons.mozilla.org/en-US/firefox/addon/tablang/) (firefox addon) etc...

**Comment by m00nk** [comment] 2016-06-01 19:15
@kirsan31 I do not understand, what is the differences between tabs and contact list like it is now?
Current layout has the contact/chat list, that list is the same thing as tabs, but vertical. Am I right?

![_2016-06-01_22-17-02](https://cloud.githubusercontent.com/assets/516574/15722393/2eef10a8-2846-11e6-9d73-d6598a62fdd6.png)

**Comment by m00nk** [comment] 2016-06-01 19:17
@kirsan31 Please read the features I wrote on first message. Tabs do nothing of them.

**Comment by terrycloth** [comment] 2017-05-09 05:57
I could open a new issue if needed, but this seems just related enough to be appropriate... Having multiple chats in the same window but still separate from the contacts could also be useful.

I had a friend today talking about how he wished he could rearrange the UI so that active conversations were separate from the contacts, so that he could see both but each would take relatively little space *on different monitors*.

**Comment by Qwerty-Space** [comment] 2017-05-09 12:07
I think it would be great if the chat list window had tabs for groups, channels, users, favourites, and bots, just like Plus Messenger.

Tuesday, 09 May 2017, 06:57a.m. +01:00 from Andrew Toskin notifications@github.com<mailto:notifications@github.com>:


I could open a new issue if needed, but this seems just related enough to be appropriate... Having multiple chats in the same window but still separate from the contacts could also be useful.

I had a friend today talking about how he wished he could rearrange the UI so that active conversations were separate from the contacts, so that he could see both but each would take relatively little space on different monitors.

**Comment by terrycloth** [comment] 2017-05-10 03:10
> I think it would be great if the chat list window had tabs for groups, channels, users, favourites, and bots, just like Plus Messenger.

I really like that idea too. Definitely a duplicate of #1107, though.

**Comment by cryptoneep** [comment] 2017-10-24 17:39
yeas please!

**Closed** 2018-01-11 00:50 UTC

**Comment by epukstas** [comment] 2018-12-03 13:03
The use of old Skype separate windows option become a strong habit. Now in Telegram I often send a message to another contact by mistake. When quicktyping to multiple contacts then clear separation of chat windows is very useful. Now all chats look the same style and it is problem to quickly identify the right chat.

**Comment by vytjak** [comment] 2020-04-20 09:33
+100
