### ISSUE TITLE
Could not change download path with custom folder cause changing files only, not dirs..

### ISSUE THREAD

**Issue by emlen** [telegramdesktop/tdesktop#7356] opened 2020-03-10 18:43 UTC
Could not change download path with custom folder cause changing files only, not dirs..

### Steps to reproduce
1. Settings -> Advanced -> Download path -> Custom folder...
2. trying to select directory:
# ls -laht /tmp/tg/
drwxr-xr-x  2 active_user users  40 Mar 10 21:38 .
3. Open button in dialog not active

![tg_failure_screenshot](https://user-images.githubusercontent.com/12050586/76347766-2fc49a00-6318-11ea-8bd4-ffd7f69405f3.png)

**Comment by ilya-fedin** [comment] 2020-03-11 13:15
Duplicate of #7911

**Closed** 2020-03-11 13:50 UTC
