### ISSUE TITLE
The new "message author's avatar at last message" UI is often very confusing in group chats

### ISSUE THREAD

**Issue by fillest** [telegramdesktop/tdesktop#2827] opened 2017-01-12 21:23 UTC
In group chats people often post multiple consecutive short messages. And in the new Telegram version author's avatar appears at the last consecutive message. The chain is very often long enough to be very confusing, because the avatar image gets decoded much faster by the brain than the nickname text, which is visually merged with the messages. It is especially confusing when e.g. there is a single message by one person and then multiple by another, it reads as if these messages were by the first person.

I think is was a faulty UI change, but please at least make it optional - the previous avatar UI was good,

### Configuration
**Operating system:**
Windows

**Version of Telegram Desktop:**
1.0

**Comment by Geobert** [comment] 2017-01-16 09:59
Don't know if hard to do with current code state but here an idea: make the avatar "floating" and following a chain of messages from this avatar.

**Comment by stek29** [comment] 2017-01-17 00:08
@Geobert it is floating...

**Comment by izhovkin** [comment] 2017-01-17 02:14
@stek29 it should be floating sticking to the top of message, not the bottom, as it was before the 1.0 update.

**Comment by stek29** [comment] 2017-01-17 10:00
Oh, then it seems that #2836 was a duplicate of this.
And both of them can be closed :D

**Closed** 2017-01-17 10:01 UTC

**Comment by fillest** [comment] 2017-01-17 10:08
And what is the reason for closing? Refusing to fix?

**Comment by john-preston** [comment] 2017-01-17 10:10
@fillest Because it is intended and not meant to be "fixed". The senders name marks the top of the message or messages block and the senders photo marks the bottom of the message or messages block.

**Comment by Geobert** [comment] 2017-01-17 10:28
@stek29 didn't noticed that, it's great :D

**Comment by izhovkin** [comment] 2017-01-17 10:56
@john-preston The fact that it was intended does not mean that it is good. This change causes problems in UX, see the origintal post:
> The chain is very often long enough to be very confusing, because the avatar image gets decoded much faster by the brain than the nickname text, which is visually merged with the messages. It is especially confusing when e.g. there is a single message by one person and then multiple by another, it reads as if these messages were by the first person.

The avatars are much more distinguishable then the sender's name, and there is no reason to mark the bottom of the message with them, since the bottom is always clearly delimited with next author name/avatar.

**Comment by MasterGroosha** [comment] 2017-01-17 11:54
@john-preston When the block of messages is started by image/sticker, no sender name is on the top of the block. Sometimes it can be confising because you either should try to remember who exactly has that avatar on the left or even click on it and open profile.
With text-only messages it's okay.
