### ISSUE TITLE
Sent MP4 files treated as GIF's

### ISSUE THREAD

**Issue by dennisbos84** [telegramdesktop/tdesktop#2053] opened 2016-05-19 09:39 UTC
### Steps to reproduce
1. In a chat, drag-and-drop an (audioless) MP4 file.
2. Video file is uploaded.
3. Uploaded file is shown as a GIF in Telegram clients.
4. GIF plays looped in desktop/web-version, but not in the Android client.
### Expected behaviour

MP4 files should be treated as video files, not GIF's
### Actual behaviour

MP4 files sent from desktop/web client are treated as GIF's
### Configuration

**Operating system:** Mac OS X 10.11.4

**Version of Telegram Desktop:** Version 0.5.4 at https://web.telegram.org/

**Comment by diazbastian** [comment] 2016-05-22 03:50
@dennisbos84 I can't replicate this behavior:

•  All short video in mp4 format (QuickTime/h.264 without audio) is uploaded as GIF and played as such in other Telegram clients (Webogram, TDesktop, Android and iOS) using TDesktop 0.9.49
• Any other mp4 video with audio is uploaded as file on TDesktop.

Note: For some time, Telegram uses mp4 files as "GIF" on its platform (like Twitter) https://telegram.org/blog/gif-revolution

**Comment by leleckso** [comment] 2016-05-25 17:14
The exact same thing happened to me a few times. Only on mobile though. +1

**Comment by Kondra007** [comment] 2016-06-11 15:58
So no chance to send mp4's like videos from TDesktop?

**Comment by auchri** [comment] 2016-06-11 16:03
@Kondra007 works for me

![image](https://cloud.githubusercontent.com/assets/5092164/15986057/bc9fa4de-2ffe-11e6-8d4e-613395e39957.png)

**Comment by Kondra007** [comment] 2016-06-11 16:08
And doesn't work for me. Strange.

**Comment by auchri** [comment] 2016-06-11 16:09
@Kondra007 whats your exact steps? Whats the result?

**Comment by Kondra007** [comment] 2016-06-11 16:11
@auchri 
1) Drag & Drop mp4 video into TDesktop chat. Result: Gif.  
2) Choose "Send - File" in chat, select mp4 video. Result: Gif.

TDesktop 0.9.49dev, Windows 8.1 x64

**Comment by auchri** [comment] 2016-06-11 16:13
Does it work with this video:

[small.zip](https://github.com/telegramdesktop/tdesktop/files/310352/small.zip)

**Comment by Kondra007** [comment] 2016-06-11 16:16
@auchri Nope. The file is sent (in both ways) as "file" (with preview on Android and just as file on Desktop).

**Comment by auchri** [comment] 2016-06-11 16:17
@Kondra007 after a restart of tdesktop the file gets displayed correctly

**Comment by Kondra007** [comment] 2016-06-11 16:25
@auchri I've recorded a small video from my Android phone, copied it to PC and sent via TDesktop. It was treated as GIF: https://yadi.sk/i/xNLNCo0msRV2W

**Comment by Lachmoewe** [comment] 2016-06-17 12:19
Just had the same problem when trying to share this mp4:

[video.mp4.zip](https://github.com/telegramdesktop/tdesktop/files/320417/video.mp4.zip)

**Comment by stek29** [comment] 2016-12-22 23:27
Isn't this server side issue?

**Comment by Tynach** [comment] 2017-01-24 06:49
Telegram converts .gif files server-side to .mp4 files with no audio track, and using the H.264 video codec. It still *calls* them gifs, but they are not .gif files. If you right-click and save-as, it still has a .mp4 file extension.

If you upload such a .mp4 (H.264 video codec, absolutely no audio track, under 10 MiB in size), it will show up like a 'gif' that was converted by the server would... But it will **not** be in the .gif file format.

It sounds like people here are getting confused about the difference between Telegram *calling* something a 'gif', and something *actually* being a .gif.

In my opinion, the only real bug here is that Telegram still calls them 'gif' files, instead of something else like 'mp4s' or maybe 'Clips' (or something like that).

**Comment by stek29** [comment] 2017-01-25 21:47
@Tynach because most people think that "animated &looped image = GIF". And they don't really care what those gifs are really are.

**Comment by Lachmoewe** [comment] 2017-01-26 01:11
The problem ist that with really high resolution but short playback time, filesize can still be below 10mb. Because telegram will then autoplay the "gif", you get a huge amount of load on your device. I dont really know if this should be treated in the client though, as it seems like an issue to be dealt with on the server side.

**Comment by Tynach** [comment] 2017-01-26 01:37
@Lachmoewe, that's why both the desktop and Android client have an option in the settings to disable auto-playing 'gifs' (and I presume the iOS client has it as well, but I have no way of confirming that), and another setting for choosing if they auto-download.

The 'problem' you speak of is already solved.

**Comment by Lachmoewe** [comment] 2017-01-26 20:52
Well while it's good to stop it from autoplaying (even though that setting is kinda hidden), I can't find a way to stop a clip from being played once it started. I always have the telegram window open, so whenever a bigger clip just got posted to the group I currently have open, I have to switch to a different chat in order to keep the cpu-fan quiet. So no, the problem hasn't really been solved. Adding a possibility to stop it would be an option, but maybe there is an even more elegant solution that I can't think of right now.

**Comment by Tynach** [comment] 2017-02-10 07:38
@Lachmoewe, the easier solution is to click on the gif again to stop it playing. I think you used to have to scroll up until it was no longer visible (and then scrolling back down would have it stopped), but right now it works to just click it to play, and click again to stop.

**Comment by Aokromes** [comment] 2017-03-31 12:49
maybe fixed after 1.0.27?

**Comment by massimiliano-leoni** [comment] 2017-05-18 15:28
I should also add that when MP4s are treated as gifs they cannot be put to full-screen mode, and this is what I found most annoying the time this happened to me.

**Comment by stek29** [comment] 2017-05-18 17:16
@massimiliano-leoni Android and iOS apps can play GIFs in Fullscreen

**Comment by massimiliano-leoni** [comment] 2017-05-18 17:20
@stek29 Mmm, how? On Android, if I tap on a gif it starts playing, and if I tap again it stops. The menu does not give options to go full screen either.

**Comment by ugaldew** [comment] 2017-05-19 10:31
... upload video using web version it works...

**Comment by AndydeCleyre** [comment] 2018-08-10 02:55
I sent an mp4 **with** audio and it was uploaded as a gif (no sound, of course).

`1.3.10-2`, Arch Linux

```
General
Complete name                            : four_years.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 3.13 MiB
Duration                                 : 20 s 25 ms
Overall bit rate                         : 1 311 kb/s
Writing application                      : Lavf58.12.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 20 s 25 ms
Bit rate                                 : 909 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (23976/1000) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.018
Stream size                              : 2.17 MiB (69%)
Writing library                          : x264 core 152 r2854 e9a5903
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 20 s 22 ms
Bit rate mode                            : Constant
Bit rate                                 : 394 kb/s
Channel(s)                               : 2 channels
Channel(s)_Original                      : 6 channels
Channel positions                        : Front: L C R, Side: C, Back: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 964 KiB (30%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
```

**Comment by hk0O7** [comment] 2018-09-26 17:08
It's still happening on version 1.3.14 with .mp4 files with no sound.

**Comment by stek29** [comment] 2018-09-28 08:59
@hk0O7 it *should* happen for mp4 Files with no sound -- that's a feature.
This issue is about files *with* sound being sent as GIFs.

**Comment by ariebrainware** [comment] 2018-12-04 08:33
Still, happen in 2018. Where is the developer?

**Comment by john-preston** [comment] 2018-12-04 08:51
@ariebrainware .mp4 files that have no audio track are treated as GIF animations (played in loop inside chat) by all apps and by server side. This is the intended behaviour, nothing to fix, sorry.

**Comment by Aokromes** [comment] 2018-12-04 08:54
i tested one mp4 with sound and works properly, so this ticket can be closed.

**Comment by AndydeCleyre** [comment] 2018-12-04 15:40
@john-preston did you miss my last comment here? If you can't reproduce I'll try to upload a file here that exposes the bug.

**Comment by john-preston** [comment] 2018-12-04 15:42
@AndydeCleyre Yes, please.

**Comment by john-preston** [comment] 2018-12-04 15:43
@AndydeCleyre Also you can send me it in .zip archive to t.me/preston

**Comment by AndydeCleyre** [comment] 2018-12-04 19:14
[four_years.zip](https://github.com/telegramdesktop/tdesktop/files/2645715/four_years.zip)

**Comment by john-preston** [comment] 2018-12-05 10:05
@AndydeCleyre Thanks. I've tried this example and I see that tdesktop sends this file as a video file, but the server adds "animated" attribute, like when converting soundless .mp4 or .gif to a "gifv" animation. I'll ask the server-side guys if it's a bug.

**Comment by ariebrainware** [comment] 2018-12-07 09:58
> @ariebrainware .mp4 files that have no audio track are treated as GIF animations (played in loop inside chat) by all apps and by server side. This is the intended behaviour, nothing to fix, sorry.

Oke, no big deal.

**Comment by john-preston** [comment] 2019-03-01 13:09
@AndydeCleyre This one was fixed on the server-side.

**Closed by john-preston** 2019-03-01 13:09 UTC
Labels: bug

**Comment by bedilbek** [comment] 2020-03-07 04:20
@john-preston Why did you close it. This bug is still active on all TDesktop clients even if it is fixed on the server-side. Please take a look at the TDesktop client. I do not know why this bug is still active because it is already a year I upload all my h264 videos in zip format. I am curious why no one complains about this issue

**Comment by MJafarMashhadi** [comment] 2020-05-28 15:18
I always thought this was an actual feature and this issue is going to be "woooosh"'d

**Comment by RememberTheAir** [comment] 2020-05-28 16:18
@MJafarMashhadi yes this is actually intended - every mp4 file without sound is handled like a GIF. This is why this issue is closed

**Comment by bedilbek** [comment] 2020-05-28 16:21
@RememberTheAir Do you think all people are dumb? Of course I have checked with all the combinations where video had a sound and where it had no sound. I believe you have to dig deeper before answering here and creating false conception on others!

**Comment by RememberTheAir** [comment] 2020-05-28 19:34
> I believe you have to dig deeper before answering here and creating false conception on others!

Oh sorry next time I will ask you for all the recordings of you uploading several video files to Telegram, since you provided literally zero context or example file to your previous comment. Anyway, my comment wasn't an answer to your comment. I was answering to MJafarMashhadi explaining him that it's intended that mp4 videos are uploaded as GIFs, if they have no sound.

Telegram Desktop on my machine works correctly, it uploads files as videos if they have an audio. If it doesn't work for you, do a proper bug report and attach to your comment your current setup and maybe some example of file that is causing issues. As a way to mitigate this undesired behavior, you can try [Kotatogram](https://t.me/kotatogram). It shows the player controls even when you play a GIF, so there's  no difference between GIFs and videos there

**Comment by kasumiru** [comment] 2021-01-28 20:41
UP! the bug was here. If screen capture video in mp4, without sound, Telegram Desktop have not the player controls. Telegram Desktop 2.5.6
