### ISSUE TITLE
[Feature Request] In groups hide messages from some users.

### ISSUE THREAD

**Issue by WrongBit** [telegramdesktop/tdesktop#9048] opened 2020-11-11 10:55 UTC
In groups where you're not admin, you can do nothing with messages/people. Some people lose any sense of culture and send inappropriate messages - from advert to clear offence. Every time pushing admin - not a solution, he can be busy, irrelevant, etc.
It could be nice to hide/make muddy messages from specific people. Such messages still appear in your chat window, but they will be collapsed or drawn in gray to be easier ignored.

**Comment by RememberTheAir** [comment] 2020-11-11 11:00
Duplicate of #1025, #1281, #5492

**Closed** 2020-11-11 12:42 UTC

**Comment by WrongBit** [comment] 2020-11-12 02:13
@Aokromes , @RememberTheAir : hey, what the hell you close issue if NOBODY still assigned to fix duplicate issues?? At least one of duplicates have to be in progress.

**Comment by RememberTheAir** [comment] 2020-11-12 07:47
That doesn't mean we should keep a thousand issues opened asking for the same thing. I mentioned only three issues because that's where most of the discussion happened, but there are actually like 10 duplicates or so. Also #1025, which is the oldest one among those, is closed and labeled as "api issue", which means that no work is going to be done on the desktop app until the API provides some methods to block users in groups. So no, "at least one of duplicates have being in progress" is not required to close duplicate issues

**Comment by WrongBit** [comment] 2020-11-12 13:03
If you read carefully my request, I said nothing about blocking of users. I want messages of "undesirable" users being collapsed in the group chat! Meaning NO ANY CHANGES are required in API - just GUI feature. Please be careful before you mark request as "duplicate" - they can look similar, but actually not.

**Comment by RememberTheAir** [comment] 2020-11-12 22:09
It's still not going to be implemented because it would be inconsistent with the features offered on other clients. The reason why no one picked up the implementation requested in the issues I linked applies to your feature request too - essentieally both your request and the linked ones are asking for a way to hide some users' messages in a group chat, which is something that no other official Telegram allows to do: tdesktop is not going on its own way with custom features that would impact this much on the user experience
