### ISSUE TITLE
Feature request: Home and End keys

### ISSUE THREAD

**Issue by jeffythedragonslayer** [telegramdesktop/tdesktop#5220] opened 2018-10-03 00:03 UTC
It would be nice if pressing the Home or End keys would jump to the beginning or end of a chat just like web browsers.  Page up and down do work but home and end seem to do nothing right now.

Tested on Windows 10, Telegram version 1.3.14

**Comment by RememberTheAir** [comment] 2018-10-03 06:29
Duplicate of #4699

**Comment by jeffythedragonslayer** [comment] 2018-10-03 06:34
Hmm ok, I tried searching for 'home' and 'end' and didn't find that one.

**Closed** 2018-10-07 23:40 UTC

**Comment by hooddy** [comment] 2019-04-18 09:37
> 
> 
> Duplicate of #4699

So its planned to implement? Its obviously feature I wonder why it still absent.
