### ISSUE TITLE
Latest KDE (plasma) left click on tray icon is not working

### ISSUE THREAD

**Issue by kvaster** [telegramdesktop/tdesktop#3132] opened 2017-03-21 08:13 UTC
Download telegram desktop from main site (it will download 1.0.14 alpha version, not 1.0.12).

1. Start telegram, perform left click on tray icon several times - telegram will be shown and afte hidden to try icon.
2. Wait for telegram to be updated automatically to next version (1.0.24).
3. Perform left click on tray icon - nothing happens. Only right click opens menu.

Telegram stopped responding to left click on tray icon starting from 1.0.15 version.

**Comment by john-preston** [comment] 2017-03-21 08:22
@kvaster Please find out which version exactly has broken this. You can find binaries for the last releases here:

https://github.com/telegramdesktop/tdesktop/releases/

You can use something like binary search to find which is the last version where it is working (try out 1.0.19 then 1.0.16 or 1.0.22 etc.)

**Comment by kvaster** [comment] 2017-03-21 08:23
Ok. No problems. Will do it in a few minutes.

**Comment by kvaster** [comment] 2017-03-21 08:34
1.0.14 is OK
and
1.0.15 is NOT OK

**Comment by Aokromes** [comment] 2017-03-31 09:01
#2451 ?

**Comment by xvitaly** [comment] 2017-03-31 10:54
> #2451 ?

Too old issue. Everything works fine for me on 1.0.14, but broken in 1.0.15 alpha.

**Comment by Aokromes** [comment] 2017-03-31 11:04
It's called regression, the bug was fixed, the ticket remained opened, it bugged again :P

**Comment by ea4eoz** [comment] 2017-03-31 11:08
After installing gir1.2-appindicator3-0.1 in Debian Sid + Plasma 5 everything is working fine.

**Comment by subdiff** [comment] 2017-03-31 22:43
> After installing gir1.2-appindicator3-0.1 in Debian Sid + Plasma 5 everything is working fine, except the double click on the icon. I must raise telegram from the right click menu.

This is most certainly unrelated to the issue of "one time left click doesn't open Telegram" discussed here.

**Comment by ea4eoz** [comment] 2017-03-31 23:28
The issue: Latest KDE (plasma) left click on tray icon is not working

Solution: gir1.2-appindicator3-0.1

And it's not related. Ok.

**Comment by subdiff** [comment] 2017-04-01 14:54
Nope. What did you mean with "double click" in the first place? There is no double click in play anyway. Telegram should be raised/closed on single click.

gir1.2-appindicator... is the Ubuntu lib for system tray icons. This should be unrelated, because Plasma raises Telegram via QSystemTrayIcon methods, as it's written in Qt.

After you installed the lib, what exactly did change for you? For me it still didn't work afterwards.

**Comment by Rafagd** [comment] 2017-04-04 19:09
Same problem on Mate-Desktop. Telegram is on tray. Left click used to bring it to foreground, but now it opens the context menu (as if I've right clicked it.)

Mate 1.16.1
Telegram 1.0.26

**Comment by john-preston** [comment] 2017-04-04 19:10
@Rafagd This will be fixed in the next version.

**Comment by auchri** [comment] 2017-04-04 19:11
Related commit: https://github.com/telegramdesktop/tdesktop/commit/c1aa1c5a0f26b29fce1307ba455f9887e7c1c1ec

**Closed** 2017-04-04 19:10 UTC

**Comment by qthree** [comment] 2017-04-07 06:04
@john-preston Version 1.0.29
1. Open Telegram
2. Click another maximized window
3. Click tray icon
4. Strange behavior, needs many clicks to reopen and then you can't hide window by clicking tray icon.

**Comment by emvaized** [comment] 2020-01-21 22:52
> @john-preston Version 1.0.29
> 
>     1. Open Telegram
> 
>     2. Click another maximized window
> 
>     3. Click tray icon
> 
>     4. Strange behavior, needs many clicks to reopen and then you can't hide window by clicking tray icon.

I face this problem too. For me the solution was to set Telegram to be always on top of windows in Plasma settings -- now it works as expected.
