### ISSUE TITLE
No tray icon since update 0.7.16 on GNOME 3 Fallback Mode

### ISSUE THREAD

**Issue by EmptyStackExn** [telegramdesktop/tdesktop#491] opened 2015-02-18 01:19 UTC
Hello,

I am using Ubuntu 12.04 with GNOME 3 Fallback Mode and the Telegram tray icon was doing just fine **until** the new 0.7.16 release. Indeed, before that release, the tray icon was an **indicator applet** that Ubuntu *perfectly* handled with the **Indicator Applet Complete** of GNOME Panel.

Since the new release, it appears you made a design choice to put the tray icon in the **Notification bar** of GNOME Panel. However, the former now does not work and **no** tray icon appears. Even if an instance of Telegram was running, there would be no tray icon at all.

Same problem with previous versions of Dropbox. Appears that the **Notification bar** is buggy... You should go back and use the old version with **Indicator Applet Complete**.

**Comment by slamath** [comment] 2015-02-18 04:49
mine too.. i'm using elementary os freya. it is working fine in previous version, but it disappear now..

**Comment by arkty** [comment] 2015-02-18 07:51
Same on Elementary OS luna.

**Comment by koshi-dono** [comment] 2015-02-18 09:57
Same on Elementary OS luna.

**Comment by haimat** [comment] 2015-02-18 10:39
I can confirm, the tray icon is missing on Xfce 4.10 on Debian since last version 0.7.16. It used to work fine before.

**Comment by halturin** [comment] 2015-02-18 12:19
confirm. gnome 3 classic (3.14). Debian Jessie.

**Comment by Madh93** [comment] 2015-02-18 22:56
Same problem in Xubuntu 14.04 (XFCE 4.10).

**Comment by telegramdesktop** [comment] 2015-02-19 07:06
Many messages about better working icon through QSystemTrayIcon instead of libappindicator, so I've left libappindicator only for Unity. After some more reports I saw I should return libappindicator in p
Pantheon and perhaps some others. Can you please tell what does "echo $XDG_CURRENT_DESKTOP" tell you in Terminal so I could switch back from QSystemTrayIcon to libappindicator in your case?

**Comment by nshopik** [comment] 2015-02-19 08:55
@Madh93 Yeah uncheck/check "Show tray icon" helps on XFCE

**Comment by starg09** [comment] 2015-02-19 17:01
Hi, having the same issue over here. Until 0.7.13 (Haven't updated my netbook for a few days), the icon worked just fine. Now, in my computer where I just installed it (0.7.17), the tray icon won't show up. I'm using Manjaro 0.8.12 XFCE, and as some have mentioned, if I toggle off and on the "Tay icon" setting, it shows up. But each time I close it entirely, and reopen it, the icon is gone again. If I use that new start in tray option, the program opens up as usual, but the icon appears (Not a very practical solution).

**Comment by arkty** [comment] 2015-02-19 17:16
@telegramdesktop 
arkty@alcorb:~$ echo $XDG_CURRENT_DESKTOP
Pantheon

**Comment by EmptyStackExn** [comment] 2015-02-20 10:26
@telegramdesktop 
```
$ echo $XDG_CURRENT_DESKTOP
GNOME
```

**Comment by arkty** [comment] 2015-02-20 12:20
@telegramdesktop Elementary Luna(Pantheon): fixed in latest version. All fine.

**Comment by halturin** [comment] 2015-02-20 12:25
$ echo $XDG_CURRENT_DESKTOP
GNOME

$ cat /etc/issue
Debian GNU/Linux 8 \n \l

fixed in latest update (ver 0.7.17).

**Comment by EmptyStackExn** [comment] 2015-02-20 15:48
Now fixed in 0.7.17. Thanks :+1:

**Closed** 2015-02-25 22:31 UTC

**Comment by jmayday** [comment] 2015-06-20 10:23
Unfortunately unchecking/checking "Show tray icon" does't work for me (Archlinux with XFCE 4.12). Telegram version: 0.8.24.

**Comment by aroblu94** [comment] 2015-06-23 20:28
On Fedora 22 with GNOME Shell 3.16 there isn't the "Show tray icon" option under Telegram > Settings and the tray icon does not appear.
Telegram 0.8.24

**Comment by ejiek** [comment] 2015-06-25 14:50
Telegram 0.8.32 still no tray indicator for Fedora 22 with Gnome Shell 3.16.2

**Comment by aroblu94** [comment] 2015-06-28 12:23
Ok, after installing *libappindicator* I can now see tray icon on Fedora 22 (GNOME Shell 3.16.2), thanks @ejiek

**Comment by gromoleg** [comment] 2015-09-09 08:10
having same problems in Ubuntu
$ echo $XDG_CURRENT_DESKTOP
MATE
$ cat /etc/issue
Ubuntu 14.04.3 LTS \n \l

**Comment by KristobalJunta** [comment] 2015-10-11 12:35
Fedora 22 Gnome 3.16 also worked after installing *libappindicator*
Thanks @ejiek

**Comment by gromoleg** [comment] 2015-10-11 13:13
but that solution not working on Ubuntu 14 (Mate)

**Comment by rbieb** [comment] 2015-10-21 16:09
I do have a tray icon, but I can't click on it.

Fedora 22 with gnome 3.16.

**Comment by gracca** [comment] 2015-11-11 18:39
Try icon appeared after installing `libappindicator` in Fedora 23 under Gnome 3.18 (using `telegram-desktop-0.9.10-1.fc23.x86_64`).
