### ISSUE TITLE
Touch Keyboard

### ISSUE THREAD

**Issue by rdrrdl** [telegramdesktop/tdesktop#2882] opened 2017-01-19 16:54 UTC
### Steps to reproduce
1. Open telegram
2. Open touch keyboard (windows 10)
(3.give up and use telegram chrome app...) 

### Expected behaviour
Tell us what should happen
The "write a message" box should go up, together with the whole program, to the top of the screen. So that it is possible to see what is being written without the keyboard covering
### Actual behaviour
Tell us what happens instead
The program does go to the top of the screen but not enough. the touch keyboard totally blocks the box i'm typing in.
### Configuration
**Operating system:**
Win 10, 1607
**Version of Telegram Desktop:**
1.0.2
![tt](https://cloud.githubusercontent.com/assets/25228423/22116199/713bcf8a-de78-11e6-96c2-c00e78d62f58.PNG)

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment] 2017-01-19 16:57
Duplicate of #1297

**Closed by auchri** 2017-01-19 16:57 UTC
