### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by UnAfraid** [telegramdesktop/tdesktop#1029] opened 2015-08-24 14:14 UTC
Hello,

I adore the Desktop Telegram client, but here are some things that would make it even better in my opinion:

Can you please add some hot keys for switching between the chats like alt + 1, 2, 3, 4.

Also when you send a link with CTRL + Enter to do not create preview.

Also would be pretty nice if there was some markdown supported, at least bold, italic, etc..

Thanks, keep up the good work!

**Comment by auchri** [comment] 2015-08-24 14:18
Duplicate of other issues

**Closed by auchri** 2015-08-24 14:18 UTC

**Comment by UnAfraid** [comment] 2015-08-24 16:56
@auchri can you be more specific i suggested 3 different things!

**Comment by auchri** [comment] 2015-08-24 17:27
#687 #330 ... use search

**Comment by UnAfraid** [comment] 2015-08-24 19:29
https://github.com/telegramdesktop/tdesktop/issues/330 is around one year old, seems forgotten so i am bring it up again

**Comment by auchri** [comment] 2015-08-24 19:31
It's still not possible on the mobile apps, so it won't be implemented in the desktop app
