### ISSUE TITLE
App Crashes when Playing Audio [Linux Mint]

### ISSUE THREAD

**Issue by aibnsamin** [telegramdesktop/tdesktop#24032] opened 2022-02-06 13:43 UTC
### Steps to reproduce

1. Open the app
2. Navigate to a chat
3. Find an audio
4. Play it
5. App freezes, no audio
6. App crashes

### Expected behaviour

1. Open the app
2. Navigate to a chat
3. Find an audio
4. Play it
5. Audio plays

### Actual behaviour

Upon clicking the play button, the app freezes, and eventually it crashes.

### Operating system

Linux Mint 19.3 Cinnamon

### Version of Telegram Desktop

3.5.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment] 2022-02-06 18:26
Is this specific to some audio files? Because I can't reproduce with the provided reproduction steps and random audio tracks.

**Comment by dsmotrov** [comment] 2022-02-06 18:45
+1 for same Telegram version on Ubuntu 18.04.6 LTS x86_64 with kernel  5.4.0-97-generic. Absolutely same issue when trying to play audio message. Issue appeared right after upgrade to this Telegram version.

**Comment by gashloog** [comment] 2022-02-06 21:41
+1 for same Telegram Desktop version (3.5.1) on Fedora 31 with kernel 5.8.18. Exactly same issue: freezes when playing audio files, voice messages AND "round video messages"... videos play normal...

**Comment by ilya-fedin** [comment] 2022-02-06 21:45
People who have the app installed with the binary from desktop.telegram.org can send a crash report and post a crash report tag here. That would help a lot.

**Comment by gashloog** [comment] 2022-02-06 23:43
sry, total github-noob here...

how would i do that? copy & paste the console-output? "crash report tag"?
sorry...

Am So., 6. Feb. 2022 um 22:45 Uhr schrieb ilya-fedin <
***@***.***>:

**Comment by walknotes** [comment] 2022-02-07 02:45
+1 the same here.
Telegram desktop version 3.5.1, Debian 10, kernel Linux 5.2.0-2-amd64 x86_64, 
right after update to 3.5.1,  click any audio message, telegram freeze. Kill the process or reboot, issue still exists, keep the same.
Do we have a  [**Back to Previous Version**] function,  to solve the same issue in the future?

**Comment by AlxLeon** [comment] 2022-02-07 11:28
Kubuntu 21.10, same thing.
It hangs with these messages:
`[2022.02.07 14:19:30] OpenGL: QOpenGLContext created, version: 4.4.
[2022.02.07 14:19:30] OpenGL: [TRUE] (OverlayWidget)
[2022.02.07 14:19:30] Notification daemon product name: Plasma
[2022.02.07 14:19:30] Notification daemon vendor name: KDE
[2022.02.07 14:19:30] Notification daemon version: 5.22.5
[2022.02.07 14:19:30] Notification daemon specification version: 1.2
[2022.02.07 14:19:30] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, persistence, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[2022.02.07 14:20:00] Audio Info: recreating audio device and reattaching the tracks
`
But it seems that reboot solved the issue for me. I was able to reproduce it only once after rebooting.

Multiple attempts to reproduce:
`[2022.02.07 14:20:00] Audio Info: recreating audio device and reattaching the tracks
[2022.02.07 14:20:46] Audio Info: Closing audio playback device.
[2022.02.07 14:22:18] Audio Info: recreating audio device and reattaching the tracks
[2022.02.07 14:22:41] Audio Info: Closing audio playback device.
[2022.02.07 14:22:50] API Warning: not loaded minimal channel applied.
[2022.02.07 14:22:50] API Warning: not loaded minimal channel applied.
[2022.02.07 14:22:52] Audio Info: recreating audio device and reattaching the tracks
[2022.02.07 14:23:15] Audio Info: Closing audio playback device.
[2022.02.07 14:25:54] Audio Info: recreating audio device and reattaching the tracks
[2022.02.07 14:25:57] Audio Info: Closing audio playback device.
`

**Comment by mgo1977** [comment] 2022-02-07 15:08
Exactly same behaviour here. Application freezes after trying to reproduce any audio.

**Comment by edelmoral** [comment] 2022-02-08 08:49
Same here, everything was OK with previous versions, now if I play any voice message the app freezes (3.5.1).

**Comment by ilya-fedin** [comment] 2022-02-08 10:21
Please, no more 'same issue' messages, they're useless. If you want to help, see https://github.com/telegramdesktop/tdesktop/issues/24032#issuecomment-1030920966.

**Comment by john-preston** [comment] 2022-02-08 15:11
@aibnsamin @dsmotrov @gashloog @walknotes @AlxLeon @mgo1977 @edelmoral 

Can you please check this version:

https://td.telegram.org/tlinux/tsetup.3.5.2.tar.xz

and report here if it plays audio / voice messages fine or not?

**Comment by mgo1977** [comment] 2022-02-08 15:21
@john-preston It works perfectly for both, audio and video

**Comment by dsmotrov** [comment] 2022-02-08 15:39
@john-preston I Can confirm that 3.5.2 resolved issue with audio messages on Ubuntu 18.04. Thank you !

**Comment by john-preston** [comment] 2022-02-08 16:28
Thanks for the confirmation.

**Closed by john-preston** 2022-02-08 16:28 UTC
Labels: bug, waiting for answer

**Comment by edelmoral** [comment] 2022-02-08 18:13
@john-preston  3.5.2 fixes the issue with voice messages on Debian Buster with KDE. Thanks!!

**Comment by gashloog** [comment] 2022-02-08 19:28
@john-preston everything's cool again with 3.5.2. thank you for fixing!
