### ISSUE TITLE
Use default sound output device

### ISSUE THREAD

**Issue by lpfann** [telegramdesktop/tdesktop#418] opened 2015-01-19 15:21 UTC
I used my headphones, which are my default audio output device.
But the program played back the audio of a voice message through my speaker system.

**Comment by mirhl** [comment] 2015-01-19 17:39
Could be related to #179, where changing default audio output does nothing

**Comment by julianxhokaxhiu** [comment] 2015-08-08 22:18
I confirm that the bug still persists on Windows 10

**Comment by zackpollard** [comment] 2016-05-30 17:30
This is still an issue now, over 6 months later, any idea if this is going to be fixed any time soon as it is a pretty major issue for anyone who switches audio devices frequently, such as between headphones and speakers. I have frequently had issues where I am using my headphones and telegram has played audio out of my speakers instead, which is not good in certain situations.

**Comment by XylexRayne** [comment] 2016-06-23 04:16
I too confirm this issue persisting on windows 7 & 10. I just moved from 7 to 10 yesterday.
I use Wireless Turtle beach headphones that I take with me to work everyday. When the headphones are out of range or off, that Audio device is no longer seen by Windows, and windows makes my TV the default audio device. This breaks Music/Audio clip playback in Telegram till I reconnect my headset and actually disable my TV as an output device.

**Comment by john-preston** [comment] 2016-06-26 15:47
It looks like the OpenAL library, which is used for all sound output in tdesktop, is not handling the device switch and even doesn't have any callbacks about the default device change. I'm not sure how to fix that in an easy way (without migrating to some other sound output library).

**Comment by mirh** [comment] 2016-06-26 16:03
[?](http://forum.devmaster.net/t/changing-the-output-device-with-openal/5697/7)

**Comment by john-preston** [comment] 2016-06-26 16:33
@mirh This looks like a way to get a list of all sound devices in OpenAL and then destroy old one and create new one from that list. There is no code or explanation for following the default sound output device (and change it in the moment the default one is changed in the OS). Of course, you can set up a timer and each second query the default device to see if it has changed.. But I'm not yet ready for that :/

**Comment by julianxhokaxhiu** [comment] 2016-07-11 11:02
What about a solution [mentioned here](http://forum.devmaster.net/t/changing-the-output-device-with-openal/5697/4)?

There's even a snippet code which may help you understand how to implement that. Does the real issue actually resides on the fact that we're enumerating and using the real device and not the software layer provided from the OS? ( DirectSound for example on Windows )

Thanks for still trying to dig deeper into this topic. It's currently becoming more and more annoying to continuously close Telegram, switch audio source and re-open it, into a routine when you have to switch audio context continuously.

**Comment by jaysonsantos** [comment] 2016-08-31 15:51
This also happens on linux, I tried with both arch linux, gentoo and ubuntu. In my case I have a bluetooth device and sometimes it turns off or even I turn it on and the default device switches and telegram won't play sounds anymore.

**Comment by mrazavi64** [comment] 2017-01-29 06:34
I have the same issue with the latest version on ubuntu 16.04.

**Comment by julianxhokaxhiu** [comment] 2017-01-29 11:08
@john-preston any plan on fixing this or shall I try patching it myself and going for a PR?

**Comment by mirh** [comment] 2017-01-29 12:28
It was fixed a couple of days ago in dev-branch.

**Comment by julianxhokaxhiu** [comment] 2017-01-29 12:37
Nice!

For everybody who jumps into this issue, these are the affected commits that ( hopefully ) will fix this.

- https://github.com/telegramdesktop/tdesktop/commit/6ae68b337db256b0fbdd18896da451f445f137e0
- https://github.com/telegramdesktop/tdesktop/commit/4964b8b4880b08e861e8647345cfa0c5e3eba0ec
- https://github.com/telegramdesktop/tdesktop/commit/697fdd42944e95af99c9d594f26d8a2bb1aac6d7

Let's all wait for 1.0.3 and test it there. If fixed, I purpose to close this.

**Comment by john-preston** [comment] 2017-01-29 12:37
@julianxhokaxhiu Please try the latest alpha version from the bottom of https://desktop.telegram.org/changelog#alpha-version page. I did what I can regarding the sound devices there.

**Comment by julianxhokaxhiu** [comment] 2017-01-29 12:41
I can confirm that on Windows 10 it works fine! ( Alpha channel )

I played an audio, then I switched the output device during the playback and the audio switched correctly! Well done :)

**Comment by mrazavi64** [comment] 2017-02-01 05:44
And I can confirm the problem is solved on ubuntu 16.04. (After update to version 1.0.5)
Although there is a small glitch. Changing the output device will not affect the current playing audio in Telegram. But stopping the player and playing it again will use the new selected output device.
Anyway, I can live with that.
Good job. Cheers!

**Closed** 2017-02-01 08:22 UTC
Labels: enhancement

**Comment by john-preston** [comment] 2017-02-01 08:34
@mrazavi64 If someone can point out for API in pulseaudio (and / or ALSA) that will allow instantly understand that the default device was changed in the system, I'll switch to it without starting / stopping of audio by user. But currently I don't know that API :(

**Comment by julianxhokaxhiu** [comment] 2017-02-02 12:37
What about event subscriptions? https://freedesktop.org/software/pulseaudio/doxygen/subscribe.html

I guess `PA_SUBSCRIPTION_EVENT_SOURCE` and `PA_SUBSCRIPTION_EVENT_SOURCE_OUTPUT` are probably the most interesting events for you, but feel free to take a look at the list located here: https://freedesktop.org/software/pulseaudio/doxygen/def_8h.html#a6bedfa147a9565383f1f44642cfef6a3

**Comment by paulsommer** [comment] 2017-05-10 10:14
I would like to try the alpha (on Linux). Will the alpha still update automatically when new (regular) versions are available?

**Comment by terion-name** [comment] 2018-01-21 08:57
This is still an issue on mac with external usb sound

**Comment by black-wolfie** [comment] 2018-09-22 04:50
Had the same issue on my Windows 10. Even if I use my earbuds, after the call is connected, the sounds somehow start to come from the speakers.

**Comment by sl5net** [comment] 2018-10-31 09:58
Problem is **not** solved. Only telegram does not use the default settings.
Restarting telegram has helped.
I need to unplug the USB speaker.
Then the headset will be used automatically [what i want].

Normally I use the headset only on calls.
If a call comes in, I will adjust the default settings to the headset.
Telegram is the only application that ignores this default settings.

Windows 10.

please reopen it.

**Comment by hoover67** [comment] 2019-02-08 17:16
Problem still exists on my system (Mint 19.1, TG 1.5.11, XFCE desktop).

Switching sound output devices works nicely for all other apps, only telegram stubbornly outputs sound to the speakers.

**Comment by gun1x** [comment] 2019-04-19 21:07
I can't even force it to go to another sound device in pavucontrol. How did you manage to do this?
This bug is fascinating.

**Comment by ShrewdSpirit** [comment] 2019-05-14 06:00
it used to work in previous versions but got messed up again. I've been having this issue for months now.
All applications use the default input device I set in pavucontrol but telegram doesn't and won't even let me change the device

**Comment by mirh** [comment] 2019-05-14 11:43
https://github.com/telegramdesktop/tdesktop/issues/3459#issuecomment-397711149

**Comment by edi** [comment] 2020-06-03 13:52
It's 2020 and the issue's been created 5 years ago :) Telegram Desktop (on windows) still does not change audio output device (to default). I don't even want it to change on the fly ... having headphones plugged in, sound goes out through monitor's speakers.

But at least ... when a call starts, it should simply output to the default device (set at that time).

**Comment by aviallon** [comment] 2020-09-25 20:53
The problem happens on Android too when a wired headset is used. If a video call is started, it switches automatically to phone speaker, and there is no way to change it.

**Comment by mirh** [comment] 2020-09-26 08:48
This bug tracker has nothing to do with android, and the issue is/was somewhat specific to KDE.

**Comment by aviallon** [comment] 2020-09-26 12:21
@mirh Ooops, you're right... Should've opened another issue :sweat_smile:

_Sent from my MI 5S Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by tonyrulez** [comment] 2020-12-11 14:52
Looks like this issue hasn't got fixed in 6 years? Today I had to switch output device to an other headset. Chose the headset as default in Windows settings. All sound cam out of it, even the Telegram ringing sound, however the voice of whom I called **did not**. What sorcery is this?

**Comment by supersnager** [comment] 2020-12-14 08:43
Same problem on Linux Mint :(

**Comment by tonyrulez** [comment] 2020-12-14 08:53
Since voice chat got so much traction in Telegram (voice chat, video chat, and now group voice chat), there is ought to be proper audio settings in the app. Being able to set the input and output device, hell, even the mic volume or sensitivity, is necessary. Right now you can't set anything sounds related, even thoug you have the above-mentioned voice services.

**Comment by ilya-fedin** [comment] 2020-12-15 12:15
This is not a bug, Windows allows has separate default device for communtication streams and probably you're not aware of that.

**Comment by widdakay** [comment] 2021-02-25 01:54
This still is an issue on MacOS in 2021 and has been for as long as I have used telegram (since about the start of this thread), and I would be very happy to have it fixed. Eg. I am listening to stuff on my laptop speakers and turn up the volume. Later (sometimes hours later) I plug in headphones and someone sends me a message and the new message sound comes out of the laptop speakers at the old volume and can be quite loud.

**Comment by ilya-fedin** [comment] 2021-02-25 01:58
@widdakay this issue is closed a long time ago, commenting here won't change anything...

**Comment by FeanorsCurse** [comment] 2021-03-27 12:06
So what are we to do about it? Create a new issue?

**Comment by widdakay** [comment] 2021-05-03 01:23
@ilya-fedin This bug messed up a recording I was making again because Telegram did not switch to headphone output automatically when the system default did, and I really don't know where else to voice my concerns. Do you know where I should? Issue #179 is locked so I can't add anything there and #3459 is a different issue so not relevant. I don't want to open up a duplicate of this issue which I run into approximately every day, but it just caused loss of work again despite my best efforts today.

**Comment by ilya-fedin** [comment] 2021-05-03 05:10
Are you sure you have this bug and not #9814?

**Comment by widdakay** [comment] 2021-05-03 05:19
That actually does seem to be the same behavior, however I am seeing this occur on MacOS. Is it possible this bug is on multiple platforms? Thanks for the help!

**Comment by ilya-fedin** [comment] 2021-05-03 05:22
> Is it possible this bug is on multiple platforms? Thanks for the help!

Not sure. Most likely if you have macOS it's a separate issue since only Windows needs manual implementation of device change.
