### ISSUE TITLE
Please respect freedesktop standards (XDG)!

### ISSUE THREAD

**Issue by SanKro** [telegramdesktop/tdesktop#624] opened 2015-04-01 23:57 UTC
Telegram on Linux has a really bad behavior. it just dumps the configs to /home/USER. thats bad.

the XDG freedesktop standards are that it should look for the env "$XDG_CONFIG_HOME". when it is set, use this path for configs "$XDG_CONFIG_HOME/TelegremDesktop",, when its empty, the Fallback is /home/$USER/.config/TelegramDesktop

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

it shouldnt sit on the ~/Download directory. for the download via homepage, you should create a little installer that moves everything to

$XDG_DATA_HOME or (if not set) /home/$USER/.local/share and create a *.desktop file to $XDG_DATA_HOME/applications (/home/$USER/.local/share/applications) to get a menu entry.

**Comment by jtojnar** [comment] 2015-04-17 19:40
Duplicate of #107

**Closed** 2015-08-14 23:11 UTC
