### ISSUE TITLE
The app on linux restarting after the first run

### ISSUE THREAD

**Issue by vincenzopalazzo** [telegramdesktop/tdesktop#7199] opened 2020-02-13 11:20 UTC
### Steps to reproduce
1. Restart OS and Open the telegram app
2. texting on some chat
3. App closing

### Expected behaviour
The app shouldn't restart

### Actual behaviour
When I open the app, it closing, and I should be restart it

### Configuration
**Operating system:** Linux Mint 19.3

**Version of Telegram Desktop:** 1.9.9

**Used theme**: Dark

How can I take the log file?
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment] 2020-02-13 13:48
without crash log or gdb, i vote its' duplicate of #7095 spellchecker crash.

**Closed by Aokromes** 2020-02-13 13:48 UTC

**Comment by vincenzopalazzo** [comment] 2020-02-13 14:16
Yes, thanks :smile: 

Thanks for this work
