### ISSUE TITLE
huge memory leak in work with cached images and medium leak with loading images

### ISSUE THREAD

**Issue by MBkkt** [telegramdesktop/tdesktop#7361] opened 2020-03-11 13:17 UTC
https://github.com/telegramdesktop/tdesktop/issues/1317
Why closed? 
I tried 1.9.19, if you watch the channel with pictures, the memory leaks in the same way. If you watch the channel only with gifs, there are no memory leaks. 
The fix referring to which you closed the bug only works for [history/view/media/history_view_gif.h](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/view/media/history_view_gif.h)

**Comment by john-preston** [comment] 2020-03-11 13:33
@MBkkt Can you please provide an example of a public channel with such problem and information about the memory consumption after you scroll through enough of images.

**Comment by lejabque** [comment] 2020-03-11 14:16
Well, I checked it in a channel https://t.me/lentachold and memory increased 10 times when i scrolled. Then I closed and left the channel but client still using 1.2gb.
Version 1.9.19.
![1](https://user-images.githubusercontent.com/30625073/76426085-9f3f9580-63bb-11ea-96c8-5ee1820e9330.png)
![2](https://user-images.githubusercontent.com/30625073/76426114-a797d080-63bb-11ea-8da1-cfadede6d4e3.png)

**Comment by lejabque** [comment] 2020-03-11 14:23
Also I notice that there is no such problem in channel only with GIFs https://t.me/cgifs.

**Comment by john-preston** [comment] 2020-03-12 07:01
@lejabque I'm not sure this is the case described in the original issue, between posts that you show there are more than 15'000 messages. Currently Telegram Desktop stores all messages in memory (while caching the images and animations on HDD), so it does take a lot of memory in this case -- but I'm sure if you scroll some channel with 15'000 GIF animations it won't be much better. Or it could be much worse.

**Comment by lejabque** [comment] 2020-03-12 07:15
@john-preston but there is no problem while I'm scrolling channel with gifs, e.g. t.me/cgifs 

Also is it ok that ram not freed a few hours after scrolling?

**Comment by john-preston** [comment] 2020-03-12 07:49
@lejabque Do the GIFs autoplay?

**Comment by john-preston** [comment] 2020-03-12 07:51
@lejabque Messages (text and media metadata) are not freed unless messages are deleted. But they should not take lots of memory.

Also, /cgifs has 3'000 messages, so even if you scroll up till the very beginning of that channel, it will be less than 20% of messages that you've loaded in /lentachold - about additional 200 MB compared to additional 1 GB in /lentachold, for example.

**Comment by john-preston** [comment] 2020-03-12 08:11
Tried to memory-profile a long-lentachold-scroll :/ I'll try some other time.

![image](https://user-images.githubusercontent.com/17900494/76500788-9eaa0c00-645a-11ea-88d6-1394436c358e.png)

**Comment by ab123321** [comment] 2020-03-12 19:31
> between posts that you show there are more than 15'000 messages. Currently Telegram Desktop stores all messages in memory (while caching the images and animations on HDD), so it does take a lot of memory in this case -- but I'm sure if you scroll some channel with 15'000 GIF animations it won't be much better. Or it could be much worse.
@john-preston This way or another, it's not a rare occasion that tgdesktop takes more than 1 GB after several days of uptime (laptops are affected harder due to small capacity of RAM). If you have a lot of chats and groups, even light usage of client would cause abovementioned problem, without having to reproduce it on purpose.
With no doubt memory usage after December patch became much better, but large amount of RAM still being wasted even when you have client window closed does not sound like a proper or expected behaviour.

**Comment by Hezkore** [comment] 2020-03-14 15:11
I'm not sure this is relevant to what's going on here.
But I've noticed that Telegram uses a whole lot more memory these days.
It used to stay just below Steam at around 130 MB, but I now typically see it around 300 MB.
Well above Steam, and even Discord.

**Comment by Khomyak-sibiryak** [comment] 2020-03-15 01:05
https://github.com/telegramdesktop/tdesktop/issues/7280 I have a similar problem with RAM consumption. How to tell the client that after leaving the chat, channel, player, he must free up RAM?

**Comment by MBkkt** [comment] 2020-03-15 14:08
@Khomyak-sibiryak 
This cannot be done:( 
I believe if the application can consume an unlimited amount of memory, this is a leak. 
@john-preston apparently doesn’t think so, and people who have a lot of chats should suffer and restart telegram manually once a day.

**Comment by jeffythedragonslayer** [comment] 2020-03-16 22:19
@lejabque
Can you output of running it under valgrind?

**Comment by john-preston** [comment] 2020-03-18 08:15
@MBkkt It should work differently, I hope to fix that some day. But it is a huge amount of work, it's not just "find a bug that leaks memory and fix it", because it is working mostly as intended.

I was hoping that apart from working as intended (and holding all the messages you saw in memory) it also has some bug that leaks much more memory than the messages texts and media metadata. But for now I didn't find one.

**Comment by Ezri** [comment] 2020-03-25 13:40
> @Khomyak-sibiryak
> This cannot be done:(
> I think if the application can consume an unlimited amount of memory, this is a leak.
> @john-preston doesn't seem to think so, and therefore people who have a lot of chats have to suffer and restart telegram manually at least once a day.

Simple workaround would be add a reload button, similar to the one when you need to run an update. Would not solve the underlying problem, but makes it easier to handle.

**Comment by jeffythedragonslayer** [comment] 2020-03-25 16:57
I do not see how a reload button would make sense.  If memory is leaking then the application is either letting pointers go out of scope without free()ing or deleting them, or is holding on to lots of old pointers and then also not free()ing or deleting them.  By the time someone figures out which is happening it should be pretty straightforward to insert the missing calls to free() or delete into the source.

**Comment by Ezri** [comment] 2020-03-25 17:08
> I do not see how a reload button would make sense. If memory is leaking then the application is either letting pointers go out of scope without free()ing or deleting them, or is holding on to lots of old pointers and then also not free()ing or deleting them. By the time someone figures out which is happening it should be pretty straightforward to insert the missing calls to free() or delete into the source.

The visible problem I am associating with this issue is that image previews of new images stop loading. They are forever in the blurry "in the process of downloading" state. Only a shutdown and restart of telegram solves the problem. Then the button would help. If the issues are unrelated then it won't fix everybodies problem

**Comment by jeffythedragonslayer** [comment] 2020-03-26 00:57
For someone to code the button's onclick event to get it to free the memory, we need to know what the leaking buffer's memory address is and how big it is.  And at that point we might as well just free it when someone closes the channel and not have a separate button at all.  What you're describing almost sounds like manual garbage collection to me though.

**Comment by gaplo917** [comment] 2020-04-08 11:44
As I remember my telegram desktop did close about 1 week. The memory can unexpectedly go high to 9.8 GB!!
![Screenshot 2020-04-08 at 19 01 30](https://user-images.githubusercontent.com/5468398/78780142-b7adca80-79d0-11ea-9c64-6d39fe16d191.png)

**Comment by as3ii** [comment] 2020-04-28 19:35
I've noticed a memory leak (I don't know if it is related with cached images or something else). I'm using telegram 2.1.0 on arch linux. I don't know if it will be helpful, but I've used telegram-desktop for a couple of hours logging memory leaks with
`valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt telegram-desktop`
Here the resulting log file: [valgrind-out.txt](https://github.com/telegramdesktop/tdesktop/files/4548075/valgrind-out.txt)

**Comment by EndrII** [comment] 2020-05-09 09:10
![image](https://user-images.githubusercontent.com/12465465/81469516-e5637a80-91ed-11ea-97e8-d0f83ad33629.png)
![image](https://user-images.githubusercontent.com/12465465/81469535-12179200-91ee-11ea-9868-2f34c021c14b.png)

**Comment by oshanz** [comment] 2020-05-19 04:31
I thought electron apps are worst.
my slack app always under 400MB whatever I do around channels.
but telegram app seems never releasing memory. I have to reopen couple of times per day.

**Comment by olegon-ru** [comment] 2020-06-09 18:50
Source : telegram-desktop-2.1.7-1.fc32.src.rpm
From repo : rpmfusion-free-updates
5.6.14-300.fc32.x86_64, Fedora 32 Gnome, all updates included
The same trouble... I have to `killall telegram-desktop` every evening to prevent unstoppable memory leakage and can use it only in restricted mode on notebook with 4Gb memory.

**Comment by Germano0** [comment] 2020-10-03 10:26
Telegram 2.4.2 made my system (Fedora 32) with 16 GB RAM and 32 GB SSD swap, run out of memory.
No time to get any useful debuginfo since everytime I experience this problem I have to kill the process from TTY

**Comment by jeffythedragonslayer** [comment] 2020-10-03 15:49
Is the Fedora OOM killer enabled?

**Comment by soredake** [comment] 2020-12-01 11:41
Same happens when scrolling channel with large videos (2.3gb after five minutes)
![изображение](https://user-images.githubusercontent.com/5204968/100736101-f1599880-33da-11eb-925b-fbabe063e164.png)

**Comment by oshanz** [comment] 2020-12-06 07:11
1.6gb for a day, Fedora 33 
![image](https://user-images.githubusercontent.com/5364479/101273968-404f5700-3768-11eb-827c-054068887ce1.png)

**Comment by bzeller** [comment] 2021-01-15 08:09
This morning i had to kill a Telegram client using over 20Gigs of memory forcing my machine to swap heavily. Right after restart memory is already over 3Gigs as reported by pmap ....

**Comment by ilya-fedin** [comment] 2021-03-11 13:35
> Here the resulting log file: [valgrind-out.txt](https://github.com/telegramdesktop/tdesktop/files/4548075/valgrind-out.txt)

valgrind reports are useless with tdesktop since smart pointers are used. If one really want to debug this, [heaptrack](https://github.com/KDE/heaptrack) should be used (preferably on a binary with debug symbols).

**Closed** 2021-03-12 12:11 UTC
Labels: bug
