### ISSUE TITLE
Падает при запуске

### ISSUE THREAD

**Issue by martrix78** [telegramdesktop/tdesktop#2427] opened 2016-09-14 10:25 UTC
Падает при запуске
### Configuration
**Operating system:**
Linux Mint 17.2 Rafaela
**Version of Telegram Desktop:**
 0.10.6
### Logs
Insert logs here (if necessary)
./Telegram
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Auto configuration failed
140147970737920:error:26078067:engine routines:ENGINE_LIST_ADD:conflicting engine id:eng_list.c:116:
140147970737920:error:2606906E:engine routines:ENGINE_add:internal list error:eng_list.c:288:
140147970737920:error:260B6067:engine routines:DYNAMIC_LOAD:conflicting engine id:eng_dyn.c:540:
140147970737920:error:260BC066:engine routines:INT_ENGINE_CONFIGURE:engine configuration error:eng_cnf.c:204:section=gost_section, name=dynamic_path, value=/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libgost.so
140147970737920:error:0E07606D:configuration file routines:MODULE_RUN:module initialization error:conf_mod.c:235:module=engines, value=engine_section, retcode=-1      
QMutex: destroying locked mutex
QObject::~QObject: Timers cannot be stopped from another thread
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by john-preston** [comment] 2016-09-14 10:45
@martrix78 What about 0.10.4 alpha version? You can try it from the bottom of https://desktop.telegram.org page

**Comment by martrix78** [comment] 2016-09-14 10:47
its work!
thx :)

**Comment by john-preston** [comment] 2016-09-14 10:49
@martrix78 Well, it won't help, because it will auto update to 0.10.6 and fail again.

**Comment by martrix78** [comment] 2016-09-14 11:07
already wants to be updated :)

**Comment by john-preston** [comment] 2016-09-14 11:57
@martrix78 What DE do you use? https://www.linuxmint.com/release.php?id=25

**Comment by martrix78** [comment] 2016-09-14 11:57
LXDE

**Comment by john-preston** [comment] 2016-09-14 12:02
@martrix78 No such one on the Linux Mint website =( I've tested in Linux Mint 17.1 KDE and it works fine.

**Comment by martrix78** [comment] 2016-09-14 12:07
on repository :)
LXDE 17.2

**Comment by john-preston** [comment] 2016-09-14 12:46
@martrix78 And it does work in Linux Mint 17.3 LXDE, so I'm afraid I won't help you with that :(

**Comment by nshopik** [comment] 2016-09-19 10:30
@john-preston Same problem here with XFCE on xbuntu 16.04

**Comment by martrix78** [comment] 2016-09-19 11:21
It does not depend on DE

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Auto configuration failed
**139697793971968:error:26078067:engine routines:ENGINE_LIST_ADD:conflicting engine id:eng_list.c:116:
139697793971968:error:2606906E:engine routines:ENGINE_add:internal list error:eng_list.c:288:
139697793971968:error:260B6067:engine routines:DYNAMIC_LOAD:conflicting engine id:eng_dyn.c:540:
139697793971968:error:260BC066:engine routines:INT_ENGINE_CONFIGURE:engine configuration error:eng_cnf.c:204:section=gost_section, name=dynamic_path, value=/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libgost.so
139697793971968:error:0E07606D:configuration file routines:MODULE_RUN:module initialization error:conf_mod.c:235:module=engines, value=engine_section, retcode=-1**      
QMutex: destroying locked mutex
QObject::~QObject: Timers cannot be stopped from another thread
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by john-preston** [comment] 2016-09-20 07:02
Can anyone with this problem contact me at https://telegram.me/preston so I could build some test versions and ask to run them? I can't reproduce that problem myself.

**Comment by john-preston** [comment] 2016-09-20 18:27
This one should be fixed in 0.10.7 stable, available from https://desktop.telegram.org

**Closed by john-preston** 2016-09-20 18:27 UTC
