### ISSUE TITLE
Ctrl+C Ctrl+V not working on Ubuntu 

### ISSUE THREAD

**Issue by Hisfantor** [telegramdesktop/tdesktop#10060] opened 2021-01-03 11:13 UTC
### Steps to reproduce
1. Ubuntu 20.4 i3wm
2. I tested snap, apt and the download from https://desktop.telegram.org/
3. Ctrl+C and Ctrl+V in chat

### Expected behaviour
copy paste via shortcuts in input field
### Actual behaviour
nothing at all
### Configuration
now on tsetup.2.5.1.tar.xz

**Comment by ilya-fedin** [comment] 2021-01-03 11:21
Can't reproduce, copies and pastes just fine.

**Comment by ilya-fedin** [comment] 2021-01-04 15:15
@Hisfantor

**Comment by Hisfantor** [comment] 2021-01-06 22:24
> Can't reproduce, copies and pastes just fine.

seems to be a problem with my windowmanager i3

**Comment by ilya-fedin** [comment] 2021-01-06 22:28
If this is an i3's issue, you can close the issue

**Closed** 2021-01-06 22:35 UTC
