### ISSUE TITLE
Option to ignore 'Contact joined Telegram' notification

### ISSUE THREAD

**Issue by blacklat** [telegramdesktop/tdesktop#10470] opened 2021-03-05 02:59 UTC
Six years later the bug still exists, FUCK THAT SHIT!

**Comment by Ryder17z** [comment] 2021-03-05 06:12
have you double-checked that the notification is turned off?

**Comment by RememberTheAir** [comment] 2021-03-05 08:18
Telegram Desktop's behavior is consistent with the other official Telegram apps. Please upvote the general suggestion on Telegram's suggestions & bugs tracker: https://bugs.telegram.org/c/65 (this issue is a duplicate of #964)

@Ryder17z that option disable the notification, yes, but the chat will always be created. I think that's what people complain about

**Comment by blacklat** [comment] 2021-03-28 04:00
> have you double-checked that the notification is turned off?

Obviously, notifications are disabled in all my instances of the telegram, I'm not an idiot, if they weren't disabled I wouldn't be complaining. But it is useless to disable it, the IRRITANT messages from new contacts who joined the telegram always appear, the option just does not work

**Comment by RememberTheAir** [comment] 2021-03-28 19:34
> the option just does not work

The option is supposed to just disable the sound

**Closed** 2021-03-28 19:40 UTC

**Comment by blacklat** [comment] 2021-03-28 21:52
of course not, the option 'disable' means disable, understand? nobody wants to know if someone joined the telegram or not, for real daily telegram users this is extremely irritating, it can be cool for those who like to people that install it once in a while and then uninstall it, but for me it is not, I I use the telegram to work and that makes me ANGRY and ANGRY to everyone who works with me and everyone I know.

**Comment by Aokromes** [comment] 2021-03-28 21:57
> of course not, the option 'disable' means disable, understand? nobody wants to know if someone joined the telegram or not, for real daily telegram users this is extremely irritating, it can be cool for those who like to people that install it once in a while and then uninstall it, but for me it is not, I I use the telegram to work and that makes me ANGRY and ANGRY to everyone who works with me and everyone I know.

i want, but like RememberTheAir ointed you, the way to go on this issue is https://bugs.telegram.org/c/65

**Comment by Ryder17z** [comment] 2021-03-28 22:04
Actually, some people do like to know when a contact joins telegram. (not
many, but a few people I know do)

**Comment by RememberTheAir** [comment] 2021-03-29 07:11
> of course not, the option 'disable' means disable, understand?

The option should be worded differently, because it's meant to simply disable the notification sound. It's supposed to work like it works now

**Comment by john-preston** [comment] 2021-09-23 13:41
The toasts should not appear starting with the next version.
