### ISSUE TITLE
app crash on minimizing videos

### ISSUE THREAD

**Issue by chalist** [telegramdesktop/tdesktop#27608] opened 2024-03-17 08:05 UTC
### Steps to reproduce

1. play a video
2. exit from full screen to float window mode

### Expected behaviour

playing video in float window mode

### Actual behaviour

Crash telegram and force close

### Operating system

Manjaro Linux 23.1.3

### Version of Telegram Desktop

4.15.5 beta

### Installation source

Static binary from official website

### Crash ID

a90eb697-ca2d-4122-3fcddab4-433e1fad

**Comment by shwade** [comment] 2024-03-22 12:23
Probably the same issue as #https://github.com/telegramdesktop/tdesktop/issues/27177 . 

Crashes on minimizing videos as well, with `Scudo ERROR: CHECK failed @ /usr/src/tdesktop/Telegram/ThirdParty/scudo/list.h`

**Comment by VladimirMrzv** [comment] 2024-03-26 15:46
same problem
and also when got incoming video call
Crash ID: f7b22af1-8632-4f6e-a46d37b3-2cd40045

**Comment by CoSoCo** [comment] 2024-03-30 13:17
Same problem here on Ubuntu-Unity 22.04 with App installed from [PPA](https://launchpad.net/~atareao/+archive/ubuntu/telegram?field.series_filter=jammy) (which basicly is a copy of the original binaries) since Version 4.15.1

Mostly the minimized video runs fine, but after closing it, in 80 % the app crashes small time after.

Some months ago the same problem – even without minimized video – happened regularly with 4.8.2, but it was gone with later versions.

**Comment by VladimirMrzv** [comment] 2024-04-02 06:01
update to 4.16, crash not fixed. 
New id
6e347454-a807-40f5-334a8985-bb5dd19b

**Comment by VladimirMrzv** [comment] 2024-04-05 06:16
Crash ID: b8f971e3-b6aa-40d7-6e22b2b1-d671cb4f
from latest updated version

**Comment by ilya-fedin** [comment] 2024-04-05 21:05
Looks like Qt update has broke OpenGL again...

**Comment by VladimirMrzv** [comment] 2024-04-06 05:53
@ilya-fedin what version of QT works fine?
what libs are you use?
Tested KDE Plasma 6.0.3 and Telegram crash too.

same problem
https://github.com/telegramdesktop/tdesktop/issues/27710

**Comment by Uncomfy** [comment] 2024-04-06 13:38
Kubuntu 22.04
Instead of creating a floating window it creates a floating triangle and when you try to point at it with mouse - it crashes

https://github.com/telegramdesktop/tdesktop/assets/43932319/9b06d455-afdf-4bba-ba92-5107989d9b41

**Comment by ilya-fedin** [comment] 2024-04-06 16:55
> what version of QT works fine?
> what libs are you use?
> Tested KDE Plasma 6.0.3 and Telegram crash too.

Last Qt version working fine was 6.6.2... Not sure about 6.6.3, it was skipped but is likely to be fine.

**Comment by AVAtarMod** [comment] 2024-04-07 08:32
Update to to 4.16.4 fixes this issue on Gnome 45 (Wayland session, installation source: static binary from official website).

**Closed** 2024-04-07 08:35 UTC
Labels: bug

**Comment by VladimirMrzv** [comment] 2024-04-07 08:38
Ubuntu Unity 22.04 fixed too, no more crash. (X11 session)

**Comment by justOtto** [comment] 2024-04-22 01:14
This is still happening on my computer. Arch, Gnome 46, Xorg, Telegram 4.16.8.

**Comment by justOtto** [comment] 2024-04-28 01:08
Am i the only one still having this problem?

**Comment by ilya-fedin** [comment] 2024-04-28 06:35
@justOtto you may have this problem if you don't use official binaries, it was fixed by rolling back some Qt changes

**Comment by chalist** [comment] 2024-04-28 10:13
> This is still happening on my computer. Arch, Gnome 46, Xorg, Telegram 4.16.8.

I unchecked beta version installation and this problem was fixed for me.

**Comment by justOtto** [comment] 2024-04-28 15:36
@ilya-fedin @chalist Thanks so far.
I don't use any beta versions and everything is from the official repos so i'm not aware of any unofficial binaries. I'll try the Qt update to 6.7
Figured out now that the crashes only happen with X11, no problem using wayland.

**Comment by ilya-fedin** [comment] 2024-04-28 16:04
> I'll try the Qt update to 6.7

Qt 6.7 is the thing containing the bug. Qt should be lesser than 6.7 for that bug to not to happen.

**Comment by ilya-fedin** [comment] 2024-04-28 16:06
> Figured out now that the crashes only happen with X11, no problem using wayland.

This sounds like you have an unrelated issue as it was happening on Wayland

**Comment by justOtto** [comment] 2024-04-28 23:48
It crashes also with Qt 6.6.2, but yes it's from the arch repos, i just trust them and it's also not wayland, so thanks for your time.

**Comment by ilya-fedin** [comment] 2024-05-21 23:04
@anarsoul not sure what you mean, there's already a build on flathub. It's not the same as static binary though as part of the dependencies is controlled by the freedesktop runtime.

**Comment by anarsoul** [comment] 2024-05-21 23:17
> not the same as static binary though

That is exactly what I mean. Nothing prevents you from packaging a static binary in flatpak

**Comment by ilya-fedin** [comment] 2024-05-21 23:25
> Nothing prevents you from packaging a static binary in flatpak

@john-preston  prevents me. He has a strong no on deprecating systems and providing static binary would mean deprecating aarch64 systems in flathub builds.

I also don't see what would that give.

**Comment by anarsoul** [comment] 2024-05-21 23:46
> I also don't see what would that give.

That would allow users to install official build of tdesktop via GUI in a single click (Gnome Software on Gnome, Discover on KDE Plasma).

Moreover you could replicate your steps for building static binary in flatpak manifest to build static binary for aarch64 as well.

flatpak gives software developers a stable and predictable platform to run their software on regardless of what underlying distribution is used. It is a convenient way to distribute your software for Linux. You are providing official builds for Android in Google Play Store and for Apple in Apple App Store after all, why not to do the same for Linux where flathub is a de-facto official app store for multiple Linux distros.

**Comment by ilya-fedin** [comment] 2024-05-21 23:55
> Moreover you could replicate your steps for building static binary in flatpak manifest to build static binary for aarch64 as well.

No, I don't see how that would work.
1. Static binary build doesn't work on aarch64 according to reports on github, I don't have arm hardware to debug it and not I nor preston have interest in that in general. The community seem to also unwiling to help with getting ARM builds, I say that we need help in every issue about ARM support yet people just ignore these words.
2. It uses docker which couldn't run via flatpak-builder

> That would allow users to install official build of tdesktop via GUI in a single click (Gnome Software on Gnome, Discover on KDE Plasma).

Getting the binary from official website is not any harder. Download, unpack (with a simple drag'n'drop!), use.

> why not to do the same for Linux where flathub is a de-facto official app store for multiple Linux distros.

Well, it's already done. Please don't gaslight just because you don't like it differs. :)

**Comment by anarsoul** [comment] 2024-05-22 00:08
> because you don't like it differs. :)

The issue is not that it differs, the issue is that whenever someone hits a bug you ask them to try static binary from a tarball. In other words, flatpak build it not treated as a first-class citizen (try to make a video call on flatpak build)

> Please don't gaslight

I'm not gaslighting you unless you started to question your understanding of reality :) However it doesn't look like this discussion is very constructive, so I'll wrap it up from my side. Feel free to reach out to me (my nickname at gmail) if you want to discuss it further.

**Comment by CoSoCo** [comment] 2024-05-22 00:11
Am 22.05.24 um 01:46 schrieb Vasily Khoruzhick:
>
> flatpak gives software developers a stable and predictable platform to run their software on regardless of what underlying distribution is used. It is a convenient way to distribute your software for Linux. You are providing official builds for Android in Google Play Store and for Apple in Apple App Store after all, why not to do the same for Linux where flathub is a de-facto official app store for multiple Linux distros.
>
And it consumes > 2 GB of ballast / space for nothing. For that reason I prefer the builds from https://launchpad.net/~atareao/+archive/ubuntu/telegram or https://telegram.org/dl/desktop/linux

**Comment by ilya-fedin** [comment] 2024-05-22 00:17
> The issue is not that it differs, the issue is that whenever someone hits a bug you ask them to try static binary from a tarball.

Identifying whether the issue is specific to a build is important for triaging. Static binary is indeed the first option but in very weird scenarios it happens that it's requested to try all three (static binary, flatpak, snap).

> flatpak build it not treated as a first-class citizen

The main blocker for the flatpak build to become a first class citizen is the lack of secrets functionality to provide builds with official API keys without revealing them to the world.

> try to make a video call on flatpak build

Works just fine

**Comment by anarsoul** [comment] 2024-05-22 00:31
> Works just fine

Crashes for me with a backtrace very similar similar to one in #25706, the only difference is libgallium_dri.so instead of iris_dri.so due to using mega-driver for mesa in flatpak

**Comment by ilya-fedin** [comment] 2024-05-22 00:34
Well, if you have problems with OpenGL, just disable it in settings
