### ISSUE TITLE
[Feature Request] Screen Capture

### ISSUE THREAD

**Issue by angusyeung** [telegramdesktop/tdesktop#4080] opened 2017-11-21 03:24 UTC
It would be nice if it is able to capture specific area of my screen.

**Comment by MasterGroosha** [comment] 2017-11-21 07:29
Aren't [Fraps](http://www.fraps.com/)/[Bandicam](https://www.bandicam.com/)/[CamStudio](https://portableapps.com/news/2013-10-26--camstudio-portable-2.7.2-released)/etc enough for you?

**Comment by angusyeung** [comment] 2017-11-21 08:47
Is it possible to be a build-in feature? for peoples who always share images in a group, they have to jump across difference application all the time, it would be nice if they can capture and share images in the chat dialog, just like "LINE" desktop version.

**Comment by MasterGroosha** [comment] 2017-11-21 08:54
_Disclaimer: I am not a member of Telegram team and everything below are just my own thoughts_

@angusyeung This is possible (in theory), but the problem is that Telegram is cross-platform messenger with main apps built for Android and iOS. (@john-preston [said it himself](https://github.com/telegramdesktop/tdesktop/issues/3148#issuecomment-289285463), though in another context). List of apps' features should be the same as much as possible and implementing a "local" feature might be frustrating for other people who use Telegram on smartphones.

**Comment by stek29** [comment] 2017-11-21 09:17
@MasterGroosha but Desktop app is different from mobile apps. See #3154.

This issue is a duplicate of #1351.

**Closed by stek29** 2017-11-21 09:17 UTC

**Comment by trollcop** [comment] 2017-11-30 14:53
Bah. The dupes are talking about a feature request from 2015. It's gonna be 2018 soon. It's extremely inconvenient to have to alt-tab between different apps like snip etc on windows just to grab a portion of the screen. LINE did it right - select a region and send. It even works in their web app in google store. So I doubt that this is something "impossible" to implement cross-platform way.

I use telegram a lot for work, and most use cases involving sending screenshot only need a small portion of a larger full-screened app (schematics/PCB layout, if that makes any difference). Alt-printscreen would be useless as that would still be sending my entire 4K desktop, and the area of interest is usually very small. Now I have to press win, type snip, enter, click new button, select an area, and ctrl+v into telegram....

**Comment by trollcop** [comment] 2017-11-30 15:11
@MasterGroosha i thought i was pretty clear in my post specifically talking about "third party apps" being a nuisance just to take a screenshot for sharing.

Yes, I'm aware of alt-print screen. My software is full-screen and generally only needs a small Region of Interest.
Yes, I'm aware of Windows Snipping Tool and MacOS key combo.

I'm also aware that both of those things break the workflow from two apps (target app for region of interest, telegram) into three apps (target app, some screenshot app, telegram). Something that should take ~5 seconds now takes about 15-30, as snip needs to be launched, area selected, and pasted. All this while maintaining the target app focused/fullscreen/not obscured by e.g telegram client or other apps.
