### ISSUE TITLE
Media key support for music playback?

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#3960] opened 2017-10-05 13:20 UTC
Dear all, 

Just an idea:

What are your thoughts on adding media key support for Telegram Desktop for people to pause and resume audio file playback by pressing their media keys on their keyboard?

Tested it on Ubuntu 17.10 but it's not recognized.

![image](https://user-images.githubusercontent.com/170947/31229377-c441446a-a9e0-11e7-8771-3fb62956327e.png)

**Comment by stek29** [comment] 2017-10-06 07:23
They work on macOS and (iirc) on Windows, btw

**Comment by orschiro** [comment] 2017-10-06 07:31
Cool! So we (just) need to add Linux MPRIS support. Anyone an idea how to
proceed?

**Comment by saeidscorp** [comment] 2019-01-12 09:02
If I understand correctly, firstly there is a need for DBus support (as MPRIS works on top of DBus). Probably a compilation env var to add conditional support for DBus when compiling for Linux systems? Or it can have the support available on all platforms but decide to use MPRIS on runtime?

**Comment by seniorivn** [comment] 2019-06-28 16:43
@saeidscorp there is already a dbus support in qt and also it is used here https://github.com/telegramdesktop/tdesktop/blob/0868a9f7b9e94e419542cb0d4a5d023b2fc7cb1f/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L19

**Comment by smaznet** [comment] 2019-07-20 13:11
I also think [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) is very useful
to control music using media keys

please add this feature

**Comment by ilya-fedin** [comment] 2020-03-04 19:52
> I also think [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) is very useful
> to control music using media keys

As I can see, this specification is for controlling multimedia players for dbus
The only way to implement media keys watching - xorg api (or compositor api, on wayland)
https://gist.github.com/javiercantero/7753445

**Comment by AriaMoradi** [comment] 2020-04-25 08:42
any progress on this issue? 
I would like to help with it

**Comment by chekoopa** [comment] 2020-10-27 03:16
Still relevant on 2.4.4

**Comment by ilya-fedin** [comment] 2020-10-27 03:24
> any progress on this issue?

I made a try to add mpris support some time ago, but the specification requires a lot of properties, signals and methods to be implemented, not to say that specification requires emitting PropertiesChanged. Looking to the facts that tdesktop code is really hard to understand and that I'm not interested in this feature, I stopped the work. If anyone wants to continue, there are my commits: https://github.com/ilya-fedin/tdesktop/tree/mpris.

**Comment by ilya-fedin** [comment] 2020-10-28 05:37
> same bug?

No, I think this ticket could be renamed to "Add MPRIS support" to eliminate confusion

**Comment by JuniorJPDJ** [comment] 2020-12-20 11:34
I did similar issue: #9961 as I didn't found this one as it's called weird.

**Comment by JuniorJPDJ** [comment] 2020-12-20 12:10
Could someone please rename this issue?

**Comment by ilya-fedin** [comment] 2020-12-20 12:18
> as I didn't found this one

![image](https://user-images.githubusercontent.com/17829319/102713081-6d018380-42bd-11eb-8800-b1173328a999.png)

**Comment by ilya-fedin** [comment] 2020-12-27 11:46
I found a way to fix this without implementing this horrible MPRIS spec. People who want MPRIS should find another issue, probably, since this one will be closed as soon as the fix will land dev branch.

**Closed** 2020-12-28 13:00 UTC
Labels: enhancement, linux

**Comment by chekoopa** [comment] 2020-12-31 13:33
The problem is it would now probably conflict with MPRIS apps.

**Comment by JuniorJPDJ** [comment] 2020-12-31 14:01
@chekoopa probably if MPRIS support would arrive, this pull should be togglable
