### ISSUE TITLE
telegram-desktop 2.4.11: malloc: invalid size (unsorted) - upon audio call

### ISSUE THREAD

**Issue by sedimentation-fault** [telegramdesktop/tdesktop#9803] opened 2020-11-24 19:48 UTC
### Steps to reproduce
1. Start telegram-desktop on a Gentoo Linux X terminal by typing:

TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=FUCK_ME telegram-desktop

(you say: 

Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value

so I set TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY  to the value FUCK_ME).

2. Make an audio call to a contact.
3. telegram-desktop crashes with:

malloc(): invalid size (unsorted)
Aborted.

If I start it with

TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=no telegram-desktop &

(i.e. "no", instead of "FUCK_ME" value for TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY), it crashes when I try an outgoing audio call with:

telegram-desktop: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Aborted.

### Expected behaviour
It should not crash. It should make the call (isn't it obvious?).

### Actual behaviour
I start it with

TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=no telegram-desktop &

and see on the terminal:

Application was built without embedded fonts, this may lead to font issues.
AL lib: (EE) Error enumerating devices: Context did not connect (Connection terminated)
AL lib: (EE) Error enumerating devices: Context did not connect (Connection terminated)
error: : cannot open
error: : cannot open
error: : cannot open
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol

Notice that it *was* compiled with

        -DDESKTOP_APP_USE_PACKAGED=ON
        -DDESKTOP_APP_USE_PACKAGED_FONTS=ON

so the complain about the fonts does not make any sense to me. Anyway, the application window is there, so I try an outgoing audio call to some contact. At that point, I hear the ringing, maybe twice, then the whole app crashes and I see on the terminal:

D/tgvoip: === Updating voip config ===
D/tgvoip: {"enable_vp8_encoder":true,"enable_vp8_decoder":true,"enable_vp9_encoder":true,"enable_vp9_decoder":true,"enable_h265_encoder":true,"enable_h265_decoder":true,"enable_h264_encoder":true,"enable_h264_decoder":true,"audio_frame_size":60,"jitter_min_delay_60":2,"jitter_max_delay_60":10,"jitter_max_slots_60":20,"jitter_losses_to_reset":20,"jitter_resync_threshold":0.5,"audio_congestion_window":1024,"audio_max_bitrate":20000,"audio_max_bitrate_edge":16000,"audio_max_bitrate_gprs":8000,"audio_max_bitrate_saving":8000,"audio_init_bitrate":16000,"audio_init_bitrate_edge":8000,"audio_init_bitrate_gprs":8000,"audio_init_bitrate_saving":8000,"audio_bitrate_step_incr":1000,"audio_bitrate_step_decr":1000,"use_system_ns":true,"use_system_aec":true,"force_tcp":false,"jitter_initial_delay_60":2,"adsp_good_impls":"(Qualcomm Fluence)","bad_call_rating":true,"use_ios_vpio_agc":false,"use_tcp":false,"audio_medium_fec_bitrate":20000,"audio_medium_fec_multiplier":0.1,"audio_strong_fec_bitrate":7000}
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
telegram-desktop: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Aborted.

### Configuration
**Operating system:**
Gentoo Linux
Portage 2.3.99 (python 3.7.7-final-0, default/linux/amd64/17.0/hardened, gcc-9.3.0, glibc-2.30-r8, 4.19.81-gentoo x86_64)
=================================================================
System uname: Linux-4.19.81-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700HQ_CPU_@_2.60GHz-with-gentoo-2.6

sh bash 5.0_p17
ld GNU ld (Gentoo 2.33.1 p2) 2.33.1
app-shells/bash:          5.0_p17::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.1::gentoo
dev-lang/python:          2.7.18::gentoo, 3.6.10-r2::gentoo, 3.7.7-r2::gentoo, 3.8.2-r2::gentoo
dev-util/cmake:           3.16.5::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.11.6-r3::gentoo, 1.12.6::gentoo, 1.13.4-r2::gentoo, 1.14.1::gentoo, 1.15.1-r2::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.33.1-r1::gentoo
sys-devel/gcc:            7.3.0-r3::gentoo, 7.4.0-r2::gentoo, 7.5.0::gentoo, 8.3.0-r1::gentoo, 9.2.0-r2::gentoo, 9.3.0::gentoo
sys-devel/gcc-config:     2.2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.4::gentoo (virtual/os-headers)
sys-libs/glibc:           2.30-r8::gentoo

**Version of Telegram Desktop:**
2.4.11
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
net-im/telegram-desktop official Gentoo ebuild:

https://gitweb.gentoo.org/repo/gentoo.git/tree/net-im/telegram-desktop/telegram-desktop-2.4.11.ebuild
**Used theme**:
The "standard" one, whatever this is. Didn't change anything about it.
<details><summary><b>Logs</b>:</summary>
No log found...
</details>

**Comment by ilya-fedin** [comment] 2020-11-24 20:19
ALSA is not supported by webrtc, duplicate of #8472

**Closed** 2020-11-24 20:20 UTC

**Comment by ilya-fedin** [comment] 2020-11-24 20:23
> Notice that it _was_ compiled with

As far as I know, tg_owt package is broken in gentoo, I suggest to use official binary.

**Comment by sedimentation-fault** [comment] 2020-11-24 22:35
Quote: ALSA is not supported by webrtc, duplicate of #8472

Wait, I *do* have pulseaudio installed. Pulseaudio is configured as a "minimal unintrusive dumb pipe to ALSA", as described here: 

https://wiki.archlinux.org/index.php/PulseAudio/Examples#PulseAudio_as_a_minimal_unintrusive_dumb_pipe_to_ALSA

Therefore, applications that need it, will be able to use it (it will "autospawn") and it will exit after 20 seconds of inactivity. Maybe I have to start pulseaudio manually before I use telegram-desktop, because (for some reason) this "autospawn" mechanism does not work here?

**Comment by ilya-fedin** [comment] 2020-11-24 23:08
Read the second message

**Comment by sedimentation-fault** [comment] 2020-11-25 06:47
Well, this situation is unsatisfactory from a user perspective - but thanks anyway.
