### ISSUE TITLE
Press and hold on MacOS doesn't work

### ISSUE THREAD

**Issue by fourlastor** [telegramdesktop/tdesktop#2587] opened 2016-10-31 09:00 UTC
When you hold a letter pressed on MacOS you usually get a menu like this:

<img width="198" alt="screen shot 2016-10-31 at 09 51 55" src="https://cloud.githubusercontent.com/assets/1263058/19848735/bdf8a734-9f4f-11e6-99d3-29372f9cca7e.png">

### Steps to reproduce

1. Be sure you set `defaults write -g ApplePressAndHoldEnabled -bool true` if you changed it before (or just try to press and hold in Notes, for example).
2. Open a chat and focus the input text
3. Press and hold a vowel

### Expected behaviour
The previously shown menu should appear.

### Actual behaviour
The letter is repeated in the text input.

### Configuration
**Operating system: OSX El Capitan 10.11.6

**Version of Telegram Desktop: 0.10.19

### Notes

I believe this is QT's fault, probably to achieve having a shared widget for text input, so it might be useful to do a quick test app with a text input field and see if the behavior is incorrect.

**Comment by stek29** [comment] 2016-11-05 17:57
I never seen it working in any multiplatform app.

**Comment by fourlastor** [comment] 2016-11-06 10:18
On electronjs based apps this works actually, without any extra effort.

**Comment by stek29** [comment] 2017-02-11 11:16
@fourlastor I mean *multiplatform app*, not a browser with icon changed.
Btw, duplicate of #1939

**Closed** 2017-02-11 11:19 UTC
