### ISSUE TITLE
Ubuntu version crash on video call

### ISSUE THREAD

**Issue by RedCollarPanda** [telegramdesktop/tdesktop#27705] opened 2024-04-04 16:46 UTC
### Steps to reproduce

1. Call someone vith video
2. Seg fault

### Expected behaviour

The normal call

### Actual behaviour

ApiId: 2040
Binary: Telegram
Launched: 04.04.2024 19:57:53
OpenGL: Enabled
OpenGL Renderer: [not-initialized]
Platform: Linux
UserTag: 786e22d8a8d27bce
Username: Octos
Version: 4016001

Caught signal 11 (SIGSEGV) in thread 138536008835584
Google Breakpad caught a crash, minidump written in thread 138536008835584
Minidump: /home/name
[8a2c0800-b421-4bcd-32abacb2-5b3b2ad0.dmp](https://github.com/telegramdesktop/tdesktop/files/14874439/8a2c0800-b421-4bcd-32abacb2-5b3b2ad0.dmp)
/.local/share/TelegramDesktop/tdata/dumps/8a2c0800-b421-4bcd-32abacb2-5b3b2ad0.dmp

### Operating system

ubuntu 22.04

### Version of Telegram Desktop

 4016001

### Installation source

Static binary from official website

### Crash ID

04ecd2f3-2ee2-4c7d-99d070a5-8993b843

**Comment by Aokromes** [comment] 2024-04-04 17:15
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by RedCollarPanda** [comment] 2024-04-04 17:51
@Aokromes  good day!Updated issue with " Crash ID: 04ecd2f3-2ee2-4c7d-99d070a5-8993b843"

**Comment by zbkllz** [comment] 2024-04-04 23:44
I thought it was a problem with my settings, but the behavior only happens when I start a call. So annoying always needing to explain to non-Linux users why I shut them out.

**Comment by xxfogs** [comment] 2024-04-05 14:56
Same issue on my end

**Comment by Chudvan** [comment] 2024-04-06 15:28
The same error for me. The error occurs when the other participant turns on the camera, not me. When I turn on the camera, participant sees me, the sound also works. Both he and me can hear each other.
[log.txt](https://github.com/telegramdesktop/tdesktop/files/14893989/log.txt)
[log_.txt](https://github.com/telegramdesktop/tdesktop/files/14893990/log_.txt)

Logs with errors: // look at log.txt (log_.txt)

**Comment by Aokromes** [comment] 2024-04-06 16:57
https://github.com/telegramdesktop/tdesktop/issues/27608

**Comment by RedCollarPanda** [comment] 2024-04-07 11:35
It is not fixed in latest version, 4.16.4. what should i do?

**Comment by john-preston** [comment] 2024-04-07 11:51
@RedCollarPanda Most of the crashes related to OpenGL (at least with Picture-in-Picture video) were fixed by this update. So please reproduce in 4.16.4 and send one more crash report and post crash id here.

Although I have to say that currently TDesktop crashes on Linux a lot, and even with reports I have no ideas what to do with that, it happens somewhere inside the memory allocator checks, reporting basically that some memory was corrupted at some time in the past.

**Comment by Aokromes** [comment] 2024-04-07 11:59
tried with ubuntu 23.04 and from android mobile phone and it doesn't crashes for me. (intel gfx)

**Comment by ilya-fedin** [comment] 2024-04-07 12:04
yeah, I can't reproduce too anymore

**Comment by Chudvan** [comment] 2024-04-08 19:13
4.16.4 - videocall now works for me! Thanks)

**Comment by YevhenKholevchuk** [comment] 2024-04-16 09:55
Ubuntu 20.04, Telegram Desktop 4.16.7 - breaks when opening any personal message

**Comment by Aokromes** [comment] 2024-04-16 09:59
> Ubuntu 20.04, Telegram Desktop 4.16.7 - breaks when opening any personal message

i don't think your is video call crash no?

**Comment by YevhenKholevchuk** [comment] 2024-04-16 10:01
> > Ubuntu 20.04, Telegram Desktop 4.16.7 - breaks when opening any personal message
> 
> i don't think your is video call crash no?

Do you mean that I need to create a separate issue for this problem?

**Comment by Aokromes** [comment] 2024-04-16 10:04
> > > Ubuntu 20.04, Telegram Desktop 4.16.7 - breaks when opening any personal message
> > 
> > 
> > i don't think your is video call crash no?
> 
> Do you mean that I need to create a separate issue for this problem?

if your chat have a custom background a issue is already open for that.

**Closed** 2024-04-22 00:19 UTC
Labels: bug, waiting for answer, cant reproduce
