### ISSUE TITLE
Dialogues pinning

### ISSUE THREAD

**Issue by agrml** [telegramdesktop/tdesktop#2425] opened 2016-09-13 17:05 UTC
It wold be useful to have an ability to ping some dialogues and groups to the top of the list of chats. And the next suggestion is about hiding certain chats.

**Comment by maroon775** [comment] 2016-09-19 11:49
+

**Comment by klkvsk** [comment] 2016-09-29 15:48
Please don't close it as a duplicate of #1107 
Pinning would still be useful whether categories are implemented or not. You'd still want to have several most used contacts always on top of a list, and they might be from different categories.

**Comment by DRSDavidSoft** [comment] 2016-10-09 00:29
I would vote for both pinning and categorizing. Each category should have its own sticky pins, and when the 'All' category is selected, all of the sticky pins are stuck in the top of the list.

**Comment by auchri** [comment] 2016-11-10 19:18
No api for that

**Comment by gudvinr** [comment] 2016-12-10 18:24
@auchri Now it seems that [API](https://telegram.org/blog/pin-and-ifttt) for this is arrived. Can we expect pinning in tdesktop?

**Comment by auchri** [comment] 2016-12-10 18:25
Yup ;)

**Comment by DRSDavidSoft** [comment] 2016-12-10 22:08
Finally!

**Closed** 2017-01-11 22:00 UTC
Labels: enhancement
