### ISSUE TITLE
Allow stopping gifs

### ISSUE THREAD

**Issue by Eccenux** [telegramdesktop/tdesktop#2313] opened 2016-08-05 12:35 UTC
### Steps to reproduce
1. Post a gif to chat.

### Expected behaviour
Play once or two and stop automatically. Allow playing again and stopping.

### Actual behaviour
Plays endlessly. There seem to be no way of stopping it (except deleting the post or spamming the chat to make it go away...)

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 0.10

**Comment by timocov** [comment] 2016-08-05 20:00
You can disable gif autoplay and then you can stop and play gifs by click on it

**Comment by auchri** [comment] 2016-08-05 20:02
Duplicate of #1485 btw.

**Closed by auchri** 2016-08-05 20:02 UTC

**Comment by inopinatus** [comment] 2018-07-20 06:01
lies.  if you click on it it just opens in the middle of the screen.

**Comment by StefanOssendorf** [comment] 2018-08-27 07:12
@inopinatus No. You have to disable the gif autoplay first. Settings -> Automatic media download settings -> "Automatic GIF download" uncheck Autoplay.
After that you can click on the gif to start and stop.

**Comment by inopinatus** [comment] 2018-09-26 02:55
@StefanOssendorf No, that doesn't work, at least not on the Mac client.

I have _Autoplay GIFs_ unchecked and _Auto-Download Media_ unchecked. Clicking an animated GIF once will start it playing. Clicking a second time opens it in the middle of the screen; still playing.

Loss of application focus doesn't stop it either, which I find just plain obnoxious.

The only way I can find to stop them playing is to click away into another chat and then back again.

**Comment by john-preston** [comment] 2018-09-26 04:49
@inopinatus What version do you try?

**Comment by Ddorda** [comment] 2019-02-12 20:21
why was the ticket closed? issue still exists.
