### ISSUE TITLE
Super high CPU load for no reason

### ISSUE THREAD

**Issue by sapphirepro** [telegramdesktop/tdesktop#26785] opened 2023-09-13 10:36 UTC
### Steps to reproduce

1. Update Telegram to 4.9.5 or 4.9.6
2. Open chat window

### Expected behaviour

Normal low cpu usage operation.

### Actual behaviour

Stupidly high CPU load due to just a chat window being opened. It's disgusting. Version 4.9.6 fixed nothing. 40% each core load. It is not even a video call, just an ordinary chat window in KDE being opened. It triggers only on Telegram, so Telegram's bug is obvious. Started to happen since update to version 4.9.5. Please either fix or roll back changes you made, cause it's disgusting. I need CPU power for other things different from Telegram and just one messenger eating mobile xeon CPU all 4 cores 40% is unacceptable! More over I pay for premium and that's definitely not a premium quality. If bug not eliminated till next recurring payment I just cancel premium subscription.

### Operating system

OpenSUSE Tumbleweed Linux x86_64

### Version of Telegram Desktop

4.9.6

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2023-09-13 10:41
> Version 4.9.6 fixed nothing.

Why should it fix something? :thinking: 

> or roll back changes you made

Would you be so kind to point to those changes? Cause I'm unable to reproduce and if you won't point then it won't be fixed nor anything would be reverted.

**Comment by ilya-fedin** [comment] 2023-09-13 10:43
Note if you have moving items in chat then that's expected (CPU work happens to render those screen changes) and the only thing you could do is to enable battery saving in settings.

**Comment by sapphirepro** [comment] 2023-09-13 11:07
> > Version 4.9.6 fixed nothing.
> 
> Why should it fix something? 🤔
> 
> > or roll back changes you made
> 
![photo_2023-09-13_13-04-09](https://github.com/telegramdesktop/tdesktop/assets/35900229/24b24ca5-b793-4797-b160-0e937aa3e8dd)

> Would you be so kind to point to those changes? Cause I'm unable to reproduce and if you won't point then it won't be fixed nor anything would be reverted.

I attach photos. See system load without Telegram window opened and with it. It's madness. It happened since release 4.9.5 of Telegram. I have no clue what did Telegram desktop change, but it's a bug that must be fixed ASAP. Maybe wrong rendering or something. I have no clue what Telegram wastes CPU at. And see photos of system details and see another window opened without such crazy load. It's Telegram's fault 100%. I didn't review the code, I just report a bug. And I guess on photo you can see me being Telegram Premium user.

Thanks in advance for any solution coming.

![photo_2023-09-13_13-02-32](https://github.com/telegramdesktop/tdesktop/assets/35900229/6a65db3a-c90a-483e-9ad2-54bcab9c7ba3)
![photo_2023-09-13_13-02-59](https://github.com/telegramdesktop/tdesktop/assets/35900229/785b3eff-5e7b-4c4d-8ac0-61fac60d8541)

**Comment by ilya-fedin** [comment] 2023-09-13 11:20
> but it's a bug that must be fixed ASAP.

You would be sad to hear that but your report is not enough for the issue to be of high priority... If there won't be lots of reports regarding that and I won't get it reproduced then it will likely get stuck unless someone else would give a light.

> I have no clue what did Telegram desktop change

If you would do a git bisect and find the offending commit, that would help a lot.

> And I guess on photo you can see me being Telegram Premium user.

Note that GitHub repo is powered by the community and this issue tracker is meant for communication between developers and powered users who can do advanced things. If you want support level quality, please use in-app support.

**Comment by Master811129** [comment] 2023-09-13 17:57
@sapphirepro completely close the app from systray open it from terminal then post the output

**Comment by sapphirepro** [comment] 2023-09-13 19:28
Ok. Done. Here is output

`Sapphire@SapphirePro:/AutoErase> /home/Sapphire/Telegram/Telegram > output.txt
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter

(Telegram:21925): Gtk-WARNING **: 21:22:51.941: Theme parsing error: <data>:1:0: Expected a valid selector
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
`

**Comment by sapphirepro** [comment] 2023-09-13 19:30
At the same time if I use other Qt apps, including KDE own ones - all fine, no any errors output, but Telegram shows what I posted above + eats a lot of cpu all the time if chat window being open

**Comment by sapphirepro** [comment] 2023-09-13 22:32
Last info maybe useful to add here. Package got from here https://telegram.org/dl/desktop/linux (tar.gz version) long ago and always updated from inside app itself (self update mechanism). Since version 4.9.5 (4.9.6 also with that bug) all became using cpu a lot in Telegram.

**Comment by sapphirepro** [comment] 2023-09-13 22:33
> @sapphirepro completely close the app from systray open it from terminal then post the output

Hello and check answers above, please. Thanks in advance

**Comment by sapphirepro** [comment] 2023-09-13 22:48
> @sapphirepro completely close the app from systray open it from terminal then post the output

with Telegram 4.9.7 output is a bit less errors, but same cpu load.

Output:

```
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment

(Telegram:792): Gtk-WARNING **: 00:46:07.533: Theme parsing error: <data>:1:0: Expected a valid selector
```

**Comment by sapphirepro** [comment] 2023-09-14 05:06
Ok.

I found a way to reproduce.
![Screenshot_20230914_070108](https://github.com/telegramdesktop/tdesktop/assets/35900229/e7e204b5-72bf-46cb-b406-9ba8c76bbbf4)

Add like this, many animated emoji enabled and it will play on emoji tab. Counting Telegram makes it Premium, it's an epic nonsense. I will try to contact Telegram also, if they don't fix, demand refund.

So just add those animated emoji and open window being active, so that it plays it and let your CPU cook a beacon on it. It must be GPU accelerated and wisely cached, not using software rendering for it overloading the whole system with a stuff that normally shouldn't consume any sensible CPU usage at all

**Comment by sapphirepro** [comment] 2023-09-14 05:14
> @sapphirepro completely close the app from systray open it from terminal then post the output

so please remove "can't reproduce" label. You can reproduce it, see just one post above. And that's a serious bug, especially counting all those stuff are premium charged by Telegram

**Comment by ilya-fedin** [comment] 2023-09-14 05:30
That's expected. If you don't like this, disable animations in Settings -> Battery Saving.

**Comment by sapphirepro** [comment] 2023-09-14 05:37
> That's sadly expected, tdesktop is built on top of QtWidgets and so uses purely CPU for rendering, rendering animated emojis needs a lot of effort from your CPU. If you don't like this, disable animations in Settings -> Battery Saving or switch to Telegram-A that is built on top of Electron and so uses GPU-based rendering.
> 
> Even though it's a valid problem, it's an architectural problem, so it's unlikely to be fixed...

Do you mean no solution possible at all in the first place? What about OpenGL rendering of those things? Disabling it makes "Premium" a garbage in the first place, while Telegram makes money on it. Hopefully Durov reacts on Twitter and makes something to solve it

**Comment by ilya-fedin** [comment] 2023-09-14 05:40
> What about OpenGL rendering of those things?

This requires application rewrite on top of other, GPU-accelerated framework like Electron. It will be a completely another client then and such a completely another client already exists, it's called Telegram-A, you just need to switch to it.

**Comment by sapphirepro** [comment] 2023-09-14 05:50
> Telegram-A

Google doesn't find such a client. Well, what to do, then Telegram Desktop need a whole rewrite, as Telegram only keeps adding animated stuff, so it's only going to get worse and worse

**Comment by ilya-fedin** [comment] 2023-09-14 05:50
Seem to be a dup of #25952

**Comment by ilya-fedin** [comment] 2023-09-14 05:51
> Google doesn't find such a client.

https://github.com/Ajaxy/telegram-tt/releases/latest

**Closed** 2023-09-14 05:51 UTC
Labels: bug

**Comment by sapphirepro** [comment] 2023-09-14 06:02
Besides, take a look here, maybe it's some option through -  https://stackoverflow.com/questions/41179514/qt5-on-imx6-how-to-make-sure-the-hardware-acceleration-is-in-use

**Comment by sapphirepro** [comment] 2023-09-14 06:04
And here too - https://stackoverflow.com/questions/36568668/how-to-use-qpainter-in-qopenglwidgets-paintgl

Should be a solution, Qt is not that dumb to fail and simply OpenGL support

**Comment by sapphirepro** [comment] 2023-09-14 06:05
> Seem to be a dup of #25952

look at links above please, seems like some solution exists

**Comment by ilya-fedin** [comment] 2023-09-14 06:05
Using QOpenGLWidget means rewriting from Qt widget to pure GL code (that's something media viewer and call window are doing partially but still application needs to be entirely rewritten for this and I guess would require even more effort than Electron and would be less stable). Using Qt Quick means rewriting to another toolkit just like with Electron (google difference between QtWidgets and QtQuick), too.

**Comment by sapphirepro** [comment] 2023-09-14 06:08
> Using QOpenGLWidget means rewriting from Qt widget to pure GL code (that's something media viewer and call window are doing partially but still application needs to be entirely rewritten for this and I guess would require even more effort than Electron and would be less stable). Using Qt Quick means rewriting to another toolkit just like with Electron (google difference between QtWidgets and QtQuick), too. There's no magic solution to this. Only full rewrite work which is probably better done by abandoning tdesktop and replacing it with Unigram/Telegram macOS/Telegram-A cause they're already written.

But they are no official and therefore trust void + not always up to date third-party apps. Telegram went commercial, so yeah, it needs efforts

**Comment by ilya-fedin** [comment] 2023-09-14 06:10
They are official. macos.telegram.org, weba.telegram.org. telegram-tt is the repository of Web A. Unigram is indeed half-official.

**Comment by sapphirepro** [comment] 2023-09-14 06:24
> Using QOpenGLWidget means rewriting from Qt widget to pure GL code (that's something media viewer and call window are doing partially but still application needs to be entirely rewritten for this and I guess would require even more effort than Electron and would be less stable). Using Qt Quick means rewriting to another toolkit just like with Electron (google difference between QtWidgets and QtQuick), too. There's no magic solution to this. Only full rewrite work which is probably better done by abandoning tdesktop and replacing it with Unigram/Telegram macOS/Telegram-A cause they're already written.

According to this => https://www.electronjs.org/docs/latest it's based on Google product. What privacy Telegram will promote feeding google with private data? I have banned all google products from installing in the first place, cause it's anti trust corporation. Qt is trust worthy, same as Telegram, that's why I use it

**Comment by ilya-fedin** [comment] 2023-09-14 06:30
Qt is sadly lagging behind desktop technologies a lot. Its OpenGL support is very crashy (there are lots of reports about media viewer crashes, graphics artifacts and what not), Qt Quick (QML) feels unstable and buggy as well. The only cross-platform modern toolkits are from Google or are based on Google technologies, like you that or not: Electron, Flutter. Skia is the only GPU-accelerated renderer library (at least the only that is popular and worths trust), is made by Google. Electron is the only framework that has multi-process architecture, that is the only way to avoid OpenGL crashes cause OpenGL drivers are almost always crashy on all the platforms.
