### ISSUE TITLE
[Question]  I got an error to build on windows 10，please help me thanks

### ISSUE THREAD

**Issue by fish6688** [telegramdesktop/tdesktop#23936] opened 2022-01-20 08:25 UTC
I am getting the following error when building on Windows 10, please help, thanks.
![image](https://user-images.githubusercontent.com/61409802/150300740-5f35c5ca-9df4-4296-8bbb-87981c0bccd5.png)

**Comment by fish6688** [comment] 2022-01-20 10:06
@john-preston @ilya-fedin
Please help me, thanks a lot.

**Comment by john-preston** [comment] 2022-01-20 10:10
@fish6688 this is some problem in python / gyp / your locale, I don't know how to fix that. Fortunately, you don't really need `dump_syms`. I think your best bet is to remove those lines:
```
    cd tools\\windows\\dump_syms
    gyp dump_syms.gyp --format=ninja
    cd ..\\..\\..
    ninja -C out/Release%FolderPostfix% dump_syms
```
from `tdesktop/Telegram/build/prepare/prepare.py`, then run `prepare/win.bat` again.

**Comment by fish6688** [comment] 2022-01-20 10:19
Ok, I'll try it now, any help is greatly appreciated.

**Comment by Aokromes** [comment] 2022-01-20 11:33
i told you to stop closing still valid issues and open new issues.

**Comment by ilya-fedin** [comment] 2022-01-20 11:34
ban him!

**Comment by fish6688** [comment] 2022-01-21 03:08
Sorry, maybe I don't understand the rules well, I didn't figure out what's a little problem. I thought of closing the ones I don't need so I can ask new ones. Sorry to trouble you, I will pay attention in the future.

**Comment by ilya-fedin** [comment] 2022-02-11 16:03
Seem to be a duplicate of #16939 actually

**Closed** 2022-02-11 16:47 UTC
Labels: question
