### ISSUE TITLE
Telegram Desktop crashes when locking up the screen on Gnome 46, Fedora 40

### ISSUE THREAD

**Issue by Impasse52** [telegramdesktop/tdesktop#28158] opened 2024-07-12 06:06 UTC
### Steps to reproduce

1. Start up Telegram Desktop
2. Lock up the screen
3. Unlock the screen
4. Verify that Telegram Desktop crashes

### Expected behaviour

Telegram Desktop should stay up and running with no crashes.

### Actual behaviour

Telegram Desktop crashes and causes a core dump. The following is found when running `journalctl -xe`:

```
Jul 12 07:49:39 fedora systemd-coredump[5085]: [🡕] Process 4646 (telegram-deskto) of user 1000 dumped core.
                                               
                                               Stack trace of thread 2:
                                               #0  0x00007f68119f91d4 n/a (/app/lib/libQt6Gui.so.6.7.2 + 0x1f91d4)
                                               #1  0x00007f68109cc734 n/a (/app/lib/libQt6Core.so.6.7.2 + 0x1cc734)
                                               #2  0x00007f68109cc734 n/a (/app/lib/libQt6Core.so.6.7.2 + 0x1cc734)
                                               #3  0x00007f68119bd134 n/a (/app/lib/libQt6Gui.so.6.7.2 + 0x1bd134)
                                               #4  0x00007f680b0e9bc3 n/a (/app/lib/libQt6WaylandClient.so.6.7.2 + 0x80bc3)
                                               #5  0x00007f680b10fe03 n/a (/app/lib/libQt6WaylandClient.so.6.7.2 + 0xa6e03)
                                               #6  0x00007f680e1a0056 n/a (/usr/lib/x86_64-linux-gnu/libffi.so.8.1.4 + 0x9056)
                                               #7  0x0000000000000000 n/a (n/a + 0x0)
                                               ELF object binary architecture: AMD x86-64
░░ Subject: Process 4646 (telegram-deskto) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 4646 (telegram-deskto) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.
```

### Operating system

Fedora 40

### Version of Telegram Desktop

5.2.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment] 2024-07-12 09:23
```
flatpak install --no-auto-pin org.freedesktop.Sdk{,.Debug}//23.08 org.telegram.desktop.Debug
flatpak-coredumpctl org.telegram.desktop
```

**Comment by Impasse52** [comment] 2024-07-12 14:12
I'm struggling to understand how to use this so let me know if this is correct. I executed your command, I ran Telegram Desktop and I waited for core dumps to show up in the `flatpak-coredumpctl` command.

This is what I got:

```
^[[B[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/app/bin/telegram-desktop'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb43cdf91d4 in QPlatformScreen::screen() const () from /app/lib/libQt6Gui.so.6
[Current thread is 1 (Thread 0x7fb4366db2c0 (LWP 2))]
```

**Comment by Impasse52** [comment] 2024-07-12 18:59
> Your output sadly lacks the backtrace and thus of no help:(

Is it supposed to show up? I feel like I'm not understanding your directions so feel free to let me know :/

**Comment by ilya-fedin** [comment] 2024-07-12 19:13
I'm not sure either, I don't remember how it's supposed to work... Maybe it would be easier for you to switch to the official binary with built-in crash reporter? You just have to enable beta version installation in settings, reproduce the crash and you will get a crash id on next launch (don't forget to actually send crash report) which you can post here.

**Comment by LetzteInstanz** [comment] 2024-07-16 09:00
The same is under Ubuntu 24.04: #28171.

**Comment by iammark2** [comment] 2024-07-28 20:18
Same issue for me, same verson of Telegram Desktop, 5.2.3

**Comment by Etherdrake** [comment] 2024-08-01 23:11
Issue just started for me as well.

**Comment by AnthraX1** [comment] 2024-08-31 05:49
same problem.

**Comment by Impasse52** [comment] 2024-09-10 11:10
Problem still persists, and I noticed that it also occurs on other desktop environments such as Plasma 6.

**Comment by ilya-fedin** [comment] 2024-09-10 12:11
I'm still waiting for a backtrace. The issue is not actionable without a backtrace.

**Comment by ilya-fedin** [comment] 2024-09-10 12:14
Without the required info, the bot will just close the issue again.

**Comment by leo-puh** [comment] 2024-09-11 04:51
Hi @ilya-fedin , are crash ids equal to *.dmp file names in the ~/.local/share/TelegramDesktop/tdata/dumps dir? If so, here are some of mine:
04f67d50-722d-4e57-fb35db9f-70f39b58.dmp
debd47e2-9e95-4ff2-ec2c0595-752e227e.dmp
5c6d7735-c439-4b1c-947536b2-3e6fb351.dmp
6c8b69d1-6c32-4c5d-8601b89e-df0a6c8d.dmp
c56400ff-f3dc-4e87-4386c9a3-eab9dcca.dmp
d260d65f-58b4-4bf4-45f100b1-1d393c05.dmp
9557f861-da68-4539-2bb1ada0-45e7e126.dmp
b12f5f5f-6963-4f7a-d3512580-2e13cd7d.dmp
4c512fc0-551a-4e07-7fc595bc-d4456f45.dmp
3490f212-12f0-42c0-c720ea92-619cd285.dmp

**Comment by leo-puh** [comment] 2024-09-11 09:43
Crash reporting was enabled, pls let me know if you can't find them and where to upload them again if necessary.

**Comment by ilya-fedin** [comment] 2024-09-11 12:36
None of those crashes are from the latest version

**Comment by leo-puh** [comment] 2024-09-11 12:43
Well, they should have been from the latest-to-that-moment until Telegram became broken with mutter and I switched to stable. 
Now stable is also broken so I easily switched back to the beta stream and will report here as soon as it crash.

**Comment by ilya-fedin** [comment] 2024-09-11 12:50
All those crashes point to Qt internals and Qt was updated in 5.4.5.

**Comment by Etherdrake** [comment] 2024-09-13 17:02
> All those crashes point to Qt internals and Qt was updated in 5.4.5.
. 
I had it happen with GNOME which uses GTK+.

**Comment by ilya-fedin** [comment] 2024-09-13 18:05
I'm not sure how it is related what GNOME uses...

**Closed** 2024-09-25 00:48 UTC
Labels: bug, waiting for answer
