### ISSUE TITLE
Not being able to edit and replace sent images with a new image like on android

### ISSUE THREAD

**Issue by Terrydaktal** [telegramdesktop/tdesktop#5278] opened 2018-10-18 15:38 UTC
I keep having to send myself the image and go to my android client and make the change on that. I should be able to do this on the desktop client, when is this feature going to be implemented?

**Comment by RememberTheAir** [comment] 2018-10-18 17:51
Duplicate of #5149

**Closed** 2018-10-19 17:33 UTC
