### ISSUE TITLE
Call interference

### ISSUE THREAD

**Issue by GooseBumpsOS** [telegramdesktop/tdesktop#16757] opened 2021-08-04 18:34 UTC
### Actual behaviour
During a call, I hear noises for every word of the caller(as when talking on the radio, like radio interference), it doesn't matter who starts the call. This problem appeared after updating to version 2.9. I installed the old version of TG from GitHub(I chose v2.8.0), the problem disappeared, after clicking on update button inside the application, this bug appeared again.

### Configuration
**Operating system:**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Version of Telegram Desktop:**
2.9.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Tried with: 
1. snap
2. official website
3. GitHub release

**Comment by meklonets** [comment] 2021-08-05 08:39
I confirm. The problem exists.

**Comment by mariosant** [comment] 2021-08-05 08:59
Is this a duplicate of https://github.com/telegramdesktop/tdesktop/issues/16733 ?

**Comment by Aokromes** [comment] 2021-08-05 09:25
yes

**Closed by Aokromes** 2021-08-05 09:25 UTC
