### ISSUE TITLE
Feature request: Autofocus search input on pressing Ctrl/Cmd+F

### ISSUE THREAD

**Issue by emitstop** [telegramdesktop/tdesktop#97] opened 2014-08-05 00:50 UTC
It'd be great if I could hit ctrl+f and have it autofocus the search input.
Just a bit of nice UX polish that I think would be nice to have!

**Comment by joshery420** [comment] 2015-02-20 23:39
Trying to get a single thread for this feature request.
Maybe mark this as a duplicate of Issue #364 since that one has recent attention.

**Comment by auchri** [comment] 2015-08-14 20:24
Added

**Closed by auchri** 2015-08-14 20:24 UTC
