### ISSUE TITLE
Black (hence almost invisible) systray icon in KDE Linux

### ISSUE THREAD

**Issue by SinTan1729** [telegramdesktop/tdesktop#7488] opened 2020-03-29 04:52 UTC
### Steps to reproduce
1. Just start the app

### Expected behaviour
Systray of more visible color should appear

### Actual behaviour
Black systray icon appears (used to be blue before the last update)

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 1.9.21

**Used theme**: Tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by xvitaly** [comment] 2020-03-29 10:12
Duplicate of #7399.

**Closed** 2020-03-29 11:44 UTC
