### ISSUE TITLE
[Feature Request] don't show messages from blocked users in group chat

### ISSUE THREAD

**Issue by iddq** [telegramdesktop/tdesktop#8279] opened 2020-07-20 08:44 UTC
don't show messages from blocked users in group chat. thank you.

**Comment by RememberTheAir** [comment] 2020-07-20 09:50
Duplicate of #1025, #1281, #5492

**Closed** 2020-07-20 10:25 UTC

**Comment by iddq** [comment] 2020-07-21 09:24
Why do you close it if it is not implemented?

**Comment by RememberTheAir** [comment] 2020-07-21 09:51
@iddq because it's an API issue and needs to be implemented in the API first

**Comment by gmsantos** [comment] 2020-07-23 16:36
@RememberTheAir do the backend have a roadmap, issues, discussions, whatever, for these kinds of issues?

**Comment by RememberTheAir** [comment] 2020-07-24 06:46
Nope, you can only suggest things to the in-app support or [on Twitter](https://twitter.com/telegram)
