### ISSUE TITLE
The app consumes an enormous amount of RAM after a short period of use.

### ISSUE THREAD

**Issue by farivar-tabatabaei** [telegramdesktop/tdesktop#25189] opened 2022-10-14 08:42 UTC
### Steps to reproduce:
**Usual Memory Leak:**
1. Open the Telegram app
2. watch some videos or any media
3. scroll through some channels posts

- Result ---> using around 6.5 GB - 8 GB of ram.

**Extreme Memory Leak:**
1. Close the app without clearing the ram manually
2. run it again
3. watch some media
4. scroll through some channels posts 

- Result ---> adding to the previous amount of allocated ram.

### Configuration:

- **OS:** Windows 11 - Build 22623.741
- **Platform:** AMD R9 64-bit
- **Telegram Version**: 4.2.4
- **Source**: The binary on Telegram's official website

### Some Notes:
I'm not aware of how much ram the app should use technically, but using 6.5 GB - 8 GB of ram after running for 15 minutes doesn't look very reasonable.

I think it's an old memory leak problem of the telegram desktop that happens after playing video files or watching photos that have been reported in previous versions, like since 2015, and have been discussed a lot before but it has not been fixed since then.

my issue can be related to #1317, #7361, #7280, #10327, #10516, and #16084, I know the actual technical reason may be different, but apparently, all these issues are reporting the same kind of problem over and over again.

Also, using apps like IOBit Advanced SystemCare's ram cleaner works without affecting the app's performance or causing it to crash, so it confirms the memory leak that we all know exists, so is there a technical limitation or something that no one has fixed this problem?
And sometimes when you close the app the data in the RAM is still there and does not get cleaned by the garbage collector until I call the ram cleaner, so if I open the app again without clearing the ram it just uses more and more and if you do it a couple of times it fills up the entire ram till there is no more space in it.

And one more thing that I'm not entirely sure of is that clearing local storage using the app's built-in function can reduce ram usage.

**If any more information is required let me know.**

**Comment by ilya-fedin** [comment] 2022-10-14 20:37
#25162?

**Comment by farivar-tabatabaei** [comment] 2022-10-15 08:24
> #25162?

Not exactly, in #25162, its-monotype says that this problem doesn't happen for him always, but in my case, it happens every single time I use the Telegram desktop app. So it is a more severe case of his problem, and also the process of filling the ram continues until there is no more ram left and the Telegram desktop app is now practically unusable for me.

**Comment by ilya-fedin** [comment] 2022-10-15 08:31
Maybe you enabled hardware decoding feature? It's very bugged

**Comment by farivar-tabatabaei** [comment] 2022-10-15 08:56
> Maybe you enabled hardware decoding feature? It's very bugged

It was enabled at first, but it came to my mind that HW decoding may be the cause of the problem so I turned it off but nothing changed and it didn't fix the problem.

**Comment by farivar-tabatabaei** [comment] 2022-10-15 09:14
> Maybe you enabled hardware decoding feature? It's very bugged

**Found it!!!**
It's the **ANGLE graphics backend**, when it's set to **Direct3D 11** or **auto** that chooses Direct3D 11 and you play even a single 4MB video the ram just ramps up gigabytes, but when it's set to **OpenGL** or **Direct3D 9** it's perfect.

And I found another problem in the process that is when I set ANGLE graphics backend to D3D11on12 and play a video the video player doesn't show up at all, it's there as an overly because I can't click on anything and the audio is playing, so yep here is another problem.

### FIX:

- **Changing ANGLE graphics backend to Something other than Direct3D 11**

**Comment by ilya-fedin** [comment] 2022-10-15 09:33
OpenGL is likely no-op and actually disables ANGLE

**Comment by farivar-tabatabaei** [comment] 2022-10-15 14:16
> OpenGL is likely no-op and actually disables ANGLE

As I said Direct3D 9 works too even with HW decoding enabled.

Anyway, I tested the app on the same hardware and as you can guess the results were the same, so on the second windows machine I changed the graphics card driver to the latest DCH driver available and it fixed the problem, so I don't exactly know why, but apparently, the Direct3D 11 problem is with AMD's legacy drivers no the DCH one's.

**Comment by Aokromes** [comment] 2022-10-15 15:23
then 3rd party bug?

**Comment by farivar-tabatabaei** [comment] 2022-10-15 15:39
> then 3rd party bug?

I'm not sure exactly, I should look into it deeper, but everything aside, the memory leak bug is there, and as I mentioned earlier there were and are many complaints about this memory leak, and actually, one them that [ilya-fedin](https://github.com/ilya-fedin) mentioned is about the recent version, so I'll keep looking and also I'll keep an eye on #25162 till [its-monotype](https://github.com/its-monotype) provide more information, thanks, guys.

**Comment by ilya-fedin** [comment] 2022-10-15 23:33
His leak may be due to another reason. If it's the same reason then there's no other fix then blacklisting your and his graphics driver.

**Comment by farivar-tabatabaei** [comment] 2022-10-17 04:36
> > OpenGL is likely no-op and actually disables ANGLE
> 
> As I said Direct3D 9 works too even with HW decoding enabled.
> 
> Anyway, I tested the app on the same hardware and as you can guess the results were the same, so on the second windows machine I changed the graphics card driver to the latest DCH driver available and it fixed the problem, so I don't exactly know why, but apparently, the Direct3D 11 problem is with AMD's legacy drivers no the DCH one's.

Nope, It's there again, even with the legacy drivers, I wonder why I took some time to show up 🤷‍♂️.

**Comment by ilya-fedin** [comment] 2022-10-17 04:38
Try to disable both ANGLE and HW decoding

**Comment by pleabargain** [comment] 2023-01-13 07:52
v v4.5 30.12.22
win 10
Telegram does not have focus
it is not running in the foreground but it's consuming 500MG of memory
![image](https://user-images.githubusercontent.com/640846/212266901-af79bd6f-a805-4b09-9241-0a4223ccc8cf.png)

**Comment by ilya-fedin** [comment] 2023-01-13 08:08
500 MB is ok, it's the average tdesktop consumption in most setups

**Comment by Igorgro** [comment] 2023-02-05 12:06
I've just runned Telegram on Arch Linux and it is already using 1.1Gb of RAM
![image](https://user-images.githubusercontent.com/22894169/216817723-7f034c2f-7313-4088-8e16-6f71d73a6ce4.png)

**Comment by nikelborm** [comment] 2023-03-08 23:46
Same thing for me on latest arch + gnome 43
And it is just after the start

after some runtime it becomes up to 1.5 gb

![Screenshot from 2023-03-09 02-44-11](https://user-images.githubusercontent.com/29357907/223878247-2f6f9469-ead5-4967-8ae6-56c6accb6be5.png)

**Comment by john-preston** [comment] 2023-03-10 12:21
@Igorgro @nikelborm Please check if it is better in beta 4.6.9, there were unneeded allocations in colored custom emoji sets, if we're lucky that was your case.

**Comment by nikelborm** [comment] 2023-03-11 18:21
I've run binary from this release and it now takes even more RAM
https://github.com/telegramdesktop/tdesktop/releases/tag/v4.6.9
![Screenshot from 2023-03-11 21-20-21](https://user-images.githubusercontent.com/29357907/224505183-04bc743a-76ed-4700-ad57-59eea918eef6.png)

**Comment by nikelborm** [comment] 2023-03-11 18:47
This is consumption after i return back to 4.6.5
![Screenshot from 2023-03-11 21-47-54](https://user-images.githubusercontent.com/29357907/224506231-e856fbd4-3511-4b3d-bd65-78d985b61a20.png)

**Comment by Igorgro** [comment] 2023-03-27 07:10
I agree with previous commenters - looks like the app uses more and more ram after each release. It consumes even more ram that vscode (which is written in electron)

**Comment by ilya-fedin** [comment] 2023-03-27 07:13
Maybe you're using a third party build with bad allocator?
![изображение](https://user-images.githubusercontent.com/17829319/227867210-7fda2655-cc54-4bf6-977f-ce26171ec313.png)

**Comment by nikelborm** [comment] 2023-03-27 07:27
@ilya-fedin How can it be third-party build if I downloaded it from the provided link (official release page on github)?

> I've run binary from this release and it now takes even more RAM https://github.com/telegramdesktop/tdesktop/releases/tag/v4.6.9

**Comment by ilya-fedin** [comment] 2023-03-27 07:33
I also heard that some GPU drivers add used VRAM to the used RAM value on Linux (Intel?), so it may be hardware dependent. Personally I have AMD hardware.

**Comment by nikelborm** [comment] 2023-03-27 07:58
@ilya-fedin I'm using arch notebook with no additional GPU (CPU graphics)

And by the way i checked memory consumption on latest version from AUR and it is significantly lower now

![Screenshot from 2023-03-27 10-58-44](https://user-images.githubusercontent.com/29357907/227877721-0d609394-78c1-471e-81fb-312d0e782ea5.png)

**Comment by ilya-fedin** [comment] 2023-03-27 10:40
> I'm using arch notebook with no additional GPU (CPU graphics)

that is not really a helpful information, integrated GPU is a GPU from software point of view.

**Comment by nikelborm** [comment] 2023-03-27 12:26
```
screenfetch 
                   -`                 
                  .o+`                 nikel@archhost
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 6.2.8-arch1-1
               `+oooooo:               Uptime: 2d 3h 59m
               -+oooooo+:              Packages: 1427
             `/:-:++oooo+:             Shell: bash 5.1.16
            `/++++/+++++++:            Resolution: 3840x2560
           `/++++++++++++++:           DE: GNOME 43.4.1
          `/+++ooooooooooooo/`         WM: Mutter
         ./ooosssso++osssssso+`        WM Theme: 
        .oossssso-````/ossssss+`       GTK Theme: Adwaita-dark [GTK2/3]
       -osssssso.      :ssssssso.      Icon Theme: Adwaita
      :osssssss/        osssso+++.     Font: Noto Sans,  10
     /ossssssss/        +ssssooo/-     Disk: 128G / 457G (29%)
   `/ossssso+/:-        -:/+osssso+-   CPU: AMD Ryzen 7 5800H with Radeon Graphics @ 16x 3.2GHz
  `+sso+:-`                 `.-/+oso:  GPU: AMD/ATI Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
 `++:.                           `-/+/ RAM: 9624MiB / 13830MiB
 .`                                 `/
```

**Comment by ilya-fedin** [comment] 2023-03-27 12:34
> 3840x2560

Ah, you have HiDPI hardware, that pretty explains RAM usage: tdesktop caches interface parts a lot in order to stay perfomant while using CPU-based rendering (tdesktop is not capable of GPU rendering outside of media viewer and calls window and even there it's partical), the more scaling you have, the bigger resolution of raster caches in RAM are, the more RAM usage. This is pretty intended behavior.

Also, tdesktop predates modern HiDPI practices and operates in a global scale factor from the most biggest scale factor of all monitors in the system. I.e. if you have a 1x, 2x and 3x monitors in the system, tdesktop will generate 3x pixmaps no matter which screen tdesktop window on with raster downscaling of system or Qt.

**Comment by nikelborm** [comment] 2023-03-27 12:41
But it still does not explain why it was like 1.5 GB of RAM

Now it is about 600 Mb on the same 4k monitor

Have developers removed all the caches in few latest versions?

**Comment by ilya-fedin** [comment] 2023-03-27 12:55
> Have developers removed all the caches in few latest versions?

As far as I'm aware, no. Although for me it's always were and is 480M at start.

**Comment by MaxRev-Dev** [comment] 2023-03-31 22:28
Telegram 4.7.1
Windows 11 (22H2)

Memory Leak
Sometimes happens after a computer is idle for a long time.
After a startup, it also uses 2GB+ RAM. It can't be hidden in a tray with that amount of RAM.
I have to close the app when I don't use it(

How you can reproduce it: 
- Try to open any video or photo in full-screen mode and close it.
- After viewing a few media, you will get +1GB of allocated RAM.

![image](https://user-images.githubusercontent.com/24393967/229243751-e89349de-6522-4cd9-b54c-eca9f59a89fc.png)

**Comment by john-preston** [comment] 2023-08-11 07:30
@farivar-tabatabaei @MaxRev-Dev Please check the latest beta 4.8.11:

https://github.com/telegramdesktop/tdesktop/releases/tag/v4.8.11

On Windows with Direct3D 11 backend for ANGLE. I hope it won't leak memory anymore, I've updated ANGLE and found a workaround for strange memory allocations.

**Closed** 2023-08-26 00:15 UTC
Labels: waiting for answer
