### ISSUE TITLE
Telegram prevents Windows 8.1 automatic sleep

### ISSUE THREAD

**Issue by thepillow86** [telegramdesktop/tdesktop#229] opened 2014-11-02 22:18 UTC
When telegram is opened, it prevents windows 8.1 from going into sleep mode, because it opens an audiostream. 
I found this through running the powercfg /requests command in CMD. 
Telegram opens a Realtek HD Audio stream:
---------------
C:\Windows\system32>powercfg /requests
DISPLAY:
None.

SYSTEM:
[DRIVER] Realtek High Definition Audio (HDAUDIO\FUNC_01&VEN_10EC&DEV_0668&SUBSYS
_102805FD&REV_1000\4&325a6d8c&0&0001)
An audio stream is currently in use.

AWAYMODE:
None.

EXECUTION:
None.

PERFBOOST:
None.

**Comment by fefrei** [comment] 2015-01-16 07:07
Let me add that this is extremely annoying.

In addition to the Audio Stream entry shown above, Telegram also causes this entry for me:

    [DRIVER] Legacy Kernel Caller

**Comment by telegramdesktop** [comment] 2015-01-29 12:12
Should be fixed, try the latest version 0.7.10.

**Closed by telegramdesktop** 2015-01-29 12:12 UTC

**Comment by fefrei** [comment] 2015-01-29 13:38
I can confirm this is fixed. The audio stream opens on demand and closes soon after the sound has finished.

**Comment by terraquian** [comment] 2016-02-18 20:02
this problem was solved in the past but now occurs again (i'm a windows 10 user)

**Comment by fefrei** [comment] 2016-02-18 20:53
Are you sure this is the same problem? I cannot reproduce it.
Can you post an output of `powercfg /requests`?

**Comment by terraquian** [comment] 2016-02-20 20:43
certainly, it just try and does not happend. sorry :-(
