### ISSUE TITLE
[Feature Request] Desktop Client add alternative to push to talk for avoiding misclicks and losing voice record.

### ISSUE THREAD

**Issue by anacondaq** [telegramdesktop/tdesktop#6365] opened 2019-08-07 19:36 UTC
### Is your feature request related to a problem?
Desktop version. Whole problem related to this button:
![](https://i.imgur.com/G0PMraL.gif)
I must hold it for recording and have a very small area where I must to hold my mouse and keep a mouse cursor in this small area. I'm and all my friends with who I talk in the telegram via voice recording have the same problems. ALL of them, and very angry because of that.
The problem very simple: VERY FREQUENTLY because of releasing the mouse after several minutes holding it outside the box resulting in losing several minutes of voice record, which makes everyone (me, my friends, and so on) very angry. This is a problem. This feature with a voice recorder with "hold in the box mouse with left click pressed for several minutes while recording and release the mouse button in this small area" makes a lot of problems with losing voice recording over and over again. A drunk people almost always losing focus on this button, even people who do not drink alcohol have the same problem.

### Describe the solution you'd like
I want suggest add an ALTERNATIVE method for recording voice without holding the mouse button in a small area by simply adding an alternative method that works in almost all classic windows apps. I see this method by next:
- Add an option to enable alternative method of recording voices for desktop version
- In the alternative method, for recording a user must press ONCE a record button and record will be started and the user will not need to hold mouse or touch anything. And when the user decide to stop recording he will simply click on the same button one more time, and recording will stop and data will be sent to the chat. 

If you're worried about traffic or other technical stuff for example if someone will use this feature for something different, you can restrict the maximum length of voice recording for example to 10 or 20 minutes and then stop recording and asking to send the first message and then try to record another one. I do not remember that any of voice  records was more than 15 minutes in my experience. Average voice recording from me or any of my friends around 30-300 seconds long. Very rarely 600+ seconds long. 

### Describe alternatives you've considered
Add alternative option in telegram desktop version for PC (setting) where people can choose: "hold left mouse and button in a telegram (current method) or press once for start recording and press when need to stop recording and voice record will be automatically sent to the chat".

### Additional context
I strongly suggest to implement it, this is a really very important and very user-friendly feature which will minimize problems while using telegram. And I love damn so much the Telegram, but because of lack of this feature can't work with it normally, because again and again I need repeat and repeat voice recording because of small mistakes (human factor) while recording. With the feature in the suggestions, the problem will disappear.

**Comment by Aokromes** [comment] 2019-09-01 08:19
https://github.com/telegramdesktop/tdesktop/issues/6309

**Comment by exegg** [comment] 2019-11-21 01:04
Please how is this not being considered? It is so annoying

**Comment by RadRussianRus** [comment] 2019-11-24 04:40
Isn't it a duplicate of #3208?

**Comment by anacondaq** [comment] 2019-11-24 09:13
This is not a duplicate, this is "bump/reminder/<please focus on me>" of the most annoying problem in the desktop version of telegram.

But it seems nobody cares about the feature for almost 3 years, and nobody will implement it because of the lack of understanding of what the user really needs and asks directly.

**Comment by RadRussianRus** [comment] 2019-11-24 11:30
"bump/reminder" is still a duplicate.

**Closed** 2019-11-24 12:24 UTC
Labels: enhancement
