### ISSUE TITLE
[Bug] Folder badge counters show muted chats even with "include muted chats" setting disabled

### ISSUE THREAD

**Issue by ccrowles** [telegramdesktop/tdesktop#7634] opened 2020-04-13 18:17 UTC
**Steps to reproduce:**
Create a folder that has both unmuted and muted chats (i.e. the default "groups" chat).
Disable "Include muted chats in unread count"
Optional: enable "count unread messages"

**Expected behaviour**
It should only count messages for unmuted chats

**Actual behaviour**
It counts muted chats in the badges. Also it seems to count only chats and not messages themselves even though I checked "count unread messages"

**Configuration**
Operating system: Windows 10
Version of Telegram Desktop: 2.0.1

![ScreenShot04301](https://user-images.githubusercontent.com/12866474/79146817-3cc72400-7dc3-11ea-824c-8753092e24bf.jpg)

![ScreenShot04302](https://user-images.githubusercontent.com/12866474/79146974-81eb5600-7dc3-11ea-9442-3b9b00e6e27d.jpg)

**Comment by RememberTheAir** [comment] 2020-04-14 06:39
This is actually the intended behavior. It's rather a feature request

**Comment by ccrowles** [comment] 2020-04-15 15:16
> This is actually the intended behavior. It's rather a feature request

But the option available states otherwise? I mean if in "badge counter" section I deselect "include muted chats in unread count" and it still includes muted chats in badge unread count, it's either a bug or it makes no logical sense.

Also the fact that it still counts unread chats instead of messages even though I selected "count unread messages" is definitely a bug.

**Comment by RememberTheAir** [comment] 2020-04-16 08:01
That option is about the taskbar/tray icon counter

**Comment by ccrowles** [comment] 2020-04-16 18:56
It isn't specified in the description that it's only about that, so either the wording should be changed - and after that yes, mine will become a feature request - or if they keep it like that they should make it so it'll work with folders too. 

Also folder badge counters are super confusing like this because in folders where there are both unmuted and muted chats - let's say for example 8 muted and 3 unmuted - if you receive a message in one of the unmuted chats the badge will become highlighted... but with the counter for all of them (11!), muted and unmuted. So you don't actually know how many unmuted chats have new messages until you open that folder.

Also, when you actually do open that folder the counter stays highlighted, so you don't know if you actually opened all of the unmuted chats with new messages, until you tap on another folder to deselect that one. In my opinion that's extremely tedious and gives unclear information that require extra steps every single time.

**Comment by RememberTheAir** [comment] 2020-04-17 12:53
@ccrowles I agree with you about the current implementation not being ideal. I was just describing what is the current intended behavior. The tabs' unread counter should respect my badge settings imo

**Comment by ccrowles** [comment] 2020-04-19 14:07
Oh ok, sorry if I misunderstood. Yeah the logical thing would be that settings for the taskbar unread counter should match those for the folder unread counter. Like this the settings are misleading because it seems that you can set all badge counters like this when in fact you can't. So either they change the wording and make it clear, or (preferably) make it so it applies to both.

**Comment by JuDelCo** [comment] 2020-06-11 18:35
I also want this to be implemented. Is a bit tedious having to enter in each folder when some muted group/channel have a new message to see if some of the unmuted ones have a message because of the "(1)" in the badge of the folder, or to somehow disable those badges in the folder icons (they are too tempting to not click on them and the concentration/productivity goes down)

**Comment by RememberTheAir** [comment] 2020-06-11 19:02
@JuDelCo when there's a notification from an unmuted chat in a folder, the folder's badge counter should use a different color iirc

**Comment by JuDelCo** [comment] 2020-06-11 19:20
@RememberTheAir You're correct. But my "problem" resides in the distraction of those numbers anyway (again, is tempting to not click on them), I have a lot of folders whose channels/groups are all muted but still...

Is just that it would be nice to have an option to disable folder badges for muted channels/groups or to disable folder badges for specific folders.

**Comment by RememberTheAir** [comment] 2020-06-11 22:44
For people looking for a workaround, [Kotatogram](http://github.com/kotatogram/kotatogram-desktop) has such an option

**Comment by ccrowles** [comment] 2020-06-13 11:32
> For people looking for a workaround, [Kotatogram](https://github.com/kotatogram/kotatogram-desktop) has such an option

Thanks, meanwhile I'll use this. Although I still really hope to see this fix/enhancement implemented in the official Tdesktop and and Android version. Because of this issue I literally had to uninstall the app on my phone and reinstall an old Plus Messenger version that has both tabs and proper badge counter (old because newer one implemented these same og telegram issues).

**Comment by JuDelCo** [comment] 2020-10-24 11:46
I ended moving all the busy chats into a "low priority" folder below all the others, for me is not ideal because those chats are not properly categorized, its something more like an archived folder but not quite. If there is no limit in the number of folders I would create more to categorize those chats in a low-priority version of all the categories I use, but thats not possible either.

**Comment by ilya-fedin** [comment] 2020-10-24 12:46
> wording should be changed

It shouldn't, the setting is in Notifications section that contains settings only for notification popus and tray icon (also known as notification area)

**Comment by sgon00** [comment] 2021-04-15 15:09
Sorry, but I have to +1.

**Comment by cosmicog** [comment] 2021-09-24 18:48
I ended up creating a folder named Main. It includes everything but I exclude work chats, muted chats, bots and channels.
But the badge counter of the All Chats section still shows up and this way, every chat also increase All Chats badge counter, which is not exactly the best behaviour. 
![Screenshot from 2021-09-24 21-37-56](https://user-images.githubusercontent.com/9158844/134724475-5c8ad537-fdc1-4dc1-93f2-3dfc9cffb490.png)

> It isn't specified in the description that it's only about that, so either the wording should be changed - and after that yes, mine will become a feature request - or if they keep it like that they should make it so it'll work with folders too.

I strongly support this very rational opinion.

**Comment by kass-kass** [comment] 2022-03-14 11:01
This behaviour keeps me from using the "folders" feature at all. It is confusing, and exists on all clients (web/desktop/iOS/etc). It seems like an intended feature, but makes very little sense.

Muted chats with "exlude muted" should not be included in message counters. Why are folders special and exempt from this? A counter is a counter.

Using alternative client on desktop doesn't solve this issue, because the folders sync, and insane message counters appear on my phone.

I get anxiety from counter numbers (I'm sure I'm not alone in this). If it's not 0, something needs attention. If it's 1000, the attention needed gets to insane levels.

So the "exclude muted" option is the only way for me to keep active groups and channels at all. There's no way to categorize them that doesn't bring back insane levels of stress, so they're left in a huge pile in the archive, never being read.

Seems like TG added a big feature, almost nobody started using it, so they just ignore it and move on to exciting new features, instead of improving this one and making it usable.

I get it, shiny new features bring new users. But lack of attention to existing lesser known features is sad. UX for folders is quite bad, can be improved in 1000 ways, and people would likely use them.

**Comment by cosmicog** [comment] 2022-03-14 18:20
I ended up editing my theme that is visible in my previous comment above, making that counter background grey was not enough. 
I made it (`sideBarBadgeBgMuted`) transparent for muted chats to FURTHER decrease annoyance of this bug. 

This is when there's a notification from muted chats:
[<img alt="alt_text" src="https://user-images.githubusercontent.com/9158844/158229256-3f71be95-6bbd-47e6-be07-675dbe40ee01.png" />](https://user-images.githubusercontent.com/9158844/158229256-3f71be95-6bbd-47e6-be07-675dbe40ee01.png)

And this is when there's a notification from an unmuted chat.
![Screenshot from 2022-03-14 20-20-27](https://user-images.githubusercontent.com/9158844/158229270-f1b64b56-8b67-4cfd-9d7c-b4f3976f5bba.png)

Here's the theme link if you want to try (Click on the image): [<img alt="alt_text" src="https://user-images.githubusercontent.com/9158844/158233442-a4d51364-9b8f-446b-b9a1-e001da3bb834.png" />](https://t.me/addtheme/AwesomeCosmicogDark)

@Aokromes Could you please reinspect this? We need developers to recognize this as `bug` and remove the `enhancement` tag. Because this is an information that clearly a lot of people do not want to see after disabling the "badge counter for muted chats" option in settings. This seems like the same behaviour in mobile version but that doesn't make the issue tolerable. I would open an issue in the mobile app's repository but to avoid duplicates, I would prefer a person who is more familiar to open that issue in the main repository. 

On the phone side, the badges are not even configurable like the desktop version. Our logic is simple, If I mute a chat, should it bother me with a badge every time I look at tabs in my phone too?

![Screenshot_20220314-204640_Telegram](https://user-images.githubusercontent.com/9158844/158231758-ca3e103b-1dcd-499c-bb11-69102d79ba63.jpg)

**Comment by ilya-fedin** [comment] 2022-03-14 18:24
It really works as intended. These settings are configuring only desktop notifications, tray & taskbar icon (so-called notification area). These settings have nothing to do with counters inside the window.

**Comment by RememberTheAir** [comment] 2022-03-14 18:29
@cosmicog you should open a new ticket on https://suggestions.telegram.org: it's telegram's official place for bug reporting and suggestions (the android app doesn't have github issues enabled). This issue tracker is monitored only by the developer of tdesktop and some third-party contributors which are not related to Telegram - this app's the developer can only go as far as Telegram lets him go, so this kind of suggestions that imply a change in the behavior of every official app should be brought to the platform I linked above

**Comment by cosmicog** [comment] 2022-03-17 17:13
I opened . I think everyone here cares about it: https://bugs.telegram.org/c/15572

Please go and vote then 🙃

**Comment by scarlehoff** [comment] 2022-07-14 10:15
@cosmicog I did vote for this, but I would suggest to put more keywords in the title (if you can still edit it) because if I look for something like "muted chat folders" this suggestion doesn't come up. Also, thanks for the theme. It does make it better but it is a pity that it cannot be done in the phone :(

I'm in the same boat as @kass-kass, unread counters give me anxiety so I cannot use the feature (also because there's no way to hide the `all chats` tab or to edit to make show no notifications at all).

**Comment by cosmicog** [comment] 2022-07-18 06:05
@scarlehoff It seems like I cannot edit, I tried to make the title simple, didn't know that the search function only uses titles. They now brought moving "All chats" folder and making another folder default to premium. I'll buy premium soon but sadly this feature is still not available.

**Comment by ccrowles** [comment] 2023-02-08 14:00
> I opened. I think everyone here cares about it: https://bugs.telegram.org/c/15572
> 
> Please go and vote then 🙃

I voted, but there are still only around 20 votes and so even a year after it keeps getting ignored. And now the only desktop fork that I've found that offered this feature (Kotatogram) is heavily outdated and barely usable. I really hope they'll fix it, I literally cannot use Telegram with the muted badges, it makes me so stressed.

**Comment by PizzaProgram** [comment] 2023-07-06 08:11
> I opened. I think everyone here cares about it: https://bugs.telegram.org/c/15572

+1 Thanks for opening the ticket!
Very annoying this alert-counter can not be turned off for muted chats on desktop :-(

**Comment by ccrowles** [comment] 2023-11-20 11:35
It's been 3 years and this issue hasn't been fixed yet... And Kotatogram is barely usable with not having received updates in a long while, and I can't find a valid alternative either.
So currently I find myself barely using Telegram from my pc, because I have to choose between not seeing half of the messages (messages with new features i.e. spoilers don't appear on Kotatogram) or having to deal with notification badges for chats that I do not wish to be notified of (if I install the official Telegram desktop client).

**Comment by ignatovv** [comment] 2024-04-29 09:34
Bump, It is really annoying stuff. Make it paid and all of the user will pay you for this feature. It is really frustrating to have tons of badges for muted channels 🥹🙏

**Comment by scarlehoff** [comment] 2024-09-15 09:02
Bumping it as well. Agree with the previous comment re the payment.

**Comment by john-preston** [comment] 2024-09-17 06:46
I've added a new setting "Include muted chats in folder counters" =)

**Comment by RememberTheAir** [comment] 2024-09-17 06:56
oh my god thanks a lot this is very appreciated! I hope a similar setting will come to the mobile apps too!

**Comment by scarlehoff** [comment] 2024-09-17 06:57
In mobile, Telegram X has that setting.

**Comment by ccrowles** [comment] 2024-09-17 08:38
Plus Messenger also has that feature, unfortunately it's mobile only.
Which is why we're all asking here to implement the fix in the official desktop app.

**Comment by john-preston** [comment] 2024-09-19 08:53
https://github.com/telegramdesktop/tdesktop/commit/3218c309832430ed4fbf5647d14c215d64c747fb will be in the beta

**Comment by enchained** [comment] 2024-09-20 01:27
@john-preston Thank you so much! Tested in beta, had to click through some folders for the counters to update, but it works nicely now. Less visual noise and anxiety.
Any chance "Include Channels" toggle from iOS could be added too? https://github.com/telegramdesktop/tdesktop/issues/16167

**Comment by john-preston** [comment] 2024-09-20 04:46
@enchained Not sure about that one, it's not easily done right now and that feels a bit strange to leave the unmuted channels out of the unread counter.

**Closed** 2024-09-20 04:46 UTC
Labels: enhancement, waiting for answer, WIP
