### ISSUE TITLE
Cloud draft clear message while typing

### ISSUE THREAD

**Issue by AhyaH-YHWH** [telegramdesktop/tdesktop#9928] opened 2020-12-14 17:58 UTC
It is an old bug, Also on 2.4.13 Windows

When I am typing a message, it syncs a part of message to cloud draft 
and I type a new word, my message while typing is replaced, with previous cloud draft of 5/10 seconds ago

so I have to type again, or if I am lucky Ctrl+Z bring back the part cleared by cloud draft
(my Telegram on Phone and other client is not online for hours to affect Desktop)

Expected behavior : only when I close the chat and go to Another chat, or Quit Telegram and reopen it, it calls for cloud draft to be seen in typing section
https://t.me/TelegramDesktopTalk/51460

**Comment by taha-ghadirian** [comment] 2020-12-14 18:29
Its maybe for bad internet connection.

**Comment by RememberTheAir** [comment] 2020-12-14 19:10
Yes, very well known issue, apparently fixing it is not as trivial as one might think. Duplicate of #4922

**Closed** 2020-12-14 19:14 UTC
