### ISSUE TITLE
HiDPI screens

### ISSUE THREAD

**Issue by Puntoboy** [telegramdesktop/tdesktop#1729] opened 2016-03-04 13:22 UTC
I have a Surface Pro 4 and the app works perfectly on it, however when I drag the window to my external monitor the window goes huge like 640x480 resolution. The app doesn't seem auto resize.

**Comment by v12** [comment] 2017-01-16 10:02
The problem is that the app doesn't take into account scaling factor of an active screen, so when you run it on HiDPI screen and then drag it to a usual full HD screen, it doesn't change scaling, and the app remains scaled whereas it should not.

**Comment by auchri** [comment] 2017-02-01 11:54
Duplicate of #1121

**Closed by auchri** 2017-02-01 11:54 UTC
