### ISSUE TITLE
White line at the bottom of the screen when maximized

### ISSUE THREAD

**Issue by Laiteux** [telegramdesktop/tdesktop#8746] opened 2020-10-05 03:02 UTC
### Steps to reproduce
Maximize tdesktop

### Expected behaviour
Not this

### Actual behaviour
An annoying white line appears at the bottom of my screen whenever I maximize the app.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.2 (latest and I have beta versions enabled)

**Used theme:** Night but it remains an issue no matter the theme

---

Video: https://youtu.be/LlCzqSaWcKI

**Comment by Laiteux** [comment] 2020-10-05 03:04
Additional info: This started happening only a few days ago, I never had this issue during the last year.

I believe it might be linked to an Intel driver update my computer installed, but I might be wrong.

**Comment by ilya-fedin** [comment] 2020-10-05 04:14
Yes, this is needeed to have auto-hidden taskbar working

**Comment by Laiteux** [comment] 2020-10-05 04:16
Sorry, what do you mean? I'm having the issue on my second monitor, but I only have a taskbar on my main one.

**Comment by ilya-fedin** [comment] 2020-10-05 04:20
I mean that this issue is appeared as a result of fix for #3579

**Comment by Laiteux** [comment] 2020-10-05 04:21
So as you said it is an issue, so it should get fixed right? I really hope this isn't a normal behavior and that it will get fixed because this white line really attracts my eyes everytime, especially at night

**Comment by ilya-fedin** [comment] 2020-10-05 04:24
I have no idea how to fix both issues and this issue seems to be more harmless

**Comment by ilya-fedin** [comment] 2020-10-05 05:49
Hmm, just checked in a VM and can't reproduce this
[vokoscreen-2020-10-05_09-47-43.mp4.zip](https://github.com/telegramdesktop/tdesktop/files/5325472/vokoscreen-2020-10-05_09-47-43.mp4.zip)

**Comment by Laiteux** [comment] 2020-10-05 05:51
Hmm, interesting..

Quoting myself:
> I believe it might be linked to an Intel driver update my computer installed, but I might be wrong.

**Comment by ilya-fedin** [comment] 2020-10-05 06:33
Hmm, I started a test build: https://github.com/ilya-fedin/tdesktop/actions/runs/288854820
It should build in 30 mintues, then you can download the artifact.

**Comment by ilya-fedin** [comment] 2020-10-05 07:16
It is built

**Comment by Laiteux** [comment] 2020-10-05 07:26
Sorry, could you please download this file and upload it to mega or something faster than GitHub? I am completely unable to reach more than 10 MB downloaded with my wifi and will probably never be able to fully download this file.

Also, how does an artifact work? I have no idea. Will it just contain Telegram.exe as usually or are there extra steps? Please let me know.

Thank you!

**Comment by ilya-fedin** [comment] 2020-10-05 07:38
> Also, how does an artifact work?

It contain a Telegram.exe that will create data folder in the same directory where the binary is placed. This is debug build, so it will be a way slower.

> Sorry, could you please download this file and upload it to mega or something faster than GitHub?

https://drive.google.com/file/d/1yxsJYJGMEuXSJdIGvfbqM0HfAnj0Wi1D/view?usp=sharing

**Comment by Laiteux** [comment] 2020-10-05 07:44
I can confirm that using your build, the issue is fixed.

**Closed** 2020-10-05 10:50 UTC
Labels: bug
