### ISSUE TITLE
Client stops responding to mouse wheel scrolling

### ISSUE THREAD

**Issue by shentino** [telegramdesktop/tdesktop#3896] opened 2017-09-15 04:43 UTC
### Steps to reproduce
1.  Start it
2.  Let it run for a good while
3.  Try to use the mouse wheel to scroll one of the two panes

### Expected behaviour
The pane (conversation and/or list  of chats) should scroll when you use the mouse wheel

### Actual behaviour
It scrolls at first, but later gets "stuck" and quits responding to the mouse wheel

### Configuration
Gentoo Linux, kernel version 4.13

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
Whatever the default is, I haven't changed it

**Comment by chris13524** [comment] 2018-01-28 20:29
Having a similar issue here. Scroll works fine in other applications. Closing and reopening the Telegram window doesn't help. The only thing that fixes it is restarting Telegram entirely.

**Comment by toshokan** [comment] 2018-04-22 02:39
I'm seeing the same issue. Also on Gentoo GNU/Linux. It seems to happen after the system resumes from suspend.

**Comment by fotonmoton** [comment] 2018-05-01 08:42
Same here. Possibly duplicate of #2734

**Comment by c0rp-aubakirov** [comment] 2018-09-22 07:44
Same on arch, Telegram 1.3.14

**Comment by mikserc** [comment] 2018-11-29 08:07
Same on Ubuntu 18.04.1

**Comment by hansbogert** [comment] 2019-04-04 10:28
hate to add a confirm post, but this isn't getting any prio.
xubuntu with awesomeWM. Though I saw it under vanilla ubuntu 18.04 as well.

**Comment by gorghino** [comment] 2019-04-14 10:45
I can confirm this bug on elementaryOS 5.0 (Ubuntu 18) and telegram 1.6.7
Kernel: Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Aokromes** [comment] 2019-05-14 16:39
https://github.com/telegramdesktop/tdesktop/issues/3859 ?

**Closed** 2019-08-28 13:56 UTC

**Comment by darksun27** [comment] 2019-09-04 08:56
Same problem with Elementary OS running Ubuntu 18.04. Telegram Version: 1.2.17

**Comment by jlemonde** [comment] 2019-10-20 20:18
Same bug for me on Ubuntu 19.04 and with Telegram 1.8.15

**Comment by carpajr** [comment] 2020-04-14 14:44
The same issue is noted in Elementary OS running Ubuntu 18.04. Telegram Version: 2.0.1
The scrolling works for some time but stops.
