### ISSUE TITLE
[BUG] 3.6.3beta media viewer flickers between displays

### ISSUE THREAD

**Issue by atis** [telegramdesktop/tdesktop#24335] opened 2022-04-14 16:38 UTC
### Steps to reproduce

1. Open chat
2. Click on image

### Expected behaviour

Media shows on the same screen, where TG app is

### Actual behaviour

Media flickers between screens

### Operating system

Ubuntu 16.04 Mate Desktop

### Version of Telegram Desktop

3.6.3 beta

### Installation source

Static binary from official website

**Comment by atis** [comment] 2022-04-14 17:46
Issue does not happen, if Telegram window is moved to other display

Example below:

https://user-images.githubusercontent.com/1108226/163446003-2e14f3d1-862e-4caa-a45a-3f9b171db129.mp4

**Comment by ilya-fedin** [comment] 2022-04-15 02:27
can you enable debug logs, reproduce the bug and paste all the lines with `Viewer Pos` here?
You can enable debug logs by typing `debugmode` in settings blidnly, you can find the logs by typing `viewlogs`. The debug logs will be in DebugLogs subfolder splitted by every 15 minutes.

**Comment by atis** [comment] 2022-04-15 10:30
result of grep -F "Viewer Pos"

[log.txt](https://github.com/telegramdesktop/tdesktop/files/8495441/log.txt)

**Comment by ilya-fedin** [comment] 2022-04-15 10:35
What's the screen main window on? 0, 150, 1680, 1050 or 1680, 0, 1920, 1200?

**Comment by atis** [comment] 2022-04-15 11:35
TG window on 1680x1050
Other screen (1920x1200) is set as primary

**Comment by ilya-fedin** [comment] 2022-04-15 11:43
So it seems your window manager tries to move the media viewer to the primary screen, tdesktop reverts it back and then it all repeats endlessly. Before this update media viewer always was on the primary screen I guess?

**Comment by atis** [comment] 2022-04-15 11:52
Before update, media viewer was on same screen as TG

**Comment by ilya-fedin** [comment] 2022-04-15 11:53
It's weird, then... Why your window manager fights with tdesktop though? Can you update to actual OS (Ubuntu MATE 20.04)?

**Comment by TechnicalFox** [comment] 2022-04-17 19:33
Having seemingly related window location issues on the latest version 3.7.0, reverted to 3.6.1 and everything working fine. Running Debian 11 on 5.17 kernel, cinnamon desktop env. Since the update the media viewer opens on my main monitor with desktop notifications going to the main monitor as well. This is while tg is docked to the bottom of an aux monitor. When I undock it, the media viewer will display on that screen, but it's cut off, seemingly rendering off screen (aux monitor in question is in a vertical config).

**Comment by ttp** [comment] 2022-04-18 11:25
Have the same issue on ubuntu unity, Telegram 3.7.0. No issue in 3.6.1.

**Comment by ilya-fedin** [comment] 2022-04-18 11:47
It's really the time to stop using abandoned buggy Unity. Qt removes the workarounds it had for Unity since it (unity) was implementing all the standards in bad waya, so you will see more & more bugs with new versions.

**Comment by ttp** [comment] 2022-04-18 12:00
Confirm, no issue in default gnome shell env. Thanks @ilya-fedin

**Comment by atis** [comment] 2022-05-02 11:38
Issue still persists, several updates later
I haven't had time to update my OS, but should you reject issue just because i'm on older OS (which is still in support btw)

**Comment by Aokromes** [comment] 2022-05-02 11:47
> Issue still persists, several updates later I haven't had time to update my OS, but should you reject issue just because i'm on older OS (which is still in support btw)

Ubuntu Linux 16.04 LTS reached the end of its five-year LTS window on April 30th 2021 and is no longer supported by its vendor, Canonical except through a paid annual Extended Security Maintenance (ESM).

nope, it's eol.

**Closed by Aokromes** 2022-05-02 11:47 UTC
Labels: bug

**Comment by ilya-fedin** [comment] 2022-05-02 23:43
> which is still in support btw

If you say it's still in support, can you report the bug to it? It seems to be a Unity bug.

**Comment by ilya-fedin** [comment] 2022-05-02 23:46
> which is still in support btw

I don't see such a bug on actual version of MATE, so if you say it's still in support, they should be able to backport the fix if you report the bug to them?

**Comment by atis** [comment] 2022-05-04 12:12
Fixed in 3.7.4 beta
