### ISSUE TITLE
[Feature request] Choose a different background by user (no more wrong chat!)

### ISSUE THREAD

**Issue by intrd** [telegramdesktop/tdesktop#587] opened 2015-03-22 08:21 UTC
Why?
I bet everyone here already typed in the wrong chat.. this could be minimized if you can choose a different background by user

**Comment by Arttse** [comment] 2015-03-23 10:05
Agree. Necessary feature

**Comment by cobalto** [comment] 2015-03-24 21:17
lol all the time. Yes, I agree with it.

**Comment by Aokromes** [comment] 2015-03-28 13:16
+1 to add this feature.

**Comment by Aokromes** [comment] 2015-03-29 08:37
BTW duplicate of #523

**Comment by AhmedDjoudi** [comment] 2015-03-29 23:15
True, and also the possibility to pin some conversations so that they don't move when you receive messages.

+1

**Comment by intrd** [comment] 2015-08-02 07:06
+1 ..

**Closed** 2015-08-14 23:12 UTC

**Comment by yashpalgoyal1304** [comment] 2020-07-27 06:52
label: duplicate
