### ISSUE TITLE
[Linux] App crashes after viewing some type of media (GIF, pic , video) 

### ISSUE THREAD

**Issue by AliSawari** [telegramdesktop/tdesktop#24076] opened 2022-02-14 16:52 UTC
### Steps to reproduce

1. Open Telegram Desktop
2. Scroll down to different types of GIFs, Pictures and Videos 

### Expected behaviour

It should normally open many types of media without any issue

### Actual behaviour

it crashes exactly when it reaches the mentioned types of media. I suspect it has to do with streams, because the log says something like that.
I will provide more information if I can get anything from `gdb` or `journalctl`.

### Operating system

Ubuntu 20.04.3 LTS focal on GNOME Shell 3.36.9

### Version of Telegram Desktop

3.5.2

### Installation source

Static binary from official website

### Logs

```shell
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
Feb 14 19:30:54 ali org.gnome.Nautilus[42263]: Invalid return value 0 for stream protocol
```

**Comment by Aokromes** [comment] 2022-02-14 18:14
https://github.com/telegramdesktop/tdesktop/issues/24073 ?

**Comment by ilya-fedin** [comment] 2022-02-14 20:43
Provide a crash report tag

**Comment by AliSawari** [comment] 2022-02-14 21:29
@Aokromes its not that case, my window immediately closes and the whole telegram app crashes and forcibly exits, and I need to restart it again. my `journalctl` has different logs as well. my `dmesg` logs keep saying something about my wifi driver , I will include it here if it could be the cause of this issue by any chance. i had to install my wifi driver through `dkms` because it had no official driver support from linux kernel

`[Feb14 20:06] rtw_8821ce 0000:04:00.0: failed to send h2c command`

**Comment by ilya-fedin** [comment] 2022-02-14 21:56
@AliSawari crash report tag is needed anyway

**Comment by AliSawari** [comment] 2022-02-14 22:41
@ilya-fedin do I need to provide more crash reports? if yes what type of logs do I need?
Note that **Telegram crashes immediately whenever it reaches a certain message**

I have run the app in the terminal. here's the logs after the crash: 

```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
[libvpx-vp9 @ 0x7fe48db60a00] v1.11.0
[libvpx-vp9 @ 0x7fe48db60a00] v1.11.0
[libvpx-vp9 @ 0x7fe48db60f00] v1.11.0
[libvpx-vp9 @ 0x7fe48db60f00] v1.11.0
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
```

**Comment by ilya-fedin** [comment] 2022-02-14 22:43
> do I need to provide more crash reports?

You need to provide the crash report tag crash reporter tells you before you send a crash report

**Comment by AliSawari** [comment] 2022-02-15 12:09
> You need to provide the crash report tag crash reporter tells you before you send a crash report
what crash reporter? please be more specific. the program does not prompt me for any crash reports to send. it only runs and closes. I have nothing but the logs i have already supplied.

**Comment by ilya-fedin** [comment] 2022-02-15 14:05
> the program does not prompt me for any crash reports to send

Try to enable "Install beta versions" option in Advanced settings

**Comment by AliSawari** [comment] 2022-02-16 08:30
> Try to enable "Install beta versions" option in Advanced settings

not useful because there's no beta versions at this moment. I guess a fix PR should be created for this bug and a new minor update should be released. this is a known bug

**Comment by ilya-fedin** [comment] 2022-02-16 10:03
> not useful because there's no beta versions at this moment.

You don't need to install a beta version. You need to activate that option in order to get crash reporter dialog.

> this is a known bug

How is that?

**Comment by AliSawari** [comment] 2022-02-16 10:16
@ilya-fedin  Thank you for this information, here's the Crash Report
```
ApiId: 2040
Assertion: "index > 0 && index < 10" text_utilities.cpp:46
Binary: Telegram
Launched: 16.02.2022 11:23:49
OpenGL: Disabled
OpenGL Renderer: [not-initialized]
Platform: Linux
UserTag: affbfed9da481b40
Username: MrGh0st
Version: 3005002

Caught signal 6 (SIGABRT) in thread 140082538775040

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 140082538775040
Minidump: /home/ali/.local/share/TelegramDesktop/tdata/dumps/e6950c70-6521-4977-e22e258e-f321939b.dmp

Backtrace omitted.
```

> this is a known bug

I mean that it has been mentioned more than one time (#24077), this could mean it is an ongoing issue

Do I also need to provide the dump file in `/.local/share/TelegramDesktop/tdata/dumps/` as well ?

**Comment by AliSawari** [comment] 2022-02-16 10:26
> Are you sure you have done actions for this issue

Yes I have opened the certain group chat that caused the issue, it does not appear on other normal chat or private chat. maybe it does I need to re-test with the exact same type of media that caused the issue in a private chat with someone else to see if it holds true in a private chat

**Comment by ilya-fedin** [comment] 2022-02-16 11:36
Ah, I thought app crashes when you open a media viewer. So, apparently, it's a duplicate of #24077

**Closed** 2022-02-16 11:37 UTC
Labels: bug

**Comment by AliSawari** [comment] 2022-02-16 12:10
@ilya-fedin  thank you for reviewing this. I'll make sure to test different types of media in different chats for better debugging.

**Comment by ashtonx** [comment] 2022-02-19 14:22
```
Operating System: Arch Linux
KDE Plasma Version: 5.24.1
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.16.10-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-3570K CPU @ 3.40GHz
Memory: 15,6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 970/PCIe/SSE2
```
telegram version:
`telegram-desktop 3.5.2-1`

1. When switching to chat telegram desktop app freezes.
2. No issue on separate dm that contained 2 photos
3. Only image i've seen on that chat was preview from reddit link (on phone at least)
4. desktop History doesn't render past last msg received.

logs bassically spam this line
`telegram-desktop[10019]: qt.svg: Error while inflating gzip file: SVG format check failed`

5. managed to 'fix' it by cleaning chat history..
