### ISSUE TITLE
Favorite/urgent messages in contact info or message

### ISSUE THREAD

**Issue by moookino** [telegramdesktop/tdesktop#1806] opened 2016-03-19 16:05 UTC
Feature to pin favorite or urgent messages in chat and able to list them in contact info in special "favorite messages" cathegory

Sometimes have to save urgent messages somewhere, because not able to find them in future, it will be nice to have vk.com's like feature to star a message. Thank you

**Comment by auchri** [comment] 2016-03-19 19:01
Duplicate of #1312

**Closed by auchri** 2016-03-19 19:01 UTC
