### ISSUE TITLE
player crash after other software using ffmpeg

### ISSUE THREAD

**Issue by TohidHeshmati** [telegramdesktop/tdesktop#10097] opened 2021-01-10 10:56 UTC
### Steps to reproduce
1. open telegram on a linux maschine such as Ubuntu for example and play a music. jump forward and backward.
2. open VLC player (or any videoplayer using ffmpeg library) and play something with
3. go to telegram and try to do first step once again. it will consider music files as not playable in the app after moving forward.

### Expected behaviour
it is supposed to play songs and be able to move forward and backward after using other applications

### Actual behaviour
crashing player after using other players.

### Configuration
**Operating system:** Linux Ubuntu

**Version of Telegram Desktop:** any version

**Installation source (Linux Only)** snap

**Used theme**: dark

**Comment by Aokromes** [comment] 2021-01-10 13:36
plz try on 2.5.5

**Comment by ilya-fedin** [comment] 2021-01-10 14:34
> any version

Please specify exactly version you're using

**Comment by ilya-fedin** [comment] 2021-01-10 14:53
> plz try on 2.5.5

snap doesn't have beta releases due to #9979

**Comment by TohidHeshmati** [comment] 2021-01-10 23:36
I am on 2.5.1 but this has been the case in previous versions as well.

**Comment by ilya-fedin** [comment] 2021-01-11 00:50
I can't reproduce, the app continues to playing just like before. I guess steps to reproduce missing something.

**Comment by ilya-fedin** [comment] 2021-01-11 02:45
I reproduced, one important step is missing: track should be downloaded, the bug won't reproduce if the track is not downloaded

**Comment by ilya-fedin** [comment] 2021-01-11 02:48
Oops, looks like confused between issues

**Comment by ilya-fedin** [comment] 2021-01-11 06:14
Seems to be a duplicate of #10040

**Closed** 2021-01-11 06:58 UTC
Labels: waiting for answer
