### ISSUE TITLE
Telegram keeps self entering in drag and drop mode

### ISSUE THREAD

**Issue by gbschenkel** [telegramdesktop/tdesktop#16853] opened 2021-08-25 04:33 UTC
### Steps to reproduce
1. While telegram desktop is opened try listening some audios.
2. Move the focus to another window like Firefox
3. Keep using it that way

### Expected behaviour
To window stay quiet

### Actual behaviour
Telegram keep entering on drag and drop move mode, like click and hold and move the window around, but without clicking.
If I just click it exit the move mode, but sometimes it exit but the window stay transparent(like in move mode) and if I click to close the window, it create a "shadow". The shadow stay showing even though the program be closed or killed.

### Configuration
**Operating system:**
Slackware 15.0 rc1 + Plasma 5.22.4 + X11
**Version of Telegram Desktop:**
2.9.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
official .deb but repacked for Slackware
**Used theme**:
default / nightmode

**Screenshot**
![image](https://user-images.githubusercontent.com/1715069/130726630-0c116c1c-abbe-4d2b-bab8-01d4b36196f4.png)
on left is the current telegram, on the right is the shadows from previous telegram

**Comment by ilya-fedin** [comment] 2021-08-25 05:16
duplicate of #10348

**Comment by ilya-fedin** [comment] 2021-08-25 05:20
> official .deb but repacked for Slackware

But Telegram doesn't have official .deb...

**Closed** 2021-08-25 06:52 UTC

**Comment by gbschenkel** [comment] 2021-08-25 12:28
yeah, my mistake, is the tar.xz from https://telegram.org/dl/desktop/linux
