### ISSUE TITLE
[Linux] Chat scrolls to the bottom on every new message if another client marks messages as read

### ISSUE THREAD

**Issue by ValdikSS** [telegramdesktop/tdesktop#4989] opened 2018-07-16 11:46 UTC
### Steps to reproduce
1. Open crowded group chat where people write new messages frequently
2. Try to read older messages by scrolling chat window to top

### Expected behaviour
Telegram does not scroll to the bottom of the chat on every new message.

### Actual behaviour
Telegram scrolls to the bottom on every new chat message regardless of scrolling method (scrolling wheel, page up button, scroll bar), it's impossible to read older messages.

### Configuration
**Operating system:** Fedora 28

**Version of Telegram Desktop**: tested on 1.3.9 from russianfedora repository and 1.3.10 from tdesktop releases

**Used theme**: default

**Comment by ValdikSS** [comment] 2018-07-16 11:48
Version from russianfedora repository doesn't generate debug log, typing debugmode in settings does nothing. Please tell me if debug logs are necessary, I'll try to generate them with release version.

**Comment by stek29** [comment] 2018-07-19 06:55
@xvitaly DebugLogs have nothing to do with crash reporting -- and are quite useful for debugging API related issues. What's the point of disabling them?

**Comment by xvitaly** [comment] 2018-07-19 12:58
> DebugLogs have nothing to do with crash reporting -- and are quite useful for debugging API related issues. What's the point of disabling them?

Fedora has it's own crash reporter - abrt. All others must be unbundled and removed.

**Comment by john-preston** [comment] 2018-07-19 13:07
@xvitaly But why doesn't debug logs enabling work? They're not about crash reporting.

**Comment by xvitaly** [comment] 2018-07-19 13:09
> But why doesn't debug logs enabling work? They're not about crash reporting.

Debug logs works fine on Fedora. Package maintainers only removes build-in static crash reporter module. All others don't.

**Comment by ValdikSS** [comment] 2018-07-19 13:16
>Telegram logs can be found in ~/.local/share/TelegramDesktop/log.txt file.

But that's not a debug log. Could it be I do something wrong? I'm opening Telegram settings, typing "debugmode" right in the settings window, and nothing happens: no new files in `~/.local/share/TelegramDesktop/`, no additional debug text in `~/.local/share/TelegramDesktop/log.txt`.
I tried to restart Telegram after typing "debugmode", it's the same.

**Comment by john-preston** [comment] 2018-07-19 13:18
@ValdikSS Yeah, I got it. I'm just curious why it doesn't work the way it should.

**Comment by xvitaly** [comment] 2018-07-19 13:19
> But that's not a debug log. Could it be I do something wrong?

I can confirm. I think this is a bug. Previously it worked fine with same configuration.

**Comment by ValdikSS** [comment] 2018-07-31 18:39
It happens again on 1.3.10. I'll try to understand how to reproduce this bug.

**Comment by ValdikSS** [comment] 2018-10-17 21:54
The bug is reproducible 100% of the time in the last several application versions. It's reproducible in the current latest 1.4.2, too. It's not possible to read chat history in crowded chat groups. The only way is to constantly hold scroll bar and move it a bit when new message arrives, to return to history position.

**Comment by ValdikSS** [comment] 2018-10-17 22:04
I finally got it. Telegram scrolls to the bottom of the chat if there's another Telegram client which marks new messages of this chat as "read".
Is that a bug or a feature?

**Comment by john-preston** [comment] 2018-10-18 00:59
@ValdikSS Yes, this is intended.

**Comment by Pzixel** [comment] 2019-09-02 17:28
So, what's the progress on that? Facing an issue with that (which is now marked as duplicate), and really would like having it fixed.

**Comment by Pzixel** [comment] 2019-09-02 18:05
The problem is that sometimes I even cannot avoid this behavior because I cannot terminate other session where telegram is opened:

![image](https://user-images.githubusercontent.com/11201122/64129553-6a77d380-cdc5-11e9-8d85-71b79e221bf2.png)

**Comment by Aokromes** [comment] 2019-09-02 20:00
like stated, it's one security measure to stop someone who steals your account to terminate your older sessions.

https://github.com/telegramdesktop/tdesktop/issues/4989#issuecomment-430839261

**Closed by Aokromes** 2019-09-02 20:00 UTC

**Comment by Pzixel** [comment] 2019-09-02 21:33
Hmm, what? It's ok that other evil guys cannot steal my sessions, but it's not ok that it's the only way to stop being spammed.

It's a shame you consider that being a "feature". It's impossible to read a chat this way.
