### ISSUE TITLE
[macOS] Telegram Desktop opens its window after it receives focus right after closing another application

### ISSUE THREAD

**Issue by kli0rf** [telegramdesktop/tdesktop#26261] opened 2023-05-05 21:09 UTC
### Steps to reproduce

1. Open Telegram Desktop.
2. Close the window (cmd+w) of Telegram Desktop.
3. Open any other app, say app X.
4. Quit (cmd+q) the app X.

I have the box "Show tray icon" checked in the Settings -> Advanced -> System integration.

### Expected behaviour

Absolutely nothing should happen. Telegram Desktop should simply keep running in the background.

### Actual behaviour

Telegram Desktop receives focus, since it was the last app used before opening the app X, and reopens the window.

I'm sorry to bring this up again, but the original one (https://github.com/telegramdesktop/tdesktop/issues/25033), not posted by me, btw, is now locked and it somehow got wrongly marked as resolved. Well it's not.

I believe it's been five years or so to this (very annoying, btw) bug, and it's still there.

### Operating system

Catalina, Mojave

### Version of Telegram Desktop

v4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment] 2023-05-05 22:08
The issue you call as "original" is about a completely different client

**Comment by ilya-fedin** [comment] 2023-05-05 22:09
Sounds like a duplicate of #24909

**Closed** 2023-05-05 22:18 UTC
Labels: bug

**Comment by kli0rf** [comment] 2023-05-05 22:23
> The issue you call as "original" is about a completely different client

Ah, you're right. Sorry about that, i didn't notice he's using native Telegram. Anyway, the issue still persists.

**Comment by kli0rf** [comment] 2023-05-14 22:03
> Sounds like a duplicate of #24909

However, i don't think this is a duplicate. The issue you're refering to is a feature request, the one i'm talking about is obviously a bug. That doesn't happen on snap version, doesn't happen on Windows version. MacOS only.

**Comment by ilya-fedin** [comment] 2023-05-14 22:07
Topic-wise, it's a duplicate. You can't open a bug as long as the feature request is open. Sorry.
