### ISSUE TITLE
Full-screen problems on windows 10 when I use two screens (hd and full-hd)

### ISSUE THREAD

**Issue by tva94** [telegramdesktop/tdesktop#4998] opened 2018-07-18 10:46 UTC
Problem shown on next screenshot:
![-1](https://user-images.githubusercontent.com/24491769/42876877-b62b6b9e-8a90-11e8-8955-aef043cc2d07.jpg)
Also on second screen placed small part of telegram window

**Comment by d-Rickyy-b** [comment] 2018-07-18 16:57
Duplicate of #4649
TL;DR: Windows 8 Compatibility Mode fixes this for now (don't know if/when a proper fix is on the way).

**Closed** 2018-07-19 07:00 UTC

**Comment by levrik** [comment] 2018-07-25 11:34
@tva94 @d-Rickyy-b See my latest comment in https://github.com/telegramdesktop/tdesktop/issues/4649#issuecomment-407722748

**Comment by d-Rickyy-b** [comment] 2018-07-25 20:04
@levrik Thanks a lot :)
