### ISSUE TITLE
Image viewer and context menus are off-screen on hidpi gnome

### ISSUE THREAD

**Issue by tiagoad** [telegramdesktop/tdesktop#8818] opened 2020-10-13 20:08 UTC
### Steps to reproduce
1. Install Fedora 32 (gnome) on a computer with a 4K display
2. Install telegram-desktop through the rpmfusion repository (version 2.4.2 at the moment)
3. Open an image preview

### Expected behaviour
The image should be visible

### Actual behaviour
Telegram seems to think the screen is much larger, and I only see one quarter of the image, the rest being out of bounds.
If I open a context menu in the bottom of the window, it's not shifted up, so it's partially obscured.
Weirdly, if I drag the image slightly, it will pop into the right place, in the middle of the window (although the menu still looks mangled)

![](https://i.imgur.com/8IWvgIu.png)
![](https://i.imgur.com/cG76ciT.png)

### Configuration
**Operating system:**
Fedora 32

**Version of Telegram Desktop:**
2.4.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
rpmfusion

**Used theme**: Day

**Comment by ilya-fedin** [comment] 2020-10-13 22:11
Can you reproduce with official binary?

**Comment by tiagoad** [comment] 2020-10-15 08:12
> Can you reproduce with official binary?

Can't reproduce with the official binary.
I've noticed the original binary, on 100% scaling, looks very tiny, although the one that comes from rpmfusion is scaled to the proper size on 100%.

This trickery is probably what's creating the bug.

**Comment by tiagoad** [comment] 2020-10-15 08:20
On the original binary I managed to reproduce the bug by setting `QT_QPA_PLATFORM=wayland`. I assume this is being set by the packagers?

**Comment by tiagoad** [comment] 2020-10-15 09:04
I can confirm `XDG_SESSION_TYPE=x11` on the fedora binary fixes this problem.

**Comment by ilya-fedin** [comment] 2020-10-15 11:18
> I assume this is being set by the packagers?

As far as I know, Qt in Fedora (and Flatpak) is patched to use native Wayland on GNOME by default, even though Qt upstream states that their native Wayland is still incompatible with GNOME.

**Comment by ilya-fedin** [comment] 2020-11-10 12:58
Well, kde wayland guys helped me to understand that the issue is not that the image viewer is bigger, but is that due to the lack of the move api, the code to move the media viewer window to the right screen doesn't work, while window geometry is still counted for the screen it should appear on rather than for the screen it actually appears.

Unfortunately, this seems to be unfixable due to the lack of the needed API on Wayland.

**Comment by proletarius101** [comment] 2021-01-04 10:52
However after switching between images/videos, the video/image is centered correctly. Maybe there is more can be done.

**Comment by ilya-fedin** [comment] 2021-01-04 12:36
> However after switching between images/videos, the video/image is centered correctly.

Yeah, I tried to add reacting to resizeEvent and this fixes the bug when switching between images helps. Unfortunately, switching between image helps not at each viewer open and when it doesn't help, resizeEvent doesn't help as well.

**Comment by ilya-fedin** [comment] 2021-02-18 02:24
Is this still an issue with 2.5.9?

**Comment by proletarius101** [comment] 2021-02-18 03:19
No, it seems fixed now. Thx!

**Closed** 2021-02-18 08:59 UTC
Labels: 3rd party issue, wayland
