### ISSUE TITLE
"fontconfig" folder being kept created at home folder in Linux

### ISSUE THREAD

**Issue by TechnoSparks** [telegramdesktop/tdesktop#740] opened 2015-05-22 05:24 UTC
I am using Linux Mint 17.1 32 bit system with Cinnamon as desktop.

Telegram desktop seemed to create a folder "fontconfig" in Home directory in Linux. The files are exactly the same as in /path-to-telegram-binary/fontconfig
If you delete the folder, it will be recreated (along with the contents) when Telegram launches again.

Considering that the files are the same, I consider this as a bug.

**Comment by completit** [comment] 2015-05-22 08:13
Everyone running Linux has a [fontconfig](http://packages.ubuntu.com/search?keywords=fontconfig) file, it's generated by the system (generic font configuration library), so it's nothing to be scared of. :)

**Comment by TechnoSparks** [comment] 2015-05-22 08:36
I have been using Linux for 4 years now. I have never seen such of a folder. The folder will creates itself right after the time telegram's process starts. I can do a screen record for proof, though.

**Comment by ShabbyX** [comment] 2015-05-22 14:21
It's `.fontconfig` with a dot in the beginning that is normal. Telegram should actually be using that directory, rather than `fontconfig`.

**Comment by ppparadox** [comment] 2015-05-27 12:02
Duplicate of #495

**Closed** 2015-08-14 23:11 UTC
