### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by WhiteCzar** [telegramdesktop/tdesktop#17493] opened 2022-01-02 08:55 UTC
### Is your feature request related to a problem?

Currently Telegram-desktop looks very out of place on Gnome DE. The problem is exacerbated under Wayland, since there is no way to make the Telegram title bar respect the DE theme.

### Describe the solution you'd like

https://wiki.gnome.org/Initiatives/CSD/Telegram

Have you considered implementing this paradigm in Telegram? Or has it been rejected for some reason? These mockups are from 2018.

### Describe alternatives you've considered

See above.

**Comment by Aokromes** [comment] 2022-01-02 09:01
yeah that url was send before, it's duplicate of another ticket, but searching for it is a pita because near 500 results.

**Closed by Aokromes** 2022-01-02 09:01 UTC
Labels: enhancement

**Comment by Aokromes** [comment] 2022-01-02 09:07
https://github.com/telegramdesktop/tdesktop/issues/4358
