### ISSUE TITLE
Telegram Desktop snap on Ubuntu 20.04 has broken alt+tab behaviour

### ISSUE THREAD

**Issue by tomkcook** [telegramdesktop/tdesktop#7913] opened 2020-05-19 10:23 UTC
### Steps to reproduce
1. Open the Telegram Desktop client.
2. Switch to another workspace (eg Ctrl+Alt+Down) and open any other application window.
3. Alt+Tab

### Expected behaviour
Telegram window should only appear in the alt+tab window list for the workspace it is in.

### Actual behaviour
Telegram window appears as the first window in the list in all workspaces it is not open in (and at its normal position in the list for the workspace it is open in).

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.1.6

**Installation source (Linux Only)** - snap

**Used theme**: Classic

### General whinge
This is really annoying behaviour and seems to have started fairly recently.  It makes alt+tab window switching very annoyingly broken any time the telegram desktop window is open anywhere on the system.  The whole point of having multiple workspaces is so that I can compartmentalise what I've got open.

**Comment by ilya-fedin** [comment] 2020-05-19 15:26
Duplicate of #7887

**Closed** 2020-05-19 17:29 UTC
