### ISSUE TITLE
 pin on more than 5 conversations

### ISSUE THREAD

**Issue by alexis26** [telegramdesktop/tdesktop#5140] opened 2018-09-04 06:46 UTC
Hi,
it would be really nice to be able to pin on more than 5 conversations...
5 it's really too little
ty

**Comment by RememberTheAir** [comment] 2018-09-04 07:04
Duplicate of #4937 #4870 #4798 #4600 #4249 #4037 #3406 #3026 and probably more

**Closed** 2018-09-04 07:15 UTC

**Comment by alexis26** [comment] 2018-09-04 07:16
sorry for duplicate...
but if it's asked so much, maybe it's time to think about it, no? ;-)
ty for the answer

**Comment by paoletto** [comment] 2018-09-12 14:09
All the issues you linked as duplicated are closed. Can you please link an open one? OR add the explanation why they are all closed?
The hard limit is nonsense, users might want to know why the team thought it's a good idea?

**Comment by Johnnynator** [comment] 2018-09-12 14:19
@paoletto they are probably closed since this is a API issue and not a tdesktop one.

**Comment by alexis26** [comment] 2018-09-12 14:32
"probably" ... can we know if it is really that, plz
if yes, it's not a pb to open the same issue over there... I can argument
if not, paoletto is right open one or give explanation...
ty

**Comment by RememberTheAir** [comment] 2018-09-12 15:29
@alexis26 @paoletto the reason is that the API allows 5 chats at max. [TDesktop is not going to raise the limit because of platform consistency](https://github.com/telegramdesktop/tdesktop/issues/4037#issuecomment-341496759)

**Comment by alexis26** [comment] 2018-09-13 05:31
ok, thank you for your answer, that's what I'm going to do
