### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Jyusup** [telegramdesktop/tdesktop#24897] opened 2022-08-09 22:05 UTC
### Is your feature request related to a problem?

we have to make night theme by ourselves

### Describe the solution you'd like

make auto night mode from time and from theme in the system

### Describe alternatives you've considered

make auto night mode from time and from theme in the system

**Comment by ilya-fedin** [comment] 2022-08-10 05:01
Settings -> Chat settings -> Match system settings
For time-base, duplicate of #3613

**Closed** 2022-08-10 07:57 UTC
Labels: enhancement
