### ISSUE TITLE
Supergroup messages bug (?)

### ISSUE THREAD

**Issue by dem23step** [telegramdesktop/tdesktop#2065] opened 2016-05-22 19:12 UTC
### Steps to reproduce
Post something to supergroup where **nobody** is online except yours.

### Expected behaviour
Message becomes marked as unread until somebody will read it.

### Actual behaviour
Message becomes marked as read immediately after posting, but there's nobody who can read it, except me.
Is it normal behaviour? If so, why does it work in such non-obvious way (I mean, this way differs from the way used in usual groups)?

### Configuration
**Operating system:** Windows 10 Pro

**Version of Telegram Desktop:** 0.9.49

**Comment by DaFri-Nochiterov** [comment] 2016-05-22 20:58
"It's not bug, it's feature" - Telegram 
                                     :unamused:

**Comment by Gollam** [comment] 2016-05-24 10:28
duplicate of https://github.com/telegramdesktop/tdesktop/issues/1940

**Closed** 2016-05-24 10:51 UTC
