### ISSUE TITLE
[Feature request] Keep Telegram in background on Ubuntu

### ISSUE THREAD

**Issue by nplezka** [telegramdesktop/tdesktop#401] opened 2015-01-15 17:35 UTC
I really like Telegram Desktop for Linux, but I'd like to close app and see it in background (with an applet icon on system tray for example). I'm on Gnome Shell and it's not so comfortable to keep the window on.

**Comment by Aokromes** [comment] 2015-01-15 22:56
I think this is duplicate of #139

**Comment by telegramdesktop** [comment] 2015-01-16 09:21
Tray icon using libappindicator with fallback to gtk_status_icon, if libappindicator is not installed, will be added in 0.7.7. I don't know actually, will it work on your system.

**Comment by Sollex-21412** [comment] 2015-01-16 10:54
Can you please try version from my branch. It have to work on all systems which support D-Bus.

**Comment by telegramdesktop** [comment] 2015-01-16 11:12
I can try it, but I am afraid of such huge qt patch (of updating it for Qt 5.4 when moving to it). For now the deployment of 0.7.7 with libappindicator is on it's way, hope it will cover most of the cases.

**Comment by Sollex-21412** [comment] 2015-01-16 11:16
Actually, i backported some features from 5.4. and just add a static plugin to qt. It have to work in 5.4 too. May be it will help in future ).

libappindicator will cover my case at least =)

**Closed** 2015-08-14 21:48 UTC
