### ISSUE TITLE
"Use native notifications" flag is off after update

### ISSUE THREAD

**Issue by qg0** [telegramdesktop/tdesktop#7284] opened 2020-02-25 13:16 UTC
Telegram 1.9.18 beta
Linux OpenSUSE Tumbleweed
KDE

"Use native notifications" flag is off after the telegram has been updated. It was in the last minor versions like updating from 1.9.16 to 1.9.17, from 1.9.17 to 1.9.18 beta.

**Comment by komorebithrowsatable** [comment] 2020-02-25 23:02
It's also not available on my 1.9.14 (stable, installed from flathub). 
Operating System: KDE neon 5.18
KDE Plasma Version: 5.18.1
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1

Maybe the issue is KDE specific.

**Comment by ilya-fedin** [comment] 2020-02-26 01:39
> It's also not available

Not available or off? If second, #7279.

**Comment by qg0** [comment] 2020-02-26 03:27
In my case it was available, but just turned off. It was like a reset (log off) cuz I needed to write the code from sms.

**Comment by ilya-fedin** [comment] 2020-02-26 03:28
Then it is duplicate of #7279

**Closed** 2020-02-26 04:07 UTC
