### ISSUE TITLE
huge memory leak in work with cached images and medium leak with loading images

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#1317] opened 2015-11-22 19:52 UTC
easy to reproduce

medium leak
1) clear cache
2) close telegram
3) run again
4) open group chat with 1000-1500 posted images
5) open task manager to see memory consumption
6) scroll up to earlier messages

huge leak
1) just close telegram after previous experiment (if it don't crashed lol) without clear cache
2) open group chat with 1000-1500 posted images
3) open task manager to see memory consumption
4) scroll up to earlier messages

i recorded video https://files.fm/u/ynvqtnms

**Comment by slaveriq** [comment] 2016-01-22 13:55
I can confirm this behaviour on telegram 0.9.19 on Linux.

**Comment by stpnk** [comment] 2016-04-27 10:23
I can confirm too. I use Telegram 0.9.42 for Linux 64 bit downloaded from official site. But I also got confirmation from few people who uses it on Windows.

Open chat with stickers, images and other attached media files. Scroll to beginning of the chat and then to the end. Repeat several times and you could notice memory leak.

**Comment by kokoko3k** [comment] 2016-07-18 17:57
I left Telegram-desktop opened on my always-on archlinux machine for about 10 days without even touching that machine.
When i was back ,telegram was using about 2.5GB of ram and i repeat, nobody even used it.

**Comment by Aokromes** [comment] 2016-11-08 09:58
I used valgrind few months ago, but the amount of errors related to QT was a pain to debug properly.

**Comment by infoman** [comment] 2017-05-04 19:00
Telegram Desktop slowly increases it's memory usage and never seems to clear it, until restarted manually or eaten by OOM Killer.

**Comment by tdesktop-closer** [comment] 2018-06-01 18:26
Hey there!

We're automatically closing this issue since there was no activity in this issue since 392 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

<sub>(Please note that this is an [automated](https://github.com/auchri/github_auto_closer) comment.)</sub>

**Comment by f242** [comment] 2018-06-01 18:33
problem is still present

**Comment by Darkcacok** [comment] 2018-12-14 15:07
When are you fix this?

**Comment by john-preston** [comment] 2018-12-14 15:08
@Darkcacok It should be better in the latest versions.

**Comment by Darkcacok** [comment] 2018-12-14 15:09
Already 1.5 version and this bug is still not fixed on Linux. I do not know how it works in Windows, but Windows does not have the same problem

**Comment by john-preston** [comment] 2018-12-14 15:11
@Darkcacok Linux and Windows versions work the same way with images and caching, so there should not be any major difference. Maybe you test them differently?

**Comment by Darkcacok** [comment] 2018-12-14 15:14
I open the task manager on Windows and scroll through the chat. When the telegram begins to use more than 100 megabytes, the memory is reset to 50-60 megabytes. On Linux, memory does not even decrease, but only increases. What's the problem and how it is work?

**Comment by john-preston** [comment] 2018-12-14 15:16
@Darkcacok Do you try 1.5.2 on Windows? It should allow up to 128 MB of image data in memory before it starts clearing, both on Windows and on Linux.

**Comment by Darkcacok** [comment] 2018-12-14 15:35
Ok. I tried version 1.5.2 on windows. Now the memory is kept at around 200 megabytes, but it is still slowly increasing. I managed to reach 230-240 megabytes. On Linux, memory cleanup does not work at all.
![image](https://user-images.githubusercontent.com/28192607/50012199-71f91180-ffd7-11e8-8fe7-ce259258e8c0.png)

**Comment by Darkcacok** [comment] 2018-12-14 15:36
![image](https://user-images.githubusercontent.com/28192607/50012255-9bb23880-ffd7-11e8-88a9-53851e0757be.png)

**Comment by Darkcacok** [comment] 2018-12-14 15:49
So why on Linux it does not work?

**Comment by Darkcacok** [comment] 2018-12-14 16:07
I'm so sorry. Memory is really cleared on Linux. But not as aggressive as on Windows. I was not able to increase my memory usage by more than 1 gigabyte. Good work. But you can do better.
![image](https://user-images.githubusercontent.com/28192607/50013900-e03fd300-ffdb-11e8-8de0-13242a7a9ca0.png)

**Comment by danielleontiev** [comment] 2019-03-14 09:07
1.5.15 on Linux. Tdesktop use to eat 50-60 mb on startup but after ~24 hours memory usage increases up to 300 mb

**Comment by kokoko3k** [comment] 2019-03-14 09:35
Man, this issue is opened for more than 3 years now.
I dubt it would ever been solved, so i just made a script that restarts it every hour.

**Comment by danielleontiev** [comment] 2019-03-14 09:58
@kokoko3k oh, it's really straightforward solution thank you.

**Comment by danielleontiev** [comment] 2019-03-14 10:00
But it's sad that the memory leaking is not in the priority for developers. Where are the benefits of native app? It uses RAM as Electron

**Comment by Aokromes** [comment] 2019-03-14 10:05
@danielleontiev that's false @john-preston already fixed few big memory leaks, now it's really hard to use >1GB of ram

**Comment by danielleontiev** [comment] 2019-03-14 10:10
@Aokromes I've seen [this](https://imgur.com/a/1G0hPGW) just now. Yes, maybe 1Gb is unreachable but 400 Mb is still too much

**Comment by amosbird** [comment] 2019-03-25 07:32
I've opened tdesktop on linux for a month and it consumes 15GB memory. It still has some memory leak issues under the hood.

**Comment by Aokromes** [comment] 2019-10-03 17:55
In case someone knows how to fix, debug build 1.8.13 running under ubuntu linux x64

https://gist.github.com/37b7ee627100c703518b6586a1ed9713

**Comment by Aokromes** [comment] 2019-10-07 15:32
a sample of how they can be fixed:
https://github.com/TrinityCore/TrinityCore/commit/2050a36b58ba25010bc7a786861f2c3c58aeda18

**Comment by ab123321** [comment] 2019-12-19 16:55
![Screenshot_20191219_092636](https://user-images.githubusercontent.com/16152056/71192445-58993e00-2299-11ea-9f62-60dbd1fd6476.png)
Left my PC on for night and got this beauty today's morning :face_with_head_bandage:

**Comment by indvd00m** [comment] 2020-01-22 09:09
After updating from version 1.9.3 to 1.9.5 my telegram app consumes ~130 MB of RAM instead of ~3 GB on 1.9.3.

**Comment by indvd00m** [comment] 2020-01-22 09:12
Starting of application require 1-2 sec now vs ~10 seconds on 1.9.3.

**Comment by Aokromes** [comment] 2020-01-22 09:15
maybe fixed by https://github.com/telegramdesktop/tdesktop/commit/5f5d5629f8e36f4eb6f9c478eb1b76a4cdb08b17

**Closed by Aokromes** 2020-01-22 09:15 UTC
Labels: bug, help wanted

**Comment by MBkkt** [comment] 2020-03-09 23:12
> maybe fixed by [5f5d562](https://github.com/telegramdesktop/tdesktop/commit/5f5d5629f8e36f4eb6f9c478eb1b76a4cdb08b17)

I think this only works for "GIF". What about the photo?

**Comment by ImNexus** [comment] 2020-04-03 06:25
Sorry my "English".

2.0.1 version telegram
Mac OS High Sierra 10.13.6 (17G65)

30 min usage:
![image](https://user-images.githubusercontent.com/8022567/78329727-1d422700-758b-11ea-802c-2dc37eba8080.png)

I off in settings:
- smiles, animations, autoload all files/images

I clear cache

Restart telegram

Slow scroll messages - high load RAM (Unlimited. RAM not clear. Sometimes, 30 min usage telegram = 10Gb RAM).

Video - https://cloud.mail.ru/public/5ie4/5MgambzAK

**Comment by ImNexus** [comment] 2020-04-16 15:29
up?
