### ISSUE TITLE
Feature Request: Add shortcut to Ubuntu 15.04 unity menus

### ISSUE THREAD

**Issue by frodus** [telegramdesktop/tdesktop#1142] opened 2015-09-30 11:38 UTC
In Ubuntu 15.04 64bit, I can not find any way to launch Telegram other then manualy find the executable in /opt/Telegram/Telegram

I request for a shortcut to automaticlly be added to Ubuntu's standard launcher. Or at least be able to type "telegram" in a terminal to start telegram.

**Comment by rmbleeker** [comment] 2015-10-02 16:40
See #306 #760 #933 #1057

**Comment by auchri** [comment] 2015-10-03 20:30
So it's a duplicate of #1057 I think

**Closed by auchri** 2015-10-03 20:30 UTC
