### ISSUE TITLE
Feature Request: Chat Profiles

### ISSUE THREAD

**Issue by DanielRios549** [telegramdesktop/tdesktop#4461] opened 2018-03-04 04:15 UTC
I use Telegram everytime and now, that I'm member in very many groups, it's too hard to find them, I think that a feature of Profiles (some kind of filtering) is a good one to add in Telegram.

### Steps to reproduce
1. Select a chat/group/channel and select the option "Add to Profile".
2. The existent profiles, will be shown in the list, and a option to create a new one is shown on the top.

### Expected behaviour
Separate chats in profiles, for exemple, I have 10 groups about technology, I add them in a profile called technology, and when I select this profile, only these groups are shown on left panel, more easier to find them.

### Actual behaviour
All the chats/groups/channels are shown on left panel, only with pinned ones or with unread messages on the top.

### Configuration
It's a feature request for all operation systems.

**Version of Telegram Desktop:**
1.2.6

**Comment by RememberTheAir** [comment] 2018-03-04 13:16
Duplicate of #1107

**Closed** 2018-03-04 13:57 UTC

**Comment by DanielRios549** [comment] 2018-03-05 22:13
It's something similar to this I want, tanks
