### ISSUE TITLE
[Feature Request] Highlight Text while using the search function

### ISSUE THREAD

**Issue by telegramsearch** [telegramdesktop/tdesktop#8408] opened 2020-08-10 11:57 UTC
When you use telegram for desktop, you can search with ctrl+f but it doesnt highlight the searched text, it just jumps to the message instead. It should also highlight the searched text in the message. Just like ctrl+f would do it in Chrome or Firefox.

**Comment by RememberTheAir** [comment] 2020-08-10 13:38
Duplicate of #7177

**Closed** 2020-08-10 14:22 UTC
