### ISSUE TITLE
Context Menu disappears on bottom half of vertical monitor (3.7)

### ISSUE THREAD

**Issue by caraka** [telegramdesktop/tdesktop#24396] opened 2022-04-19 19:04 UTC
### Steps to reproduce

1) move tdesktop to straddle the midline of a vertical (portrait mode) monitor.
2) right click anywhere below the midline of the monitor to open context menu - it fails
3) right click anywhere above the midline of the monitor to open context menu - it opens normally
4) move tdesktop to the top half of the monitor and context menu works everywhere.
5) move tdesktop to the bottom half of the monitor and context menu fails everywhere.

### Expected behaviour

I expect the context menu to appear anywhere on any monitor

### Actual behaviour

The context menu does not appear on the lower half of a vertical (portrait mode) monitor. This appears to be a regression in the 3.7 client, as it only started happening after a very recent update. (I normally park tdeskptop on the bottom half of my vertical monitor, so it's a recent regression)

### Operating system

Ubuntu Focal, default gnome desktop, vanilla setup

### Version of Telegram Desktop

3.7

### Installation source

Static binary from official website

**Comment by einheitsviktor** [comment] 2022-04-19 19:44
Same here on my vertical monitors. It started after the recent update to version 3.7.

Furthermore, videos and images are mostly not displayed centered. You have to click on them several times until it is correctly adjusted to the vertical monitor.

It gives the impression that the media content is aligned to the horizontal monitor and then displayed cropped.

**Comment by ilya-fedin** [comment] 2022-04-20 04:09
I don't think we need a separate issue about that, so let that be a duplicate of #24218

**Closed** 2022-04-20 05:24 UTC
Labels: bug

**Comment by GraithTiger** [comment] 2022-04-23 05:17
I'm having the same issue as @caraka here. Context menu only shows up on my vertical monitor if it's on the top half of the screen. This is a separate issue from #24218, which doesn't occur on my system.

# Platform:
Arch Linux 5.17.4
KDE Plasma 5.24.4
Telegram Desktop v3.7.1

**Comment by ilya-fedin** [comment] 2022-04-23 05:48
@GraithTiger are you using official binary from https://desktop.telegram.org?

**Comment by GraithTiger** [comment] 2022-04-23 18:50
The issue occurs on the Arch Linux official package. I'm not seeing the issue with the binary.

**Comment by ilya-fedin** [comment] 2022-04-23 21:22
Use the official binary, then
