### ISSUE TITLE
Telegram may sometimes fail to release screensaver inhibits

### ISSUE THREAD

**Issue by gentoo-root** [telegramdesktop/tdesktop#26897] opened 2023-10-05 18:20 UTC
### Steps to reproduce

Unfortunately, steps to reproduce are unknown. I'll update if I find out more details.

### Expected behaviour

When a user opens a video, a screensaver inhibit is registered. After closing the video Telegram should release the inhibit.

### Actual behaviour

Inhibits are not always released. I ended up in a situation where Telegram held 5 inhibits but no videos or chats were open. The inhibits were not released after closing the Telegram window (minimizing to the tray). I could only release the inhibits by closing and restarting Telegram.

The command I used:

```
busctl --user -j call org.gnome.SessionManager /org/gnome/SessionManager org.gnome.SessionManager GetInhibitors | jq -r '.data[0][]' | while read -r obj; do
	busctl --user call org.gnome.SessionManager "$obj" org.gnome.SessionManager.Inhibitor GetAppId
done
```

printed:

```
s "org.telegram.desktop"
s "org.telegram.desktop"
s "org.telegram.desktop"
s "org.telegram.desktop"
s "org.telegram.desktop"
```

### Operating system

Arch Linux, GNOME 44.5

### Version of Telegram Desktop

4.10.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment] 2023-10-11 21:10
> Unfortunately, steps to reproduce are unknown. I'll update if I find out more details.

Marking as can't reproduce accordingly

**Closed** 2024-01-28 00:19 UTC
Labels: bug, cant reproduce

**Comment by ilya-fedin** [comment] 2024-02-12 19:15
The inhibitors are made even for music, so maybe you're reporting intended inhibitors?

**Comment by ilya-fedin** [comment] 2024-02-12 19:47
> I understand I should see an inhibitor when a media viewer, a video/audio call or a live stream is open

or playing a music file/voice message

**Comment by ilya-fedin** [comment] 2024-02-12 20:15
> then I come back, and it's not auto-locked

Ah, music/voice message should inhibit suspend but not locking. Although it all goes through multiple (third party) abstractions and funny things may occur at any of them...

**Comment by ilya-fedin** [comment] 2024-02-12 20:24
Honestly, I have no idea whether this matters. I know only what happens on tdesktop level (and it's not aware of such settings) but I have no idea what happens on the other side (GNOME) when it processes tdesktop request

**Comment by ilya-fedin** [comment] 2024-02-13 18:17
Can you get descriptions for the inhibitors?
